In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame()

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df =pd.read_csv('PandasExample.csv')

In [5]:
df

,FlightID,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Month,Flight Year
0,Flight1,41972,ORD-BOS,3.9,43,0.750000,450.0,74250.0,11,2014
1,Flight2,41967,ORD-JFK,6.8,61,0.791667,375.0,61875.0,11,2014
2,Flight3,42238,ORD-EWR,2.7,72,0.708333,247.5,44797.5,8,2015
3,Flight4,41833,ORD-LAX,3.8,172,0.729167,385.0,63525.0,7,2014
4,Flight5,42135,ORD-IAH,3.0,89,0.708333,200.0,36200.0,5,2015
...,...,...,...,...,...,...,...,...,...,...
9631,Flight9632,42146,ORD-DEN,2.8,85,0.312500,300.0,54300.0,5,2015
9632,Flight9633,41818,ORD-DEN,1.6,185,0.291667,330.0,54450.0,6,2014
9633,Flight9634,42361,ORD-JFK,4.3,165,0.708333,350.0,57750.0,12,2015
9634,Flight9635,42188,ORD-MIA,2.8,201,0.833333,330.0,54450.0,7,2015
9635,Flight9636,42126,ORD-PHX,1.7,176,0.520833,250.0,41250.0,5,2015

In [6]:
df.head()

,FlightID,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Month,Flight Year
0,Flight1,41972,ORD-BOS,3.9,43,0.750000,450.0,74250.0,11,2014
1,Flight2,41967,ORD-JFK,6.8,61,0.791667,375.0,61875.0,11,2014
2,Flight3,42238,ORD-EWR,2.7,72,0.708333,247.5,44797.5,8,2015
3,Flight4,41833,ORD-LAX,3.8,172,0.729167,385.0,63525.0,7,2014
4,Flight5,42135,ORD-IAH,3.0,89,0.708333,200.0,36200.0,5,2015

In [7]:
df.tail()

,FlightID,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Month,Flight Year
9631,Flight9632,42146,ORD-DEN,2.8,85,0.312500,300.0,54300.0,5,2015
9632,Flight9633,41818,ORD-DEN,1.6,185,0.291667,330.0,54450.0,6,2014
9633,Flight9634,42361,ORD-JFK,4.3,165,0.708333,350.0,57750.0,12,2015
9634,Flight9635,42188,ORD-MIA,2.8,201,0.833333,330.0,54450.0,7,2015
9635,Flight9636,42126,ORD-PHX,1.7,176,0.520833,250.0,41250.0,5,2015

In [8]:
df.head(2)

,FlightID,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Month,Flight Year
0,Flight1,41972,ORD-BOS,3.9,43,0.750000,450.0,74250.0,11,2014
1,Flight2,41967,ORD-JFK,6.8,61,0.791667,375.0,61875.0,11,2014

In [9]:
df.tail(8)

,FlightID,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Month,Flight Year
9628,Flight9629,41725,ORD-SEA,1.8,146,0.333333,350.0,64750.0,3,2014
9629,Flight9630,42054,ORD-LGA,2.6,154,0.333333,275.0,45375.0,2,2015
9630,Flight9631,42302,ORD-BOS,1.2,155,0.770833,300.0,49500.0,10,2015
9631,Flight9632,42146,ORD-DEN,2.8,85,0.312500,300.0,54300.0,5,2015
9632,Flight9633,41818,ORD-DEN,1.6,185,0.291667,330.0,54450.0,6,2014
9633,Flight9634,42361,ORD-JFK,4.3,165,0.708333,350.0,57750.0,12,2015
9634,Flight9635,42188,ORD-MIA,2.8,201,0.833333,330.0,54450.0,7,2015
9635,Flight9636,42126,ORD-PHX,1.7,176,0.520833,250.0,41250.0,5,2015

In [10]:
df.iloc[0]

FlightID               Flight1
Date                     41972
RouteID                ORD-BOS
Departure Delay            3.9
AircraftID                  43
Scheduled Departure       0.75
Avg Ticket Price         450.0
Total Fare             74250.0
Flight Month                11
Flight Year               2014
Name: 0, dtype: object

In [11]:
df.iloc[3]

FlightID                Flight4
Date                      41833
RouteID                 ORD-LAX
Departure Delay             3.8
AircraftID                  172
Scheduled Departure    0.729167
Avg Ticket Price          385.0
Total Fare              63525.0
Flight Month                  7
Flight Year                2014
Name: 3, dtype: object

In [12]:
df.values

array([['Flight1', 41972, 'ORD-BOS', ..., 74250.0, 11, 2014],
       ['Flight2', 41967, 'ORD-JFK', ..., 61875.0, 11, 2014],
       ['Flight3', 42238, 'ORD-EWR', ..., 44797.5, 8, 2015],
       ...,
       ['Flight9634', 42361, 'ORD-JFK', ..., 57750.0, 12, 2015],
       ['Flight9635', 42188, 'ORD-MIA', ..., 54450.0, 7, 2015],
       ['Flight9636', 42126, 'ORD-PHX', ..., 41250.0, 5, 2015]],
      dtype=object)

In [13]:
df = pd.read_csv('PandasExample.csv',chunksize=2)

In [14]:
for chunk in df:
    print(chunk)

  FlightID   Date  RouteID  Departure Delay  AircraftID  Scheduled Departure  \
0  Flight1  41972  ORD-BOS              3.9          43             0.750000
1  Flight2  41967  ORD-JFK              6.8          61             0.791667

   Avg Ticket Price  Total Fare  Flight Month  Flight Year
0               450       74250            11         2014
1               375       61875            11         2014
  FlightID   Date  RouteID  Departure Delay  AircraftID  Scheduled Departure  \
2  Flight3  42238  ORD-EWR              2.7          72             0.708333
3  Flight4  41833  ORD-LAX              3.8         172             0.729167

   Avg Ticket Price  Total Fare  Flight Month  Flight Year
2             247.5     44797.5             8         2015
3             385.0     63525.0             7         2014
  FlightID   Date  RouteID  Departure Delay  AircraftID  Scheduled Departure  \
4  Flight5  42135  ORD-IAH              3.0          89             0.708333
5  Flight6  42359  ORD-CLT              3.5          91             0.479167

   Avg Ticket Price  Total Fare  Flight Month  Flight Year
4               200       36200             5         2015
5               175       32375            12         2015
  FlightID   Date  RouteID  Departure Delay  AircraftID  Scheduled Departure  \
6  Flight7  41726  ORD-DEN              1.7         138                0.625
7  Flight8  42318  ORD-DFW              2.3         131                0.750

   Avg Ticket Price  Total Fare  Flight Month  Flight Year
6               300       55500             3         2014
7               200       37000            11         2015
   FlightID   Date  RouteID  Departure Delay  AircraftID  Scheduled Departure  \
8   Flight9  41774  ORD-ATL             10.6          23             0.750000
9  Flight10  41900  ORD-CLT              2.0         169             0.291667

   Avg Ticket Price  Total Fare  Flight Month  Flight Year
8               200       37000             5         2014
9               125       20625             9         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
10  Flight11  42219  ORD-MCO              2.6         197
11  Flight12  41648  ORD-LAX              3.2         209

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
10             0.750000               275       45375             8
11             0.520833               350       57750             1

    Flight Year
10         2015
11         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
12  Flight13  42234  ORD-SFO              1.6          97
13  Flight14  41828  ORD-LAX              5.5           6

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
12             0.416667             412.5     76312.5             8
13             0.708333             385.0     71225.0             7

    Flight Year
12         2015
13         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
14  Flight15  41676  ORD-LAX              4.1         116
15  Flight16  41736  ORD-SEA              2.1         178

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
14             0.625000               350       64750             2
15             0.645833               350       57750             4

    Flight Year
14         2014
15         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
16  Flight17  41716  ORD-MCO              2.3         154
17  Flight18  42208  ORD-MSP              1.0         100

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
16             0.729167             250.0     41250.0             3
17             0.750000             126.5     23402.5             7

    Flight Year
16         2014
17         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
18  Flight19  41996  ORD-DEN              4.1           7
19  Flight20  41733  ORD-DEN              1.3         190

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
18             0.291667               420       77700            12
19             0.791667               300       49500             4

    Flight Year
18         2014
19         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
20  Flight21  42119  ORD-DFW              1.5          63
21  Flight22  41723  ORD-BOS              1.6         194

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
20                0.750               200       36200             4
21                0.375               300       49500             3

    Flight Year
20         2015
21         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
22  Flight23  41954  ORD-LAX              5.2         137
23  Flight24  41845  ORD-PHX              1.6          54

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
22             0.291667               350       64750            11
23             0.708333               275       45375             7

    Flight Year
22         2014
23         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
24  Flight25  41824  ORD-CLT              2.0         166
25  Flight26  41999  ORD-LGA              5.6          26

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
24             0.583333             137.5     22687.5             7
25             0.458333             385.0     71225.0            12

    Flight Year
24         2014
25         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
26  Flight27  41823  ORD-IAH              0.8         204
27  Flight28  41869  ORD-FLL              1.6          71

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
26             0.791667               220       36300             7
27             0.687500               330       59730             8

    Flight Year
26         2014
27         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
28  Flight29  41818  ORD-ATL              7.3         149
29  Flight30  42290  ORD-MCO              2.2         123

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
28             0.437500               220       40700             6
29             0.770833               250       46250            10

    Flight Year
28         2014
29         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
30  Flight31  42045  ORD-LAX              4.5         172
31  Flight32  42361  ORD-DEN              3.8          11

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
30             0.708333               350       57750             2
31             0.750000               420       77700            12

    Flight Year
30         2015
31         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
32  Flight33  42288  ORD-SFO              1.7         108
33  Flight34  41695  ORD-MCO              1.2          74

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
32             0.500000               375       69375            10
33             0.666667               250       45250             2

    Flight Year
32         2015
33         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
34  Flight35  42103  ORD-BOS              2.9          83
35  Flight36  42300  ORD-JFK              1.7         141

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
34             0.333333               300       54300             4
35             0.687500               250       46250            10

    Flight Year
34         2015
35         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
36  Flight37  42316  ORD-DFW              1.7          80
37  Flight38  41822  ORD-EWR              1.8          20

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
36             0.458333             200.0     36200.0            11
37             0.708333             247.5     45787.5             7

    Flight Year
36         2015
37         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
38  Flight39  42270  ORD-DFW              1.5          81
39  Flight40  41866  ORD-CLT              2.7          86

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
38             0.750000             200.0     36200.0             9
39             0.583333             137.5     24887.5             8

    Flight Year
38         2015
39         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
40  Flight41  42232  ORD-CLT              1.9          69
41  Flight42  42359  ORD-EWR              3.3          43

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
40             0.791667             137.5     24887.5             8
41             0.708333             315.0     51975.0            12

    Flight Year
40         2015
41         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
42  Flight43  42101  ORD-LGA              2.0         104
43  Flight44  41866  ORD-LAS              1.2         166

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
42             0.645833             275.0     50875.0             4
43             0.708333             302.5     49912.5             8

    Flight Year
42         2015
43         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
44  Flight45  42154  ORD-EWR              3.0           8
45  Flight46  42006  ORD-EWR              2.5         205

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
44             0.750000               225       41625             5
45             0.791667               225       37125             1

    Flight Year
44         2015
45         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
46  Flight47  42242  ORD-PHX              0.5          70
47  Flight48  42201  ORD-MSP              2.2           1

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
46             0.833333             275.0     49775.0             8
47             0.604167             126.5     23402.5             7

    Flight Year
46         2015
47         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
48  Flight49  42336  ORD-FLL              4.6          50
49  Flight50  42261  ORD-DEN              1.3          87

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
48             0.583333               450       74250            11
49             0.708333               300       54300             9

    Flight Year
48         2015
49         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
50  Flight51  42164  ORD-JFK              1.5           3
51  Flight52  41887  ORD-LAS              3.5         155

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
50             0.791667               275       50875             6
51             0.479167               275       45375             9

    Flight Year
50         2015
51         2014

    FlightID   Date  RouteID  Departure Delay  AircraftID  \
52  Flight53  42072  ORD-MIA              2.1          83
53  Flight54  42095  ORD-MIA              1.6         206

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
52             0.770833               300       54300             3
53             0.333333               300       49500             4

    Flight Year
52         2015
53         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
54  Flight55  42244  ORD-BWI              1.5         203
55  Flight56  41952  ORD-BOS              3.0         173

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
54             0.708333               264       43560             8
55             0.500000               300       49500            11

    Flight Year
54         2015
55         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
56  Flight57  41653  ORD-DTW              2.1          75
57  Flight58  42331  ORD-LAX             10.0          17

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
56             0.750000               115       20815             1
57             0.708333               525       97125            11

    Flight Year
56         2014
57         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
58  Flight59  42341  ORD-DFW              1.5          16
59  Flight60  41747  ORD-JFK              1.9          82

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
58             0.770833               200       37000            12
59             0.291667               250       45250             4

    Flight Year
58         2015
59         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
60  Flight61  41996  ORD-BOS              3.2         125
61  Flight62  41876  ORD-DEN              2.5         202

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
60             0.333333               420       77700            12
61             0.541667               330       54450             8

    Flight Year
60         2014
61         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
62  Flight63  41847  ORD-MIA              2.9         136
63  Flight64  41918  ORD-PHX              3.1          38

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
62             0.791667               330       61050             7
63             0.729167               250       41250            10

    Flight Year
62         2014
63         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
64  Flight65  42189  ORD-JFK              2.1          65
65  Flight66  41681  ORD-MSP              1.8         124

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
64             0.750000               275       49775             7
65             0.708333               115       21275             2

    Flight Year
64         2015
65         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
66  Flight67  42069  ORD-DTW              2.7         115
67  Flight68  42132  ORD-PHL              2.0          77

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
66             0.458333               115       21275             3
67             0.333333               275       49775             5

    Flight Year
66         2015
67         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
68  Flight69  42125  ORD-IAH              1.5          72
69  Flight70  42083  ORD-PHX              1.6          12

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
68             0.312500               200       36200             5
69             0.395833               250       46250             3

    Flight Year
68         2015
69         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
70  Flight71  41680  ORD-MIA              3.6          95
71  Flight72  42245  ORD-IAD              2.0         143

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
70             0.375000               300       55500             2
71             0.833333               330       61050             8

    Flight Year
70         2014
71         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
72  Flight73  41974  ORD-LAS              2.3         186
73  Flight74  41803  ORD-EWR              1.2          52

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
72             0.604167             275.0     45375.0            12
73             0.333333             247.5     40837.5             6

    Flight Year
72         2014
73         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
74  Flight75  41948  ORD-LAS              1.7          69
75  Flight76  41769  ORD-LGA              1.7          86

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
74             0.291667               275       49775            11
75             0.708333               275       49775             5

    Flight Year
74         2014
75         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
76  Flight77  41961  ORD-DFW              1.0          23
77  Flight78  42306  ORD-SFO              1.1         121

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
76             0.291667               200       37000            11
77             0.708333               375       69375            10

    Flight Year
76         2014
77         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
78  Flight79  41694  ORD-JFK              2.4         175
79  Flight80  42309  ORD-SFO              2.2         146

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
78             0.708333               250       41250             2
79             0.312500               375       69375            11

    Flight Year
78         2014
79         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
80  Flight81  41764  ORD-DFW              1.6          76
81  Flight82  41802  ORD-SEA              3.3          70

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
80             0.541667               200       36200             5
81             0.750000               385       69685             6

    Flight Year
80         2014
81         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
82  Flight83  42316  ORD-CLT              3.3         101
83  Flight84  41995  ORD-BOS              3.2         203

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
82                0.875               125       23125            11
83                0.500               420       69300            12

    Flight Year
82         2015
83         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
84  Flight85  41845  ORD-FLL              0.9         153
85  Flight86  42335  ORD-MCO              6.3         187

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
84               0.6250               330       54450             7
85               0.8125               375       61875            11

    Flight Year
84         2014
85         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
86  Flight87  42073  ORD-LGA              0.9         126
87  Flight88  41807  ORD-LAS              2.0         116

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
86             0.791667             275.0     50875.0             3
87             0.812500             302.5     55962.5             6

    Flight Year
86         2015
87         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
88  Flight89  42239  ORD-BOS              3.2         198
89  Flight90  42110  ORD-MSP              0.7         136

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
88             0.520833               330       54450             8
89             0.291667               115       21275             4

    Flight Year
88         2015
89         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
90  Flight91  41804  ORD-SFO              0.5         117
91  Flight92  41677  ORD-ATL             12.3          15

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
90             0.520833             412.5     76312.5             6
91             0.708333             200.0     37000.0             2

    Flight Year
90         2014
91         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
92  Flight93  42075  ORD-SEA              1.8          70
93  Flight94  41704  ORD-SFO              2.3         187

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
92             0.666667               350       63350             3
93             0.750000               375       61875             3

    Flight Year
92         2015
93         2014
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
94  Flight95  41692  ORD-BOS              2.6          14
95  Flight96  42240  ORD-EWR              3.6         138

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
94             0.875000             300.0     55500.0             2
95             0.291667             247.5     45787.5             8

    Flight Year
94         2014
95         2015
    FlightID   Date  RouteID  Departure Delay  AircraftID  \
96  Flight97  41825  ORD-SEA              0.9         110
97  Flight98  42202  ORD-ATL             10.3          34

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
96             0.708333               385       71225             7
97             0.729167               220       40700             7

    Flight Year
96         2014
97         2015
     FlightID   Date  RouteID  Departure Delay  AircraftID  \
98   Flight99  42212  ORD-MIA              0.7          26
99  Flight100  42251  ORD-IAH              1.0         204

    Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
98             0.708333               330       61050             7
99             0.895833               200       33000             9

    Flight Year
98         2015
99         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
100  Flight101  41793  ORD-CLT              1.2         131
101  Flight102  41972  ORD-MIA              7.1          90

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
100             0.520833             137.5     25437.5             6
101             0.458333             450.0     81450.0            11

     Flight Year
100         2014
101         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
102  Flight103  41664  ORD-MSP              1.7         153
103  Flight104  42144  ORD-IAD              2.5          51

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
102             0.583333               115       18975             1
103             0.791667               300       49500             5

     Flight Year
102         2014
103         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
104  Flight105  41971  ORD-LAS              5.6         196
105  Flight106  41967  ORD-CLT              4.6          43

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
104             0.500000             412.5     68062.5            11
105             0.666667             187.5     30937.5            11

     Flight Year
104         2014
105         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
106  Flight107  42026  ORD-DFW              2.1         117
107  Flight108  42164  ORD-CLT              1.3          29

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
106             0.291667             200.0     37000.0             1
107             0.458333             137.5     25437.5             6

     Flight Year
106         2015
107         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
108  Flight109  41786  ORD-BOS              1.6          49
109  Flight110  42058  ORD-LAX              3.8          83

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
108             0.291667               300       49500             5
109             0.541667               350       63350             2

     Flight Year
108         2014
109         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
110  Flight111  42241  ORD-SEA              1.4          43
111  Flight112  41981  ORD-ATL              9.1          32

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
110             0.708333               385       63525             8
111             0.458333               200       37000            12

     Flight Year
110         2015
111         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
112  Flight113  41798  ORD-IAH              2.3          95
113  Flight114  41982  ORD-LAS              2.6         122

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
112             0.312500               220       40700             6
113             0.416667               275       50875            12

     Flight Year
112         2014
113         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
114  Flight115  42133  ORD-EWR              2.2          32
115  Flight116  41906  ORD-LAX              4.7         140

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
114             0.791667               225       41625             5
115             0.666667               350       64750             9

     Flight Year
114         2015
115         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
116  Flight117  42136  ORD-CLT              2.7          81
117  Flight118  42049  ORD-DEN              1.3         115

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
116             0.333333               125       22625             5
117             0.375000               300       55500             2

     Flight Year
116         2015
117         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
118  Flight119  41866  ORD-JFK              2.6         158
119  Flight120  41674  ORD-SFO              1.0          21

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
118             0.437500               275       45375             8
119             0.729167               375       69375             2

     Flight Year
118         2014
119         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
120  Flight121  41746  ORD-CLT              1.7          74
121  Flight122  41969  ORD-ATL             14.8          38

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
120             0.333333               125       22625             4
121             0.354167               300       49500            11

     Flight Year
120         2014
121         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
122  Flight123  41826  ORD-DEN              3.0          26
123  Flight124  41978  ORD-DFW              1.8         131

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
122             0.375000               330       61050             7
123             0.291667               200       37000            12

     Flight Year
122         2014
123         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
124  Flight125  42242  ORD-SEA              2.3          94
125  Flight126  42248  ORD-DEN              1.1         183

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
124             0.500000               385       71225             8
125             0.479167               300       49500             9

     Flight Year
124         2015
125         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
126  Flight127  41684  ORD-SEA              1.8         140
127  Flight128  41874  ORD-LAX              5.6         110

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
126             0.770833               350       64750             2
127             0.791667               385       71225             8

     Flight Year
126         2014
127         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
128  Flight129  42043  ORD-SFO              2.4         179
129  Flight130  42013  ORD-PHX              2.1         204

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
128             0.375000               375       61875             2
129             0.333333               250       41250             1

     Flight Year
128         2015
129         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
130  Flight131  41758  ORD-LGA              2.7          90
131  Flight132  42035  ORD-ATL              9.4          13

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
130             0.791667               275       49775             4
131             0.645833               200       37000             1

     Flight Year
130         2014
131         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
132  Flight133  42106  ORD-SFO              1.8          42
133  Flight134  42132  ORD-FLL              1.4         142

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
132             0.708333               375       61875             4
133             0.833333               300       55500             5

     Flight Year
132         2015
133         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
134  Flight135  41873  ORD-DFW              2.1          84
135  Flight136  42352  ORD-MCO              2.9          23

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
134             0.333333               220       39820             8
135             0.645833               250       46250            12

     Flight Year
134         2014
135         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
136  Flight137  42282  ORD-DFW              2.1         160
137  Flight138  42220  ORD-LAS              2.1          25

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
136             0.708333             200.0     33000.0            10
137             0.416667             302.5     55962.5             8

     Flight Year
136         2015
137         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
138  Flight139  41931  ORD-DFW              1.1         172
139  Flight140  41652  ORD-MIA              2.6          45

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
138             0.687500               200       33000            10
139             0.333333               300       49500             1

     Flight Year
138         2014
139         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
140  Flight141  41686  ORD-PHL              2.2          94
141  Flight142  41881  ORD-CLT              1.0          75

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
140             0.500000             275.0     50875.0             2
141             0.791667             137.5     24887.5             8

     Flight Year
140         2014
141         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
142  Flight143  41946  ORD-EWR              1.0         156
143  Flight144  41877  ORD-SFO              1.5         137

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
142             0.625000             225.0     37125.0            11
143             0.416667             412.5     76312.5             8

     Flight Year
142         2014
143         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
144  Flight145  42247  ORD-IAH              3.0          39
145  Flight146  41751  ORD-CLT              3.5         202

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
144             0.791667               220       36300             8
145             0.875000               125       20625             4

     Flight Year
144         2015
145         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
146  Flight147  42315  ORD-LAS              1.8         188
147  Flight148  41886  ORD-LAX              3.0         117

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
146             0.708333               275       45375            11
147             0.312500               350       64750             9

     Flight Year
146         2015
147         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
148  Flight149  41648  ORD-MSP              1.8          38
149  Flight150  41996  ORD-DEN              2.3         104

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
148             0.500000               115       18975             1
149             0.770833               420       77700            12

     Flight Year
148         2014
149         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
150  Flight151  42287  ORD-LGA              2.3          41
151  Flight152  41837  ORD-LAX              6.2         165

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
150             0.770833               275       45375            10
151             0.333333               385       63525             7

     Flight Year
150         2015
151         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
152  Flight153  42014  ORD-MIA              2.8          93
153  Flight154  42027  ORD-PHX              2.8          50

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
152             0.458333               300       55500             1
153             0.770833               250       41250             1

     Flight Year
152         2015
153         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
154  Flight155  42269  ORD-SEA              2.2          75
155  Flight156  42135  ORD-SFO              2.1         179

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
154             0.583333               350       63350             9
155             0.437500               375       61875             5

     Flight Year
154         2015
155         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
156  Flight157  42266  ORD-BWI              1.6         162
157  Flight158  42255  ORD-PHL              2.9         205

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
156             0.395833               240       39600             9
157             0.708333               275       45375             9

     Flight Year
156         2015
157         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
158  Flight159  41959  ORD-ATL              6.9          80
159  Flight160  41841  ORD-PHX              2.2         112

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
158             0.583333               200       36200            11
159             0.583333               275       50875             7

     Flight Year
158         2014
159         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
160  Flight161  41916  ORD-CLT              1.4         120
161  Flight162  41902  ORD-CLT              0.7         185

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
160             0.875000               125       23125            10
161             0.708333               125       20625             9

     Flight Year
160         2014
161         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
162  Flight163  41848  ORD-JFK              0.8          26
163  Flight164  42080  ORD-MCO              2.6          87

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
162             0.520833               275       50875             7
163             0.750000               250       45250             3

     Flight Year
162         2014
163         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
164  Flight165  41926  ORD-CLT              2.2         110
165  Flight166  42337  ORD-DEN              4.4         152

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
164             0.770833               125       23125            10
165             0.791667               450       74250            11

     Flight Year
164         2014
165         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
166  Flight167  42246  ORD-PHX              3.2         112
167  Flight168  41987  ORD-PHX              2.3          84

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
166             0.416667               275       50875             8
167             0.333333               250       45250            12

     Flight Year
166         2015
167         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
168  Flight169  41756  ORD-PHL              1.5         173
169  Flight170  41747  ORD-DFW              2.4         204

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
168               0.7500               275       45375             4
169               0.6875               200       33000             4

     Flight Year
168         2014
169         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
170  Flight171  42054  ORD-DFW              0.9         101
171  Flight172  41809  ORD-PHX              2.5         128

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
170             0.708333               200       37000             2
171             0.875000               275       50875             6

     Flight Year
170         2015
171         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
172  Flight173  41884  ORD-SFO              1.5          46
173  Flight174  41953  ORD-DFW              2.1          35

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
172             0.895833               375       61875             9
173             0.375000               200       37000            11

     Flight Year
172         2014
173         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
174  Flight175  42148  ORD-ATL              8.2         171
175  Flight176  42305  ORD-ATL              8.1         134

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
174             0.895833               200       33000             5
175             0.833333               200       37000            10

     Flight Year
174         2015
175         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
176  Flight177  42288  ORD-SFO              1.0          34
177  Flight178  41792  ORD-SEA              1.1         142

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
176             0.833333               375       69375            10
177             0.875000               385       71225             6

     Flight Year
176         2015
177         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
178  Flight179  42246  ORD-LAS              2.5         101
179  Flight180  42150  ORD-JFK              1.6          16

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
178             0.291667             302.5     55962.5             8
179             0.291667             250.0     46250.0             5

     Flight Year
178         2015
179         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
180  Flight181  42078  ORD-MSP              0.8         121
181  Flight182  41770  ORD-PHX              1.5         198

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
180             0.708333               115       21275             3
181             0.729167               250       41250             5

     Flight Year
180         2015
181         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
182  Flight183  42365  ORD-LAS              1.1         137
183  Flight184  42203  ORD-DEN              2.6          26

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
182               0.5625               385       71225            12
183               0.8125               330       61050             7

     Flight Year
182         2015
183         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
184  Flight185  41958  ORD-LAX              4.6          24
185  Flight186  41645  ORD-ATL              8.4          36

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
184             0.458333               350       64750            11
185             0.416667               200       33000             1

     Flight Year
184         2014
185         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
186  Flight187  41728  ORD-SEA              1.6         152
187  Flight188  41868  ORD-DEN              2.5         206

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
186             0.833333               350       57750             3
187             0.708333               330       54450             8

     Flight Year
186         2014
187         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
188  Flight189  42159  ORD-DFW              2.9         171
189  Flight190  42210  ORD-DFW              2.2         145

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
188             0.458333               220       36300             6
189             0.750000               220       40700             7

     Flight Year
188         2015
189         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
190  Flight191  42079  ORD-LAX              3.2         150
191  Flight192  41707  ORD-PHX              2.6         117

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
190             0.708333               350       64750             3
191             0.458333               250       46250             3

     Flight Year
190         2015
191         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
192  Flight193  42366  ORD-EWR              2.5          58
193  Flight194  42114  ORD-PHL              1.9         182

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
192             0.708333               225       37125            12
193             0.645833               275       45375             4

     Flight Year
192         2015
193         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
194  Flight195  41833  ORD-MSP              3.2         174
195  Flight196  41843  ORD-LAS              2.2          21

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
194             0.479167             126.5     20872.5             7
195             0.791667             302.5     55962.5             7

     Flight Year
194         2014
195         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
196  Flight197  41951  ORD-ATL              9.7         191
197  Flight198  41667  ORD-IAH              1.7          68

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
196               0.8125               200       33000            11
197               0.8125               200       36200             1

     Flight Year
196         2014
197         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
198  Flight199  41792  ORD-BOS              2.5         201
199  Flight200  41983  ORD-ATL              8.3         205

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
198             0.708333               330       54450             6
199             0.750000               200       33000            12

     Flight Year
198         2014
199         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
200  Flight201  42345  ORD-PHX              2.5          14
201  Flight202  41669  ORD-JFK              2.7          28

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
200             0.333333               250       46250            12
201             0.354167               250       46250             1

     Flight Year
200         2015
201         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
202  Flight203  42000  ORD-PHX              5.1         180
203  Flight204  42313  ORD-DFW              3.1         193

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
202                0.750               350       57750            12
203                0.625               200       33000            11

     Flight Year
202         2014
203         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
204  Flight205  41890  ORD-JFK              1.7         197
205  Flight206  42001  ORD-DFW              5.5         139

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
204             0.708333               250       41250             9
205             0.708333               280       51800            12

     Flight Year
204         2014
205         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
206  Flight207  41646  ORD-CLT              2.7         137
207  Flight208  41910  ORD-MIA              2.4          88

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
206             0.333333               125       23125             1
207             0.583333               300       54300             9

     Flight Year
206         2014
207         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
208  Flight209  42044  ORD-IAH              1.4          73
209  Flight210  42076  ORD-JFK              2.9         171

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
208             0.729167               200       36200             2
209             0.333333               250       41250             3

     Flight Year
208         2015
209         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
210  Flight211  42255  ORD-SFO              1.8         190
211  Flight212  41704  ORD-JFK              2.4         106

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
210             0.812500               375       61875             9
211             0.833333               250       46250             3

     Flight Year
210         2015
211         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
212  Flight213  41943  ORD-IAH              2.3          72
213  Flight214  41843  ORD-CLT              3.7         204

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
212             0.458333             200.0     36200.0            10
213             0.708333             137.5     22687.5             7

     Flight Year
212         2014
213         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
214  Flight215  42330  ORD-MIA              1.6         205
215  Flight216  41848  ORD-MIA              3.8          70

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
214                 0.75               300       49500            11
215                 0.50               330       59730             7

     Flight Year
214         2015
215         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
216  Flight217  41929  ORD-JFK              1.1         172
217  Flight218  42256  ORD-MSP              1.9         176

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
216             0.729167               250       41250            10
217             0.833333               115       18975             9

     Flight Year
216         2014
217         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
218  Flight219  41961  ORD-CLT              2.6         137
219  Flight220  42267  ORD-IAH              0.9         170

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
218             0.770833               125       23125            11
219             0.770833               200       33000             9

     Flight Year
218         2014
219         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
220  Flight221  41738  ORD-MCO              1.8         138
221  Flight222  42358  ORD-ATL              5.8         139

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
220             0.854167               250       46250             4
221             0.604167               200       37000            12

     Flight Year
220         2014
221         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
222  Flight223  41782  ORD-CLT                2         156
223  Flight224  41844  ORD-MCO                1          51

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
222             0.583333               125       20625             5
223             0.750000               275       45375             7

     Flight Year
222         2014
223         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
224  Flight225  42293  ORD-LAX              3.1          11
225  Flight226  41871  ORD-LAX              3.5           6

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
224             0.312500               350       64750            10
225             0.291667               385       71225             8

     Flight Year
224         2015
225         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
226  Flight227  41995  ORD-JFK              2.8          30
227  Flight228  41847  ORD-JFK              2.0           8

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
226             0.291667               350       64750            12
227             0.854167               275       50875             7

     Flight Year
226         2014
227         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
228  Flight229  41864  ORD-IAH              2.9         177
229  Flight230  42337  ORD-DFW              5.8           9

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
228             0.645833               220       36300             8
229             0.833333               300       55500            11

     Flight Year
228         2014
229         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
230  Flight231  42194  ORD-PHL              2.1         176
231  Flight232  41796  ORD-LGA              2.3         166

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
230             0.791667             302.5     49912.5             7
231             0.791667             302.5     49912.5             6

     Flight Year
230         2015
231         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
232  Flight233  41966  ORD-MSP              2.9         118
233  Flight234  42335  ORD-LAX             10.3         190

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
232             0.333333               115       21275            11
233             0.812500               525       86625            11

     Flight Year
232         2014
233         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
234  Flight235  42109  ORD-LAS              3.2         125
235  Flight236  41694  ORD-IAH              2.3         122

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
234             0.708333               275       50875             4
235             0.770833               200       37000             2

     Flight Year
234         2015
235         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
236  Flight237  42086  ORD-PHX              2.1          97
237  Flight238  42365  ORD-CLT              7.4         182

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
236             0.750000               250       46250             3
237             0.333333               175       28875            12

     Flight Year
236         2015
237         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
238  Flight239  42237  ORD-ATL              4.7         181
239  Flight240  41960  ORD-FLL              1.9         100

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
238             0.666667               220       36300             8
239             0.708333               300       55500            11

     Flight Year
238         2015
239         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
240  Flight241  41712  ORD-PHX              2.3         146
241  Flight242  42203  ORD-MIA              3.1         103

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
240                0.875               250       46250             3
241                0.625               330       61050             7

     Flight Year
240         2014
241         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
242  Flight243  42242  ORD-FLL              1.9         111
243  Flight244  42211  ORD-LAS              1.6          54

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
242             0.354167             330.0     61050.0             8
243             0.854167             302.5     49912.5             7

     Flight Year
242         2015
243         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
244  Flight245  41932  ORD-MIA              1.2         157
245  Flight246  41998  ORD-BOS              4.7          33

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
244             0.416667               300       49500            10
245             0.708333               420       77700            12

     Flight Year
244         2014
245         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
246  Flight247  42292  ORD-DEN              3.6          88
247  Flight248  42225  ORD-LAX              6.3         190

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
246               0.3125               300       54300            10
247               0.4375               385       63525             8

     Flight Year
246         2015
247         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
248  Flight249  42188  ORD-SFO              2.0         176
249  Flight250  42187  ORD-DFW              2.8          37

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
248             0.458333             412.5     68062.5             7
249             0.541667             220.0     36300.0             7

     Flight Year
248         2015
249         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
250  Flight251  41771  ORD-EWR              2.3          41
251  Flight252  41973  ORD-PHL              3.6         173

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
250             0.354167             225.0     37125.0             5
251             0.291667             412.5     68062.5            11

     Flight Year
250         2014
251         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
252  Flight253  41773  ORD-SEA              1.9         150
253  Flight254  41672  ORD-DEN              1.9          43

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
252             0.479167               350       64750             5
253             0.708333               300       49500             2

     Flight Year
252         2014
253         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
254  Flight255  42189  ORD-SFO              2.9         135
255  Flight256  42189  ORD-JFK              3.5          64

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
254               0.8125             412.5     76312.5             7
255               0.8125             275.0     49775.0             7

     Flight Year
254         2015
255         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
256  Flight257  41869  ORD-ATL              5.7         132
257  Flight258  41849  ORD-JFK              1.7          29

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
256             0.708333               220       40700             8
257             0.812500               275       50875             7

     Flight Year
256         2014
257         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
258  Flight259  42357  ORD-ATL              7.2          10
259  Flight260  41881  ORD-LGA              1.6           9

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
258             0.458333             200.0     37000.0            12
259             0.312500             302.5     55962.5             8

     Flight Year
258         2015
259         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
260  Flight261  42301  ORD-ATL              8.4         122
261  Flight262  41739  ORD-DEN              0.5          85

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
260             0.333333               200       37000            10
261             0.291667               300       54300             4

     Flight Year
260         2015
261         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
262  Flight263  42075  ORD-SEA              2.7         151
263  Flight264  41949  ORD-DFW              1.3           6

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
262             0.416667               350       64750             3
263             0.812500               200       37000            11

     Flight Year
262         2015
263         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
264  Flight265  42331  ORD-MIA              5.7          71
265  Flight266  41870  ORD-EWR              1.6         146

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
264             0.416667             450.0     81450.0            11
265             0.312500             247.5     45787.5             8

     Flight Year
264         2015
265         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
266  Flight267  42040  ORD-JFK              2.1         166
267  Flight268  41769  ORD-ATL             10.0         160

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
266             0.291667               250       41250             2
267             0.291667               200       33000             5

     Flight Year
266         2015
267         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
268  Flight269  42055  ORD-JFK              1.6          74
269  Flight270  41968  ORD-SFO              4.8          35

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
268             0.854167             250.0     45250.0             2
269             0.812500             562.5    104062.5            11

     Flight Year
268         2015
269         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
270  Flight271  41895  ORD-SEA              2.4          17
271  Flight272  41759  ORD-PHX              1.0          55

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
270             0.520833               350       64750             9
271             0.750000               250       41250             4

     Flight Year
270         2014
271         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
272  Flight273  41969  ORD-ATL             21.3         187
273  Flight274  42161  ORD-DFW              2.2         135

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
272             0.666667               300       49500            11
273             0.687500               220       40700             6

     Flight Year
272         2014
273         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
274  Flight275  41730  ORD-DEN              3.2          21
275  Flight276  41949  ORD-IAH              1.4         114

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
274             0.333333               300       55500             4
275             0.833333               200       37000            11

     Flight Year
274         2014
275         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
276  Flight277  41726  ORD-LAS              2.3         196
277  Flight278  41972  ORD-DFW              3.1         190

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
276             0.708333               275       45375             3
277             0.541667               300       49500            11

     Flight Year
276         2014
277         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
278  Flight279  41774  ORD-CLT              2.0          46
279  Flight280  42215  ORD-DTW              2.7          80

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
278             0.333333             125.0     20625.0             5
279             0.750000             126.5     22896.5             7

     Flight Year
278         2014
279         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
280  Flight281  42254  ORD-DFW              1.9          60
281  Flight282  41735  ORD-MIA              2.1         172

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
280             0.791667               200       33000             9
281             0.833333               300       49500             4

     Flight Year
280         2015
281         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
282  Flight283  41970  ORD-SEA              7.4          52
283  Flight284  42278  ORD-LAS              1.6         156

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
282             0.354167               525       86625            11
283             0.791667               275       45375            10

     Flight Year
282         2014
283         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
284  Flight285  42103  ORD-DEN              3.2         111
285  Flight286  42110  ORD-LAX              5.6          47

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
284             0.666667               300       55500             4
285             0.791667               350       57750             4

     Flight Year
284         2015
285         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
286  Flight287  42180  ORD-SEA              1.5         134
287  Flight288  41842  ORD-JFK              2.4          21

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
286             0.750000               385       71225             6
287             0.291667               275       50875             7

     Flight Year
286         2015
287         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
288  Flight289  41968  ORD-CLT              5.0          32
289  Flight290  41780  ORD-SFO              1.6          93

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
288             0.645833             187.5     34687.5            11
289             0.875000             375.0     69375.0             5

     Flight Year
288         2014
289         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
290  Flight291  42166  ORD-EWR              3.6          31
291  Flight292  41740  ORD-ATL              8.8          68

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
290               0.8125             247.5     45787.5             6
291               0.7500             200.0     36200.0             4

     Flight Year
290         2015
291         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
292  Flight293  41995  ORD-ATL             15.5         162
293  Flight294  42155  ORD-MSP              1.8         174

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
292             0.791667               280       46200            12
293             0.312500               115       18975             5

     Flight Year
292         2014
293         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
294  Flight295  42254  ORD-ATL              6.1          15
295  Flight296  42301  ORD-LAS              2.8          85

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
294             0.583333               200       37000             9
295             0.750000               275       49775            10

     Flight Year
294         2015
295         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
296  Flight297  41796  ORD-ATL              6.8         139
297  Flight298  42353  ORD-ATL             11.5         110

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
296             0.708333               220       40700             6
297             0.291667               200       37000            12

     Flight Year
296         2014
297         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
298  Flight299  42026  ORD-JFK              0.5          53
299  Flight300  41803  ORD-PHX              1.7         207

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
298             0.562500               250       41250             1
299             0.458333               275       45375             6

     Flight Year
298         2015
299         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
300  Flight301  41972  ORD-JFK              5.6         171
301  Flight302  42152  ORD-LAS              2.5         113

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
300             0.708333               375       61875            11
301             0.541667               275       50875             5

     Flight Year
300         2014
301         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
302  Flight303  41787  ORD-MIA              3.1         148
303  Flight304  41981  ORD-CLT              1.3          20

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
302             0.750000               300       55500             5
303             0.416667               125       23125            12

     Flight Year
302         2014
303         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
304  Flight305  42291  ORD-DEN              2.9          66
305  Flight306  41966  ORD-SFO              1.2         174

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
304             0.666667               300       54300            10
305             0.291667               375       61875            11

     Flight Year
304         2015
305         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
306  Flight307  41977  ORD-PHL              1.3         132
307  Flight308  41677  ORD-LAX              6.0         102

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
306             0.895833               275       50875            12
307             0.708333               350       64750             2

     Flight Year
306         2014
307         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
308  Flight309  41968  ORD-DEN              5.5          90
309  Flight310  42246  ORD-DEN              1.4          81

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
308             0.375000               450       81450            11
309             0.833333               330       59730             8

     Flight Year
308         2014
309         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
310  Flight311  42182  ORD-MSP              2.2          31
311  Flight312  41913  ORD-SFO              2.4         143

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
310             0.666667             126.5     23402.5             6
311             0.750000             375.0     69375.0            10

     Flight Year
310         2015
311         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
312  Flight313  41989  ORD-BOS              2.2          23
313  Flight314  41779  ORD-SEA              2.3         135

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
312             0.708333               300       55500            12
313             0.875000               350       64750             5

     Flight Year
312         2014
313         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
314  Flight315  42210  ORD-DEN              1.8          91
315  Flight316  41969  ORD-BOS              4.4          70

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
314             0.437500               330       61050             7
315             0.416667               450       81450            11

     Flight Year
314         2015
315         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
316  Flight317  42203  ORD-SEA              1.7         104
317  Flight318  42219  ORD-MIA              2.5          71

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
316             0.583333               385       71225             7
317             0.750000               330       59730             8

     Flight Year
316         2015
317         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
318  Flight319  41773  ORD-MSP              1.6          15
319  Flight320  41889  ORD-SEA              3.4          51

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
318             0.291667               115       21275             5
319             0.645833               350       57750             9

     Flight Year
318         2014
319         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
320  Flight321  42301  ORD-ATL              8.6         175
321  Flight322  41712  ORD-DFW              2.1          45

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
320             0.291667               200       33000            10
321             0.604167               200       33000             3

     Flight Year
320         2015
321         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
322  Flight323  41869  ORD-SEA              2.7         101
323  Flight324  42048  ORD-JFK              2.3           5

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
322             0.729167               385       71225             8
323             0.708333               250       46250             2

     Flight Year
322         2014
323         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
324  Flight325  42158  ORD-IAH              2.6         124
325  Flight326  42254  ORD-MIA              1.1         150

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
324             0.687500               220       40700             6
325             0.708333               300       55500             9

     Flight Year
324         2015
325         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
326  Flight327  41920  ORD-SEA              1.3         121
327  Flight328  42219  ORD-BOS              0.9           1

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
326             0.333333               350       64750            10
327             0.708333               330       61050             8

     Flight Year
326         2014
327         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
328  Flight329  41910  ORD-EWR              1.1         104
329  Flight330  42098  ORD-MIA              1.8          22

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
328               0.5000               225       41625             9
329               0.3125               300       55500             4

     Flight Year
328         2014
329         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
330  Flight331  42275  ORD-DFW              1.2          98
331  Flight332  41723  ORD-FLL              1.7         125

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
330             0.291667               200       37000             9
331             0.750000               300       55500             3

     Flight Year
330         2015
331         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
332  Flight333  42246  ORD-ATL              8.2         196
333  Flight334  42086  ORD-JFK              1.9         134

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
332             0.458333               220       36300             8
333             0.312500               250       46250             3

     Flight Year
332         2015
333         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
334  Flight335  41668  ORD-MCO              0.1         195
335  Flight336  42019  ORD-DTW              1.6         114

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
334             0.375000               250       41250             1
335             0.333333               115       21275             1

     Flight Year
334         2014
335         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
336  Flight337  42307  ORD-BOS              2.5          29
337  Flight338  41677  ORD-IAH              2.6         135

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
336             0.333333               300       55500            10
337             0.291667               200       37000             2

     Flight Year
336         2015
337         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
338  Flight339  42261  ORD-IAH              2.6         186
339  Flight340  41790  ORD-MCO              2.2          81

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
338             0.458333               200       33000             9
339             0.291667               250       45250             5

     Flight Year
338         2015
339         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
340  Flight341  42073  ORD-PHL              1.9          68
341  Flight342  41978  ORD-FLL              1.7          66

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
340             0.875000               275       49775             3
341             0.291667               300       54300            12

     Flight Year
340         2015
341         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
342  Flight343  42247  ORD-DEN              1.7         101
343  Flight344  42332  ORD-DFW              4.9         160

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
342             0.875000               330       61050             8
343             0.729167               300       49500            11

     Flight Year
342         2015
343         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
344  Flight345  41901  ORD-DEN              1.7         103
345  Flight346  41816  ORD-SFO              2.6          63

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
344             0.750000             300.0     55500.0             9
345             0.833333             412.5     74662.5             6

     Flight Year
344         2014
345         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
346  Flight347  41792  ORD-DEN              2.0         155
347  Flight348  42275  ORD-ATL             10.3          19

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
346             0.708333               330       54450             6
347             0.625000               200       37000             9

     Flight Year
346         2014
347         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
348  Flight349  42177  ORD-PHX              3.7           2
349  Flight350  41820  ORD-MSP              1.6          53

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
348             0.291667             275.0     50875.0             6
349             0.708333             126.5     20872.5             6

     Flight Year
348         2015
349         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
350  Flight351  42170  ORD-SFO              1.9          85
351  Flight352  42113  ORD-MCO              2.3         208

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
350             0.604167             412.5     74662.5             6
351             0.500000             250.0     41250.0             4

     Flight Year
350         2015
351         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
352  Flight353  41674  ORD-LAX              3.3          70
353  Flight354  41862  ORD-IAH              1.2         185

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
352             0.645833               350       63350             2
353             0.291667               220       36300             8

     Flight Year
352         2014
353         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
354  Flight355  41836  ORD-LAX              5.4         191
355  Flight356  41663  ORD-LAX              2.6          78

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
354             0.750000               385       63525             7
355             0.708333               350       63350             1

     Flight Year
354         2014
355         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
356  Flight357  41805  ORD-DEN              3.3         167
357  Flight358  41796  ORD-MSP              1.4         143

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
356             0.291667             330.0     54450.0             6
357             0.291667             126.5     23402.5             6

     Flight Year
356         2014
357         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
358  Flight359  42281  ORD-MCO              3.6          19
359  Flight360  42244  ORD-PHX              2.7          30

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
358             0.291667               250       46250            10
359             0.750000               275       50875             8

     Flight Year
358         2015
359         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
360  Flight361  41886  ORD-DEN              2.7         159
361  Flight362  42150  ORD-DFW              2.1         153

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
360             0.291667               300       49500             9
361             0.333333               200       33000             5

     Flight Year
360         2014
361         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
362  Flight363  41991  ORD-JFK              2.0         162
363  Flight364  41833  ORD-LGA              2.2          57

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
362             0.375000             250.0     41250.0            12
363             0.708333             302.5     49912.5             7

     Flight Year
362         2014
363         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
364  Flight365  42128  ORD-DFW              2.3         182
365  Flight366  41893  ORD-MCO              1.1         198

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
364                 0.75               200       33000             5
365                 0.75               250       41250             9

     Flight Year
364         2015
365         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
366  Flight367  41771  ORD-DEN              3.6         126
367  Flight368  41991  ORD-DFW              1.2         122

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
366             0.708333               300       55500             5
367             0.750000               200       37000            12

     Flight Year
366         2014
367         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
368  Flight369  42358  ORD-PHL              0.8          15
369  Flight370  42225  ORD-ATL              9.7         110

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
368             0.875000               275       50875            12
369             0.729167               220       40700             8

     Flight Year
368         2015
369         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
370  Flight371  42260  ORD-LAS              1.3         148
371  Flight372  42066  ORD-SFO              1.7         195

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
370             0.458333               275       50875             9
371             0.375000               375       61875             3

     Flight Year
370         2015
371         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
372  Flight373  41973  ORD-LGA              3.7         107
373  Flight374  42363  ORD-PHX              5.4          70

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
372             0.291667             412.5     76312.5            11
373             0.750000             350.0     63350.0            12

     Flight Year
372         2014
373         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
374  Flight375  41922  ORD-LAS              1.2         162
375  Flight376  42243  ORD-DTW              1.7         173

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
374             0.354167             275.0     45375.0            10
375             0.708333             126.5     20872.5             8

     Flight Year
374         2014
375         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
376  Flight377  42118  ORD-DEN              1.9           4
377  Flight378  41801  ORD-EWR              1.2         161

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
376             0.791667             300.0     55500.0             4
377             0.708333             247.5     40837.5             6

     Flight Year
376         2015
377         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
378  Flight379  41727  ORD-PHX              1.1         180
379  Flight380  42244  ORD-LAS              2.2          43

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
378             0.791667             250.0     41250.0             3
379             0.333333             302.5     49912.5             8

     Flight Year
378         2014
379         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
380  Flight381  42047  ORD-DEN              1.9          24
381  Flight382  41837  ORD-CLT              1.9         109

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
380             0.500000             300.0     55500.0             2
381             0.708333             137.5     25437.5             7

     Flight Year
380         2015
381         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
382  Flight383  41748  ORD-CLT              0.7          98
383  Flight384  42291  ORD-ATL             10.0          86

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
382             0.458333               125       23125             4
383             0.812500               200       36200            10

     Flight Year
382         2014
383         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
384  Flight385  41920  ORD-LGA              3.3         205
385  Flight386  42352  ORD-BOS              1.9          27

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
384             0.770833               275       45375            10
385             0.625000               300       55500            12

     Flight Year
384         2014
385         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
386  Flight387  41642  ORD-SFO              1.1         123
387  Flight388  41972  ORD-SEA              5.7          38

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
386             0.458333               375       69375             1
387             0.333333               525       86625            11

     Flight Year
386         2014
387         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
388  Flight389  42084  ORD-JFK              2.0         110
389  Flight390  41924  ORD-SEA              2.3         130

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
388             0.291667               250       46250             3
389             0.291667               350       64750            10

     Flight Year
388         2015
389         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
390  Flight391  41902  ORD-DFW              2.5          98
391  Flight392  41745  ORD-LGA              2.6          58

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
390             0.708333               200       37000             9
391             0.812500               275       45375             4

     Flight Year
390         2014
391         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
392  Flight393  41725  ORD-LAX              3.7          67
393  Flight394  41942  ORD-LAS              1.7          75

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
392             0.500000               350       63350             3
393             0.895833               275       49775            10

     Flight Year
392         2014
393         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
394  Flight395  42016  ORD-DTW              1.8         176
395  Flight396  42056  ORD-LAS              2.4          99

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
394             0.750000               115       18975             1
395             0.479167               275       50875             2

     Flight Year
394         2015
395         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
396  Flight397  41721  ORD-IAD              1.7          15
397  Flight398  42160  ORD-SFO              2.2         102

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
396               0.8125             300.0     55500.0             3
397               0.6250             412.5     76312.5             6

     Flight Year
396         2014
397         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
398  Flight399  42329  ORD-DFW              2.1         184
399  Flight400  42123  ORD-DFW              2.3          33

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
398             0.583333               200       33000            11
399             0.583333               200       37000             4

     Flight Year
398         2015
399         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
400  Flight401  42299  ORD-EWR              2.2          84
401  Flight402  41975  ORD-LAS              2.1         147

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
400             0.354167               225       40725            10
401             0.791667               275       50875            12

     Flight Year
400         2015
401         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
402  Flight403  42041  ORD-JFK              2.4          42
403  Flight404  41800  ORD-MCO              2.7          66

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
402             0.375000               250       41250             2
403             0.833333               275       49775             6

     Flight Year
402         2015
403         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
404  Flight405  42006  ORD-DFW                1          37
405  Flight406  41704  ORD-SFO                2         168

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
404             0.583333               200       33000             1
405             0.708333               375       61875             3

     Flight Year
404         2015
405         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
406  Flight407  41854  ORD-MIA              2.3           6
407  Flight408  41864  ORD-DFW              1.8          91

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
406             0.479167               330       61050             8
407             0.833333               220       40700             8

     Flight Year
406         2014
407         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
408  Flight409  41904  ORD-DFW              2.5         124
409  Flight410  41642  ORD-LGA              0.3         143

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
408             0.708333               200       37000             9
409             0.312500               275       50875             1

     Flight Year
408         2014
409         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
410  Flight411  41904  ORD-JFK              1.6         153
411  Flight412  42060  ORD-DTW              2.0         121

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
410             0.291667               250       41250             9
411             0.333333               115       21275             2

     Flight Year
410         2014
411         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
412  Flight413  41769  ORD-DTW              2.9         104
413  Flight414  41880  ORD-EWR              2.2          61

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
412                 0.75             115.0     21275.0             5
413                 0.50             247.5     40837.5             8

     Flight Year
412         2014
413         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
414  Flight415  42245  ORD-MIA              1.1         172
415  Flight416  41969  ORD-BOS              5.6         192

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
414             0.666667               330       54450             8
415             0.541667               450       74250            11

     Flight Year
414         2015
415         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
416  Flight417  41688  ORD-JFK              1.6         160
417  Flight418  42129  ORD-DEN              1.6          70

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
416             0.708333               250       41250             2
417             0.833333               300       54300             5

     Flight Year
416         2014
417         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
418  Flight419  42252  ORD-SEA              2.1          91
419  Flight420  41866  ORD-LAX              5.0          78

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
418             0.833333               350       64750             9
419             0.291667               385       69685             8

     Flight Year
418         2015
419         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
420  Flight421  41704  ORD-ATL              5.4          21
421  Flight422  41841  ORD-LGA              1.9           1

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
420             0.708333             200.0     37000.0             3
421             0.708333             302.5     55962.5             7

     Flight Year
420         2014
421         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
422  Flight423  42325  ORD-DTW              2.1         210
423  Flight424  41880  ORD-DFW              2.6          41

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
422             0.791667               115       18975            11
423             0.333333               220       36300             8

     Flight Year
422         2015
423         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
424  Flight425  41883  ORD-PHX              2.6          31
425  Flight426  42218  ORD-LGA              1.2         154

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
424             0.770833             250.0     46250.0             9
425             0.708333             302.5     49912.5             8

     Flight Year
424         2014
425         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
426  Flight427  42153  ORD-CLT              2.1          56
427  Flight428  41956  ORD-LAX              4.1           8

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
426                 0.75               125       20625             5
427                 0.50               350       64750            11

     Flight Year
426         2015
427         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
428  Flight429  42360  ORD-LGA              5.3         148
429  Flight430  41843  ORD-LAS              2.9         151

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
428             0.333333             385.0     71225.0            12
429             0.291667             302.5     55962.5             7

     Flight Year
428         2015
429         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
430  Flight431  41896  ORD-DFW              2.2          88
431  Flight432  41898  ORD-SFO              1.9          87

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
430             0.333333               200       36200             9
431             0.812500               375       67875             9

     Flight Year
430         2014
431         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
432  Flight433  41980  ORD-ATL             10.3          28
433  Flight434  42098  ORD-ATL             11.2         183

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
432             0.479167               200       37000            12
433             0.750000               200       33000             4

     Flight Year
432         2014
433         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
434  Flight435  41702  ORD-ATL              8.1         140
435  Flight436  42153  ORD-ATL              6.0          32

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
434             0.625000               200       37000             3
435             0.729167               200       37000             5

     Flight Year
434         2014
435         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
436  Flight437  42243  ORD-JFK              2.5         207
437  Flight438  41854  ORD-CLT              1.5         152

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
436             0.833333             275.0     45375.0             8
437             0.750000             137.5     22687.5             8

     Flight Year
436         2015
437         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
438  Flight439  41971  ORD-IAH              4.6          38
439  Flight440  42128  ORD-ATL              9.5         145

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
438             0.708333               300       49500            11
439             0.791667               200       37000             5

     Flight Year
438         2014
439         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
440  Flight441  42245  ORD-BOS              0.7         189
441  Flight442  42171  ORD-MSP              2.1          77

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
440             0.833333             330.0     54450.0             8
441             0.791667             126.5     22896.5             6

     Flight Year
440         2015
441         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
442  Flight443  42232  ORD-SFO              1.3         139
443  Flight444  42205  ORD-MIA              2.0         182

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
442               0.8125             412.5     76312.5             8
443               0.7500             330.0     54450.0             7

     Flight Year
442         2015
443         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
444  Flight445  42263  ORD-DTW              1.1          58
445  Flight446  41713  ORD-ATL             10.1         113

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
444             0.791667               115       18975             9
445             0.833333               200       37000             3

     Flight Year
444         2015
445         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
446  Flight447  41724  ORD-DFW              3.8         180
447  Flight448  41838  ORD-ATL             11.2         189

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
446             0.312500               200       33000             3
447             0.333333               220       36300             7

     Flight Year
446         2014
447         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
448  Flight449  42322  ORD-MIA              3.6          50
449  Flight450  42133  ORD-MSP              2.1         154

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
448             0.291667               300       49500            11
449             0.500000               115       18975             5

     Flight Year
448         2015
449         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
450  Flight451  42172  ORD-SEA              1.2         131
451  Flight452  42329  ORD-ATL              8.0         129

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
450             0.625000               385       71225             6
451             0.291667               200       37000            11

     Flight Year
450         2015
451         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
452  Flight453  42006  ORD-LAX              4.7          60
453  Flight454  41770  ORD-JFK              2.3          23

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
452             0.416667               350       57750             1
453             0.291667               250       46250             5

     Flight Year
452         2015
453         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
454  Flight455  41865  ORD-DTW              1.4          19
455  Flight456  42192  ORD-SEA              1.7         148

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
454             0.583333             126.5     23402.5             8
455             0.479167             385.0     71225.0             7

     Flight Year
454         2014
455         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
456  Flight457  41778  ORD-DFW              1.3         138
457  Flight458  41942  ORD-LGA              2.4          40

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
456             0.479167               200       37000             5
457             0.875000               275       45375            10

     Flight Year
456         2014
457         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
458  Flight459  41810  ORD-LAX              4.2           2
459  Flight460  41670  ORD-PHL              0.8          95

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
458             0.770833               385       71225             6
459             0.791667               275       50875             1

     Flight Year
458         2014
459         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
460  Flight461  42266  ORD-EWR              2.9         208
461  Flight462  42185  ORD-DEN              1.1          21

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
460             0.854167               225       37125             9
461             0.854167               330       61050             6

     Flight Year
460         2015
461         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
462  Flight463  41659  ORD-CLT              1.6          69
463  Flight464  41894  ORD-JFK              3.3         104

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
462             0.833333               125       22625             1
463             0.895833               250       46250             9

     Flight Year
462         2014
463         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
464  Flight465  42334  ORD-PHL              5.8         124
465  Flight466  42259  ORD-EWR              2.0         168

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
464             0.791667             412.5     76312.5            11
465             0.708333             225.0     37125.0             9

     Flight Year
464         2015
465         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
466  Flight467  41838  ORD-MCO              2.9          10
467  Flight468  42256  ORD-LAX              5.9          96

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
466             0.416667               275       50875             7
467             0.812500               350       64750             9

     Flight Year
466         2014
467         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
468  Flight469  42280  ORD-ATL             10.1           3
469  Flight470  41755  ORD-SFO              1.4         128

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
468             0.708333               200       37000            10
469             0.625000               375       69375             4

     Flight Year
468         2015
469         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
470  Flight471  42000  ORD-LAX              8.3         113
471  Flight472  41714  ORD-DTW              2.9         130

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
470             0.875000               490       90650            12
471             0.854167               115       21275             3

     Flight Year
470         2014
471         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
472  Flight473  41845  ORD-DTW                3          59
473  Flight474  42069  ORD-DFW                2         116

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
472             0.333333             126.5     20872.5             7
473             0.708333             200.0     37000.0             3

     Flight Year
472         2014
473         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
474  Flight475  42280  ORD-LAX              3.6         127
475  Flight476  42202  ORD-JFK              2.2         201

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
474             0.291667               350       64750            10
475             0.291667               275       45375             7

     Flight Year
474         2015
475         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
476  Flight477  42009  ORD-MIA              2.7         100
477  Flight478  42350  ORD-DTW              2.3           9

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
476             0.750000               300       55500             1
477             0.854167               115       21275            12

     Flight Year
476         2015
477         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
478  Flight479  42179  ORD-MIA              3.2          61
479  Flight480  42175  ORD-PHL              1.8          76

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
478             0.875000             330.0     54450.0             6
479             0.708333             302.5     54752.5             6

     Flight Year
478         2015
479         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
480  Flight481  42173  ORD-SEA              3.1          85
481  Flight482  42143  ORD-DFW              1.5          27

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
480             0.666667               385       69685             6
481             0.791667               200       37000             5

     Flight Year
480         2015
481         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
482  Flight483  41868  ORD-SFO              1.8         171
483  Flight484  41825  ORD-MSP              1.4         183

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
482             0.458333             412.5     68062.5             8
483             0.291667             126.5     20872.5             7

     Flight Year
482         2014
483         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
484  Flight485  41641  ORD-DFW              3.6           3
485  Flight486  41781  ORD-MSP              2.5         106

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
484             0.791667               200       37000             1
485             0.375000               115       21275             5

     Flight Year
484         2014
485         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
486  Flight487  41843  ORD-LAX              6.7         155
487  Flight488  42145  ORD-CLT              2.7         147

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
486             0.291667               385       63525             7
487             0.750000               125       23125             5

     Flight Year
486         2014
487         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
488  Flight489  41790  ORD-CLT              2.0         179
489  Flight490  41719  ORD-JFK              2.3          79

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
488             0.708333               125       20625             5
489             0.333333               250       45250             3

     Flight Year
488         2014
489         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
490  Flight491  41958  ORD-ATL              8.5         126
491  Flight492  41697  ORD-EWR              1.6          41

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
490             0.416667               200       37000            11
491             0.604167               225       37125             2

     Flight Year
490         2014
491         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
492  Flight493  41852  ORD-CLT              2.0         185
493  Flight494  41723  ORD-LAX              4.2          37

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
492             0.833333             137.5     22687.5             8
493             0.333333             350.0     57750.0             3

     Flight Year
492         2014
493         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
494  Flight495  41732  ORD-CLT              1.6         201
495  Flight496  41780  ORD-LAS              3.3          76

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
494             0.791667               125       20625             4
495             0.333333               275       49775             5

     Flight Year
494         2014
495         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
496  Flight497  41873  ORD-LAX              5.3          48
497  Flight498  41968  ORD-PHX              5.2          89

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
496             0.791667               385       63525             8
497             0.708333               375       67875            11

     Flight Year
496         2014
497         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
498  Flight499  41769  ORD-IAH              1.8         202
499  Flight500  41870  ORD-EWR              1.3          74

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
498             0.645833             200.0     33000.0             5
499             0.291667             247.5     44797.5             8

     Flight Year
498         2014
499         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
500  Flight501  42212  ORD-LGA              2.6         183
501  Flight502  42208  ORD-ATL             11.2          33

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
500             0.395833             302.5     49912.5             7
501             0.291667             220.0     40700.0             7

     Flight Year
500         2015
501         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
502  Flight503  41858  ORD-DFW              2.3          95
503  Flight504  42058  ORD-FLL              2.2           8

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
502             0.833333               220       40700             8
503             0.583333               300       55500             2

     Flight Year
502         2014
503         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
504  Flight505  42108  ORD-BOS              1.3         207
505  Flight506  42362  ORD-EWR              4.4          51

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
504             0.875000               300       49500             4
505             0.791667               315       51975            12

     Flight Year
504         2015
505         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
506  Flight507  41834  ORD-SFO              0.7         153
507  Flight508  42304  ORD-LAX              2.6          40

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
506             0.645833             412.5     68062.5             7
507             0.666667             350.0     57750.0            10

     Flight Year
506         2014
507         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
508  Flight509  42086  ORD-LAS              1.5         112
509  Flight510  41684  ORD-DFW              2.2          46

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
508             0.750000               275       50875             3
509             0.416667               200       33000             2

     Flight Year
508         2015
509         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
510  Flight511  42108  ORD-ATL             10.4          57
511  Flight512  42352  ORD-IAH              1.7          81

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
510             0.750000               200       33000             4
511             0.291667               200       36200            12

     Flight Year
510         2015
511         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
512  Flight513  42197  ORD-DFW              1.9         202
513  Flight514  41884  ORD-LGA              1.5          39

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
512             0.791667               220       36300             7
513             0.875000               275       45375             9

     Flight Year
512         2015
513         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
514  Flight515  42164  ORD-JFK              0.8         137
515  Flight516  42202  ORD-SEA              1.7          62

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
514             0.833333               275       50875             6
515             0.750000               385       63525             7

     Flight Year
514         2015
515         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
516  Flight517  42341  ORD-FLL              2.1         129
517  Flight518  42155  ORD-PHX              1.8         101

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
516             0.750000               300       55500            12
517             0.791667               250       46250             5

     Flight Year
516         2015
517         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
518  Flight519  42060  ORD-LAS              1.6          10
519  Flight520  42066  ORD-DFW              2.6          84

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
518             0.312500               275       50875             2
519             0.541667               200       36200             3

     Flight Year
518         2015
519         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
520  Flight521  42057  ORD-MIA              1.8         137
521  Flight522  41713  ORD-BOS              1.5          12

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
520             0.333333               300       55500             2
521             0.750000               300       55500             3

     Flight Year
520         2015
521         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
522  Flight523  42077  ORD-MIA              2.2           7
523  Flight524  42215  ORD-SEA              2.5         165

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
522             0.333333               300       55500             3
523             0.750000               385       63525             7

     Flight Year
522         2015
523         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
524  Flight525  42086  ORD-ATL              9.2          86
525  Flight526  42001  ORD-SEA              3.6         183

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
524               0.5625               200       36200             3
525               0.7500               490       80850            12

     Flight Year
524         2015
525         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
526  Flight527  41981  ORD-EWR              0.8          93
527  Flight528  41758  ORD-MIA              1.6          81

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
526             0.791667               225       41625            12
527             0.375000               300       54300             4

     Flight Year
526         2014
527         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
528  Flight529  41796  ORD-MCO              2.6          63
529  Flight530  42150  ORD-DFW              2.7          95

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
528             0.791667               275       49775             6
529             0.416667               200       37000             5

     Flight Year
528         2014
529         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
530  Flight531  41834  ORD-BOS              3.4         164
531  Flight532  42015  ORD-JFK              2.8           2

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
530             0.291667               330       54450             7
531             0.812500               250       46250             1

     Flight Year
530         2014
531         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
532  Flight533  42208  ORD-DEN              1.5         141
533  Flight534  42214  ORD-DEN              2.7         150

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
532             0.458333               330       61050             7
533             0.812500               330       61050             7

     Flight Year
532         2015
533         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
534  Flight535  42281  ORD-MSP              2.9          47
535  Flight536  41988  ORD-ATL              7.3         167

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
534             0.354167               115       18975            10
535             0.375000               200       33000            12

     Flight Year
534         2015
535         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
536  Flight537  42261  ORD-PHX              1.3          92
537  Flight538  42331  ORD-SEA              4.9          38

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
536             0.833333               250       46250             9
537             0.354167               525       86625            11

     Flight Year
536         2015
537         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
538  Flight539  41654  ORD-DEN              0.7          96
539  Flight540  42287  ORD-DFW              2.3         193

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
538             0.729167               300       55500             1
539             0.791667               200       33000            10

     Flight Year
538         2014
539         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
540  Flight541  41824  ORD-MIA              0.9         206
541  Flight542  41967  ORD-DFW              4.4         153

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
540             0.333333               330       54450             7
541             0.750000               300       49500            11

     Flight Year
540         2014
541         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
542  Flight543  42337  ORD-SEA              3.9         168
543  Flight544  41797  ORD-IAH              2.5          23

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
542             0.583333               525       86625            11
543             0.708333               220       40700             6

     Flight Year
542         2015
543         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
544  Flight545  41641  ORD-LAS              3.8         171
545  Flight546  41948  ORD-DFW              1.1          55

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
544             0.312500               275       45375             1
545             0.333333               200       33000            11

     Flight Year
544         2014
545         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
546  Flight547  42333  ORD-LAX             11.5          13
547  Flight548  41967  ORD-LAS              5.6         177

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
546             0.291667             525.0     97125.0            11
547             0.500000             412.5     68062.5            11

     Flight Year
546         2015
547         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
548  Flight549  42108  ORD-EWR              1.4          46
549  Flight550  41844  ORD-DEN              3.0          42

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
548               0.7500               225       37125             4
549               0.8125               330       54450             7

     Flight Year
548         2015
549         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
550  Flight551  41788  ORD-DEN              2.1         143
551  Flight552  41928  ORD-LGA              2.3          31

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
550             0.375000               300       55500             5
551             0.708333               275       50875            10

     Flight Year
550         2014
551         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
552  Flight553  42126  ORD-LAX              4.6          19
553  Flight554  41692  ORD-DEN              1.7          82

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
552             0.666667               350       64750             5
553             0.583333               300       54300             2

     Flight Year
552         2015
553         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
554  Flight555  41971  ORD-IAH              4.1         194
555  Flight556  42107  ORD-EWR              2.0          12

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
554             0.333333               300       49500            11
555             0.708333               225       41625             4

     Flight Year
554         2014
555         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
556  Flight557  42238  ORD-MCO              1.8         182
557  Flight558  42185  ORD-DFW              2.1          24

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
556             0.291667               275       45375             8
557             0.833333               220       40700             6

     Flight Year
556         2015
557         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
558  Flight559  42161  ORD-IAH              1.7          57
559  Flight560  42092  ORD-PHX              3.1          34

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
558             0.708333               220       36300             6
559             0.333333               250       46250             3

     Flight Year
558         2015
559         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
560  Flight561  42087  ORD-MIA              2.3         120
561  Flight562  42353  ORD-SEA              1.5         190

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
560             0.791667               300       55500             3
561             0.708333               350       57750            12

     Flight Year
560         2015
561         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
562  Flight563  41819  ORD-MSP              2.4         183
563  Flight564  42273  ORD-ATL             11.3           1

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
562             0.770833             126.5     20872.5             6
563             0.770833             200.0     37000.0             9

     Flight Year
562         2014
563         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
564  Flight565  41795  ORD-CLT              2.9          41
565  Flight566  41661  ORD-MIA              1.6         127

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
564             0.333333             137.5     22687.5             6
565             0.333333             300.0     55500.0             1

     Flight Year
564         2014
565         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
566  Flight567  41874  ORD-MIA              2.2          31
567  Flight568  42180  ORD-PHX              2.9         159

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
566             0.770833               330       61050             8
567             0.875000               275       45375             6

     Flight Year
566         2014
567         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
568  Flight569  41996  ORD-SFO              3.5          19
569  Flight570  42265  ORD-PHL              2.2           1

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
568                 0.75               525       97125            12
569                 0.75               275       50875             9

     Flight Year
568         2014
569         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
570  Flight571  42024  ORD-JFK              0.7          63
571  Flight572  41918  ORD-SFO              1.8         181

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
570             0.458333               250       45250             1
571             0.791667               375       61875            10

     Flight Year
570         2015
571         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
572  Flight573  42204  ORD-EWR              1.3          57
573  Flight574  42174  ORD-IAH              1.8          99

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
572             0.750000             247.5     40837.5             7
573             0.708333             220.0     40700.0             6

     Flight Year
572         2015
573         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
574  Flight575  41649  ORD-DFW              1.3          20
575  Flight576  41649  ORD-DTW              0.9         104

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
574             0.666667               200       37000             1
575             0.729167               115       21275             1

     Flight Year
574         2014
575         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
576  Flight577  41704  ORD-PHL              2.3          69
577  Flight578  42136  ORD-SFO              2.2         172

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
576               0.5625               275       49775             3
577               0.7500               375       61875             5

     Flight Year
576         2014
577         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
578  Flight579  42359  ORD-LAX              9.7         195
579  Flight580  41721  ORD-DFW              1.7          33

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
578             0.666667               490       80850            12
579             0.750000               200       37000             3

     Flight Year
578         2015
579         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
580  Flight581  41671  ORD-LGA              1.5         190
581  Flight582  42265  ORD-CLT              2.1          12

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
580             0.333333               275       45375             2
581             0.770833               125       23125             9

     Flight Year
580         2014
581         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
582  Flight583  42351  ORD-LAS              1.2          71
583  Flight584  42113  ORD-SFO              2.9          45

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
582             0.791667               275       49775            12
583             0.833333               375       61875             4

     Flight Year
582         2015
583         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
584  Flight585  42336  ORD-ATL             20.2         173
585  Flight586  41805  ORD-DTW              2.4         146

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
584             0.625000             300.0     49500.0            11
585             0.708333             126.5     23402.5             6

     Flight Year
584         2015
585         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
586  Flight587  42274  ORD-BWI              1.3          49
587  Flight588  41983  ORD-PHL              1.7          70

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
586             0.333333               240       39600             9
587             0.458333               275       49775            12

     Flight Year
586         2015
587         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
588  Flight589  42291  ORD-PHX              1.6         201
589  Flight590  42160  ORD-BOS              3.4         181

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
588             0.708333               250       41250            10
589             0.333333               330       54450             6

     Flight Year
588         2015
589         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
590  Flight591  41818  ORD-DFW              2.0          43
591  Flight592  42015  ORD-SFO              2.9          41

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
590             0.666667               220       36300             6
591             0.333333               375       61875             1

     Flight Year
590         2014
591         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
592  Flight593  42361  ORD-IAH              3.7          25
593  Flight594  41969  ORD-JFK              5.0         132

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
592             0.791667               280       51800            12
593             0.770833               375       69375            11

     Flight Year
592         2015
593         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
594  Flight595  42007  ORD-LAS              1.8         158
595  Flight596  42335  ORD-DFW              4.6         109

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
594             0.395833               275       45375             1
595             0.875000               300       55500            11

     Flight Year
594         2015
595         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
596  Flight597  41855  ORD-SFO              1.3           2
597  Flight598  42061  ORD-DEN              2.0           9

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
596             0.770833             412.5     76312.5             8
597             0.791667             300.0     55500.0             2

     Flight Year
596         2014
597         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
598  Flight599  42145  ORD-LGA              1.2         152
599  Flight600  41821  ORD-JFK              2.3          98

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
598             0.708333               275       45375             5
599             0.750000               275       50875             7

     Flight Year
598         2015
599         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
600  Flight601  42260  ORD-ATL              6.9          32
601  Flight602  42358  ORD-JFK              3.5         145

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
600             0.562500               200       37000             9
601             0.541667               250       46250            12

     Flight Year
600         2015
601         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
602  Flight603  41971  ORD-LAX             10.3         134
603  Flight604  42344  ORD-BOS              2.6          49

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
602             0.333333               525       97125            11
603             0.291667               300       49500            12

     Flight Year
602         2014
603         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
604  Flight605  42024  ORD-MCO              1.9          65
605  Flight606  42094  ORD-BOS              2.5          26

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
604                0.625               250       45250             1
605                0.750               300       55500             3

     Flight Year
604         2015
605         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
606  Flight607  42220  ORD-PHX              1.8          15
607  Flight608  42353  ORD-SFO              0.5          56

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
606             0.708333               275       50875             8
607             0.833333               375       61875            12

     Flight Year
606         2015
607         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
608  Flight609  41734  ORD-ATL              7.9          66
609  Flight610  41961  ORD-DTW              2.0         110

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
608             0.645833               200       36200             4
609             0.666667               115       21275            11

     Flight Year
608         2014
609         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
610  Flight611  42359  ORD-DFW              1.7         159
611  Flight612  42348  ORD-ATL             10.4          78

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
610             0.333333               280       46200            12
611             0.750000               200       36200            12

     Flight Year
610         2015
611         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
612  Flight613  41826  ORD-DFW              1.8           7
613  Flight614  42348  ORD-ATL              6.7          39

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
612             0.750000               220       40700             7
613             0.833333               200       33000            12

     Flight Year
612         2014
613         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
614  Flight615  42041  ORD-MCO              2.8         144
615  Flight616  42251  ORD-MCO              2.8         138

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
614             0.625000               250       46250             2
615             0.291667               250       46250             9

     Flight Year
614         2015
615         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
616  Flight617  41940  ORD-LAX              5.0         159
617  Flight618  41804  ORD-ATL             10.4         103

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
616             0.666667               350       57750            10
617             0.541667               220       40700             6

     Flight Year
616         2014
617         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
618  Flight619  42241  ORD-ATL              7.8         111
619  Flight620  41657  ORD-ATL             10.1         171

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
618             0.354167               220       40700             8
619             0.520833               200       33000             1

     Flight Year
618         2015
619         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
620  Flight621  41896  ORD-LAX              4.9         199
621  Flight622  42140  ORD-ATL              8.2         188

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
620             0.333333               350       57750             9
621             0.354167               200       33000             5

     Flight Year
620         2014
621         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
622  Flight623  41661  ORD-ATL             11.9         187
623  Flight624  42247  ORD-LGA              1.3          56

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
622             0.791667             200.0     33000.0             1
623             0.750000             302.5     49912.5             8

     Flight Year
622         2014
623         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
624  Flight625  41799  ORD-MCO              1.2         195
625  Flight626  41772  ORD-JFK              0.9          42

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
624             0.333333               275       45375             6
625             0.333333               250       41250             5

     Flight Year
624         2014
625         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
626  Flight627  41891  ORD-LAX              5.7         198
627  Flight628  42360  ORD-LGA              4.7          45

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
626             0.666667               350       57750             9
627             0.708333               385       63525            12

     Flight Year
626         2014
627         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
628  Flight629  42246  ORD-IAH              1.4           9
629  Flight630  42008  ORD-BOS              2.2          59

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
628             0.791667               220       40700             8
629             0.750000               300       49500             1

     Flight Year
628         2015
629         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
630  Flight631  42175  ORD-LGA              1.2          57
631  Flight632  41797  ORD-LAS              1.5         142

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
630             0.458333             302.5     49912.5             6
631             0.729167             302.5     55962.5             6

     Flight Year
630         2015
631         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
632  Flight633  41716  ORD-CLT              1.9         103
633  Flight634  41833  ORD-CLT              2.3          17

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
632             0.354167             125.0     23125.0             3
633             0.833333             137.5     25437.5             7

     Flight Year
632         2014
633         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
634  Flight635  41999  ORD-ATL             10.8         177
635  Flight636  41757  ORD-CLT              1.8           6

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
634             0.291667               280       46200            12
635             0.791667               125       23125             4

     Flight Year
634         2014
635         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
636  Flight637  41938  ORD-PHL              2.3         123
637  Flight638  42076  ORD-LAS              3.3         190

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
636             0.791667               275       50875            10
637             0.770833               275       45375             3

     Flight Year
636         2014
637         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
638  Flight639  42028  ORD-DEN              2.9          81
639  Flight640  41841  ORD-SFO              2.8         171

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
638             0.333333             300.0     54300.0             1
639             0.500000             412.5     68062.5             7

     Flight Year
638         2015
639         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
640  Flight641  41669  ORD-PHX              1.7          65
641  Flight642  42057  ORD-IAH              1.7         181

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
640             0.854167               250       45250             1
641             0.583333               200       33000             2

     Flight Year
640         2014
641         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
642  Flight643  41780  ORD-DFW              2.4         150
643  Flight644  42191  ORD-PHL              1.7         105

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
642             0.291667             200.0     37000.0             5
643             0.625000             302.5     55962.5             7

     Flight Year
642         2014
643         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
644  Flight645  41760  ORD-DFW              2.3         183
645  Flight646  41834  ORD-PHX              2.1         185

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
644             0.354167               200       33000             5
645             0.750000               275       45375             7

     Flight Year
644         2014
645         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
646  Flight647  42234  ORD-LAS              4.2          89
647  Flight648  41865  ORD-FLL              2.1          28

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
646             0.729167             302.5     54752.5             8
647             0.354167             330.0     61050.0             8

     Flight Year
646         2015
647         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
648  Flight649  42270  ORD-JFK              2.0         121
649  Flight650  41975  ORD-DEN              2.2         119

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
648             0.333333               250       46250             9
649             0.708333               300       55500            12

     Flight Year
648         2015
649         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
650  Flight651  41675  ORD-PHX              2.2          76
651  Flight652  41948  ORD-CLT              1.1         188

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
650             0.500000               250       45250             2
651             0.791667               125       20625            11

     Flight Year
650         2014
651         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
652  Flight653  42307  ORD-PHX              1.4           3
653  Flight654  41864  ORD-SFO              2.4         206

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
652             0.750000             250.0     46250.0            10
653             0.854167             412.5     68062.5             8

     Flight Year
652         2015
653         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
654  Flight655  42042  ORD-ATL              9.4         128
655  Flight656  41715  ORD-LGA              2.3         197

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
654             0.750000               200       37000             2
655             0.791667               275       45375             3

     Flight Year
654         2015
655         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
656  Flight657  42287  ORD-SEA              1.2          58
657  Flight658  42070  ORD-ATL              9.1          95

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
656             0.791667               350       57750            10
657             0.750000               200       37000             3

     Flight Year
656         2015
657         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
658  Flight659  42211  ORD-IAH              1.9         118
659  Flight660  41999  ORD-LAX              7.2         198

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
658                0.750               220       40700             7
659                0.625               490       80850            12

     Flight Year
658         2015
659         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
660  Flight661  41822  ORD-CLT              3.0         153
661  Flight662  41956  ORD-MIA              1.1         176

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
660             0.791667             137.5     22687.5             7
661             0.812500             300.0     49500.0            11

     Flight Year
660         2014
661         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
662  Flight663  42048  ORD-CLT              2.0          36
663  Flight664  42008  ORD-ATL             11.7          93

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
662             0.291667               125       20625             2
663             0.875000               200       37000             1

     Flight Year
662         2015
663         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
664  Flight665  41766  ORD-MIA              1.4          66
665  Flight666  42108  ORD-CLT              1.1          77

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
664             0.291667               300       54300             5
665             0.312500               125       22625             4

     Flight Year
664         2014
665         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
666  Flight667  42366  ORD-ATL              7.2          90
667  Flight668  42332  ORD-IAH              4.1           4

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
666               0.5000               200       36200            12
667               0.6875               300       55500            11

     Flight Year
666         2015
667         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
668  Flight669  41722  ORD-DEN              3.1           8
669  Flight670  42230  ORD-ATL              8.7          89

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
668             0.333333               300       55500             3
669             0.812500               220       39820             8

     Flight Year
668         2014
669         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
670  Flight671  41677  ORD-SFO              2.1          33
671  Flight672  42058  ORD-ATL              8.0         152

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
670             0.750000               375       69375             2
671             0.708333               200       33000             2

     Flight Year
670         2014
671         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
672  Flight673  42325  ORD-IAD              2.2         189
673  Flight674  41854  ORD-FLL              2.3          31

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
672             0.416667               300       49500            11
673             0.437500               330       61050             8

     Flight Year
672         2015
673         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
674  Flight675  41996  ORD-SFO              3.0          56
675  Flight676  42298  ORD-MSP              1.7          63

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
674             0.375000               525       86625            12
675             0.791667               115       20815            10

     Flight Year
674         2014
675         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
676  Flight677  42112  ORD-BOS              2.5         195
677  Flight678  41681  ORD-PHL              1.6          55

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
676             0.312500               300       49500             4
677             0.291667               275       45375             2

     Flight Year
676         2015
677         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
678  Flight679  42169  ORD-DEN              2.4          40
679  Flight680  42218  ORD-CLT              2.6          80

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
678             0.312500             330.0     54450.0             6
679             0.854167             137.5     24887.5             8

     Flight Year
678         2015
679         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
680  Flight681  41832  ORD-LAX              4.1         175
681  Flight682  41642  ORD-PHL              2.0          39

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
680             0.500000               385       63525             7
681             0.791667               275       45375             1

     Flight Year
680         2014
681         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
682  Flight683  42167  ORD-CLT              2.2          65
683  Flight684  42122  ORD-SFO              2.1          61

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
682             0.562500             137.5     24887.5             6
683             0.333333             375.0     61875.0             4

     Flight Year
682         2015
683         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
684  Flight685  42034  ORD-EWR              1.7         172
685  Flight686  42141  ORD-SFO              2.0          36

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
684             0.479167               225       37125             1
685             0.854167               375       61875             5

     Flight Year
684         2015
685         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
686  Flight687  41977  ORD-EWR              0.4         165
687  Flight688  41762  ORD-CLT              2.8          50

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
686             0.416667               225       37125            12
687             0.333333               125       20625             5

     Flight Year
686         2014
687         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
688  Flight689  41986  ORD-DFW              0.6         191
689  Flight690  41980  ORD-MIA              1.6         169

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
688               0.3125               200       33000            12
689               0.7500               300       49500            12

     Flight Year
688         2014
689         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
690  Flight691  41718  ORD-BOS              0.3          18
691  Flight692  42066  ORD-PHX              0.5          66

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
690             0.416667               300       55500             3
691             0.666667               250       45250             3

     Flight Year
690         2014
691         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
692  Flight693  42294  ORD-LAS              1.1         111
693  Flight694  42295  ORD-DEN              2.5         132

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
692             0.812500               275       50875            10
693             0.708333               300       55500            10

     Flight Year
692         2015
693         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
694  Flight695  42030  ORD-MIA              1.1         201
695  Flight696  42282  ORD-PHX              2.0         109

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
694             0.354167               300       49500             1
695             0.458333               250       46250            10

     Flight Year
694         2015
695         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
696  Flight697  42039  ORD-LAX              2.6          90
697  Flight698  41995  ORD-PHX              4.3          33

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
696             0.791667               350       63350             2
697             0.291667               350       64750            12

     Flight Year
696         2015
697         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
698  Flight699  41915  ORD-DFW              0.8          64
699  Flight700  41874  ORD-BOS              1.8         142

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
698             0.291667               200       36200            10
699             0.583333               330       61050             8

     Flight Year
698         2014
699         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
700  Flight701  41909  ORD-IAH              3.1           3
701  Flight702  41986  ORD-SFO              1.7          46

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
700             0.541667               200       37000             9
701             0.291667               375       61875            12

     Flight Year
700         2014
701         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
702  Flight703  42217  ORD-MSP              1.5          37
703  Flight704  41861  ORD-JFK              2.7         103

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
702             0.750000             126.5     20872.5             8
703             0.354167             275.0     50875.0             8

     Flight Year
702         2015
703         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
704  Flight705  42272  ORD-JFK              1.7         196
705  Flight706  41863  ORD-JFK              2.1         137

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
704               0.8125               250       41250             9
705               0.6875               275       50875             8

     Flight Year
704         2015
705         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
706  Flight707  42177  ORD-JFK              3.3          86
707  Flight708  41669  ORD-CLT              1.4          55

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
706                0.875               275       49775             6
707                0.750               125       20625             1

     Flight Year
706         2015
707         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
708  Flight709  41805  ORD-FLL              2.6         113
709  Flight710  41780  ORD-JFK              2.8          49

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
708               0.5000               330       61050             6
709               0.8125               250       41250             5

     Flight Year
708         2014
709         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
710  Flight711  42315  ORD-SEA              2.7         200
711  Flight712  42043  ORD-IAD              3.0         107

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
710             0.333333               350       57750            11
711             0.729167               300       55500             2

     Flight Year
710         2015
711         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
712  Flight713  41645  ORD-BOS              1.4          91
713  Flight714  41874  ORD-ATL             11.2          17

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
712               0.8125               300       55500             1
713               0.8125               220       40700             8

     Flight Year
712         2014
713         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
714  Flight715  41694  ORD-JFK              2.1          85
715  Flight716  42178  ORD-EWR              2.9          29

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
714             0.312500             250.0     45250.0             2
715             0.791667             247.5     45787.5             6

     Flight Year
714         2014
715         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
716  Flight717  42212  ORD-PHL              2.1         114
717  Flight718  41827  ORD-CLT              1.8         120

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
716             0.666667             302.5     55962.5             7
717             0.770833             137.5     25437.5             7

     Flight Year
716         2015
717         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
718  Flight719  42141  ORD-EWR              1.5          37
719  Flight720  41708  ORD-SEA              3.7         167

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
718             0.791667               225       37125             5
719             0.812500               350       57750             3

     Flight Year
718         2015
719         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
720  Flight721  41835  ORD-DFW              2.1         195
721  Flight722  41702  ORD-LGA              2.5          13

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
720             0.500000               220       36300             7
721             0.333333               275       50875             3

     Flight Year
720         2014
721         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
722  Flight723  42236  ORD-LAX              6.3         189
723  Flight724  42332  ORD-DEN              3.2         139

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
722             0.812500               385       63525             8
723             0.479167               450       83250            11

     Flight Year
722         2015
723         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
724  Flight725  41859  ORD-LAX              5.5         169
725  Flight726  42124  ORD-SFO              2.5         209

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
724             0.312500               385       63525             8
725             0.833333               375       61875             4

     Flight Year
724         2014
725         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
726  Flight727  42095  ORD-DEN              1.5         137
727  Flight728  41810  ORD-DFW              3.0           7

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
726             0.708333               300       55500             4
727             0.583333               220       40700             6

     Flight Year
726         2015
727         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
728  Flight729  42217  ORD-PHL              1.4         198
729  Flight730  42331  ORD-IAH              2.8          83

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
728             0.854167             302.5     49912.5             8
729             0.583333             300.0     54300.0            11

     Flight Year
728         2015
729         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
730  Flight731  41738  ORD-EWR              0.8         139
731  Flight732  41918  ORD-DEN              1.5         155

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
730             0.291667               225       41625             4
731             0.291667               300       49500            10

     Flight Year
730         2014
731         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
732  Flight733  42117  ORD-MCO              0.6         104
733  Flight734  42162  ORD-BOS              1.5          76

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
732             0.291667               250       46250             4
733             0.333333               330       59730             6

     Flight Year
732         2015
733         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
734  Flight735  41782  ORD-DFW              0.9         161
735  Flight736  42204  ORD-SEA              0.1         126

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
734             0.833333               200       33000             5
735             0.458333               385       71225             7

     Flight Year
734         2014
735         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
736  Flight737  42042  ORD-PHL              3.3         188
737  Flight738  41969  ORD-LAX             10.3          96

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
736             0.708333               275       45375             2
737             0.895833               525       97125            11

     Flight Year
736         2015
737         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
738  Flight739  42230  ORD-DFW              2.2          68
739  Flight740  42152  ORD-ATL              9.7          98

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
738             0.812500               220       39820             8
739             0.708333               200       37000             5

     Flight Year
738         2015
739         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
740  Flight741  42327  ORD-MIA              1.4         117
741  Flight742  41814  ORD-DTW              2.8         129

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
740             0.708333             300.0     55500.0            11
741             0.583333             126.5     23402.5             6

     Flight Year
740         2015
741         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
742  Flight743  42178  ORD-LGA              1.1         178
743  Flight744  42244  ORD-JFK              1.4          49

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
742             0.750000             302.5     49912.5             6
743             0.458333             275.0     45375.0             8

     Flight Year
742         2015
743         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
744  Flight745  42048  ORD-JFK              1.3         136
745  Flight746  42347  ORD-FLL              3.0         190

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
744             0.750000               250       46250             2
745             0.708333               300       49500            12

     Flight Year
744         2015
745         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
746  Flight747  41725  ORD-CLT              2.4         109
747  Flight748  41900  ORD-EWR              2.5           7

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
746                 0.75               125       23125             3
747                 0.50               225       41625             9

     Flight Year
746         2014
747         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
748  Flight749  42091  ORD-IAH              1.9          19
749  Flight750  42256  ORD-BOS              1.3         194

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
748             0.750000               200       37000             3
749             0.583333               300       49500             9

     Flight Year
748         2015
749         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
750  Flight751  41885  ORD-LAX              3.9          30
751  Flight752  41737  ORD-DFW              1.2         135

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
750             0.750000               350       64750             9
751             0.770833               200       37000             4

     Flight Year
750         2014
751         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
752  Flight753  41666  ORD-DTW              1.1         124
753  Flight754  41854  ORD-LAS              1.4          10

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
752             0.458333             115.0     21275.0             1
753             0.750000             302.5     55962.5             8

     Flight Year
752         2014
753         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
754  Flight755  42346  ORD-LAX              4.7         190
755  Flight756  42029  ORD-CLT              3.0           5

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
754             0.458333               350       57750            12
755             0.291667               125       23125             1

     Flight Year
754         2015
755         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
756  Flight757  42234  ORD-ATL             10.0          16
757  Flight758  42190  ORD-DFW              1.8         160

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
756               0.3125               220       40700             8
757               0.7500               220       36300             7

     Flight Year
756         2015
757         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
758  Flight759  42279  ORD-LAX              2.5          33
759  Flight760  42255  ORD-LAX              3.2         143

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
758               0.5625               350       64750            10
759               0.8750               350       64750             9

     Flight Year
758         2015
759         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
760  Flight761  41800  ORD-IAH              1.9          12
761  Flight762  42318  ORD-LAS              1.0         112

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
760             0.541667               220       40700             6
761             0.708333               275       50875            11

     Flight Year
760         2014
761         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
762  Flight763  42333  ORD-SEA              6.2          52
763  Flight764  42309  ORD-PHX              1.3          15

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
762             0.541667               525       86625            11
763             0.500000               250       46250            11

     Flight Year
762         2015
763         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
764  Flight765  41742  ORD-BWI              1.5         181
765  Flight766  42085  ORD-MCO              2.0         109

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
764                0.750               240       39600             4
765                0.625               250       46250             3

     Flight Year
764         2014
765         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
766  Flight767  42036  ORD-PHX              3.4          25
767  Flight768  42329  ORD-CLT              2.1         201

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
766             0.479167               250       46250             2
767             0.625000               125       20625            11

     Flight Year
766         2015
767         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
768  Flight769  41681  ORD-CLT              2.3         168
769  Flight770  41790  ORD-DFW              2.7          55

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
768             0.791667               125       20625             2
769             0.791667               200       33000             5

     Flight Year
768         2014
769         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
770  Flight771  41782  ORD-LGA              2.8          95
771  Flight772  42242  ORD-PHX              1.4          63

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
770             0.437500               275       50875             5
771             0.791667               275       49775             8

     Flight Year
770         2014
771         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
772  Flight773  42348  ORD-SLC              1.7         205
773  Flight774  42243  ORD-ATL              9.6         192

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
772             0.312500               290       47850            12
773             0.645833               220       36300             8

     Flight Year
772         2015
773         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
774  Flight775  41968  ORD-MIA              3.0          66
775  Flight776  42318  ORD-BOS              3.4          52

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
774             0.312500               450       81450            11
775             0.604167               300       49500            11

     Flight Year
774         2014
775         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
776  Flight777  41788  ORD-PHL              1.7          62
777  Flight778  41792  ORD-ATL              8.3         167

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
776             0.541667               275       45375             5
777             0.791667               220       36300             6

     Flight Year
776         2014
777         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
778  Flight779  41724  ORD-SFO              2.6          36
779  Flight780  41724  ORD-CLT              1.0          92

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
778               0.6250               375       61875             3
779               0.8125               125       23125             3

     Flight Year
778         2014
779         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
780  Flight781  41894  ORD-FLL              2.0          18
781  Flight782  42002  ORD-PHL              1.9          67

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
780                0.750               300       55500             9
781                0.875               275       49775            12

     Flight Year
780         2014
781         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
782  Flight783  42020  ORD-LGA              1.8          40
783  Flight784  41827  ORD-LAX              4.1          32

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
782             0.750000               275       45375             1
783             0.291667               385       71225             7

     Flight Year
782         2015
783         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
784  Flight785  42285  ORD-PHX              1.2         153
785  Flight786  41950  ORD-JFK              2.2         141

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
784             0.791667               250       41250            10
785             0.291667               250       46250            11

     Flight Year
784         2015
785         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
786  Flight787  42335  ORD-DEN              6.7          20
787  Flight788  41995  ORD-MSP              7.0         186

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
786             0.291667               450       83250            11
787             0.750000               161       26565            12

     Flight Year
786         2015
787         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
788  Flight789  41844  ORD-EWR              1.8         195
789  Flight790  41777  ORD-ATL             10.2          86

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
788             0.833333             247.5     40837.5             7
789             0.541667             200.0     36200.0             5

     Flight Year
788         2014
789         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
790  Flight791  41861  ORD-JFK              1.8         200
791  Flight792  41903  ORD-JFK              3.1          99

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
790             0.291667               275       45375             8
791             0.791667               250       46250             9

     Flight Year
790         2014
791         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
792  Flight793  41684  ORD-DEN              3.6         167
793  Flight794  41893  ORD-PHX              1.6          43

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
792             0.666667               300       49500             2
793             0.708333               250       41250             9

     Flight Year
792         2014
793         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
794  Flight795  42007  ORD-LGA              1.1          31
795  Flight796  42053  ORD-SEA              1.8          29

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
794             0.291667               275       50875             1
795             0.708333               350       64750             2

     Flight Year
794         2015
795         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
796  Flight797  41970  ORD-PHX              5.2          94
797  Flight798  42190  ORD-LAX              6.4         172

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
796             0.791667               375       69375            11
797             0.750000               385       63525             7

     Flight Year
796         2014
797         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
798  Flight799  41857  ORD-BOS              2.6         188
799  Flight800  41874  ORD-FLL              2.5         149

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
798             0.333333               330       54450             8
799             0.875000               330       61050             8

     Flight Year
798         2014
799         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
800  Flight801  41862  ORD-SEA              2.3         131
801  Flight802  42028  ORD-LAX              3.5         153

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
800             0.291667               385       71225             8
801             0.291667               350       57750             1

     Flight Year
800         2014
801         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
802  Flight803  41822  ORD-SFO              0.4         194
803  Flight804  41794  ORD-DFW              2.0          45

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
802             0.291667             412.5     68062.5             7
803             0.708333             220.0     36300.0             6

     Flight Year
802         2014
803         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
804  Flight805  41766  ORD-DEN              2.7         141
805  Flight806  41641  ORD-ATL              9.0         159

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
804             0.750000               300       55500             5
805             0.645833               200       33000             1

     Flight Year
804         2014
805         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
806  Flight807  41829  ORD-FLL              2.7         178
807  Flight808  41909  ORD-LAX              4.1          34

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
806             0.333333               330       54450             7
807             0.666667               350       64750             9

     Flight Year
806         2014
807         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
808  Flight809  42166  ORD-ATL             11.4         205
809  Flight810  42306  ORD-LAS              1.3          57

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
808             0.666667               220       36300             6
809             0.583333               275       45375            10

     Flight Year
808         2015
809         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
810  Flight811  41776  ORD-LAX              4.0         124
811  Flight812  41996  ORD-MIA              5.7          55

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
810             0.791667               350       64750             5
811             0.833333               420       69300            12

     Flight Year
810         2014
811         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
812  Flight813  41857  ORD-SFO              2.2         183
813  Flight814  41800  ORD-PHX              1.1           9

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
812             0.458333             412.5     68062.5             8
813             0.416667             275.0     50875.0             6

     Flight Year
812         2014
813         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
814  Flight815  41841  ORD-BOS              1.5          44
815  Flight816  42251  ORD-IAD              1.7         116

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
814             0.708333               330       54450             7
815             0.729167               300       55500             9

     Flight Year
814         2014
815         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
816  Flight817  42368  ORD-DFW              1.7          35
817  Flight818  41778  ORD-ATL              8.7         140

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
816             0.416667               200       37000            12
817             0.875000               200       37000             5

     Flight Year
816         2015
817         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
818  Flight819  41820  ORD-DEN              1.5          61
819  Flight820  41987  ORD-JFK              1.6          16

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
818             0.791667               330       54450             6
819             0.604167               250       46250            12

     Flight Year
818         2014
819         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
820  Flight821  42033  ORD-SEA              1.8          77
821  Flight822  42190  ORD-DFW              1.8         165

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
820             0.291667               350       63350             1
821             0.791667               220       36300             7

     Flight Year
820         2015
821         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
822  Flight823  42093  ORD-IAD              1.1          10
823  Flight824  42333  ORD-LAS              3.7         187

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
822               0.4375             300.0     55500.0             3
823               0.3125             412.5     68062.5            11

     Flight Year
822         2015
823         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
824  Flight825  42122  ORD-IAH              2.8          24
825  Flight826  41973  ORD-DEN              4.8          89

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
824                0.375               200       37000             4
825                0.750               450       81450            11

     Flight Year
824         2015
825         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
826  Flight827  42313  ORD-LAS              2.9         168
827  Flight828  41777  ORD-SEA              2.3          88

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
826             0.541667               275       45375            11
827             0.354167               350       63350             5

     Flight Year
826         2015
827         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
828  Flight829  41694  ORD-CLT              2.7         182
829  Flight830  42238  ORD-MCO              1.8         140

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
828             0.416667               125       20625             2
829             0.750000               275       50875             8

     Flight Year
828         2014
829         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
830  Flight831  42365  ORD-MIA              4.7          64
831  Flight832  41881  ORD-BOS              1.6          68

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
830             0.854167               420       76020            12
831             0.333333               330       59730             8

     Flight Year
830         2015
831         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
832  Flight833  41872  ORD-ATL             10.2         171
833  Flight834  41713  ORD-DTW              1.8          74

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
832             0.791667               220       36300             8
833             0.854167               115       20815             3

     Flight Year
832         2014
833         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
834  Flight835  42272  ORD-SEA              1.7          36
835  Flight836  42041  ORD-DEN              1.6         179

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
834             0.708333               350       57750             9
835             0.791667               300       49500             2

     Flight Year
834         2015
835         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
836  Flight837  41876  ORD-SFO              1.7         161
837  Flight838  42302  ORD-LAS              2.3         139

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
836             0.833333             412.5     68062.5             8
837             0.875000             275.0     50875.0            10

     Flight Year
836         2014
837         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
838  Flight839  42186  ORD-BOS              0.9         126
839  Flight840  41838  ORD-LAS              1.3         129

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
838             0.312500             330.0     61050.0             7
839             0.416667             302.5     55962.5             7

     Flight Year
838         2015
839         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
840  Flight841  41807  ORD-PHL              2.7         143
841  Flight842  41806  ORD-IAD              2.5          79

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
840             0.791667             302.5     55962.5             6
841             0.625000             330.0     59730.0             6

     Flight Year
840         2014
841         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
842  Flight843  42100  ORD-DFW              1.4         124
843  Flight844  41695  ORD-CLT              2.7          16

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
842             0.291667               200       37000             4
843             0.541667               125       23125             2

     Flight Year
842         2015
843         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
844  Flight845  42079  ORD-ATL              9.3         197
845  Flight846  42135  ORD-EWR              1.5         187

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
844             0.791667               200       33000             3
845             0.708333               225       37125             5

     Flight Year
844         2015
845         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
846  Flight847  41836  ORD-JFK              1.9          18
847  Flight848  42156  ORD-SEA              1.6         195

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
846             0.562500               275       50875             7
847             0.854167               385       63525             6

     Flight Year
846         2014
847         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
848  Flight849  41945  ORD-LGA              0.8          89
849  Flight850  41968  ORD-MIA              4.6         159

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
848             0.291667               275       49775            11
849             0.291667               450       74250            11

     Flight Year
848         2014
849         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
850  Flight851  41839  ORD-JFK              1.6         200
851  Flight852  41692  ORD-DTW              2.4          66

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
850             0.479167               275       45375             7
851             0.791667               115       20815             2

     Flight Year
850         2014
851         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
852  Flight853  42363  ORD-LAX              6.2         118
853  Flight854  42352  ORD-JFK              3.2         100

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
852               0.8125               490       90650            12
853               0.8750               250       46250            12

     Flight Year
852         2015
853         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
854  Flight855  42285  ORD-ATL             12.0           5
855  Flight856  42210  ORD-ATL              9.8         111

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
854             0.500000               200       37000            10
855             0.770833               220       40700             7

     Flight Year
854         2015
855         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
856  Flight857  41855  ORD-CLT              2.9          40
857  Flight858  41969  ORD-PHL              3.9          72

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
856             0.708333             137.5     22687.5             8
857             0.312500             412.5     74662.5            11

     Flight Year
856         2014
857         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
858  Flight859  41852  ORD-DFW              1.9         116
859  Flight860  42209  ORD-PHL              2.1         138

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
858             0.604167             220.0     40700.0             8
859             0.708333             302.5     55962.5             7

     Flight Year
858         2014
859         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
860  Flight861  42244  ORD-ATL             12.2          16
861  Flight862  42106  ORD-CLT              1.4         165

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
860             0.770833               220       40700             8
861             0.541667               125       20625             4

     Flight Year
860         2015
861         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
862  Flight863  42361  ORD-DEN              3.1          98
863  Flight864  41851  ORD-LAX              5.1          81

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
862             0.625000               420       77700            12
863             0.291667               385       69685             7

     Flight Year
862         2015
863         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
864  Flight865  42068  ORD-JFK              1.7          33
865  Flight866  41791  ORD-DEN              1.7          55

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
864             0.479167               250       46250             3
865             0.312500               330       54450             6

     Flight Year
864         2015
865         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
866  Flight867  41915  ORD-SEA              2.1          32
867  Flight868  42207  ORD-LAS              2.5          84

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
866             0.833333             350.0     64750.0            10
867             0.708333             302.5     54752.5             7

     Flight Year
866         2014
867         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
868  Flight869  41705  ORD-MIA              1.3         165
869  Flight870  41997  ORD-LAS              5.9          73

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
868             0.708333               300       49500             3
869             0.791667               385       69685            12

     Flight Year
868         2014
869         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
870  Flight871  42228  ORD-DEN              3.3         162
871  Flight872  42197  ORD-FLL              0.2         132

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
870             0.333333               330       54450             8
871             0.791667               330       61050             7

     Flight Year
870         2015
871         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
872  Flight873  42241  ORD-SFO              2.0         134
873  Flight874  42358  ORD-LAX              3.8          89

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
872             0.291667             412.5     76312.5             8
873             0.291667             350.0     63350.0            12

     Flight Year
872         2015
873         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
874  Flight875  41809  ORD-JFK              2.4          92
875  Flight876  42213  ORD-LAX              7.3         149

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
874             0.520833               275       50875             6
875             0.791667               385       71225             7

     Flight Year
874         2014
875         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
876  Flight877  41958  ORD-LAX              3.8           6
877  Flight878  42346  ORD-DFW              2.3          75

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
876             0.708333               350       64750            11
877             0.729167               200       36200            12

     Flight Year
876         2014
877         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
878  Flight879  42176  ORD-PHX              1.8         190
879  Flight880  41752  ORD-MCO              2.8         157

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
878             0.291667               275       45375             6
879             0.729167               250       41250             4

     Flight Year
878         2015
879         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
880  Flight881  41661  ORD-LAX              2.5          11
881  Flight882  41657  ORD-LAX              3.5         157

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
880             0.812500               350       64750             1
881             0.708333               350       57750             1

     Flight Year
880         2014
881         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
882  Flight883  41873  ORD-ATL              8.6          29
883  Flight884  42086  ORD-PHX              0.4         107

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
882             0.291667               220       40700             8
883             0.312500               250       46250             3

     Flight Year
882         2014
883         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
884  Flight885  41784  ORD-BWI              1.3         120
885  Flight886  42307  ORD-DEN              3.1          52

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
884             0.291667               240       44400             5
885             0.291667               300       49500            10

     Flight Year
884         2014
885         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
886  Flight887  41706  ORD-LAX              3.2         204
887  Flight888  42229  ORD-IAH              2.2          37

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
886             0.854167               350       57750             3
887             0.354167               220       36300             8

     Flight Year
886         2014
887         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
888  Flight889  42118  ORD-PHX              2.3          60
889  Flight890  41683  ORD-CLT              2.3         105

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
888             0.541667               250       41250             4
889             0.812500               125       23125             2

     Flight Year
888         2015
889         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
890  Flight891  42119  ORD-JFK              2.2          98
891  Flight892  41846  ORD-LAX              7.2          16

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
890             0.437500               250       46250             4
891             0.854167               385       71225             7

     Flight Year
890         2015
891         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
892  Flight893  42222  ORD-MSP              2.1         182
893  Flight894  42292  ORD-MCO              3.0         204

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
892                0.750             126.5     20872.5             8
893                0.625             250.0     41250.0            10

     Flight Year
892         2015
893         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
894  Flight895  41820  ORD-PHL              0.8          24
895  Flight896  41816  ORD-EWR              1.1         153

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
894             0.854167             302.5     55962.5             6
895             0.312500             247.5     40837.5             6

     Flight Year
894         2014
895         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
896  Flight897  41927  ORD-DFW              1.6         145
897  Flight898  41922  ORD-LAX              4.8          32

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
896             0.291667               200       37000            10
897             0.291667               350       64750            10

     Flight Year
896         2014
897         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
898  Flight899  41847  ORD-DFW              2.8         200
899  Flight900  41754  ORD-LAS              2.2          61

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
898             0.416667               220       36300             7
899             0.708333               275       45375             4

     Flight Year
898         2014
899         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
900  Flight901  42369  ORD-ATL             11.2         144
901  Flight902  41914  ORD-SFO              1.5          74

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
900             0.708333               200       37000            12
901             0.645833               375       67875            10

     Flight Year
900         2015
901         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
902  Flight903  41968  ORD-CLT              3.2         141
903  Flight904  41980  ORD-IAD              1.0         100

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
902             0.541667             187.5     34687.5            11
903             0.750000             300.0     55500.0            12

     Flight Year
902         2014
903         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
904  Flight905  42298  ORD-LAX              4.0          33
905  Flight906  41835  ORD-DFW              1.4         181

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
904             0.770833               350       64750            10
905             0.354167               220       36300             7

     Flight Year
904         2015
905         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
906  Flight907  42315  ORD-MCO              0.9         210
907  Flight908  41823  ORD-CLT              2.1          92

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
906             0.895833             250.0     41250.0            11
907             0.750000             137.5     25437.5             7

     Flight Year
906         2015
907         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
908  Flight909  41853  ORD-LAX              4.7         207
909  Flight910  42048  ORD-LAX              4.3          21

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
908             0.708333               385       63525             8
909             0.291667               350       64750             2

     Flight Year
908         2014
909         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
910  Flight911  41830  ORD-DEN              1.5          76
911  Flight912  42183  ORD-FLL              1.8          61

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
910             0.770833               330       59730             7
911             0.666667               330       54450             6

     Flight Year
910         2014
911         2015

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
912  Flight913  42105  ORD-LAS                2          79
913  Flight914  42296  ORD-DEN                2          85

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
912             0.791667               275       49775             4
913             0.791667               300       54300            10

     Flight Year
912         2015
913         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
914  Flight915  42098  ORD-DEN              2.2         142
915  Flight916  41971  ORD-DEN              4.1          61

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
914             0.729167               300       55500             4
915             0.416667               450       74250            11

     Flight Year
914         2015
915         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
916  Flight917  41765  ORD-JFK              2.2          24
917  Flight918  42008  ORD-BOS              1.6          53

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
916             0.750000               250       46250             5
917             0.645833               300       49500             1

     Flight Year
916         2014
917         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
918  Flight919  42072  ORD-ATL              9.0          95
919  Flight920  42363  ORD-DEN              4.9         129

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
918             0.291667               200       37000             3
919             0.750000               420       77700            12

     Flight Year
918         2015
919         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
920  Flight921  42335  ORD-CLT              4.7         197
921  Flight922  42001  ORD-SFO              2.7          21

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
920             0.729167             187.5     30937.5            11
921             0.791667             525.0     97125.0            12

     Flight Year
920         2015
921         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
922  Flight923  41827  ORD-LAX              5.0          19
923  Flight924  41768  ORD-FLL              1.4          44

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
922             0.333333               385       71225             7
923             0.291667               300       49500             5

     Flight Year
922         2014
923         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
924  Flight925  41757  ORD-DTW              1.3         203
925  Flight926  41933  ORD-DFW              1.6           8

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
924             0.312500               115       18975             4
925             0.291667               200       37000            10

     Flight Year
924         2014
925         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
926  Flight927  41972  ORD-MSP              3.6         101
927  Flight928  42255  ORD-PHL              2.0         171

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
926             0.750000             172.5     31912.5            11
927             0.416667             275.0     45375.0             9

     Flight Year
926         2014
927         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
928  Flight929  41860  ORD-BOS              2.3         146
929  Flight930  41882  ORD-SFO              1.9         131

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
928             0.833333             330.0     61050.0             8
929             0.770833             412.5     76312.5             8

     Flight Year
928         2014
929         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
930  Flight931  42124  ORD-IAH              2.0          69
931  Flight932  41946  ORD-IAD              2.2          98

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
930             0.291667               200       36200             4
931             0.458333               300       55500            11

     Flight Year
930         2015
931         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
932  Flight933  41996  ORD-SEA              4.2          33
933  Flight934  42069  ORD-MSP              1.8         172

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
932             0.791667               490       90650            12
933             0.729167               115       18975             3

     Flight Year
932         2014
933         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
934  Flight935  41759  ORD-PHX              2.1           3
935  Flight936  41695  ORD-ATL             10.0         176

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
934             0.833333               250       46250             4
935             0.625000               200       33000             2

     Flight Year
934         2014
935         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
936  Flight937  41759  ORD-SFO              2.7         173
937  Flight938  42225  ORD-MSP              2.2         184

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
936             0.791667             375.0     61875.0             4
937             0.750000             126.5     20872.5             8

     Flight Year
936         2014
937         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
938  Flight939  41792  ORD-LAS              2.5         210
939  Flight940  41826  ORD-JFK              1.7         206

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
938             0.750000             302.5     49912.5             6
939             0.708333             275.0     45375.0             7

     Flight Year
938         2014
939         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
940  Flight941  42311  ORD-IAH              1.6         116
941  Flight942  41713  ORD-SEA              2.4          93

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
940             0.583333               200       37000            11
941             0.416667               350       64750             3

     Flight Year
940         2015
941         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
942  Flight943  41641  ORD-LGA              2.7          19
943  Flight944  41855  ORD-CLT              2.9         161

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
942             0.416667             275.0     50875.0             1
943             0.791667             137.5     22687.5             8

     Flight Year
942         2014
943         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
944  Flight945  42238  ORD-DTW              1.5          53
945  Flight946  42293  ORD-IAH              1.6         171

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
944             0.791667             126.5     20872.5             8
945             0.291667             200.0     33000.0            10

     Flight Year
944         2015
945         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
946  Flight947  41873  ORD-FLL              2.1          32
947  Flight948  41914  ORD-EWR              2.1          10

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
946             0.541667               330       61050             8
947             0.416667               225       41625            10

     Flight Year
946         2014
947         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
948  Flight949  41924  ORD-IAH              2.0         133
949  Flight950  41791  ORD-JFK              2.4         159

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
948             0.312500               200       37000            10
949             0.791667               275       45375             6

     Flight Year
948         2014
949         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
950  Flight951  42368  ORD-IAH              1.3          61
951  Flight952  41968  ORD-ATL             16.4           8

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
950             0.708333               200       33000            12
951             0.333333               300       55500            11

     Flight Year
950         2015
951         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
952  Flight953  42110  ORD-DFW              0.5          97
953  Flight954  42359  ORD-PHX              4.3          30

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
952             0.791667               200       37000             4
953             0.833333               350       64750            12

     Flight Year
952         2015
953         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
954  Flight955  42047  ORD-ATL             10.3          16
955  Flight956  42233  ORD-PHX              2.6           7

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
954             0.354167               200       37000             2
955             0.437500               275       50875             8

     Flight Year
954         2015
955         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
956  Flight957  41967  ORD-ATL             18.6          37
957  Flight958  42098  ORD-ATL              8.5         139

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
956               0.7500               300       49500            11
957               0.5625               200       37000             4

     Flight Year
956         2014
957         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
958  Flight959  41861  ORD-BOS              2.5           4
959  Flight960  41738  ORD-LGA              2.5         198

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
958             0.375000               330       61050             8
959             0.791667               275       45375             4

     Flight Year
958         2014
959         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
960  Flight961  42094  ORD-ATL             10.3         110
961  Flight962  41778  ORD-PHL              2.4          66

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
960             0.375000               200       37000             3
961             0.791667               275       49775             5

     Flight Year
960         2015
961         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
962  Flight963  42240  ORD-LAS              1.8         115
963  Flight964  41716  ORD-SEA              1.0         200

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
962             0.729167             302.5     55962.5             8
963             0.666667             350.0     57750.0             3

     Flight Year
962         2015
963         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
964  Flight965  42144  ORD-ATL              7.7         162
965  Flight966  42182  ORD-SFO              2.2         151

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
964             0.750000             200.0     33000.0             5
965             0.708333             412.5     76312.5             6

     Flight Year
964         2015
965         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
966  Flight967  41857  ORD-MCO              2.3          63
967  Flight968  42261  ORD-MIA              1.7         195

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
966             0.729167               275       49775             8
967             0.354167               300       49500             9

     Flight Year
966         2014
967         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
968  Flight969  42178  ORD-DEN              1.7         175
969  Flight970  41898  ORD-ATL              9.9          76

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
968             0.854167               330       54450             6
969             0.750000               200       36200             9

     Flight Year
968         2015
969         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
970  Flight971  42203  ORD-PHX              2.2          98
971  Flight972  42023  ORD-DEN              2.2          49

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
970             0.708333               275       50875             7
971             0.625000               300       49500             1

     Flight Year
970         2015
971         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
972  Flight973  41893  ORD-EWR              2.8         171
973  Flight974  41726  ORD-CLT              2.3          54

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
972             0.833333               225       37125             9
973             0.833333               125       20625             3

     Flight Year
972         2014
973         2014

      FlightID   Date  RouteID  Departure Delay  AircraftID  \
974  Flight975  41939  ORD-DFW              2.6         157
975  Flight976  41813  ORD-FLL              2.3         176

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
974             0.416667               200       33000            10
975             0.791667               330       54450             6

     Flight Year
974         2014
975         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
976  Flight977  42317  ORD-PHX              2.0          90
977  Flight978  42101  ORD-IAD              1.5         149

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
976             0.291667               250       45250            11
977             0.375000               300       55500             4

     Flight Year
976         2015
977         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
978  Flight979  41886  ORD-DFW              1.5         185
979  Flight980  41957  ORD-LAX              4.2           3

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
978             0.687500               200       33000             9
979             0.333333               350       64750            11

     Flight Year
978         2014
979         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
980  Flight981  41967  ORD-LAS              6.8          54
981  Flight982  41709  ORD-DEN              2.8         104

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
980             0.708333             412.5     68062.5            11
981             0.770833             300.0     55500.0             3

     Flight Year
980         2014
981         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
982  Flight983  42118  ORD-IAD              1.2         144
983  Flight984  41988  ORD-SEA              1.7         195

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
982             0.416667               300       55500             4
983             0.395833               350       57750            12

     Flight Year
982         2015
983         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
984  Flight985  42229  ORD-CLT              2.4           9
985  Flight986  42091  ORD-PHX              1.5         168

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
984             0.291667             137.5     25437.5             8
985             0.416667             250.0     41250.0             3

     Flight Year
984         2015
985         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
986  Flight987  42017  ORD-SEA              1.9         190
987  Flight988  41955  ORD-JFK              1.2          66

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
986             0.708333               350       57750             1
987             0.708333               250       45250            11

     Flight Year
986         2015
987         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
988  Flight989  42157  ORD-LGA              2.9         127
989  Flight990  41666  ORD-LAX              1.5         159

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
988             0.708333             302.5     55962.5             6
989             0.666667             350.0     57750.0             1

     Flight Year
988         2015
989         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
990  Flight991  41913  ORD-EWR              2.0         207
991  Flight992  42260  ORD-IAH              2.2          87

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
990                0.375               225       37125            10
991                0.500               200       36200             9

     Flight Year
990         2014
991         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
992  Flight993  42180  ORD-IAH              1.2         195
993  Flight994  42260  ORD-PHX              3.4          60

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
992             0.708333               220       36300             6
993             0.833333               250       41250             9

     Flight Year
992         2015
993         2015
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
994  Flight995  41906  ORD-LGA              1.5          44
995  Flight996  41706  ORD-LAX              3.9          43

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
994             0.333333               275       45375             9
995             0.333333               350       57750             3

     Flight Year
994         2014
995         2014
      FlightID   Date  RouteID  Departure Delay  AircraftID  \
996  Flight997  42140  ORD-EWR              2.6         147
997  Flight998  41760  ORD-SEA              1.8          26

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
996             0.375000               225       41625             5
997             0.708333               350       64750             5

     Flight Year
996         2015
997         2014
       FlightID   Date  RouteID  Departure Delay  AircraftID  \
998   Flight999  41886  ORD-BOS              2.9          66
999  Flight1000  41750  ORD-MIA              3.0         209

     Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
998             0.583333               300       54300             9
999             0.791667               300       49500             4

     Flight Year
998         2014
999         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1000  Flight1001  42194  ORD-IAH              1.9         200
1001  Flight1002  42273  ORD-EWR              2.0         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1000             0.833333               220       36300             7
1001             0.750000               225       41625             9

      Flight Year
1000         2015
1001         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1002  Flight1003  41694  ORD-DFW              1.8         132
1003  Flight1004  41970  ORD-BOS              3.9         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1002             0.333333               200       37000             2
1003             0.479167               450       83250            11

      Flight Year
1002         2014
1003         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1004  Flight1005  42175  ORD-IAH              3.1          32
1005  Flight1006  42063  ORD-PHL              1.2          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1004             0.854167               220       40700             6
1005             0.729167               275       50875             2

      Flight Year
1004         2015
1005         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1006  Flight1007  42196  ORD-MSP              0.8          80
1007  Flight1008  42096  ORD-JFK              0.7          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1006             0.875000             126.5     22896.5             7
1007             0.458333             250.0     46250.0             4

      Flight Year
1006         2015
1007         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1008  Flight1009  42072  ORD-BOS              2.6          13
1009  Flight1010  41891  ORD-FLL              1.5          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1008             0.583333               300       55500             3
1009             0.708333               300       55500             9

      Flight Year
1008         2015
1009         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1010  Flight1011  41876  ORD-LAS              1.3         189
1011  Flight1012  41980  ORD-IAH              2.7          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1010             0.312500             302.5     49912.5             8
1011             0.708333             200.0     33000.0            12

      Flight Year
1010         2014
1011         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1012  Flight1013  42155  ORD-LGA              2.8         158
1013  Flight1014  42334  ORD-JFK              3.7         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1012             0.520833               275       45375             5
1013             0.708333               375       61875            11

      Flight Year
1012         2015
1013         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1014  Flight1015  42217  ORD-JFK              2.7         166
1015  Flight1016  42335  ORD-DFW              4.2         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1014                0.750               275       45375             8
1015                0.625               300       55500            11

      Flight Year
1014         2015
1015         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1016  Flight1017  42055  ORD-IAH              1.0         192
1017  Flight1018  41971  ORD-ATL             17.3         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1016             0.333333               200       33000             2
1017             0.458333               300       49500            11

      Flight Year
1016         2015
1017         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1018  Flight1019  41896  ORD-JFK              2.9         110
1019  Flight1020  42088  ORD-MSP              1.4         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1018             0.291667               250       46250             9
1019             0.708333               115       21275             3

      Flight Year
1018         2014
1019         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1020  Flight1021  42169  ORD-LAX              5.5         201
1021  Flight1022  42183  ORD-DEN              2.2          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1020             0.291667               385       63525             6
1021             0.812500               330       61050             6

      Flight Year
1020         2015
1021         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1022  Flight1023  41998  ORD-LAX              6.5         121
1023  Flight1024  42167  ORD-MSP              0.5          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1022             0.791667             490.0     90650.0            12
1023             0.291667             126.5     23402.5             6

      Flight Year
1022         2014
1023         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1024  Flight1025  41858  ORD-LAS              2.1          58
1025  Flight1026  41876  ORD-DEN              1.3         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1024             0.312500             302.5     49912.5             8
1025             0.708333             330.0     61050.0             8

      Flight Year
1024         2014
1025         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1026  Flight1027  42366  ORD-DFW              2.1         114
1027  Flight1028  41977  ORD-PHX              1.5         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1026             0.645833               200       37000            12
1027             0.833333               250       41250            12

      Flight Year
1026         2015
1027         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1028  Flight1029  41849  ORD-DTW              2.5         131
1029  Flight1030  42360  ORD-PHX              2.7          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1028             0.729167             126.5     23402.5             7
1029             0.770833             350.0     57750.0            12

      Flight Year
1028         2014
1029         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1030  Flight1031  41771  ORD-DEN              2.3          45
1031  Flight1032  41975  ORD-IAH              1.4          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1030             0.729167               300       49500             5
1031             0.291667               200       36200            12

      Flight Year
1030         2014
1031         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1032  Flight1033  42294  ORD-LAX              3.4          28
1033  Flight1034  41704  ORD-SFO              2.9         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1032               0.3125               350       64750            10
1033               0.3125               375       69375             3

      Flight Year
1032         2015
1033         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1034  Flight1035  41731  ORD-EWR              1.9           2
1035  Flight1036  42131  ORD-IAH              2.5          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1034             0.458333               225       41625             4
1035             0.750000               200       37000             5

      Flight Year
1034         2014
1035         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1036  Flight1037  41910  ORD-BOS              2.4          17
1037  Flight1038  41908  ORD-EWR              2.1           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1036             0.812500               300       55500             9
1037             0.291667               225       41625             9

      Flight Year
1036         2014
1037         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1038  Flight1039  41997  ORD-BOS              5.0         181
1039  Flight1040  41771  ORD-MCO              2.3          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1038             0.750000               420       69300            12
1039             0.791667               250       45250             5

      Flight Year
1038         2014
1039         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1040  Flight1041  42175  ORD-SEA              1.1         110
1041  Flight1042  41903  ORD-MCO              0.6           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1040             0.791667               385       71225             6
1041             0.791667               250       46250             9

      Flight Year
1040         2015
1041         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1042  Flight1043  41740  ORD-DEN              1.9         177
1043  Flight1044  42165  ORD-JFK              0.6          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1042             0.666667               300       49500             4
1043             0.520833               275       49775             6

      Flight Year
1042         2014
1043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1044  Flight1045  41964  ORD-CLT              2.7         194
1045  Flight1046  42229  ORD-SEA              2.8           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1044             0.708333               125       20625            11
1045             0.583333               385       71225             8

      Flight Year
1044         2014
1045         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1046  Flight1047  42337  ORD-PHL              4.0          76
1047  Flight1048  41713  ORD-PHX              2.7         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1046             0.854167             412.5     74662.5            11
1047             0.895833             250.0     46250.0             3

      Flight Year
1046         2015
1047         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1048  Flight1049  41642  ORD-LAX              3.9         156
1049  Flight1050  42346  ORD-LGA              2.3          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1048             0.791667               350       57750             1
1049             0.333333               275       49775            12

      Flight Year
1048         2014
1049         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1050  Flight1051  41677  ORD-PHX              2.5          56
1051  Flight1052  42236  ORD-LAX              3.6          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1050             0.479167               250       41250             2
1051             0.541667               385       69685             8

      Flight Year
1050         2014
1051         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1052  Flight1053  42037  ORD-JFK              0.8          99
1053  Flight1054  41998  ORD-ATL             16.3          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1052             0.770833               250       46250             2
1053             0.833333               280       50680            12

      Flight Year
1052         2015
1053         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1054  Flight1055  42326  ORD-BOS              1.9         207
1055  Flight1056  42213  ORD-SFO              2.4          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1054               0.6875             300.0     49500.0            11
1055               0.6250             412.5     74662.5             7

      Flight Year
1054         2015
1055         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1056  Flight1057  42100  ORD-IAH              1.4         198
1057  Flight1058  42111  ORD-PHL              2.1          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1056             0.791667               200       33000             4
1057             0.708333               275       50875             4

      Flight Year
1056         2015
1057         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1058  Flight1059  41746  ORD-SFO              2.3         114
1059  Flight1060  41960  ORD-CLT              1.8           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1058             0.708333               375       69375             4
1059             0.791667               125       23125            11

      Flight Year
1058         2014
1059         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1060  Flight1061  42315  ORD-LAX              4.3         179
1061  Flight1062  42120  ORD-SEA              0.9          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1060             0.291667               350       57750            11
1061             0.812500               350       63350             4

      Flight Year
1060         2015
1061         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1062  Flight1063  41646  ORD-BWI              1.9          57
1063  Flight1064  42052  ORD-JFK              2.8          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1062             0.791667               240       39600             1
1063             0.500000               250       46250             2

      Flight Year
1062         2014
1063         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1064  Flight1065  41665  ORD-EWR              2.8          56
1065  Flight1066  42315  ORD-PHX              3.7         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1064             0.416667               225       37125             1
1065             0.791667               250       41250            11

      Flight Year
1064         2014
1065         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1066  Flight1067  41930  ORD-ATL              9.0          33
1067  Flight1068  41853  ORD-IAH              2.3         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1066             0.291667               200       37000            10
1067             0.833333               220       36300             8

      Flight Year
1066         2014
1067         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1068  Flight1069  42025  ORD-CLT              2.2         125
1069  Flight1070  41650  ORD-PHX              1.2         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1068             0.333333               125       23125             1
1069             0.312500               250       41250             1

      Flight Year
1068         2015
1069         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1070  Flight1071  41801  ORD-LAX              4.9         107
1071  Flight1072  42172  ORD-SEA              2.4         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1070             0.833333               385       71225             6
1071             0.291667               385       63525             6

      Flight Year
1070         2014
1071         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1072  Flight1073  41907  ORD-MCO              1.9         129
1073  Flight1074  41941  ORD-LAS              1.9         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1072             0.312500               250       46250             9
1073             0.895833               275       45375            10

      Flight Year
1072         2014
1073         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1074  Flight1075  42151  ORD-PHL              2.4          38
1075  Flight1076  41997  ORD-LAX              4.7          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1074             0.833333               275       45375             5
1075             0.770833               490       90650            12

      Flight Year
1074         2015
1075         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1076  Flight1077  42153  ORD-MCO              2.4         124
1077  Flight1078  41880  ORD-DFW              3.1         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1076               0.8125               250       46250             5
1077               0.3125               220       40700             8

      Flight Year
1076         2015
1077         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1078  Flight1079  41711  ORD-ATL              9.2          44
1079  Flight1080  41773  ORD-SFO              2.2           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1078             0.291667               200       33000             3
1079             0.750000               375       69375             5

      Flight Year
1078         2014
1079         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1080  Flight1081  41819  ORD-LAX              5.5          45
1081  Flight1082  42064  ORD-IAH              1.1         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1080             0.312500               385       63525             6
1081             0.708333               200       37000             3

      Flight Year
1080         2014
1081         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1082  Flight1083  42158  ORD-IAH              1.5         209
1083  Flight1084  42036  ORD-MCO              2.0          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1082             0.708333               220       36300             6
1083             0.791667               250       45250             2

      Flight Year
1082         2015
1083         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1084  Flight1085  41665  ORD-JFK              2.7         137
1085  Flight1086  42217  ORD-DEN              2.4         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1084             0.541667               250       46250             1
1085             0.770833               330       61050             8

      Flight Year
1084         2014
1085         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1086  Flight1087  42052  ORD-ATL              9.4         208
1087  Flight1088  42352  ORD-MSP              1.6         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1086             0.333333               200       33000             2
1087             0.312500               115       18975            12

      Flight Year
1086         2015
1087         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1088  Flight1089  42233  ORD-DTW              2.2         125
1089  Flight1090  41893  ORD-MCO              3.2          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1088             0.541667             126.5     23402.5             8
1089             0.375000             250.0     41250.0             9

      Flight Year
1088         2015
1089         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1090  Flight1091  42106  ORD-LAX              4.4         135
1091  Flight1092  41668  ORD-SLC              1.8          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1090             0.812500               350       64750             4
1091             0.354167               290       53650             1

      Flight Year
1090         2015
1091         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1092  Flight1093  41690  ORD-SEA              2.1          36
1093  Flight1094  41710  ORD-ATL             10.5          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1092             0.458333               350       57750             2
1093             0.833333               200       37000             3

      Flight Year
1092         2014
1093         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1094  Flight1095  42051  ORD-IAD              2.2          35
1095  Flight1096  41816  ORD-IAH              2.8          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1094             0.291667               300       55500             2
1095             0.729167               220       36300             6

      Flight Year
1094         2015
1095         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1096  Flight1097  42334  ORD-CLT              4.0         102
1097  Flight1098  42323  ORD-DFW              1.4         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1096             0.541667             187.5     34687.5            11
1097             0.375000             200.0     37000.0            11

      Flight Year
1096         2015
1097         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1098  Flight1099  42343  ORD-IAH              1.6         174
1099  Flight1100  41875  ORD-PHX              1.7          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1098             0.312500               200       33000            12
1099             0.458333               275       49775             8

      Flight Year
1098         2015
1099         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1100  Flight1101  42313  ORD-IAH              2.9         113
1101  Flight1102  42179  ORD-LAX              7.1         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1100             0.791667               200       37000            11
1101             0.833333               385       71225             6

      Flight Year
1100         2015
1101         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1102  Flight1103  42063  ORD-MIA              1.0         110
1103  Flight1104  42204  ORD-PHX              1.7           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1102             0.666667               300       55500             2
1103             0.708333               275       50875             7

      Flight Year
1102         2015
1103         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1104  Flight1105  42148  ORD-PHX              1.6          74
1105  Flight1106  42188  ORD-DTW              2.3           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1104             0.750000             250.0     45250.0             5
1105             0.708333             126.5     23402.5             7

      Flight Year
1104         2015
1105         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1106  Flight1107  41967  ORD-LGA              3.9         108
1107  Flight1108  42350  ORD-DFW              1.7         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1106             0.312500             412.5     76312.5            11
1107             0.458333             200.0     33000.0            12

      Flight Year
1106         2014
1107         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1108  Flight1109  42123  ORD-EWR                1         181
1109  Flight1110  41656  ORD-ATL                8         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1108             0.708333               225       37125             4
1109             0.291667               200       37000             1

      Flight Year
1108         2015
1109         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1110  Flight1111  42199  ORD-JFK              2.8          26
1111  Flight1112  41750  ORD-EWR              2.3          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1110             0.291667               275       50875             7
1111             0.583333               225       40725             4

      Flight Year
1110         2015
1111         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1112  Flight1113  41660  ORD-LAX              4.7         115
1113  Flight1114  42025  ORD-PHX              1.8         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1112             0.791667               350       64750             1
1113             0.750000               250       46250             1

      Flight Year
1112         2014
1113         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1114  Flight1115  41852  ORD-MIA              3.0         159
1115  Flight1116  42177  ORD-SFO              2.3         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1114             0.520833             330.0     54450.0             8
1115             0.291667             412.5     76312.5             6

      Flight Year
1114         2014
1115         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1116  Flight1117  42219  ORD-LGA              2.4          42
1117  Flight1118  42230  ORD-IAH              1.9          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1116             0.708333             302.5     49912.5             8
1117             0.895833             220.0     40700.0             8

      Flight Year
1116         2015
1117         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1118  Flight1119  42356  ORD-ATL              7.9         151
1119  Flight1120  42359  ORD-DFW              2.0          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1118             0.687500               200       37000            12
1119             0.729167               280       50680            12

      Flight Year
1118         2015
1119         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1120  Flight1121  41943  ORD-LAX              4.6          54
1121  Flight1122  41739  ORD-DEN              2.7         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1120             0.791667               350       57750            10
1121             0.416667               300       55500             4

      Flight Year
1120         2014
1121         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1122  Flight1123  42164  ORD-MIA              2.0         105
1123  Flight1124  42327  ORD-DFW              2.9         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1122             0.750000               330       61050             6
1123             0.770833               200       33000            11

      Flight Year
1122         2015
1123         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1124  Flight1125  41789  ORD-SFO              2.2          29
1125  Flight1126  42137  ORD-SFO              2.4         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1124             0.708333               375       69375             5
1125             0.791667               375       61875             5

      Flight Year
1124         2014
1125         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1126  Flight1127  42357  ORD-PHL              2.7          33
1127  Flight1128  41993  ORD-SFO              0.4         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1126             0.291667               275       50875            12
1127             0.291667               375       69375            12

      Flight Year
1126         2015
1127         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1128  Flight1129  41712  ORD-DFW              1.9         193
1129  Flight1130  42361  ORD-LGA              4.6         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1128             0.708333               200       33000             3
1129             0.458333               385       71225            12

      Flight Year
1128         2014
1129         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1130  Flight1131  42363  ORD-DFW              4.7          96
1131  Flight1132  41823  ORD-ATL             10.2         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1130               0.4375               280       51800            12
1131               0.7500               220       40700             7

      Flight Year
1130         2015
1131         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1132  Flight1133  42212  ORD-DFW              1.3          79
1133  Flight1134  42181  ORD-CLT              3.1         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1132                  0.5             220.0     39820.0             7
1133                  0.5             137.5     22687.5             6

      Flight Year
1132         2015
1133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1134  Flight1135  41982  ORD-ATL              9.3          19
1135  Flight1136  41860  ORD-ATL              9.5          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1134             0.750000               200       37000            12
1135             0.833333               220       36300             8

      Flight Year
1134         2014
1135         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1136  Flight1137  42165  ORD-DFW              2.5         131
1137  Flight1138  41982  ORD-SEA              2.7         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1136             0.854167               220       40700             6
1137             0.291667               350       64750            12

      Flight Year
1136         2015
1137         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1138  Flight1139  42183  ORD-SEA              1.6          68
1139  Flight1140  42076  ORD-BOS              1.8         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1138             0.354167               385       69685             6
1139             0.750000               300       55500             3

      Flight Year
1138         2015
1139         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1140  Flight1141  41936  ORD-DFW              3.2         182
1141  Flight1142  42131  ORD-JFK              1.5          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1140                 0.75               200       33000            10
1141                 0.75               250       45250             5

      Flight Year
1140         2014
1141         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1142  Flight1143  42172  ORD-CLT              1.8          22
1143  Flight1144  41838  ORD-LGA              1.9          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1142             0.812500             137.5     25437.5             6
1143             0.354167             302.5     49912.5             7

      Flight Year
1142         2015
1143         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1144  Flight1145  42271  ORD-MSP              2.5         170
1145  Flight1146  42179  ORD-MIA              1.9          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1144             0.791667               115       18975             9
1145             0.333333               330       61050             6

      Flight Year
1144         2015
1145         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1146  Flight1147  41806  ORD-BOS              2.4          97
1147  Flight1148  42122  ORD-DTW              1.5         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1146             0.812500               330       61050             6
1147             0.791667               115       21275             4

      Flight Year
1146         2014
1147         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1148  Flight1149  42204  ORD-SFO              2.0          90
1149  Flight1150  42123  ORD-BOS              1.9          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1148             0.562500             412.5     74662.5             7
1149             0.791667             300.0     55500.0             4

      Flight Year
1148         2015
1149         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1150  Flight1151  42361  ORD-BWI              2.0         188
1151  Flight1152  42090  ORD-JFK              2.6         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1150             0.770833               336       55440            12
1151             0.333333               250       46250             3

      Flight Year
1150         2015
1151         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1152  Flight1153  41649  ORD-MIA              2.6         122
1153  Flight1154  41774  ORD-ATL             12.2         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1152             0.791667               300       55500             1
1153             0.541667               200       33000             5

      Flight Year
1152         2014
1153         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1154  Flight1155  42051  ORD-ATL             10.2         116
1155  Flight1156  41899  ORD-LAS              1.4           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1154             0.333333               200       37000             2
1155             0.291667               275       50875             9

      Flight Year
1154         2015
1155         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1156  Flight1157  41709  ORD-CLT              2.1         164
1157  Flight1158  41717  ORD-BOS              2.0         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1156             0.375000               125       20625             3
1157             0.708333               300       55500             3

      Flight Year
1156         2014
1157         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1158  Flight1159  42005  ORD-PHX              1.9         172
1159  Flight1160  41840  ORD-DFW              2.3          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1158             0.708333               250       41250             1
1159             0.729167               220       36300             7

      Flight Year
1158         2015
1159         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1160  Flight1161  41954  ORD-BWI              1.9         152
1161  Flight1162  42211  ORD-MCO              3.0          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1160             0.708333               240       39600            11
1161             0.416667               275       50875             7

      Flight Year
1160         2014
1161         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1162  Flight1163  41675  ORD-EWR              1.8         185
1163  Flight1164  42232  ORD-ATL             11.0         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1162             0.312500               225       37125             2
1163             0.541667               220       40700             8

      Flight Year
1162         2014
1163         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1164  Flight1165  42064  ORD-DTW              2.2          60
1165  Flight1166  41858  ORD-FLL              2.5         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1164             0.750000               115       18975             3
1165             0.666667               330       54450             8

      Flight Year
1164         2015
1165         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1166  Flight1167  42264  ORD-SFO              1.4         175
1167  Flight1168  41656  ORD-LAX              3.7         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1166             0.333333               375       61875             9
1167             0.833333               350       64750             1

      Flight Year
1166         2015
1167         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1168  Flight1169  42000  ORD-SFO              2.7          96
1169  Flight1170  42057  ORD-BOS              1.5         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1168               0.4375               525       97125            12
1169               0.3125               300       49500             2

      Flight Year
1168         2014
1169         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1170  Flight1171  42051  ORD-DFW              2.3         178
1171  Flight1172  41766  ORD-LAX              4.0          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1170               0.8125               200       33000             2
1171               0.8125               350       63350             5

      Flight Year
1170         2015
1171         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1172  Flight1173  41998  ORD-CLT              3.3          80
1173  Flight1174  41656  ORD-BOS              1.1          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1172             0.354167               175       31675            12
1173             0.750000               300       54300             1

      Flight Year
1172         2014
1173         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1174  Flight1175  42203  ORD-IAH              1.9         186
1175  Flight1176  42052  ORD-MCO              2.3          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1174             0.708333               220       36300             7
1175             0.791667               250       41250             2

      Flight Year
1174         2015
1175         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1176  Flight1177  42134  ORD-LAS              1.6         146
1177  Flight1178  42257  ORD-JFK              1.2          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1176             0.750000               275       50875             5
1177             0.791667               250       46250             9

      Flight Year
1176         2015
1177         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1178  Flight1179  42030  ORD-DEN              1.8         133
1179  Flight1180  41672  ORD-ATL              9.5         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1178             0.291667               300       55500             1
1179             0.708333               200       33000             2

      Flight Year
1178         2015
1179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1180  Flight1181  41794  ORD-FLL              3.6         170
1181  Flight1182  42201  ORD-CLT              2.4         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1180             0.479167             330.0     54450.0             6
1181             0.708333             137.5     22687.5             7

      Flight Year
1180         2014
1181         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1182  Flight1183  42234  ORD-MIA              0.7         191
1183  Flight1184  41815  ORD-LAX              4.8         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1182                0.750               330       54450             8
1183                0.625               385       63525             6

      Flight Year
1182         2015
1183         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1184  Flight1185  42226  ORD-EWR              1.3          89
1185  Flight1186  42124  ORD-SEA              2.2          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1184             0.416667             247.5     44797.5             8
1185             0.875000             350.0     64750.0             4

      Flight Year
1184         2015
1185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1186  Flight1187  41770  ORD-DFW              1.3         165
1187  Flight1188  41881  ORD-ATL              8.6          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1186             0.791667               200       33000             5
1187             0.708333               220       40700             8

      Flight Year
1186         2014
1187         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1188  Flight1189  42121  ORD-LAS              0.9         182
1189  Flight1190  42056  ORD-DTW              4.2          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1188             0.729167               275       45375             4
1189             0.708333               115       18975             2

      Flight Year
1188         2015
1189         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1190  Flight1191  41958  ORD-SFO              1.7          22
1191  Flight1192  42015  ORD-DFW              1.2          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1190             0.708333               375       69375            11
1191             0.333333               200       36200             1

      Flight Year
1190         2014
1191         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1192  Flight1193  41767  ORD-CLT              1.6          20
1193  Flight1194  41821  ORD-IAH              3.5          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1192             0.416667               125       23125             5
1193             0.375000               220       36300             7

      Flight Year
1192         2014
1193         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1194  Flight1195  42108  ORD-DFW              0.6         155
1195  Flight1196  41725  ORD-BOS              1.3         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1194             0.291667               200       33000             4
1195             0.395833               300       55500             3

      Flight Year
1194         2015
1195         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1196  Flight1197  42291  ORD-ATL              8.9         134
1197  Flight1198  42008  ORD-SFO              2.8         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1196                 0.75               200       37000            10
1197                 0.75               375       61875             1

      Flight Year
1196         2015
1197         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1198  Flight1199  41998  ORD-DFW              5.9          38
1199  Flight1200  42077  ORD-LAX              4.0         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1198             0.729167               280       46200            12
1199             0.500000               350       57750             3

      Flight Year
1198         2014
1199         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1200  Flight1201  41658  ORD-LAX              3.4          72
1201  Flight1202  41973  ORD-SEA              4.9         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1200             0.791667               350       63350             1
1201             0.333333               525       97125            11

      Flight Year
1200         2014
1201         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1202  Flight1203  42224  ORD-MIA              1.4         140
1203  Flight1204  42037  ORD-JFK              2.4          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1202             0.479167               330       61050             8
1203             0.875000               250       46250             2

      Flight Year
1202         2015
1203         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1204  Flight1205  41948  ORD-LAX              4.9          53
1205  Flight1206  42326  ORD-LAS              2.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1204             0.291667               350       57750            11
1205             0.333333               275       49775            11

      Flight Year
1204         2014
1205         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1206  Flight1207  42163  ORD-ATL                9          42
1207  Flight1208  42262  ORD-LAS                1          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1206               0.8125               220       36300             6
1207               0.8125               275       45375             9

      Flight Year
1206         2015
1207         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1208  Flight1209  42297  ORD-PHX              2.1         171
1209  Flight1210  41667  ORD-PHX              1.7         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1208             0.854167               250       41250            10
1209             0.791667               250       41250             1

      Flight Year
1208         2015
1209         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1210  Flight1211  42213  ORD-DFW              2.0         146
1211  Flight1212  41827  ORD-DEN              2.4         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1210             0.395833               220       40700             7
1211             0.333333               330       54450             7

      Flight Year
1210         2015
1211         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1212  Flight1213  42164  ORD-IAH              1.3         174
1213  Flight1214  41873  ORD-CLT              3.0         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1212             0.791667             220.0     36300.0             6
1213             0.666667             137.5     25437.5             8

      Flight Year
1212         2015
1213         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1214  Flight1215  42300  ORD-LAS              2.4         166
1215  Flight1216  41906  ORD-DTW              1.0          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1214             0.541667               275       45375            10
1215             0.791667               115       21275             9

      Flight Year
1214         2015
1215         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1216  Flight1217  42246  ORD-LAX              4.9          73
1217  Flight1218  42168  ORD-DEN              2.7         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1216             0.291667               385       69685             8
1217             0.791667               330       54450             6

      Flight Year
1216         2015
1217         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1218  Flight1219  41664  ORD-ATL              7.0         123
1219  Flight1220  42018  ORD-SFO              2.1         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1218             0.708333               200       37000             1
1219             0.416667               375       69375             1

      Flight Year
1218         2014
1219         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1220  Flight1221  41854  ORD-LAX              3.7         196
1221  Flight1222  41865  ORD-IAD              2.1           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1220             0.812500               385       63525             8
1221             0.416667               330       61050             8

      Flight Year
1220         2014
1221         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1222  Flight1223  41840  ORD-LAX              4.1         132
1223  Flight1224  41818  ORD-DTW              1.2          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1222             0.791667             385.0     71225.0             7
1223             0.875000             126.5     22896.5             6

      Flight Year
1222         2014
1223         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1224  Flight1225  41996  ORD-LAS              4.0          43
1225  Flight1226  42170  ORD-FLL              1.7         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1224             0.729167               385       63525            12
1225             0.708333               330       61050             6

      Flight Year
1224         2014
1225         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1226  Flight1227  42218  ORD-MSP              3.0          72
1227  Flight1228  41711  ORD-DFW              2.4          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1226             0.854167             126.5     22896.5             8
1227             0.812500             200.0     36200.0             3

      Flight Year
1226         2015
1227         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1228  Flight1229  42312  ORD-SEA              1.7         185
1229  Flight1230  42227  ORD-SEA              3.3          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1228             0.333333               350       57750            11
1229             0.291667               385       69685             8

      Flight Year
1228         2015
1229         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1230  Flight1231  42334  ORD-DFW              6.4         209
1231  Flight1232  42299  ORD-SFO              1.5          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1230               0.8750               300       49500            11
1231               0.3125               375       69375            10

      Flight Year
1230         2015
1231         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1232  Flight1233  42250  ORD-MIA              2.2          47
1233  Flight1234  42004  ORD-ATL              6.3         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1232             0.750000               300       49500             9
1233             0.604167               200       33000            12

      Flight Year
1232         2015
1233         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1234  Flight1235  42360  ORD-SFO              3.6          32
1235  Flight1236  42107  ORD-SFO              1.0         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1234             0.770833               525       97125            12
1235             0.875000               375       61875             4

      Flight Year
1234         2015
1235         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1236  Flight1237  42247  ORD-DEN              1.9          62
1237  Flight1238  42232  ORD-MCO              1.5         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1236             0.791667               330       54450             8
1237             0.854167               275       50875             8

      Flight Year
1236         2015
1237         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1238  Flight1239  42116  ORD-PHX              2.6          76
1239  Flight1240  42212  ORD-JFK              3.2         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1238             0.291667               250       45250             4
1239             0.500000               275       45375             7

      Flight Year
1238         2015
1239         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1240  Flight1241  41646  ORD-ATL              7.9           6
1241  Flight1242  41930  ORD-LAX              4.0         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1240             0.708333               200       37000             1
1241             0.291667               350       64750            10

      Flight Year
1240         2014
1241         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1242  Flight1243  41727  ORD-SEA              1.9         183
1243  Flight1244  42335  ORD-DEN              4.5         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1242             0.812500               350       57750             3
1243             0.291667               450       74250            11

      Flight Year
1242         2014
1243         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1244  Flight1245  42093  ORD-DTW              2.3          25
1245  Flight1246  42330  ORD-JFK              2.1          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1244             0.791667               115       21275             3
1245             0.750000               250       41250            11

      Flight Year
1244         2015
1245         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1246  Flight1247  42237  ORD-PHX              1.8          89
1247  Flight1248  41970  ORD-DTW              4.6         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1246             0.666667             275.0     49775.0             8
1247             0.666667             172.5     28462.5            11

      Flight Year
1246         2015
1247         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1248  Flight1249  41810  ORD-LAX              5.8         191
1249  Flight1250  41734  ORD-DFW              2.0          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1248             0.395833               385       63525             6
1249             0.291667               200       33000             4

      Flight Year
1248         2014
1249         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1250  Flight1251  42144  ORD-SFO              2.6          25
1251  Flight1252  41849  ORD-MSP              1.6         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1250             0.791667             375.0     69375.0             5
1251             0.520833             126.5     23402.5             7

      Flight Year
1250         2015
1251         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1252  Flight1253  42359  ORD-IAH              3.3         178
1253  Flight1254  42178  ORD-SFO              2.4         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1252             0.895833             280.0     46200.0            12
1253             0.708333             412.5     68062.5             6

      Flight Year
1252         2015
1253         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1254  Flight1255  41999  ORD-MCO              3.1           1
1255  Flight1256  42326  ORD-SEA              2.7          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1254             0.750000               350       64750            12
1255             0.729167               350       64750            11

      Flight Year
1254         2014
1255         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1256  Flight1257  42084  ORD-SFO              1.9         182
1257  Flight1258  42045  ORD-ATL              9.3         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1256             0.770833               375       61875             3
1257             0.312500               200       37000             2

      Flight Year
1256         2015
1257         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1258  Flight1259  42016  ORD-SFO              1.6          30
1259  Flight1260  42158  ORD-SFO              1.7          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1258                 0.75             375.0     69375.0             1
1259                 0.50             412.5     76312.5             6

      Flight Year
1258         2015
1259         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1260  Flight1261  41942  ORD-ATL              7.4         195
1261  Flight1262  42023  ORD-DFW              2.4         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1260                 0.50               200       33000            10
1261                 0.75               200       33000             1

      Flight Year
1260         2014
1261         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1262  Flight1263  42188  ORD-MCO              2.5          55
1263  Flight1264  41823  ORD-PHX              2.7         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1262             0.791667               275       45375             7
1263             0.458333               275       45375             7

      Flight Year
1262         2015
1263         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1264  Flight1265  42006  ORD-ATL              7.8          59
1265  Flight1266  42309  ORD-IAH              2.5          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1264             0.708333               200       33000             1
1265             0.395833               200       37000            11

      Flight Year
1264         2015
1265         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1266  Flight1267  41857  ORD-MIA              2.4         168
1267  Flight1268  41971  ORD-JFK              3.8          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1266             0.729167               330       54450             8
1267             0.437500               375       61875            11

      Flight Year
1266         2014
1267         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1268  Flight1269  42254  ORD-LAX              5.1          76
1269  Flight1270  42257  ORD-SEA              3.1         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1268             0.583333               350       63350             9
1269             0.312500               350       64750             9

      Flight Year
1268         2015
1269         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1270  Flight1271  41781  ORD-MIA              3.0         103
1271  Flight1272  41667  ORD-DEN              1.5         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1270             0.875000               300       55500             5
1271             0.791667               300       55500             1

      Flight Year
1270         2014
1271         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1272  Flight1273  42099  ORD-DFW              1.7         102
1273  Flight1274  41863  ORD-LAX              4.8          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1272             0.708333               200       37000             4
1273             0.687500               385       69685             8

      Flight Year
1272         2015
1273         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1274  Flight1275  41677  ORD-MIA              2.3         125
1275  Flight1276  42072  ORD-JFK              1.7         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1274             0.895833               300       55500             2
1275             0.416667               250       46250             3

      Flight Year
1274         2014
1275         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1276  Flight1277  42288  ORD-CLT              2.2          88
1277  Flight1278  41799  ORD-EWR              1.8          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1276             0.666667             125.0     22625.0            10
1277             0.333333             247.5     45787.5             6

      Flight Year
1276         2015
1277         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1278  Flight1279  41908  ORD-LGA              2.5         189
1279  Flight1280  41966  ORD-ATL              9.6         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1278             0.291667               275       45375             9
1279             0.791667               200       37000            11

      Flight Year
1278         2014
1279         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1280  Flight1281  41824  ORD-LGA              1.5          42
1281  Flight1282  42263  ORD-MSP              3.0          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1280             0.708333             302.5     49912.5             7
1281             0.750000             115.0     21275.0             9

      Flight Year
1280         2014
1281         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1282  Flight1283  41760  ORD-SEA              1.8         196
1283  Flight1284  41842  ORD-LAX              5.6         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1282             0.437500               350       57750             5
1283             0.291667               385       71225             7

      Flight Year
1282         2014
1283         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1284  Flight1285  42175  ORD-JFK              1.7         159
1285  Flight1286  42360  ORD-PHL              5.3         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1284             0.291667               275       45375             6
1285             0.791667               385       63525            12

      Flight Year
1284         2015
1285         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1286  Flight1287  42244  ORD-EWR              2.4         138
1287  Flight1288  41916  ORD-DFW              1.7         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1286               0.5000             247.5     45787.5             8
1287               0.3125             200.0     33000.0            10

      Flight Year
1286         2015
1287         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1288  Flight1289  41872  ORD-IAH              3.0          59
1289  Flight1290  41809  ORD-MIA              2.4          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1288             0.333333               220       36300             8
1289             0.583333               330       59730             6

      Flight Year
1288         2014
1289         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1290  Flight1291  42193  ORD-DEN              3.3         180
1291  Flight1292  41925  ORD-SEA              1.7         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1290                0.750               330       54450             7
1291                0.375               350       57750            10

      Flight Year
1290         2015
1291         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1292  Flight1293  42253  ORD-IAH              2.7         138
1293  Flight1294  42350  ORD-IAH              1.5          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1292             0.291667               200       37000             9
1293             0.812500               200       37000            12

      Flight Year
1292         2015
1293         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1294  Flight1295  42146  ORD-ATL             10.1         162
1295  Flight1296  42235  ORD-EWR              2.6          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1294             0.500000             200.0     33000.0             5
1295             0.666667             247.5     44797.5             8

      Flight Year
1294         2015
1295         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1296  Flight1297  42351  ORD-LGA              1.3          18
1297  Flight1298  41689  ORD-LAX              3.8          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1296             0.708333               275       50875            12
1297             0.708333               350       64750             2

      Flight Year
1296         2015
1297         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1298  Flight1299  42203  ORD-SFO              0.6         201
1299  Flight1300  42117  ORD-BWI              2.7         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1298                 0.75             412.5     68062.5             7
1299                 0.75             240.0     44400.0             4

      Flight Year
1298         2015
1299         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1300  Flight1301  41753  ORD-DFW              3.3         195
1301  Flight1302  42341  ORD-BWI              0.8          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1300             0.458333               200       33000             4
1301             0.291667               240       44400            12

      Flight Year
1300         2014
1301         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1302  Flight1303  42241  ORD-ATL              9.4         198
1303  Flight1304  42354  ORD-CLT              1.7          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1302             0.770833               220       36300             8
1303             0.291667               125       23125            12

      Flight Year
1302         2015
1303         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1304  Flight1305  41745  ORD-CLT              2.8          45
1305  Flight1306  42167  ORD-DEN              2.5          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1304             0.458333               125       20625             4
1305             0.708333               330       54450             6

      Flight Year
1304         2014
1305         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1306  Flight1307  42360  ORD-PHX              6.2          54
1307  Flight1308  41824  ORD-SFO              2.0           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1306             0.791667             350.0     57750.0            12
1307             0.895833             412.5     76312.5             7

      Flight Year
1306         2015
1307         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1308  Flight1309  41921  ORD-LAX              3.7          89
1309  Flight1310  41836  ORD-DFW              2.5         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1308             0.333333               350       63350            10
1309             0.354167               220       36300             7

      Flight Year
1308         2014
1309         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1310  Flight1311  42171  ORD-ATL             10.0         125
1311  Flight1312  41675  ORD-JFK              1.9         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1310             0.791667               220       40700             6
1311             0.291667               250       41250             2

      Flight Year
1310         2015
1311         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1312  Flight1313  42020  ORD-BOS              2.7          20
1313  Flight1314  41826  ORD-SFO              2.4         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1312             0.708333             300.0     55500.0             1
1313             0.458333             412.5     68062.5             7

      Flight Year
1312         2015
1313         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1314  Flight1315  41799  ORD-DEN              1.8           8
1315  Flight1316  42070  ORD-LGA              1.2         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1314             0.750000               330       61050             6
1315             0.291667               275       50875             3

      Flight Year
1314         2014
1315         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1316  Flight1317  42330  ORD-LAX              4.8          50
1317  Flight1318  41714  ORD-JFK              3.1           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1316             0.500000               350       57750            11
1317             0.791667               250       46250             3

      Flight Year
1316         2015
1317         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1318  Flight1319  41681  ORD-JFK              2.9          35
1319  Flight1320  42006  ORD-BOS              1.5          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1318             0.833333               250       46250             2
1319             0.291667               300       54300             1

      Flight Year
1318         2014
1319         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1320  Flight1321  42252  ORD-CLT              3.0          41
1321  Flight1322  41793  ORD-JFK              2.3         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1320             0.666667               125       20625             9
1321             0.791667               275       50875             6

      Flight Year
1320         2015
1321         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1322  Flight1323  41970  ORD-LAX               12          98
1323  Flight1324  41769  ORD-ATL                7          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1322             0.770833               525       97125            11
1323             0.291667               200       36200             5

      Flight Year
1322         2014
1323         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1324  Flight1325  41809  ORD-ATL             12.1         180
1325  Flight1326  41947  ORD-DEN              1.2         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1324             0.333333               220       36300             6
1325             0.812500               300       55500            11

      Flight Year
1324         2014
1325         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1326  Flight1327  41866  ORD-CLT              0.9         183
1327  Flight1328  41695  ORD-PHX              1.9           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1326             0.708333             137.5     22687.5             8
1327             0.333333             250.0     46250.0             2

      Flight Year
1326         2014
1327         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1328  Flight1329  42336  ORD-PHL              5.0         171
1329  Flight1330  42169  ORD-LAS              3.1          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1328             0.708333             412.5     68062.5            11
1329             0.625000             302.5     54752.5             6

      Flight Year
1328         2015
1329         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1330  Flight1331  42043  ORD-FLL              1.4         102
1331  Flight1332  42008  ORD-MIA              3.2          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1330             0.708333               300       55500             2
1331             0.791667               300       55500             1

      Flight Year
1330         2015
1331         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1332  Flight1333  42292  ORD-DTW              0.8         169
1333  Flight1334  41933  ORD-JFK              1.6          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1332             0.291667               115       18975            10
1333             0.791667               250       41250            10

      Flight Year
1332         2015
1333         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1334  Flight1335  42262  ORD-LAS              1.8         164
1335  Flight1336  41964  ORD-LAS              2.1          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1334             0.708333               275       45375             9
1335             0.750000               275       50875            11

      Flight Year
1334         2015
1335         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1336  Flight1337  42281  ORD-SFO              1.5         120
1337  Flight1338  42238  ORD-MIA              2.0          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1336             0.833333               375       69375            10
1337             0.333333               330       54450             8

      Flight Year
1336         2015
1337         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1338  Flight1339  41849  ORD-MIA              1.4          53
1339  Flight1340  42335  ORD-DEN              3.9         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1338             0.708333               330       54450             7
1339             0.333333               450       74250            11

      Flight Year
1338         2014
1339         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1340  Flight1341  42305  ORD-DTW              2.4         141
1341  Flight1342  41716  ORD-MCO              1.7         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1340             0.833333               115       21275            10
1341             0.583333               250       41250             3

      Flight Year
1340         2015
1341         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1342  Flight1343  41838  ORD-SFO                2         205
1343  Flight1344  42159  ORD-BWI                1          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1342             0.791667             412.5     68062.5             7
1343             0.583333             264.0     43560.0             6

      Flight Year
1342         2014
1343         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1344  Flight1345  41910  ORD-IAH              3.5          65
1345  Flight1346  42320  ORD-SFO              2.0          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1344             0.708333               200       36200             9
1345             0.750000               375       69375            11

      Flight Year
1344         2014
1345         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1346  Flight1347  41907  ORD-CLT              1.7           5
1347  Flight1348  42192  ORD-PHX              2.2          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1346             0.604167               125       23125             9
1347             0.812500               275       45375             7

      Flight Year
1346         2014
1347         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1348  Flight1349  41755  ORD-PHL              4.5         109
1349  Flight1350  42200  ORD-LGA              2.5         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1348             0.625000             275.0     50875.0             4
1349             0.583333             302.5     55962.5             7

      Flight Year
1348         2014
1349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1350  Flight1351  42126  ORD-BOS              1.3         136
1351  Flight1352  42261  ORD-MSP              1.7         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1350             0.833333               300       55500             5
1351             0.666667               115       21275             9

      Flight Year
1350         2015
1351         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1352  Flight1353  42335  ORD-LGA              6.7         170
1353  Flight1354  41949  ORD-FLL              2.1          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1352             0.583333             412.5     68062.5            11
1353             0.291667             300.0     55500.0            11

      Flight Year
1352         2015
1353         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1354  Flight1355  41969  ORD-ATL             15.6          59
1355  Flight1356  42158  ORD-ATL             10.1         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1354             0.791667               300       49500            11
1355             0.291667               220       36300             6

      Flight Year
1354         2014
1355         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1356  Flight1357  42103  ORD-EWR              1.4          88
1357  Flight1358  41655  ORD-IAH              0.4          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1356             0.416667               225       40725             4
1357             0.416667               200       37000             1

      Flight Year
1356         2015
1357         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1358  Flight1359  41745  ORD-JFK              2.4         149
1359  Flight1360  42017  ORD-PHL              2.2         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1358             0.333333               250       46250             4
1359             0.333333               275       50875             1

      Flight Year
1358         2014
1359         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1360  Flight1361  41895  ORD-LAX              3.5          84
1361  Flight1362  41671  ORD-DEN              2.4          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1360             0.791667               350       63350             9
1361             0.291667               300       54300             2

      Flight Year
1360         2014
1361         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1362  Flight1363  42176  ORD-LGA              0.4          38
1363  Flight1364  42184  ORD-ATL              9.2          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1362             0.854167             302.5     49912.5             6
1363             0.416667             220.0     39820.0             6

      Flight Year
1362         2015
1363         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1364  Flight1365  42324  ORD-ATL              8.9          25
1365  Flight1366  42139  ORD-LAX              5.2          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1364             0.750000               200       37000            11
1365             0.416667               350       63350             5

      Flight Year
1364         2015
1365         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1366  Flight1367  42027  ORD-IAD              1.9         186
1367  Flight1368  41858  ORD-LAS              1.1         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1366             0.416667             300.0     49500.0             1
1367             0.770833             302.5     55962.5             8

      Flight Year
1366         2015
1367         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1368  Flight1369  41728  ORD-MCO              0.9          93
1369  Flight1370  41685  ORD-IAH              2.2          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1368             0.625000               250       46250             3
1369             0.333333               200       37000             2

      Flight Year
1368         2014
1369         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1370  Flight1371  42363  ORD-MIA              4.7          95
1371  Flight1372  41869  ORD-CLT              0.8          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1370               0.5625             420.0     77700.0            12
1371               0.3750             137.5     24887.5             8

      Flight Year
1370         2015
1371         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1372  Flight1373  41695  ORD-CLT              2.6          17
1373  Flight1374  42045  ORD-ATL              8.2         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1372             0.770833               125       23125             2
1373             0.291667               200       37000             2

      Flight Year
1372         2014
1373         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1374  Flight1375  42157  ORD-EWR              1.0         131
1375  Flight1376  41936  ORD-JFK              1.6          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1374               0.6250             247.5     45787.5             6
1375               0.3125             250.0     41250.0            10

      Flight Year
1374         2015
1375         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1376  Flight1377  42362  ORD-FLL              4.7          35
1377  Flight1378  42223  ORD-MCO              2.3          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1376             0.458333               420       77700            12
1377             0.750000               275       45375             8

      Flight Year
1376         2015
1377         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1378  Flight1379  41858  ORD-MIA                2         147
1379  Flight1380  42001  ORD-LAX                7         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1378             0.812500               330       61050             8
1379             0.354167               490       80850            12

      Flight Year
1378         2014
1379         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1380  Flight1381  41750  ORD-DFW              2.1          95
1381  Flight1382  41847  ORD-MIA              2.7         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1380             0.354167               200       37000             4
1381             0.291667               330       54450             7

      Flight Year
1380         2014
1381         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1382  Flight1383  42338  ORD-PHL              2.1          62
1383  Flight1384  41956  ORD-PHX              2.1          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1382             0.541667               275       45375            11
1383             0.583333               250       46250            11

      Flight Year
1382         2015
1383         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1384  Flight1385  42355  ORD-LGA              1.9         210
1385  Flight1386  41892  ORD-JFK              1.6          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1384             0.812500               275       45375            12
1385             0.291667               250       41250             9

      Flight Year
1384         2015
1385         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1386  Flight1387  42301  ORD-CLT              1.4          58
1387  Flight1388  42222  ORD-SFO              2.6         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1386             0.479167             125.0     20625.0            10
1387             0.750000             412.5     68062.5             8

      Flight Year
1386         2015
1387         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1388  Flight1389  41664  ORD-MSP              2.5          37
1389  Flight1390  42050  ORD-PHX              1.7         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1388             0.812500               115       18975             1
1389             0.854167               250       41250             2

      Flight Year
1388         2014
1389         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1390  Flight1391  42128  ORD-DEN                2          47
1391  Flight1392  41978  ORD-DEN                3         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1390             0.729167               300       49500             5
1391             0.708333               300       49500            12

      Flight Year
1390         2015
1391         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1392  Flight1393  42146  ORD-LAS              2.4         190
1393  Flight1394  41818  ORD-MSP              1.7          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1392             0.333333             275.0     45375.0             5
1393             0.541667             126.5     22896.5             6

      Flight Year
1392         2015
1393         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1394  Flight1395  42255  ORD-LGA              3.0         168
1395  Flight1396  41735  ORD-MIA              2.1         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1394             0.312500               275       45375             9
1395             0.708333               300       55500             4

      Flight Year
1394         2015
1395         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1396  Flight1397  41887  ORD-ATL              9.4          81
1397  Flight1398  41652  ORD-DEN              1.6         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1396             0.729167               200       36200             9
1397             0.541667               300       49500             1

      Flight Year
1396         2014
1397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1398  Flight1399  41773  ORD-DFW              1.8         162
1399  Flight1400  42249  ORD-LGA              3.1         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1398             0.312500               200       33000             5
1399             0.708333               275       50875             9

      Flight Year
1398         2014
1399         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1400  Flight1401  41820  ORD-FLL              2.9          83
1401  Flight1402  41649  ORD-PHL              3.0         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1400             0.791667               330       59730             6
1401             0.750000               275       50875             1

      Flight Year
1400         2014
1401         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1402  Flight1403  41656  ORD-CLT              1.0         200
1403  Flight1404  41865  ORD-LAS              1.8         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1402             0.750000             125.0     20625.0             1
1403             0.395833             302.5     55962.5             8

      Flight Year
1402         2014
1403         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1404  Flight1405  41767  ORD-DTW              1.7         115
1405  Flight1406  41648  ORD-PHL              1.4         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1404             0.541667               115       21275             5
1405             0.333333               275       50875             1

      Flight Year
1404         2014
1405         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1406  Flight1407  41747  ORD-LAS              2.4         122
1407  Flight1408  42078  ORD-LAS              2.7         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1406             0.333333               275       50875             4
1407             0.729167               275       45375             3

      Flight Year
1406         2014
1407         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1408  Flight1409  42021  ORD-JFK              2.1          89
1409  Flight1410  41728  ORD-CLT              3.2          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1408             0.791667               250       45250             1
1409             0.750000               125       22625             3

      Flight Year
1408         2015
1409         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1410  Flight1411  41887  ORD-DFW              2.6          79
1411  Flight1412  42207  ORD-SFO              2.2         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1410             0.729167             200.0     36200.0             9
1411             0.833333             412.5     68062.5             7

      Flight Year
1410         2014
1411         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1412  Flight1413  42000  ORD-CLT              3.0          22
1413  Flight1414  42354  ORD-IAD              2.5          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1412             0.750000               175       32375            12
1413             0.583333               300       55500            12

      Flight Year
1412         2014
1413         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1414  Flight1415  41834  ORD-SEA              2.8          40
1415  Flight1416  42197  ORD-IAH              0.4          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1414             0.708333               385       63525             7
1415             0.416667               220       36300             7

      Flight Year
1414         2014
1415         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1416  Flight1417  41765  ORD-MCO              2.2          67
1417  Flight1418  42179  ORD-MIA              2.8         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1416             0.708333               250       45250             5
1417             0.395833               330       54450             6

      Flight Year
1416         2014
1417         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1418  Flight1419  41731  ORD-PHL              2.7         118
1419  Flight1420  41969  ORD-JFK              5.0          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1418             0.833333               275       50875             4
1419             0.333333               375       69375            11

      Flight Year
1418         2014
1419         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1420  Flight1421  41964  ORD-MSP              2.5          42
1421  Flight1422  42171  ORD-BOS              2.2         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1420             0.854167               115       18975            11
1421             0.583333               330       61050             6

      Flight Year
1420         2014
1421         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1422  Flight1423  42362  ORD-PHX              3.7         195
1423  Flight1424  41711  ORD-BOS              2.0         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1422             0.812500               350       57750            12
1423             0.458333               300       49500             3

      Flight Year
1422         2015
1423         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1424  Flight1425  42241  ORD-LAX              4.3         108
1425  Flight1426  42232  ORD-SEA              3.2         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1424             0.354167               385       71225             8
1425             0.812500               385       63525             8

      Flight Year
1424         2015
1425         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1426  Flight1427  42224  ORD-MCO              2.3          23
1427  Flight1428  41867  ORD-MSP              1.9          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1426             0.791667             275.0     50875.0             8
1427             0.291667             126.5     20872.5             8

      Flight Year
1426         2015
1427         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1428  Flight1429  42205  ORD-EWR              2.2          19
1429  Flight1430  41703  ORD-BWI              2.0          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1428             0.750000             247.5     45787.5             7
1429             0.541667             240.0     43440.0             3

      Flight Year
1428         2015
1429         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1430  Flight1431  41749  ORD-PHX              2.6           2
1431  Flight1432  41994  ORD-IAH              2.1         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1430             0.708333               250       46250             4
1431             0.312500               200       37000            12

      Flight Year
1430         2014
1431         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1432  Flight1433  41968  ORD-LAX              8.8         139
1433  Flight1434  41717  ORD-DTW              0.7         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1432             0.833333               525       97125            11
1433             0.645833               115       18975             3

      Flight Year
1432         2014
1433         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1434  Flight1435  41815  ORD-DTW              2.3         204
1435  Flight1436  41893  ORD-SEA              2.4           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1434             0.812500             126.5     20872.5             6
1435             0.833333             350.0     64750.0             9

      Flight Year
1434         2014
1435         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1436  Flight1437  42064  ORD-MCO              1.2          30
1437  Flight1438  41741  ORD-DEN              1.5          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1436             0.291667               250       46250             3
1437             0.750000               300       49500             4

      Flight Year
1436         2015
1437         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1438  Flight1439  42190  ORD-BOS              2.5          72
1439  Flight1440  42169  ORD-LAS              1.8         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1438             0.750000             330.0     59730.0             7
1439             0.708333             302.5     49912.5             6

      Flight Year
1438         2015
1439         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1440  Flight1441  41901  ORD-LAX              4.2         160
1441  Flight1442  42249  ORD-BOS              2.7          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1440               0.5000               350       57750             9
1441               0.8125               300       54300             9

      Flight Year
1440         2014
1441         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1442  Flight1443  41741  ORD-IAH              1.4          23
1443  Flight1444  41785  ORD-DFW              2.3         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1442               0.7500               200       37000             4
1443               0.3125               200       37000             5

      Flight Year
1442         2014
1443         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1444  Flight1445  41873  ORD-DFW              1.9         164
1445  Flight1446  41772  ORD-DEN              1.6         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1444             0.708333               220       36300             8
1445             0.708333               300       55500             5

      Flight Year
1444         2014
1445         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1446  Flight1447  42257  ORD-MIA              2.7         161
1447  Flight1448  41944  ORD-BWI              3.1         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1446             0.708333               300       49500             9
1447             0.895833               240       39600            11

      Flight Year
1446         2015
1447         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1448  Flight1449  42279  ORD-DCA              1.5         128
1449  Flight1450  42126  ORD-DFW              1.7          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1448             0.708333              5000      925000            10
1449             0.583333               200       33000             5

      Flight Year
1448         2015
1449         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1450  Flight1451  42356  ORD-LGA              1.1         177
1451  Flight1452  41669  ORD-DEN              2.3         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1450             0.541667               275       45375            12
1451             0.437500               300       55500             1

      Flight Year
1450         2015
1451         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1452  Flight1453  42168  ORD-CLT              1.2         201
1453  Flight1454  42056  ORD-DEN              2.4          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1452             0.333333             137.5     22687.5             6
1453             0.687500             300.0     54300.0             2

      Flight Year
1452         2015
1453         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1454  Flight1455  42191  ORD-MSP              1.7         162
1455  Flight1456  41720  ORD-DFW              2.4         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1454               0.7500             126.5     20872.5             7
1455               0.8125             200.0     33000.0             3

      Flight Year
1454         2015
1455         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1456  Flight1457  42095  ORD-DEN              3.1          53
1457  Flight1458  42118  ORD-EWR              2.1         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1456             0.291667               300       49500             4
1457             0.291667               225       37125             4

      Flight Year
1456         2015
1457         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1458  Flight1459  42270  ORD-FLL              2.5         140
1459  Flight1460  41904  ORD-BOS              2.9         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1458             0.541667               300       55500             9
1459             0.333333               300       49500             9

      Flight Year
1458         2015
1459         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1460  Flight1461  41828  ORD-MIA              2.2         184
1461  Flight1462  41672  ORD-LAX              4.2         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1460             0.875000               330       54450             7
1461             0.333333               350       57750             2

      Flight Year
1460         2014
1461         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1462  Flight1463  42318  ORD-DTW              2.6          20
1463  Flight1464  41714  ORD-PHX              1.7          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1462             0.416667               115       21275            11
1463             0.750000               250       46250             3

      Flight Year
1462         2015
1463         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1464  Flight1465  42228  ORD-LAS              2.3          19
1465  Flight1466  42049  ORD-MIA              2.2          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1464             0.708333             302.5     55962.5             8
1465             0.291667             300.0     54300.0             2

      Flight Year
1464         2015
1465         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1466  Flight1467  41983  ORD-LAX              5.0          78
1467  Flight1468  41827  ORD-DEN              2.1         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1466             0.708333               350       63350            12
1467             0.354167               330       61050             7

      Flight Year
1466         2014
1467         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1468  Flight1469  42241  ORD-LGA              1.3          66
1469  Flight1470  42064  ORD-LAS              2.8         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1468             0.791667             302.5     54752.5             8
1469             0.416667             275.0     50875.0             3

      Flight Year
1468         2015
1469         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1470  Flight1471  42333  ORD-PHX              5.0         113
1471  Flight1472  42350  ORD-SFO              1.4          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1470             0.312500               375       69375            11
1471             0.854167               375       61875            12

      Flight Year
1470         2015
1471         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1472  Flight1473  41969  ORD-DFW              6.2          89
1473  Flight1474  42029  ORD-DFW              1.8          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1472                0.750               300       54300            11
1473                0.625               200       37000             1

      Flight Year
1472         2014
1473         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1474  Flight1475  42292  ORD-SFO              2.1         116
1475  Flight1476  41677  ORD-FLL              1.9          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1474             0.291667               375       69375            10
1475             0.875000               300       54300             2

      Flight Year
1474         2015
1475         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1476  Flight1477  42257  ORD-DFW              1.8          80
1477  Flight1478  41839  ORD-SFO              1.5         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1476             0.708333             200.0     36200.0             9
1477             0.458333             412.5     68062.5             7

      Flight Year
1476         2015
1477         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1478  Flight1479  42314  ORD-JFK              1.8          14
1479  Flight1480  42358  ORD-EWR              1.6           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1478             0.291667               250       46250            11
1479             0.291667               225       41625            12

      Flight Year
1478         2015
1479         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1480  Flight1481  41788  ORD-JFK              1.6          77
1481  Flight1482  42211  ORD-PHL              2.6          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1480                 0.75             250.0     45250.0             5
1481                 0.75             302.5     49912.5             7

      Flight Year
1480         2014
1481         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1482  Flight1483  41695  ORD-PHL              1.6          55
1483  Flight1484  42065  ORD-CLT             -0.2         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1482             0.333333               275       45375             2
1483             0.312500               125       23125             3

      Flight Year
1482         2014
1483         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1484  Flight1485  41652  ORD-LAX              5.5          50
1485  Flight1486  41674  ORD-SFO              2.2          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1484             0.791667               350       57750             1
1485             0.354167               375       69375             2

      Flight Year
1484         2014
1485         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1486  Flight1487  42152  ORD-PHL              2.2          47
1487  Flight1488  41886  ORD-LAS              1.7         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1486             0.750000               275       45375             5
1487             0.395833               275       45375             9

      Flight Year
1486         2015
1487         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1488  Flight1489  42334  ORD-LGA              4.6          83
1489  Flight1490  42336  ORD-LAX              9.0         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1488             0.312500             412.5     74662.5            11
1489             0.708333             525.0     97125.0            11

      Flight Year
1488         2015
1489         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1490  Flight1491  42177  ORD-DEN                1         169
1491  Flight1492  41978  ORD-MSP                1         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1490             0.583333               330       54450             6
1491             0.687500               115       21275            12

      Flight Year
1490         2015
1491         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1492  Flight1493  41704  ORD-SFO              1.6           8
1493  Flight1494  41642  ORD-CLT              2.7         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1492             0.833333               375       69375             3
1493             0.708333               125       20625             1

      Flight Year
1492         2014
1493         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1494  Flight1495  41945  ORD-IAH              1.3         117
1495  Flight1496  42253  ORD-LAS              2.3          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1494             0.791667               200       37000            11
1495             0.750000               275       50875             9

      Flight Year
1494         2014
1495         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1496  Flight1497  41665  ORD-EWR              1.7          29
1497  Flight1498  42341  ORD-IAD              2.1         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1496             0.812500               225       41625             1
1497             0.458333               300       49500            12

      Flight Year
1496         2014
1497         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1498  Flight1499  41963  ORD-BOS              2.2          66
1499  Flight1500  42187  ORD-SFO              2.2         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1498             0.729167             300.0     54300.0            11
1499             0.291667             412.5     76312.5             7

      Flight Year
1498         2014
1499         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1500  Flight1501  41759  ORD-SFO              2.5         112
1501  Flight1502  42280  ORD-DEN              2.0          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1500             0.333333               375       69375             4
1501             0.395833               300       55500            10

      Flight Year
1500         2014
1501         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1502  Flight1503  41784  ORD-DFW              1.9         188
1503  Flight1504  42118  ORD-ATL              9.9         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1502             0.333333               200       33000             5
1503             0.291667               200       33000             4

      Flight Year
1502         2014
1503         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1504  Flight1505  42237  ORD-LGA              1.5          81
1505  Flight1506  42339  ORD-DTW              2.3          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1504             0.750000             302.5     54752.5             8
1505             0.291667             115.0     21275.0            12

      Flight Year
1504         2015
1505         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1506  Flight1507  42362  ORD-MCO              3.3         120
1507  Flight1508  42088  ORD-BOS              3.0         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1506             0.354167               350       64750            12
1507             0.791667               300       55500             3

      Flight Year
1506         2015
1507         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1508  Flight1509  42083  ORD-MIA              2.1          88
1509  Flight1510  42338  ORD-BOS              1.1          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1508             0.708333               300       54300             3
1509             0.333333               300       55500            11

      Flight Year
1508         2015
1509         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1510  Flight1511  42155  ORD-CLT              1.7          52
1511  Flight1512  41833  ORD-DEN              2.6          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1510             0.812500               125       20625             5
1511             0.291667               330       59730             7

      Flight Year
1510         2015
1511         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1512  Flight1513  41873  ORD-LAX              4.1         156
1513  Flight1514  42241  ORD-LGA              1.4          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1512             0.770833             385.0     63525.0             8
1513             0.708333             302.5     54752.5             8

      Flight Year
1512         2014
1513         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1514  Flight1515  42321  ORD-IAH              1.8         208
1515  Flight1516  41894  ORD-CLT              2.1          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1514             0.333333               200       33000            11
1515             0.333333               125       23125             9

      Flight Year
1514         2015
1515         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1516  Flight1517  41900  ORD-BWI              2.7          54
1517  Flight1518  41976  ORD-BOS              2.3         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1516             0.312500               240       39600             9
1517             0.458333               300       55500            12

      Flight Year
1516         2014
1517         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1518  Flight1519  42162  ORD-PHX              2.8         197
1519  Flight1520  42312  ORD-PHL              2.8         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1518             0.729167               275       45375             6
1519             0.708333               275       50875            11

      Flight Year
1518         2015
1519         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1520  Flight1521  42335  ORD-LAS              5.0         104
1521  Flight1522  41656  ORD-JFK              1.9         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1520             0.729167             412.5     76312.5            11
1521             0.666667             250.0     46250.0             1

      Flight Year
1520         2015
1521         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1522  Flight1523  42361  ORD-EWR              4.0          13
1523  Flight1524  42024  ORD-CLT              1.6          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1522             0.458333               315       58275            12
1523             0.833333               125       23125             1

      Flight Year
1522         2015
1523         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1524  Flight1525  41810  ORD-EWR              1.3         171
1525  Flight1526  41930  ORD-SEA              1.8         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1524             0.833333             247.5     40837.5             6
1525             0.354167             350.0     64750.0            10

      Flight Year
1524         2014
1525         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1526  Flight1527  41996  ORD-MSP              3.7          52
1527  Flight1528  42341  ORD-DFW              3.2         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1526             0.729167               161       26565            12
1527             0.375000               200       37000            12

      Flight Year
1526         2014
1527         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1528  Flight1529  41681  ORD-EWR              2.4          71
1529  Flight1530  42168  ORD-CLT              1.7          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1528                 0.75             225.0     40725.0             2
1529                 0.75             137.5     25437.5             6

      Flight Year
1528         2014
1529         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1530  Flight1531  41763  ORD-IAH              1.2          40
1531  Flight1532  42259  ORD-DFW              3.1         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1530             0.750000               200       33000             5
1531             0.791667               200       37000             9

      Flight Year
1530         2014
1531         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1532  Flight1533  41699  ORD-JFK              1.7         195
1533  Flight1534  41791  ORD-MIA              2.8         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1532             0.708333               250       41250             3
1533             0.708333               330       61050             6

      Flight Year
1532         2014
1533         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1534  Flight1535  42005  ORD-MIA              1.1          48
1535  Flight1536  41985  ORD-MIA              1.6           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1534             0.854167               300       49500             1
1535             0.375000               300       55500            12

      Flight Year
1534         2015
1535         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1536  Flight1537  41640  ORD-ATL              6.0          17
1537  Flight1538  41662  ORD-JFK              1.7          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1536             0.833333               200       37000             1
1537             0.875000               250       46250             1

      Flight Year
1536         2014
1537         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1538  Flight1539  42024  ORD-LAX              2.6         111
1539  Flight1540  41908  ORD-LAX              4.2          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1538             0.791667               350       64750             1
1539             0.791667               350       63350             9

      Flight Year
1538         2015
1539         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1540  Flight1541  42218  ORD-ATL              8.6          44
1541  Flight1542  41871  ORD-DEN              1.5          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1540             0.729167               220       36300             8
1541             0.291667               330       61050             8

      Flight Year
1540         2015
1541         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1542  Flight1543  42180  ORD-ATL              7.8         145
1543  Flight1544  42133  ORD-SFO              2.1           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1542             0.875000               220       40700             6
1543             0.479167               375       69375             5

      Flight Year
1542         2015
1543         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1544  Flight1545  42172  ORD-BOS              1.5           7
1545  Flight1546  41728  ORD-PHX              2.2         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1544             0.395833               330       61050             6
1545             0.875000               250       46250             3

      Flight Year
1544         2015
1545         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1546  Flight1547  41997  ORD-PHX              4.0          76
1547  Flight1548  41641  ORD-LAS              1.7         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1546             0.770833               350       63350            12
1547             0.687500               275       45375             1

      Flight Year
1546         2014
1547         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1548  Flight1549  42288  ORD-DFW              2.7          41
1549  Flight1550  41878  ORD-MSP              1.1          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1548             0.729167             200.0     33000.0            10
1549             0.750000             126.5     23402.5             8

      Flight Year
1548         2015
1549         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1550  Flight1551  42058  ORD-ATL              8.1          73
1551  Flight1552  41952  ORD-DTW              2.3         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1550             0.541667               200       36200             2
1551             0.604167               115       18975            11

      Flight Year
1550         2015
1551         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1552  Flight1553  42288  ORD-DFW              3.1         113
1553  Flight1554  41720  ORD-MIA              2.7          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1552             0.520833               200       37000            10
1553             0.583333               300       49500             3

      Flight Year
1552         2015
1553         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1554  Flight1555  41677  ORD-JFK              2.0          22
1555  Flight1556  41848  ORD-MIA              1.8          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1554                0.625               250       46250             2
1555                0.625               330       54450             7

      Flight Year
1554         2014
1555         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1556  Flight1557  41949  ORD-MIA              0.6         194
1557  Flight1558  42310  ORD-DFW              1.1          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1556             0.750000               300       49500            11
1557             0.895833               200       36200            11

      Flight Year
1556         2014
1557         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1558  Flight1559  41973  ORD-CLT              5.2         168
1559  Flight1560  41919  ORD-FLL              1.9          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1558             0.291667             187.5     30937.5            11
1559             0.479167             300.0     49500.0            10

      Flight Year
1558         2014
1559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1560  Flight1561  42031  ORD-DFW              1.5         202
1561  Flight1562  42111  ORD-IAH              1.2          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1560             0.812500               200       33000             1
1561             0.791667               200       36200             4

      Flight Year
1560         2015
1561         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1562  Flight1563  41843  ORD-LGA              2.9          17
1563  Flight1564  41768  ORD-DEN              2.4          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1562             0.791667             302.5     55962.5             7
1563             0.416667             300.0     49500.0             5

      Flight Year
1562         2014
1563         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1564  Flight1565  41998  ORD-MSP              2.1         204
1565  Flight1566  41851  ORD-MCO              1.7          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1564               0.5000               161       26565            12
1565               0.8125               275       45375             7

      Flight Year
1564         2014
1565         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1566  Flight1567  42363  ORD-JFK              3.1         187
1567  Flight1568  42191  ORD-DFW              2.0         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1566             0.791667               350       57750            12
1567             0.895833               220       36300             7

      Flight Year
1566         2015
1567         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1568  Flight1569  42183  ORD-EWR              2.0          67
1569  Flight1570  42063  ORD-IAD              2.4          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1568             0.750000             247.5     44797.5             6
1569             0.791667             300.0     55500.0             2

      Flight Year
1568         2015
1569         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1570  Flight1571  41765  ORD-SFO              3.0         171
1571  Flight1572  41846  ORD-IAD              2.1         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1570             0.791667               375       61875             5
1571             0.583333               330       54450             7

      Flight Year
1570         2014
1571         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1572  Flight1573  41761  ORD-MCO              2.7         145
1573  Flight1574  41783  ORD-SEA              1.7          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1572             0.791667               250       46250             5
1573             0.333333               350       57750             5

      Flight Year
1572         2014
1573         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1574  Flight1575  41973  ORD-MCO              4.8          43
1575  Flight1576  41737  ORD-DFW              3.4         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1574             0.854167               375       61875            11
1575             0.854167               200       37000             4

      Flight Year
1574         2014
1575         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1576  Flight1577  41879  ORD-LGA              1.4          65
1577  Flight1578  41877  ORD-SFO              1.6          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1576             0.375000             302.5     54752.5             8
1577             0.666667             412.5     76312.5             8

      Flight Year
1576         2014
1577         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1578  Flight1579  42208  ORD-CLT              2.7         147
1579  Flight1580  41918  ORD-DCA              1.8          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1578             0.541667             137.5     25437.5             7
1579             0.708333            5000.0    925000.0            10

      Flight Year
1578         2015
1579         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1580  Flight1581  41811  ORD-DTW              2.3         180
1581  Flight1582  41723  ORD-BWI              1.5          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1580             0.770833             126.5     20872.5             6
1581             0.291667             240.0     44400.0             3

      Flight Year
1580         2014
1581         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1582  Flight1583  42021  ORD-ATL             11.0         123
1583  Flight1584  41779  ORD-MIA              1.9         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1582             0.791667               200       37000             1
1583             0.604167               300       49500             5

      Flight Year
1582         2015
1583         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1584  Flight1585  41997  ORD-ATL             12.9         136
1585  Flight1586  41824  ORD-ATL             11.0         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1584             0.583333               280       51800            12
1585             0.812500               220       36300             7

      Flight Year
1584         2014
1585         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1586  Flight1587  41996  ORD-JFK              5.2          65
1587  Flight1588  42275  ORD-PHL              1.9         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1586             0.770833               350       63350            12
1587             0.333333               275       50875             9

      Flight Year
1586         2014
1587         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1588  Flight1589  42020  ORD-DEN              2.4           9
1589  Flight1590  41670  ORD-DTW              2.2          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1588             0.625000               300       55500             1
1589             0.729167               115       21275             1

      Flight Year
1588         2015
1589         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1590  Flight1591  41860  ORD-SFO              2.1         193
1591  Flight1592  42220  ORD-JFK              1.3         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1590             0.291667             412.5     68062.5             8
1591             0.791667             275.0     45375.0             8

      Flight Year
1590         2014
1591         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1592  Flight1593  42105  ORD-CLT              2.0         118
1593  Flight1594  42107  ORD-SFO              2.3          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1592             0.291667               125       23125             4
1593             0.416667               375       67875             4

      Flight Year
1592         2015
1593         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1594  Flight1595  41787  ORD-LAX              2.5         140
1595  Flight1596  42135  ORD-FLL              2.5         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1594             0.708333               350       64750             5
1595             0.791667               300       55500             5

      Flight Year
1594         2014
1595         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1596  Flight1597  41841  ORD-MCO              2.1         157
1597  Flight1598  41908  ORD-DTW              1.2         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1596             0.354167               275       45375             7
1597             0.541667               115       21275             9

      Flight Year
1596         2014
1597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1598  Flight1599  41873  ORD-SFO              1.8          51
1599  Flight1600  41851  ORD-DEN              1.3         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1598             0.291667             412.5     68062.5             8
1599             0.541667             330.0     54450.0             7

      Flight Year
1598         2014
1599         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1600  Flight1601  41899  ORD-IAH              2.1          35
1601  Flight1602  42286  ORD-DFW              1.8          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1600             0.333333               200       37000             9
1601             0.375000               200       36200            10

      Flight Year
1600         2014
1601         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1602  Flight1603  42251  ORD-SFO              1.7         111
1603  Flight1604  41805  ORD-PHL              0.7          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1602             0.750000             375.0     69375.0             9
1603             0.541667             302.5     55962.5             6

      Flight Year
1602         2015
1603         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1604  Flight1605  41677  ORD-DEN              3.3          65
1605  Flight1606  42086  ORD-SFO              2.2          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1604             0.291667               300       54300             2
1605             0.750000               375       69375             3

      Flight Year
1604         2014
1605         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1606  Flight1607  41735  ORD-LAS              2.4         149
1607  Flight1608  41685  ORD-SFO              2.1          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1606             0.770833               275       50875             4
1607             0.291667               375       61875             2

      Flight Year
1606         2014
1607         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1608  Flight1609  41748  ORD-DFW              2.4          94
1609  Flight1610  41981  ORD-LAS              2.0         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1608             0.333333               200       37000             4
1609             0.729167               275       45375            12

      Flight Year
1608         2014
1609         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1610  Flight1611  41860  ORD-ATL              8.8          54
1611  Flight1612  41748  ORD-BOS              1.5          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1610             0.875000               220       36300             8
1611             0.770833               300       49500             4

      Flight Year
1610         2014
1611         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1612  Flight1613  41676  ORD-DFW              1.3          73
1613  Flight1614  41958  ORD-DEN              3.1           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1612             0.708333               200       36200             2
1613             0.354167               300       55500            11

      Flight Year
1612         2014
1613         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1614  Flight1615  41971  ORD-ATL             17.4         171
1615  Flight1616  41872  ORD-LGA              2.7         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1614             0.291667             300.0     49500.0            11
1615             0.416667             302.5     49912.5             8

      Flight Year
1614         2014
1615         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1616  Flight1617  42060  ORD-MIA              1.7          99
1617  Flight1618  42333  ORD-SFO              6.6          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1616             0.791667             300.0     55500.0             2
1617             0.500000             562.5    104062.5            11

      Flight Year
1616         2015
1617         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1618  Flight1619  41739  ORD-IAH              2.3          46
1619  Flight1620  42245  ORD-DFW              1.9          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1618             0.729167               200       33000             4
1619             0.583333               220       39820             8

      Flight Year
1618         2014
1619         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1620  Flight1621  42073  ORD-DFW              2.7         138
1621  Flight1622  41984  ORD-SFO              3.3         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1620             0.291667               200       37000             3
1621             0.729167               375       61875            12

      Flight Year
1620         2015
1621         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1622  Flight1623  41866  ORD-IAH              1.6          44
1623  Flight1624  42334  ORD-JFK              5.9          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1622               0.7500               220       36300             8
1623               0.5625               375       61875            11

      Flight Year
1622         2014
1623         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1624  Flight1625  41778  ORD-LAX              3.5          21
1625  Flight1626  42163  ORD-DFW              2.6         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1624               0.7500               350       64750             5
1625               0.6875               220       36300             6

      Flight Year
1624         2014
1625         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1626  Flight1627  42036  ORD-ATL              5.5         148
1627  Flight1628  42144  ORD-DEN              3.1          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1626             0.833333               200       37000             2
1627             0.312500               300       54300             5

      Flight Year
1626         2015
1627         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1628  Flight1629  42046  ORD-JFK              1.6          67
1629  Flight1630  41897  ORD-CLT              2.2         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1628             0.333333               250       45250             2
1629             0.312500               125       20625             9

      Flight Year
1628         2015
1629         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1630  Flight1631  42204  ORD-LAX              5.4          82
1631  Flight1632  41944  ORD-SEA              1.3          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1630             0.854167               385       69685             7
1631             0.708333               350       64750            11

      Flight Year
1630         2015
1631         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1632  Flight1633  42093  ORD-SEA              2.6         164
1633  Flight1634  41811  ORD-DEN              3.1          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1632             0.666667               350       57750             3
1633             0.750000               330       54450             6

      Flight Year
1632         2015
1633         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1634  Flight1635  41766  ORD-JFK              2.7         189
1635  Flight1636  41676  ORD-JFK              2.8          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1634             0.750000               250       41250             5
1635             0.291667               250       41250             2

      Flight Year
1634         2014
1635         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1636  Flight1637  41826  ORD-LAS              2.3          16
1637  Flight1638  41935  ORD-MIA              1.4          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1636             0.416667             302.5     55962.5             7
1637             0.354167             300.0     55500.0            10

      Flight Year
1636         2014
1637         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1638  Flight1639  42332  ORD-DEN              6.0         100
1639  Flight1640  42343  ORD-LAX              5.1          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1638             0.291667               450       83250            11
1639             0.625000               350       57750            12

      Flight Year
1638         2015
1639         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1640  Flight1641  42361  ORD-ATL             12.9          64
1641  Flight1642  41952  ORD-PHX              1.8          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1640             0.708333               280       50680            12
1641             0.791667               250       46250            11

      Flight Year
1640         2015
1641         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1642  Flight1643  42098  ORD-FLL              2.7          20
1643  Flight1644  42162  ORD-SEA              2.5         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1642                 0.75               300       55500             4
1643                 0.75               385       71225             6

      Flight Year
1642         2015
1643         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1644  Flight1645  42210  ORD-SFO              2.2         186
1645  Flight1646  42220  ORD-DFW              2.4         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1644             0.729167             412.5     68062.5             7
1645             0.458333             220.0     40700.0             8

      Flight Year
1644         2015
1645         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1646  Flight1647  41801  ORD-LAX              4.9          78
1647  Flight1648  42241  ORD-CLT              1.3         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1646             0.875000             385.0     69685.0             6
1647             0.791667             137.5     22687.5             8

      Flight Year
1646         2014
1647         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1648  Flight1649  42306  ORD-JFK              2.4          19
1649  Flight1650  41747  ORD-LAS              1.1          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1648             0.791667               250       46250            10
1649             0.416667               275       50875             4

      Flight Year
1648         2015
1649         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1650  Flight1651  41803  ORD-MCO              2.1         148
1651  Flight1652  41878  ORD-PHX              1.7         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1650             0.416667               275       50875             6
1651             0.812500               275       50875             8

      Flight Year
1650         2014
1651         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1652  Flight1653  41920  ORD-DEN              2.4          88
1653  Flight1654  42195  ORD-BOS              1.4         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1652             0.375000               300       54300            10
1653             0.541667               330       54450             7

      Flight Year
1652         2014
1653         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1654  Flight1655  41686  ORD-DFW              2.3          41
1655  Flight1656  42324  ORD-MCO              2.1         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1654             0.291667               200       33000             2
1655             0.562500               250       41250            11

      Flight Year
1654         2014
1655         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1656  Flight1657  41907  ORD-DFW              3.4          52
1657  Flight1658  42163  ORD-SFO              2.1         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1656             0.291667             200.0     33000.0             9
1657             0.833333             412.5     68062.5             6

      Flight Year
1656         2014
1657         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1658  Flight1659  42319  ORD-CLT              1.4          83
1659  Flight1660  42233  ORD-DFW              1.3           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1658               0.6875               125       22625            11
1659               0.5625               220       40700             8

      Flight Year
1658         2015
1659         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1660  Flight1661  42111  ORD-DEN              2.9         175
1661  Flight1662  41817  ORD-IAH              2.6         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1660                0.625               300       49500             4
1661                0.750               220       36300             6

      Flight Year
1660         2015
1661         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1662  Flight1663  42181  ORD-SFO              0.9          36
1663  Flight1664  42328  ORD-LGA              3.1          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1662             0.333333             412.5     68062.5             6
1663             0.708333             275.0     45375.0            11

      Flight Year
1662         2015
1663         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1664  Flight1665  41887  ORD-ATL              6.5          97
1665  Flight1666  41965  ORD-MIA              1.1          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1664             0.708333               200       37000             9
1665             0.291667               300       54300            11

      Flight Year
1664         2014
1665         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1666  Flight1667  42222  ORD-SEA              1.2         167
1667  Flight1668  41921  ORD-IAH              2.2          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1666             0.729167               385       63525             8
1667             0.291667               200       37000            10

      Flight Year
1666         2015
1667         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1668  Flight1669  42246  ORD-SFO              0.5          74
1669  Flight1670  41813  ORD-SFO              2.5          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1668             0.708333             412.5     74662.5             8
1669             0.291667             412.5     76312.5             6

      Flight Year
1668         2015
1669         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1670  Flight1671  41867  ORD-SFO              1.8         110
1671  Flight1672  41733  ORD-EWR              2.0          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1670             0.604167             412.5     76312.5             8
1671             0.354167             225.0     40725.0             4

      Flight Year
1670         2014
1671         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1672  Flight1673  41875  ORD-PHX              3.0         193
1673  Flight1674  41777  ORD-DEN              2.5         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1672             0.291667               275       45375             8
1673             0.291667               300       49500             5

      Flight Year
1672         2014
1673         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1674  Flight1675  42134  ORD-IAH              2.7          70
1675  Flight1676  41673  ORD-SEA              2.3         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1674             0.604167               200       36200             5
1675             0.291667               350       57750             2

      Flight Year
1674         2015
1675         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1676  Flight1677  41654  ORD-MIA              2.5         188
1677  Flight1678  42194  ORD-SEA              1.8          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1676                0.625               300       49500             1
1677                0.500               385       63525             7

      Flight Year
1676         2014
1677         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1678  Flight1679  42070  ORD-LAS              2.6          79
1679  Flight1680  41776  ORD-ATL             10.1         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1678             0.770833               275       49775             3
1679             0.812500               200       37000             5

      Flight Year
1678         2015
1679         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1680  Flight1681  41812  ORD-SEA              2.4          96
1681  Flight1682  42065  ORD-CLT              2.2         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1680             0.395833               385       71225             6
1681             0.750000               125       23125             3

      Flight Year
1680         2014
1681         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1682  Flight1683  42273  ORD-IAD              3.4          67
1683  Flight1684  41665  ORD-CLT              3.1          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1682             0.854167               300       54300             9
1683             0.708333               125       23125             1

      Flight Year
1682         2015
1683         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1684  Flight1685  41881  ORD-BOS              1.6          78
1685  Flight1686  42103  ORD-LAX              3.9          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1684             0.458333               330       59730             8
1685             0.833333               350       64750             4

      Flight Year
1684         2014
1685         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1686  Flight1687  41862  ORD-DEN              2.9         116
1687  Flight1688  41912  ORD-MCO              2.0          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1686               0.6875               330       61050             8
1687               0.5000               250       45250             9

      Flight Year
1686         2014
1687         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1688  Flight1689  41831  ORD-CLT              2.8         204
1689  Flight1690  41971  ORD-JFK              6.2         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1688             0.729167             137.5     22687.5             7
1689             0.875000             375.0     61875.0            11

      Flight Year
1688         2014
1689         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1690  Flight1691  41675  ORD-CLT              1.4         163
1691  Flight1692  41976  ORD-BWI              1.5          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1690             0.541667               125       20625             2
1691             0.729167               240       43440            12

      Flight Year
1690         2014
1691         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1692  Flight1693  42130  ORD-LGA              1.9          12
1693  Flight1694  42356  ORD-IAH              2.6         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1692             0.708333               275       50875             5
1693             0.500000               200       37000            12

      Flight Year
1692         2015
1693         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1694  Flight1695  42086  ORD-ATL              9.9          21
1695  Flight1696  42178  ORD-IAH              1.5         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1694             0.708333               200       37000             3
1695             0.291667               220       40700             6

      Flight Year
1694         2015
1695         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1696  Flight1697  41929  ORD-JFK              1.5         183
1697  Flight1698  41948  ORD-ATL              8.2         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1696             0.458333               250       41250            10
1697             0.416667               200       33000            11

      Flight Year
1696         2014
1697         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1698  Flight1699  42055  ORD-JFK              3.5         144
1699  Flight1700  41998  ORD-ATL             14.7         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1698             0.458333               250       46250             2
1699             0.708333               280       46200            12

      Flight Year
1698         2015
1699         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1700  Flight1701  42175  ORD-JFK              2.7          63
1701  Flight1702  42302  ORD-SEA              1.7          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1700             0.666667               275       49775             6
1701             0.312500               350       64750            10

      Flight Year
1700         2015
1701         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1702  Flight1703  42229  ORD-MIA              2.4          57
1703  Flight1704  42309  ORD-MCO              3.3         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1702             0.708333               330       54450             8
1703             0.895833               250       46250            11

      Flight Year
1702         2015
1703         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1704  Flight1705  42349  ORD-LAS              1.6          32
1705  Flight1706  42120  ORD-DFW              2.1         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1704             0.812500               275       50875            12
1705             0.333333               200       37000             4

      Flight Year
1704         2015
1705         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1706  Flight1707  41829  ORD-MIA              1.5          68
1707  Flight1708  41681  ORD-JFK              1.1          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1706             0.729167               330       59730             7
1707             0.312500               250       46250             2

      Flight Year
1706         2014
1707         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1708  Flight1709  42195  ORD-PHL              2.7         209
1709  Flight1710  42332  ORD-SFO              7.0          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1708             0.583333             302.5     49912.5             7
1709             0.354167             562.5    104062.5            11

      Flight Year
1708         2015
1709         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1710  Flight1711  41720  ORD-CLT              1.5         168
1711  Flight1712  42318  ORD-LAS              0.2          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1710             0.541667               125       20625             3
1711             0.791667               275       45375            11

      Flight Year
1710         2014
1711         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1712  Flight1713  41995  ORD-DFW              5.4         157
1713  Flight1714  41900  ORD-DFW              2.0          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1712             0.854167               280       46200            12
1713             0.666667               200       37000             9

      Flight Year
1712         2014
1713         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1714  Flight1715  42055  ORD-SFO              2.7         175
1715  Flight1716  42174  ORD-IAH              2.2          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1714             0.812500               375       61875             2
1715             0.708333               220       36300             6

      Flight Year
1714         2015
1715         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1716  Flight1717  42314  ORD-BOS              2.0         183
1717  Flight1718  41868  ORD-ATL              9.8          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1716             0.750000               300       49500            11
1717             0.708333               220       39820             8

      Flight Year
1716         2015
1717         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1718  Flight1719  41821  ORD-JFK              2.5         194
1719  Flight1720  41971  ORD-CLT              5.3         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1718             0.854167             275.0     45375.0             7
1719             0.291667             187.5     34687.5            11

      Flight Year
1718         2014
1719         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1720  Flight1721  42284  ORD-DEN              1.5         172
1721  Flight1722  42248  ORD-LAX              3.0          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1720             0.583333               300       49500            10
1721             0.583333               350       64750             9

      Flight Year
1720         2015
1721         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1722  Flight1723  41882  ORD-IAH              1.9          91
1723  Flight1724  42360  ORD-SEA              4.4          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1722             0.645833               220       40700             8
1723             0.312500               490       90650            12

      Flight Year
1722         2014
1723         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1724  Flight1725  42208  ORD-JFK              2.2         191
1725  Flight1726  42332  ORD-PHL              6.7          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1724             0.395833             275.0     45375.0             7
1725             0.791667             412.5     68062.5            11

      Flight Year
1724         2015
1725         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1726  Flight1727  41791  ORD-MIA              2.2          52
1727  Flight1728  42232  ORD-LAX              3.3           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1726             0.333333               330       54450             6
1727             0.291667               385       71225             8

      Flight Year
1726         2014
1727         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1728  Flight1729  41969  ORD-CLT              4.5         178
1729  Flight1730  41655  ORD-MCO              2.8         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1728             0.875000             187.5     30937.5            11
1729             0.708333             250.0     41250.0             1

      Flight Year
1728         2014
1729         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1730  Flight1731  42126  ORD-IAH              1.6         145
1731  Flight1732  41647  ORD-LGA              1.9         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1730             0.666667               200       37000             5
1731             0.333333               275       50875             1

      Flight Year
1730         2015
1731         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1732  Flight1733  42367  ORD-DEN              1.9         156
1733  Flight1734  41825  ORD-PHX              1.2          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1732             0.520833               300       49500            12
1733             0.833333               275       50875             7

      Flight Year
1732         2015
1733         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1734  Flight1735  42025  ORD-PHX              1.8          97
1735  Flight1736  42119  ORD-EWR              1.7         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1734             0.604167               250       46250             1
1735             0.687500               225       37125             4

      Flight Year
1734         2015
1735         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1736  Flight1737  41880  ORD-CLT              3.1         146
1737  Flight1738  41804  ORD-ATL              7.5          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1736             0.500000             137.5     25437.5             8
1737             0.708333             220.0     36300.0             6

      Flight Year
1736         2014
1737         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1738  Flight1739  42114  ORD-CLT              1.8         160
1739  Flight1740  42235  ORD-SFO              2.0         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1738             0.333333             125.0     20625.0             4
1739             0.500000             412.5     68062.5             8

      Flight Year
1738         2015
1739         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1740  Flight1741  41831  ORD-LAX              3.9         130
1741  Flight1742  42237  ORD-FLL              1.8         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1740             0.708333               385       71225             7
1741             0.458333               330       61050             8

      Flight Year
1740         2014
1741         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1742  Flight1743  42009  ORD-BOS              1.7         163
1743  Flight1744  42125  ORD-DEN              1.9          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1742             0.895833               300       49500             1
1743             0.291667               300       49500             5

      Flight Year
1742         2015
1743         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1744  Flight1745  41955  ORD-LAX              4.1          33
1745  Flight1746  42347  ORD-LAX              2.2         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1744             0.500000               350       64750            11
1745             0.458333               350       57750            12

      Flight Year
1744         2014
1745         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1746  Flight1747  41798  ORD-IAD              1.2         195
1747  Flight1748  42216  ORD-DFW              2.5         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1746             0.291667               330       54450             6
1747             0.791667               220       40700             7

      Flight Year
1746         2014
1747         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1748  Flight1749  42218  ORD-SEA              3.4         181
1749  Flight1750  42170  ORD-JFK              0.8         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1748             0.500000               385       63525             8
1749             0.416667               275       45375             6

      Flight Year
1748         2015
1749         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1750  Flight1751  41852  ORD-PHX              2.4          72
1751  Flight1752  42204  ORD-JFK              0.4         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1750             0.416667               275       49775             8
1751             0.312500               275       45375             7

      Flight Year
1750         2014
1751         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1752  Flight1753  42361  ORD-SFO              4.0         101
1753  Flight1754  42170  ORD-DEN              2.6         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1752             0.291667               525       97125            12
1753             0.854167               330       61050             6

      Flight Year
1752         2015
1753         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1754  Flight1755  42364  ORD-DEN              3.7          64
1755  Flight1756  41985  ORD-MSP              2.0         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1754             0.708333               420       76020            12
1755             0.333333               115       18975            12

      Flight Year
1754         2015
1755         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1756  Flight1757  42120  ORD-JFK              1.4          61
1757  Flight1758  41688  ORD-ATL              9.7          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1756             0.395833               250       41250             4
1757             0.812500               200       36200             2

      Flight Year
1756         2015
1757         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1758  Flight1759  41963  ORD-MCO              2.7         116
1759  Flight1760  42097  ORD-SEA              1.9          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1758             0.291667               250       46250            11
1759             0.708333               350       57750             4

      Flight Year
1758         2014
1759         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1760  Flight1761  42285  ORD-DEN              1.4         113
1761  Flight1762  42073  ORD-EWR              2.2          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1760               0.3750               300       55500            10
1761               0.8125               225       37125             3

      Flight Year
1760         2015
1761         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1762  Flight1763  41973  ORD-BOS              4.8          33
1763  Flight1764  41852  ORD-MCO              2.5          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1762             0.291667               450       83250            11
1763             0.750000               275       50875             8

      Flight Year
1762         2014
1763         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1764  Flight1765  42365  ORD-LAS              4.8          20
1765  Flight1766  41841  ORD-DFW              3.2         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1764             0.333333               385       71225            12
1765             0.666667               220       36300             7

      Flight Year
1764         2015
1765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1766  Flight1767  41675  ORD-ATL              8.5          64
1767  Flight1768  42180  ORD-DEN              2.8         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1766             0.791667               200       36200             2
1767             0.395833               330       54450             6

      Flight Year
1766         2014
1767         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1768  Flight1769  41867  ORD-IAH              2.1         155
1769  Flight1770  41888  ORD-PHL              2.7           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1768             0.708333               220       36300             8
1769             0.833333               275       50875             9

      Flight Year
1768         2014
1769         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1770  Flight1771  42221  ORD-LAS              2.1          66
1771  Flight1772  42077  ORD-JFK              0.7         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1770             0.812500             302.5     54752.5             8
1771             0.770833             250.0     41250.0             3

      Flight Year
1770         2015
1771         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1772  Flight1773  42107  ORD-SEA              2.4         176
1773  Flight1774  42245  ORD-PHL              2.3         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1772             0.791667             350.0     57750.0             4
1773             0.833333             302.5     55962.5             8

      Flight Year
1772         2015
1773         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1774  Flight1775  42191  ORD-MCO              1.2           1
1775  Flight1776  41787  ORD-CLT              1.9          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1774             0.708333               275       50875             7
1775             0.708333               125       22625             5

      Flight Year
1774         2015
1775         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1776  Flight1777  41810  ORD-SEA              2.1          87
1777  Flight1778  42115  ORD-IAH              2.8         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1776             0.708333               385       69685             6
1777             0.875000               200       37000             4

      Flight Year
1776         2014
1777         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1778  Flight1779  41877  ORD-DTW              2.0         192
1779  Flight1780  42363  ORD-LAX              8.1         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1778             0.541667             126.5     20872.5             8
1779             0.750000             490.0     80850.0            12

      Flight Year
1778         2014
1779         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1780  Flight1781  42316  ORD-LAX              4.4          27
1781  Flight1782  42210  ORD-LGA              2.3          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1780             0.750000             350.0     64750.0            11
1781             0.791667             302.5     55962.5             7

      Flight Year
1780         2015
1781         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1782  Flight1783  42303  ORD-PHL              2.3          37
1783  Flight1784  42337  ORD-IAH              6.0         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1782             0.291667               275       45375            10
1783             0.500000               300       55500            11

      Flight Year
1782         2015
1783         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1784  Flight1785  42351  ORD-ATL              9.0         187
1785  Flight1786  42001  ORD-MSP              3.8         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1784             0.458333               200       33000            12
1785             0.416667               161       26565            12

      Flight Year
1784         2015
1785         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1786  Flight1787  42197  ORD-DEN              3.0         166
1787  Flight1788  42154  ORD-SFO              2.7         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1786             0.333333               330       54450             7
1787             0.437500               375       69375             5

      Flight Year
1786         2015
1787         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1788  Flight1789  41766  ORD-MIA                3          46
1789  Flight1790  42249  ORD-BWI                2          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1788             0.791667               300       49500             5
1789             0.583333               240       44400             9

      Flight Year
1788         2014
1789         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1790  Flight1791  41854  ORD-PHX              2.2          20
1791  Flight1792  42180  ORD-JFK              2.1         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1790             0.583333               275       50875             8
1791             0.770833               275       45375             6

      Flight Year
1790         2014
1791         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1792  Flight1793  41988  ORD-SEA              1.7          96
1793  Flight1794  41715  ORD-SFO              1.1         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1792             0.708333               350       64750            12
1793             0.770833               375       69375             3

      Flight Year
1792         2014
1793         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1794  Flight1795  41759  ORD-CLT              3.1          68
1795  Flight1796  41655  ORD-IAH              1.4         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1794             0.333333               125       22625             4
1795             0.312500               200       33000             1

      Flight Year
1794         2014
1795         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1796  Flight1797  42034  ORD-DFW              1.2         206
1797  Flight1798  42139  ORD-DFW              2.0         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1796             0.500000               200       33000             1
1797             0.583333               200       37000             5

      Flight Year
1796         2015
1797         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1798  Flight1799  42195  ORD-ATL              9.6         179
1799  Flight1800  41735  ORD-SFO              2.8         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1798             0.812500               220       36300             7
1799             0.833333               375       69375             4

      Flight Year
1798         2015
1799         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1800  Flight1801  42175  ORD-LAS              1.3         139
1801  Flight1802  41905  ORD-BOS              0.9          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1800             0.812500             302.5     55962.5             6
1801             0.291667             300.0     49500.0             9

      Flight Year
1800         2015
1801         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1802  Flight1803  41753  ORD-DFW              2.2         193
1803  Flight1804  42339  ORD-JFK              2.0         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1802             0.791667               200       33000             4
1803             0.666667               250       41250            12

      Flight Year
1802         2014
1803         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1804  Flight1805  42259  ORD-FLL              1.3         162
1805  Flight1806  42221  ORD-PHL              2.6         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1804             0.416667             300.0     49500.0             9
1805             0.750000             302.5     55962.5             8

      Flight Year
1804         2015
1805         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1806  Flight1807  42165  ORD-PHX              2.2         106
1807  Flight1808  41864  ORD-JFK              2.0         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1806             0.791667               275       50875             6
1807             0.750000               275       45375             8

      Flight Year
1806         2015
1807         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1808  Flight1809  42104  ORD-BWI              2.2          79
1809  Flight1810  42065  ORD-SEA              2.4          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1808             0.291667               240       43440             4
1809             0.312500               350       64750             3

      Flight Year
1808         2015
1809         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1810  Flight1811  42284  ORD-DFW              1.5          59
1811  Flight1812  42198  ORD-JFK              2.7          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1810             0.333333               200       33000            10
1811             0.291667               275       45375             7

      Flight Year
1810         2015
1811         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1812  Flight1813  41654  ORD-PHX              2.0         104
1813  Flight1814  42308  ORD-JFK              2.1         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1812             0.333333               250       46250             1
1813             0.333333               250       46250            10

      Flight Year
1812         2014
1813         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1814  Flight1815  42000  ORD-EWR              2.7          32
1815  Flight1816  41911  ORD-CLT              2.8          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1814             0.625000               315       58275            12
1815             0.791667               125       20625             9

      Flight Year
1814         2014
1815         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1816  Flight1817  41836  ORD-PHL              2.1          39
1817  Flight1818  42364  ORD-MSP              2.3          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1816             0.625000             302.5     49912.5             7
1817             0.291667             161.0     29141.0            12

      Flight Year
1816         2014
1817         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1818  Flight1819  41820  ORD-DCA              1.9         117
1819  Flight1820  42148  ORD-SFO              2.0          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1818               0.8125              5500     1017500             6
1819               0.4375               375       67875             5

      Flight Year
1818         2014
1819         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1820  Flight1821  42045  ORD-EWR              2.9          17
1821  Flight1822  41867  ORD-LGA              1.7         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1820             0.750000             225.0     41625.0             2
1821             0.708333             302.5     55962.5             8

      Flight Year
1820         2015
1821         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1822  Flight1823  41971  ORD-MCO              5.5          37
1823  Flight1824  41966  ORD-MCO              2.0         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1822             0.750000               375       61875            11
1823             0.833333               250       41250            11

      Flight Year
1822         2014
1823         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1824  Flight1825  41882  ORD-LGA              2.8         125
1825  Flight1826  42359  ORD-BOS              3.8         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1824             0.875000             302.5     55962.5             8
1825             0.541667             420.0     69300.0            12

      Flight Year
1824         2014
1825         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1826  Flight1827  41813  ORD-LAX              6.6         116
1827  Flight1828  41997  ORD-DEN              4.1         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1826             0.416667               385       71225             6
1827             0.291667               420       77700            12

      Flight Year
1826         2014
1827         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1828  Flight1829  42019  ORD-IAH              1.4         143
1829  Flight1830  41793  ORD-LGA              1.5          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1828             0.791667             200.0     37000.0             1
1829             0.333333             302.5     49912.5             6

      Flight Year
1828         2015
1829         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1830  Flight1831  41861  ORD-PHL              1.2         172
1831  Flight1832  42230  ORD-SFO              2.2         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1830             0.708333             302.5     49912.5             8
1831             0.562500             412.5     68062.5             8

      Flight Year
1830         2014
1831         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1832  Flight1833  41920  ORD-JFK              2.4         188
1833  Flight1834  42158  ORD-IAH              2.0          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1832             0.812500               250       41250            10
1833             0.708333               220       40700             6

      Flight Year
1832         2014
1833         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1834  Flight1835  41647  ORD-DEN              2.0         137
1835  Flight1836  41773  ORD-MIA              2.2          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1834             0.729167               300       55500             1
1835             0.750000               300       54300             5

      Flight Year
1834         2014
1835         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1836  Flight1837  42238  ORD-DFW              2.2         138
1837  Flight1838  41817  ORD-DTW              1.3         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1836             0.750000             220.0     40700.0             8
1837             0.666667             126.5     20872.5             6

      Flight Year
1836         2015
1837         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1838  Flight1839  42244  ORD-JFK              0.9         182
1839  Flight1840  41992  ORD-SFO              2.6         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1838             0.791667               275       45375             8
1839             0.791667               375       61875            12

      Flight Year
1838         2015
1839         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1840  Flight1841  42040  ORD-ATL              9.0          94
1841  Flight1842  41972  ORD-PHX              3.7         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1840             0.291667               200       37000             2
1841             0.729167               375       69375            11

      Flight Year
1840         2015
1841         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1842  Flight1843  42169  ORD-PHX              1.7         204
1843  Flight1844  42337  ORD-MCO              5.3          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1842                0.500               275       45375             6
1843                0.625               375       69375            11

      Flight Year
1842         2015
1843         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1844  Flight1845  42017  ORD-JFK              2.2          96
1845  Flight1846  42186  ORD-MIA              1.8         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1844             0.354167               250       46250             1
1845             0.687500               330       61050             7

      Flight Year
1844         2015
1845         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1846  Flight1847  42013  ORD-JFK              2.1          26
1847  Flight1848  42094  ORD-LAS              2.3          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1846             0.791667               250       46250             1
1847             0.895833               275       49775             3

      Flight Year
1846         2015
1847         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1848  Flight1849  41860  ORD-DFW              3.1          33
1849  Flight1850  42017  ORD-LAX              4.3          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1848             0.375000               220       40700             8
1849             0.791667               350       57750             1

      Flight Year
1848         2014
1849         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1850  Flight1851  41669  ORD-DCA              1.4          51
1851  Flight1852  42068  ORD-ATL              7.6         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1850             0.625000              5000      825000             1
1851             0.791667               200       37000             3

      Flight Year
1850         2014
1851         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1852  Flight1853  42360  ORD-LAS              5.7           1
1853  Flight1854  41830  ORD-LAS              1.9          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1852             0.708333             385.0     71225.0            12
1853             0.833333             302.5     49912.5             7

      Flight Year
1852         2015
1853         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1854  Flight1855  42107  ORD-JFK              1.7         191
1855  Flight1856  42165  ORD-IAH              1.3          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1854             0.312500               250       41250             4
1855             0.833333               220       36300             6

      Flight Year
1854         2015
1855         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1856  Flight1857  42001  ORD-DEN              3.9         157
1857  Flight1858  42132  ORD-LAS              2.8          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1856             0.333333               420       69300            12
1857             0.333333               275       50875             5

      Flight Year
1856         2014
1857         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1858  Flight1859  42128  ORD-SFO              2.9          37
1859  Flight1860  42295  ORD-ATL              5.8          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1858             0.562500               375       61875             5
1859             0.395833               200       36200            10

      Flight Year
1858         2015
1859         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1860  Flight1861  42245  ORD-ATL             10.8         117
1861  Flight1862  41834  ORD-DFW              1.3          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1860             0.708333               220       40700             8
1861             0.333333               220       40700             7

      Flight Year
1860         2015
1861         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1862  Flight1863  42057  ORD-CLT              1.3         156
1863  Flight1864  42252  ORD-LAS              2.4          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1862             0.291667               125       20625             2
1863             0.770833               275       45375             9

      Flight Year
1862         2015
1863         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1864  Flight1865  42347  ORD-DEN              1.1         110
1865  Flight1866  41853  ORD-LAS              3.1          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1864             0.833333             300.0     55500.0            12
1865             0.583333             302.5     54752.5             8

      Flight Year
1864         2015
1865         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1866  Flight1867  42061  ORD-MCO              2.5          60
1867  Flight1868  41796  ORD-ATL              8.5          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1866             0.708333               250       41250             2
1867             0.500000               220       40700             6

      Flight Year
1866         2015
1867         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1868  Flight1869  41756  ORD-MSP              1.6          56
1869  Flight1870  41750  ORD-DTW              1.3         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1868             0.770833               115       18975             4
1869             0.750000               115       18975             4

      Flight Year
1868         2014
1869         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1870  Flight1871  41865  ORD-MIA              1.1         128
1871  Flight1872  42260  ORD-BOS              2.1          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1870             0.708333               330       61050             8
1871             0.750000               300       54300             9

      Flight Year
1870         2014
1871         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1872  Flight1873  41833  ORD-PHX              2.8         133
1873  Flight1874  41867  ORD-DFW              1.4         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1872             0.625000               275       50875             7
1873             0.333333               220       36300             8

      Flight Year
1872         2014
1873         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1874  Flight1875  42208  ORD-LAS              1.9          75
1875  Flight1876  42342  ORD-BOS              2.5         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1874             0.750000             302.5     54752.5             7
1875             0.791667             300.0     49500.0            12

      Flight Year
1874         2015
1875         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1876  Flight1877  41889  ORD-IAH              0.6          54
1877  Flight1878  41949  ORD-JFK              2.1          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1876             0.750000               200       33000             9
1877             0.583333               250       46250            11

      Flight Year
1876         2014
1877         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1878  Flight1879  42275  ORD-ATL              9.3           8
1879  Flight1880  42090  ORD-SFO              2.7         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1878             0.750000               200       37000             9
1879             0.791667               375       69375             3

      Flight Year
1878         2015
1879         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1880  Flight1881  42218  ORD-LAX              4.1          25
1881  Flight1882  42275  ORD-LAX              4.6         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1880               0.3125               385       71225             8
1881               0.7500               350       64750             9

      Flight Year
1880         2015
1881         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1882  Flight1883  42082  ORD-IAD              2.4         171
1883  Flight1884  41982  ORD-BOS              1.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1882             0.291667               300       49500             3
1883             0.875000               300       49500            12

      Flight Year
1882         2015
1883         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1884  Flight1885  41897  ORD-EWR              4.4         134
1885  Flight1886  42331  ORD-MIA              3.6          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1884             0.791667               225       41625             9
1885             0.520833               450       74250            11

      Flight Year
1884         2014
1885         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1886  Flight1887  41952  ORD-SLC              1.7          67
1887  Flight1888  42043  ORD-EWR              3.2          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1886             0.812500               290       52490            11
1887             0.666667               225       37125             2

      Flight Year
1886         2014
1887         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1888  Flight1889  41818  ORD-DFW              1.3         125
1889  Flight1890  42119  ORD-MSP              2.3          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1888               0.3750               220       40700             6
1889               0.5625               115       20815             4

      Flight Year
1888         2014
1889         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1890  Flight1891  42223  ORD-EWR              3.0         148
1891  Flight1892  41752  ORD-CLT              1.1         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1890             0.708333             247.5     45787.5             8
1891             0.333333             125.0     23125.0             4

      Flight Year
1890         2015
1891         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1892  Flight1893  41714  ORD-MSP              2.2         150
1893  Flight1894  42023  ORD-ATL             10.7         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1892             0.291667               115       21275             3
1893             0.750000               200       37000             1

      Flight Year
1892         2014
1893         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1894  Flight1895  42194  ORD-BOS              1.9         171
1895  Flight1896  41917  ORD-LGA              3.0         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1894             0.833333               330       54450             7
1895             0.791667               275       45375            10

      Flight Year
1894         2015
1895         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1896  Flight1897  41815  ORD-MCO              1.8          12
1897  Flight1898  41734  ORD-SFO              1.7         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1896             0.354167               275       50875             6
1897             0.791667               375       69375             4

      Flight Year
1896         2014
1897         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1898  Flight1899  41813  ORD-JFK              3.1          27
1899  Flight1900  42092  ORD-DFW              1.4          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1898                0.375               275       50875             6
1899                0.750               200       36200             3

      Flight Year
1898         2014
1899         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1900  Flight1901  42053  ORD-DEN              2.0         144
1901  Flight1902  42337  ORD-LAS              3.3          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1900             0.791667             300.0     55500.0             2
1901             0.375000             412.5     74662.5            11

      Flight Year
1900         2015
1901         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1902  Flight1903  42088  ORD-SEA              1.7          80
1903  Flight1904  41999  ORD-EWR              6.1         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1902             0.375000               350       63350             3
1903             0.729167               315       58275            12

      Flight Year
1902         2015
1903         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1904  Flight1905  42279  ORD-JFK              0.1          31
1905  Flight1906  42103  ORD-LGA              1.3          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1904             0.687500               250       46250            10
1905             0.791667               275       49775             4

      Flight Year
1904         2015
1905         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1906  Flight1907  41793  ORD-MSP              2.6          27
1907  Flight1908  41879  ORD-JFK              2.9          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1906             0.458333             126.5     23402.5             6
1907             0.708333             275.0     45375.0             8

      Flight Year
1906         2014
1907         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1908  Flight1909  41987  ORD-EWR              0.7          37
1909  Flight1910  42243  ORD-SFO              1.6         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1908             0.625000             225.0     37125.0            12
1909             0.833333             412.5     68062.5             8

      Flight Year
1908         2014
1909         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1910  Flight1911  41852  ORD-MSP              2.6         143
1911  Flight1912  41834  ORD-LAS              1.9          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1910             0.416667             126.5     23402.5             8
1911             0.333333             302.5     54752.5             7

      Flight Year
1910         2014
1911         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1912  Flight1913  41791  ORD-PHX              1.6         168
1913  Flight1914  41855  ORD-MSP              3.2          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1912               0.7500             275.0     45375.0             6
1913               0.8125             126.5     22896.5             8

      Flight Year
1912         2014
1913         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1914  Flight1915  42129  ORD-JFK              1.2         128
1915  Flight1916  42276  ORD-DTW              1.9         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1914             0.333333               250       46250             5
1915             0.750000               115       21275             9

      Flight Year
1914         2015
1915         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1916  Flight1917  41703  ORD-IAH              2.3         132
1917  Flight1918  42021  ORD-DFW              2.3         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1916             0.583333               200       37000             3
1917             0.333333               200       37000             1

      Flight Year
1916         2014
1917         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1918  Flight1919  42285  ORD-DEN              1.8          87
1919  Flight1920  41944  ORD-DTW              2.7         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1918             0.812500               300       54300            10
1919             0.541667               115       18975            11

      Flight Year
1918         2015
1919         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1920  Flight1921  42138  ORD-ATL             10.3         197
1921  Flight1922  41876  ORD-PHX              1.9          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1920                0.750               200       33000             5
1921                0.625               275       50875             8

      Flight Year
1920         2015
1921         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1922  Flight1923  41773  ORD-SFO              1.8         129
1923  Flight1924  41751  ORD-DEN              0.7          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1922             0.541667               375       69375             5
1923             0.750000               300       55500             4

      Flight Year
1922         2014
1923         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1924  Flight1925  41666  ORD-IAD              2.5          32
1925  Flight1926  42209  ORD-SFO              0.9          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1924             0.333333             300.0     55500.0             1
1925             0.583333             412.5     76312.5             7

      Flight Year
1924         2014
1925         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1926  Flight1927  42048  ORD-CLT              1.4          62
1927  Flight1928  42363  ORD-SEA              6.0         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1926             0.750000               125       20625             2
1927             0.291667               490       80850            12

      Flight Year
1926         2015
1927         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1928  Flight1929  41969  ORD-IAH              3.6          98
1929  Flight1930  42065  ORD-LAX              3.6          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1928             0.458333               300       55500            11
1929             0.395833               350       63350             3

      Flight Year
1928         2014
1929         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1930  Flight1931  42006  ORD-DFW              3.7         110
1931  Flight1932  41720  ORD-PHL              2.9          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1930               0.4375               200       37000             1
1931               0.6875               275       45375             3

      Flight Year
1930         2015
1931         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1932  Flight1933  42365  ORD-IAH              2.8          12
1933  Flight1934  41818  ORD-CLT              1.6         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1932             0.333333             280.0     51800.0            12
1933             0.583333             137.5     25437.5             6

      Flight Year
1932         2015
1933         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1934  Flight1935  41732  ORD-CLT              2.7         150
1935  Flight1936  41925  ORD-JFK              2.6          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1934             0.625000               125       23125             4
1935             0.354167               250       46250            10

      Flight Year
1934         2014
1935         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1936  Flight1937  42287  ORD-LAX              3.3         139
1937  Flight1938  42100  ORD-LAX              3.9          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1936             0.291667               350       64750            10
1937             0.750000               350       63350             4

      Flight Year
1936         2015
1937         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1938  Flight1939  42252  ORD-LGA              2.9          57
1939  Flight1940  42232  ORD-CLT              2.3         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1938             0.291667             275.0     45375.0             9
1939             0.833333             137.5     25437.5             8

      Flight Year
1938         2015
1939         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1940  Flight1941  42085  ORD-MSP              1.2         196
1941  Flight1942  41754  ORD-MIA              2.7          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1940                0.875               115       18975             3
1941                0.875               300       49500             4

      Flight Year
1940         2015
1941         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1942  Flight1943  42098  ORD-LAS              3.3         202
1943  Flight1944  41795  ORD-BOS              2.2          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1942             0.708333               275       45375             4
1943             0.791667               330       54450             6

      Flight Year
1942         2015
1943         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1944  Flight1945  41841  ORD-LAS              0.8         192
1945  Flight1946  42176  ORD-DFW              2.2         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1944             0.625000             302.5     49912.5             7
1945             0.645833             220.0     36300.0             6

      Flight Year
1944         2014
1945         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1946  Flight1947  41998  ORD-LAS              3.3         159
1947  Flight1948  41956  ORD-MSP              2.3          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1946             0.708333               385       63525            12
1947             0.625000               115       18975            11

      Flight Year
1946         2014
1947         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1948  Flight1949  42004  ORD-EWR              2.1         111
1949  Flight1950  41739  ORD-SFO              3.1          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1948             0.625000               225       41625            12
1949             0.395833               375       67875             4

      Flight Year
1948         2014
1949         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1950  Flight1951  42304  ORD-LAX              4.1          39
1951  Flight1952  42113  ORD-PHX              0.8         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1950             0.875000               350       57750            10
1951             0.583333               250       46250             4

      Flight Year
1950         2015
1951         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1952  Flight1953  42193  ORD-BOS              3.1         208
1953  Flight1954  41743  ORD-LAS              1.7          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1952             0.791667               330       54450             7
1953             0.291667               275       45375             4

      Flight Year
1952         2015
1953         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1954  Flight1955  41749  ORD-LAX              3.2         164
1955  Flight1956  42121  ORD-PHX              1.2          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1954             0.479167               350       57750             4
1955             0.375000               250       46250             4

      Flight Year
1954         2014
1955         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1956  Flight1957  42163  ORD-ATL              9.1          30
1957  Flight1958  41821  ORD-BOS              2.8          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1956             0.833333               220       40700             6
1957             0.291667               330       61050             7

      Flight Year
1956         2015
1957         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1958  Flight1959  41865  ORD-SEA              2.6         137
1959  Flight1960  41785  ORD-PHX              2.3          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1958             0.750000               385       71225             8
1959             0.708333               250       45250             5

      Flight Year
1958         2014
1959         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1960  Flight1961  41948  ORD-MCO              1.5         107
1961  Flight1962  42336  ORD-BOS              4.6         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1960             0.291667               250       46250            11
1961             0.750000               450       83250            11

      Flight Year
1960         2014
1961         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1962  Flight1963  42185  ORD-JFK              2.0         118
1963  Flight1964  41928  ORD-SFO              1.4          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1962             0.416667               275       50875             6
1963             0.708333               375       69375            10

      Flight Year
1962         2015
1963         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1964  Flight1965  41750  ORD-EWR              1.9         101
1965  Flight1966  41795  ORD-PHL              2.0         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1964                0.625             225.0     41625.0             4
1965                0.375             302.5     55962.5             6

      Flight Year
1964         2014
1965         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1966  Flight1967  42192  ORD-MSP              2.8           6
1967  Flight1968  42095  ORD-IAH              1.7         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1966             0.416667             126.5     23402.5             7
1967             0.416667             200.0     33000.0             4

      Flight Year
1966         2015
1967         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1968  Flight1969  41796  ORD-ATL              6.7          21
1969  Flight1970  42333  ORD-ATL             18.7          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1968             0.791667               220       40700             6
1969             0.500000               300       49500            11

      Flight Year
1968         2014
1969         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1970  Flight1971  42220  ORD-FLL              2.6         117
1971  Flight1972  41653  ORD-BOS              0.9         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1970             0.333333               330       61050             8
1971             0.833333               300       49500             1

      Flight Year
1970         2015
1971         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1972  Flight1973  42230  ORD-MSP              2.2         124
1973  Flight1974  42118  ORD-MIA              3.7          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1972               0.3125             126.5     23402.5             8
1973               0.6250             300.0     55500.0             4

      Flight Year
1972         2015
1973         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1974  Flight1975  41891  ORD-DFW              1.1         113
1975  Flight1976  41745  ORD-MCO              2.6          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1974             0.395833               200       37000             9
1975             0.708333               250       41250             4

      Flight Year
1974         2014
1975         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1976  Flight1977  41875  ORD-DFW              1.4           3
1977  Flight1978  42133  ORD-LAS              2.2         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1976             0.395833               220       40700             8
1977             0.729167               275       50875             5

      Flight Year
1976         2014
1977         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1978  Flight1979  41953  ORD-LAX              5.5         150
1979  Flight1980  41966  ORD-JFK              0.1         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1978             0.291667               350       64750            11
1979             0.291667               250       41250            11

      Flight Year
1978         2014
1979         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1980  Flight1981  41793  ORD-PHL              2.6          87
1981  Flight1982  42107  ORD-MIA              4.0         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1980             0.770833             302.5     54752.5             6
1981             0.291667             300.0     49500.0             4

      Flight Year
1980         2014
1981         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1982  Flight1983  42055  ORD-IAD              2.0         183
1983  Flight1984  41890  ORD-MSP              2.2         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1982             0.750000               300       49500             2
1983             0.333333               115       18975             9

      Flight Year
1982         2015
1983         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1984  Flight1985  41797  ORD-DEN              2.1         151
1985  Flight1986  41658  ORD-JFK              2.4         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1984             0.625000               330       61050             6
1985             0.791667               250       41250             1

      Flight Year
1984         2014
1985         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1986  Flight1987  42302  ORD-BOS                2         127
1987  Flight1988  42075  ORD-DEN                2         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1986             0.312500               300       55500            10
1987             0.895833               300       49500             3

      Flight Year
1986         2015
1987         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1988  Flight1989  41700  ORD-MCO              2.4          21
1989  Flight1990  42219  ORD-JFK              1.6          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1988             0.312500               250       46250             3
1989             0.645833               275       50875             8

      Flight Year
1988         2014
1989         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1990  Flight1991  41886  ORD-EWR              2.0         157
1991  Flight1992  41913  ORD-IAD              1.8          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1990             0.375000               225       37125             9
1991             0.541667               300       54300            10

      Flight Year
1990         2014
1991         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1992  Flight1993  42213  ORD-EWR              1.8         208
1993  Flight1994  41905  ORD-LGA              2.8          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1992             0.333333             247.5     40837.5             7
1993             0.291667             275.0     45375.0             9

      Flight Year
1992         2015
1993         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1994  Flight1995  41932  ORD-LGA              0.3         136
1995  Flight1996  42192  ORD-LAX              3.7          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1994             0.291667               275       50875            10
1995             0.291667               385       71225             7

      Flight Year
1994         2014
1995         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1996  Flight1997  42198  ORD-DTW              1.4          14
1997  Flight1998  41948  ORD-ATL             10.3         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1996             0.375000             126.5     23402.5             7
1997             0.854167             200.0     37000.0            11

      Flight Year
1996         2015
1997         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
1998  Flight1999  42048  ORD-SEA              2.3          71
1999  Flight2000  42038  ORD-ATL              9.7         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
1998             0.291667               350       63350             2
1999             0.333333               200       37000             2

      Flight Year
1998         2015
1999         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2000  Flight2001  42003  ORD-DFW              1.8          84
2001  Flight2002  42094  ORD-IAH              1.9         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2000             0.708333               200       36200            12
2001             0.604167               200       37000             3

      Flight Year
2000         2014
2001         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2002  Flight2003  41692  ORD-LAS              1.5         174
2003  Flight2004  42276  ORD-ATL             10.2          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2002             0.708333               275       45375             2
2003             0.812500               200       37000             9

      Flight Year
2002         2014
2003         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2004  Flight2005  41886  ORD-SEA              1.6          35
2005  Flight2006  41975  ORD-DFW              2.9         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2004             0.312500               350       64750             9
2005             0.333333               200       37000            12

      Flight Year
2004         2014
2005         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2006  Flight2007  42246  ORD-PHL              2.3         182
2007  Flight2008  41939  ORD-LAX              2.9         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2006             0.708333             302.5     49912.5             8
2007             0.791667             350.0     57750.0            10

      Flight Year
2006         2015
2007         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2008  Flight2009  42162  ORD-DFW              1.8         135
2009  Flight2010  41744  ORD-EWR              3.7         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2008             0.291667               220       40700             6
2009             0.708333               225       41625             4

      Flight Year
2008         2015
2009         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2010  Flight2011  42093  ORD-PHX              2.1         149
2011  Flight2012  42139  ORD-EWR              1.7         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2010             0.708333               250       46250             3
2011             0.708333               225       41625             5

      Flight Year
2010         2015
2011         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2012  Flight2013  41884  ORD-SEA              3.0         165
2013  Flight2014  42362  ORD-JFK              4.2          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2012               0.5625               350       57750             9
2013               0.6875               350       63350            12

      Flight Year
2012         2014
2013         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2014  Flight2015  42289  ORD-BWI              0.7          13
2015  Flight2016  42332  ORD-DFW              3.2         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2014             0.541667               240       44400            10
2015             0.333333               300       49500            11

      Flight Year
2014         2015
2015         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2016  Flight2017  42296  ORD-DFW              2.3          74
2017  Flight2018  41782  ORD-LGA              2.6         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2016             0.750000               200       36200            10
2017             0.791667               275       45375             5

      Flight Year
2016         2015
2017         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2018  Flight2019  41815  ORD-MIA              1.7          15
2019  Flight2020  42326  ORD-LGA              1.8          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2018             0.833333               330       61050             6
2019             0.791667               275       45375            11

      Flight Year
2018         2014
2019         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2020  Flight2021  41923  ORD-BOS              2.0          70
2021  Flight2022  41736  ORD-LAX              4.1         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2020             0.395833               300       54300            10
2021             0.583333               350       57750             4

      Flight Year
2020         2014
2021         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2022  Flight2023  42019  ORD-PHX              1.1          66
2023  Flight2024  42337  ORD-ATL             16.6         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2022             0.416667               250       45250             1
2023             0.625000               300       49500            11

      Flight Year
2022         2015
2023         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2024  Flight2025  42365  ORD-LAX              8.1         141
2025  Flight2026  41970  ORD-LAX             11.2         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2024             0.708333               490       90650            12
2025             0.666667               525       97125            11

      Flight Year
2024         2015
2025         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2026  Flight2027  42365  ORD-LAX              8.1          17
2027  Flight2028  42195  ORD-DFW              1.0         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2026             0.541667               490       90650            12
2027             0.500000               220       36300             7

      Flight Year
2026         2015
2027         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2028  Flight2029  41668  ORD-EWR              2.6         104
2029  Flight2030  41752  ORD-BOS              3.4          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2028             0.333333               225       41625             1
2029             0.812500               300       49500             4

      Flight Year
2028         2014
2029         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2030  Flight2031  41947  ORD-DEN              2.1         163
2031  Flight2032  41738  ORD-JFK              2.0         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2030             0.791667               300       49500            11
2031             0.333333               250       41250             4

      Flight Year
2030         2014
2031         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2032  Flight2033  42197  ORD-MIA              1.5         196
2033  Flight2034  42367  ORD-LAX              3.8          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2032                0.500               330       54450             7
2033                0.875               350       63350            12

      Flight Year
2032         2015
2033         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2034  Flight2035  42270  ORD-PHL              2.6         108
2035  Flight2036  42164  ORD-CLT              2.1         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2034             0.750000             275.0     50875.0             9
2035             0.708333             137.5     25437.5             6

      Flight Year
2034         2015
2035         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2036  Flight2037  41767  ORD-DTW              2.8          34
2037  Flight2038  42074  ORD-ATL             10.4         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2036             0.333333               115       21275             5
2037             0.729167               200       37000             3

      Flight Year
2036         2014
2037         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2038  Flight2039  42160  ORD-FLL              0.9         129
2039  Flight2040  41780  ORD-EWR              2.8          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2038             0.291667               330       61050             6
2039             0.333333               225       37125             5

      Flight Year
2038         2015
2039         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2040  Flight2041  42346  ORD-LAX              2.9         128
2041  Flight2042  41668  ORD-LAS              2.0         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2040             0.312500               350       64750            12
2041             0.395833               275       45375             1

      Flight Year
2040         2015
2041         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2042  Flight2043  42168  ORD-MIA              2.3          32
2043  Flight2044  42112  ORD-ATL             11.8         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2042             0.666667               330       61050             6
2043             0.895833               200       33000             4

      Flight Year
2042         2015
2043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2044  Flight2045  42158  ORD-LAS              2.6          42
2045  Flight2046  42034  ORD-DEN              1.7          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2044             0.833333             302.5     49912.5             6
2045             0.791667             300.0     54300.0             1

      Flight Year
2044         2015
2045         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2046  Flight2047  42188  ORD-DFW              2.8         122
2047  Flight2048  41833  ORD-BOS              3.2          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2046             0.854167               220       40700             7
2047             0.354167               330       61050             7

      Flight Year
2046         2015
2047         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2048  Flight2049  41780  ORD-CLT              2.1          44
2049  Flight2050  42018  ORD-JFK              2.0          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2048             0.750000               125       20625             5
2049             0.833333               250       45250             1

      Flight Year
2048         2014
2049         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2050  Flight2051  41981  ORD-MCO              1.8          62
2051  Flight2052  42094  ORD-DFW              2.0         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2050             0.333333               250       41250            12
2051             0.750000               200       37000             3

      Flight Year
2050         2014
2051         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2052  Flight2053  41858  ORD-BWI              0.4         132
2053  Flight2054  42250  ORD-LGA              2.1           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2052             0.583333               264       48840             8
2053             0.291667               275       50875             9

      Flight Year
2052         2014
2053         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2054  Flight2055  41829  ORD-IAH              1.2         191
2055  Flight2056  42142  ORD-ATL              9.0          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2054             0.833333               220       36300             7
2055             0.645833               200       33000             5

      Flight Year
2054         2014
2055         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2056  Flight2057  41643  ORD-DTW              1.8          68
2057  Flight2058  42014  ORD-CLT              2.1         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2056             0.500000               115       20815             1
2057             0.895833               125       20625             1

      Flight Year
2056         2014
2057         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2058  Flight2059  41773  ORD-PHL              2.3         144
2059  Flight2060  41800  ORD-CLT              2.5          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2058             0.791667             275.0     50875.0             5
2059             0.687500             137.5     25437.5             6

      Flight Year
2058         2014
2059         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2060  Flight2061  42002  ORD-ATL             12.1          49
2061  Flight2062  42218  ORD-LAX              5.8         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2060             0.791667               200       33000            12
2061             0.729167               385       71225             8

      Flight Year
2060         2014
2061         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2062  Flight2063  41688  ORD-LAS              3.1          65
2063  Flight2064  42247  ORD-IAH              2.2          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2062             0.708333               275       49775             2
2063             0.687500               220       40700             8

      Flight Year
2062         2014
2063         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2064  Flight2065  41856  ORD-FLL              2.4           5
2065  Flight2066  42095  ORD-FLL              2.2          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2064             0.500000               330       61050             8
2065             0.708333               300       54300             4

      Flight Year
2064         2014
2065         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2066  Flight2067  42255  ORD-ATL              9.7         104
2067  Flight2068  42153  ORD-JFK              2.0          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2066                 0.75               200       37000             9
2067                 0.75               250       41250             5

      Flight Year
2066         2015
2067         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2068  Flight2069  41797  ORD-DFW              2.6          50
2069  Flight2070  42198  ORD-LAS              2.9         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2068             0.291667             220.0     36300.0             6
2069             0.791667             302.5     49912.5             7

      Flight Year
2068         2014
2069         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2070  Flight2071  42186  ORD-LAX              5.8          28
2071  Flight2072  41726  ORD-LAX              3.4         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2070             0.791667               385       71225             7
2071             0.750000               350       64750             3

      Flight Year
2070         2015
2071         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2072  Flight2073  41898  ORD-BOS              1.8         110
2073  Flight2074  42354  ORD-IAH              2.0          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2072             0.625000               300       55500             9
2073             0.541667               200       33000            12

      Flight Year
2072         2014
2073         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2074  Flight2075  42264  ORD-MSP              2.5          30
2075  Flight2076  42361  ORD-ATL             13.9         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2074             0.791667               115       21275             9
2075             0.583333               280       51800            12

      Flight Year
2074         2015
2075         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2076  Flight2077  41668  ORD-SEA              1.3          77
2077  Flight2078  41837  ORD-PHL              2.3          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2076             0.291667             350.0     63350.0             1
2077             0.791667             302.5     54752.5             7

      Flight Year
2076         2014
2077         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2078  Flight2079  41795  ORD-IAH              1.5          79
2079  Flight2080  42222  ORD-EWR              2.6         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2078               0.8125             220.0     39820.0             6
2079               0.7500             247.5     40837.5             8

      Flight Year
2078         2014
2079         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2080  Flight2081  42186  ORD-DFW              1.2         139
2081  Flight2082  41946  ORD-PHL              0.9          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2080             0.708333               220       40700             7
2081             0.354167               275       50875            11

      Flight Year
2080         2015
2081         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2082  Flight2083  41843  ORD-CLT              2.0          58
2083  Flight2084  41852  ORD-MSP              1.7         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2082             0.354167             137.5     22687.5             7
2083             0.312500             126.5     20872.5             8

      Flight Year
2082         2014
2083         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2084  Flight2085  42080  ORD-CLT              1.7         150
2085  Flight2086  42306  ORD-DEN              1.5         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2084             0.750000               125       23125             3
2085             0.833333               300       49500            10

      Flight Year
2084         2015
2085         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2086  Flight2087  41651  ORD-JFK              2.8          36
2087  Flight2088  41730  ORD-MIA              1.7         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2086             0.416667               250       41250             1
2087             0.354167               300       55500             4

      Flight Year
2086         2014
2087         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2088  Flight2089  42214  ORD-JFK              2.5         114
2089  Flight2090  41720  ORD-LGA              1.8         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2088             0.375000               275       50875             7
2089             0.708333               275       50875             3

      Flight Year
2088         2015
2089         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2090  Flight2091  41837  ORD-PHX              3.2         152
2091  Flight2092  41729  ORD-DTW              1.0          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2090             0.333333               275       45375             7
2091             0.291667               115       20815             3

      Flight Year
2090         2014
2091         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2092  Flight2093  42021  ORD-SFO              3.8          87
2093  Flight2094  42228  ORD-ATL             10.4          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2092             0.333333               375       67875             1
2093             0.416667               220       36300             8

      Flight Year
2092         2015
2093         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2094  Flight2095  42231  ORD-MSP              2.8         153
2095  Flight2096  42081  ORD-CLT              1.4          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2094                0.750             126.5     20872.5             8
2095                0.625             125.0     23125.0             3

      Flight Year
2094         2015
2095         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2096  Flight2097  42172  ORD-MIA              2.0          43
2097  Flight2098  42201  ORD-SFO              1.1          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2096             0.458333             330.0     54450.0             6
2097             0.750000             412.5     68062.5             7

      Flight Year
2096         2015
2097         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2098  Flight2099  42280  ORD-BOS              1.4         131
2099  Flight2100  41861  ORD-JFK              1.1           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2098             0.708333               300       55500            10
2099             0.312500               275       50875             8

      Flight Year
2098         2015
2099         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2100  Flight2101  42211  ORD-LGA              1.3          85
2101  Flight2102  41998  ORD-ATL             17.2         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2100             0.500000             302.5     54752.5             7
2101             0.291667             280.0     51800.0            12

      Flight Year
2100         2015
2101         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2102  Flight2103  42087  ORD-DEN              2.2          83
2103  Flight2104  41903  ORD-JFK              2.1          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2102             0.750000               300       54300             3
2103             0.291667               250       46250             9

      Flight Year
2102         2015
2103         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2104  Flight2105  42282  ORD-EWR              1.4         141
2105  Flight2106  42083  ORD-IAH              1.6         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2104             0.791667               225       41625            10
2105             0.750000               200       37000             3

      Flight Year
2104         2015
2105         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2106  Flight2107  42329  ORD-PHX              2.6         117
2107  Flight2108  41649  ORD-JFK              3.1          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2106             0.750000               250       46250            11
2107             0.770833               250       46250             1

      Flight Year
2106         2015
2107         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2108  Flight2109  42009  ORD-DFW              2.3         202
2109  Flight2110  42045  ORD-SFO              2.3         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2108             0.791667               200       33000             1
2109             0.708333               375       69375             2

      Flight Year
2108         2015
2109         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2110  Flight2111  42105  ORD-CLT              1.0         141
2111  Flight2112  41692  ORD-DFW              1.5          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2110             0.479167               125       23125             4
2111             0.791667               200       36200             2

      Flight Year
2110         2015
2111         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2112  Flight2113  41664  ORD-SFO              1.8          81
2113  Flight2114  41849  ORD-IAH              0.9         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2112             0.291667               375       67875             1
2113             0.791667               220       36300             7

      Flight Year
2112         2014
2113         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2114  Flight2115  41662  ORD-SFO              1.6         171
2115  Flight2116  42036  ORD-EWR              1.5          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2114             0.458333               375       61875             1
2115             0.333333               225       41625             2

      Flight Year
2114         2014
2115         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2116  Flight2117  41780  ORD-MIA              3.3          31
2117  Flight2118  41657  ORD-DEN              1.1          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2116             0.791667               300       55500             5
2117             0.666667               300       55500             1

      Flight Year
2116         2014
2117         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2118  Flight2119  42198  ORD-LAS              1.4          82
2119  Flight2120  42267  ORD-PHL              2.5          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2118             0.791667             302.5     54752.5             7
2119             0.625000             275.0     45375.0             9

      Flight Year
2118         2015
2119         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2120  Flight2121  42325  ORD-SEA              3.2          64
2121  Flight2122  41936  ORD-IAH              1.4         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2120             0.750000               350       63350            11
2121             0.708333               200       37000            10

      Flight Year
2120         2015
2121         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2122  Flight2123  42340  ORD-CLT              2.9          11
2123  Flight2124  41835  ORD-PHL              2.7         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2122             0.770833             125.0     23125.0            12
2123             0.333333             302.5     49912.5             7

      Flight Year
2122         2015
2123         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2124  Flight2125  42251  ORD-IAH              1.6         200
2125  Flight2126  42037  ORD-IAH              1.8         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2124             0.479167               200       33000             9
2125             0.333333               200       33000             2

      Flight Year
2124         2015
2125         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2126  Flight2127  42062  ORD-CLT              2.1         167
2127  Flight2128  42324  ORD-LAS              1.2           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2126             0.750000               125       20625             2
2127             0.291667               275       50875            11

      Flight Year
2126         2015
2127         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2128  Flight2129  42233  ORD-DEN              2.2          55
2129  Flight2130  41815  ORD-DTW              1.7          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2128             0.708333             330.0     54450.0             8
2129             0.791667             126.5     23402.5             6

      Flight Year
2128         2015
2129         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2130  Flight2131  42345  ORD-PHX              2.3         104
2131  Flight2132  42222  ORD-JFK              0.9          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2130             0.520833               250       46250            12
2131             0.791667               275       49775             8

      Flight Year
2130         2015
2131         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2132  Flight2133  41842  ORD-LAX              7.1         140
2133  Flight2134  42303  ORD-EWR              1.6         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2132             0.354167               385       71225             7
2133             0.833333               225       41625            10

      Flight Year
2132         2014
2133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2134  Flight2135  41993  ORD-DTW              2.6         186
2135  Flight2136  42260  ORD-PHL              3.1          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2134             0.333333               115       18975            12
2135             0.875000               275       45375             9

      Flight Year
2134         2014
2135         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2136  Flight2137  42121  ORD-DFW              1.7         208
2137  Flight2138  42070  ORD-IAH              2.7          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2136             0.875000               200       33000             4
2137             0.833333               200       33000             3

      Flight Year
2136         2015
2137         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2138  Flight2139  41886  ORD-EWR              3.0         142
2139  Flight2140  42162  ORD-FLL              2.5         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2138             0.541667               225       41625             9
2139             0.291667               330       54450             6

      Flight Year
2138         2014
2139         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2140  Flight2141  41945  ORD-DFW              3.4         195
2141  Flight2142  41839  ORD-SEA              1.3          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2140             0.833333               200       33000            11
2141             0.625000               385       71225             7

      Flight Year
2140         2014
2141         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2142  Flight2143  41737  ORD-DEN              1.9         157
2143  Flight2144  41663  ORD-PHL              2.1          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2142             0.333333               300       49500             4
2143             0.750000               275       50875             1

      Flight Year
2142         2014
2143         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2144  Flight2145  41784  ORD-EWR              2.0         164
2145  Flight2146  41744  ORD-LGA              2.2          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2144             0.333333               225       37125             5
2145             0.833333               275       49775             4

      Flight Year
2144         2014
2145         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2146  Flight2147  42236  ORD-MIA              2.5         119
2147  Flight2148  41912  ORD-BOS              2.7         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2146             0.812500               330       61050             8
2147             0.333333               300       55500             9

      Flight Year
2146         2015
2147         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2148  Flight2149  41799  ORD-JFK              2.6          15
2149  Flight2150  41719  ORD-DFW              3.2          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2148                0.625               275       50875             6
2149                0.750               200       33000             3

      Flight Year
2148         2014
2149         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2150  Flight2151  41954  ORD-DEN              1.9          10
2151  Flight2152  42154  ORD-MSP              2.1           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2150             0.333333               300       55500            11
2151             0.791667               115       21275             5

      Flight Year
2150         2014
2151         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2152  Flight2153  42351  ORD-JFK              1.6          16
2153  Flight2154  42172  ORD-PHX              1.7         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2152             0.791667               250       46250            12
2153             0.708333               275       50875             6

      Flight Year
2152         2015
2153         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2154  Flight2155  42263  ORD-SFO              2.6         183
2155  Flight2156  42300  ORD-ATL              9.7         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2154                0.750               375       61875             9
2155                0.625               200       37000            10

      Flight Year
2154         2015
2155         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2156  Flight2157  42122  ORD-MCO              2.2         192
2157  Flight2158  41933  ORD-LAX              2.3          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2156             0.750000               250       41250             4
2157             0.291667               350       63350            10

      Flight Year
2156         2015
2157         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2158  Flight2159  42187  ORD-JFK              2.2          97
2159  Flight2160  41785  ORD-BOS              2.5          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2158             0.770833               275       50875             7
2159             0.708333               300       54300             5

      Flight Year
2158         2015
2159         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2160  Flight2161  42338  ORD-DEN              2.9          38
2161  Flight2162  42133  ORD-IAD              1.7         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2160             0.791667               300       49500            11
2161             0.583333               300       49500             5

      Flight Year
2160         2015
2161         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2162  Flight2163  42102  ORD-PHL              2.2           2
2163  Flight2164  42075  ORD-DFW              2.1          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2162             0.479167               275       50875             4
2163             0.875000               200       36200             3

      Flight Year
2162         2015
2163         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2164  Flight2165  42331  ORD-BOS              4.7          42
2165  Flight2166  42122  ORD-BOS              0.8         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2164             0.708333               450       74250            11
2165             0.791667               300       49500             4

      Flight Year
2164         2015
2165         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2166  Flight2167  41918  ORD-DFW              1.5         204
2167  Flight2168  41652  ORD-LAX              5.5          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2166             0.354167               200       33000            10
2167             0.333333               350       57750             1

      Flight Year
2166         2014
2167         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2168  Flight2169  42092  ORD-PHX              2.1         116
2169  Flight2170  41881  ORD-CLT              1.2         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2168               0.8125             250.0     46250.0             3
2169               0.8750             137.5     22687.5             8

      Flight Year
2168         2015
2169         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2170  Flight2171  41848  ORD-SFO              3.0          21
2171  Flight2172  41887  ORD-DFW              1.8         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2170             0.729167             412.5     76312.5             7
2171             0.833333             200.0     33000.0             9

      Flight Year
2170         2014
2171         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2172  Flight2173  42168  ORD-LAX              3.7         203
2173  Flight2174  42348  ORD-ATL             10.2          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2172                 0.75               385       63525             6
2173                 0.75               200       33000            12

      Flight Year
2172         2015
2173         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2174  Flight2175  42176  ORD-IAH              3.1         132
2175  Flight2176  42023  ORD-MIA              2.4          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2174             0.708333               220       40700             6
2175             0.500000               300       49500             1

      Flight Year
2174         2015
2175         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2176  Flight2177  41854  ORD-PHL              2.3          82
2177  Flight2178  42193  ORD-PHX              3.0         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2176             0.708333             302.5     54752.5             8
2177             0.729167             275.0     50875.0             7

      Flight Year
2176         2014
2177         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2178  Flight2179  42276  ORD-LAX              4.6          55
2179  Flight2180  42129  ORD-LAX              6.2         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2178             0.895833               350       57750             9
2179             0.416667               350       64750             5

      Flight Year
2178         2015
2179         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2180  Flight2181  41772  ORD-DTW              1.3         145
2181  Flight2182  41952  ORD-SEA              1.7         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2180             0.416667               115       21275             5
2181             0.375000               350       64750            11

      Flight Year
2180         2014
2181         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2182  Flight2183  41995  ORD-LGA              5.1          78
2183  Flight2184  41972  ORD-ATL             18.3         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2182             0.729167               385       69685            12
2183             0.291667               300       55500            11

      Flight Year
2182         2014
2183         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2184  Flight2185  42142  ORD-LGA              2.8          92
2185  Flight2186  42304  ORD-DFW              1.0         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2184             0.416667               275       50875             5
2185             0.541667               200       37000            10

      Flight Year
2184         2015
2185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2186  Flight2187  41853  ORD-DFW              2.6          81
2187  Flight2188  42318  ORD-SFO              1.6           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2186             0.812500               220       39820             8
2187             0.666667               375       69375            11

      Flight Year
2186         2014
2187         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2188  Flight2189  41698  ORD-DEN              2.8          50
2189  Flight2190  42076  ORD-CLT              0.4         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2188             0.750000               300       49500             2
2189             0.833333               125       20625             3

      Flight Year
2188         2014
2189         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2190  Flight2191  42079  ORD-DEN              1.5          18
2191  Flight2192  41828  ORD-MSP              1.6         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2190             0.291667             300.0     55500.0             3
2191             0.750000             126.5     20872.5             7

      Flight Year
2190         2015
2191         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2192  Flight2193  42291  ORD-DFW              3.2         183
2193  Flight2194  41726  ORD-MIA              2.0          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2192             0.708333               200       33000            10
2193             0.500000               300       55500             3

      Flight Year
2192         2015
2193         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2194  Flight2195  41813  ORD-EWR              1.3          45
2195  Flight2196  42220  ORD-LAS              2.6         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2194             0.729167             247.5     40837.5             6
2195             0.291667             302.5     55962.5             8

      Flight Year
2194         2014
2195         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2196  Flight2197  41956  ORD-MIA              2.6         206
2197  Flight2198  41898  ORD-DFW              3.5         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2196             0.541667               300       49500            11
2197             0.354167               200       37000             9

      Flight Year
2196         2014
2197         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2198  Flight2199  42018  ORD-ATL              8.7         132
2199  Flight2200  42091  ORD-SFO              1.0          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2198             0.833333               200       37000             1
2199             0.333333               375       69375             3

      Flight Year
2198         2015
2199         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2200  Flight2201  42345  ORD-DEN              2.3          20
2201  Flight2202  41673  ORD-MSP              2.2         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2200             0.416667               300       55500            12
2201             0.791667               115       21275             2

      Flight Year
2200         2015
2201         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2202  Flight2203  42169  ORD-PHX              1.9         146
2203  Flight2204  41788  ORD-BOS              1.8         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2202             0.625000               275       50875             6
2203             0.895833               300       55500             5

      Flight Year
2202         2015
2203         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2204  Flight2205  42231  ORD-SFO              2.8         128
2205  Flight2206  41935  ORD-IAD              2.0         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2204             0.354167             412.5     76312.5             8
2205             0.437500             300.0     49500.0            10

      Flight Year
2204         2015
2205         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2206  Flight2207  42309  ORD-LAS              1.4         123
2207  Flight2208  41707  ORD-SFO              0.9          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2206             0.708333               275       50875            11
2207             0.833333               375       67875             3

      Flight Year
2206         2015
2207         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2208  Flight2209  42328  ORD-LAX              5.6         121
2209  Flight2210  41702  ORD-DFW              3.0         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2208             0.708333               350       64750            11
2209             0.312500               200       37000             3

      Flight Year
2208         2015
2209         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2210  Flight2211  41695  ORD-DFW              1.7          38
2211  Flight2212  42060  ORD-MIA              2.4          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2210             0.333333               200       33000             2
2211             0.375000               300       54300             2

      Flight Year
2210         2014
2211         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2212  Flight2213  42032  ORD-MIA              1.5          94
2213  Flight2214  41849  ORD-BOS              2.1         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2212             0.729167               300       55500             1
2213             0.708333               330       54450             7

      Flight Year
2212         2015
2213         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2214  Flight2215  41833  ORD-ATL              8.7         159
2215  Flight2216  42252  ORD-IAH              3.0         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2214             0.708333               220       36300             7
2215             0.416667               200       37000             9

      Flight Year
2214         2014
2215         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2216  Flight2217  42338  ORD-SFO              2.9         146
2217  Flight2218  41789  ORD-CLT              1.6         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2216             0.583333               375       69375            11
2217             0.291667               125       20625             5

      Flight Year
2216         2015
2217         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2218  Flight2219  42045  ORD-ATL              9.9          30
2219  Flight2220  42072  ORD-PHL              2.4           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2218             0.875000               200       37000             2
2219             0.458333               275       50875             3

      Flight Year
2218         2015
2219         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2220  Flight2221  42318  ORD-MIA              1.3          89
2221  Flight2222  42082  ORD-BOS              1.2         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2220             0.333333               300       54300            11
2221             0.416667               300       55500             3

      Flight Year
2220         2015
2221         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2222  Flight2223  41843  ORD-MSP              2.1          86
2223  Flight2224  42090  ORD-LGA              1.7          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2222             0.708333             126.5     22896.5             7
2223             0.625000             275.0     45375.0             3

      Flight Year
2222         2014
2223         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2224  Flight2225  42229  ORD-SEA              1.8         144
2225  Flight2226  42219  ORD-PHL              4.3         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2224             0.458333             385.0     71225.0             8
2225             0.520833             302.5     55962.5             8

      Flight Year
2224         2015
2225         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2226  Flight2227  41753  ORD-IAH              1.3          33
2227  Flight2228  42028  ORD-ATL              9.4         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2226             0.583333               200       37000             4
2227             0.354167               200       37000             1

      Flight Year
2226         2014
2227         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2228  Flight2229  42069  ORD-SFO              2.4           2
2229  Flight2230  42207  ORD-LAX              5.5          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2228             0.750000               375       69375             3
2229             0.791667               385       71225             7

      Flight Year
2228         2015
2229         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2230  Flight2231  42162  ORD-SFO              3.1         139
2231  Flight2232  41889  ORD-DCA              1.7           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2230             0.312500             412.5     76312.5             6
2231             0.729167            5000.0    925000.0             9

      Flight Year
2230         2015
2231         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2232  Flight2233  41678  ORD-DEN              2.8          76
2233  Flight2234  41989  ORD-BOS              2.1         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2232             0.770833               300       54300             2
2233             0.791667               300       55500            12

      Flight Year
2232         2014
2233         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2234  Flight2235  42289  ORD-MSP              2.8          70
2235  Flight2236  41967  ORD-DTW              6.0           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2234             0.583333             115.0     20815.0            10
2235             0.750000             172.5     31912.5            11

      Flight Year
2234         2015
2235         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2236  Flight2237  42149  ORD-LAX              4.2          96
2237  Flight2238  42019  ORD-SEA              2.3         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2236             0.750000               350       64750             5
2237             0.333333               350       57750             1

      Flight Year
2236         2015
2237         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2238  Flight2239  42049  ORD-PHX              1.6          71
2239  Flight2240  42335  ORD-SEA              5.1          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2238             0.833333               250       45250             2
2239             0.791667               525       97125            11

      Flight Year
2238         2015
2239         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2240  Flight2241  42312  ORD-DTW              1.8         101
2241  Flight2242  41724  ORD-LAX              4.0          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2240             0.333333               115       21275            11
2241             0.562500               350       63350             3

      Flight Year
2240         2015
2241         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2242  Flight2243  42315  ORD-SEA              2.4         190
2243  Flight2244  41672  ORD-CLT              1.3         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2242             0.583333               350       57750            11
2243             0.354167               125       20625             2

      Flight Year
2242         2015
2243         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2244  Flight2245  41688  ORD-DEN              1.4         182
2245  Flight2246  42236  ORD-IAH              1.5         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2244             0.750000               300       49500             2
2245             0.729167               220       36300             8

      Flight Year
2244         2014
2245         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2246  Flight2247  42181  ORD-DEN              2.3          43
2247  Flight2248  42017  ORD-PHX              0.6          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2246             0.541667               330       54450             6
2247             0.291667               250       41250             1

      Flight Year
2246         2015
2247         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2248  Flight2249  42176  ORD-MIA              0.8          52
2249  Flight2250  41849  ORD-IAH              2.4         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2248             0.291667               330       54450             6
2249             0.729167               220       40700             7

      Flight Year
2248         2015
2249         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2250  Flight2251  42272  ORD-PHL              2.4          24
2251  Flight2252  41996  ORD-LAX              6.7         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2250                 0.75               275       50875             9
2251                 0.75               490       90650            12

      Flight Year
2250         2015
2251         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2252  Flight2253  41926  ORD-EWR              3.3         161
2253  Flight2254  42205  ORD-DTW              1.3         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2252             0.729167             225.0     37125.0            10
2253             0.354167             126.5     20872.5             7

      Flight Year
2252         2014
2253         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2254  Flight2255  42224  ORD-LAX              7.3         147
2255  Flight2256  42031  ORD-SLC              1.9          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2254             0.770833               385       71225             8
2255             0.833333               290       47850             1

      Flight Year
2254         2015
2255         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2256  Flight2257  41987  ORD-ATL             10.6          73
2257  Flight2258  41867  ORD-SEA              1.4         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2256             0.604167               200       36200            12
2257             0.541667               385       63525             8

      Flight Year
2256         2014
2257         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2258  Flight2259  41874  ORD-JFK              2.6         163
2259  Flight2260  41847  ORD-ATL              9.0         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2258             0.791667               275       45375             8
2259             0.791667               220       36300             7

      Flight Year
2258         2014
2259         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2260  Flight2261  42330  ORD-MCO              0.9         138
2261  Flight2262  41972  ORD-IAH              5.2          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2260                0.875               250       46250            11
2261                0.750               300       55500            11

      Flight Year
2260         2015
2261         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2262  Flight2263  41670  ORD-MCO              1.3         196
2263  Flight2264  42057  ORD-IAD              0.9         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2262             0.291667               250       41250             1
2263             0.354167               300       55500             2

      Flight Year
2262         2014
2263         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2264  Flight2265  42274  ORD-ATL              9.5          64
2265  Flight2266  42242  ORD-DEN              2.2         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2264             0.583333               200       36200             9
2265             0.312500               330       61050             8

      Flight Year
2264         2015
2265         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2266  Flight2267  42130  ORD-ATL              9.4          63
2267  Flight2268  42194  ORD-ATL             12.7          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2266             0.333333               200       36200             5
2267             0.395833               220       40700             7

      Flight Year
2266         2015
2267         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2268  Flight2269  42260  ORD-BOS              1.7           9
2269  Flight2270  42141  ORD-PHX              2.4         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2268             0.791667               300       55500             9
2269             0.812500               250       41250             5

      Flight Year
2268         2015
2269         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2270  Flight2271  42335  ORD-LAX              9.4         139
2271  Flight2272  41958  ORD-DEN              2.0          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2270             0.875000               525       97125            11
2271             0.708333               300       49500            11

      Flight Year
2270         2015
2271         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2272  Flight2273  42369  ORD-LAX              5.5          13
2273  Flight2274  42228  ORD-ATL              9.9          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2272             0.583333               350       64750            12
2273             0.791667               220       40700             8

      Flight Year
2272         2015
2273         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2274  Flight2275  41860  ORD-PHX              2.2         156
2275  Flight2276  42362  ORD-MIA              4.5         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2274             0.354167               275       45375             8
2275             0.416667               420       69300            12

      Flight Year
2274         2014
2275         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2276  Flight2277  42081  ORD-PHX              1.9          87
2277  Flight2278  41909  ORD-LAX              1.1          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2276             0.729167               250       45250             3
2277             0.833333               350       63350             9

      Flight Year
2276         2015
2277         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2278  Flight2279  41952  ORD-IAD              2.8         119
2279  Flight2280  42034  ORD-SFO              1.8         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2278             0.791667               300       55500            11
2279             0.541667               375       61875             1

      Flight Year
2278         2014
2279         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2280  Flight2281  42318  ORD-SLC              2.9         134
2281  Flight2282  42312  ORD-PHL              1.9          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2280             0.583333               290       53650            11
2281             0.791667               275       45375            11

      Flight Year
2280         2015
2281         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2282  Flight2283  41832  ORD-SFO              1.6         102
2283  Flight2284  42260  ORD-DTW              2.8          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2282                 0.75             412.5     76312.5             7
2283                 0.75             115.0     20815.0             9

      Flight Year
2282         2014
2283         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2284  Flight2285  42157  ORD-PHX              1.4         142
2285  Flight2286  41830  ORD-MSP              2.4          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2284             0.750000             275.0     50875.0             6
2285             0.458333             126.5     22896.5             7

      Flight Year
2284         2015
2285         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2286  Flight2287  41861  ORD-LAX              3.9         193
2287  Flight2288  41988  ORD-DTW              2.0          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2286             0.875000               385       63525             8
2287             0.729167               115       18975            12

      Flight Year
2286         2014
2287         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2288  Flight2289  42256  ORD-ATL             11.6         205
2289  Flight2290  42174  ORD-PHL              1.4          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2288             0.375000             200.0     33000.0             9
2289             0.708333             302.5     49912.5             6

      Flight Year
2288         2015
2289         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2290  Flight2291  41831  ORD-LAX                7         143
2291  Flight2292  41660  ORD-MCO                2         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2290             0.541667               385       71225             7
2291             0.541667               250       41250             1

      Flight Year
2290         2014
2291         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2292  Flight2293  41904  ORD-CLT              3.1         192
2293  Flight2294  42301  ORD-PHL              1.4          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2292             0.500000               125       20625             9
2293             0.333333               275       45375            10

      Flight Year
2292         2014
2293         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2294  Flight2295  41663  ORD-SFO              2.1         177
2295  Flight2296  42129  ORD-CLT              2.2          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2294             0.291667               375       61875             1
2295             0.729167               125       20625             5

      Flight Year
2294         2014
2295         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2296  Flight2297  42061  ORD-PHX              2.7          20
2297  Flight2298  41845  ORD-PHX              3.4         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2296             0.583333               250       46250             2
2297             0.520833               275       50875             7

      Flight Year
2296         2015
2297         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2298  Flight2299  41785  ORD-SEA              2.1         161
2299  Flight2300  42204  ORD-LGA              1.7          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2298               0.3125             350.0     57750.0             5
2299               0.3125             302.5     49912.5             7

      Flight Year
2298         2014
2299         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2300  Flight2301  42222  ORD-LAS              1.3          47
2301  Flight2302  42163  ORD-FLL              2.3          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2300             0.729167             302.5     49912.5             8
2301             0.500000             330.0     54450.0             6

      Flight Year
2300         2015
2301         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2302  Flight2303  42336  ORD-IAH              5.2          75
2303  Flight2304  41840  ORD-DTW              2.0         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2302             0.750000             300.0     54300.0            11
2303             0.895833             126.5     23402.5             7

      Flight Year
2302         2015
2303         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2304  Flight2305  41663  ORD-DEN              2.1         104
2305  Flight2306  42156  ORD-EWR              1.3         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2304             0.791667             300.0     55500.0             1
2305             0.604167             247.5     40837.5             6

      Flight Year
2304         2014
2305         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2306  Flight2307  41739  ORD-DEN             -0.1          25
2307  Flight2308  42185  ORD-SEA              2.8         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2306             0.833333               300       55500             4
2307             0.791667               385       63525             6

      Flight Year
2306         2014
2307         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2308  Flight2309  41671  ORD-DFW              1.8         128
2309  Flight2310  41970  ORD-LAX              9.4          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2308             0.833333               200       37000             2
2309             0.750000               525       97125            11

      Flight Year
2308         2014
2309         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2310  Flight2311  41821  ORD-LAX              6.2          24
2311  Flight2312  41809  ORD-LGA              3.1         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2310               0.8125             385.0     71225.0             7
2311               0.6250             302.5     49912.5             6

      Flight Year
2310         2014
2311         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2312  Flight2313  41946  ORD-ATL             12.0         139
2313  Flight2314  42276  ORD-CLT              1.4         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2312             0.750000               200       37000            11
2313             0.791667               125       20625             9

      Flight Year
2312         2014
2313         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2314  Flight2315  42332  ORD-MCO              5.6          30
2315  Flight2316  41998  ORD-MSP              5.2          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2314             0.750000               375       69375            11
2315             0.791667               161       29141            12

      Flight Year
2314         2015
2315         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2316  Flight2317  42363  ORD-BWI              2.7         188
2317  Flight2318  42239  ORD-MSP              0.6          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2316             0.375000             336.0     55440.0            12
2317             0.708333             126.5     20872.5             8

      Flight Year
2316         2015
2317         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2318  Flight2319  41875  ORD-JFK              1.0          67
2319  Flight2320  42360  ORD-ATL             16.4          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2318             0.583333               275       49775             8
2319             0.791667               280       50680            12

      Flight Year
2318         2014
2319         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2320  Flight2321  42334  ORD-PHL              7.5         158
2321  Flight2322  42036  ORD-LGA              2.0          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2320             0.750000             412.5     68062.5            11
2321             0.791667             275.0     45375.0             2

      Flight Year
2320         2015
2321         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2322  Flight2323  42177  ORD-BOS              2.0          26
2323  Flight2324  42307  ORD-SEA              2.5         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2322             0.291667               330       61050             6
2323             0.333333               350       64750            10

      Flight Year
2322         2015
2323         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2324  Flight2325  42128  ORD-DEN              3.3          40
2325  Flight2326  41967  ORD-DEN              5.9          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2324             0.666667               300       49500             5
2325             0.750000               450       74250            11

      Flight Year
2324         2015
2325         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2326  Flight2327  41928  ORD-PHL              2.1         182
2327  Flight2328  41840  ORD-MSP              1.9          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2326             0.875000             275.0     45375.0            10
2327             0.291667             126.5     20872.5             7

      Flight Year
2326         2014
2327         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2328  Flight2329  41968  ORD-ATL             18.1         179
2329  Flight2330  42332  ORD-BWI              6.6         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2328             0.666667               300       49500            11
2329             0.791667               360       59400            11

      Flight Year
2328         2014
2329         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2330  Flight2331  41673  ORD-SFO              2.1         162
2331  Flight2332  41791  ORD-DEN              3.5         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2330             0.750000               375       61875             2
2331             0.791667               330       54450             6

      Flight Year
2330         2014
2331         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2332  Flight2333  41972  ORD-FLL              6.1         117
2333  Flight2334  42273  ORD-MCO              1.9         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2332               0.7500               450       83250            11
2333               0.3125               250       41250             9

      Flight Year
2332         2014
2333         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2334  Flight2335  41912  ORD-JFK              2.7          64
2335  Flight2336  41953  ORD-DEN              2.9          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2334             0.604167               250       45250             9
2335             0.625000               300       55500            11

      Flight Year
2334         2014
2335         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2336  Flight2337  41949  ORD-LAX              4.0         196
2337  Flight2338  41800  ORD-MIA              1.4         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2336             0.791667               350       57750            11
2337             0.770833               330       54450             6

      Flight Year
2336         2014
2337         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2338  Flight2339  41808  ORD-FLL              1.4          42
2339  Flight2340  41905  ORD-EWR              1.1          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2338             0.750000               330       54450             6
2339             0.791667               225       40725             9

      Flight Year
2338         2014
2339         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2340  Flight2341  42157  ORD-DTW              2.0         125
2341  Flight2342  41863  ORD-ATL              9.1         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2340             0.437500             126.5     23402.5             6
2341             0.833333             220.0     36300.0             8

      Flight Year
2340         2015
2341         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2342  Flight2343  41672  ORD-MSP              1.3         186
2343  Flight2344  41811  ORD-EWR              1.4          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2342             0.875000             115.0     18975.0             2
2343             0.333333             247.5     44797.5             6

      Flight Year
2342         2014
2343         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2344  Flight2345  42170  ORD-SEA              2.0           5
2345  Flight2346  42181  ORD-MSP              2.6          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2344             0.875000             385.0     71225.0             6
2345             0.833333             126.5     23402.5             6

      Flight Year
2344         2015
2345         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2346  Flight2347  41762  ORD-BOS              3.5          45
2347  Flight2348  42064  ORD-ATL             12.5         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2346             0.541667               300       49500             5
2347             0.729167               200       37000             3

      Flight Year
2346         2014
2347         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2348  Flight2349  42163  ORD-EWR              3.0         199
2349  Flight2350  42276  ORD-DEN              2.2         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2348             0.750000             247.5     40837.5             6
2349             0.791667             300.0     55500.0             9

      Flight Year
2348         2015
2349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2350  Flight2351  42000  ORD-DFW              4.9         115
2351  Flight2352  41830  ORD-BOS              2.0          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2350             0.354167               280       51800            12
2351             0.791667               330       61050             7

      Flight Year
2350         2014
2351         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2352  Flight2353  41945  ORD-DFW              1.3          81
2353  Flight2354  42229  ORD-IAH              2.1         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2352             0.583333               200       36200            11
2353             0.750000               220       36300             8

      Flight Year
2352         2014
2353         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2354  Flight2355  42286  ORD-JFK              1.6         112
2355  Flight2356  41938  ORD-DFW              1.2         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2354             0.708333               250       46250            10
2355             0.354167               200       33000            10

      Flight Year
2354         2015
2355         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2356  Flight2357  41967  ORD-BOS              4.6          96
2357  Flight2358  42034  ORD-DEN              1.2          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2356             0.583333               450       83250            11
2357             0.708333               300       55500             1

      Flight Year
2356         2014
2357         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2358  Flight2359  42305  ORD-SEA              2.9         127
2359  Flight2360  41904  ORD-JFK              0.8         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2358             0.666667               350       64750            10
2359             0.875000               250       41250             9

      Flight Year
2358         2015
2359         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2360  Flight2361  41967  ORD-JFK              3.1         143
2361  Flight2362  41829  ORD-JFK              1.8          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2360             0.333333               375       69375            11
2361             0.833333               275       50875             7

      Flight Year
2360         2014
2361         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2362  Flight2363  41718  ORD-JFK              1.6          25
2363  Flight2364  41767  ORD-CLT              1.6          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2362             0.354167               250       46250             3
2363             0.833333               125       22625             5

      Flight Year
2362         2014
2363         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2364  Flight2365  42078  ORD-SFO              2.3          74
2365  Flight2366  41964  ORD-SEA              1.7          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2364             0.812500               375       67875             3
2365             0.791667               350       57750            11

      Flight Year
2364         2015
2365         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2366  Flight2367  42200  ORD-DEN              1.9         172
2367  Flight2368  41806  ORD-MCO              2.5          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2366                 0.50               330       54450             7
2367                 0.75               275       45375             6

      Flight Year
2366         2015
2367         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2368  Flight2369  41894  ORD-LGA              1.0          84
2369  Flight2370  41910  ORD-EWR              2.1          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2368             0.291667               275       49775             9
2369             0.791667               225       41625             9

      Flight Year
2368         2014
2369         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2370  Flight2371  41816  ORD-JFK              2.6          76
2371  Flight2372  41705  ORD-DFW              2.8         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2370               0.8750               275       49775             6
2371               0.5625               200       33000             3

      Flight Year
2370         2014
2371         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2372  Flight2373  41706  ORD-DFW              1.7         101
2373  Flight2374  42361  ORD-MCO              5.2         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2372             0.833333               200       37000             3
2373             0.333333               350       64750            12

      Flight Year
2372         2014
2373         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2374  Flight2375  42159  ORD-ATL              9.0         186
2375  Flight2376  42241  ORD-SFO              2.5         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2374               0.3750             220.0     36300.0             6
2375               0.5625             412.5     68062.5             8

      Flight Year
2374         2015
2375         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2376  Flight2377  41995  ORD-ATL             13.9          93
2377  Flight2378  41908  ORD-DEN              1.8          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2376             0.791667               280       51800            12
2377             0.812500               300       54300             9

      Flight Year
2376         2014
2377         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2378  Flight2379  42071  ORD-IAH              2.0         129
2379  Flight2380  42224  ORD-FLL              1.6          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2378             0.291667               200       37000             3
2379             0.708333               330       61050             8

      Flight Year
2378         2015
2379         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2380  Flight2381  41770  ORD-SFO              2.2         105
2381  Flight2382  42022  ORD-LAS              2.7         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2380             0.708333               375       69375             5
2381             0.833333               275       45375             1

      Flight Year
2380         2014
2381         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2382  Flight2383  42055  ORD-SEA              1.2         199
2383  Flight2384  41663  ORD-EWR              1.8         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2382                0.750               350       57750             2
2383                0.625               225       37125             1

      Flight Year
2382         2015
2383         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2384  Flight2385  41916  ORD-LAS              2.1          11
2385  Flight2386  41755  ORD-MIA              2.0           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2384                0.625               275       50875            10
2385                0.750               300       55500             4

      Flight Year
2384         2014
2385         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2386  Flight2387  41906  ORD-DTW              1.7          57
2387  Flight2388  41852  ORD-ATL             11.3         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2386             0.583333               115       18975             9
2387             0.875000               220       36300             8

      Flight Year
2386         2014
2387         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2388  Flight2389  42199  ORD-MIA              2.8         200
2389  Flight2390  42349  ORD-CLT              1.8         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2388             0.729167               330       54450             7
2389             0.312500               125       20625            12

      Flight Year
2388         2015
2389         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2390  Flight2391  41930  ORD-DTW              2.3          91
2391  Flight2392  41968  ORD-JFK              3.5         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2390             0.479167               115       21275            10
2391             0.750000               375       69375            11

      Flight Year
2390         2014
2391         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2392  Flight2393  41936  ORD-JFK              2.2         186
2393  Flight2394  42090  ORD-LAX              4.4          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2392             0.541667               250       41250            10
2393             0.875000               350       57750             3

      Flight Year
2392         2014
2393         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2394  Flight2395  42369  ORD-MCO              2.8         103
2395  Flight2396  42228  ORD-ATL             10.9          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2394             0.666667               250       46250            12
2395             0.687500               220       39820             8

      Flight Year
2394         2015
2395         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2396  Flight2397  42055  ORD-DFW              2.7          58
2397  Flight2398  41846  ORD-CLT              2.6         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2396             0.854167             200.0     33000.0             2
2397             0.583333             137.5     22687.5             7

      Flight Year
2396         2015
2397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2398  Flight2399  42214  ORD-ATL             10.0          91
2399  Flight2400  42108  ORD-LAX              3.9           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2398             0.333333               220       40700             7
2399             0.333333               350       64750             4

      Flight Year
2398         2015
2399         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2400  Flight2401  41854  ORD-ATL              9.6          73
2401  Flight2402  41959  ORD-JFK              2.6          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2400             0.854167               220       39820             8
2401             0.729167               250       45250            11

      Flight Year
2400         2014
2401         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2402  Flight2403  42230  ORD-SEA              2.8          90
2403  Flight2404  41828  ORD-DTW              1.5          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2402             0.791667             385.0     69685.0             8
2403             0.291667             126.5     20872.5             7

      Flight Year
2402         2015
2403         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2404  Flight2405  41951  ORD-ATL              9.4           7
2405  Flight2406  42247  ORD-IAH              2.0          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2404             0.770833               200       37000            11
2405             0.416667               220       40700             8

      Flight Year
2404         2014
2405         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2406  Flight2407  41948  ORD-JFK              2.6         169
2407  Flight2408  42349  ORD-SFO              3.6         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2406             0.666667               250       41250            11
2407             0.708333               375       61875            12

      Flight Year
2406         2014
2407         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2408  Flight2409  41883  ORD-EWR              2.1         172
2409  Flight2410  41904  ORD-ATL              9.0         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2408             0.833333               225       37125             9
2409             0.333333               200       37000             9

      Flight Year
2408         2014
2409         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2410  Flight2411  41959  ORD-PHL              2.0         133
2411  Flight2412  41802  ORD-LAS              2.1         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2410             0.666667             275.0     50875.0            11
2411             0.770833             302.5     49912.5             6

      Flight Year
2410         2014
2411         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2412  Flight2413  41706  ORD-MSP              2.4         153
2413  Flight2414  41871  ORD-DEN              2.4         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2412               0.7500               115       18975             3
2413               0.3125               330       61050             8

      Flight Year
2412         2014
2413         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2414  Flight2415  42260  ORD-MSP              1.1           5
2415  Flight2416  41951  ORD-PHL              0.9         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2414             0.645833               115       21275             9
2415             0.479167               275       45375            11

      Flight Year
2414         2015
2415         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2416  Flight2417  41937  ORD-CLT              1.9          47
2417  Flight2418  41712  ORD-JFK              2.1         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2416             0.770833               125       20625            10
2417             0.333333               250       41250             3

      Flight Year
2416         2014
2417         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2418  Flight2419  42367  ORD-LAS              2.8         188
2419  Flight2420  41856  ORD-BOS              1.8          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2418             0.625000               275       45375            12
2419             0.833333               330       59730             8

      Flight Year
2418         2015
2419         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2420  Flight2421  41641  ORD-JFK              2.5         195
2421  Flight2422  41815  ORD-MSP              1.4          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2420             0.666667             250.0     41250.0             1
2421             0.604167             126.5     22896.5             6

      Flight Year
2420         2014
2421         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2422  Flight2423  42000  ORD-EWR              4.0          97
2423  Flight2424  42090  ORD-ATL              9.4         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2422                 0.75               315       58275            12
2423                 0.50               200       37000             3

      Flight Year
2422         2014
2423         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2424  Flight2425  42304  ORD-JFK              1.3         159
2425  Flight2426  42230  ORD-ATL             10.0         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2424             0.791667               250       41250            10
2425             0.833333               220       40700             8

      Flight Year
2424         2015
2425         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2426  Flight2427  41912  ORD-JFK              2.8          60
2427  Flight2428  42172  ORD-JFK              2.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2426             0.854167               250       41250             9
2427             0.333333               275       49775             6

      Flight Year
2426         2014
2427         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2428  Flight2429  41877  ORD-LAX              4.8          32
2429  Flight2430  42217  ORD-PHX              1.6          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2428             0.770833               385       71225             8
2429             0.791667               275       50875             8

      Flight Year
2428         2014
2429         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2430  Flight2431  41859  ORD-SFO              1.9          11
2431  Flight2432  42364  ORD-SFO              3.9         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2430             0.854167             412.5     76312.5             8
2431             0.791667             525.0     86625.0            12

      Flight Year
2430         2014
2431         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2432  Flight2433  42058  ORD-MIA              1.8          82
2433  Flight2434  42326  ORD-ATL              9.5         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2432             0.333333               300       54300             2
2433             0.750000               200       33000            11

      Flight Year
2432         2015
2433         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2434  Flight2435  42148  ORD-EWR              3.0         188
2435  Flight2436  42207  ORD-JFK              1.1         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2434             0.666667               225       37125             5
2435             0.750000               275       50875             7

      Flight Year
2434         2015
2435         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2436  Flight2437  42213  ORD-LAX              6.6         111
2437  Flight2438  41874  ORD-DFW              2.2          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2436             0.333333               385       71225             7
2437             0.708333               220       36300             8

      Flight Year
2436         2015
2437         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2438  Flight2439  41765  ORD-JFK              2.0         129
2439  Flight2440  42005  ORD-MIA              1.2         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2438             0.291667               250       46250             5
2439             0.500000               300       49500             1

      Flight Year
2438         2014
2439         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2440  Flight2441  41797  ORD-DEN              3.1          52
2441  Flight2442  42273  ORD-DEN              1.5         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2440             0.833333               330       54450             6
2441             0.312500               300       49500             9

      Flight Year
2440         2014
2441         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2442  Flight2443  41722  ORD-MCO              1.2          26
2443  Flight2444  42361  ORD-DEN              3.5          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2442             0.750000               250       46250             3
2443             0.291667               420       69300            12

      Flight Year
2442         2014
2443         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2444  Flight2445  41740  ORD-PHL              2.0          11
2445  Flight2446  41728  ORD-EWR              2.6         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2444             0.583333               275       50875             4
2445             0.291667               225       37125             3

      Flight Year
2444         2014
2445         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2446  Flight2447  41796  ORD-MSP              2.0         174
2447  Flight2448  42098  ORD-DFW              1.7         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2446             0.416667             126.5     20872.5             6
2447             0.791667             200.0     33000.0             4

      Flight Year
2446         2014
2447         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2448  Flight2449  42102  ORD-JFK              2.5         209
2449  Flight2450  41726  ORD-BOS              2.5         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2448             0.625000               250       41250             4
2449             0.791667               300       49500             3

      Flight Year
2448         2015
2449         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2450  Flight2451  41824  ORD-MSP              3.2         204
2451  Flight2452  42042  ORD-SFO              2.5         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2450                 0.75             126.5     20872.5             7
2451                 0.50             375.0     69375.0             2

      Flight Year
2450         2014
2451         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2452  Flight2453  42201  ORD-DTW              1.7         186
2453  Flight2454  42366  ORD-PHX              1.4          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2452             0.791667             126.5     20872.5             7
2453             0.291667             250.0     41250.0            12

      Flight Year
2452         2015
2453         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2454  Flight2455  41846  ORD-CLT              2.6          24
2455  Flight2456  42280  ORD-DTW              2.9         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2454             0.562500             137.5     25437.5             7
2455             0.333333             115.0     21275.0            10

      Flight Year
2454         2014
2455         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2456  Flight2457  41861  ORD-SFO              2.3          16
2457  Flight2458  41857  ORD-JFK              0.9          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2456             0.291667             412.5     76312.5             8
2457             0.291667             275.0     49775.0             8

      Flight Year
2456         2014
2457         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2458  Flight2459  41695  ORD-FLL              1.4         131
2459  Flight2460  41864  ORD-ATL              8.1         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2458             0.791667               300       55500             2
2459             0.333333               220       36300             8

      Flight Year
2458         2014
2459         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2460  Flight2461  41971  ORD-LAX             10.1           9
2461  Flight2462  41717  ORD-IAH              2.7         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2460             0.291667               525       97125            11
2461             0.791667               200       33000             3

      Flight Year
2460         2014
2461         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2462  Flight2463  41676  ORD-PHL              2.6         115
2463  Flight2464  42306  ORD-DTW              2.4         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2462             0.666667               275       50875             2
2463             0.562500               115       18975            10

      Flight Year
2462         2014
2463         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2464  Flight2465  41996  ORD-JFK              4.2         128
2465  Flight2466  42036  ORD-DCA              2.4          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2464             0.791667               350       64750            12
2465             0.750000              5000      925000             2

      Flight Year
2464         2014
2465         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2466  Flight2467  42048  ORD-DEN              2.5         191
2467  Flight2468  41851  ORD-PHX              2.0          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2466             0.291667               300       49500             2
2467             0.291667               275       50875             7

      Flight Year
2466         2015
2467         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2468  Flight2469  41993  ORD-DFW              1.9          29
2469  Flight2470  42085  ORD-LAX              2.4          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2468               0.3125               200       37000            12
2469               0.5000               350       64750             3

      Flight Year
2468         2014
2469         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2470  Flight2471  42213  ORD-JFK                2          40
2471  Flight2472  42208  ORD-PHX                2           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2470             0.458333               275       45375             7
2471             0.833333               275       50875             7

      Flight Year
2470         2015
2471         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2472  Flight2473  41785  ORD-LGA              1.7         107
2473  Flight2474  41792  ORD-ATL             12.1          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2472             0.437500               275       50875             5
2473             0.791667               220       40700             6

      Flight Year
2472         2014
2473         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2474  Flight2475  41912  ORD-SFO              2.4          38
2475  Flight2476  42233  ORD-LAS              0.5         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2474             0.812500             375.0     61875.0             9
2475             0.291667             302.5     55962.5             8

      Flight Year
2474         2014
2475         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2476  Flight2477  42114  ORD-MCO              1.4         187
2477  Flight2478  41848  ORD-DEN              2.4           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2476             0.750000               250       41250             4
2477             0.291667               330       61050             7

      Flight Year
2476         2015
2477         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2478  Flight2479  42280  ORD-BWI              1.9         204
2479  Flight2480  41672  ORD-PHX              0.9          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2478             0.750000               240       39600            10
2479             0.770833               250       46250             2

      Flight Year
2478         2015
2479         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2480  Flight2481  41725  ORD-SEA              1.8         140
2481  Flight2482  41849  ORD-MSP              1.7          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2480             0.291667             350.0     64750.0             3
2481             0.770833             126.5     22896.5             7

      Flight Year
2480         2014
2481         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2482  Flight2483  42189  ORD-DTW              1.9         151
2483  Flight2484  41872  ORD-MIA              3.3          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2482               0.3125             126.5     23402.5             7
2483               0.5625             330.0     61050.0             8

      Flight Year
2482         2015
2483         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2484  Flight2485  41698  ORD-CLT              1.2         102
2485  Flight2486  41828  ORD-IAH              1.3         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2484             0.291667               125       23125             2
2485             0.791667               220       40700             7

      Flight Year
2484         2014
2485         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2486  Flight2487  42207  ORD-MCO              0.9         113
2487  Flight2488  42045  ORD-DTW              1.4          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2486             0.291667               275       50875             7
2487             0.770833               115       20815             2

      Flight Year
2486         2015
2487         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2488  Flight2489  42210  ORD-SFO              2.3          42
2489  Flight2490  41969  ORD-DFW              4.8          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2488             0.520833             412.5     68062.5             7
2489             0.604167             300.0     49500.0            11

      Flight Year
2488         2015
2489         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2490  Flight2491  41881  ORD-ATL             10.4         153
2491  Flight2492  41897  ORD-JFK              1.6         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2490             0.791667               220       36300             8
2491             0.687500               250       46250             9

      Flight Year
2490         2014
2491         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2492  Flight2493  41943  ORD-SFO              1.5         206
2493  Flight2494  42183  ORD-IAH              2.9          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2492             0.750000               375       61875            10
2493             0.333333               220       39820             6

      Flight Year
2492         2014
2493         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2494  Flight2495  41720  ORD-DEN              1.6         200
2495  Flight2496  42122  ORD-SFO              2.6          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2494             0.708333               300       49500             3
2495             0.666667               375       67875             4

      Flight Year
2494         2014
2495         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2496  Flight2497  41833  ORD-LAS              2.5          64
2497  Flight2498  41972  ORD-BOS              6.5         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2496             0.333333             302.5     54752.5             7
2497             0.625000             450.0     74250.0            11

      Flight Year
2496         2014
2497         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2498  Flight2499  42127  ORD-SFO              2.5         119
2499  Flight2500  41963  ORD-SLC              1.9          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2498             0.750000               375       69375             5
2499             0.520833               290       47850            11

      Flight Year
2498         2015
2499         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2500  Flight2501  41760  ORD-LGA              2.7         116
2501  Flight2502  41914  ORD-DEN              1.3         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2500             0.333333               275       50875             5
2501             0.875000               300       55500            10

      Flight Year
2500         2014
2501         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2502  Flight2503  41882  ORD-PHX              3.0          76
2503  Flight2504  42207  ORD-DFW              1.1          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2502             0.458333               275       49775             8
2503             0.500000               220       40700             7

      Flight Year
2502         2014
2503         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2504  Flight2505  42001  ORD-LGA              4.6          54
2505  Flight2506  42239  ORD-MSP              2.0          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2504             0.750000             385.0     63525.0            12
2505             0.541667             126.5     23402.5             8

      Flight Year
2504         2014
2505         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2506  Flight2507  42175  ORD-MIA              1.5          28
2507  Flight2508  41968  ORD-MIA              5.3         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2506             0.291667               330       61050             6
2507             0.291667               450       74250            11

      Flight Year
2506         2015
2507         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2508  Flight2509  41977  ORD-MIA              2.4          97
2509  Flight2510  41765  ORD-MCO              1.1         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2508             0.541667               300       55500            12
2509             0.291667               250       46250             5

      Flight Year
2508         2014
2509         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2510  Flight2511  41775  ORD-PHX                2         114
2511  Flight2512  42299  ORD-ATL                6         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2510             0.791667               250       46250             5
2511             0.812500               200       33000            10

      Flight Year
2510         2014
2511         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2512  Flight2513  41965  ORD-IAH              0.9         136
2513  Flight2514  42016  ORD-MIA              1.8         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2512             0.354167               200       37000            11
2513             0.708333               300       49500             1

      Flight Year
2512         2014
2513         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2514  Flight2515  41974  ORD-LGA              3.2         180
2515  Flight2516  41800  ORD-IAH              2.6         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2514             0.750000               275       45375            12
2515             0.583333               220       40700             6

      Flight Year
2514         2014
2515         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2516  Flight2517  41772  ORD-DEN              0.7          62
2517  Flight2518  42040  ORD-LAX              4.2         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2516             0.458333               300       49500             5
2517             0.583333               350       64750             2

      Flight Year
2516         2014
2517         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2518  Flight2519  41759  ORD-SFO              2.1          56
2519  Flight2520  42195  ORD-EWR              2.5         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2518             0.770833             375.0     61875.0             4
2519             0.895833             247.5     45787.5             7

      Flight Year
2518         2014
2519         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2520  Flight2521  41964  ORD-JFK              1.3         172
2521  Flight2522  42361  ORD-PHX              1.1         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2520             0.645833               250       41250            11
2521             0.562500               350       64750            12

      Flight Year
2520         2014
2521         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2522  Flight2523  41711  ORD-PHL              2.4         117
2523  Flight2524  42230  ORD-DTW              1.8         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2522             0.750000             275.0     50875.0             3
2523             0.854167             126.5     23402.5             8

      Flight Year
2522         2014
2523         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2524  Flight2525  41688  ORD-BOS              1.4         113
2525  Flight2526  41660  ORD-MSP              1.5          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2524             0.333333               300       55500             2
2525             0.791667               115       21275             1

      Flight Year
2524         2014
2525         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2526  Flight2527  42115  ORD-SEA              0.9          71
2527  Flight2528  42046  ORD-LAS              2.0          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2526             0.750000               350       63350             4
2527             0.791667               275       45375             2

      Flight Year
2526         2015
2527         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2528  Flight2529  42215  ORD-DEN              2.0          47
2529  Flight2530  42097  ORD-DEN              1.9         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2528             0.708333               330       54450             7
2529             0.604167               300       55500             4

      Flight Year
2528         2015
2529         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2530  Flight2531  41720  ORD-IAH              2.0          82
2531  Flight2532  42334  ORD-DEN              3.8         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2530             0.625000               200       36200             3
2531             0.291667               450       74250            11

      Flight Year
2530         2014
2531         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2532  Flight2533  42140  ORD-DFW              1.0          65
2533  Flight2534  41863  ORD-ATL              8.3         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2532             0.479167               200       36200             5
2533             0.895833               220       40700             8

      Flight Year
2532         2015
2533         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2534  Flight2535  41932  ORD-DTW              1.8          49
2535  Flight2536  42211  ORD-LAS              1.1         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2534               0.3750             115.0     18975.0            10
2535               0.8125             302.5     49912.5             7

      Flight Year
2534         2014
2535         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2536  Flight2537  42307  ORD-FLL              1.8          25
2537  Flight2538  42163  ORD-PHL              2.3         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2536             0.708333             300.0     55500.0            10
2537             0.375000             302.5     55962.5             6

      Flight Year
2536         2015
2537         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2538  Flight2539  42332  ORD-DFW              6.4         181
2539  Flight2540  41839  ORD-MSP              2.1          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2538             0.708333             300.0     49500.0            11
2539             0.708333             126.5     23402.5             7

      Flight Year
2538         2015
2539         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2540  Flight2541  41868  ORD-IAH              0.9         176
2541  Flight2542  41843  ORD-JFK              2.2         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2540             0.770833               220       36300             8
2541             0.333333               275       45375             7

      Flight Year
2540         2014
2541         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2542  Flight2543  41816  ORD-PHX              2.1          29
2543  Flight2544  41891  ORD-DFW              2.4         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2542             0.541667               275       50875             6
2543             0.729167               200       37000             9

      Flight Year
2542         2014
2543         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2544  Flight2545  41874  ORD-LAX              5.3         132
2545  Flight2546  41985  ORD-EWR              2.0          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2544                 0.75               385       71225             8
2545                 0.75               225       41625            12

      Flight Year
2544         2014
2545         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2546  Flight2547  42199  ORD-JFK              2.4          78
2547  Flight2548  41797  ORD-DEN              2.1         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2546             0.479167               275       49775             7
2547             0.291667               330       54450             6

      Flight Year
2546         2015
2547         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2548  Flight2549  42192  ORD-MCO              3.1          27
2549  Flight2550  42103  ORD-JFK              1.6         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2548             0.625000               275       50875             7
2549             0.833333               250       41250             4

      Flight Year
2548         2015
2549         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2550  Flight2551  42337  ORD-PHX              4.0          53
2551  Flight2552  42215  ORD-PHX              2.4          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2550             0.291667               375       61875            11
2551             0.729167               275       45375             7

      Flight Year
2550         2015
2551         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2552  Flight2553  41971  ORD-DTW              5.7          40
2553  Flight2554  41961  ORD-MSP              1.5          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2552                0.750             172.5     28462.5            11
2553                0.875             115.0     21275.0            11

      Flight Year
2552         2014
2553         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2554  Flight2555  41680  ORD-MSP              2.6         210
2555  Flight2556  42290  ORD-DEN              2.1          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2554             0.875000               115       18975             2
2555             0.333333               300       54300            10

      Flight Year
2554         2014
2555         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2556  Flight2557  41821  ORD-SFO              1.7         112
2557  Flight2558  42180  ORD-IAH              2.0          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2556             0.770833             412.5     76312.5             7
2557             0.812500             220.0     36300.0             6

      Flight Year
2556         2014
2557         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2558  Flight2559  42276  ORD-ATL              6.9         142
2559  Flight2560  42356  ORD-DFW              2.7          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2558             0.791667               200       37000             9
2559             0.708333               200       36200            12

      Flight Year
2558         2015
2559         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2560  Flight2561  42291  ORD-PHX              2.3          85
2561  Flight2562  42186  ORD-LAX              6.4         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2560             0.458333               250       45250            10
2561             0.812500               385       63525             7

      Flight Year
2560         2015
2561         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2562  Flight2563  42299  ORD-SFO              2.9         123
2563  Flight2564  41911  ORD-LGA              2.7          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2562             0.708333               375       69375            10
2563             0.458333               275       50875             9

      Flight Year
2562         2015
2563         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2564  Flight2565  41863  ORD-DEN              3.3         206
2565  Flight2566  42353  ORD-DFW              2.6         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2564             0.791667               330       54450             8
2565             0.333333               200       37000            12

      Flight Year
2564         2014
2565         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2566  Flight2567  41678  ORD-ATL              6.7         119
2567  Flight2568  42165  ORD-JFK              3.8          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2566             0.812500               200       37000             2
2567             0.333333               275       50875             6

      Flight Year
2566         2014
2567         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2568  Flight2569  41837  ORD-LAS              1.6          42
2569  Flight2570  42332  ORD-MCO              4.7         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2568             0.416667             302.5     49912.5             7
2569             0.562500             375.0     61875.0            11

      Flight Year
2568         2014
2569         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2570  Flight2571  41924  ORD-LGA              1.4         171
2571  Flight2572  41821  ORD-DEN              2.6         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2570             0.375000               275       45375            10
2571             0.291667               330       54450             7

      Flight Year
2570         2014
2571         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2572  Flight2573  41691  ORD-CLT              1.7         200
2573  Flight2574  42298  ORD-CLT              2.4         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2572             0.729167               125       20625             2
2573             0.333333               125       23125            10

      Flight Year
2572         2014
2573         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2574  Flight2575  41721  ORD-CLT              4.1          81
2575  Flight2576  42256  ORD-CLT              1.4         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2574             0.875000               125       22625             3
2575             0.354167               125       23125             9

      Flight Year
2574         2014
2575         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2576  Flight2577  41885  ORD-MIA              1.7          98
2577  Flight2578  41780  ORD-LAS              2.4          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2576             0.416667               300       55500             9
2577             0.833333               275       50875             5

      Flight Year
2576         2014
2577         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2578  Flight2579  41681  ORD-JFK              1.7         161
2579  Flight2580  41897  ORD-ATL              9.3          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2578             0.458333               250       41250             2
2579             0.291667               200       33000             9

      Flight Year
2578         2014
2579         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2580  Flight2581  41726  ORD-LGA              2.4         140
2581  Flight2582  41780  ORD-IAH              2.1          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2580             0.729167               275       50875             3
2581             0.625000               200       36200             5

      Flight Year
2580         2014
2581         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2582  Flight2583  41919  ORD-CLT              2.0         147
2583  Flight2584  42111  ORD-MSP              1.8          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2582             0.812500               125       23125            10
2583             0.791667               115       20815             4

      Flight Year
2582         2014
2583         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2584  Flight2585  41998  ORD-JFK              4.4          21
2585  Flight2586  42363  ORD-SEA              2.7          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2584             0.708333               350       64750            12
2585             0.791667               490       88690            12

      Flight Year
2584         2014
2585         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2586  Flight2587  41906  ORD-CLT              2.0         153
2587  Flight2588  41752  ORD-CLT              2.2          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2586             0.875000               125       20625             9
2587             0.541667               125       23125             4

      Flight Year
2586         2014
2587         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2588  Flight2589  41685  ORD-IAH              2.1          40
2589  Flight2590  41653  ORD-SFO              1.8          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2588             0.791667               200       33000             2
2589             0.291667               375       69375             1

      Flight Year
2588         2014
2589         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2590  Flight2591  42286  ORD-ATL              8.5         124
2591  Flight2592  41952  ORD-ATL             10.3         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2590             0.750000               200       37000            10
2591             0.520833               200       33000            11

      Flight Year
2590         2015
2591         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2592  Flight2593  41916  ORD-LAS              1.7         167
2593  Flight2594  41716  ORD-LAX              4.2           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2592             0.416667               275       45375            10
2593             0.458333               350       64750             3

      Flight Year
2592         2014
2593         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2594  Flight2595  42307  ORD-DFW              3.1          35
2595  Flight2596  42077  ORD-PHX              2.2          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2594             0.291667               200       37000            10
2595             0.791667               250       45250             3

      Flight Year
2594         2015
2595         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2596  Flight2597  42035  ORD-SFO              3.1         187
2597  Flight2598  41716  ORD-ATL              8.6         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2596             0.333333               375       61875             1
2597             0.791667               200       33000             3

      Flight Year
2596         2015
2597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2598  Flight2599  41887  ORD-JFK              2.3         186
2599  Flight2600  42143  ORD-IAH              2.0          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2598                0.750               250       41250             9
2599                0.375               200       33000             5

      Flight Year
2598         2014
2599         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2600  Flight2601  41662  ORD-CLT              1.6         188
2601  Flight2602  41671  ORD-MIA              1.6           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2600             0.291667               125       20625             1
2601             0.770833               300       55500             2

      Flight Year
2600         2014
2601         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2602  Flight2603  41863  ORD-ATL              7.3         135
2603  Flight2604  41929  ORD-SFO              0.7         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2602             0.791667               220       40700             8
2603             0.708333               375       69375            10

      Flight Year
2602         2014
2603         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2604  Flight2605  42357  ORD-MIA              1.8         172
2605  Flight2606  42271  ORD-LAS              2.9         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2604             0.791667               300       49500            12
2605             0.291667               275       45375             9

      Flight Year
2604         2015
2605         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2606  Flight2607  42187  ORD-PHX              2.7           5
2607  Flight2608  42072  ORD-ATL              9.5         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2606               0.4375               275       50875             7
2607               0.4375               200       33000             3

      Flight Year
2606         2015
2607         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2608  Flight2609  41935  ORD-MCO              2.2         178
2609  Flight2610  42193  ORD-CLT              2.4         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2608             0.750000             250.0     41250.0            10
2609             0.333333             137.5     25437.5             7

      Flight Year
2608         2014
2609         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2610  Flight2611  41915  ORD-SEA              2.4          53
2611  Flight2612  41995  ORD-CLT              4.6          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2610             0.541667               350       57750            10
2611             0.791667               175       32375            12

      Flight Year
2610         2014
2611         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2612  Flight2613  42197  ORD-PHX              2.4          59
2613  Flight2614  42143  ORD-MCO              2.7         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2612             0.562500               275       45375             7
2613             0.333333               250       41250             5

      Flight Year
2612         2015
2613         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2614  Flight2615  41738  ORD-DEN              1.4          23
2615  Flight2616  41720  ORD-LAS              2.1           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2614             0.812500               300       55500             4
2615             0.291667               275       50875             3

      Flight Year
2614         2014
2615         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2616  Flight2617  42332  ORD-EWR              4.6          38
2617  Flight2618  42156  ORD-SFO              2.4         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2616             0.291667             337.5     55687.5            11
2617             0.791667             412.5     76312.5             6

      Flight Year
2616         2015
2617         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2618  Flight2619  42156  ORD-MSP              1.8           8
2619  Flight2620  42346  ORD-PHL              1.9          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2618             0.458333             126.5     23402.5             6
2619             0.812500             275.0     45375.0            12

      Flight Year
2618         2015
2619         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2620  Flight2621  41792  ORD-CLT              1.1          17
2621  Flight2622  42237  ORD-DEN              1.8         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2620             0.375000             137.5     25437.5             6
2621             0.708333             330.0     54450.0             8

      Flight Year
2620         2014
2621         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2622  Flight2623  41669  ORD-MIA              2.8           7
2623  Flight2624  41889  ORD-EWR              1.4         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2622               0.3125               300       55500             1
2623               0.7500               225       41625             9

      Flight Year
2622         2014
2623         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2624  Flight2625  41970  ORD-MIA              5.0          66
2625  Flight2626  41794  ORD-EWR              2.6         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2624             0.333333             450.0     81450.0            11
2625             0.708333             247.5     40837.5             6

      Flight Year
2624         2014
2625         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2626  Flight2627  42054  ORD-JFK              1.3         195
2627  Flight2628  42238  ORD-LAX              3.9         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2626             0.416667               250       41250             2
2627             0.312500               385       63525             8

      Flight Year
2626         2015
2627         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2628  Flight2629  41688  ORD-CLT              2.8         207
2629  Flight2630  41846  ORD-EWR              3.5          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2628             0.333333             125.0     20625.0             2
2629             0.854167             247.5     45787.5             7

      Flight Year
2628         2014
2629         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2630  Flight2631  42246  ORD-LAS              2.9          61
2631  Flight2632  41969  ORD-LAX             10.0          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2630             0.583333             302.5     49912.5             8
2631             0.708333             525.0     95025.0            11

      Flight Year
2630         2015
2631         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2632  Flight2633  42342  ORD-ATL              7.4          73
2633  Flight2634  42133  ORD-PHX              1.3          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2632             0.833333               200       36200            12
2633             0.291667               250       46250             5

      Flight Year
2632         2015
2633         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2634  Flight2635  41761  ORD-SFO              3.8          69
2635  Flight2636  41742  ORD-EWR              1.8         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2634             0.791667               375       67875             5
2635             0.708333               225       37125             4

      Flight Year
2634         2014
2635         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2636  Flight2637  42285  ORD-CLT              2.1         182
2637  Flight2638  42115  ORD-EWR              2.2         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2636             0.291667               125       20625            10
2637             0.291667               225       41625             4

      Flight Year
2636         2015
2637         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2638  Flight2639  42333  ORD-ATL             19.2         138
2639  Flight2640  42222  ORD-MCO              1.6         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2638             0.479167               300       55500            11
2639             0.812500               275       50875             8

      Flight Year
2638         2015
2639         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2640  Flight2641  42369  ORD-EWR              2.2          34
2641  Flight2642  41997  ORD-DFW              4.3          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2640             0.333333               225       41625            12
2641             0.583333               280       46200            12

      Flight Year
2640         2015
2641         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2642  Flight2643  42359  ORD-PHL              1.8         173
2643  Flight2644  42223  ORD-CLT              1.2         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2642                 0.75             385.0     63525.0            12
2643                 0.50             137.5     25437.5             8

      Flight Year
2642         2015
2643         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2644  Flight2645  41971  ORD-MCO              6.1          76
2645  Flight2646  42336  ORD-SEA              4.1         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2644             0.520833               375       67875            11
2645             0.833333               525       86625            11

      Flight Year
2644         2014
2645         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2646  Flight2647  42296  ORD-LAX              4.2         189
2647  Flight2648  42014  ORD-DFW              1.8          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2646             0.708333               350       57750            10
2647             0.291667               200       37000             1

      Flight Year
2646         2015
2647         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2648  Flight2649  41656  ORD-ATL                6          43
2649  Flight2650  41823  ORD-BOS                2         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2648             0.770833               200       33000             1
2649             0.750000               330       61050             7

      Flight Year
2648         2014
2649         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2650  Flight2651  41796  ORD-CLT              1.9         144
2651  Flight2652  41956  ORD-SEA              1.7          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2650                 0.75             137.5     25437.5             6
2651                 0.50             350.0     63350.0            11

      Flight Year
2650         2014
2651         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2652  Flight2653  41812  ORD-SEA              1.3          58
2653  Flight2654  42026  ORD-SEA              2.3         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2652               0.5000               385       63525             6
2653               0.3125               350       64750             1

      Flight Year
2652         2014
2653         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2654  Flight2655  42177  ORD-DFW              2.3         194
2655  Flight2656  42130  ORD-DEN              0.8         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2654             0.520833               220       36300             6
2655             0.708333               300       49500             5

      Flight Year
2654         2015
2655         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2656  Flight2657  41694  ORD-DEN              1.7          83
2657  Flight2658  42060  ORD-LGA              2.4         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2656               0.3125               300       54300             2
2657               0.7500               275       50875             2

      Flight Year
2656         2014
2657         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2658  Flight2659  41867  ORD-BOS              1.1          58
2659  Flight2660  42184  ORD-LAX              4.5          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2658             0.333333               330       54450             8
2659             0.645833               385       69685             6

      Flight Year
2658         2014
2659         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2660  Flight2661  42083  ORD-DEN              1.1         104
2661  Flight2662  42117  ORD-LAX              3.2           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2660               0.8125               300       55500             3
2661               0.8750               350       64750             4

      Flight Year
2660         2015
2661         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2662  Flight2663  42332  ORD-SFO              2.8         110
2663  Flight2664  42368  ORD-DEN              1.8         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2662             0.875000             562.5    104062.5            11
2663             0.791667             300.0     49500.0            12

      Flight Year
2662         2015
2663         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2664  Flight2665  42258  ORD-IAH              2.9         154
2665  Flight2666  41799  ORD-JFK              2.5          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2664             0.458333               200       33000             9
2665             0.708333               275       50875             6

      Flight Year
2664         2015
2665         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2666  Flight2667  41920  ORD-DFW              3.0         165
2667  Flight2668  42104  ORD-MIA              1.9           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2666               0.3125               200       33000            10
2667               0.7500               300       55500             4

      Flight Year
2666         2014
2667         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2668  Flight2669  41861  ORD-MIA              2.2         132
2669  Flight2670  41948  ORD-ATL              8.5         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2668             0.291667               330       61050             8
2669             0.791667               200       33000            11

      Flight Year
2668         2014
2669         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2670  Flight2671  41678  ORD-CLT              2.6         173
2671  Flight2672  42207  ORD-LGA              0.8         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2670             0.729167             125.0     20625.0             2
2671             0.666667             302.5     49912.5             7

      Flight Year
2670         2014
2671         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2672  Flight2673  42024  ORD-SFO              1.7         158
2673  Flight2674  41746  ORD-ATL              7.8          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2672               0.8125               375       61875             1
2673               0.6875               200       37000             4

      Flight Year
2672         2015
2673         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2674  Flight2675  41830  ORD-CLT              2.0         116
2675  Flight2676  42000  ORD-CLT              5.5         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2674             0.791667             137.5     25437.5             7
2675             0.375000             175.0     28875.0            12

      Flight Year
2674         2014
2675         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2676  Flight2677  42117  ORD-ATL             10.4          71
2677  Flight2678  42018  ORD-CLT              2.4          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2676             0.500000               200       36200             4
2677             0.541667               125       23125             1

      Flight Year
2676         2015
2677         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2678  Flight2679  42204  ORD-ATL              6.0         113
2679  Flight2680  41741  ORD-MIA              1.3         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2678             0.291667               220       40700             7
2679             0.708333               300       55500             4

      Flight Year
2678         2015
2679         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2680  Flight2681  42094  ORD-LGA              2.7          31
2681  Flight2682  42281  ORD-JFK              2.4          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2680             0.395833               275       50875             3
2681             0.375000               250       41250            10

      Flight Year
2680         2015
2681         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2682  Flight2683  42239  ORD-MIA              2.3          10
2683  Flight2684  42064  ORD-EWR              2.1          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2682             0.312500               330       61050             8
2683             0.791667               225       37125             3

      Flight Year
2682         2015
2683         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2684  Flight2685  42144  ORD-EWR              1.8          74
2685  Flight2686  42131  ORD-MCO              1.9           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2684             0.791667               225       40725             5
2685             0.770833               250       46250             5

      Flight Year
2684         2015
2685         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2686  Flight2687  41856  ORD-PHX              1.0          93
2687  Flight2688  41681  ORD-JFK              2.6          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2686             0.791667               275       50875             8
2687             0.750000               250       46250             2

      Flight Year
2686         2014
2687         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2688  Flight2689  41794  ORD-MIA              1.2          87
2689  Flight2690  42308  ORD-IAH              1.8         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2688             0.812500               330       59730             6
2689             0.791667               200       33000            10

      Flight Year
2688         2014
2689         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2690  Flight2691  41809  ORD-DFW              1.4         199
2691  Flight2692  41950  ORD-DFW              1.0          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2690             0.791667               220       36300             6
2691             0.291667               200       37000            11

      Flight Year
2690         2014
2691         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2692  Flight2693  42323  ORD-EWR              3.3           7
2693  Flight2694  41752  ORD-DEN              2.1         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2692             0.729167               225       41625            11
2693             0.354167               300       55500             4

      Flight Year
2692         2015
2693         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2694  Flight2695  41696  ORD-SFO              2.5         188
2695  Flight2696  41861  ORD-DFW              2.7          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2694             0.791667               375       61875             2
2695             0.708333               220       40700             8

      Flight Year
2694         2014
2695         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2696  Flight2697  41670  ORD-LAS              1.3          90
2697  Flight2698  41999  ORD-ATL             15.3          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2696             0.791667               275       49775             1
2697             0.791667               280       50680            12

      Flight Year
2696         2014
2697         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2698  Flight2699  41876  ORD-JFK              2.7         153
2699  Flight2700  41811  ORD-ATL             11.0         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2698             0.312500               275       45375             8
2699             0.333333               220       36300             6

      Flight Year
2698         2014
2699         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2700  Flight2701  41840  ORD-ATL              8.0         209
2701  Flight2702  42083  ORD-LAS              2.2          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2700             0.833333               220       36300             7
2701             0.791667               275       49775             3

      Flight Year
2700         2014
2701         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2702  Flight2703  42263  ORD-IAH              2.0         205
2703  Flight2704  42249  ORD-DFW              1.7         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2702             0.770833               200       33000             9
2703             0.708333               200       37000             9

      Flight Year
2702         2015
2703         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2704  Flight2705  42124  ORD-MSP              0.7           4
2705  Flight2706  41925  ORD-ATL             12.2         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2704             0.791667               115       21275             4
2705             0.833333               200       33000            10

      Flight Year
2704         2015
2705         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2706  Flight2707  41879  ORD-LAX              6.4         162
2707  Flight2708  42219  ORD-LAS              2.3         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2706             0.791667             385.0     63525.0             8
2707             0.291667             302.5     55962.5             8

      Flight Year
2706         2014
2707         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2708  Flight2709  42297  ORD-SEA              2.1          30
2709  Flight2710  41803  ORD-MSP              2.1          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2708             0.729167             350.0     64750.0            10
2709             0.687500             126.5     23402.5             6

      Flight Year
2708         2015
2709         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2710  Flight2711  41840  ORD-EWR              2.3         123
2711  Flight2712  42318  ORD-LAX              6.2         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2710             0.645833             247.5     45787.5             7
2711             0.312500             350.0     57750.0            11

      Flight Year
2710         2014
2711         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2712  Flight2713  41841  ORD-EWR              1.4          11
2713  Flight2714  42125  ORD-PHL              0.8         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2712             0.583333             247.5     45787.5             7
2713             0.416667             275.0     45375.0             5

      Flight Year
2712         2014
2713         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2714  Flight2715  42049  ORD-SFO              2.0          62
2715  Flight2716  42210  ORD-FLL              2.3         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2714             0.791667               375       61875             2
2715             0.750000               330       61050             7

      Flight Year
2714         2015
2715         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2716  Flight2717  42137  ORD-DFW              2.1         117
2717  Flight2718  41784  ORD-FLL              2.4          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2716             0.333333               200       37000             5
2717             0.333333               300       54300             5

      Flight Year
2716         2015
2717         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2718  Flight2719  42019  ORD-CLT              1.4         182
2719  Flight2720  41686  ORD-LAS              1.9         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2718             0.750000               125       20625             1
2719             0.416667               275       50875             2

      Flight Year
2718         2015
2719         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2720  Flight2721  41650  ORD-MCO              2.4         138
2721  Flight2722  41663  ORD-LAX              4.3          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2720             0.625000               250       46250             1
2721             0.791667               350       57750             1

      Flight Year
2720         2014
2721         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2722  Flight2723  42189  ORD-PHL              2.1          67
2723  Flight2724  41874  ORD-JFK              2.1          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2722             0.854167             302.5     54752.5             7
2723             0.541667             275.0     50875.0             8

      Flight Year
2722         2015
2723         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2724  Flight2725  42269  ORD-IAH              1.5         193
2725  Flight2726  42246  ORD-JFK              2.8          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2724             0.833333               200       33000             9
2725             0.291667               275       45375             8

      Flight Year
2724         2015
2725         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2726  Flight2727  42304  ORD-LAS              1.9         113
2727  Flight2728  41858  ORD-ATL             13.3          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2726             0.750000               275       50875            10
2727             0.770833               220       39820             8

      Flight Year
2726         2015
2727         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2728  Flight2729  42053  ORD-DTW              1.7          48
2729  Flight2730  41795  ORD-SFO              2.3         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2728             0.750000             115.0     18975.0             2
2729             0.583333             412.5     68062.5             6

      Flight Year
2728         2015
2729         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2730  Flight2731  42131  ORD-MSP              3.6          57
2731  Flight2732  41889  ORD-MSP              2.1         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2730             0.333333               115       18975             5
2731             0.708333               115       21275             9

      Flight Year
2730         2015
2731         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2732  Flight2733  41765  ORD-CLT              2.7         126
2733  Flight2734  42098  ORD-ATL             10.4         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2732             0.791667               125       23125             5
2733             0.791667               200       33000             4

      Flight Year
2732         2014
2733         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2734  Flight2735  41821  ORD-CLT              2.8          47
2735  Flight2736  42176  ORD-JFK              2.1          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2734             0.291667             137.5     22687.5             7
2735             0.291667             275.0     49775.0             6

      Flight Year
2734         2014
2735         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2736  Flight2737  42146  ORD-ATL              9.3         130
2737  Flight2738  42063  ORD-CLT              3.1         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2736             0.833333               200       37000             5
2737             0.708333               125       23125             2

      Flight Year
2736         2015
2737         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2738  Flight2739  42151  ORD-MSP              2.3         173
2739  Flight2740  41905  ORD-PHX              2.3          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2738             0.437500               115       18975             5
2739             0.791667               250       45250             9

      Flight Year
2738         2015
2739         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2740  Flight2741  41645  ORD-DTW              2.3          98
2741  Flight2742  42178  ORD-LAX              3.8         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2740             0.791667               115       21275             1
2741             0.791667               385       63525             6

      Flight Year
2740         2014
2741         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2742  Flight2743  41675  ORD-SFO              0.8          45
2743  Flight2744  42198  ORD-IAH              1.4          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2742             0.291667               375       61875             2
2743             0.291667               220       36300             7

      Flight Year
2742         2014
2743         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2744  Flight2745  41696  ORD-LAX              5.7         161
2745  Flight2746  42119  ORD-ATL              9.3          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2744             0.291667               350       57750             2
2745             0.833333               200       36200             4

      Flight Year
2744         2014
2745         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2746  Flight2747  41750  ORD-BWI              1.3           8
2747  Flight2748  42180  ORD-PHX              1.9         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2746             0.791667               240       44400             4
2747             0.291667               275       45375             6

      Flight Year
2746         2014
2747         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2748  Flight2749  41646  ORD-MSP              1.4          27
2749  Flight2750  42242  ORD-EWR              1.7          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2748             0.833333             115.0     21275.0             1
2749             0.291667             247.5     40837.5             8

      Flight Year
2748         2014
2749         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2750  Flight2751  42055  ORD-LAS              1.8          72
2751  Flight2752  41862  ORD-PHX              1.1          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2750             0.708333               275       49775             2
2751             0.687500               275       50875             8

      Flight Year
2750         2015
2751         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2752  Flight2753  42130  ORD-ATL             10.7         143
2753  Flight2754  42334  ORD-EWR              5.1         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2752             0.666667             200.0     37000.0             5
2753             0.291667             337.5     55687.5            11

      Flight Year
2752         2015
2753         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2754  Flight2755  42275  ORD-ATL              9.0          17
2755  Flight2756  42301  ORD-SFO              1.5          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2754             0.708333               200       37000             9
2755             0.812500               375       67875            10

      Flight Year
2754         2015
2755         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2756  Flight2757  41843  ORD-PHX              2.2          95
2757  Flight2758  42300  ORD-SFO              1.9         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2756             0.500000               275       50875             7
2757             0.291667               375       61875            10

      Flight Year
2756         2014
2757         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2758  Flight2759  42127  ORD-MCO              1.1         104
2759  Flight2760  42312  ORD-EWR              2.0          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2758             0.333333               250       46250             5
2759             0.791667               225       40725            11

      Flight Year
2758         2015
2759         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2760  Flight2761  41989  ORD-LAS              1.1          74
2761  Flight2762  42252  ORD-DFW              1.7          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2760             0.333333               275       49775            12
2761             0.729167               200       37000             9

      Flight Year
2760         2014
2761         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2762  Flight2763  41889  ORD-CLT              1.9         105
2763  Flight2764  42332  ORD-DEN              5.4          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2762             0.854167               125       23125             9
2763             0.416667               450       74250            11

      Flight Year
2762         2014
2763         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2764  Flight2765  41776  ORD-JFK              1.3          73
2765  Flight2766  41982  ORD-DFW              1.1           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2764             0.458333               250       45250             5
2765             0.812500               200       37000            12

      Flight Year
2764         2014
2765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2766  Flight2767  41735  ORD-PHX              2.9         190
2767  Flight2768  42300  ORD-MIA              1.6         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2766             0.312500               250       41250             4
2767             0.833333               300       55500            10

      Flight Year
2766         2014
2767         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2768  Flight2769  42155  ORD-PHL              2.3          26
2769  Flight2770  41745  ORD-MIA              2.0           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2768             0.291667               275       50875             5
2769             0.791667               300       55500             4

      Flight Year
2768         2015
2769         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2770  Flight2771  41857  ORD-MIA              1.1         208
2771  Flight2772  42181  ORD-LGA              2.0         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2770             0.416667             330.0     54450.0             8
2771             0.812500             302.5     49912.5             6

      Flight Year
2770         2014
2771         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2772  Flight2773  42198  ORD-MIA              3.3          11
2773  Flight2774  41863  ORD-CLT              1.6          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2772             0.416667             330.0     61050.0             7
2773             0.791667             137.5     22687.5             8

      Flight Year
2772         2015
2773         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2774  Flight2775  42335  ORD-EWR              4.6         179
2775  Flight2776  42135  ORD-ATL              7.8         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2774             0.750000             337.5     55687.5            11
2775             0.520833             200.0     33000.0             5

      Flight Year
2774         2015
2775         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2776  Flight2777  42176  ORD-DEN              3.0           9
2777  Flight2778  41827  ORD-SEA              2.3          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2776             0.354167               330       61050             6
2777             0.833333               385       71225             7

      Flight Year
2776         2015
2777         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2778  Flight2779  41827  ORD-SFO              2.4          17
2779  Flight2780  42356  ORD-PHL              3.0           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2778             0.833333             412.5     76312.5             7
2779             0.875000             275.0     50875.0            12

      Flight Year
2778         2014
2779         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2780  Flight2781  42158  ORD-JFK              2.4         188
2781  Flight2782  42079  ORD-LAX              4.1         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2780             0.708333               275       45375             6
2781             0.750000               350       57750             3

      Flight Year
2780         2015
2781         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2782  Flight2783  42305  ORD-DFW              2.0         201
2783  Flight2784  41872  ORD-ATL             13.4         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2782             0.791667               200       33000            10
2783             0.791667               220       36300             8

      Flight Year
2782         2015
2783         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2784  Flight2785  41714  ORD-FLL              2.5         195
2785  Flight2786  42113  ORD-BOS              1.4         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2784             0.875000               300       49500             3
2785             0.583333               300       49500             4

      Flight Year
2784         2014
2785         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2786  Flight2787  41973  ORD-DEN              6.9         139
2787  Flight2788  41843  ORD-SEA              1.7         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2786             0.291667               450       83250            11
2787             0.708333               385       63525             7

      Flight Year
2786         2014
2787         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2788  Flight2789  41818  ORD-LGA              3.4         143
2789  Flight2790  42247  ORD-MCO              2.7          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2788             0.604167             302.5     55962.5             6
2789             0.291667             275.0     49775.0             8

      Flight Year
2788         2014
2789         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2790  Flight2791  42223  ORD-ATL             12.9         126
2791  Flight2792  42202  ORD-DEN              1.6         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2790             0.729167               220       40700             8
2791             0.854167               330       54450             7

      Flight Year
2790         2015
2791         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2792  Flight2793  42357  ORD-DTW              3.3         167
2793  Flight2794  41726  ORD-PHL              1.5          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2792             0.333333               115       18975            12
2793             0.354167               275       45375             3

      Flight Year
2792         2015
2793         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2794  Flight2795  42001  ORD-SEA              4.7         172
2795  Flight2796  41979  ORD-JFK              1.6         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2794             0.541667               490       80850            12
2795             0.791667               250       41250            12

      Flight Year
2794         2014
2795         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2796  Flight2797  42025  ORD-MSP              1.5         131
2797  Flight2798  41718  ORD-LAX              4.7         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2796             0.333333               115       21275             1
2797             0.312500               350       57750             3

      Flight Year
2796         2015
2797         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2798  Flight2799  41881  ORD-SEA              1.5         171
2799  Flight2800  42009  ORD-SFO              3.3           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2798             0.750000               385       63525             8
2799             0.333333               375       69375             1

      Flight Year
2798         2014
2799         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2800  Flight2801  41986  ORD-SFO              1.4           6
2801  Flight2802  42201  ORD-EWR              1.7         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2800             0.354167             375.0     69375.0            12
2801             0.416667             247.5     40837.5             7

      Flight Year
2800         2014
2801         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2802  Flight2803  42341  ORD-DEN              1.1         177
2803  Flight2804  42334  ORD-ATL             18.5         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2802             0.750000               300       49500            12
2803             0.666667               300       49500            11

      Flight Year
2802         2015
2803         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2804  Flight2805  41711  ORD-JFK              1.9          34
2805  Flight2806  42009  ORD-BOS              1.6         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2804             0.375000               250       46250             3
2805             0.708333               300       49500             1

      Flight Year
2804         2014
2805         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2806  Flight2807  41826  ORD-DTW              1.6         170
2807  Flight2808  42002  ORD-LAX              4.6          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2806             0.291667             126.5     20872.5             7
2807             0.833333             350.0     63350.0            12

      Flight Year
2806         2014
2807         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2808  Flight2809  42088  ORD-IAH              2.2          35
2809  Flight2810  42052  ORD-LAS              1.6         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2808             0.291667               200       37000             3
2809             0.750000               275       45375             2

      Flight Year
2808         2015
2809         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2810  Flight2811  42115  ORD-DFW              2.0         129
2811  Flight2812  42359  ORD-LAX              7.6          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2810             0.312500               200       37000             4
2811             0.291667               490       90650            12

      Flight Year
2810         2015
2811         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2812  Flight2813  42344  ORD-LAS              3.2          31
2813  Flight2814  42139  ORD-BOS              1.7          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2812             0.666667               275       50875            12
2813             0.750000               300       49500             5

      Flight Year
2812         2015
2813         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2814  Flight2815  41933  ORD-EWR              2.6         206
2815  Flight2816  42369  ORD-CLT              2.9         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2814             0.291667               225       37125            10
2815             0.791667               125       20625            12

      Flight Year
2814         2014
2815         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2816  Flight2817  42108  ORD-MIA              1.6         117
2817  Flight2818  42191  ORD-LAX              4.7          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2816             0.291667               300       55500             4
2817             0.750000               385       71225             7

      Flight Year
2816         2015
2817         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2818  Flight2819  42350  ORD-ATL              8.9         133
2819  Flight2820  42044  ORD-DFW              2.2         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2818             0.875000               200       37000            12
2819             0.833333               200       37000             2

      Flight Year
2818         2015
2819         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2820  Flight2821  42139  ORD-LAS              2.9          25
2821  Flight2822  42189  ORD-PHX              1.9         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2820             0.291667               275       50875             5
2821             0.770833               275       45375             7

      Flight Year
2820         2015
2821         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2822  Flight2823  42353  ORD-IAH              1.5           2
2823  Flight2824  41724  ORD-BOS              1.4         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2822             0.791667               200       37000            12
2823             0.708333               300       55500             3

      Flight Year
2822         2015
2823         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2824  Flight2825  42172  ORD-LAS              1.7         121
2825  Flight2826  42237  ORD-DFW              2.9          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2824             0.750000             302.5     55962.5             6
2825             0.354167             220.0     39820.0             8

      Flight Year
2824         2015
2825         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2826  Flight2827  42285  ORD-JFK              0.3          64
2827  Flight2828  41888  ORD-IAH              2.2         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2826             0.833333               250       45250            10
2827             0.354167               200       37000             9

      Flight Year
2826         2015
2827         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2828  Flight2829  41842  ORD-BOS              2.1           9
2829  Flight2830  41796  ORD-JFK              2.6         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2828             0.791667               330       61050             7
2829             0.770833               275       45375             6

      Flight Year
2828         2014
2829         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2830  Flight2831  41741  ORD-ATL              9.6           8
2831  Flight2832  41968  ORD-DTW              6.8         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2830             0.458333             200.0     37000.0             4
2831             0.333333             172.5     28462.5            11

      Flight Year
2830         2014
2831         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2832  Flight2833  41808  ORD-MCO              2.4          16
2833  Flight2834  41697  ORD-LAX              4.1          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2832             0.812500               275       50875             6
2833             0.541667               350       57750             2

      Flight Year
2832         2014
2833         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2834  Flight2835  41769  ORD-DFW              1.7          30
2835  Flight2836  42093  ORD-SFO              2.7         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2834             0.583333               200       37000             5
2835             0.291667               375       61875             3

      Flight Year
2834         2014
2835         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2836  Flight2837  42263  ORD-EWR              1.9          57
2837  Flight2838  41761  ORD-LAS              1.7         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2836             0.333333               225       37125             9
2837             0.833333               275       45375             5

      Flight Year
2836         2015
2837         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2838  Flight2839  42190  ORD-LAX              6.6          67
2839  Flight2840  41705  ORD-ATL             10.4         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2838             0.458333               385       69685             7
2839             0.812500               200       33000             3

      Flight Year
2838         2015
2839         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2840  Flight2841  42117  ORD-EWR              2.6         178
2841  Flight2842  42196  ORD-SFO              1.0         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2840             0.854167             225.0     37125.0             4
2841             0.791667             412.5     76312.5             7

      Flight Year
2840         2015
2841         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2842  Flight2843  42222  ORD-SEA              1.7         135
2843  Flight2844  41894  ORD-DFW              2.4          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2842             0.750000               385       71225             8
2843             0.833333               200       37000             9

      Flight Year
2842         2015
2843         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2844  Flight2845  41843  ORD-FLL              3.0         163
2845  Flight2846  42357  ORD-MIA              3.2         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2844             0.729167               330       54450             7
2845             0.666667               300       49500            12

      Flight Year
2844         2014
2845         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2846  Flight2847  41956  ORD-LAS              1.3          44
2847  Flight2848  42227  ORD-DFW              1.8         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2846             0.291667               275       45375            11
2847             0.479167               220       40700             8

      Flight Year
2846         2014
2847         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2848  Flight2849  41937  ORD-DEN              1.7          39
2849  Flight2850  42081  ORD-LAX              3.6         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2848             0.583333               300       49500            10
2849             0.750000               350       57750             3

      Flight Year
2848         2014
2849         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2850  Flight2851  42332  ORD-BOS              3.4          50
2851  Flight2852  42230  ORD-SFO              1.5         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2850             0.708333             450.0     74250.0            11
2851             0.791667             412.5     76312.5             8

      Flight Year
2850         2015
2851         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2852  Flight2853  41752  ORD-SFO              1.8          60
2853  Flight2854  42347  ORD-JFK              1.2          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2852             0.625000               375       61875             4
2853             0.791667               250       46250            12

      Flight Year
2852         2014
2853         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2854  Flight2855  41866  ORD-ATL              7.5         113
2855  Flight2856  41763  ORD-LAX              4.4          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2854             0.541667               220       40700             8
2855             0.479167               350       64750             5

      Flight Year
2854         2014
2855         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2856  Flight2857  41890  ORD-IAH              2.8          72
2857  Flight2858  41723  ORD-SLC              2.7          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2856             0.333333               200       36200             9
2857             0.333333               290       52490             3

      Flight Year
2856         2014
2857         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2858  Flight2859  42133  ORD-PHX              2.0          77
2859  Flight2860  41971  ORD-BOS              2.6          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2858             0.604167               250       45250             5
2859             0.833333               450       81450            11

      Flight Year
2858         2015
2859         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2860  Flight2861  41721  ORD-ATL              8.5          70
2861  Flight2862  42168  ORD-IAH              1.6         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2860             0.333333               200       36200             3
2861             0.541667               220       36300             6

      Flight Year
2860         2014
2861         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2862  Flight2863  42050  ORD-ATL              5.7           9
2863  Flight2864  42211  ORD-EWR              1.7          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2862             0.291667             200.0     37000.0             2
2863             0.562500             247.5     44797.5             7

      Flight Year
2862         2015
2863         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2864  Flight2865  41727  ORD-MIA              1.4         197
2865  Flight2866  42345  ORD-ATL              9.8         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2864             0.729167               300       49500             3
2865             0.729167               200       33000            12

      Flight Year
2864         2014
2865         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2866  Flight2867  42086  ORD-ATL              4.6         106
2867  Flight2868  41777  ORD-SEA              1.5         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2866             0.291667               200       37000             3
2867             0.666667               350       57750             5

      Flight Year
2866         2015
2867         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2868  Flight2869  41833  ORD-DFW              2.0         202
2869  Flight2870  41909  ORD-CLT              1.6         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2868             0.458333               220       36300             7
2869             0.833333               125       23125             9

      Flight Year
2868         2014
2869         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2870  Flight2871  41942  ORD-ATL              6.9         137
2871  Flight2872  41686  ORD-EWR              1.3         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2870             0.291667               200       37000            10
2871             0.458333               225       41625             2

      Flight Year
2870         2014
2871         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2872  Flight2873  41862  ORD-IAH              0.9          53
2873  Flight2874  41903  ORD-EWR              3.3         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2872                0.625               220       36300             8
2873                0.750               225       37125             9

      Flight Year
2872         2014
2873         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2874  Flight2875  41807  ORD-LAX              3.9         135
2875  Flight2876  41896  ORD-LAX              4.0         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2874             0.708333               385       71225             6
2875             0.333333               350       64750             9

      Flight Year
2874         2014
2875         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2876  Flight2877  41687  ORD-JFK              2.1           5
2877  Flight2878  41808  ORD-MIA              0.8         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2876             0.520833               250       46250             2
2877             0.833333               330       61050             6

      Flight Year
2876         2014
2877         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2878  Flight2879  41712  ORD-PHX              2.8          98
2879  Flight2880  41994  ORD-MCO              2.6           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2878             0.375000               250       46250             3
2879             0.291667               250       46250            12

      Flight Year
2878         2014
2879         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2880  Flight2881  42016  ORD-EWR              1.5         161
2881  Flight2882  42162  ORD-IAH              2.2         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2880             0.416667               225       37125             1
2881             0.833333               220       40700             6

      Flight Year
2880         2015
2881         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2882  Flight2883  42325  ORD-LAX              4.0         117
2883  Flight2884  41860  ORD-SFO              2.9         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2882             0.708333             350.0     64750.0            11
2883             0.750000             412.5     76312.5             8

      Flight Year
2882         2015
2883         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2884  Flight2885  41850  ORD-ATL             10.4         174
2885  Flight2886  41803  ORD-PHL              2.1         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2884             0.708333             220.0     36300.0             7
2885             0.875000             302.5     49912.5             6

      Flight Year
2884         2014
2885         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2886  Flight2887  42101  ORD-LGA              2.4         129
2887  Flight2888  42212  ORD-CLT              1.9          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2886             0.291667             275.0     50875.0             4
2887             0.666667             137.5     22687.5             7

      Flight Year
2886         2015
2887         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2888  Flight2889  41718  ORD-PHL              3.5          17
2889  Flight2890  42263  ORD-SFO              1.9           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2888             0.708333               275       50875             3
2889             0.708333               375       69375             9

      Flight Year
2888         2014
2889         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2890  Flight2891  41737  ORD-DEN              3.2         122
2891  Flight2892  42093  ORD-PHL              3.4          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2890                 0.75               300       55500             4
2891                 0.75               275       50875             3

      Flight Year
2890         2014
2891         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2892  Flight2893  41768  ORD-LAX              4.2          10
2893  Flight2894  41945  ORD-CLT              2.2         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2892             0.750000               350       64750             5
2893             0.333333               125       20625            11

      Flight Year
2892         2014
2893         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2894  Flight2895  41711  ORD-SFO              1.0         128
2895  Flight2896  41857  ORD-SFO              1.3         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2894             0.708333             375.0     69375.0             3
2895             0.812500             412.5     76312.5             8

      Flight Year
2894         2014
2895         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2896  Flight2897  42209  ORD-DTW              2.2          91
2897  Flight2898  42337  ORD-SFO              3.0          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2896             0.291667             126.5     23402.5             7
2897             0.812500             562.5     92812.5            11

      Flight Year
2896         2015
2897         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2898  Flight2899  41984  ORD-DTW              2.4         142
2899  Flight2900  42090  ORD-BWI              0.8          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2898                 0.75               115       21275            12
2899                 0.75               240       43440             3

      Flight Year
2898         2014
2899         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2900  Flight2901  42231  ORD-ATL              7.6          43
2901  Flight2902  42196  ORD-ATL              9.9          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2900                0.375               220       36300             8
2901                0.375               220       40700             7

      Flight Year
2900         2015
2901         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2902  Flight2903  42223  ORD-DEN              2.9         152
2903  Flight2904  41944  ORD-MIA              2.2         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2902             0.458333               330       54450             8
2903             0.729167               300       55500            11

      Flight Year
2902         2015
2903         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2904  Flight2905  42239  ORD-IAD              2.6         101
2905  Flight2906  42105  ORD-ATL              8.9          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2904             0.291667               330       61050             8
2905             0.500000               200       37000             4

      Flight Year
2904         2015
2905         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2906  Flight2907  42016  ORD-BWI              2.7         193
2907  Flight2908  41786  ORD-MIA              1.7          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2906             0.750000               240       39600             1
2907             0.833333               300       54300             5

      Flight Year
2906         2015
2907         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2908  Flight2909  42337  ORD-PHL              5.3          90
2909  Flight2910  41676  ORD-IAH              3.0         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2908               0.8750             412.5     74662.5            11
2909               0.3125             200.0     33000.0             2

      Flight Year
2908         2015
2909         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2910  Flight2911  41670  ORD-JFK              2.0           7
2911  Flight2912  41935  ORD-CLT              1.9          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2910             0.875000               250       46250             1
2911             0.333333               125       23125            10

      Flight Year
2910         2014
2911         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2912  Flight2913  41734  ORD-SFO              2.7          17
2913  Flight2914  42036  ORD-DEN              1.7         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2912             0.791667               375       69375             4
2913             0.583333               300       55500             2

      Flight Year
2912         2014
2913         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2914  Flight2915  42005  ORD-CLT              3.7         106
2915  Flight2916  42203  ORD-BOS              2.6           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2914             0.750000               125       23125             1
2915             0.708333               330       61050             7

      Flight Year
2914         2015
2915         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2916  Flight2917  42127  ORD-EWR              1.6         210
2917  Flight2918  41868  ORD-LAS              1.5          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2916             0.291667             225.0     37125.0             5
2917             0.562500             302.5     49912.5             8

      Flight Year
2916         2015
2917         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2918  Flight2919  42283  ORD-SEA              2.9         157
2919  Flight2920  41721  ORD-DEN              1.6          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2918             0.666667               350       57750            10
2919             0.291667               300       54300             3

      Flight Year
2918         2015
2919         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2920  Flight2921  42225  ORD-DEN              2.5          44
2921  Flight2922  41670  ORD-DTW              1.7          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2920             0.333333               330       54450             8
2921             0.666667               115       18975             1

      Flight Year
2920         2015
2921         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2922  Flight2923  42259  ORD-SEA              2.2         124
2923  Flight2924  41700  ORD-CLT              1.8         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2922               0.8125               350       64750             9
2923               0.6250               125       23125             3

      Flight Year
2922         2015
2923         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2924  Flight2925  41806  ORD-LGA              2.0         183
2925  Flight2926  41990  ORD-PHL              0.8          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2924             0.333333             302.5     49912.5             6
2925             0.375000             275.0     45375.0            12

      Flight Year
2924         2014
2925         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2926  Flight2927  42224  ORD-PHL              0.5          66
2927  Flight2928  42154  ORD-MCO              1.8          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2926             0.750000             302.5     54752.5             8
2927             0.333333             250.0     45250.0             5

      Flight Year
2926         2015
2927         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2928  Flight2929  41737  ORD-MCO              2.3           2
2929  Flight2930  42115  ORD-IAD              1.5         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2928             0.750000               250       46250             4
2929             0.520833               300       55500             4

      Flight Year
2928         2014
2929         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2930  Flight2931  41859  ORD-EWR              2.0          47
2931  Flight2932  41730  ORD-JFK              2.4          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2930             0.333333             247.5     40837.5             8
2931             0.333333             250.0     41250.0             4

      Flight Year
2930         2014
2931         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2932  Flight2933  41893  ORD-IAH              2.1         175
2933  Flight2934  41755  ORD-CLT              1.0          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2932             0.791667               200       33000             9
2933             0.375000               125       22625             4

      Flight Year
2932         2014
2933         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2934  Flight2935  42018  ORD-PHX              1.9          10
2935  Flight2936  42216  ORD-DFW              1.6         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2934             0.416667               250       46250             1
2935             0.291667               220       40700             7

      Flight Year
2934         2015
2935         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2936  Flight2937  41670  ORD-CLT              0.4         119
2937  Flight2938  41992  ORD-DTW              1.3         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2936               0.8750               125       23125             1
2937               0.8125               115       21275            12

      Flight Year
2936         2014
2937         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2938  Flight2939  42204  ORD-LAX              4.6          93
2939  Flight2940  42022  ORD-EWR              3.5         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2938             0.333333               385       71225             7
2939             0.520833               225       41625             1

      Flight Year
2938         2015
2939         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2940  Flight2941  41648  ORD-FLL              2.3          47
2941  Flight2942  42163  ORD-DFW              0.5          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2940             0.354167               300       49500             1
2941             0.812500               220       40700             6

      Flight Year
2940         2014
2941         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2942  Flight2943  42090  ORD-ATL              8.4          18
2943  Flight2944  41776  ORD-JFK              2.3          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2942             0.812500               200       37000             3
2943             0.333333               250       45250             5

      Flight Year
2942         2015
2943         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2944  Flight2945  41765  ORD-PHL              0.2         199
2945  Flight2946  42162  ORD-LAS              1.9           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2944             0.708333             275.0     45375.0             5
2945             0.708333             302.5     55962.5             6

      Flight Year
2944         2014
2945         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2946  Flight2947  42166  ORD-MIA              2.3         192
2947  Flight2948  41950  ORD-MCO              1.5         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2946             0.291667               330       54450             6
2947             0.750000               250       41250            11

      Flight Year
2946         2015
2947         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2948  Flight2949  42119  ORD-SFO              2.6          94
2949  Flight2950  42023  ORD-SEA              2.2         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2948             0.791667               375       69375             4
2949             0.770833               350       57750             1

      Flight Year
2948         2015
2949         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2950  Flight2951  41995  ORD-EWR              3.4         185
2951  Flight2952  41784  ORD-FLL              2.1         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2950             0.458333               315       51975            12
2951             0.645833               300       49500             5

      Flight Year
2950         2014
2951         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2952  Flight2953  42330  ORD-DFW              2.2         191
2953  Flight2954  42249  ORD-JFK              3.3         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2952             0.875000               200       33000            11
2953             0.833333               250       46250             9

      Flight Year
2952         2015
2953         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2954  Flight2955  41687  ORD-DFW              1.9          79
2955  Flight2956  42331  ORD-EWR              4.5         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2954             0.729167             200.0     36200.0             2
2955             0.583333             337.5     55687.5            11

      Flight Year
2954         2014
2955         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2956  Flight2957  42317  ORD-SFO              1.7         172
2957  Flight2958  42231  ORD-MIA              2.6          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2956             0.729167               375       61875            11
2957             0.333333               330       61050             8

      Flight Year
2956         2015
2957         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2958  Flight2959  41873  ORD-DFW                1           8
2959  Flight2960  41851  ORD-FLL                2         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2958             0.291667               220       40700             8
2959             0.291667               330       61050             7

      Flight Year
2958         2014
2959         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2960  Flight2961  42001  ORD-LAX              9.9         117
2961  Flight2962  41981  ORD-JFK              1.5         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2960                 0.50               490       90650            12
2961                 0.75               250       46250            12

      Flight Year
2960         2014
2961         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2962  Flight2963  42021  ORD-DTW              2.6          99
2963  Flight2964  42295  ORD-ATL              6.7         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2962             0.416667               115       21275             1
2963             0.375000               200       33000            10

      Flight Year
2962         2015
2963         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2964  Flight2965  41679  ORD-MSP              1.7         130
2965  Flight2966  42073  ORD-PHX              2.1         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2964             0.791667               115       21275             2
2965             0.729167               250       41250             3

      Flight Year
2964         2014
2965         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2966  Flight2967  41903  ORD-DTW              1.7          10
2967  Flight2968  42362  ORD-DEN              3.3         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2966             0.791667               115       21275             9
2967             0.750000               420       77700            12

      Flight Year
2966         2014
2967         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2968  Flight2969  42333  ORD-SEA              5.2         194
2969  Flight2970  42129  ORD-SLC              1.6         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2968             0.291667               525       86625            11
2969             0.833333               290       47850             5

      Flight Year
2968         2015
2969         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2970  Flight2971  41728  ORD-ATL              9.6         163
2971  Flight2972  41836  ORD-EWR              2.6         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2970             0.291667             200.0     33000.0             3
2971             0.625000             247.5     40837.5             7

      Flight Year
2970         2014
2971         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2972  Flight2973  41970  ORD-JFK              3.3         123
2973  Flight2974  41666  ORD-PHX              1.9         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2972             0.770833               375       69375            11
2973             0.687500               250       41250             1

      Flight Year
2972         2014
2973         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2974  Flight2975  42104  ORD-LAX              3.7         118
2975  Flight2976  41679  ORD-ATL              8.9         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2974             0.708333               350       64750             4
2975             0.312500               200       37000             2

      Flight Year
2974         2015
2975         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2976  Flight2977  41877  ORD-LAX              5.8          97
2977  Flight2978  41966  ORD-JFK              2.0          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2976                 0.50               385       71225             8
2977                 0.75               250       46250            11

      Flight Year
2976         2014
2977         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2978  Flight2979  41845  ORD-LAX              3.6         142
2979  Flight2980  41697  ORD-PHL              1.7          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2978             0.750000               385       71225             7
2979             0.583333               275       50875             2

      Flight Year
2978         2014
2979         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2980  Flight2981  41941  ORD-PHX              1.3         128
2981  Flight2982  41862  ORD-SFO              1.1         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2980             0.729167             250.0     46250.0            10
2981             0.750000             412.5     76312.5             8

      Flight Year
2980         2014
2981         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2982  Flight2983  41894  ORD-LAS              1.4          82
2983  Flight2984  41731  ORD-CLT              1.5         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2982             0.770833               275       49775             9
2983             0.333333               125       23125             4

      Flight Year
2982         2014
2983         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2984  Flight2985  41844  ORD-LAX              4.6         178
2985  Flight2986  42065  ORD-BWI              2.3         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2984             0.750000               385       63525             7
2985             0.791667               240       44400             3

      Flight Year
2984         2014
2985         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2986  Flight2987  41733  ORD-CLT              1.0          45
2987  Flight2988  42169  ORD-FLL              2.4          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2986                0.500               125       20625             4
2987                0.375               330       59730             6

      Flight Year
2986         2014
2987         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2988  Flight2989  41946  ORD-ATL             10.4         127
2989  Flight2990  41844  ORD-SEA              2.8         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2988             0.333333               200       37000            11
2989             0.833333               385       63525             7

      Flight Year
2988         2014
2989         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2990  Flight2991  42361  ORD-SEA              4.7         200
2991  Flight2992  42365  ORD-CLT              4.5         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2990             0.833333               490       80850            12
2991             0.708333               175       28875            12

      Flight Year
2990         2015
2991         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2992  Flight2993  41773  ORD-LAS              1.6         190
2993  Flight2994  41698  ORD-LGA              1.6          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2992             0.291667               275       45375             5
2993             0.291667               275       45375             2

      Flight Year
2992         2014
2993         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2994  Flight2995  42336  ORD-CLT              7.1         154
2995  Flight2996  41854  ORD-SFO              2.1         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2994             0.708333             187.5     30937.5            11
2995             0.791667             412.5     76312.5             8

      Flight Year
2994         2015
2995         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2996  Flight2997  42273  ORD-FLL              1.7          95
2997  Flight2998  41868  ORD-JFK              1.7          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2996             0.833333               300       55500             9
2997             0.625000               275       45375             8

      Flight Year
2996         2015
2997         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
2998  Flight2999  42318  ORD-ATL             10.1          82
2999  Flight3000  42334  ORD-SEA              6.1         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
2998               0.7500               200       36200            11
2999               0.3125               525       86625            11

      Flight Year
2998         2015
2999         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3000  Flight3001  42262  ORD-IAD              2.5         112
3001  Flight3002  42153  ORD-PHX              1.8          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3000             0.791667               300       55500             9
3001             0.333333               250       46250             5

      Flight Year
3000         2015
3001         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3002  Flight3003  42236  ORD-LAX              5.1         186
3003  Flight3004  42117  ORD-DTW              2.9         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3002               0.8125               385       63525             8
3003               0.7500               115       18975             4

      Flight Year
3002         2015
3003         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3004  Flight3005  41657  ORD-JFK              1.5         163
3005  Flight3006  42292  ORD-IAD              1.9          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3004             0.750000               250       41250             1
3005             0.291667               300       54300            10

      Flight Year
3004         2014
3005         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3006  Flight3007  41980  ORD-SEA              1.9         172
3007  Flight3008  42249  ORD-MSP              1.3         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3006             0.833333               350       57750            12
3007             0.895833               115       21275             9

      Flight Year
3006         2014
3007         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3008  Flight3009  41658  ORD-LGA              1.3         104
3009  Flight3010  42184  ORD-DEN              2.0         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3008             0.750000               275       50875             1
3009             0.333333               330       54450             6

      Flight Year
3008         2014
3009         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3010  Flight3011  42268  ORD-EWR              1.6         116
3011  Flight3012  42029  ORD-BWI              1.5         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3010             0.895833               225       41625             9
3011             0.416667               240       44400             1

      Flight Year
3010         2015
3011         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3012  Flight3013  41989  ORD-BWI              3.4          18
3013  Flight3014  42121  ORD-BOS              2.2          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3012             0.791667               240       44400            12
3013             0.895833               300       49500             4

      Flight Year
3012         2014
3013         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3014  Flight3015  42341  ORD-SFO              2.3           6
3015  Flight3016  42354  ORD-SFO              2.8         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3014             0.437500               375       69375            12
3015             0.333333               375       61875            12

      Flight Year
3014         2015
3015         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3016  Flight3017  41997  ORD-DFW              2.1          28
3017  Flight3018  42348  ORD-JFK              1.7         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3016             0.854167               280       51800            12
3017             0.395833               250       41250            12

      Flight Year
3016         2014
3017         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3018  Flight3019  41692  ORD-PHX              2.1           4
3019  Flight3020  42329  ORD-IAH              2.4         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3018             0.729167               250       46250             2
3019             0.812500               200       33000            11

      Flight Year
3018         2014
3019         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3020  Flight3021  42337  ORD-ATL             18.9           2
3021  Flight3022  41879  ORD-SEA              1.5         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3020             0.354167               300       55500            11
3021             0.312500               385       63525             8

      Flight Year
3020         2015
3021         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3022  Flight3023  41699  ORD-PHX              0.9          40
3023  Flight3024  42238  ORD-LAS              1.8         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3022             0.333333             250.0     41250.0             3
3023             0.666667             302.5     49912.5             8

      Flight Year
3022         2014
3023         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3024  Flight3025  42024  ORD-MSP              1.5          53
3025  Flight3026  41912  ORD-ATL              9.8          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3024             0.708333               115       18975             1
3025             0.791667               200       37000             9

      Flight Year
3024         2015
3025         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3026  Flight3027  41938  ORD-MCO              2.0          38
3027  Flight3028  41874  ORD-MIA              1.4          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3026             0.750000               250       41250            10
3027             0.708333               330       54450             8

      Flight Year
3026         2014
3027         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3028  Flight3029  41702  ORD-MCO              2.2          21
3029  Flight3030  42022  ORD-JFK              1.5          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3028             0.708333               250       46250             3
3029             0.833333               250       41250             1

      Flight Year
3028         2014
3029         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3030  Flight3031  41883  ORD-ATL              9.1         147
3031  Flight3032  41761  ORD-MSP              1.8          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3030             0.354167               200       37000             9
3031             0.458333               115       18975             5

      Flight Year
3030         2014
3031         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3032  Flight3033  41990  ORD-DFW              1.8         146
3033  Flight3034  41850  ORD-MIA              0.9         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3032             0.333333               200       37000            12
3033             0.833333               330       54450             7

      Flight Year
3032         2014
3033         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3034  Flight3035  41874  ORD-DTW              2.6         177
3035  Flight3036  42246  ORD-JFK              2.8         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3034             0.791667             126.5     20872.5             8
3035             0.729167             275.0     50875.0             8

      Flight Year
3034         2014
3035         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3036  Flight3037  42290  ORD-DEN              1.0          98
3037  Flight3038  41807  ORD-CLT              1.7         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3036             0.625000             300.0     55500.0            10
3037             0.729167             137.5     25437.5             6

      Flight Year
3036         2015
3037         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3038  Flight3039  41641  ORD-PHX              2.4          68
3039  Flight3040  41986  ORD-PHL              3.5         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3038             0.791667               250       45250             1
3039             0.791667               275       45375            12

      Flight Year
3038         2014
3039         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3040  Flight3041  42108  ORD-SEA              1.8          27
3041  Flight3042  41990  ORD-EWR              2.3          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3040             0.833333               350       64750             4
3041             0.708333               225       37125            12

      Flight Year
3040         2015
3041         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3042  Flight3043  41758  ORD-LAS              0.6         191
3043  Flight3044  41989  ORD-FLL              2.2         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3042             0.395833               275       45375             4
3043             0.708333               300       49500            12

      Flight Year
3042         2014
3043         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3044  Flight3045  41648  ORD-PHL              3.1         187
3045  Flight3046  41985  ORD-LAS              2.0         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3044             0.791667               275       45375             1
3045             0.666667               275       50875            12

      Flight Year
3044         2014
3045         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3046  Flight3047  41806  ORD-SEA              0.6         172
3047  Flight3048  41995  ORD-LAS              4.4         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3046             0.791667               385       63525             6
3047             0.291667               385       63525            12

      Flight Year
3046         2014
3047         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3048  Flight3049  41688  ORD-ATL             10.5         126
3049  Flight3050  41966  ORD-MCO              3.0          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3048             0.708333               200       37000             2
3049             0.291667               250       41250            11

      Flight Year
3048         2014
3049         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3050  Flight3051  41841  ORD-MIA              2.7          41
3051  Flight3052  41876  ORD-DEN              2.1          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3050             0.750000               330       54450             7
3051             0.416667               330       61050             8

      Flight Year
3050         2014
3051         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3052  Flight3053  42087  ORD-MCO              1.5          96
3053  Flight3054  42054  ORD-MCO              1.2         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3052             0.791667               250       46250             3
3053             0.791667               250       46250             2

      Flight Year
3052         2015
3053         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3054  Flight3055  42083  ORD-LAX              5.6         185
3055  Flight3056  41692  ORD-PHX              1.9         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3054               0.6250               350       57750             3
3055               0.6875               250       41250             2

      Flight Year
3054         2015
3055         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3056  Flight3057  41928  ORD-MSP              1.6         160
3057  Flight3058  41933  ORD-PHL              1.8         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3056             0.291667               115       18975            10
3057             0.625000               275       50875            10

      Flight Year
3056         2014
3057         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3058  Flight3059  41681  ORD-LAX              4.8          37
3059  Flight3060  42037  ORD-SFO              1.5          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3058             0.791667               350       57750             2
3059             0.312500               375       67875             2

      Flight Year
3058         2014
3059         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3060  Flight3061  41883  ORD-SEA              1.9         162
3061  Flight3062  41881  ORD-MIA              2.8         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3060                0.625               350       57750             9
3061                0.625               330       61050             8

      Flight Year
3060         2014
3061         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3062  Flight3063  42122  ORD-LAS              1.6         109
3063  Flight3064  42089  ORD-EWR              2.8          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3062             0.770833               275       50875             4
3063             0.458333               225       41625             3

      Flight Year
3062         2015
3063         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3064  Flight3065  41819  ORD-JFK              1.8          86
3065  Flight3066  41686  ORD-IAH              0.4          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3064             0.770833               275       49775             6
3065             0.458333               200       33000             2

      Flight Year
3064         2014
3065         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3066  Flight3067  42101  ORD-BWI              3.4         188
3067  Flight3068  41822  ORD-DFW              2.5         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3066             0.729167               240       39600             4
3067             0.291667               220       36300             7

      Flight Year
3066         2015
3067         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3068  Flight3069  42165  ORD-IAH              1.8         139
3069  Flight3070  42283  ORD-BOS              2.1         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3068             0.854167               220       40700             6
3069             0.708333               300       49500            10

      Flight Year
3068         2015
3069         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3070  Flight3071  42181  ORD-DEN              2.7         115
3071  Flight3072  42136  ORD-LAX              3.1          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3070             0.479167               330       61050             6
3071             0.875000               350       64750             5

      Flight Year
3070         2015
3071         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3072  Flight3073  42140  ORD-SEA              2.7         169
3073  Flight3074  41998  ORD-CLT              3.3         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3072             0.291667               350       57750             5
3073             0.854167               175       28875            12

      Flight Year
3072         2015
3073         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3074  Flight3075  41998  ORD-CLT              5.7         183
3075  Flight3076  41654  ORD-DFW              1.6          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3074             0.875000               175       28875            12
3075             0.541667               200       33000             1

      Flight Year
3074         2014
3075         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3076  Flight3077  41833  ORD-DFW                2         180
3077  Flight3078  42186  ORD-PHX                1          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3076             0.812500               220       36300             7
3077             0.395833               275       45375             7

      Flight Year
3076         2014
3077         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3078  Flight3079  42176  ORD-SFO              3.1           3
3079  Flight3080  41891  ORD-LAX              4.2         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3078             0.291667             412.5     76312.5             6
3079             0.708333             350.0     64750.0             9

      Flight Year
3078         2015
3079         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3080  Flight3081  41813  ORD-SEA              3.2          83
3081  Flight3082  41797  ORD-MCO              1.7          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3080             0.437500               385       69685             6
3081             0.729167               275       45375             6

      Flight Year
3080         2014
3081         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3082  Flight3083  42006  ORD-SEA              2.7         129
3083  Flight3084  42161  ORD-PHL              1.7          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3082               0.3125             350.0     64750.0             1
3083               0.8750             302.5     54752.5             6

      Flight Year
3082         2015
3083         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3084  Flight3085  41689  ORD-PHL              1.1          23
3085  Flight3086  41713  ORD-EWR              1.5         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3084                0.750               275       50875             2
3085                0.875               225       41625             3

      Flight Year
3084         2014
3085         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3086  Flight3087  42098  ORD-ATL             10.1         186
3087  Flight3088  41809  ORD-BOS              2.1         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3086             0.729167               200       33000             4
3087             0.729167               330       54450             6

      Flight Year
3086         2015
3087         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3088  Flight3089  41704  ORD-MCO              1.2         199
3089  Flight3090  42157  ORD-MCO              3.1          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3088             0.604167               250       41250             3
3089             0.333333               275       45375             6

      Flight Year
3088         2014
3089         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3090  Flight3091  41973  ORD-DEN              4.5          59
3091  Flight3092  42029  ORD-LAS              2.3         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3090             0.541667               450       74250            11
3091             0.500000               275       45375             1

      Flight Year
3090         2014
3091         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3092  Flight3093  42172  ORD-DTW              1.6         120
3093  Flight3094  41972  ORD-FLL              6.6         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3092             0.770833             126.5     23402.5             6
3093             0.895833             450.0     83250.0            11

      Flight Year
3092         2015
3093         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3094  Flight3095  42216  ORD-PHX              1.9         148
3095  Flight3096  42021  ORD-EWR              0.4         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3094             0.750000               275       50875             7
3095             0.833333               225       37125             1

      Flight Year
3094         2015
3095         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3096  Flight3097  41773  ORD-SFO              2.3          37
3097  Flight3098  42168  ORD-MSP              2.6          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3096             0.354167             375.0     61875.0             5
3097             0.604167             126.5     22896.5             6

      Flight Year
3096         2014
3097         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3098  Flight3099  42160  ORD-ATL              8.5         136
3099  Flight3100  42227  ORD-DFW              3.5          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3098             0.291667               220       40700             6
3099             0.854167               220       40700             8

      Flight Year
3098         2015
3099         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3100  Flight3101  42289  ORD-ATL              9.4         128
3101  Flight3102  41746  ORD-MCO              1.1         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3100             0.854167               200       37000            10
3101             0.791667               250       46250             4

      Flight Year
3100         2015
3101         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3102  Flight3103  42253  ORD-BOS              3.3         135
3103  Flight3104  41934  ORD-ATL             10.1         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3102             0.791667               300       55500             9
3103             0.750000               200       33000            10

      Flight Year
3102         2015
3103         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3104  Flight3105  42175  ORD-ATL              7.7          68
3105  Flight3106  42139  ORD-DEN              1.8          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3104             0.333333               220       39820             6
3105             0.750000               300       55500             5

      Flight Year
3104         2015
3105         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3106  Flight3107  41837  ORD-PHX              1.3         195
3107  Flight3108  42204  ORD-DEN              2.1         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3106               0.8125               275       45375             7
3107               0.8750               330       61050             7

      Flight Year
3106         2014
3107         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3108  Flight3109  42210  ORD-IAH              2.7          16
3109  Flight3110  42060  ORD-ATL             11.7         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3108             0.333333               220       40700             7
3109             0.770833               200       33000             2

      Flight Year
3108         2015
3109         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3110  Flight3111  41797  ORD-DFW              3.0         155
3111  Flight3112  42093  ORD-SEA              2.1         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3110             0.708333               220       36300             6
3111             0.354167               350       64750             3

      Flight Year
3110         2014
3111         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3112  Flight3113  41844  ORD-IAH              1.5          53
3113  Flight3114  41878  ORD-IAH              3.0         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3112             0.479167               220       36300             7
3113             0.729167               220       40700             8

      Flight Year
3112         2014
3113         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3114  Flight3115  41979  ORD-LGA              1.0         196
3115  Flight3116  42301  ORD-EWR              2.5         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3114             0.291667               275       45375            12
3115             0.791667               225       37125            10

      Flight Year
3114         2014
3115         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3116  Flight3117  42200  ORD-SFO              2.7         188
3117  Flight3118  42337  ORD-DEN              3.8         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3116             0.750000             412.5     68062.5             7
3117             0.729167             450.0     74250.0            11

      Flight Year
3116         2015
3117         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3118  Flight3119  42227  ORD-MIA              2.5         175
3119  Flight3120  41730  ORD-LAS              1.7         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3118             0.875000               330       54450             8
3119             0.791667               275       50875             4

      Flight Year
3118         2015
3119         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3120  Flight3121  42231  ORD-MIA              3.4         111
3121  Flight3122  41867  ORD-BOS              1.6         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3120             0.791667               330       61050             8
3121             0.770833               330       61050             8

      Flight Year
3120         2015
3121         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3122  Flight3123  41970  ORD-PHL              3.6         162
3123  Flight3124  42208  ORD-SFO              2.8         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3122             0.291667             412.5     68062.5            11
3123             0.375000             412.5     76312.5             7

      Flight Year
3122         2014
3123         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3124  Flight3125  41938  ORD-SEA              2.7          78
3125  Flight3126  41824  ORD-ATL              7.2          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3124             0.333333               350       63350            10
3125             0.791667               220       36300             7

      Flight Year
3124         2014
3125         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3126  Flight3127  41999  ORD-EWR              4.8          85
3127  Flight3128  42123  ORD-DEN              2.4          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3126             0.750000               315       57015            12
3127             0.895833               300       55500             4

      Flight Year
3126         2014
3127         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3128  Flight3129  42144  ORD-DEN              1.3         157
3129  Flight3130  42176  ORD-DTW              2.7          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3128             0.416667             300.0     49500.0             5
3129             0.750000             126.5     22896.5             6

      Flight Year
3128         2015
3129         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3130  Flight3131  41872  ORD-LAX              4.2          60
3131  Flight3132  42307  ORD-DEN              2.5         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3130             0.291667               385       63525             8
3131             0.750000               300       55500            10

      Flight Year
3130         2014
3131         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3132  Flight3133  41838  ORD-DFW              2.5          72
3133  Flight3134  42365  ORD-MSP              2.6          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3132             0.791667               220       39820             7
3133             0.791667               161       26565            12

      Flight Year
3132         2014
3133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3134  Flight3135  41970  ORD-DTW              6.9          54
3135  Flight3136  42163  ORD-MSP              2.3          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3134             0.770833             172.5     28462.5            11
3135             0.312500             126.5     23402.5             6

      Flight Year
3134         2014
3135         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3136  Flight3137  42339  ORD-DFW              2.5         129
3137  Flight3138  42356  ORD-MCO              1.1          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3136             0.875000               200       37000            12
3137             0.791667               250       41250            12

      Flight Year
3136         2015
3137         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3138  Flight3139  41922  ORD-PHL              1.9         145
3139  Flight3140  42328  ORD-DFW              1.8          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3138               0.8125               275       50875            10
3139               0.7500               200       36200            11

      Flight Year
3138         2014
3139         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3140  Flight3141  42031  ORD-DFW              2.0         197
3141  Flight3142  41796  ORD-LAS              1.6          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3140             0.666667             200.0     33000.0             1
3141             0.291667             302.5     54752.5             6

      Flight Year
3140         2015
3141         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3142  Flight3143  41969  ORD-DEN              5.9         112
3143  Flight3144  42332  ORD-CLT              4.0         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3142             0.833333             450.0     83250.0            11
3143             0.291667             187.5     34687.5            11

      Flight Year
3142         2014
3143         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3144  Flight3145  41968  ORD-CLT              5.7         172
3145  Flight3146  41647  ORD-BWI              1.2         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3144             0.750000             187.5     30937.5            11
3145             0.354167             240.0     44400.0             1

      Flight Year
3144         2014
3145         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3146  Flight3147  41957  ORD-MSP              2.5          17
3147  Flight3148  42133  ORD-LAX              4.3          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3146             0.750000               115       21275            11
3147             0.291667               350       57750             5

      Flight Year
3146         2014
3147         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3148  Flight3149  42311  ORD-SFO              2.3           6
3149  Flight3150  42025  ORD-DFW              2.6         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3148             0.750000               375       69375            11
3149             0.791667               200       33000             1

      Flight Year
3148         2015
3149         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3150  Flight3151  42280  ORD-CLT              2.2           5
3151  Flight3152  42360  ORD-LAX              7.8          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3150             0.416667               125       23125            10
3151             0.500000               490       80850            12

      Flight Year
3150         2015
3151         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3152  Flight3153  41747  ORD-PHX              3.1          43
3153  Flight3154  42147  ORD-BOS              2.3         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3152             0.729167               250       41250             4
3153             0.750000               300       55500             5

      Flight Year
3152         2014
3153         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3154  Flight3155  41789  ORD-SFO              2.5          59
3155  Flight3156  42361  ORD-LAX              8.7          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3154             0.750000               375       61875             5
3155             0.791667               490       90650            12

      Flight Year
3154         2014
3155         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3156  Flight3157  41889  ORD-DFW              1.5          19
3157  Flight3158  41996  ORD-MSP              6.2         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3156             0.791667               200       37000             9
3157             0.375000               161       26565            12

      Flight Year
3156         2014
3157         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3158  Flight3159  41931  ORD-LAS              1.8         195
3159  Flight3160  41648  ORD-LAX              3.6          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3158             0.750000               275       45375            10
3159             0.708333               350       63350             1

      Flight Year
3158         2014
3159         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3160  Flight3161  42335  ORD-SEA              5.4         173
3161  Flight3162  42251  ORD-PHX              3.4         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3160             0.770833               525       86625            11
3161             0.541667               250       41250             9

      Flight Year
3160         2015
3161         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3162  Flight3163  42202  ORD-JFK              1.9          66
3163  Flight3164  42296  ORD-MCO              1.5         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3162             0.666667               275       49775             7
3163             0.708333               250       46250            10

      Flight Year
3162         2015
3163         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3164  Flight3165  41885  ORD-LGA              2.7          32
3165  Flight3166  41787  ORD-PHL              3.0         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3164                 0.75               275       50875             9
3165                 0.75               275       45375             5

      Flight Year
3164         2014
3165         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3166  Flight3167  42079  ORD-CLT              0.8          81
3167  Flight3168  42299  ORD-LAX              3.4          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3166             0.791667               125       22625             3
3167             0.750000               350       64750            10

      Flight Year
3166         2015
3167         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3168  Flight3169  41918  ORD-CLT              1.9          47
3169  Flight3170  41727  ORD-SFO              1.4          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3168             0.770833               125       20625            10
3169             0.729167               375       69375             3

      Flight Year
3168         2014
3169         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3170  Flight3171  42130  ORD-ATL              7.0         146
3171  Flight3172  42365  ORD-IAH              3.4         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3170             0.625000               200       37000             5
3171             0.354167               280       51800            12

      Flight Year
3170         2015
3171         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3172  Flight3173  41836  ORD-SEA              3.1          24
3173  Flight3174  41756  ORD-EWR              2.3         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3172             0.791667               385       71225             7
3173             0.750000               225       37125             4

      Flight Year
3172         2014
3173         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3174  Flight3175  42240  ORD-BOS              1.9          49
3175  Flight3176  42032  ORD-DFW              2.6          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3174             0.833333               330       54450             8
3175             0.770833               200       37000             1

      Flight Year
3174         2015
3175         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3176  Flight3177  42197  ORD-LAS              1.7          21
3177  Flight3178  41827  ORD-DFW              1.1          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3176             0.770833             302.5     55962.5             7
3177             0.770833             220.0     40700.0             7

      Flight Year
3176         2015
3177         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3178  Flight3179  42216  ORD-ATL              8.3         210
3179  Flight3180  41950  ORD-LGA              1.5          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3178                0.750               220       36300             7
3179                0.625               275       45375            11

      Flight Year
3178         2015
3179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3180  Flight3181  41869  ORD-LAX              4.3         147
3181  Flight3182  42345  ORD-ATL              9.8         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3180             0.645833               385       71225             8
3181             0.791667               200       37000            12

      Flight Year
3180         2014
3181         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3182  Flight3183  41790  ORD-CLT              0.2          62
3183  Flight3184  42002  ORD-SFO              3.5          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3182             0.708333               125       20625             5
3183             0.291667               375       69375            12

      Flight Year
3182         2014
3183         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3184  Flight3185  42179  ORD-DEN              2.8          51
3185  Flight3186  42057  ORD-LAX              4.6          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3184             0.708333               330       54450             6
3185             0.895833               350       63350             2

      Flight Year
3184         2015
3185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3186  Flight3187  42221  ORD-JFK              3.1         162
3187  Flight3188  41782  ORD-LGA              2.1          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3186             0.791667               275       45375             8
3187             0.708333               275       49775             5

      Flight Year
3186         2015
3187         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3188  Flight3189  42298  ORD-BOS              1.8         167
3189  Flight3190  41984  ORD-EWR              3.4         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3188             0.291667               300       49500            10
3189             0.333333               225       41625            12

      Flight Year
3188         2015
3189         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3190  Flight3191  41847  ORD-JFK              0.6         103
3191  Flight3192  41813  ORD-DEN              1.9         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3190                0.875               275       50875             7
3191                0.375               330       54450             6

      Flight Year
3190         2014
3191         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3192  Flight3193  42362  ORD-FLL              4.6          24
3193  Flight3194  42172  ORD-ATL             12.3          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3192             0.770833               420       77700            12
3193             0.333333               220       39820             6

      Flight Year
3192         2015
3193         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3194  Flight3195  42157  ORD-DEN              1.1         198
3195  Flight3196  42334  ORD-LAX             10.4         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3194             0.750000               330       54450             6
3195             0.479167               525       97125            11

      Flight Year
3194         2015
3195         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3196  Flight3197  42322  ORD-DEN              3.0          85
3197  Flight3198  41761  ORD-LGA              2.2         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3196             0.791667               300       54300            11
3197             0.291667               275       45375             5

      Flight Year
3196         2015
3197         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3198  Flight3199  42044  ORD-MIA              2.0          57
3199  Flight3200  41827  ORD-JFK              2.5          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3198             0.291667               300       49500             2
3199             0.750000               275       50875             7

      Flight Year
3198         2015
3199         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3200  Flight3201  41729  ORD-LGA              1.9         181
3201  Flight3202  41958  ORD-LAX              4.6         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3200             0.416667               275       45375             3
3201             0.791667               350       57750            11

      Flight Year
3200         2014
3201         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3202  Flight3203  41959  ORD-DTW              2.4         113
3203  Flight3204  42113  ORD-SEA              1.8         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3202             0.791667               115       21275            11
3203             0.291667               350       57750             4

      Flight Year
3202         2014
3203         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3204  Flight3205  41652  ORD-DFW              2.6          67
3205  Flight3206  41808  ORD-SFO              2.8          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3204             0.520833             200.0     36200.0             1
3205             0.750000             412.5     74662.5             6

      Flight Year
3204         2014
3205         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3206  Flight3207  41931  ORD-LAX              4.0         188
3207  Flight3208  42309  ORD-DEN              1.6          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3206               0.3750               350       57750            10
3207               0.8125               300       49500            11

      Flight Year
3206         2014
3207         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3208  Flight3209  42228  ORD-MIA              3.3         160
3209  Flight3210  41745  ORD-BOS              2.6         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3208             0.645833               330       54450             8
3209             0.375000               300       55500             4

      Flight Year
3208         2015
3209         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3210  Flight3211  41645  ORD-DTW              1.7           1
3211  Flight3212  41693  ORD-SFO              2.1           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3210             0.750000               115       21275             1
3211             0.395833               375       69375             2

      Flight Year
3210         2014
3211         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3212  Flight3213  41884  ORD-SFO              1.6          53
3213  Flight3214  42141  ORD-CLT              2.5          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3212             0.750000               375       61875             9
3213             0.708333               125       23125             5

      Flight Year
3212         2014
3213         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3214  Flight3215  42027  ORD-MCO              1.3         161
3215  Flight3216  41838  ORD-MSP              2.1          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3214             0.729167             250.0     41250.0             1
3215             0.750000             126.5     20872.5             7

      Flight Year
3214         2015
3215         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3216  Flight3217  42096  ORD-SEA              2.7           2
3217  Flight3218  41804  ORD-LGA              2.1         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3216             0.625000             350.0     64750.0             4
3217             0.333333             302.5     49912.5             6

      Flight Year
3216         2015
3217         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3218  Flight3219  42335  ORD-DFW              5.1          36
3219  Flight3220  42216  ORD-SFO              2.3         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3218             0.791667             300.0     49500.0            11
3219             0.750000             412.5     76312.5             7

      Flight Year
3218         2015
3219         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3220  Flight3221  41833  ORD-DEN              1.6         186
3221  Flight3222  42273  ORD-ATL              8.4         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3220             0.750000               330       54450             7
3221             0.854167               200       33000             9

      Flight Year
3220         2014
3221         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3222  Flight3223  41771  ORD-EWR              1.4         108
3223  Flight3224  42188  ORD-DFW              1.3          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3222             0.708333               225       41625             5
3223             0.416667               220       39820             7

      Flight Year
3222         2014
3223         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3224  Flight3225  41992  ORD-LAS              1.7         172
3225  Flight3226  41793  ORD-MSP              1.4         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3224             0.312500             275.0     45375.0            12
3225             0.791667             126.5     23402.5             6

      Flight Year
3224         2014
3225         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3226  Flight3227  41890  ORD-JFK              1.3         117
3227  Flight3228  42255  ORD-PHL              2.1         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3226             0.750000               250       46250             9
3227             0.708333               275       50875             9

      Flight Year
3226         2014
3227         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3228  Flight3229  41722  ORD-MSP              2.8         185
3229  Flight3230  41706  ORD-DFW              1.9         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3228             0.770833               115       18975             3
3229             0.333333               200       33000             3

      Flight Year
3228         2014
3229         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3230  Flight3231  42054  ORD-PHL              2.6          37
3231  Flight3232  42094  ORD-LAS              2.1           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3230             0.520833               275       45375             2
3231             0.708333               275       50875             3

      Flight Year
3230         2015
3231         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3232  Flight3233  42358  ORD-DEN              0.9         138
3233  Flight3234  42089  ORD-LGA              1.8          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3232             0.791667               300       55500            12
3233             0.791667               275       49775             3

      Flight Year
3232         2015
3233         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3234  Flight3235  42022  ORD-LAS              2.2         193
3235  Flight3236  42278  ORD-MIA              1.8         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3234             0.416667               275       45375             1
3235             0.333333               300       49500            10

      Flight Year
3234         2015
3235         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3236  Flight3237  42059  ORD-MSP              1.7         139
3237  Flight3238  42127  ORD-PHX              2.0         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3236             0.291667               115       21275             2
3237             0.875000               250       41250             5

      Flight Year
3236         2015
3237         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3238  Flight3239  41730  ORD-MSP              1.2          47
3239  Flight3240  41875  ORD-LAX              5.0          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3238             0.333333               115       18975             4
3239             0.833333               385       69685             8

      Flight Year
3238         2014
3239         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3240  Flight3241  42171  ORD-LAS              1.8          73
3241  Flight3242  41655  ORD-EWR              1.8         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3240             0.833333             302.5     54752.5             6
3241             0.770833             225.0     37125.0             1

      Flight Year
3240         2015
3241         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3242  Flight3243  42355  ORD-LAS              1.3          50
3243  Flight3244  41712  ORD-LAS              2.0          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3242               0.6875               275       45375            12
3243               0.7500               275       45375             3

      Flight Year
3242         2015
3243         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3244  Flight3245  42231  ORD-PHX              1.6         179
3245  Flight3246  42313  ORD-SFO              1.7         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3244                0.875               275       45375             8
3245                0.625               375       69375            11

      Flight Year
3244         2015
3245         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3246  Flight3247  42251  ORD-ATL              9.2         110
3247  Flight3248  41871  ORD-SEA              2.4           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3246               0.5000               200       37000             9
3247               0.6875               385       71225             8

      Flight Year
3246         2015
3247         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3248  Flight3249  42252  ORD-LAX              4.8         187
3249  Flight3250  41642  ORD-SEA              2.1          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3248               0.7500               350       57750             9
3249               0.3125               350       63350             1

      Flight Year
3248         2015
3249         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3250  Flight3251  42230  ORD-SEA              1.7         151
3251  Flight3252  42096  ORD-LAX              5.0          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3250             0.354167               385       71225             8
3251             0.625000               350       57750             4

      Flight Year
3250         2015
3251         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3252  Flight3253  42321  ORD-SEA              1.8          55
3253  Flight3254  41892  ORD-LAX              4.3          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3252               0.5000               350       57750            11
3253               0.3125               350       63350             9

      Flight Year
3252         2015
3253         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3254  Flight3255  41849  ORD-SFO              2.7         190
3255  Flight3256  42183  ORD-ATL             10.2          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3254             0.333333             412.5     68062.5             7
3255             0.750000             220.0     40700.0             6

      Flight Year
3254         2014
3255         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3256  Flight3257  42244  ORD-LAS              2.2         109
3257  Flight3258  41839  ORD-BOS              1.4         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3256             0.833333             302.5     55962.5             8
3257             0.833333             330.0     54450.0             7

      Flight Year
3256         2015
3257         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3258  Flight3259  42119  ORD-LAS              2.3          26
3259  Flight3260  42039  ORD-CLT              0.4         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3258             0.729167               275       50875             4
3259             0.312500               125       20625             2

      Flight Year
3258         2015
3259         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3260  Flight3261  42017  ORD-MSP              2.7          18
3261  Flight3262  41733  ORD-PHX              1.1          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3260             0.333333               115       21275             1
3261             0.333333               250       45250             4

      Flight Year
3260         2015
3261         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3262  Flight3263  42291  ORD-SFO              2.0          12
3263  Flight3264  41881  ORD-SFO              1.5         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3262             0.708333             375.0     69375.0            10
3263             0.333333             412.5     68062.5             8

      Flight Year
3262         2015
3263         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3264  Flight3265  42106  ORD-ATL              6.4         157
3265  Flight3266  41701  ORD-DFW              1.6         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3264             0.333333               200       33000             4
3265             0.750000               200       37000             3

      Flight Year
3264         2015
3265         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3266  Flight3267  42132  ORD-ATL             11.0          96
3267  Flight3268  42331  ORD-LAX             10.9         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3266             0.708333               200       37000             5
3267             0.416667               525       86625            11

      Flight Year
3266         2015
3267         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3268  Flight3269  42095  ORD-CLT              1.1           2
3269  Flight3270  41943  ORD-IAH              0.5         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3268             0.770833               125       23125             4
3269             0.291667               200       37000            10

      Flight Year
3268         2015
3269         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3270  Flight3271  41709  ORD-DFW              3.1         175
3271  Flight3272  42198  ORD-DTW              2.8          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3270             0.354167             200.0     33000.0             3
3271             0.708333             126.5     22896.5             7

      Flight Year
3270         2014
3271         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3272  Flight3273  41846  ORD-CLT              1.6          79
3273  Flight3274  42259  ORD-DFW              3.1          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3272             0.708333             137.5     24887.5             7
3273             0.354167             200.0     33000.0             9

      Flight Year
3272         2014
3273         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3274  Flight3275  41953  ORD-JFK              0.8          92
3275  Flight3276  42220  ORD-DFW              1.6         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3274             0.791667               250       46250            11
3275             0.333333               220       40700             8

      Flight Year
3274         2014
3275         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3276  Flight3277  41837  ORD-ATL             10.8          52
3277  Flight3278  42300  ORD-LAX              5.7          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3276             0.770833               220       36300             7
3277             0.750000               350       57750            10

      Flight Year
3276         2014
3277         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3278  Flight3279  42164  ORD-ATL             12.2          89
3279  Flight3280  42005  ORD-LAX              4.4           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3278             0.583333               220       39820             6
3279             0.291667               350       64750             1

      Flight Year
3278         2015
3279         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3280  Flight3281  42036  ORD-MIA              1.1         147
3281  Flight3282  42277  ORD-DEN              1.3          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3280             0.833333               300       55500             2
3281             0.708333               300       49500             9

      Flight Year
3280         2015
3281         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3282  Flight3283  42309  ORD-LAX              5.8         205
3283  Flight3284  41998  ORD-LAX              6.9         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3282             0.291667               350       57750            11
3283             0.750000               490       90650            12

      Flight Year
3282         2015
3283         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3284  Flight3285  42188  ORD-SEA              3.5          66
3285  Flight3286  42020  ORD-LAX              3.7          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3284             0.895833               385       69685             7
3285             0.312500               350       64750             1

      Flight Year
3284         2015
3285         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3286  Flight3287  41867  ORD-DEN              3.0         184
3287  Flight3288  42188  ORD-CLT              2.1          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3286             0.541667             330.0     54450.0             8
3287             0.458333             137.5     25437.5             7

      Flight Year
3286         2014
3287         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3288  Flight3289  41871  ORD-MIA              2.8          16
3289  Flight3290  42155  ORD-LAX              4.3         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3288             0.291667               330       61050             8
3289             0.791667               350       64750             5

      Flight Year
3288         2014
3289         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3290  Flight3291  41671  ORD-LAX              4.5         202
3291  Flight3292  42362  ORD-LAS              3.0         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3290                 0.50               350       57750             2
3291                 0.75               385       63525            12

      Flight Year
3290         2014
3291         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3292  Flight3293  42326  ORD-BWI              2.1         114
3293  Flight3294  42275  ORD-DEN              1.5         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3292             0.750000               240       44400            11
3293             0.333333               300       49500             9

      Flight Year
3292         2015
3293         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3294  Flight3295  41822  ORD-LAS              2.4         163
3295  Flight3296  41663  ORD-LAS              1.2         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3294             0.750000             302.5     49912.5             7
3295             0.833333             275.0     50875.0             1

      Flight Year
3294         2014
3295         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3296  Flight3297  41681  ORD-EWR              1.8           5
3297  Flight3298  41848  ORD-PHX              3.6          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3296             0.895833               225       41625             2
3297             0.666667               275       50875             7

      Flight Year
3296         2014
3297         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3298  Flight3299  41973  ORD-PHX              3.8          58
3299  Flight3300  42247  ORD-BWI              1.8          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3298               0.8750               375       61875            11
3299               0.3125               264       43560             8

      Flight Year
3298         2014
3299         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3300  Flight3301  42063  ORD-SFO              3.5          54
3301  Flight3302  42001  ORD-MIA              4.5          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3300             0.708333               375       61875             2
3301             0.500000               420       77700            12

      Flight Year
3300         2015
3301         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3302  Flight3303  41856  ORD-DFW              3.3          75
3303  Flight3304  41955  ORD-MIA              2.4         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3302             0.708333               220       39820             8
3303             0.437500               300       55500            11

      Flight Year
3302         2014
3303         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3304  Flight3305  41841  ORD-LAX              6.8          37
3305  Flight3306  42061  ORD-LAX              4.0         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3304             0.333333               385       63525             7
3305             0.375000               350       64750             2

      Flight Year
3304         2014
3305         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3306  Flight3307  42216  ORD-IAH              1.6          77
3307  Flight3308  41923  ORD-BOS              1.3         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3306             0.750000               220       39820             7
3307             0.666667               300       49500            10

      Flight Year
3306         2015
3307         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3308  Flight3309  41872  ORD-JFK              2.9         168
3309  Flight3310  42131  ORD-SEA              0.7         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3308             0.541667               275       45375             8
3309             0.291667               350       64750             5

      Flight Year
3308         2014
3309         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3310  Flight3311  41767  ORD-ATL              9.6           2
3311  Flight3312  42331  ORD-DEN              4.1          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3310             0.604167               200       37000             5
3311             0.583333               450       83250            11

      Flight Year
3310         2014
3311         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3312  Flight3313  42326  ORD-MCO              2.8          22
3313  Flight3314  42292  ORD-CLT              2.5         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3312             0.791667               250       46250            11
3313             0.291667               125       23125            10

      Flight Year
3312         2015
3313         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3314  Flight3315  41792  ORD-LAX              4.7          73
3315  Flight3316  42259  ORD-LAS              1.9         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3314             0.750000               385       69685             6
3315             0.333333               275       50875             9

      Flight Year
3314         2014
3315         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3316  Flight3317  41957  ORD-DFW              3.2          20
3317  Flight3318  42040  ORD-DEN              1.6         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3316                0.625               200       37000            11
3317                0.500               300       49500             2

      Flight Year
3316         2014
3317         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3318  Flight3319  42098  ORD-SFO             -0.2          98
3319  Flight3320  41868  ORD-MSP              2.7          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3318             0.833333             375.0     69375.0             4
3319             0.458333             126.5     23402.5             8

      Flight Year
3318         2015
3319         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3320  Flight3321  41676  ORD-LGA              1.5         111
3321  Flight3322  41841  ORD-SEA              2.6         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3320             0.500000               275       50875             2
3321             0.291667               385       63525             7

      Flight Year
3320         2014
3321         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3322  Flight3323  41919  ORD-IAH              1.2          28
3323  Flight3324  41840  ORD-EWR              2.7          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3322                 0.75             200.0     37000.0            10
3323                 0.75             247.5     45787.5             7

      Flight Year
3322         2014
3323         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3324  Flight3325  41722  ORD-IAH              3.7         200
3325  Flight3326  42021  ORD-DEN              1.9         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3324             0.291667               200       33000             3
3325             0.729167               300       55500             1

      Flight Year
3324         2014
3325         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3326  Flight3327  42287  ORD-LGA              2.0         134
3327  Flight3328  41651  ORD-PHL              2.4          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3326             0.666667               275       50875            10
3327             0.750000               275       45375             1

      Flight Year
3326         2015
3327         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3328  Flight3329  42261  ORD-SFO              0.4          96
3329  Flight3330  42334  ORD-JFK              5.1         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3328             0.395833               375       69375             9
3329             0.541667               375       61875            11

      Flight Year
3328         2015
3329         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3330  Flight3331  42317  ORD-LGA              1.9          93
3331  Flight3332  42126  ORD-DTW              2.5         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3330             0.791667               275       50875            11
3331             0.729167               115       18975             5

      Flight Year
3330         2015
3331         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3332  Flight3333  42308  ORD-SEA              1.2         117
3333  Flight3334  41869  ORD-PHX              3.5         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3332             0.750000               350       64750            10
3333             0.708333               275       50875             8

      Flight Year
3332         2015
3333         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3334  Flight3335  42220  ORD-JFK              2.0         157
3335  Flight3336  42357  ORD-DFW              1.9          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3334             0.291667               275       45375             8
3335             0.312500               200       37000            12

      Flight Year
3334         2015
3335         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3336  Flight3337  41827  ORD-EWR              0.9         146
3337  Flight3338  42190  ORD-PHX              2.1          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3336             0.291667             247.5     45787.5             7
3337             0.791667             275.0     49775.0             7

      Flight Year
3336         2014
3337         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3338  Flight3339  41672  ORD-DEN              3.3           5
3339  Flight3340  42121  ORD-SFO              2.7          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3338             0.291667               300       55500             2
3339             0.750000               375       67875             4

      Flight Year
3338         2014
3339         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3340  Flight3341  42361  ORD-MCO              5.4         122
3341  Flight3342  41666  ORD-DFW              2.2         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3340             0.416667               350       64750            12
3341             0.333333               200       33000             1

      Flight Year
3340         2015
3341         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3342  Flight3343  41997  ORD-PHL              2.2         182
3343  Flight3344  41829  ORD-DEN              2.5         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3342             0.770833               385       63525            12
3343             0.291667               330       54450             7

      Flight Year
3342         2014
3343         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3344  Flight3345  41907  ORD-DEN              2.0          28
3345  Flight3346  41992  ORD-JFK              2.4         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3344             0.583333               300       55500             9
3345             0.333333               250       41250            12

      Flight Year
3344         2014
3345         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3346  Flight3347  41669  ORD-IAH              1.6          90
3347  Flight3348  41820  ORD-DTW              2.5          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3346             0.750000             200.0     36200.0             1
3347             0.291667             126.5     20872.5             6

      Flight Year
3346         2014
3347         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3348  Flight3349  42208  ORD-EWR              2.3         124
3349  Flight3350  42022  ORD-DFW              1.3          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3348             0.791667             247.5     45787.5             7
3349             0.687500             200.0     36200.0             1

      Flight Year
3348         2015
3349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3350  Flight3351  42334  ORD-JFK              3.9          40
3351  Flight3352  42184  ORD-SEA              0.4         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3350             0.333333               375       61875            11
3351             0.750000               385       71225             6

      Flight Year
3350         2015
3351         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3352  Flight3353  41761  ORD-CLT              2.0          15
3353  Flight3354  42128  ORD-EWR              2.6         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3352             0.541667               125       23125             5
3353             0.750000               225       37125             5

      Flight Year
3352         2014
3353         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3354  Flight3355  41701  ORD-IAH              2.0          76
3355  Flight3356  42146  ORD-BWI              2.9         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3354             0.854167               200       36200             3
3355             0.791667               240       44400             5

      Flight Year
3354         2014
3355         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3356  Flight3357  42333  ORD-MCO              4.8         176
3357  Flight3358  42185  ORD-LGA              1.2          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3356             0.750000             375.0     61875.0            11
3357             0.333333             302.5     55962.5             6

      Flight Year
3356         2015
3357         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3358  Flight3359  42084  ORD-ATL              9.4         148
3359  Flight3360  41675  ORD-CLT             -0.2         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3358             0.895833               200       37000             3
3359             0.500000               125       23125             2

      Flight Year
3358         2015
3359         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3360  Flight3361  41689  ORD-MSP              3.1          16
3361  Flight3362  42172  ORD-EWR              2.2         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3360             0.833333             115.0     21275.0             2
3361             0.708333             247.5     40837.5             6

      Flight Year
3360         2014
3361         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3362  Flight3363  41840  ORD-ATL              9.8          18
3363  Flight3364  41805  ORD-SEA              2.7         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3362               0.6875               220       40700             7
3363               0.3125               385       63525             6

      Flight Year
3362         2014
3363         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3364  Flight3365  41935  ORD-MCO              2.0         170
3365  Flight3366  42334  ORD-LAX             11.5         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3364             0.291667               250       41250            10
3365             0.625000               525       86625            11

      Flight Year
3364         2014
3365         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3366  Flight3367  42365  ORD-BWI              3.4         150
3367  Flight3368  41707  ORD-DEN              1.8         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3366             0.708333               336       62160            12
3367             0.666667               300       49500             3

      Flight Year
3366         2015
3367         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3368  Flight3369  41850  ORD-DFW              1.6         163
3369  Flight3370  42325  ORD-IAH              1.8          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3368             0.791667               220       36300             7
3369             0.791667               200       36200            11

      Flight Year
3368         2014
3369         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3370  Flight3371  42344  ORD-CLT              2.1          84
3371  Flight3372  42168  ORD-CLT              1.7         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3370             0.791667             125.0     22625.0            12
3371             0.333333             137.5     25437.5             6

      Flight Year
3370         2015
3371         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3372  Flight3373  41753  ORD-SFO              3.0          68
3373  Flight3374  41872  ORD-SLC              2.5          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3372                0.750               375       67875             4
3373                0.375               319       59015             8

      Flight Year
3372         2014
3373         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3374  Flight3375  42089  ORD-BOS              1.9          35
3375  Flight3376  42148  ORD-MIA              3.0         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3374             0.666667               300       55500             3
3375             0.895833               300       55500             5

      Flight Year
3374         2015
3375         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3376  Flight3377  42224  ORD-PHX              1.2         165
3377  Flight3378  42330  ORD-SEA              2.3         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3376             0.500000               275       45375             8
3377             0.604167               350       57750            11

      Flight Year
3376         2015
3377         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3378  Flight3379  42202  ORD-DEN              2.7          85
3379  Flight3380  42198  ORD-DEN              1.5         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3378             0.583333               330       59730             7
3379             0.750000               330       61050             7

      Flight Year
3378         2015
3379         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3380  Flight3381  42121  ORD-CLT              1.2          59
3381  Flight3382  42272  ORD-PHX              0.6          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3380             0.791667               125       20625             4
3381             0.291667               250       46250             9

      Flight Year
3380         2015
3381         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3382  Flight3383  41682  ORD-PHX              3.4         120
3383  Flight3384  42172  ORD-BWI              3.0          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3382             0.729167               250       46250             2
3383             0.354167               264       47784             6

      Flight Year
3382         2014
3383         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3384  Flight3385  41784  ORD-EWR              2.3         160
3385  Flight3386  42264  ORD-DFW              2.5         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3384             0.395833               225       37125             5
3385             0.416667               200       33000             9

      Flight Year
3384         2014
3385         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3386  Flight3387  41980  ORD-SFO              2.2          47
3387  Flight3388  42033  ORD-DEN              2.8          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3386             0.708333               375       61875            12
3387             0.854167               300       55500             1

      Flight Year
3386         2014
3387         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3388  Flight3389  41839  ORD-MSP              1.4         162
3389  Flight3390  41907  ORD-CLT              2.1          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3388             0.708333             126.5     20872.5             7
3389             0.812500             125.0     23125.0             9

      Flight Year
3388         2014
3389         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3390  Flight3391  41820  ORD-LAS              1.9         208
3391  Flight3392  42239  ORD-BOS              1.0          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3390             0.833333             302.5     49912.5             6
3391             0.812500             330.0     54450.0             8

      Flight Year
3390         2014
3391         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3392  Flight3393  41922  ORD-PHL              1.2          87
3393  Flight3394  42262  ORD-DEN              1.0          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3392             0.770833               275       49775            10
3393             0.708333               300       54300             9

      Flight Year
3392         2014
3393         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3394  Flight3395  42195  ORD-LAS              1.3          75
3395  Flight3396  41797  ORD-SEA              3.5          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3394             0.708333             302.5     54752.5             7
3395             0.354167             385.0     69685.0             6

      Flight Year
3394         2015
3395         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3396  Flight3397  42085  ORD-DEN              2.3          86
3397  Flight3398  41881  ORD-SEA              2.9         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3396             0.729167               300       54300             3
3397             0.708333               385       71225             8

      Flight Year
3396         2015
3397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3398  Flight3399  42128  ORD-MSP              3.1         110
3399  Flight3400  42148  ORD-DFW              2.9         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3398             0.666667               115       21275             5
3399             0.791667               200       33000             5

      Flight Year
3398         2015
3399         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3400  Flight3401  41822  ORD-SEA              1.9          32
3401  Flight3402  42158  ORD-FLL              2.5          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3400             0.791667               385       71225             7
3401             0.750000               330       59730             6

      Flight Year
3400         2014
3401         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3402  Flight3403  42014  ORD-MIA              2.3         171
3403  Flight3404  42359  ORD-ATL             16.3         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3402             0.708333               300       49500             1
3403             0.312500               280       46200            12

      Flight Year
3402         2015
3403         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3404  Flight3405  41754  ORD-SLC              1.7          20
3405  Flight3406  41986  ORD-LGA              1.9         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3404             0.750000               290       53650             4
3405             0.708333               275       45375            12

      Flight Year
3404         2014
3405         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3406  Flight3407  42273  ORD-LAX              3.8         179
3407  Flight3408  41641  ORD-EWR              1.5          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3406               0.6250               350       57750             9
3407               0.6875               225       41625             1

      Flight Year
3406         2015
3407         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3408  Flight3409  41783  ORD-SLC              1.4          83
3409  Flight3410  41992  ORD-EWR              3.3         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3408             0.833333               290       52490             5
3409             0.458333               225       37125            12

      Flight Year
3408         2014
3409         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3410  Flight3411  42227  ORD-IAH              0.9          11
3411  Flight3412  42124  ORD-DEN              1.6         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3410             0.833333               220       40700             8
3411             0.395833               300       49500             4

      Flight Year
3410         2015
3411         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3412  Flight3413  42299  ORD-MSP              2.6         200
3413  Flight3414  42113  ORD-IAH              1.6         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3412             0.708333               115       18975            10
3413             0.583333               200       37000             4

      Flight Year
3412         2015
3413         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3414  Flight3415  42360  ORD-LAX              6.7          95
3415  Flight3416  41774  ORD-PHL              1.7         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3414             0.395833               490       90650            12
3415             0.875000               275       45375             5

      Flight Year
3414         2015
3415         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3416  Flight3417  41894  ORD-DCA              1.8         171
3417  Flight3418  42062  ORD-JFK              1.8         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3416             0.291667              5000      825000             9
3417             0.750000               250       46250             2

      Flight Year
3416         2014
3417         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3418  Flight3419  41882  ORD-DEN              0.7           4
3419  Flight3420  42202  ORD-LAX              4.9         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3418             0.770833               330       61050             8
3419             0.875000               385       71225             7

      Flight Year
3418         2014
3419         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3420  Flight3421  41949  ORD-CLT              2.1          83
3421  Flight3422  42091  ORD-MSP              2.0          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3420             0.750000               125       22625            11
3421             0.666667               115       18975             3

      Flight Year
3420         2014
3421         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3422  Flight3423  41885  ORD-MCO              2.8           9
3423  Flight3424  41759  ORD-DFW              3.1         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3422             0.708333               250       46250             9
3423             0.291667               200       37000             4

      Flight Year
3422         2014
3423         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3424  Flight3425  41800  ORD-MCO              2.6         209
3425  Flight3426  42223  ORD-PHX              1.4          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3424             0.458333               275       45375             6
3425             0.666667               275       45375             8

      Flight Year
3424         2014
3425         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3426  Flight3427  42181  ORD-BOS              3.7          52
3427  Flight3428  42086  ORD-IAH              1.0         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3426                 0.50               330       54450             6
3427                 0.75               200       33000             3

      Flight Year
3426         2015
3427         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3428  Flight3429  41689  ORD-FLL              2.4          21
3429  Flight3430  42176  ORD-LAX              5.8         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3428             0.354167               300       55500             2
3429             0.291667               385       63525             6

      Flight Year
3428         2014
3429         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3430  Flight3431  42016  ORD-ATL             11.5         202
3431  Flight3432  41693  ORD-ATL              7.9          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3430             0.770833               200       33000             1
3431             0.395833               200       37000             2

      Flight Year
3430         2015
3431         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3432  Flight3433  41815  ORD-JFK              1.3         199
3433  Flight3434  42073  ORD-LAS              1.6          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3432             0.291667               275       45375             6
3433             0.333333               275       45375             3

      Flight Year
3432         2014
3433         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3434  Flight3435  42354  ORD-DFW              1.6          62
3435  Flight3436  42077  ORD-SFO              2.6         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3434             0.750000               200       33000            12
3435             0.791667               375       61875             3

      Flight Year
3434         2015
3435         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3436  Flight3437  42081  ORD-LAX              3.1         203
3437  Flight3438  42229  ORD-PHL              1.8         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3436             0.791667             350.0     57750.0             3
3437             0.750000             302.5     49912.5             8

      Flight Year
3436         2015
3437         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3438  Flight3439  41820  ORD-LAS              2.0          37
3439  Flight3440  42172  ORD-SEA              2.2         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3438             0.458333             302.5     49912.5             6
3439             0.333333             385.0     71225.0             6

      Flight Year
3438         2014
3439         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3440  Flight3441  41816  ORD-ATL             11.2         196
3441  Flight3442  41714  ORD-LAS              1.2         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3440             0.750000               220       36300             6
3441             0.833333               275       50875             3

      Flight Year
3440         2014
3441         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3442  Flight3443  42270  ORD-PHX             -0.1         190
3443  Flight3444  41822  ORD-MIA              2.7          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3442             0.750000               250       41250             9
3443             0.791667               330       59730             7

      Flight Year
3442         2015
3443         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3444  Flight3445  41873  ORD-PHL              2.4         167
3445  Flight3446  41708  ORD-MCO              2.1           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3444             0.625000             302.5     49912.5             8
3445             0.708333             250.0     46250.0             3

      Flight Year
3444         2014
3445         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3446  Flight3447  42092  ORD-MIA              3.1         142
3447  Flight3448  41915  ORD-EWR              2.3          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3446             0.750000               300       55500             3
3447             0.333333               225       40725            10

      Flight Year
3446         2015
3447         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3448  Flight3449  42330  ORD-JFK              2.3         177
3449  Flight3450  41864  ORD-PHX              3.0          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3448             0.333333               250       41250            11
3449             0.416667               275       50875             8

      Flight Year
3448         2015
3449         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3450  Flight3451  41802  ORD-CLT              1.7         125
3451  Flight3452  42071  ORD-SEA              3.6          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3450             0.729167             137.5     25437.5             6
3451             0.708333             350.0     57750.0             3

      Flight Year
3450         2014
3451         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3452  Flight3453  41928  ORD-PHL              1.7         123
3453  Flight3454  41804  ORD-ATL             10.5          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3452             0.708333               275       50875            10
3453             0.291667               220       36300             6

      Flight Year
3452         2014
3453         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3454  Flight3455  42026  ORD-SFO              2.1          45
3455  Flight3456  42292  ORD-DCA              2.7          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3454               0.5625               375       61875             1
3455               0.7500              5000      905000            10

      Flight Year
3454         2015
3455         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3456  Flight3457  42153  ORD-PHL              0.7         174
3457  Flight3458  41847  ORD-CLT              2.7          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3456             0.708333             275.0     45375.0             5
3457             0.833333             137.5     22687.5             7

      Flight Year
3456         2015
3457         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3458  Flight3459  41988  ORD-ATL              9.8          56
3459  Flight3460  42253  ORD-LAS              1.6          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3458             0.750000               200       33000            12
3459             0.645833               275       49775             9

      Flight Year
3458         2014
3459         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3460  Flight3461  42240  ORD-JFK              1.3         168
3461  Flight3462  42211  ORD-EWR              1.7         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3460                 0.75             275.0     45375.0             8
3461                 0.75             247.5     40837.5             7

      Flight Year
3460         2015
3461         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3462  Flight3463  42185  ORD-SFO              2.0         187
3463  Flight3464  42174  ORD-BOS              2.4         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3462             0.354167             412.5     68062.5             6
3463             0.291667             330.0     54450.0             6

      Flight Year
3462         2015
3463         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3464  Flight3465  41769  ORD-DFW              3.4         192
3465  Flight3466  41713  ORD-IAD              0.8         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3464             0.312500               200       33000             5
3465             0.833333               300       55500             3

      Flight Year
3464         2014
3465         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3466  Flight3467  42237  ORD-EWR              0.0         117
3467  Flight3468  41713  ORD-ATL              8.9          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3466             0.708333             247.5     45787.5             8
3467             0.750000             200.0     36200.0             3

      Flight Year
3466         2015
3467         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3468  Flight3469  42069  ORD-SFO              1.8          20
3469  Flight3470  42210  ORD-DFW              2.7         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3468             0.354167               375       69375             3
3469             0.416667               220       40700             7

      Flight Year
3468         2015
3469         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3470  Flight3471  41950  ORD-MIA              3.6         172
3471  Flight3472  41846  ORD-SEA              1.7         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3470             0.333333               300       49500            11
3471             0.500000               385       63525             7

      Flight Year
3470         2014
3471         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3472  Flight3473  42302  ORD-LAX              2.9          59
3473  Flight3474  41741  ORD-SFO              2.2          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3472             0.666667               350       57750            10
3473             0.333333               375       67875             4

      Flight Year
3472         2015
3473         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3474  Flight3475  41770  ORD-EWR              1.4          91
3475  Flight3476  41939  ORD-ATL             10.3          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3474             0.812500               225       41625             5
3475             0.833333               200       33000            10

      Flight Year
3474         2014
3475         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3476  Flight3477  41803  ORD-MSP              1.9         150
3477  Flight3478  41982  ORD-LGA              2.4         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3476             0.770833             126.5     23402.5             6
3477             0.875000             275.0     45375.0            12

      Flight Year
3476         2014
3477         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3478  Flight3479  42205  ORD-JFK              3.0         150
3479  Flight3480  41821  ORD-DFW              2.9         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3478               0.3125               275       50875             7
3479               0.7500               220       40700             7

      Flight Year
3478         2015
3479         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3480  Flight3481  41918  ORD-JFK              1.5          12
3481  Flight3482  41661  ORD-SFO              2.0          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3480             0.750000               250       46250            10
3481             0.791667               375       67875             1

      Flight Year
3480         2014
3481         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3482  Flight3483  42198  ORD-EWR              3.1          65
3483  Flight3484  42116  ORD-ATL             10.6         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3482             0.875000             247.5     44797.5             7
3483             0.354167             200.0     37000.0             4

      Flight Year
3482         2015
3483         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3484  Flight3485  41665  ORD-CLT              3.6          28
3485  Flight3486  41762  ORD-MIA              2.2          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3484             0.791667               125       23125             1
3485             0.729167               300       54300             5

      Flight Year
3484         2014
3485         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3486  Flight3487  42316  ORD-MIA              2.4         109
3487  Flight3488  42152  ORD-IAD              2.1         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3486             0.750000               300       55500            11
3487             0.333333               300       55500             5

      Flight Year
3486         2015
3487         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3488  Flight3489  41753  ORD-SEA              0.9         161
3489  Flight3490  41692  ORD-MIA              2.0         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3488             0.791667               350       57750             4
3489             0.354167               300       55500             2

      Flight Year
3488         2014
3489         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3490  Flight3491  41996  ORD-LAS              3.4          87
3491  Flight3492  42130  ORD-JFK              0.9         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3490             0.562500               385       69685            12
3491             0.291667               250       41250             5

      Flight Year
3490         2014
3491         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3492  Flight3493  41755  ORD-MCO              1.1         125
3493  Flight3494  41865  ORD-IAH              2.5         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3492                0.375               250       46250             4
3493                0.875               220       36300             8

      Flight Year
3492         2014
3493         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3494  Flight3495  42300  ORD-IAD              2.8          74
3495  Flight3496  41785  ORD-MIA              1.1         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3494             0.833333               300       54300            10
3495             0.687500               300       55500             5

      Flight Year
3494         2015
3495         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3496  Flight3497  41849  ORD-MIA              1.9          65
3497  Flight3498  42024  ORD-JFK              3.1         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3496             0.833333               330       59730             7
3497             0.791667               250       46250             1

      Flight Year
3496         2014
3497         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3498  Flight3499  41640  ORD-LAS              2.3          78
3499  Flight3500  42295  ORD-ATL              7.7          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3498             0.770833               275       49775             1
3499             0.750000               200       33000            10

      Flight Year
3498         2014
3499         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3500  Flight3501  41825  ORD-PHL              2.6         133
3501  Flight3502  41844  ORD-DTW              2.3           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3500             0.708333             302.5     55962.5             7
3501             0.291667             126.5     23402.5             7

      Flight Year
3500         2014
3501         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3502  Flight3503  42015  ORD-SFO              2.7         194
3503  Flight3504  42016  ORD-MIA              2.2         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3502             0.708333               375       61875             1
3503             0.333333               300       55500             1

      Flight Year
3502         2015
3503         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3504  Flight3505  41652  ORD-DFW              3.9         172
3505  Flight3506  41969  ORD-ATL             17.4         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3504             0.479167               200       33000             1
3505             0.291667               300       55500            11

      Flight Year
3504         2014
3505         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3506  Flight3507  41860  ORD-DFW              1.4         121
3507  Flight3508  41982  ORD-SFO              1.0         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3506             0.312500               220       40700             8
3507             0.791667               375       61875            12

      Flight Year
3506         2014
3507         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3508  Flight3509  42180  ORD-SEA              2.7         182
3509  Flight3510  41695  ORD-DTW              2.7         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3508             0.333333               385       63525             6
3509             0.500000               115       18975             2

      Flight Year
3508         2015
3509         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3510  Flight3511  42365  ORD-JFK              2.7         190
3511  Flight3512  42167  ORD-LGA              1.4         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3510             0.791667             350.0     57750.0            12
3511             0.770833             302.5     49912.5             6

      Flight Year
3510         2015
3511         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3512  Flight3513  41923  ORD-DEN              1.4          88
3513  Flight3514  42184  ORD-PHX              2.5         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3512             0.708333               300       54300            10
3513             0.291667               275       50875             6

      Flight Year
3512         2014
3513         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3514  Flight3515  42192  ORD-EWR              1.3          42
3515  Flight3516  41995  ORD-SEA              3.2          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3514             0.291667             247.5     40837.5             7
3515             0.312500             490.0     88690.0            12

      Flight Year
3514         2015
3515         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3516  Flight3517  41682  ORD-DFW              2.9         165
3517  Flight3518  41924  ORD-CLT              2.2         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3516             0.791667               200       33000             2
3517             0.708333               125       23125            10

      Flight Year
3516         2014
3517         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3518  Flight3519  41963  ORD-SFO              1.5          48
3519  Flight3520  42169  ORD-LAX              5.0          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3518               0.3125               375       61875            11
3519               0.3125               385       63525             6

      Flight Year
3518         2014
3519         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3520  Flight3521  41890  ORD-ATL              7.2         161
3521  Flight3522  41853  ORD-MIA              1.0           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3520             0.750000               200       33000             9
3521             0.791667               330       61050             8

      Flight Year
3520         2014
3521         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3522  Flight3523  41799  ORD-LAX              5.6         156
3523  Flight3524  42311  ORD-PHX              0.8          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3522             0.291667               385       63525             6
3523             0.750000               250       45250            11

      Flight Year
3522         2014
3523         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3524  Flight3525  41953  ORD-LAX              2.9         185
3525  Flight3526  41884  ORD-ATL              8.5         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3524             0.291667               350       57750            11
3525             0.791667               200       37000             9

      Flight Year
3524         2014
3525         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3526  Flight3527  42257  ORD-MCO              1.0          86
3527  Flight3528  42169  ORD-SFO              2.3         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3526             0.666667             250.0     45250.0             9
3527             0.791667             412.5     68062.5             6

      Flight Year
3526         2015
3527         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3528  Flight3529  42157  ORD-MSP              3.5           7
3529  Flight3530  42341  ORD-DCA              3.0          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3528             0.333333             126.5     23402.5             6
3529             0.770833            5000.0    825000.0            12

      Flight Year
3528         2015
3529         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3530  Flight3531  42175  ORD-LAX              7.1         143
3531  Flight3532  41689  ORD-BWI              1.4          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3530             0.291667               385       71225             6
3531             0.583333               240       43440             2

      Flight Year
3530         2015
3531         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3532  Flight3533  42100  ORD-ATL              7.8          34
3533  Flight3534  41882  ORD-SFO              1.2         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3532             0.729167             200.0     37000.0             4
3533             0.500000             412.5     68062.5             8

      Flight Year
3532         2015
3533         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3534  Flight3535  41997  ORD-LAX              8.7         162
3535  Flight3536  41961  ORD-SLC              2.7          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3534             0.395833               490       80850            12
3535             0.833333               290       52490            11

      Flight Year
3534         2014
3535         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3536  Flight3537  41682  ORD-MCO              2.9         113
3537  Flight3538  42229  ORD-PHX              2.1         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3536             0.333333               250       46250             2
3537             0.833333               275       50875             8

      Flight Year
3536         2014
3537         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3538  Flight3539  41782  ORD-SLC              1.5         130
3539  Flight3540  42154  ORD-EWR              0.1          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3538             0.750000               290       53650             5
3539             0.416667               225       40725             5

      Flight Year
3538         2014
3539         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3540  Flight3541  41880  ORD-IAD              2.9          24
3541  Flight3542  42165  ORD-LGA              2.4          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3540             0.395833             330.0     61050.0             8
3541             0.791667             302.5     54752.5             6

      Flight Year
3540         2014
3541         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3542  Flight3543  41963  ORD-FLL              1.6         103
3543  Flight3544  42096  ORD-CLT              1.4         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3542             0.333333               300       55500            11
3543             0.666667               125       20625             4

      Flight Year
3542         2014
3543         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3544  Flight3545  42352  ORD-MSP              3.0         203
3545  Flight3546  42127  ORD-JFK              1.2         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3544             0.750000               115       18975            12
3545             0.791667               250       41250             5

      Flight Year
3544         2015
3545         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3546  Flight3547  42284  ORD-ATL              9.8         189
3547  Flight3548  41979  ORD-CLT              2.1         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3546             0.666667               200       33000            10
3547             0.833333               125       23125            12

      Flight Year
3546         2015
3547         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3548  Flight3549  42129  ORD-DFW              2.8         165
3549  Flight3550  41642  ORD-CLT              1.7          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3548             0.750000               200       33000             5
3549             0.645833               125       20625             1

      Flight Year
3548         2015
3549         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3550  Flight3551  42171  ORD-DEN              1.8         100
3551  Flight3552  41999  ORD-CLT              4.4          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3550             0.750000               330       61050             6
3551             0.708333               175       28875            12

      Flight Year
3550         2015
3551         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3552  Flight3553  41680  ORD-DEN              2.1         179
3553  Flight3554  41739  ORD-LAX              5.7         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3552             0.729167               300       49500             2
3553             0.291667               350       57750             4

      Flight Year
3552         2014
3553         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3554  Flight3555  41771  ORD-LAS              2.3          93
3555  Flight3556  42015  ORD-DTW              1.4         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3554             0.708333               275       50875             5
3555             0.458333               115       21275             1

      Flight Year
3554         2014
3555         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3556  Flight3557  42319  ORD-ATL              7.7         182
3557  Flight3558  42362  ORD-DEN              3.8         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3556             0.833333               200       33000            11
3557             0.291667               420       77700            12

      Flight Year
3556         2015
3557         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3558  Flight3559  41911  ORD-SFO              0.9          31
3559  Flight3560  41648  ORD-DTW              3.1         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3558             0.541667               375       69375             9
3559             0.750000               115       18975             1

      Flight Year
3558         2014
3559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3560  Flight3561  41872  ORD-ATL             11.7          66
3561  Flight3562  41831  ORD-IAH              1.5         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3560             0.666667               220       39820             8
3561             0.770833               220       40700             7

      Flight Year
3560         2014
3561         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3562  Flight3563  42109  ORD-MIA              1.4         116
3563  Flight3564  41735  ORD-LAS              1.4          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3562             0.333333               300       55500             4
3563             0.791667               275       49775             4

      Flight Year
3562         2015
3563         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3564  Flight3565  42177  ORD-SFO              2.3         111
3565  Flight3566  41969  ORD-MIA              4.1         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3564             0.291667             412.5     76312.5             6
3565             0.625000             450.0     83250.0            11

      Flight Year
3564         2015
3565         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3566  Flight3567  41862  ORD-BOS              3.1          89
3567  Flight3568  42343  ORD-MSP              1.3         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3566             0.500000               330       59730             8
3567             0.333333               115       21275            12

      Flight Year
3566         2014
3567         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3568  Flight3569  41823  ORD-MIA              2.9          88
3569  Flight3570  41845  ORD-ATL              8.6          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3568             0.750000               330       59730             7
3569             0.770833               220       39820             7

      Flight Year
3568         2014
3569         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3570  Flight3571  41799  ORD-DTW              1.3          20
3571  Flight3572  42179  ORD-PHX              2.4         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3570                 0.75             126.5     23402.5             6
3571                 0.75             275.0     45375.0             6

      Flight Year
3570         2014
3571         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3572  Flight3573  41833  ORD-LAS              1.6         139
3573  Flight3574  41701  ORD-PHX              1.9          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3572             0.437500             302.5     55962.5             7
3573             0.333333             250.0     46250.0             3

      Flight Year
3572         2014
3573         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3574  Flight3575  41716  ORD-JFK              1.9         125
3575  Flight3576  42339  ORD-DEN              1.7         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3574                 0.75               250       46250             3
3575                 0.75               300       55500            12

      Flight Year
3574         2014
3575         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3576  Flight3577  42264  ORD-LAX              2.8         132
3577  Flight3578  42138  ORD-BOS              2.1          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3576             0.541667               350       64750             9
3577             0.687500               300       54300             5

      Flight Year
3576         2015
3577         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3578  Flight3579  42313  ORD-DEN              1.5         164
3579  Flight3580  41819  ORD-MCO              1.8         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3578             0.458333               300       49500            11
3579             0.291667               275       50875             6

      Flight Year
3578         2015
3579         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3580  Flight3581  41653  ORD-EWR              1.9          15
3581  Flight3582  42062  ORD-SFO              1.2         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3580             0.708333               225       41625             1
3581             0.354167               375       69375             2

      Flight Year
3580         2014
3581         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3582  Flight3583  42038  ORD-DFW              2.1         150
3583  Flight3584  42026  ORD-SFO              2.4           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3582             0.333333               200       37000             2
3583             0.291667               375       69375             1

      Flight Year
3582         2015
3583         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3584  Flight3585  42213  ORD-MSP              1.8         124
3585  Flight3586  42335  ORD-MCO              5.4         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3584             0.312500             126.5     23402.5             7
3585             0.791667             375.0     69375.0            11

      Flight Year
3584         2015
3585         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3586  Flight3587  42365  ORD-LAX              5.4          36
3587  Flight3588  41900  ORD-ATL              9.1         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3586             0.312500               490       80850            12
3587             0.791667               200       33000             9

      Flight Year
3586         2015
3587         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3588  Flight3589  41855  ORD-PHL              3.3          19
3589  Flight3590  42046  ORD-LAS              2.0          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3588             0.791667             302.5     55962.5             8
3589             0.291667             275.0     50875.0             2

      Flight Year
3588         2014
3589         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3590  Flight3591  42104  ORD-MIA              0.6         112
3591  Flight3592  42062  ORD-PHX              1.0          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3590             0.458333               300       55500             4
3591             0.458333               250       45250             2

      Flight Year
3590         2015
3591         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3592  Flight3593  41657  ORD-MCO              1.5         121
3593  Flight3594  41838  ORD-SFO              1.8         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3592             0.833333             250.0     46250.0             1
3593             0.750000             412.5     68062.5             7

      Flight Year
3592         2014
3593         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3594  Flight3595  41864  ORD-CLT              1.3          66
3595  Flight3596  42363  ORD-DFW              3.6         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3594             0.541667             137.5     24887.5             8
3595             0.729167             280.0     51800.0            12

      Flight Year
3594         2014
3595         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3596  Flight3597  42010  ORD-LAS              1.2          87
3597  Flight3598  41723  ORD-LAS              1.9          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3596             0.541667               275       49775             1
3597             0.791667               275       49775             3

      Flight Year
3596         2015
3597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3598  Flight3599  41771  ORD-MIA              3.2         148
3599  Flight3600  41660  ORD-ATL             11.3         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3598             0.750000               300       55500             5
3599             0.354167               200       37000             1

      Flight Year
3598         2014
3599         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3600  Flight3601  42222  ORD-PHX              3.3         168
3601  Flight3602  41816  ORD-EWR              1.0         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3600             0.812500             275.0     45375.0             8
3601             0.291667             247.5     40837.5             6

      Flight Year
3600         2015
3601         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3602  Flight3603  41997  ORD-IAH              2.6          13
3603  Flight3604  41798  ORD-IAH              1.2          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3602             0.750000               280       51800            12
3603             0.666667               220       39820             6

      Flight Year
3602         2014
3603         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3604  Flight3605  41689  ORD-BOS              1.5          71
3605  Flight3606  41903  ORD-PHL              2.3          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3604             0.291667               300       54300             2
3605             0.708333               275       45375             9

      Flight Year
3604         2014
3605         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3606  Flight3607  42109  ORD-LAS              1.7          91
3607  Flight3608  42164  ORD-LAS              1.7         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3606             0.750000             275.0     50875.0             4
3607             0.479167             302.5     49912.5             6

      Flight Year
3606         2015
3607         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3608  Flight3609  42204  ORD-DEN              1.5         145
3609  Flight3610  42109  ORD-LAS              1.1         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3608                0.625               330       61050             7
3609                0.750               275       50875             4

      Flight Year
3608         2015
3609         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3610  Flight3611  42239  ORD-SFO              1.3          44
3611  Flight3612  42354  ORD-SEA              2.9         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3610             0.583333             412.5     68062.5             8
3611             0.750000             350.0     57750.0            12

      Flight Year
3610         2015
3611         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3612  Flight3613  41971  ORD-SFO              5.7         127
3613  Flight3614  41740  ORD-LAS              3.4         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3612             0.291667             562.5    104062.5            11
3613             0.458333             275.0     45375.0             4

      Flight Year
3612         2014
3613         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3614  Flight3615  41656  ORD-JFK                2          75
3615  Flight3616  42033  ORD-FLL                2          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3614             0.520833               250       45250             1
3615             0.812500               300       55500             1

      Flight Year
3614         2014
3615         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3616  Flight3617  42051  ORD-DTW              2.2         163
3617  Flight3618  42211  ORD-PHX              2.0          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3616             0.541667               115       18975             2
3617             0.791667               275       45375             7

      Flight Year
3616         2015
3617         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3618  Flight3619  42271  ORD-DFW              1.9         202
3619  Flight3620  41678  ORD-PHL              3.1         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3618             0.416667               200       33000             9
3619             0.333333               275       45375             2

      Flight Year
3618         2015
3619         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3620  Flight3621  41716  ORD-LAX              3.7          87
3621  Flight3622  42020  ORD-ATL              7.2          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3620             0.625000               350       63350             3
3621             0.291667               200       37000             1

      Flight Year
3620         2014
3621         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3622  Flight3623  42269  ORD-LAX              4.3         116
3623  Flight3624  42205  ORD-BOS              0.4         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3622             0.729167               350       64750             9
3623             0.708333               330       54450             7

      Flight Year
3622         2015
3623         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3624  Flight3625  42119  ORD-LAX              4.6         160
3625  Flight3626  42031  ORD-JFK              1.3          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3624             0.312500               350       57750             4
3625             0.333333               250       41250             1

      Flight Year
3624         2015
3625         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3626  Flight3627  41796  ORD-DFW              1.2         168
3627  Flight3628  41969  ORD-MCO              4.4         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3626             0.291667               220       36300             6
3627             0.791667               375       61875            11

      Flight Year
3626         2014
3627         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3628  Flight3629  41732  ORD-DFW              2.8         138
3629  Flight3630  42291  ORD-BOS              3.4         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3628             0.750000               200       37000             4
3629             0.458333               300       55500            10

      Flight Year
3628         2014
3629         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3630  Flight3631  41647  ORD-JFK              1.9          44
3631  Flight3632  41953  ORD-CLT              2.2         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3630             0.541667               250       41250             1
3631             0.770833               125       20625            11

      Flight Year
3630         2014
3631         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3632  Flight3633  42262  ORD-LAX              3.6          63
3633  Flight3634  42248  ORD-DFW              0.8           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3632             0.708333               350       63350             9
3633             0.333333               200       37000             9

      Flight Year
3632         2015
3633         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3634  Flight3635  42123  ORD-LAX              3.5          76
3635  Flight3636  41940  ORD-DEN              2.0         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3634             0.645833               350       63350             4
3635             0.291667               300       55500            10

      Flight Year
3634         2015
3635         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3636  Flight3637  41935  ORD-LAX              4.8          72
3637  Flight3638  41764  ORD-MCO              2.2          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3636             0.666667               350       63350            10
3637             0.291667               250       46250             5

      Flight Year
3636         2014
3637         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3638  Flight3639  42286  ORD-IAH              1.6          19
3639  Flight3640  41721  ORD-JFK              2.0          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3638             0.395833               200       37000            10
3639             0.291667               250       45250             3

      Flight Year
3638         2015
3639         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3640  Flight3641  41865  ORD-LAX              4.9          35
3641  Flight3642  41775  ORD-JFK              2.8          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3640             0.708333               385       71225             8
3641             0.333333               250       45250             5

      Flight Year
3640         2014
3641         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3642  Flight3643  42105  ORD-LAX              5.0         153
3643  Flight3644  42232  ORD-FLL              2.2         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3642             0.291667               350       57750             4
3643             0.791667               330       61050             8

      Flight Year
3642         2015
3643         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3644  Flight3645  42175  ORD-JFK              1.9         147
3645  Flight3646  42115  ORD-ATL              7.8          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3644             0.416667               275       50875             6
3645             0.708333               200       33000             4

      Flight Year
3644         2015
3645         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3646  Flight3647  42247  ORD-BWI              1.3         168
3647  Flight3648  42281  ORD-PHX              2.8          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3646               0.6875               264       43560             8
3647               0.8125               250       45250            10

      Flight Year
3646         2015
3647         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3648  Flight3649  41822  ORD-PHX              2.6         134
3649  Flight3650  42221  ORD-PHX              1.9         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3648               0.5000               275       50875             7
3649               0.4375               275       50875             8

      Flight Year
3648         2014
3649         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3650  Flight3651  42183  ORD-DFW              2.7         113
3651  Flight3652  41749  ORD-LAS              1.5         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3650             0.479167               220       40700             6
3651             0.291667               275       45375             4

      Flight Year
3650         2015
3651         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3652  Flight3653  41640  ORD-PHX              2.1         157
3653  Flight3654  42289  ORD-MSP              1.4         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3652             0.625000               250       41250             1
3653             0.416667               115       18975            10

      Flight Year
3652         2014
3653         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3654  Flight3655  41725  ORD-LAX              4.4           7
3655  Flight3656  41848  ORD-DEN              0.2         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3654             0.875000               350       64750             3
3655             0.708333               330       54450             7

      Flight Year
3654         2014
3655         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3656  Flight3657  41817  ORD-LAX              6.9          49
3657  Flight3658  42084  ORD-LAX              5.2         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3656             0.708333               385       63525             6
3657             0.708333               350       57750             3

      Flight Year
3656         2014
3657         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3658  Flight3659  41742  ORD-IAD              1.6         192
3659  Flight3660  42132  ORD-DFW              1.5          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3658             0.458333               300       49500             4
3659             0.791667               200       37000             5

      Flight Year
3658         2014
3659         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3660  Flight3661  42042  ORD-LAS              2.8         191
3661  Flight3662  41756  ORD-PHL              1.0         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3660             0.333333               275       45375             2
3661             0.604167               275       50875             4

      Flight Year
3660         2015
3661         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3662  Flight3663  42359  ORD-PHX              3.4           7
3663  Flight3664  41940  ORD-SFO              3.2          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3662             0.416667               350       64750            12
3663             0.708333               375       67875            10

      Flight Year
3662         2015
3663         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3664  Flight3665  42029  ORD-DEN              2.3         105
3665  Flight3666  41994  ORD-ATL             12.2         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3664             0.750000               300       55500             1
3665             0.791667               200       37000            12

      Flight Year
3664         2015
3665         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3666  Flight3667  41956  ORD-PHX              3.2          83
3667  Flight3668  41860  ORD-DFW              1.6         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3666             0.312500               250       45250            11
3667             0.291667               220       36300             8

      Flight Year
3666         2014
3667         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3668  Flight3669  42288  ORD-DFW              2.1           5
3669  Flight3670  41839  ORD-DFW              1.4           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3668             0.354167               200       37000            10
3669             0.750000               220       40700             7

      Flight Year
3668         2015
3669         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3670  Flight3671  41928  ORD-IAH              2.2         201
3671  Flight3672  41767  ORD-FLL              3.4          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3670             0.812500               200       33000            10
3671             0.708333               300       54300             5

      Flight Year
3670         2014
3671         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3672  Flight3673  41897  ORD-EWR              1.3          76
3673  Flight3674  42199  ORD-DEN              1.9          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3672             0.291667               225       40725             9
3673             0.708333               330       61050             7

      Flight Year
3672         2014
3673         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3674  Flight3675  41673  ORD-DEN              2.5         146
3675  Flight3676  42091  ORD-DFW              1.6         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3674             0.708333               300       55500             2
3675             0.354167               200       33000             3

      Flight Year
3674         2014
3675         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3676  Flight3677  41999  ORD-LAX              9.4         185
3677  Flight3678  41970  ORD-CLT              5.8         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3676             0.500000             490.0     80850.0            12
3677             0.291667             187.5     30937.5            11

      Flight Year
3676         2014
3677         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3678  Flight3679  42365  ORD-LAX              8.5         209
3679  Flight3680  42257  ORD-LAX              3.0          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3678             0.500000               490       80850            12
3679             0.291667               350       57750             9

      Flight Year
3678         2015
3679         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3680  Flight3681  42350  ORD-CLT              2.1          77
3681  Flight3682  41923  ORD-SFO              2.3           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3680               0.3125               125       22625            12
3681               0.7500               375       69375            10

      Flight Year
3680         2015
3681         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3682  Flight3683  42073  ORD-MCO              1.5         110
3683  Flight3684  41793  ORD-JFK              3.2         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3682             0.541667               250       46250             3
3683             0.500000               275       45375             6

      Flight Year
3682         2015
3683         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3684  Flight3685  42360  ORD-LAX              8.3          25
3685  Flight3686  41862  ORD-ATL              8.4          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3684               0.3125               490       90650            12
3685               0.8750               220       39820             8

      Flight Year
3684         2015
3685         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3686  Flight3687  41895  ORD-LGA              1.6         136
3687  Flight3688  41752  ORD-PHX              0.4         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3686             0.791667               275       50875             9
3687             0.583333               250       46250             4

      Flight Year
3686         2014
3687         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3688  Flight3689  42165  ORD-DFW              2.8         172
3689  Flight3690  41853  ORD-JFK              1.1         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3688             0.833333               220       36300             6
3689             0.333333               275       45375             8

      Flight Year
3688         2015
3689         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3690  Flight3691  42155  ORD-LAS              1.8          79
3691  Flight3692  42151  ORD-PHL              1.7         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3690             0.625000               275       49775             5
3691             0.666667               275       50875             5

      Flight Year
3690         2015
3691         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3692  Flight3693  42306  ORD-CLT              2.6         102
3693  Flight3694  42267  ORD-LGA              1.4         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3692             0.708333               125       23125            10
3693             0.708333               275       50875             9

      Flight Year
3692         2015
3693         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3694  Flight3695  42082  ORD-LGA              2.0          24
3695  Flight3696  41796  ORD-LAX              4.9          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3694             0.854167               275       50875             3
3695             0.750000               385       63525             6

      Flight Year
3694         2015
3695         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3696  Flight3697  41803  ORD-BOS              2.4          31
3697  Flight3698  41889  ORD-DFW              1.2         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3696             0.291667               330       61050             6
3697             0.875000               200       37000             9

      Flight Year
3696         2014
3697         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3698  Flight3699  42327  ORD-DFW              2.3         135
3699  Flight3700  42214  ORD-BWI              1.6          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3698             0.583333               200       37000            11
3699             0.666667               264       43560             7

      Flight Year
3698         2015
3699         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3700  Flight3701  42367  ORD-LAX              5.4         122
3701  Flight3702  41886  ORD-EWR              1.9          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3700                0.750               350       64750            12
3701                0.875               225       37125             9

      Flight Year
3700         2015
3701         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3702  Flight3703  42329  ORD-JFK              2.2          62
3703  Flight3704  41650  ORD-BWI              1.6         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3702                0.875               250       41250            11
3703                0.750               240       44400             1

      Flight Year
3702         2015
3703         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3704  Flight3705  41713  ORD-DEN              2.6          28
3705  Flight3706  41814  ORD-DFW              1.9           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3704             0.291667               300       55500             3
3705             0.500000               220       40700             6

      Flight Year
3704         2014
3705         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3706  Flight3707  41969  ORD-LAS              8.0         180
3707  Flight3708  41865  ORD-SEA              0.7         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3706             0.583333             412.5     68062.5            11
3707             0.708333             385.0     63525.0             8

      Flight Year
3706         2014
3707         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3708  Flight3709  42151  ORD-ATL              6.9         143
3709  Flight3710  42286  ORD-LAX              5.6         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3708                 0.75               200       37000             5
3709                 0.50               350       57750            10

      Flight Year
3708         2015
3709         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3710  Flight3711  41861  ORD-LAS              2.2         111
3711  Flight3712  41809  ORD-DEN              0.9         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3710             0.666667             302.5     55962.5             8
3711             0.562500             330.0     61050.0             6

      Flight Year
3710         2014
3711         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3712  Flight3713  42153  ORD-ATL              7.8           1
3713  Flight3714  41716  ORD-LAX              3.9         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3712             0.333333               200       37000             5
3713             0.541667               350       64750             3

      Flight Year
3712         2015
3713         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3714  Flight3715  41962  ORD-DFW              2.7          11
3715  Flight3716  41958  ORD-SFO              1.7          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3714             0.770833               200       37000            11
3715             0.750000               375       61875            11

      Flight Year
3714         2014
3715         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3716  Flight3717  42105  ORD-LGA              1.1          19
3717  Flight3718  41796  ORD-CLT              1.3         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3716             0.729167             275.0     50875.0             4
3717             0.854167             137.5     25437.5             6

      Flight Year
3716         2015
3717         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3718  Flight3719  41844  ORD-DFW              1.1          28
3719  Flight3720  41857  ORD-LAS              2.3          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3718             0.458333             220.0     40700.0             7
3719             0.875000             302.5     55962.5             8

      Flight Year
3718         2014
3719         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3720  Flight3721  42014  ORD-MSP              2.3          44
3721  Flight3722  42266  ORD-DFW              2.1         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3720             0.833333               115       18975             1
3721             0.666667               200       37000             9

      Flight Year
3720         2015
3721         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3722  Flight3723  41955  ORD-DFW              2.9         136
3723  Flight3724  41885  ORD-DEN              2.3         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3722             0.541667               200       37000            11
3723             0.833333               300       55500             9

      Flight Year
3722         2014
3723         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3724  Flight3725  41663  ORD-LAX              3.9          84
3725  Flight3726  41705  ORD-MSP              2.6         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3724             0.291667               350       63350             1
3725             0.750000               115       21275             3

      Flight Year
3724         2014
3725         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3726  Flight3727  41666  ORD-FLL              2.2           9
3727  Flight3728  42338  ORD-EWR              0.4          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3726             0.291667               300       55500             1
3727             0.333333               225       40725            11

      Flight Year
3726         2014
3727         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3728  Flight3729  41881  ORD-BOS              2.3          71
3729  Flight3730  41770  ORD-PHL              2.6          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3728             0.708333               330       59730             8
3729             0.312500               275       49775             5

      Flight Year
3728         2014
3729         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3730  Flight3731  42270  ORD-ATL              9.6          83
3731  Flight3732  41846  ORD-DFW              1.9         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3730             0.791667               200       36200             9
3731             0.854167               220       36300             7

      Flight Year
3730         2015
3731         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3732  Flight3733  42343  ORD-PHX              1.0          55
3733  Flight3734  41828  ORD-LGA              1.6          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3732             0.333333             250.0     41250.0            12
3733             0.708333             302.5     55962.5             7

      Flight Year
3732         2015
3733         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3734  Flight3735  42062  ORD-ATL              8.9         201
3735  Flight3736  41684  ORD-LAX              4.6         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3734             0.291667               200       33000             2
3735             0.291667               350       64750             2

      Flight Year
3734         2015
3735         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3736  Flight3737  41691  ORD-IAH              1.3         170
3737  Flight3738  41897  ORD-MCO              2.3         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3736             0.333333               200       33000             2
3737             0.291667               250       41250             9

      Flight Year
3736         2014
3737         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3738  Flight3739  41647  ORD-IAH              2.6         140
3739  Flight3740  41910  ORD-EWR              2.4          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3738             0.541667               200       37000             1
3739             0.833333               225       40725             9

      Flight Year
3738         2014
3739         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3740  Flight3741  41904  ORD-MSP              1.8         134
3741  Flight3742  42146  ORD-LAX              3.3          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3740             0.625000               115       21275             9
3741             0.395833               350       57750             5

      Flight Year
3740         2014
3741         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3742  Flight3743  42070  ORD-PHL              2.6         137
3743  Flight3744  42288  ORD-IAH              1.3          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3742             0.333333               275       50875             3
3743             0.458333               200       37000            10

      Flight Year
3742         2015
3743         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3744  Flight3745  42080  ORD-PHL              1.6          81
3745  Flight3746  41772  ORD-SFO              2.7         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3744             0.812500               275       49775             3
3745             0.791667               375       69375             5

      Flight Year
3744         2015
3745         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3746  Flight3747  42087  ORD-MSP              2.6          38
3747  Flight3748  41862  ORD-CLT              0.2          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3746             0.333333             115.0     18975.0             3
3747             0.291667             137.5     24887.5             8

      Flight Year
3746         2015
3747         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3748  Flight3749  42199  ORD-SEA              1.6         163
3749  Flight3750  42364  ORD-DEN              6.8         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3748             0.687500               385       63525             7
3749             0.708333               420       77700            12

      Flight Year
3748         2015
3749         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3750  Flight3751  42348  ORD-BOS              3.1         132
3751  Flight3752  41829  ORD-ATL             11.9         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3750             0.729167               300       55500            12
3751             0.791667               220       40700             7

      Flight Year
3750         2015
3751         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3752  Flight3753  41675  ORD-DFW                2           8
3753  Flight3754  42052  ORD-DTW                2          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3752             0.333333               200       37000             2
3753             0.791667               115       20815             2

      Flight Year
3752         2014
3753         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3754  Flight3755  41967  ORD-ATL             20.9         133
3755  Flight3756  41739  ORD-BWI              3.1         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3754             0.729167               300       55500            11
3755             0.312500               240       39600             4

      Flight Year
3754         2014
3755         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3756  Flight3757  41954  ORD-PHX              1.4         169
3757  Flight3758  42143  ORD-BOS              1.9          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3756             0.708333               250       41250            11
3757             0.791667               300       49500             5

      Flight Year
3756         2014
3757         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3758  Flight3759  41869  ORD-ATL              9.3         196
3759  Flight3760  42111  ORD-IAD              1.9         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3758             0.645833               220       36300             8
3759             0.750000               300       55500             4

      Flight Year
3758         2014
3759         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3760  Flight3761  42078  ORD-ATL              7.8         103
3761  Flight3762  41984  ORD-LGA              1.9         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3760             0.708333               200       37000             3
3761             0.333333               275       50875            12

      Flight Year
3760         2015
3761         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3762  Flight3763  41861  ORD-LAX              5.5         194
3763  Flight3764  42360  ORD-SEA              4.8          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3762             0.291667               385       63525             8
3763             0.708333               490       90650            12

      Flight Year
3762         2014
3763         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3764  Flight3765  41801  ORD-SEA              2.1         159
3765  Flight3766  41836  ORD-LAX              4.8          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3764             0.750000               385       63525             6
3765             0.583333               385       69685             7

      Flight Year
3764         2014
3765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3766  Flight3767  42240  ORD-MCO              1.0         185
3767  Flight3768  41661  ORD-IAH              1.2         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3766             0.791667               275       45375             8
3767             0.312500               200       37000             1

      Flight Year
3766         2015
3767         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3768  Flight3769  42344  ORD-DCA              0.8         119
3769  Flight3770  42186  ORD-SFO              1.2         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3768             0.333333            5000.0    925000.0            12
3769             0.708333             412.5     68062.5             7

      Flight Year
3768         2015
3769         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3770  Flight3771  42322  ORD-PHL              2.8          64
3771  Flight3772  42228  ORD-LAX              5.5         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3770             0.583333               275       49775            11
3771             0.333333               385       63525             8

      Flight Year
3770         2015
3771         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3772  Flight3773  41985  ORD-LAS              1.6         186
3773  Flight3774  42203  ORD-SFO              0.9          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3772             0.791667             275.0     45375.0            12
3773             0.791667             412.5     74662.5             7

      Flight Year
3772         2014
3773         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3774  Flight3775  41901  ORD-DEN              2.8         153
3775  Flight3776  42133  ORD-SFO              1.3         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3774             0.500000               300       49500             9
3775             0.791667               375       61875             5

      Flight Year
3774         2014
3775         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3776  Flight3777  42218  ORD-LAX              4.3         185
3777  Flight3778  42166  ORD-SFO              1.7         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3776             0.770833             385.0     63525.0             8
3777             0.750000             412.5     68062.5             6

      Flight Year
3776         2015
3777         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3778  Flight3779  42207  ORD-SEA              1.3         110
3779  Flight3780  41983  ORD-CLT              2.8         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3778             0.291667               385       71225             7
3779             0.479167               125       20625            12

      Flight Year
3778         2015
3779         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3780  Flight3781  42175  ORD-MCO              3.2           6
3781  Flight3782  42140  ORD-JFK              2.3         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3780             0.708333               275       50875             6
3781             0.333333               250       41250             5

      Flight Year
3780         2015
3781         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3782  Flight3783  41813  ORD-ATL             10.6          58
3783  Flight3784  41913  ORD-DFW              1.8          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3782             0.833333               220       36300             6
3783             0.729167               200       37000            10

      Flight Year
3782         2014
3783         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3784  Flight3785  42178  ORD-PHL              2.3         133
3785  Flight3786  42124  ORD-PHL              1.7          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3784             0.708333             302.5     55962.5             6
3785             0.333333             275.0     45375.0             4

      Flight Year
3784         2015
3785         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3786  Flight3787  41643  ORD-IAH              2.3         154
3787  Flight3788  41929  ORD-EWR              1.6         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3786             0.354167               200       33000             1
3787             0.625000               225       41625            10

      Flight Year
3786         2014
3787         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3788  Flight3789  42139  ORD-CLT              1.6           5
3789  Flight3790  41995  ORD-JFK              4.4          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3788             0.708333               125       23125             5
3789             0.770833               350       57750            12

      Flight Year
3788         2015
3789         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3790  Flight3791  42229  ORD-CLT              2.6          38
3791  Flight3792  42169  ORD-PHX              3.0         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3790             0.541667             137.5     22687.5             8
3791             0.500000             275.0     45375.0             6

      Flight Year
3790         2015
3791         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3792  Flight3793  42199  ORD-PHL              2.8          29
3793  Flight3794  42046  ORD-IAH              1.1          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3792             0.812500             302.5     55962.5             7
3793             0.791667             200.0     37000.0             2

      Flight Year
3792         2015
3793         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3794  Flight3795  41876  ORD-LAS              2.8         138
3795  Flight3796  42313  ORD-MSP              1.5          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3794             0.333333             302.5     55962.5             8
3795             0.375000             115.0     18975.0            11

      Flight Year
3794         2014
3795         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3796  Flight3797  41659  ORD-JFK              2.8         131
3797  Flight3798  42078  ORD-MIA              1.3         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3796             0.833333               250       46250             1
3797             0.770833               300       49500             3

      Flight Year
3796         2014
3797         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3798  Flight3799  41742  ORD-LAX              5.3         186
3799  Flight3800  42322  ORD-MIA              1.7         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3798             0.354167               350       57750             4
3799             0.375000               300       49500            11

      Flight Year
3798         2014
3799         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3800  Flight3801  41813  ORD-LAX              4.1         128
3801  Flight3802  41799  ORD-DFW              2.4         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3800             0.583333               385       71225             6
3801             0.500000               220       40700             6

      Flight Year
3800         2014
3801         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3802  Flight3803  42346  ORD-LGA                2         136
3803  Flight3804  42357  ORD-DTW                2          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3802             0.333333               275       50875            12
3803             0.833333               115       20815            12

      Flight Year
3802         2015
3803         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3804  Flight3805  42252  ORD-PHX              2.3         177
3805  Flight3806  41644  ORD-IAH              1.8          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3804             0.645833               250       41250             9
3805             0.375000               200       36200             1

      Flight Year
3804         2015
3805         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3806  Flight3807  41752  ORD-SEA              2.1          91
3807  Flight3808  41856  ORD-LAS              1.2         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3806             0.812500             350.0     64750.0             4
3807             0.333333             302.5     55962.5             8

      Flight Year
3806         2014
3807         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3808  Flight3809  41870  ORD-DEN              3.0          14
3809  Flight3810  41801  ORD-DTW              2.5         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3808             0.708333             330.0     61050.0             8
3809             0.333333             126.5     23402.5             6

      Flight Year
3808         2014
3809         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3810  Flight3811  41794  ORD-LGA              2.3         167
3811  Flight3812  41746  ORD-MCO              2.5         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3810             0.770833             302.5     49912.5             6
3811             0.791667             250.0     46250.0             4

      Flight Year
3810         2014
3811         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3812  Flight3813  42003  ORD-IAH              2.2         113
3813  Flight3814  41879  ORD-CLT              1.7          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3812             0.395833             200.0     37000.0            12
3813             0.812500             137.5     25437.5             8

      Flight Year
3812         2014
3813         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3814  Flight3815  42128  ORD-DEN              2.6          10
3815  Flight3816  42080  ORD-SEA              1.4         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3814             0.291667               300       55500             5
3815             0.375000               350       57750             3

      Flight Year
3814         2015
3815         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3816  Flight3817  41857  ORD-IAH              3.7         132
3817  Flight3818  42307  ORD-LAS              1.9         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3816             0.354167               220       40700             8
3817             0.291667               275       50875            10

      Flight Year
3816         2014
3817         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3818  Flight3819  42235  ORD-DCA              1.5          60
3819  Flight3820  42365  ORD-EWR              1.7          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3818             0.791667              5500      907500             8
3819             0.708333               315       58275            12

      Flight Year
3818         2015
3819         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3820  Flight3821  41764  ORD-IAH              2.1         196
3821  Flight3822  41762  ORD-MIA              1.5          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3820             0.791667               200       33000             5
3821             0.750000               300       55500             5

      Flight Year
3820         2014
3821         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3822  Flight3823  41862  ORD-DFW              0.4          27
3823  Flight3824  41674  ORD-DTW              1.8          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3822             0.333333               220       40700             8
3823             0.708333               115       20815             2

      Flight Year
3822         2014
3823         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3824  Flight3825  41990  ORD-PHX              2.9         193
3825  Flight3826  41785  ORD-DEN              1.8         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3824             0.604167               250       41250            12
3825             0.750000               300       55500             5

      Flight Year
3824         2014
3825         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3826  Flight3827  42173  ORD-IAH              1.6         160
3827  Flight3828  42004  ORD-DEN              2.7          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3826             0.291667               220       36300             6
3827             0.708333               300       49500            12

      Flight Year
3826         2015
3827         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3828  Flight3829  42285  ORD-SEA              2.3          93
3829  Flight3830  42092  ORD-MCO              2.4         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3828             0.791667               350       64750            10
3829             0.875000               250       41250             3

      Flight Year
3828         2015
3829         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3830  Flight3831  41852  ORD-MSP              1.7          47
3831  Flight3832  42256  ORD-CLT              1.5         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3830             0.708333             126.5     20872.5             8
3831             0.708333             125.0     20625.0             9

      Flight Year
3830         2014
3831         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3832  Flight3833  42239  ORD-DFW              2.8         137
3833  Flight3834  41995  ORD-SFO              4.5          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3832             0.708333               220       40700             8
3833             0.312500               525       97125            12

      Flight Year
3832         2015
3833         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3834  Flight3835  41989  ORD-LAS              0.5          12
3835  Flight3836  41686  ORD-MSP              1.7          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3834             0.354167               275       50875            12
3835             0.458333               115       20815             2

      Flight Year
3834         2014
3835         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3836  Flight3837  42020  ORD-DFW              3.0         103
3837  Flight3838  42049  ORD-CLT              2.3         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3836             0.625000               200       37000             1
3837             0.333333               125       20625             2

      Flight Year
3836         2015
3837         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3838  Flight3839  42027  ORD-DEN              2.6          56
3839  Flight3840  42233  ORD-SEA              1.8         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3838             0.312500               300       49500             1
3839             0.791667               385       71225             8

      Flight Year
3838         2015
3839         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3840  Flight3841  41803  ORD-IAH              1.9          17
3841  Flight3842  41952  ORD-CLT              2.8          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3840             0.833333               220       40700             6
3841             0.708333               125       20625            11

      Flight Year
3840         2014
3841         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3842  Flight3843  42205  ORD-CLT              1.4         200
3843  Flight3844  41914  ORD-ATL              9.6         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3842             0.458333             137.5     22687.5             7
3843             0.291667             200.0     37000.0            10

      Flight Year
3842         2015
3843         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3844  Flight3845  42094  ORD-LAX              5.1         147
3845  Flight3846  41838  ORD-SFO              3.3         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3844             0.333333             350.0     64750.0             3
3845             0.770833             412.5     76312.5             7

      Flight Year
3844         2015
3845         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3846  Flight3847  42349  ORD-DEN              2.6          80
3847  Flight3848  42189  ORD-PHX              1.1         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3846             0.791667               300       54300            12
3847             0.875000               275       50875             7

      Flight Year
3846         2015
3847         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3848  Flight3849  42111  ORD-LGA              1.9           9
3849  Flight3850  41695  ORD-DEN              1.1         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3848             0.375000               275       50875             4
3849             0.729167               300       49500             2

      Flight Year
3848         2015
3849         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3850  Flight3851  42037  ORD-CLT              1.2         152
3851  Flight3852  41793  ORD-MIA              1.5          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3850             0.895833               125       20625             2
3851             0.458333               330       61050             6

      Flight Year
3850         2015
3851         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3852  Flight3853  41940  ORD-LAX              3.4         104
3853  Flight3854  42019  ORD-SEA              2.2         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3852             0.833333               350       64750            10
3853             0.333333               350       57750             1

      Flight Year
3852         2014
3853         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3854  Flight3855  41944  ORD-DEN              1.9          20
3855  Flight3856  42159  ORD-EWR              2.9          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3854             0.708333             300.0     55500.0            11
3855             0.291667             247.5     45787.5             6

      Flight Year
3854         2014
3855         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3856  Flight3857  41892  ORD-JFK              1.9         190
3857  Flight3858  42016  ORD-LGA              2.5         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3856             0.500000               250       41250             9
3857             0.333333               275       45375             1

      Flight Year
3856         2014
3857         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3858  Flight3859  42249  ORD-LAX              4.2          77
3859  Flight3860  41755  ORD-DFW              2.0         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3858             0.291667               350       63350             9
3859             0.791667               200       37000             4

      Flight Year
3858         2015
3859         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3860  Flight3861  42337  ORD-LAX              9.6         105
3861  Flight3862  42161  ORD-ATL             12.8         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3860                0.875               525       97125            11
3861                0.500               220       40700             6

      Flight Year
3860         2015
3861         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3862  Flight3863  41680  ORD-SFO              1.6          91
3863  Flight3864  41865  ORD-SFO              2.6          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3862             0.750000             375.0     69375.0             2
3863             0.791667             412.5     74662.5             8

      Flight Year
3862         2014
3863         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3864  Flight3865  41868  ORD-SEA              3.6         154
3865  Flight3866  41785  ORD-ATL             11.2          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3864             0.291667               385       63525             8
3865             0.770833               200       37000             5

      Flight Year
3864         2014
3865         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3866  Flight3867  42169  ORD-JFK              1.5          54
3867  Flight3868  42237  ORD-DFW              2.3         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3866             0.770833               275       45375             6
3867             0.333333               220       40700             8

      Flight Year
3866         2015
3867         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3868  Flight3869  41938  ORD-DEN              1.3         161
3869  Flight3870  41805  ORD-LAS              1.7          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3868             0.291667             300.0     49500.0            10
3869             0.708333             302.5     55962.5             6

      Flight Year
3868         2014
3869         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3870  Flight3871  42046  ORD-IAH              2.6          97
3871  Flight3872  42202  ORD-JFK              2.7          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3870             0.708333               200       37000             2
3871             0.666667               275       49775             7

      Flight Year
3870         2015
3871         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3872  Flight3873  41712  ORD-LAX              5.0         198
3873  Flight3874  42099  ORD-PHX              1.2          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3872             0.770833               350       57750             3
3873             0.812500               250       45250             4

      Flight Year
3872         2014
3873         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3874  Flight3875  42359  ORD-BWI              2.8         144
3875  Flight3876  42289  ORD-JFK              1.9          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3874             0.708333               336       62160            12
3875             0.791667               250       41250            10

      Flight Year
3874         2015
3875         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3876  Flight3877  41897  ORD-DFW              2.8         197
3877  Flight3878  42014  ORD-CLT              0.9          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3876                0.750               200       33000             9
3877                0.625               125       23125             1

      Flight Year
3876         2014
3877         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3878  Flight3879  42088  ORD-MCO              1.1          78
3879  Flight3880  42109  ORD-DTW              2.2          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3878             0.791667               250       45250             3
3879             0.729167               115       18975             4

      Flight Year
3878         2015
3879         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3880  Flight3881  41682  ORD-LGA              0.1         133
3881  Flight3882  41956  ORD-CLT              1.9         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3880             0.541667               275       50875             2
3881             0.708333               125       20625            11

      Flight Year
3880         2014
3881         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3882  Flight3883  41937  ORD-DEN              3.0         203
3883  Flight3884  42204  ORD-SFO              2.5           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3882             0.291667             300.0     49500.0            10
3883             0.291667             412.5     76312.5             7

      Flight Year
3882         2014
3883         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3884  Flight3885  42363  ORD-DFW              1.3         137
3885  Flight3886  41726  ORD-ATL              8.0          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3884             0.458333               280       51800            12
3885             0.541667               200       33000             3

      Flight Year
3884         2015
3885         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3886  Flight3887  42196  ORD-MSP              2.0          53
3887  Flight3888  42008  ORD-MCO              1.4         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3886             0.833333             126.5     20872.5             7
3887             0.791667             250.0     46250.0             1

      Flight Year
3886         2015
3887         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3888  Flight3889  42324  ORD-ATL              7.5         163
3889  Flight3890  42196  ORD-SFO              1.4          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3888             0.375000             200.0     33000.0            11
3889             0.791667             412.5     74662.5             7

      Flight Year
3888         2015
3889         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3890  Flight3891  42336  ORD-BWI              6.5          36
3891  Flight3892  41789  ORD-BOS              2.3          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3890             0.312500               360       59400            11
3891             0.770833               300       49500             5

      Flight Year
3890         2015
3891         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3892  Flight3893  42144  ORD-LAX              4.3          75
3893  Flight3894  42335  ORD-LGA              6.5         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3892             0.791667             350.0     63350.0             5
3893             0.708333             412.5     76312.5            11

      Flight Year
3892         2015
3893         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3894  Flight3895  41854  ORD-DEN              2.5         140
3895  Flight3896  41846  ORD-LAS              1.6          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3894             0.354167             330.0     61050.0             8
3895             0.333333             302.5     55962.5             7

      Flight Year
3894         2014
3895         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3896  Flight3897  41986  ORD-CLT              1.4         151
3897  Flight3898  41948  ORD-SEA              2.5         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3896             0.729167               125       23125            12
3897             0.333333               350       64750            11

      Flight Year
3896         2014
3897         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3898  Flight3899  41897  ORD-ATL              8.7         175
3899  Flight3900  42191  ORD-IAH              2.7         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3898             0.645833               200       33000             9
3899             0.833333               220       40700             7

      Flight Year
3898         2014
3899         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3900  Flight3901  41879  ORD-LAS              2.6         131
3901  Flight3902  42257  ORD-SEA              2.0         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3900             0.416667             302.5     55962.5             8
3901             0.770833             350.0     57750.0             9

      Flight Year
3900         2014
3901         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3902  Flight3903  41683  ORD-BWI              2.8         166
3903  Flight3904  41873  ORD-MIA              2.0         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3902             0.854167               240       39600             2
3903             0.708333               330       61050             8

      Flight Year
3902         2014
3903         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3904  Flight3905  41834  ORD-MCO              1.8         179
3905  Flight3906  42231  ORD-SEA              1.9         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3904             0.770833               275       45375             7
3905             0.583333               385       63525             8

      Flight Year
3904         2014
3905         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3906  Flight3907  42331  ORD-DFW              6.5         155
3907  Flight3908  41793  ORD-SLC              2.2          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3906             0.729167               300       49500            11
3907             0.354167               319       57739             6

      Flight Year
3906         2015
3907         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3908  Flight3909  41959  ORD-MCO                2         129
3909  Flight3910  42331  ORD-MIA                8          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3908             0.395833               250       46250            11
3909             0.520833               450       83250            11

      Flight Year
3908         2014
3909         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3910  Flight3911  42326  ORD-DEN              1.3          72
3911  Flight3912  42199  ORD-CLT              1.5          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3910             0.416667             300.0     54300.0            11
3911             0.458333             137.5     22687.5             7

      Flight Year
3910         2015
3911         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3912  Flight3913  42333  ORD-SLC              4.6         134
3913  Flight3914  42202  ORD-JFK              0.6          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3912             0.708333               435       80475            11
3913             0.875000               275       45375             7

      Flight Year
3912         2015
3913         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3914  Flight3915  42025  ORD-MSP              1.5         149
3915  Flight3916  41742  ORD-BOS              0.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3914             0.770833               115       21275             1
3915             0.750000               300       49500             4

      Flight Year
3914         2015
3915         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3916  Flight3917  42041  ORD-PHX              2.2          40
3917  Flight3918  41759  ORD-MIA              2.2         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3916             0.333333               250       41250             2
3917             0.791667               300       49500             4

      Flight Year
3916         2015
3917         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3918  Flight3919  42169  ORD-DEN              3.7         108
3919  Flight3920  42351  ORD-PHX              2.2          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3918             0.333333               330       61050             6
3919             0.750000               250       41250            12

      Flight Year
3918         2015
3919         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3920  Flight3921  42049  ORD-EWR              1.6         208
3921  Flight3922  42010  ORD-MIA              3.6         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3920             0.750000               225       37125             2
3921             0.770833               300       55500             1

      Flight Year
3920         2015
3921         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3922  Flight3923  42084  ORD-LGA              3.0         149
3923  Flight3924  42277  ORD-LAX              2.6         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3922             0.750000               275       50875             3
3923             0.791667               350       64750             9

      Flight Year
3922         2015
3923         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3924  Flight3925  42022  ORD-LAX              3.5         174
3925  Flight3926  42077  ORD-MIA              0.9          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3924             0.333333               350       57750             1
3925             0.500000               300       54300             3

      Flight Year
3924         2015
3925         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3926  Flight3927  41891  ORD-BOS              1.7          87
3927  Flight3928  42230  ORD-DEN              1.9         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3926             0.791667               300       54300             9
3927             0.583333               330       61050             8

      Flight Year
3926         2014
3927         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3928  Flight3929  41855  ORD-CLT              1.2          62
3929  Flight3930  41934  ORD-BOS              2.3         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3928               0.7500             137.5     22687.5             8
3929               0.8125             300.0     49500.0            10

      Flight Year
3928         2014
3929         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3930  Flight3931  41970  ORD-JFK              6.3         210
3931  Flight3932  41853  ORD-SFO              1.7          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3930             0.583333             375.0     61875.0            11
3931             0.708333             412.5     74662.5             8

      Flight Year
3930         2014
3931         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3932  Flight3933  42335  ORD-IAH              6.5          99
3933  Flight3934  42009  ORD-IAD              2.8         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3932             0.729167               300       55500            11
3933             0.541667               300       55500             1

      Flight Year
3932         2015
3933         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3934  Flight3935  41913  ORD-DEN              0.7          87
3935  Flight3936  41736  ORD-BOS              2.3         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3934             0.708333               300       54300            10
3935             0.312500               300       49500             4

      Flight Year
3934         2014
3935         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3936  Flight3937  42043  ORD-CLT              1.7         161
3937  Flight3938  42257  ORD-ATL              8.4         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3936             0.708333               125       20625             2
3937             0.458333               200       33000             9

      Flight Year
3936         2015
3937         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3938  Flight3939  42189  ORD-ATL             11.0         190
3939  Flight3940  41845  ORD-JFK              1.8         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3938             0.291667               220       36300             7
3939             0.708333               275       45375             7

      Flight Year
3938         2015
3939         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3940  Flight3941  42047  ORD-MIA              3.5          72
3941  Flight3942  42319  ORD-LAX              2.8         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3940             0.791667               300       54300             2
3941             0.770833               350       57750            11

      Flight Year
3940         2015
3941         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3942  Flight3943  41854  ORD-MIA              2.9         208
3943  Flight3944  41803  ORD-FLL              2.3         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3942             0.875000               330       54450             8
3943             0.833333               330       54450             6

      Flight Year
3942         2014
3943         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3944  Flight3945  42124  ORD-MCO              1.8           2
3945  Flight3946  41843  ORD-LGA              1.8          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3944             0.437500             250.0     46250.0             4
3945             0.791667             302.5     54752.5             7

      Flight Year
3944         2015
3945         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3946  Flight3947  42315  ORD-MCO              1.7          11
3947  Flight3948  42180  ORD-SEA              2.4         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3946             0.333333               250       46250            11
3947             0.541667               385       71225             6

      Flight Year
3946         2015
3947         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3948  Flight3949  41963  ORD-JFK              1.4          95
3949  Flight3950  42060  ORD-JFK              2.2         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3948             0.312500               250       46250            11
3949             0.708333               250       41250             2

      Flight Year
3948         2014
3949         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3950  Flight3951  42099  ORD-JFK              2.3         204
3951  Flight3952  41878  ORD-LAS              2.2          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3950             0.750000             250.0     41250.0             4
3951             0.833333             302.5     49912.5             8

      Flight Year
3950         2015
3951         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3952  Flight3953  41816  ORD-LAS              2.5          53
3953  Flight3954  41897  ORD-JFK              2.3         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3952             0.750000             302.5     49912.5             6
3953             0.770833             250.0     46250.0             9

      Flight Year
3952         2014
3953         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3954  Flight3955  41896  ORD-JFK              1.5         108
3955  Flight3956  42215  ORD-MCO              2.4          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3954             0.458333               250       46250             9
3955             0.291667               275       50875             7

      Flight Year
3954         2014
3955         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3956  Flight3957  42155  ORD-CLT              2.0         138
3957  Flight3958  42331  ORD-DFW              3.8         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3956             0.666667               125       23125             5
3957             0.854167               300       49500            11

      Flight Year
3956         2015
3957         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3958  Flight3959  41913  ORD-ATL              8.5          98
3959  Flight3960  41902  ORD-MCO              2.1          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3958             0.875000               200       37000            10
3959             0.708333               250       41250             9

      Flight Year
3958         2014
3959         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3960  Flight3961  41756  ORD-LAX              4.4         134
3961  Flight3962  41741  ORD-PHX              1.3          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3960             0.833333               350       64750             4
3961             0.875000               250       45250             4

      Flight Year
3960         2014
3961         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3962  Flight3963  41837  ORD-SFO              2.3          37
3963  Flight3964  41676  ORD-DEN              1.7         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3962               0.6250             412.5     68062.5             7
3963               0.8125             300.0     49500.0             2

      Flight Year
3962         2014
3963         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3964  Flight3965  41728  ORD-CLT              1.1          58
3965  Flight3966  42208  ORD-LGA              1.3         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3964             0.833333             125.0     20625.0             3
3965             0.750000             302.5     49912.5             7

      Flight Year
3964         2014
3965         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3966  Flight3967  42136  ORD-LAS              2.3         132
3967  Flight3968  42026  ORD-LAS              2.7          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3966             0.291667               275       50875             5
3967             0.666667               275       50875             1

      Flight Year
3966         2015
3967         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3968  Flight3969  41902  ORD-MSP              1.0         120
3969  Flight3970  41804  ORD-MSP              1.5         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3968             0.291667             115.0     21275.0             9
3969             0.291667             126.5     20872.5             6

      Flight Year
3968         2014
3969         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3970  Flight3971  41727  ORD-MCO              2.2          93
3971  Flight3972  42328  ORD-ATL              5.8         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3970             0.833333               250       46250             3
3971             0.791667               200       37000            11

      Flight Year
3970         2014
3971         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3972  Flight3973  42021  ORD-JFK              2.7         165
3973  Flight3974  41642  ORD-DEN              2.5         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3972             0.375000               250       41250             1
3973             0.729167               300       55500             1

      Flight Year
3972         2015
3973         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3974  Flight3975  41997  ORD-DFW              4.7         103
3975  Flight3976  41916  ORD-DEN              2.5          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3974             0.458333               280       51800            12
3975             0.625000               300       49500            10

      Flight Year
3974         2014
3975         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3976  Flight3977  41988  ORD-JFK              2.4         177
3977  Flight3978  42210  ORD-DFW              2.7         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3976             0.791667               250       41250            12
3977             0.833333               220       40700             7

      Flight Year
3976         2014
3977         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3978  Flight3979  42152  ORD-ATL             11.8         150
3979  Flight3980  42149  ORD-MSP              1.4         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3978             0.791667               200       37000             5
3979             0.333333               115       21275             5

      Flight Year
3978         2015
3979         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3980  Flight3981  42113  ORD-DEN              1.6         121
3981  Flight3982  41841  ORD-SFO              1.9         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3980             0.583333             300.0     55500.0             4
3981             0.812500             412.5     76312.5             7

      Flight Year
3980         2015
3981         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3982  Flight3983  42192  ORD-EWR              1.4          93
3983  Flight3984  41758  ORD-LAX              3.3          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3982             0.333333             247.5     45787.5             7
3983             0.750000             350.0     64750.0             4

      Flight Year
3982         2015
3983         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3984  Flight3985  42147  ORD-EWR              2.0         108
3985  Flight3986  41864  ORD-IAH              2.1         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3984             0.625000               225       41625             5
3985             0.833333               220       36300             8

      Flight Year
3984         2015
3985         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3986  Flight3987  41835  ORD-DFW              1.3         165
3987  Flight3988  42184  ORD-EWR              2.3         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3986             0.791667             220.0     36300.0             7
3987             0.750000             247.5     40837.5             6

      Flight Year
3986         2014
3987         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3988  Flight3989  42364  ORD-SFO              3.0         193
3989  Flight3990  41993  ORD-MIA              2.5           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3988               0.5625               525       86625            12
3989               0.5000               300       55500            12

      Flight Year
3988         2015
3989         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3990  Flight3991  41649  ORD-MIA              3.1           7
3991  Flight3992  41997  ORD-MSP              2.7          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3990             0.729167               300       55500             1
3991             0.812500               161       26565            12

      Flight Year
3990         2014
3991         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3992  Flight3993  42367  ORD-LAS              2.1         163
3993  Flight3994  41822  ORD-SEA              2.8         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3992             0.812500               275       45375            12
3993             0.645833               385       71225             7

      Flight Year
3992         2015
3993         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3994  Flight3995  41982  ORD-LAX              3.6          27
3995  Flight3996  41726  ORD-ATL              7.3          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3994             0.416667               350       64750            12
3995             0.312500               200       37000             3

      Flight Year
3994         2014
3995         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3996  Flight3997  42048  ORD-DEN              2.8          47
3997  Flight3998  41944  ORD-DFW              2.5          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3996             0.625000               300       49500             2
3997             0.854167               200       36200            11

      Flight Year
3996         2015
3997         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
3998  Flight3999  41985  ORD-SFO              1.5         154
3999  Flight4000  42337  ORD-LAS              5.7          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
3998             0.770833             375.0     61875.0            12
3999             0.291667             412.5     74662.5            11

      Flight Year
3998         2014
3999         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4000  Flight4001  41872  ORD-FLL              1.9         103
4001  Flight4002  41656  ORD-PHX              1.6         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4000             0.708333               330       61050             8
4001             0.333333               250       41250             1

      Flight Year
4000         2014
4001         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4002  Flight4003  42332  ORD-BOS              6.3          69
4003  Flight4004  41776  ORD-ATL              6.2         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4002             0.708333               450       81450            11
4003             0.312500               200       37000             5

      Flight Year
4002         2015
4003         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4004  Flight4005  42047  ORD-BWI              2.1         179
4005  Flight4006  41663  ORD-CLT              1.5         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4004             0.791667               240       39600             2
4005             0.750000               125       23125             1

      Flight Year
4004         2015
4005         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4006  Flight4007  41854  ORD-MIA              2.8         185
4007  Flight4008  41827  ORD-IAH              1.6          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4006             0.750000               330       54450             8
4007             0.541667               220       40700             7

      Flight Year
4006         2014
4007         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4008  Flight4009  41834  ORD-MIA              3.0         130
4009  Flight4010  41768  ORD-IAD              2.1         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4008             0.354167               330       61050             7
4009             0.458333               300       55500             5

      Flight Year
4008         2014
4009         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4010  Flight4011  42140  ORD-MIA              1.2         197
4011  Flight4012  41993  ORD-BOS              1.9         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4010             0.333333               300       49500             5
4011             0.354167               300       49500            12

      Flight Year
4010         2015
4011         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4012  Flight4013  42062  ORD-CLT              2.6         199
4013  Flight4014  41973  ORD-DTW              6.3          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4012             0.500000             125.0     20625.0             2
4013             0.791667             172.5     28462.5            11

      Flight Year
4012         2015
4013         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4014  Flight4015  41980  ORD-EWR              2.4         176
4015  Flight4016  41912  ORD-MCO              2.7          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4014             0.729167               225       37125            12
4015             0.291667               250       46250             9

      Flight Year
4014         2014
4015         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4016  Flight4017  41871  ORD-SFO              2.5           8
4017  Flight4018  42261  ORD-BWI              2.2         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4016             0.708333             412.5     76312.5             8
4017             0.291667             240.0     39600.0             9

      Flight Year
4016         2014
4017         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4018  Flight4019  42097  ORD-ATL              8.1          31
4019  Flight4020  41843  ORD-LAS              2.1          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4018             0.458333             200.0     37000.0             4
4019             0.291667             302.5     54752.5             7

      Flight Year
4018         2015
4019         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4020  Flight4021  42331  ORD-DFW              6.3          66
4021  Flight4022  42121  ORD-ATL              8.5         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4020             0.750000               300       54300            11
4021             0.333333               200       37000             4

      Flight Year
4020         2015
4021         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4022  Flight4023  41996  ORD-MCO              4.0           5
4023  Flight4024  41877  ORD-LGA              2.3         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4022             0.291667             350.0     64750.0            12
4023             0.729167             302.5     55962.5             8

      Flight Year
4022         2014
4023         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4024  Flight4025  41959  ORD-EWR              2.2          60
4025  Flight4026  42017  ORD-LGA              3.0         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4024             0.291667               225       37125            11
4025             0.333333               275       45375             1

      Flight Year
4024         2014
4025         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4026  Flight4027  41791  ORD-MIA              1.2         149
4027  Flight4028  42291  ORD-LAS              1.0         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4026             0.333333               330       61050             6
4027             0.729167               275       45375            10

      Flight Year
4026         2014
4027         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4028  Flight4029  41924  ORD-MIA              1.2          67
4029  Flight4030  42063  ORD-SEA              3.1          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4028             0.458333               300       54300            10
4029             0.312500               350       57750             2

      Flight Year
4028         2014
4029         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4030  Flight4031  41995  ORD-EWR              5.8          82
4031  Flight4032  41721  ORD-IAD              2.5          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4030               0.5625               315       57015            12
4031               0.7500               300       49500             3

      Flight Year
4030         2014
4031         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4032  Flight4033  42070  ORD-DEN              1.6          18
4033  Flight4034  42230  ORD-SFO              2.0          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4032             0.770833             300.0     55500.0             3
4033             0.500000             412.5     76312.5             8

      Flight Year
4032         2015
4033         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4034  Flight4035  42243  ORD-LGA              1.8         184
4035  Flight4036  42265  ORD-IAH              2.3         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4034             0.666667             302.5     49912.5             8
4035             0.812500             200.0     33000.0             9

      Flight Year
4034         2015
4035         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4036  Flight4037  42359  ORD-DTW              3.8           2
4037  Flight4038  41761  ORD-DEN              2.4          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4036             0.833333               161       29785            12
4037             0.708333               300       49500             5

      Flight Year
4036         2015
4037         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4038  Flight4039  42300  ORD-DTW              1.2         188
4039  Flight4040  41782  ORD-SEA              1.8         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4038             0.708333               115       18975            10
4039             0.395833               350       64750             5

      Flight Year
4038         2015
4039         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4040  Flight4041  42230  ORD-LAS              2.5         206
4041  Flight4042  42229  ORD-SEA              1.9          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4040             0.791667             302.5     49912.5             8
4041             0.291667             385.0     69685.0             8

      Flight Year
4040         2015
4041         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4042  Flight4043  41825  ORD-ATL              9.5         140
4043  Flight4044  42041  ORD-SEA              2.2         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4042               0.8125               220       40700             7
4043               0.6875               350       64750             2

      Flight Year
4042         2014
4043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4044  Flight4045  41795  ORD-DFW              2.5          78
4045  Flight4046  41802  ORD-IAH              2.3          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4044             0.645833               220       39820             6
4045             0.375000               220       40700             6

      Flight Year
4044         2014
4045         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4046  Flight4047  42029  ORD-SFO              1.9         179
4047  Flight4048  41938  ORD-DFW              1.2          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4046             0.583333               375       61875             1
4047             0.812500               200       37000            10

      Flight Year
4046         2015
4047         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4048  Flight4049  41910  ORD-BOS              1.9           1
4049  Flight4050  41742  ORD-IAH              2.5         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4048             0.770833               300       55500             9
4049             0.708333               200       37000             4

      Flight Year
4048         2014
4049         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4050  Flight4051  42134  ORD-IAH              1.5         117
4051  Flight4052  41858  ORD-LAX              5.6         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4050             0.708333               200       37000             5
4051             0.333333               385       63525             8

      Flight Year
4050         2015
4051         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4052  Flight4053  42024  ORD-EWR              2.8         185
4053  Flight4054  42329  ORD-LAX              4.5         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4052             0.354167               225       37125             1
4053             0.791667               350       64750            11

      Flight Year
4052         2015
4053         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4054  Flight4055  41710  ORD-LGA              1.1         193
4055  Flight4056  42208  ORD-EWR              1.6         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4054             0.708333             275.0     45375.0             3
4055             0.791667             247.5     40837.5             7

      Flight Year
4054         2014
4055         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4056  Flight4057  42196  ORD-SEA              2.2         177
4057  Flight4058  42357  ORD-IAD              1.9         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4056             0.895833               385       63525             7
4057             0.625000               300       49500            12

      Flight Year
4056         2015
4057         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4058  Flight4059  42028  ORD-ATL              5.7         208
4059  Flight4060  42104  ORD-ATL              8.4          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4058             0.770833               200       33000             1
4059             0.458333               200       36200             4

      Flight Year
4058         2015
4059         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4060  Flight4061  42061  ORD-MIA              2.0         159
4061  Flight4062  42311  ORD-JFK              1.2         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4060             0.291667               300       49500             2
4061             0.291667               250       46250            11

      Flight Year
4060         2015
4061         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4062  Flight4063  41812  ORD-LGA              2.4         187
4063  Flight4064  41807  ORD-LGA              1.2          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4062             0.833333             302.5     49912.5             6
4063             0.791667             302.5     54752.5             6

      Flight Year
4062         2014
4063         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4064  Flight4065  41667  ORD-MIA              2.6         195
4065  Flight4066  41708  ORD-EWR              2.4         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4064             0.500000               300       49500             1
4065             0.791667               225       37125             3

      Flight Year
4064         2014
4065         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4066  Flight4067  42312  ORD-JFK              2.3         132
4067  Flight4068  41789  ORD-SLC              2.7         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4066             0.291667               250       46250            11
4067             0.750000               290       53650             5

      Flight Year
4066         2015
4067         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4068  Flight4069  41971  ORD-IAH              4.6         102
4069  Flight4070  42237  ORD-ATL             10.3           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4068             0.791667               300       55500            11
4069             0.770833               220       40700             8

      Flight Year
4068         2014
4069         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4070  Flight4071  41890  ORD-SFO              2.8         189
4071  Flight4072  42361  ORD-PHL              3.9         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4070             0.437500               375       61875             9
4071             0.708333               385       63525            12

      Flight Year
4070         2014
4071         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4072  Flight4073  41835  ORD-JFK              2.7         168
4073  Flight4074  42334  ORD-ATL             18.1         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4072             0.708333               275       45375             7
4073             0.416667               300       49500            11

      Flight Year
4072         2014
4073         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4074  Flight4075  42213  ORD-SFO              2.2         144
4075  Flight4076  41662  ORD-ATL              7.9         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4074             0.854167             412.5     76312.5             7
4075             0.500000             200.0     33000.0             1

      Flight Year
4074         2015
4075         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4076  Flight4077  42203  ORD-LGA              0.9          90
4077  Flight4078  42198  ORD-DTW              1.3          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4076             0.375000             302.5     54752.5             7
4077             0.333333             126.5     23402.5             7

      Flight Year
4076         2015
4077         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4078  Flight4079  42278  ORD-ATL              9.9          34
4079  Flight4080  42092  ORD-SEA              3.1         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4078             0.458333               200       37000            10
4079             0.708333               350       64750             3

      Flight Year
4078         2015
4079         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4080  Flight4081  42234  ORD-ATL              7.6          55
4081  Flight4082  41836  ORD-DTW              1.9         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4080             0.291667             220.0     36300.0             8
4081             0.708333             126.5     23402.5             7

      Flight Year
4080         2015
4081         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4082  Flight4083  41692  ORD-CLT              0.5          39
4083  Flight4084  41836  ORD-CLT              1.6         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4082             0.583333             125.0     20625.0             2
4083             0.541667             137.5     22687.5             7

      Flight Year
4082         2014
4083         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4084  Flight4085  41674  ORD-CLT              1.8          50
4085  Flight4086  42138  ORD-DFW              2.2         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4084             0.708333               125       20625             2
4085             0.666667               200       37000             5

      Flight Year
4084         2014
4085         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4086  Flight4087  41726  ORD-IAD              2.8          66
4087  Flight4088  42050  ORD-LAX              4.7         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4086             0.708333               300       54300             3
4087             0.791667               350       57750             2

      Flight Year
4086         2014
4087         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4088  Flight4089  42103  ORD-JFK              1.4         102
4089  Flight4090  41830  ORD-CLT              2.2           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4088             0.333333             250.0     46250.0             4
4089             0.312500             137.5     25437.5             7

      Flight Year
4088         2015
4089         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4090  Flight4091  42241  ORD-DFW              2.9         102
4091  Flight4092  42245  ORD-FLL              1.7          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4090             0.791667               220       40700             8
4091             0.791667               330       54450             8

      Flight Year
4090         2015
4091         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4092  Flight4093  42126  ORD-BWI              2.4         200
4093  Flight4094  42315  ORD-MIA              2.4          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4092             0.791667               240       39600             5
4093             0.791667               300       54300            11

      Flight Year
4092         2015
4093         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4094  Flight4095  42366  ORD-DEN              3.3          47
4095  Flight4096  41809  ORD-EWR              1.5          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4094             0.750000             300.0     49500.0            12
4095             0.458333             247.5     45787.5             6

      Flight Year
4094         2015
4095         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4096  Flight4097  41916  ORD-LAX              4.7         135
4097  Flight4098  41733  ORD-ATL             10.0          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4096             0.875000               350       64750            10
4097             0.291667               200       36200             4

      Flight Year
4096         2014
4097         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4098  Flight4099  42100  ORD-JFK              3.0         119
4099  Flight4100  42184  ORD-MIA              2.8         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4098             0.666667               250       46250             4
4099             0.770833               330       61050             6

      Flight Year
4098         2015
4099         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4100  Flight4101  41692  ORD-SLC              2.5         171
4101  Flight4102  41875  ORD-DEN              3.0         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4100             0.312500               290       47850             2
4101             0.708333               330       61050             8

      Flight Year
4100         2014
4101         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4102  Flight4103  42099  ORD-IAH              1.7          80
4103  Flight4104  41905  ORD-DFW              4.0          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4102             0.791667               200       36200             4
4103             0.833333               200       36200             9

      Flight Year
4102         2015
4103         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4104  Flight4105  42327  ORD-PHX              1.2         174
4105  Flight4106  41898  ORD-LAS              1.7          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4104             0.354167               250       41250            11
4105             0.833333               275       50875             9

      Flight Year
4104         2015
4105         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4106  Flight4107  42153  ORD-DFW              2.5          37
4107  Flight4108  41799  ORD-DFW              2.1          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4106             0.833333               200       33000             5
4107             0.708333               220       39820             6

      Flight Year
4106         2015
4107         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4108  Flight4109  42256  ORD-DEN              1.8         192
4109  Flight4110  42236  ORD-CLT              2.3          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4108             0.729167             300.0     49500.0             9
4109             0.750000             137.5     24887.5             8

      Flight Year
4108         2015
4109         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4110  Flight4111  42103  ORD-ATL              8.8          96
4111  Flight4112  41861  ORD-ATL              9.6         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4110             0.333333               200       37000             4
4111             0.291667               220       40700             8

      Flight Year
4110         2015
4111         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4112  Flight4113  42266  ORD-LAS              2.9          86
4113  Flight4114  41998  ORD-BOS              5.8          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4112             0.791667               275       49775             9
4113             0.833333               420       77700            12

      Flight Year
4112         2015
4113         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4114  Flight4115  42220  ORD-DFW              2.0         138
4115  Flight4116  42261  ORD-MCO              2.6          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4114             0.520833               220       40700             8
4115             0.291667               250       41250             9

      Flight Year
4114         2015
4115         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4116  Flight4117  42003  ORD-DTW              2.7          41
4117  Flight4118  42236  ORD-EWR              1.9         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4116             0.354167             115.0     18975.0            12
4117             0.333333             247.5     45787.5             8

      Flight Year
4116         2014
4117         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4118  Flight4119  42334  ORD-LAS              7.0          47
4119  Flight4120  42061  ORD-FLL              2.5          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4118             0.583333             412.5     68062.5            11
4119             0.416667             300.0     49500.0             2

      Flight Year
4118         2015
4119         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4120  Flight4121  42363  ORD-JFK              4.6           9
4121  Flight4122  42080  ORD-DTW              2.0          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4120             0.791667               350       64750            12
4121             0.812500               115       18975             3

      Flight Year
4120         2015
4121         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4122  Flight4123  42333  ORD-LAS              5.2         128
4123  Flight4124  41908  ORD-IAH              2.7         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4122             0.729167             412.5     76312.5            11
4123             0.791667             200.0     37000.0             9

      Flight Year
4122         2015
4123         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4124  Flight4125  42221  ORD-JFK              0.6         185
4125  Flight4126  41853  ORD-LAX              3.6         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4124             0.583333               275       45375             8
4125             0.375000               385       63525             8

      Flight Year
4124         2015
4125         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4126  Flight4127  41956  ORD-IAH              2.0         180
4127  Flight4128  41922  ORD-CLT              1.3           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4126             0.333333               200       33000            11
4127             0.770833               125       23125            10

      Flight Year
4126         2014
4127         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4128  Flight4129  42337  ORD-LAX             10.1         170
4129  Flight4130  42362  ORD-MCO              3.2         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4128             0.750000               525       86625            11
4129             0.291667               350       57750            12

      Flight Year
4128         2015
4129         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4130  Flight4131  41642  ORD-JFK              2.2         118
4131  Flight4132  41961  ORD-SEA              2.2         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4130             0.666667               250       46250             1
4131             0.312500               350       57750            11

      Flight Year
4130         2014
4131         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4132  Flight4133  41885  ORD-DEN              2.3         199
4133  Flight4134  42334  ORD-LAX             10.8         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4132             0.750000               300       49500             9
4133             0.833333               525       97125            11

      Flight Year
4132         2014
4133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4134  Flight4135  42309  ORD-ATL              8.3          57
4135  Flight4136  42017  ORD-CLT              1.9          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4134             0.791667               200       33000            11
4135             0.333333               125       23125             1

      Flight Year
4134         2015
4135         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4136  Flight4137  42021  ORD-DEN              2.5         110
4137  Flight4138  41719  ORD-SEA              1.4         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4136             0.666667               300       55500             1
4137             0.750000               350       57750             3

      Flight Year
4136         2015
4137         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4138  Flight4139  42283  ORD-EWR              3.2          20
4139  Flight4140  41785  ORD-IAH              1.2         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4138                 0.75               225       41625            10
4139                 0.75               200       37000             5

      Flight Year
4138         2015
4139         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4140  Flight4141  42208  ORD-MIA              2.4          28
4141  Flight4142  41661  ORD-SFO              2.3          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4140             0.500000               330       61050             7
4141             0.833333               375       69375             1

      Flight Year
4140         2015
4141         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4142  Flight4143  41945  ORD-JFK              1.6          20
4143  Flight4144  42219  ORD-LAS              2.1         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4142             0.791667             250.0     46250.0            11
4143             0.291667             302.5     49912.5             8

      Flight Year
4142         2014
4143         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4144  Flight4145  42336  ORD-DTW              8.3         121
4145  Flight4146  42269  ORD-DFW              3.5         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4144             0.333333             172.5     31912.5            11
4145             0.770833             200.0     37000.0             9

      Flight Year
4144         2015
4145         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4146  Flight4147  41995  ORD-SEA              5.3         187
4147  Flight4148  41832  ORD-MIA              1.8         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4146             0.708333               490       80850            12
4147             0.291667               330       61050             7

      Flight Year
4146         2014
4147         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4148  Flight4149  41874  ORD-ATL              9.6         106
4149  Flight4150  41974  ORD-MIA              2.1          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4148             0.333333               220       40700             8
4149             0.791667               300       49500            12

      Flight Year
4148         2014
4149         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4150  Flight4151  42160  ORD-SFO              1.2         171
4151  Flight4152  42128  ORD-LAX              3.7          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4150             0.875000             412.5     68062.5             6
4151             0.395833             350.0     64750.0             5

      Flight Year
4150         2015
4151         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4152  Flight4153  42107  ORD-SFO              3.1          98
4153  Flight4154  41828  ORD-PHL              1.8          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4152             0.750000             375.0     69375.0             4
4153             0.541667             302.5     49912.5             7

      Flight Year
4152         2015
4153         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4154  Flight4155  42116  ORD-PHX              2.7          90
4155  Flight4156  41796  ORD-PHX              1.5         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4154             0.791667               250       45250             4
4155             0.812500               275       45375             6

      Flight Year
4154         2015
4155         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4156  Flight4157  41955  ORD-FLL              1.8         188
4157  Flight4158  42122  ORD-JFK              1.4         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4156             0.354167               300       49500            11
4157             0.750000               250       41250             4

      Flight Year
4156         2014
4157         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4158  Flight4159  42182  ORD-PHL              1.7         166
4159  Flight4160  41691  ORD-ATL              7.4          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4158             0.854167             302.5     49912.5             6
4159             0.458333             200.0     33000.0             2

      Flight Year
4158         2015
4159         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4160  Flight4161  41699  ORD-JFK              1.5          79
4161  Flight4162  41640  ORD-DFW              2.3         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4160             0.770833               250       45250             3
4161             0.750000               200       37000             1

      Flight Year
4160         2014
4161         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4162  Flight4163  41975  ORD-JFK              1.9         131
4163  Flight4164  41950  ORD-PHL              1.7          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4162             0.708333               250       46250            12
4163             0.750000               275       45375            11

      Flight Year
4162         2014
4163         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4164  Flight4165  41873  ORD-DEN              4.4          63
4165  Flight4166  42368  ORD-DEN              1.5         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4164             0.583333               330       59730             8
4165             0.666667               300       49500            12

      Flight Year
4164         2014
4165         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4166  Flight4167  41913  ORD-DFW              2.0         162
4167  Flight4168  42223  ORD-SFO              3.6         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4166             0.791667             200.0     33000.0            10
4167             0.291667             412.5     68062.5             8

      Flight Year
4166         2014
4167         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4168  Flight4169  41688  ORD-MCO              3.1         116
4169  Flight4170  42318  ORD-IAH              2.6          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4168             0.312500               250       46250             2
4169             0.708333               200       37000            11

      Flight Year
4168         2014
4169         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4170  Flight4171  42090  ORD-DFW              1.9          71
4171  Flight4172  42112  ORD-IAD              1.0          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4170             0.354167               200       36200             3
4171             0.416667               300       49500             4

      Flight Year
4170         2015
4171         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4172  Flight4173  42323  ORD-LGA              3.3          45
4173  Flight4174  41839  ORD-LAS              2.5          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4172             0.791667             275.0     45375.0            11
4173             0.354167             302.5     55962.5             7

      Flight Year
4172         2015
4173         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4174  Flight4175  42168  ORD-DTW              2.3         208
4175  Flight4176  42235  ORD-ATL             12.4         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4174             0.291667             126.5     20872.5             6
4175             0.833333             220.0     40700.0             8

      Flight Year
4174         2015
4175         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4176  Flight4177  42119  ORD-LAX              4.2         176
4177  Flight4178  42339  ORD-SEA              3.2         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4176             0.770833               350       57750             4
4177             0.833333               350       64750            12

      Flight Year
4176         2015
4177         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4178  Flight4179  41676  ORD-LAX              4.3         207
4179  Flight4180  41670  ORD-MCO              1.7          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4178             0.708333               350       57750             2
4179             0.687500               250       41250             1

      Flight Year
4178         2014
4179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4180  Flight4181  42199  ORD-SEA              1.6         150
4181  Flight4182  42045  ORD-SFO              3.1         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4180             0.770833               385       71225             7
4181             0.750000               375       69375             2

      Flight Year
4180         2015
4181         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4182  Flight4183  41938  ORD-FLL              1.4          34
4183  Flight4184  42339  ORD-DTW              1.1          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4182             0.312500               300       55500            10
4183             0.833333               115       18975            12

      Flight Year
4182         2014
4183         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4184  Flight4185  42043  ORD-LGA              2.4         132
4185  Flight4186  42040  ORD-SFO              1.9          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4184             0.666667               275       50875             2
4185             0.416667               375       61875             2

      Flight Year
4184         2015
4185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4186  Flight4187  42099  ORD-SEA              1.8          68
4187  Flight4188  42198  ORD-MCO              1.5         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4186             0.458333               350       63350             4
4187             0.791667               275       45375             7

      Flight Year
4186         2015
4187         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4188  Flight4189  42000  ORD-SFO              3.8          87
4189  Flight4190  41824  ORD-MCO              2.4          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4188             0.770833               525       95025            12
4189             0.333333               275       49775             7

      Flight Year
4188         2014
4189         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4190  Flight4191  42138  ORD-EWR              0.7           8
4191  Flight4192  41910  ORD-SFO              3.5         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4190             0.770833               225       41625             5
4191             0.312500               375       61875             9

      Flight Year
4190         2015
4191         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4192  Flight4193  42324  ORD-DTW              3.0         139
4193  Flight4194  41867  ORD-EWR              2.3         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4192             0.291667             115.0     21275.0            11
4193             0.666667             247.5     40837.5             8

      Flight Year
4192         2015
4193         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4194  Flight4195  41679  ORD-BOS              1.7         141
4195  Flight4196  41955  ORD-MCO              2.6          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4194                 0.75               300       55500             2
4195                 0.50               250       46250            11

      Flight Year
4194         2014
4195         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4196  Flight4197  42216  ORD-DFW              1.6           3
4197  Flight4198  42212  ORD-JFK              3.0         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4196               0.8125               220       40700             7
4197               0.8750               275       50875             7

      Flight Year
4196         2015
4197         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4198  Flight4199  42164  ORD-JFK              2.8         170
4199  Flight4200  42142  ORD-MIA              2.1         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4198             0.500000               275       45375             6
4199             0.708333               300       49500             5

      Flight Year
4198         2015
4199         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4200  Flight4201  42344  ORD-SEA              1.3         103
4201  Flight4202  42323  ORD-MIA              2.8          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4200             0.291667               350       64750            12
4201             0.291667               300       55500            11

      Flight Year
4200         2015
4201         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4202  Flight4203  42333  ORD-JFK              6.2          96
4203  Flight4204  42254  ORD-LAS              2.5         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4202             0.750000               375       69375            11
4203             0.416667               275       45375             9

      Flight Year
4202         2015
4203         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4204  Flight4205  42115  ORD-ATL              7.4         101
4205  Flight4206  42007  ORD-MSP              2.3          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4204             0.333333               200       37000             4
4205             0.708333               115       21275             1

      Flight Year
4204         2015
4205         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4206  Flight4207  41840  ORD-DFW              2.8         177
4207  Flight4208  41842  ORD-IAH              1.6          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4206             0.291667               220       36300             7
4207             0.791667               220       39820             7

      Flight Year
4206         2014
4207         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4208  Flight4209  41815  ORD-IAH              2.2         178
4209  Flight4210  42027  ORD-DTW              2.1          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4208             0.520833               220       36300             6
4209             0.312500               115       21275             1

      Flight Year
4208         2014
4209         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4210  Flight4211  41971  ORD-LAX             10.9         110
4211  Flight4212  42289  ORD-JFK              2.9         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4210             0.458333               525       97125            11
4211             0.645833               250       46250            10

      Flight Year
4210         2014
4211         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4212  Flight4213  42193  ORD-SFO              0.6          22
4213  Flight4214  41835  ORD-PHL              2.5          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4212                0.375             412.5     76312.5             7
4213                0.625             302.5     54752.5             7

      Flight Year
4212         2015
4213         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4214  Flight4215  42116  ORD-DFW              1.9         110
4215  Flight4216  41880  ORD-DEN              2.2          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4214             0.875000               200       37000             4
4215             0.708333               330       54450             8

      Flight Year
4214         2015
4215         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4216  Flight4217  41793  ORD-DTW              3.3          35
4217  Flight4218  41995  ORD-CLT              2.8         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4216             0.708333             126.5     23402.5             6
4217             0.312500             175.0     28875.0            12

      Flight Year
4216         2014
4217         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4218  Flight4219  42309  ORD-EWR              3.2         198
4219  Flight4220  42082  ORD-IAH              0.9         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4218             0.791667               225       37125            11
4219             0.791667               200       37000             3

      Flight Year
4218         2015
4219         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4220  Flight4221  42011  ORD-LGA              1.0          81
4221  Flight4222  41742  ORD-BOS              2.1           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4220             0.833333               275       49775             1
4221             0.750000               300       55500             4

      Flight Year
4220         2015
4221         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4222  Flight4223  41811  ORD-LAX              4.5         176
4223  Flight4224  41827  ORD-BOS              2.1         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4222             0.458333               385       63525             6
4223             0.708333               330       54450             7

      Flight Year
4222         2014
4223         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4224  Flight4225  42225  ORD-DFW              1.5         155
4225  Flight4226  41815  ORD-ATL              9.7         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4224             0.520833               220       36300             8
4225             0.791667               220       40700             6

      Flight Year
4224         2015
4225         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4226  Flight4227  42299  ORD-DFW              2.5         190
4227  Flight4228  42045  ORD-BOS              1.4         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4226             0.833333               200       33000            10
4227             0.333333               300       55500             2

      Flight Year
4226         2015
4227         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4228  Flight4229  42108  ORD-ATL              7.2         160
4229  Flight4230  42305  ORD-LAX              1.7         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4228             0.458333               200       33000             4
4229             0.729167               350       57750            10

      Flight Year
4228         2015
4229         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4230  Flight4231  42326  ORD-SEA              3.7         129
4231  Flight4232  41973  ORD-LGA              6.5         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4230             0.812500             350.0     64750.0            11
4231             0.333333             412.5     76312.5            11

      Flight Year
4230         2015
4231         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4232  Flight4233  42352  ORD-LAS              1.3          37
4233  Flight4234  42270  ORD-PHL              1.8          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4232             0.666667               275       45375            12
4233             0.625000               275       45375             9

      Flight Year
4232         2015
4233         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4234  Flight4235  42189  ORD-LGA              2.2         203
4235  Flight4236  42245  ORD-SEA              0.8          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4234             0.333333             302.5     49912.5             7
4235             0.500000             385.0     63525.0             8

      Flight Year
4234         2015
4235         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4236  Flight4237  42247  ORD-EWR              1.3          82
4237  Flight4238  42263  ORD-IAH              1.6          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4236             0.500000             247.5     44797.5             8
4237             0.791667             200.0     37000.0             9

      Flight Year
4236         2015
4237         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4238  Flight4239  42220  ORD-JFK              1.2         101
4239  Flight4240  41930  ORD-DEN              3.0         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4238             0.291667               275       50875             8
4239             0.750000               300       55500            10

      Flight Year
4238         2015
4239         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4240  Flight4241  41823  ORD-ATL              9.2          80
4241  Flight4242  41942  ORD-DEN              2.3          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4240             0.458333               220       39820             7
4241             0.791667               300       55500            10

      Flight Year
4240         2014
4241         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4242  Flight4243  41826  ORD-SFO              3.0         128
4243  Flight4244  41903  ORD-JFK              0.9          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4242             0.875000             412.5     76312.5             7
4243             0.583333             250.0     45250.0             9

      Flight Year
4242         2014
4243         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4244  Flight4245  42057  ORD-SFO              2.7          46
4245  Flight4246  41663  ORD-SEA              2.1         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4244             0.750000               375       61875             2
4245             0.291667               350       57750             1

      Flight Year
4244         2015
4245         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4246  Flight4247  42157  ORD-ATL              9.7          52
4247  Flight4248  41973  ORD-IAH              5.4         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4246             0.291667               220       36300             6
4247             0.291667               300       55500            11

      Flight Year
4246         2015
4247         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4248  Flight4249  42264  ORD-DFW              1.2         149
4249  Flight4250  42181  ORD-PHL              2.8         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4248                 0.50             200.0     37000.0             9
4249                 0.75             302.5     49912.5             6

      Flight Year
4248         2015
4249         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4250  Flight4251  41800  ORD-PHX              1.4          82
4251  Flight4252  41972  ORD-IAH              6.7         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4250             0.583333               275       49775             6
4251             0.333333               300       49500            11

      Flight Year
4250         2014
4251         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4252  Flight4253  42253  ORD-MSP              1.1         106
4253  Flight4254  42215  ORD-DEN              3.6          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4252             0.541667               115       21275             9
4253             0.708333               330       54450             7

      Flight Year
4252         2015
4253         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4254  Flight4255  41927  ORD-DEN              1.6          53
4255  Flight4256  42072  ORD-MIA              1.3         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4254             0.312500               300       49500            10
4255             0.729167               300       55500             3

      Flight Year
4254         2014
4255         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4256  Flight4257  41676  ORD-DEN              2.1          71
4257  Flight4258  41696  ORD-ATL              9.1           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4256             0.291667               300       54300             2
4257             0.708333               200       37000             2

      Flight Year
4256         2014
4257         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4258  Flight4259  41779  ORD-DTW              2.4          17
4259  Flight4260  41928  ORD-DFW              1.5          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4258             0.833333               115       21275             5
4259             0.770833               200       37000            10

      Flight Year
4258         2014
4259         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4260  Flight4261  42072  ORD-SFO              1.6         144
4261  Flight4262  42048  ORD-ATL              9.8          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4260             0.312500               375       69375             3
4261             0.833333               200       37000             2

      Flight Year
4260         2015
4261         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4262  Flight4263  41978  ORD-LGA              1.4         182
4263  Flight4264  41925  ORD-LGA              2.2         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4262             0.833333               275       45375            12
4263             0.750000               275       45375            10

      Flight Year
4262         2014
4263         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4264  Flight4265  41928  ORD-LAS              1.7         191
4265  Flight4266  41900  ORD-SFO              1.3          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4264             0.791667               275       45375            10
4265             0.541667               375       61875             9

      Flight Year
4264         2014
4265         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4266  Flight4267  41897  ORD-LAX              3.3          70
4267  Flight4268  42062  ORD-PHL              1.6          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4266             0.791667               350       63350             9
4267             0.312500               275       49775             2

      Flight Year
4266         2014
4267         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4268  Flight4269  42263  ORD-DFW              1.5         198
4269  Flight4270  42101  ORD-DTW              1.5         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4268             0.416667               200       33000             9
4269             0.708333               115       18975             4

      Flight Year
4268         2015
4269         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4270  Flight4271  42365  ORD-BOS              3.2           7
4271  Flight4272  41843  ORD-DFW              2.6           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4270             0.541667               420       77700            12
4271             0.875000               220       40700             7

      Flight Year
4270         2015
4271         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4272  Flight4273  42141  ORD-IAD              1.5         156
4273  Flight4274  42192  ORD-LAX              3.9          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4272             0.729167               300       49500             5
4273             0.770833               385       71225             7

      Flight Year
4272         2015
4273         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4274  Flight4275  41640  ORD-DEN              1.9          96
4275  Flight4276  41673  ORD-EWR              2.1         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4274             0.791667               300       55500             1
4275             0.291667               225       37125             2

      Flight Year
4274         2014
4275         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4276  Flight4277  41922  ORD-ATL              9.8         108
4277  Flight4278  42335  ORD-JFK              6.2         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4276             0.375000               200       37000            10
4277             0.708333               375       69375            11

      Flight Year
4276         2014
4277         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4278  Flight4279  42342  ORD-ATL              7.9          79
4279  Flight4280  42191  ORD-ATL             10.7         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4278             0.291667               200       36200            12
4279             0.500000               220       40700             7

      Flight Year
4278         2015
4279         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4280  Flight4281  42364  ORD-DEN              3.4         207
4281  Flight4282  41711  ORD-LAS              1.5          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4280               0.8125               420       69300            12
4281               0.7500               275       50875             3

      Flight Year
4280         2015
4281         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4282  Flight4283  41997  ORD-EWR              3.4         164
4283  Flight4284  42252  ORD-PHX              1.8         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4282                 0.75               315       51975            12
4283                 0.75               250       41250             9

      Flight Year
4282         2014
4283         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4284  Flight4285  42039  ORD-IAH              1.2         120
4285  Flight4286  41727  ORD-CLT              2.9         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4284             0.708333               200       37000             2
4285             0.333333               125       23125             3

      Flight Year
4284         2015
4285         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4286  Flight4287  41775  ORD-IAD              2.4         208
4287  Flight4288  42169  ORD-LAX              5.2         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4286             0.333333               300       49500             5
4287             0.479167               385       71225             6

      Flight Year
4286         2014
4287         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4288  Flight4289  42061  ORD-JFK              2.5          53
4289  Flight4290  41993  ORD-JFK              2.0         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4288             0.666667               250       41250             2
4289             0.791667               250       46250            12

      Flight Year
4288         2015
4289         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4290  Flight4291  42334  ORD-LAX             10.7         201
4291  Flight4292  41935  ORD-MSP              2.2          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4290             0.708333               525       86625            11
4291             0.333333               115       21275            10

      Flight Year
4290         2015
4291         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4292  Flight4293  41944  ORD-EWR              1.8         203
4293  Flight4294  41950  ORD-LAS              0.7         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4292             0.291667               225       37125            11
4293             0.354167               275       45375            11

      Flight Year
4292         2014
4293         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4294  Flight4295  41822  ORD-BOS              2.5         105
4295  Flight4296  42107  ORD-SEA              1.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4294             0.291667               330       61050             7
4295             0.750000               350       57750             4

      Flight Year
4294         2014
4295         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4296  Flight4297  41955  ORD-DFW              3.4          38
4297  Flight4298  42199  ORD-JFK              1.6         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4296             0.458333               200       33000            11
4297             0.520833               275       50875             7

      Flight Year
4296         2014
4297         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4298  Flight4299  41725  ORD-ATL             10.2         136
4299  Flight4300  42306  ORD-PHL              1.6         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4298             0.291667               200       37000             3
4299             0.833333               275       45375            10

      Flight Year
4298         2014
4299         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4300  Flight4301  42337  ORD-DFW              3.7          35
4301  Flight4302  42035  ORD-MIA              1.3         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4300             0.708333               300       55500            11
4301             0.833333               300       55500             1

      Flight Year
4300         2015
4301         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4302  Flight4303  42350  ORD-CLT              3.0         137
4303  Flight4304  42023  ORD-LGA              1.9          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4302             0.291667               125       23125            12
4303             0.500000               275       50875             1

      Flight Year
4302         2015
4303         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4304  Flight4305  41782  ORD-PHL              2.3         106
4305  Flight4306  42065  ORD-LGA              1.0         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4304             0.708333               275       50875             5
4305             0.708333               275       45375             3

      Flight Year
4304         2014
4305         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4306  Flight4307  42037  ORD-ATL              7.8          27
4307  Flight4308  42343  ORD-BOS              1.8         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4306             0.708333               200       37000             2
4307             0.541667               300       49500            12

      Flight Year
4306         2015
4307         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4308  Flight4309  41682  ORD-BOS              1.9          77
4309  Flight4310  42292  ORD-SFO              1.7         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4308             0.291667               300       54300             2
4309             0.354167               375       69375            10

      Flight Year
4308         2014
4309         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4310  Flight4311  41965  ORD-DFW              2.1         140
4311  Flight4312  41766  ORD-IAH              2.6         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4310             0.291667               200       37000            11
4311             0.833333               200       33000             5

      Flight Year
4310         2014
4311         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4312  Flight4313  41848  ORD-MIA              1.2         206
4313  Flight4314  42238  ORD-EWR              3.2          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4312                 0.50             330.0     54450.0             7
4313                 0.75             247.5     40837.5             8

      Flight Year
4312         2014
4313         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4314  Flight4315  41844  ORD-BWI              2.7         172
4315  Flight4316  42335  ORD-MCO              2.7         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4314             0.333333               264       43560             7
4315             0.291667               375       69375            11

      Flight Year
4314         2014
4315         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4316  Flight4317  42166  ORD-SEA              2.3          70
4317  Flight4318  41965  ORD-ATL              8.9          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4316             0.833333               385       69685             6
4317             0.604167               200       33000            11

      Flight Year
4316         2015
4317         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4318  Flight4319  42364  ORD-IAH              4.8          36
4319  Flight4320  42037  ORD-LAS              1.2         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4318                 0.75               280       46200            12
4319                 0.75               275       50875             2

      Flight Year
4318         2015
4319         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4320  Flight4321  42102  ORD-LAS              1.8         113
4321  Flight4322  42253  ORD-DEN              2.2         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4320             0.500000               275       50875             4
4321             0.666667               300       55500             9

      Flight Year
4320         2015
4321         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4322  Flight4323  42249  ORD-CLT              1.5         177
4323  Flight4324  41828  ORD-ATL              8.4          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4322             0.750000               125       20625             9
4323             0.291667               220       40700             7

      Flight Year
4322         2015
4323         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4324  Flight4325  41758  ORD-CLT              0.6         185
4325  Flight4326  42044  ORD-DEN              2.5          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4324             0.312500               125       20625             4
4325             0.833333               300       55500             2

      Flight Year
4324         2014
4325         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4326  Flight4327  42184  ORD-CLT              2.1         147
4327  Flight4328  42135  ORD-MSP              2.2          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4326             0.708333             137.5     25437.5             6
4327             0.458333             115.0     20815.0             5

      Flight Year
4326         2015
4327         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4328  Flight4329  42177  ORD-DEN              3.4         191
4329  Flight4330  42363  ORD-IAH              3.3         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4328             0.708333               330       54450             6
4329             0.458333               280       51800            12

      Flight Year
4328         2015
4329         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4330  Flight4331  42274  ORD-DFW              1.1         190
4331  Flight4332  41792  ORD-SFO              2.8          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4330             0.791667             200.0     33000.0             9
4331             0.312500             412.5     76312.5             6

      Flight Year
4330         2015
4331         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4332  Flight4333  42218  ORD-EWR              2.1          75
4333  Flight4334  42364  ORD-PHL              4.5         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4332             0.291667             247.5     44797.5             8
4333             0.791667             385.0     71225.0            12

      Flight Year
4332         2015
4333         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4334  Flight4335  41712  ORD-LAX              4.2         180
4335  Flight4336  41787  ORD-CLT              1.8           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4334             0.812500               350       57750             3
4335             0.708333               125       23125             5

      Flight Year
4334         2014
4335         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4336  Flight4337  42200  ORD-CLT              3.5          91
4337  Flight4338  41973  ORD-LAX              9.4          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4336             0.500000             137.5     25437.5             7
4337             0.854167             525.0     97125.0            11

      Flight Year
4336         2015
4337         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4338  Flight4339  42368  ORD-LAX                4         210
4339  Flight4340  41823  ORD-CLT                1         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4338             0.791667             350.0     57750.0            12
4339             0.750000             137.5     22687.5             7

      Flight Year
4338         2015
4339         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4340  Flight4341  41879  ORD-BOS              2.0         184
4341  Flight4342  41833  ORD-IAH              2.7         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4340             0.812500               330       54450             8
4341             0.729167               220       36300             7

      Flight Year
4340         2014
4341         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4342  Flight4343  42232  ORD-ATL              9.6         171
4343  Flight4344  42220  ORD-DFW              1.8           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4342             0.791667               220       36300             8
4343             0.687500               220       40700             8

      Flight Year
4342         2015
4343         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4344  Flight4345  41745  ORD-DTW              2.0          81
4345  Flight4346  41953  ORD-LGA              2.3         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4344               0.3125               115       20815             4
4345               0.3750               275       45375            11

      Flight Year
4344         2014
4345         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4346  Flight4347  41982  ORD-DTW              2.6         207
4347  Flight4348  41846  ORD-PHX              2.2         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4346             0.583333               115       18975            12
4347             0.729167               275       50875             7

      Flight Year
4346         2014
4347         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4348  Flight4349  42048  ORD-DEN              1.3         137
4349  Flight4350  42287  ORD-SFO              2.1         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4348                 0.75               300       55500             2
4349                 0.75               375       69375            10

      Flight Year
4348         2015
4349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4350  Flight4351  42155  ORD-PHX              1.6          20
4351  Flight4352  42129  ORD-ATL              9.1         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4350             0.750000               250       46250             5
4351             0.833333               200       33000             5

      Flight Year
4350         2015
4351         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4352  Flight4353  42320  ORD-DEN              1.2          44
4353  Flight4354  42039  ORD-JFK              0.5         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4352             0.312500               300       49500            11
4353             0.833333               250       46250             2

      Flight Year
4352         2015
4353         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4354  Flight4355  41895  ORD-CLT              1.4          54
4355  Flight4356  42279  ORD-LAX              4.3         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4354             0.291667               125       20625             9
4355             0.354167               350       64750            10

      Flight Year
4354         2014
4355         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4356  Flight4357  42000  ORD-MCO              3.6         202
4357  Flight4358  42362  ORD-DEN              1.6          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4356               0.7500               350       57750            12
4357               0.4375               420       76020            12

      Flight Year
4356         2014
4357         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4358  Flight4359  42159  ORD-ATL              9.7          84
4359  Flight4360  41884  ORD-LAX              4.1          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4358             0.708333               220       39820             6
4359             0.812500               350       64750             9

      Flight Year
4358         2015
4359         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4360  Flight4361  41746  ORD-LAS              2.0         179
4361  Flight4362  42092  ORD-LAX              4.8         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4360             0.666667               275       45375             4
4361             0.333333               350       64750             3

      Flight Year
4360         2014
4361         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4362  Flight4363  41683  ORD-LAS              1.5         164
4363  Flight4364  41743  ORD-DTW              2.3         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4362             0.354167               275       45375             2
4363             0.520833               115       21275             4

      Flight Year
4362         2014
4363         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4364  Flight4365  41871  ORD-DTW              1.6          99
4365  Flight4366  41947  ORD-SFO              2.2         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4364             0.520833             126.5     23402.5             8
4365             0.583333             375.0     61875.0            11

      Flight Year
4364         2014
4365         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4366  Flight4367  42212  ORD-DEN              2.9         188
4367  Flight4368  41746  ORD-IAH              2.1         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4366             0.854167               330       54450             7
4367             0.708333               200       37000             4

      Flight Year
4366         2015
4367         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4368  Flight4369  41967  ORD-ATL             17.7          11
4369  Flight4370  41985  ORD-MIA              1.1         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4368             0.416667               300       55500            11
4369             0.770833               300       49500            12

      Flight Year
4368         2014
4369         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4370  Flight4371  41649  ORD-CLT              1.8          26
4371  Flight4372  42329  ORD-DEN              2.5         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4370             0.604167               125       23125             1
4371             0.729167               300       55500            11

      Flight Year
4370         2014
4371         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4372  Flight4373  42024  ORD-SLC              2.2          10
4373  Flight4374  42185  ORD-FLL              1.2          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4372             0.395833               290       53650             1
4373             0.708333               330       61050             6

      Flight Year
4372         2015
4373         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4374  Flight4375  42249  ORD-DFW              1.8         180
4375  Flight4376  41792  ORD-MIA              1.6         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4374               0.8125               200       33000             9
4375               0.8750               330       61050             6

      Flight Year
4374         2015
4375         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4376  Flight4377  42335  ORD-CLT              3.9          69
4377  Flight4378  41724  ORD-JFK              1.5         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4376             0.541667             187.5     33937.5            11
4377             0.791667             250.0     46250.0             3

      Flight Year
4376         2015
4377         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4378  Flight4379  42246  ORD-BOS              2.9          22
4379  Flight4380  41968  ORD-PHX              7.4          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4378             0.625000               330       61050             8
4379             0.770833               375       67875            11

      Flight Year
4378         2015
4379         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4380  Flight4381  41818  ORD-MIA              3.1         154
4381  Flight4382  41786  ORD-JFK              1.2          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4380             0.333333               330       54450             6
4381             0.875000               250       46250             5

      Flight Year
4380         2014
4381         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4382  Flight4383  41928  ORD-SEA              0.6         210
4383  Flight4384  41667  ORD-MIA              1.3          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4382             0.833333               350       57750            10
4383             0.833333               300       49500             1

      Flight Year
4382         2014
4383         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4384  Flight4385  42072  ORD-PHX              2.1          91
4385  Flight4386  41993  ORD-LAX              1.8          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4384               0.7500               250       46250             3
4385               0.8125               350       63350            12

      Flight Year
4384         2015
4385         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4386  Flight4387  42236  ORD-DFW              2.1          72
4387  Flight4388  41807  ORD-FLL              1.7         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4386             0.750000               220       39820             8
4387             0.708333               330       54450             6

      Flight Year
4386         2015
4387         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4388  Flight4389  41944  ORD-DFW              1.8          74
4389  Flight4390  41686  ORD-MCO              1.1         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4388             0.750000               200       36200            11
4389             0.291667               250       41250             2

      Flight Year
4388         2014
4389         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4390  Flight4391  42087  ORD-JFK              2.6           9
4391  Flight4392  41868  ORD-DEN              2.6         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4390             0.416667               250       46250             3
4391             0.458333               330       54450             8

      Flight Year
4390         2015
4391         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4392  Flight4393  41760  ORD-ATL              5.9           1
4393  Flight4394  42164  ORD-MCO              3.0          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4392             0.791667               200       37000             5
4393             0.812500               275       50875             6

      Flight Year
4392         2014
4393         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4394  Flight4395  42200  ORD-LGA              1.2         196
4395  Flight4396  41903  ORD-SFO              1.9         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4394             0.833333             302.5     49912.5             7
4395             0.291667             375.0     61875.0             9

      Flight Year
4394         2015
4395         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4396  Flight4397  41878  ORD-DEN              2.2         187
4397  Flight4398  42000  ORD-MIA              4.8         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4396             0.645833               330       54450             8
4397             0.333333               420       77700            12

      Flight Year
4396         2014
4397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4398  Flight4399  41987  ORD-LAX              4.2          77
4399  Flight4400  41905  ORD-IAH              2.2          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4398             0.395833               350       63350            12
4399             0.333333               200       33000             9

      Flight Year
4398         2014
4399         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4400  Flight4401  41968  ORD-JFK              5.3         158
4401  Flight4402  41800  ORD-CLT              0.5         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4400             0.791667             375.0     61875.0            11
4401             0.500000             137.5     22687.5             6

      Flight Year
4400         2014
4401         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4402  Flight4403  42251  ORD-PHL              1.9          67
4403  Flight4404  42009  ORD-BOS              1.6         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4402             0.770833               275       49775             9
4403             0.708333               300       55500             1

      Flight Year
4402         2015
4403         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4404  Flight4405  42182  ORD-SFO              1.7         105
4405  Flight4406  42360  ORD-EWR              6.4         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4404             0.312500             412.5     76312.5             6
4405             0.333333             315.0     51975.0            12

      Flight Year
4404         2015
4405         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4406  Flight4407  41718  ORD-MIA              1.5         110
4407  Flight4408  41998  ORD-JFK              5.3         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4406             0.791667               300       55500             3
4407             0.791667               350       64750            12

      Flight Year
4406         2014
4407         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4408  Flight4409  42247  ORD-JFK              1.2         135
4409  Flight4410  41805  ORD-SEA              2.2         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4408             0.708333               275       50875             8
4409             0.437500               385       63525             6

      Flight Year
4408         2015
4409         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4410  Flight4411  42144  ORD-DEN              1.4          56
4411  Flight4412  41927  ORD-LAS              2.6          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4410             0.729167               300       49500             5
4411             0.708333               275       49775            10

      Flight Year
4410         2015
4411         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4412  Flight4413  42295  ORD-MCO              1.5         201
4413  Flight4414  42170  ORD-SEA              2.2         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4412             0.750000               250       41250            10
4413             0.770833               385       71225             6

      Flight Year
4412         2015
4413         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4414  Flight4415  41987  ORD-MIA              2.6          44
4415  Flight4416  41835  ORD-SFO              1.4         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4414             0.708333             300.0     49500.0            12
4415             0.666667             412.5     76312.5             7

      Flight Year
4414         2014
4415         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4416  Flight4417  41814  ORD-DFW              1.1          37
4417  Flight4418  41878  ORD-LAX              5.3         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4416             0.645833               220       36300             6
4417             0.375000               385       63525             8

      Flight Year
4416         2014
4417         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4418  Flight4419  41654  ORD-LAS              2.5         152
4419  Flight4420  41860  ORD-LAX              3.2         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4418             0.291667               275       45375             1
4419             0.791667               385       71225             8

      Flight Year
4418         2014
4419         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4420  Flight4421  42341  ORD-JFK              2.3         138
4421  Flight4422  41805  ORD-JFK              1.8          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4420             0.750000               250       46250            12
4421             0.583333               275       45375             6

      Flight Year
4420         2015
4421         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4422  Flight4423  41669  ORD-MCO              2.0         198
4423  Flight4424  42174  ORD-DTW              2.7         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4422             0.291667             250.0     41250.0             1
4423             0.875000             126.5     20872.5             6

      Flight Year
4422         2014
4423         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4424  Flight4425  41932  ORD-LGA              2.2         190
4425  Flight4426  42302  ORD-EWR              3.2           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4424             0.375000               275       45375            10
4425             0.770833               225       41625            10

      Flight Year
4424         2014
4425         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4426  Flight4427  41699  ORD-LAS              2.4         116
4427  Flight4428  41797  ORD-MCO              1.2          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4426             0.458333               275       50875             3
4427             0.354167               275       49775             6

      Flight Year
4426         2014
4427         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4428  Flight4429  42031  ORD-BWI              1.1         185
4429  Flight4430  42205  ORD-MSP              2.7         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4428             0.833333             240.0     39600.0             1
4429             0.479167             126.5     20872.5             7

      Flight Year
4428         2015
4429         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4430  Flight4431  41822  ORD-LGA              2.7           8
4431  Flight4432  41893  ORD-SEA              1.5         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4430             0.750000             302.5     55962.5             7
4431             0.708333             350.0     57750.0             9

      Flight Year
4430         2014
4431         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4432  Flight4433  41857  ORD-CLT              1.6         141
4433  Flight4434  42298  ORD-DEN              3.1          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4432             0.833333             137.5     25437.5             8
4433             0.895833             300.0     55500.0            10

      Flight Year
4432         2014
4433         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4434  Flight4435  42308  ORD-SFO              2.3          50
4435  Flight4436  42226  ORD-MIA              1.6         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4434                0.875               375       61875            10
4435                0.625               330       61050             8

      Flight Year
4434         2015
4435         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4436  Flight4437  41878  ORD-PHX              2.9           4
4437  Flight4438  41708  ORD-LAX              4.8          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4436             0.750000               275       50875             8
4437             0.541667               350       57750             3

      Flight Year
4436         2014
4437         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4438  Flight4439  41698  ORD-ATL             12.1          45
4439  Flight4440  42090  ORD-FLL              1.7          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4438             0.791667               200       33000             2
4439             0.375000               300       49500             3

      Flight Year
4438         2014
4439         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4440  Flight4441  42334  ORD-SEA              3.4         145
4441  Flight4442  42150  ORD-LAX              2.8          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4440             0.354167               525       97125            11
4441             0.791667               350       57750             5

      Flight Year
4440         2015
4441         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4442  Flight4443  41677  ORD-ATL              8.5          19
4443  Flight4444  41648  ORD-IAH              2.1         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4442                0.750               200       37000             2
4443                0.625               200       37000             1

      Flight Year
4442         2014
4443         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4444  Flight4445  41941  ORD-DTW              2.3         103
4445  Flight4446  42358  ORD-MIA              2.4          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4444             0.312500               115       21275            10
4445             0.416667               300       55500            12

      Flight Year
4444         2014
4445         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4446  Flight4447  42023  ORD-DEN              1.5          91
4447  Flight4448  42283  ORD-BOS              2.0         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4446                0.875               300       55500             1
4447                0.750               300       49500            10

      Flight Year
4446         2015
4447         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4448  Flight4449  41928  ORD-LAX              5.3         143
4449  Flight4450  41705  ORD-LAX              5.0         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4448             0.791667               350       64750            10
4449             0.750000               350       57750             3

      Flight Year
4448         2014
4449         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4450  Flight4451  42183  ORD-SFO              1.8          80
4451  Flight4452  42167  ORD-PHX              1.5           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4450             0.625000             412.5     74662.5             6
4451             0.458333             275.0     50875.0             6

      Flight Year
4450         2015
4451         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4452  Flight4453  42289  ORD-ATL             10.0         167
4453  Flight4454  42093  ORD-LAX              4.2          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4452             0.750000               200       33000            10
4453             0.333333               350       63350             3

      Flight Year
4452         2015
4453         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4454  Flight4455  41718  ORD-JFK              4.2          50
4455  Flight4456  42245  ORD-LAX              7.9         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4454             0.750000               250       41250             3
4455             0.791667               385       71225             8

      Flight Year
4454         2014
4455         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4456  Flight4457  42116  ORD-BOS              2.5          35
4457  Flight4458  41863  ORD-FLL              1.9         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4456             0.583333               300       55500             4
4457             0.833333               330       54450             8

      Flight Year
4456         2015
4457         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4458  Flight4459  41979  ORD-CLT              1.7         180
4459  Flight4460  42196  ORD-CLT              3.2          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4458             0.729167             125.0     20625.0            12
4459             0.750000             137.5     25437.5             7

      Flight Year
4458         2014
4459         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4460  Flight4461  42145  ORD-DFW              1.8         195
4461  Flight4462  42333  ORD-ATL             19.6          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4460             0.479167               200       33000             5
4461             0.729167               300       55500            11

      Flight Year
4460         2015
4461         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4462  Flight4463  41816  ORD-MCO              1.1          67
4463  Flight4464  42184  ORD-MIA              1.6         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4462             0.541667               275       49775             6
4463             0.750000               330       54450             6

      Flight Year
4462         2014
4463         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4464  Flight4465  42092  ORD-SFO              2.8         186
4465  Flight4466  42321  ORD-ATL              9.5          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4464             0.791667               375       61875             3
4465             0.833333               200       33000            11

      Flight Year
4464         2015
4465         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4466  Flight4467  41855  ORD-MCO              2.9         163
4467  Flight4468  41817  ORD-DFW              1.5          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4466             0.812500               275       45375             8
4467             0.291667               220       36300             6

      Flight Year
4466         2014
4467         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4468  Flight4469  42087  ORD-MSP              1.7          97
4469  Flight4470  41664  ORD-MIA              1.9          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4468             0.291667               115       21275             3
4469             0.583333               300       49500             1

      Flight Year
4468         2015
4469         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4470  Flight4471  41970  ORD-JFK              5.4          73
4471  Flight4472  42115  ORD-CLT              2.2         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4470             0.750000               375       67875            11
4471             0.541667               125       20625             4

      Flight Year
4470         2014
4471         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4472  Flight4473  41749  ORD-PHX              1.7         121
4473  Flight4474  42047  ORD-PHX              2.0         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4472             0.729167               250       46250             4
4473             0.291667               250       46250             2

      Flight Year
4472         2014
4473         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4474  Flight4475  42032  ORD-DFW              2.0          45
4475  Flight4476  41673  ORD-ATL              6.8          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4474             0.833333               200       33000             1
4475             0.604167               200       33000             2

      Flight Year
4474         2015
4475         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4476  Flight4477  41790  ORD-BOS              2.3         167
4477  Flight4478  41879  ORD-DTW              3.1         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4476             0.708333             300.0     49500.0             5
4477             0.791667             126.5     20872.5             8

      Flight Year
4476         2014
4477         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4478  Flight4479  41761  ORD-SFO              2.8         103
4479  Flight4480  42231  ORD-CLT              2.6          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4478             0.791667             375.0     69375.0             5
4479             0.291667             137.5     25437.5             8

      Flight Year
4478         2014
4479         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4480  Flight4481  42244  ORD-CLT              1.5         141
4481  Flight4482  41928  ORD-LAS              1.0         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4480             0.833333             137.5     25437.5             8
4481             0.375000             275.0     45375.0            10

      Flight Year
4480         2015
4481         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4482  Flight4483  41805  ORD-ATL              9.0         121
4483  Flight4484  42150  ORD-EWR              1.6         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4482                0.625               220       40700             6
4483                0.375               225       37125             5

      Flight Year
4482         2014
4483         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4484  Flight4485  42218  ORD-PHX              2.0          17
4485  Flight4486  42301  ORD-SEA              1.7          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4484             0.895833               275       50875             8
4485             0.541667               350       64750            10

      Flight Year
4484         2015
4485         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4486  Flight4487  41822  ORD-SEA              1.4         155
4487  Flight4488  41861  ORD-BOS              2.2         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4486             0.791667               385       63525             7
4487             0.291667               330       54450             8

      Flight Year
4486         2014
4487         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4488  Flight4489  41851  ORD-LAS              2.6         210
4489  Flight4490  41754  ORD-PHX              1.9          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4488             0.708333             302.5     49912.5             7
4489             0.625000             250.0     41250.0             4

      Flight Year
4488         2014
4489         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4490  Flight4491  42018  ORD-SFO              2.6          19
4491  Flight4492  42182  ORD-LGA              2.9           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4490             0.729167             375.0     69375.0             1
4491             0.750000             302.5     55962.5             6

      Flight Year
4490         2015
4491         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4492  Flight4493  41821  ORD-SFO              1.8          92
4493  Flight4494  42000  ORD-DFW              5.8         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4492             0.479167             412.5     76312.5             7
4493             0.770833             280.0     46200.0            12

      Flight Year
4492         2014
4493         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4494  Flight4495  42300  ORD-DEN              1.1         191
4495  Flight4496  42014  ORD-DFW              2.0          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4494             0.291667               300       49500            10
4495             0.791667               200       36200             1

      Flight Year
4494         2015
4495         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4496  Flight4497  41669  ORD-SEA              3.2         158
4497  Flight4498  42032  ORD-SFO              2.0           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4496             0.500000               350       57750             1
4497             0.583333               375       69375             1

      Flight Year
4496         2014
4497         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4498  Flight4499  42264  ORD-IAH              1.4         171
4499  Flight4500  41900  ORD-ATL             13.0         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4498             0.625000               200       33000             9
4499             0.416667               200       37000             9

      Flight Year
4498         2015
4499         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4500  Flight4501  41935  ORD-LAS              1.7          16
4501  Flight4502  42008  ORD-DTW              2.7          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4500             0.791667               275       50875            10
4501             0.541667               115       20815             1

      Flight Year
4500         2014
4501         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4502  Flight4503  41794  ORD-EWR              2.5           5
4503  Flight4504  41989  ORD-DEN              2.2         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4502             0.291667             247.5     45787.5             6
4503             0.291667             300.0     49500.0            12

      Flight Year
4502         2014
4503         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4504  Flight4505  41657  ORD-EWR              2.6          46
4505  Flight4506  41858  ORD-CLT              1.6           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4504             0.729167             225.0     37125.0             1
4505             0.729167             137.5     25437.5             8

      Flight Year
4504         2014
4505         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4506  Flight4507  42273  ORD-DFW              2.0         122
4507  Flight4508  41752  ORD-DFW              2.5         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4506                 0.50               200       37000             9
4507                 0.75               200       33000             4

      Flight Year
4506         2015
4507         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4508  Flight4509  42137  ORD-MCO              0.9          49
4509  Flight4510  42111  ORD-DTW              0.8          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4508             0.708333               250       41250             5
4509             0.750000               115       21275             4

      Flight Year
4508         2015
4509         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4510  Flight4511  41641  ORD-DFW              3.4          56
4511  Flight4512  42219  ORD-DFW              1.5         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4510             0.791667               200       33000             1
4511             0.729167               220       36300             8

      Flight Year
4510         2014
4511         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4512  Flight4513  41689  ORD-ATL              6.2         164
4513  Flight4514  41816  ORD-BOS              2.6          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4512             0.812500               200       33000             2
4513             0.291667               330       59730             6

      Flight Year
4512         2014
4513         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4514  Flight4515  41861  ORD-DFW              0.7           7
4515  Flight4516  42190  ORD-DTW              2.1         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4514             0.791667             220.0     40700.0             8
4515             0.645833             126.5     20872.5             7

      Flight Year
4514         2014
4515         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4516  Flight4517  42261  ORD-LAS              2.6          68
4517  Flight4518  41678  ORD-PHX              1.2          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4516             0.708333               275       49775             9
4517             0.750000               250       41250             2

      Flight Year
4516         2015
4517         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4518  Flight4519  42141  ORD-MCO              2.3         139
4519  Flight4520  41792  ORD-JFK              2.9          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4518             0.708333               250       46250             5
4519             0.770833               275       49775             6

      Flight Year
4518         2015
4519         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4520  Flight4521  42115  ORD-SFO              1.8          56
4521  Flight4522  41900  ORD-ATL              7.2          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4520             0.333333               375       61875             4
4521             0.854167               200       37000             9

      Flight Year
4520         2015
4521         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4522  Flight4523  41697  ORD-JFK              0.6         123
4523  Flight4524  42135  ORD-JFK              1.0         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4522             0.729167               250       46250             2
4523             0.791667               250       41250             5

      Flight Year
4522         2014
4523         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4524  Flight4525  41696  ORD-DFW              2.0         125
4525  Flight4526  41869  ORD-SFO              1.5          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4524             0.791667             200.0     37000.0             2
4525             0.312500             412.5     74662.5             8

      Flight Year
4524         2014
4525         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4526  Flight4527  41934  ORD-LAS              2.2         169
4527  Flight4528  42099  ORD-MIA              0.8          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4526             0.770833               275       45375            10
4527             0.500000               300       49500             4

      Flight Year
4526         2014
4527         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4528  Flight4529  41992  ORD-LAX              3.5         118
4529  Flight4530  42209  ORD-LAX              5.2         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4528             0.645833               350       64750            12
4529             0.500000               385       63525             7

      Flight Year
4528         2014
4529         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4530  Flight4531  41644  ORD-CLT              2.2         187
4531  Flight4532  42247  ORD-BWI              4.0          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4530             0.666667               125       20625             1
4531             0.791667               264       47784             8

      Flight Year
4530         2014
4531         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4532  Flight4533  41681  ORD-DTW              3.3          66
4533  Flight4534  41704  ORD-CLT              2.0          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4532             0.291667               115       20815             2
4533             0.708333               125       23125             3

      Flight Year
4532         2014
4533         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4534  Flight4535  42047  ORD-JFK              1.2           4
4535  Flight4536  42275  ORD-IAD              2.5          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4534             0.791667               250       46250             2
4535             0.770833               300       55500             9

      Flight Year
4534         2015
4535         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4536  Flight4537  42234  ORD-LAX              4.7         156
4537  Flight4538  42282  ORD-SFO              3.0          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4536             0.520833               385       63525             8
4537             0.458333               375       69375            10

      Flight Year
4536         2015
4537         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4538  Flight4539  41840  ORD-SFO              2.2         178
4539  Flight4540  42000  ORD-SFO              3.9         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4538             0.416667             412.5     68062.5             7
4539             0.458333             525.0     97125.0            12

      Flight Year
4538         2014
4539         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4540  Flight4541  42337  ORD-MIA              3.1           3
4541  Flight4542  41882  ORD-LGA              1.4         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4540             0.812500             450.0     83250.0            11
4541             0.604167             302.5     49912.5             8

      Flight Year
4540         2015
4541         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4542  Flight4543  42243  ORD-MSP              2.2         151
4543  Flight4544  42015  ORD-PHL              1.5          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4542             0.291667             126.5     23402.5             8
4543             0.375000             275.0     50875.0             1

      Flight Year
4542         2015
4543         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4544  Flight4545  42352  ORD-CLT              3.5         108
4545  Flight4546  41973  ORD-PHX              5.8          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4544             0.750000               125       23125            12
4545             0.833333               375       67875            11

      Flight Year
4544         2015
4545         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4546  Flight4547  42334  ORD-JFK              3.6         119
4547  Flight4548  42030  ORD-BOS              2.8          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4546             0.583333               375       69375            11
4547             0.458333               300       49500             1

      Flight Year
4546         2015
4547         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4548  Flight4549  41899  ORD-DEN              2.4           2
4549  Flight4550  41904  ORD-MCO              0.4         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4548             0.791667               300       55500             9
4549             0.750000               250       46250             9

      Flight Year
4548         2014
4549         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4550  Flight4551  41971  ORD-MIA              5.8         186
4551  Flight4552  41749  ORD-LAX              2.3         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4550             0.708333               450       74250            11
4551             0.375000               350       64750             4

      Flight Year
4550         2014
4551         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4552  Flight4553  42005  ORD-JFK              2.6         117
4553  Flight4554  41780  ORD-DFW              2.6          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4552             0.291667               250       46250             1
4553             0.812500               200       36200             5

      Flight Year
4552         2015
4553         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4554  Flight4555  42103  ORD-CLT              2.7         127
4555  Flight4556  41870  ORD-DFW              0.4           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4554             0.583333               125       23125             4
4555             0.750000               220       40700             8

      Flight Year
4554         2015
4555         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4556  Flight4557  41811  ORD-ATL              8.4          74
4557  Flight4558  42255  ORD-DFW              0.6          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4556             0.354167               220       39820             6
4557             0.333333               200       33000             9

      Flight Year
4556         2014
4557         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4558  Flight4559  42103  ORD-IAH              3.0          81
4559  Flight4560  41712  ORD-DEN              3.1          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4558             0.791667               200       36200             4
4559             0.750000               300       54300             3

      Flight Year
4558         2015
4559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4560  Flight4561  41828  ORD-DFW              3.2         151
4561  Flight4562  42063  ORD-SFO              2.7          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4560             0.750000               220       40700             7
4561             0.770833               375       61875             2

      Flight Year
4560         2014
4561         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4562  Flight4563  41839  ORD-MSP              1.1          40
4563  Flight4564  41940  ORD-DTW              0.7          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4562             0.604167             126.5     20872.5             7
4563             0.479167             115.0     18975.0            10

      Flight Year
4562         2014
4563         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4564  Flight4565  41765  ORD-IAH              3.1          93
4565  Flight4566  41873  ORD-SFO              2.2          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4564             0.791667             200.0     37000.0             5
4565             0.708333             412.5     76312.5             8

      Flight Year
4564         2014
4565         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4566  Flight4567  41718  ORD-MCO              1.5          38
4567  Flight4568  41711  ORD-DEN              2.3          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4566             0.333333               250       41250             3
4567             0.833333               300       49500             3

      Flight Year
4566         2014
4567         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4568  Flight4569  41660  ORD-IAH              1.7          71
4569  Flight4570  42159  ORD-DEN              1.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4568             0.666667               200       36200             1
4569             0.541667               330       54450             6

      Flight Year
4568         2014
4569         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4570  Flight4571  41968  ORD-MIA              4.9          76
4571  Flight4572  41804  ORD-CLT              2.3         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4570             0.583333             450.0     81450.0            11
4571             0.583333             137.5     25437.5             6

      Flight Year
4570         2014
4571         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4572  Flight4573  41997  ORD-ATL             13.0         170
4573  Flight4574  41805  ORD-EWR              2.8         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4572             0.291667             280.0     46200.0            12
4573             0.562500             247.5     40837.5             6

      Flight Year
4572         2014
4573         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4574  Flight4575  41856  ORD-CLT              3.2         126
4575  Flight4576  42214  ORD-IAH              1.9         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4574             0.541667             137.5     25437.5             8
4575             0.333333             220.0     40700.0             7

      Flight Year
4574         2014
4575         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4576  Flight4577  42048  ORD-DFW              2.9           4
4577  Flight4578  42173  ORD-MCO              2.9         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4576             0.750000               200       37000             2
4577             0.333333               275       50875             6

      Flight Year
4576         2015
4577         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4578  Flight4579  41749  ORD-MCO              1.6         203
4579  Flight4580  42121  ORD-JFK              2.4          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4578             0.791667               250       41250             4
4579             0.729167               250       41250             4

      Flight Year
4578         2014
4579         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4580  Flight4581  41942  ORD-LGA              2.3         153
4581  Flight4582  41996  ORD-EWR              4.5          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4580             0.791667               275       45375            10
4581             0.791667               315       51975            12

      Flight Year
4580         2014
4581         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4582  Flight4583  41939  ORD-DFW              1.7         147
4583  Flight4584  41950  ORD-CLT              1.5         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4582             0.666667               200       37000            10
4583             0.708333               125       23125            11

      Flight Year
4582         2014
4583         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4584  Flight4585  42341  ORD-SFO              1.4         136
4585  Flight4586  41677  ORD-BOS              3.1          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4584             0.604167               375       69375            12
4585             0.354167               300       49500             2

      Flight Year
4584         2015
4585         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4586  Flight4587  42123  ORD-SEA              2.1         195
4587  Flight4588  42214  ORD-PHL              2.6         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4586             0.750000             350.0     57750.0             4
4587             0.354167             302.5     55962.5             7

      Flight Year
4586         2015
4587         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4588  Flight4589  42121  ORD-MSP              1.8          53
4589  Flight4590  42343  ORD-SFO              2.0          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4588             0.500000               115       18975             4
4589             0.291667               375       69375            12

      Flight Year
4588         2015
4589         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4590  Flight4591  41930  ORD-DEN              1.5         165
4591  Flight4592  42165  ORD-MIA              2.5         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4590               0.6875               300       49500            10
4591               0.8750               330       61050             6

      Flight Year
4590         2014
4591         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4592  Flight4593  42208  ORD-JFK              1.7         170
4593  Flight4594  42308  ORD-CLT              2.1          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4592             0.416667               275       45375             7
4593             0.708333               125       20625            10

      Flight Year
4592         2015
4593         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4594  Flight4595  42222  ORD-LAS              3.1         117
4595  Flight4596  41702  ORD-IAH              2.6         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4594             0.666667             302.5     55962.5             8
4595             0.729167             200.0     37000.0             3

      Flight Year
4594         2015
4595         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4596  Flight4597  42339  ORD-PHL              2.5         134
4597  Flight4598  41790  ORD-DFW              2.0         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4596             0.812500               275       50875            12
4597             0.520833               200       33000             5

      Flight Year
4596         2015
4597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4598  Flight4599  42147  ORD-DFW              1.9          84
4599  Flight4600  42175  ORD-IAH              2.7          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4598             0.708333               200       36200             5
4599             0.812500               220       36300             6

      Flight Year
4598         2015
4599         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4600  Flight4601  41900  ORD-LGA              2.4         153
4601  Flight4602  42035  ORD-JFK              1.8         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4600             0.541667               275       45375             9
4601             0.333333               250       46250             1

      Flight Year
4600         2014
4601         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4602  Flight4603  41935  ORD-MCO              1.0         155
4603  Flight4604  41891  ORD-CLT              2.7          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4602               0.5000               250       41250            10
4603               0.3125               125       22625             9

      Flight Year
4602         2014
4603         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4604  Flight4605  41730  ORD-DFW              3.3         154
4605  Flight4606  41841  ORD-SFO              1.6         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4604             0.750000             200.0     33000.0             4
4605             0.291667             412.5     68062.5             7

      Flight Year
4604         2014
4605         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4606  Flight4607  42328  ORD-MCO              2.4         134
4607  Flight4608  41771  ORD-IAH              1.5          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4606               0.3125               250       46250            11
4607               0.8750               200       37000             5

      Flight Year
4606         2015
4607         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4608  Flight4609  42185  ORD-CLT              2.1          12
4609  Flight4610  42053  ORD-MIA              1.2         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4608             0.333333             137.5     25437.5             6
4609             0.729167             300.0     55500.0             2

      Flight Year
4608         2015
4609         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4610  Flight4611  42369  ORD-EWR              2.7          23
4611  Flight4612  42178  ORD-JFK              2.3          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4610             0.583333               225       41625            12
4611             0.333333               275       50875             6

      Flight Year
4610         2015
4611         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4612  Flight4613  41824  ORD-EWR              0.6          33
4613  Flight4614  41787  ORD-MIA              2.6         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4612             0.833333             247.5     45787.5             7
4613             0.708333             300.0     55500.0             5

      Flight Year
4612         2014
4613         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4614  Flight4615  42212  ORD-JFK              1.7         125
4615  Flight4616  42171  ORD-LAX              4.0          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4614             0.291667               275       50875             7
4615             0.791667               385       69685             6

      Flight Year
4614         2015
4615         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4616  Flight4617  41773  ORD-PHL              2.9         206
4617  Flight4618  41906  ORD-LAS              2.1         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4616             0.333333               275       45375             5
4617             0.354167               275       50875             9

      Flight Year
4616         2014
4617         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4618  Flight4619  41913  ORD-DTW              2.9          66
4619  Flight4620  41875  ORD-LAX              4.3          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4618             0.625000               115       20815            10
4619             0.291667               385       69685             8

      Flight Year
4618         2014
4619         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4620  Flight4621  41890  ORD-SFO              2.1          62
4621  Flight4622  41667  ORD-LAS              2.0          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4620             0.291667               375       61875             9
4621             0.291667               275       45375             1

      Flight Year
4620         2014
4621         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4622  Flight4623  41682  ORD-IAH              2.6         129
4623  Flight4624  41999  ORD-LAS              4.3         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4622             0.791667               200       37000             2
4623             0.750000               385       71225            12

      Flight Year
4622         2014
4623         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4624  Flight4625  42104  ORD-ATL              8.2         102
4625  Flight4626  42243  ORD-ATL             10.3          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4624             0.812500               200       37000             4
4625             0.791667               220       36300             8

      Flight Year
4624         2015
4625         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4626  Flight4627  41652  ORD-LGA              1.9          22
4627  Flight4628  42142  ORD-CLT              2.6         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4626             0.416667               275       50875             1
4627             0.791667               125       20625             5

      Flight Year
4626         2014
4627         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4628  Flight4629  41964  ORD-PHX              3.4          77
4629  Flight4630  42286  ORD-DFW              2.3          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4628             0.833333               250       45250            11
4629             0.375000               200       33000            10

      Flight Year
4628         2014
4629         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4630  Flight4631  42315  ORD-JFK              1.8          56
4631  Flight4632  42301  ORD-SFO              2.3         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4630             0.812500               250       41250            11
4631             0.770833               375       61875            10

      Flight Year
4630         2015
4631         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4632  Flight4633  41979  ORD-BOS              2.6          69
4633  Flight4634  42195  ORD-MIA              3.1         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4632             0.833333               300       54300            12
4633             0.708333               330       61050             7

      Flight Year
4632         2014
4633         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4634  Flight4635  41738  ORD-PHX              0.7          32
4635  Flight4636  41825  ORD-DTW              3.2          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4634             0.791667             250.0     46250.0             4
4635             0.333333             126.5     20872.5             7

      Flight Year
4634         2014
4635         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4636  Flight4637  42196  ORD-FLL              3.4         209
4637  Flight4638  42090  ORD-DFW              2.2         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4636             0.291667               330       54450             7
4637             0.812500               200       37000             3

      Flight Year
4636         2015
4637         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4638  Flight4639  41906  ORD-MSP              1.7          59
4639  Flight4640  41661  ORD-LAS              3.0         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4638                0.750               115       18975             9
4639                0.375               275       45375             1

      Flight Year
4638         2014
4639         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4640  Flight4641  41871  ORD-IAH              3.1          76
4641  Flight4642  41913  ORD-ATL              9.1          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4640             0.333333               220       39820             8
4641             0.333333               200       36200            10

      Flight Year
4640         2014
4641         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4642  Flight4643  41944  ORD-IAD              0.3          43
4643  Flight4644  41785  ORD-CLT              2.4          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4642             0.791667               300       49500            11
4643             0.500000               125       20625             5

      Flight Year
4642         2014
4643         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4644  Flight4645  42365  ORD-ATL             14.7           2
4645  Flight4646  41806  ORD-PHX              0.8         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4644             0.291667               280       51800            12
4645             0.791667               275       50875             6

      Flight Year
4644         2015
4645         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4646  Flight4647  42074  ORD-LAS              1.8          58
4647  Flight4648  41871  ORD-BOS              3.1         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4646             0.750000               275       45375             3
4647             0.291667               330       61050             8

      Flight Year
4646         2015
4647         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4648  Flight4649  42063  ORD-DEN              0.9          74
4649  Flight4650  41675  ORD-MSP              2.6          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4648             0.875000               300       54300             2
4649             0.541667               115       21275             2

      Flight Year
4648         2015
4649         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4650  Flight4651  41925  ORD-CLT              1.7         165
4651  Flight4652  42134  ORD-MCO              1.5         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4650             0.416667               125       20625            10
4651             0.791667               250       41250             5

      Flight Year
4650         2014
4651         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4652  Flight4653  41673  ORD-MCO              1.7         154
4653  Flight4654  41774  ORD-PHX              2.4         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4652             0.854167               250       41250             2
4653             0.291667               250       41250             5

      Flight Year
4652         2014
4653         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4654  Flight4655  41965  ORD-LAS              2.1         160
4655  Flight4656  41653  ORD-SFO              2.1         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4654             0.500000               275       45375            11
4655             0.416667               375       69375             1

      Flight Year
4654         2014
4655         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4656  Flight4657  41956  ORD-PHX              2.6          42
4657  Flight4658  41870  ORD-LAS              3.0         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4656             0.791667             250.0     41250.0            11
4657             0.875000             302.5     49912.5             8

      Flight Year
4656         2014
4657         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4658  Flight4659  41903  ORD-DFW              3.6         106
4659  Flight4660  42204  ORD-JFK              1.0         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4658                 0.75               200       37000             9
4659                 0.75               275       45375             7

      Flight Year
4658         2014
4659         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4660  Flight4661  42280  ORD-DFW              2.5           2
4661  Flight4662  42203  ORD-MCO              1.4          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4660             0.812500               200       37000            10
4661             0.291667               275       45375             7

      Flight Year
4660         2015
4661         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4662  Flight4663  42335  ORD-SEA              4.2         115
4663  Flight4664  41893  ORD-DFW              1.5          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4662             0.416667               525       97125            11
4663             0.375000               200       33000             9

      Flight Year
4662         2015
4663         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4664  Flight4665  41740  ORD-JFK              0.7           3
4665  Flight4666  41874  ORD-SFO              2.4          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4664             0.812500             250.0     46250.0             4
4665             0.354167             412.5     74662.5             8

      Flight Year
4664         2014
4665         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4666  Flight4667  42213  ORD-EWR              0.5         136
4667  Flight4668  42228  ORD-MIA              3.8           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4666             0.416667             247.5     45787.5             7
4667             0.416667             330.0     61050.0             8

      Flight Year
4666         2015
4667         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4668  Flight4669  42322  ORD-BOS              1.5         177
4669  Flight4670  41811  ORD-DTW              1.9         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4668               0.7500             300.0     49500.0            11
4669               0.4375             126.5     20872.5             6

      Flight Year
4668         2015
4669         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4670  Flight4671  41827  ORD-LAS              2.1         180
4671  Flight4672  42297  ORD-ATL              9.4         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4670             0.833333             302.5     49912.5             7
4671             0.895833             200.0     33000.0            10

      Flight Year
4670         2014
4671         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4672  Flight4673  41832  ORD-MSP              1.9          13
4673  Flight4674  42241  ORD-LAX              6.3         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4672             0.833333             126.5     23402.5             7
4673             0.333333             385.0     71225.0             8

      Flight Year
4672         2014
4673         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4674  Flight4675  42034  ORD-DEN              0.7          78
4675  Flight4676  41804  ORD-PHL              2.2         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4674             0.708333             300.0     54300.0             1
4675             0.770833             302.5     49912.5             6

      Flight Year
4674         2015
4675         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4676  Flight4677  41879  ORD-LAX              5.2         205
4677  Flight4678  42283  ORD-ATL              8.7           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4676             0.895833               385       63525             8
4677             0.437500               200       37000            10

      Flight Year
4676         2014
4677         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4678  Flight4679  41673  ORD-SFO              1.5           5
4679  Flight4680  41767  ORD-EWR              2.1         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4678             0.750000               375       69375             2
4679             0.666667               225       41625             5

      Flight Year
4678         2014
4679         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4680  Flight4681  42115  ORD-IAH              2.8          35
4681  Flight4682  42219  ORD-LAX              4.7         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4680             0.562500               200       37000             4
4681             0.458333               385       63525             8

      Flight Year
4680         2015
4681         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4682  Flight4683  42077  ORD-DTW              1.0          10
4683  Flight4684  41932  ORD-DEN              1.4         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4682             0.291667               115       21275             3
4683             0.333333               300       49500            10

      Flight Year
4682         2015
4683         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4684  Flight4685  42327  ORD-PHX              2.2         169
4685  Flight4686  42174  ORD-LGA              2.1         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4684             0.291667             250.0     41250.0            11
4685             0.416667             302.5     55962.5             6

      Flight Year
4684         2015
4685         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4686  Flight4687  41822  ORD-ATL             10.7          61
4687  Flight4688  42234  ORD-MCO              1.9         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4686             0.354167               220       36300             7
4687             0.458333               275       45375             8

      Flight Year
4686         2014
4687         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4688  Flight4689  42229  ORD-ATL              8.7         173
4689  Flight4690  42268  ORD-IAH              1.2         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4688             0.291667               220       36300             8
4689             0.833333               200       33000             9

      Flight Year
4688         2015
4689         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4690  Flight4691  42196  ORD-LGA              2.7         184
4691  Flight4692  41792  ORD-LAX              4.4         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4690             0.291667             302.5     49912.5             7
4691             0.333333             385.0     63525.0             6

      Flight Year
4690         2015
4691         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4692  Flight4693  42083  ORD-JFK              2.3         108
4693  Flight4694  42235  ORD-DTW              2.7          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4692             0.333333             250.0     46250.0             3
4693             0.791667             126.5     23402.5             8

      Flight Year
4692         2015
4693         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4694  Flight4695  42125  ORD-IAH              2.2          36
4695  Flight4696  42016  ORD-LGA              1.2         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4694             0.812500               200       33000             5
4695             0.833333               275       50875             1

      Flight Year
4694         2015
4695         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4696  Flight4697  42272  ORD-LAS              1.4         204
4697  Flight4698  42092  ORD-ATL             11.5          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4696             0.333333               275       45375             9
4697             0.708333               200       37000             3

      Flight Year
4696         2015
4697         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4698  Flight4699  42207  ORD-JFK              2.2          62
4699  Flight4700  41652  ORD-BWI              0.3         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4698             0.312500               275       45375             7
4699             0.458333               240       44400             1

      Flight Year
4698         2015
4699         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4700  Flight4701  41683  ORD-MSP              1.7          64
4701  Flight4702  42183  ORD-MIA              1.1          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4700             0.708333               115       20815             2
4701             0.791667               330       54450             6

      Flight Year
4700         2014
4701         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4702  Flight4703  41834  ORD-PHX              2.4          77
4703  Flight4704  41849  ORD-MSP              1.9          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4702             0.750000             275.0     49775.0             7
4703             0.458333             126.5     23402.5             7

      Flight Year
4702         2014
4703         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4704  Flight4705  42169  ORD-PHX              2.3         104
4705  Flight4706  42060  ORD-MSP              3.1         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4704             0.729167               275       50875             6
4705             0.729167               115       18975             2

      Flight Year
4704         2015
4705         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4706  Flight4707  41863  ORD-PHL              1.7         151
4707  Flight4708  42222  ORD-PHX              2.2         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4706             0.833333             302.5     55962.5             8
4707             0.708333             275.0     50875.0             8

      Flight Year
4706         2014
4707         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4708  Flight4709  42063  ORD-LAS              1.7         185
4709  Flight4710  41674  ORD-LAX              3.4          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4708             0.375000               275       45375             2
4709             0.333333               350       63350             2

      Flight Year
4708         2015
4709         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4710  Flight4711  41803  ORD-ATL              9.0         196
4711  Flight4712  41897  ORD-SFO              2.2          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4710             0.354167               220       36300             6
4711             0.291667               375       67875             9

      Flight Year
4710         2014
4711         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4712  Flight4713  41809  ORD-MSP              3.0          69
4713  Flight4714  42344  ORD-ATL              7.9         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4712             0.708333             126.5     22896.5             6
4713             0.625000             200.0     37000.0            12

      Flight Year
4712         2014
4713         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4714  Flight4715  42181  ORD-MCO              2.2         123
4715  Flight4716  41892  ORD-LAX              4.4         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4714             0.791667               275       50875             6
4715             0.708333               350       64750             9

      Flight Year
4714         2015
4715         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4716  Flight4717  41827  ORD-DFW              1.7         156
4717  Flight4718  41995  ORD-ATL             12.4         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4716             0.583333               220       36300             7
4717             0.333333               280       46200            12

      Flight Year
4716         2014
4717         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4718  Flight4719  42046  ORD-ATL             11.7         106
4719  Flight4720  41960  ORD-CLT              1.6          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4718             0.479167               200       37000             2
4719             0.750000               125       20625            11

      Flight Year
4718         2015
4719         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4720  Flight4721  41928  ORD-DFW              2.2         171
4721  Flight4722  42305  ORD-LAX              3.5          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4720                0.625               200       33000            10
4721                0.750               350       63350            10

      Flight Year
4720         2014
4721         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4722  Flight4723  41697  ORD-MCO              2.2         122
4723  Flight4724  42117  ORD-DEN              1.1         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4722             0.812500               250       46250             2
4723             0.583333               300       55500             4

      Flight Year
4722         2014
4723         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4724  Flight4725  42169  ORD-DFW              1.7         150
4725  Flight4726  42217  ORD-EWR              1.6         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4724             0.750000             220.0     40700.0             6
4725             0.604167             247.5     45787.5             8

      Flight Year
4724         2015
4725         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4726  Flight4727  42338  ORD-ATL              8.7         178
4727  Flight4728  41784  ORD-EWR              3.7         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4726             0.875000               200       33000            11
4727             0.708333               225       41625             5

      Flight Year
4726         2015
4727         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4728  Flight4729  42162  ORD-DEN              2.2          66
4729  Flight4730  41997  ORD-BWI              2.5         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4728             0.708333               330       59730             6
4729             0.375000               336       62160            12

      Flight Year
4728         2015
4729         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4730  Flight4731  41862  ORD-SFO              1.9         210
4731  Flight4732  41761  ORD-ATL              8.1         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4730                0.375             412.5     68062.5             8
4731                0.750             200.0     37000.0             5

      Flight Year
4730         2014
4731         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4732  Flight4733  42186  ORD-SEA              2.3          98
4733  Flight4734  41947  ORD-JFK              2.6         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4732             0.333333               385       71225             7
4733             0.875000               250       46250            11

      Flight Year
4732         2015
4733         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4734  Flight4735  42332  ORD-CLT              4.9           9
4735  Flight4736  42319  ORD-LAX              3.1          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4734               0.3750             187.5     34687.5            11
4735               0.5625             350.0     57750.0            11

      Flight Year
4734         2015
4735         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4736  Flight4737  42092  ORD-ATL             10.0          56
4737  Flight4738  41863  ORD-MCO              2.7         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4736               0.4375               200       33000             3
4737               0.3125               275       45375             8

      Flight Year
4736         2015
4737         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4738  Flight4739  41833  ORD-LAX              5.9         136
4739  Flight4740  42010  ORD-SFO              1.5         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4738             0.416667               385       71225             7
4739             0.333333               375       69375             1

      Flight Year
4738         2014
4739         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4740  Flight4741  42022  ORD-PHX              2.9          26
4741  Flight4742  42026  ORD-LAX              5.2         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4740             0.708333               250       46250             1
4741             0.416667               350       57750             1

      Flight Year
4740         2015
4741         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4742  Flight4743  42216  ORD-JFK              2.7         112
4743  Flight4744  42158  ORD-LGA              1.4         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4742             0.291667             275.0     50875.0             7
4743             0.833333             302.5     49912.5             6

      Flight Year
4742         2015
4743         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4744  Flight4745  42343  ORD-ATL              9.4          60
4745  Flight4746  41715  ORD-CLT              2.7         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4744             0.875000               200       33000            12
4745             0.729167               125       20625             3

      Flight Year
4744         2015
4745         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4746  Flight4747  42350  ORD-PHX              2.6          83
4747  Flight4748  41988  ORD-LAS              1.1           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4746             0.770833               250       45250            12
4747             0.395833               275       50875            12

      Flight Year
4746         2015
4747         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4748  Flight4749  41871  ORD-ATL              9.9         102
4749  Flight4750  42177  ORD-DFW              1.9          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4748             0.791667               220       40700             8
4749             0.354167               220       40700             6

      Flight Year
4748         2014
4749         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4750  Flight4751  41956  ORD-JFK              1.5          86
4751  Flight4752  42358  ORD-ATL              7.4         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4750             0.875000               250       45250            11
4751             0.729167               200       33000            12

      Flight Year
4750         2014
4751         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4752  Flight4753  42119  ORD-IAH              1.1         184
4753  Flight4754  41755  ORD-SEA              0.9          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4752             0.791667               200       33000             4
4753             0.791667               350       57750             4

      Flight Year
4752         2015
4753         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4754  Flight4755  42175  ORD-MIA              0.7         111
4755  Flight4756  42245  ORD-MIA              1.4          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4754             0.708333               330       61050             6
4755             0.354167               330       61050             8

      Flight Year
4754         2015
4755         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4756  Flight4757  42365  ORD-ATL             10.9          21
4757  Flight4758  42101  ORD-SFO              1.0         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4756             0.708333               280       51800            12
4757             0.875000               375       69375             4

      Flight Year
4756         2015
4757         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4758  Flight4759  41978  ORD-LAX              4.3          90
4759  Flight4760  42240  ORD-ATL              6.9          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4758             0.541667               350       63350            12
4759             0.687500               220       40700             8

      Flight Year
4758         2014
4759         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4760  Flight4761  42140  ORD-SFO              1.0         163
4761  Flight4762  41830  ORD-DFW              1.9          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4760             0.708333               375       61875             5
4761             0.750000               220       39820             7

      Flight Year
4760         2015
4761         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4762  Flight4763  41878  ORD-IAH              2.4         106
4763  Flight4764  42199  ORD-PHX              1.4          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4762             0.291667               220       40700             8
4763             0.791667               275       50875             7

      Flight Year
4762         2014
4763         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4764  Flight4765  41679  ORD-MCO              1.8         120
4765  Flight4766  41748  ORD-MIA              1.2          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4764             0.291667               250       46250             2
4765             0.708333               300       54300             4

      Flight Year
4764         2014
4765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4766  Flight4767  42335  ORD-SEA              4.1           2
4767  Flight4768  41866  ORD-MIA              1.5          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4766             0.541667               525       97125            11
4767             0.854167               330       61050             8

      Flight Year
4766         2015
4767         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4768  Flight4769  41676  ORD-CLT              2.0          42
4769  Flight4770  42289  ORD-IAH              2.7          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4768             0.291667               125       20625             2
4769             0.791667               200       36200            10

      Flight Year
4768         2014
4769         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4770  Flight4771  41942  ORD-SEA              2.2         116
4771  Flight4772  41960  ORD-IAH              1.5           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4770             0.708333               350       64750            10
4771             0.333333               200       37000            11

      Flight Year
4770         2014
4771         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4772  Flight4773  42269  ORD-MIA              3.1         196
4773  Flight4774  41676  ORD-JFK              2.3          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4772             0.833333               300       49500             9
4773             0.708333               250       46250             2

      Flight Year
4772         2015
4773         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4774  Flight4775  41937  ORD-DEN              1.6         149
4775  Flight4776  42015  ORD-SFO              3.2         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4774             0.854167               300       55500            10
4775             0.291667               375       61875             1

      Flight Year
4774         2014
4775         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4776  Flight4777  41900  ORD-MCO              1.4         150
4777  Flight4778  41750  ORD-JFK              2.6          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4776             0.770833               250       46250             9
4777             0.750000               250       41250             4

      Flight Year
4776         2014
4777         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4778  Flight4779  41935  ORD-MIA              1.0          50
4779  Flight4780  41841  ORD-DFW              2.5          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4778             0.291667               300       49500            10
4779             0.666667               220       39820             7

      Flight Year
4778         2014
4779         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4780  Flight4781  41948  ORD-SFO              3.8         109
4781  Flight4782  42091  ORD-PHX              1.7         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4780             0.604167               375       69375            11
4781             0.729167               250       46250             3

      Flight Year
4780         2014
4781         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4782  Flight4783  41923  ORD-EWR              1.0         171
4783  Flight4784  41677  ORD-LAS              1.6         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4782             0.708333               225       37125            10
4783             0.791667               275       45375             2

      Flight Year
4782         2014
4783         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4784  Flight4785  41824  ORD-LAX              5.5          64
4785  Flight4786  41950  ORD-LAX              3.5          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4784             0.812500               385       69685             7
4785             0.291667               350       63350            11

      Flight Year
4784         2014
4785         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4786  Flight4787  42242  ORD-ATL             12.2         174
4787  Flight4788  42223  ORD-JFK              2.6         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4786               0.7500               220       36300             8
4787               0.3125               275       50875             8

      Flight Year
4786         2015
4787         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4788  Flight4789  41897  ORD-JFK              1.7         173
4789  Flight4790  42113  ORD-LAX              3.1         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4788             0.687500               250       41250             9
4789             0.291667               350       57750             4

      Flight Year
4788         2014
4789         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4790  Flight4791  41747  ORD-DFW              1.9         157
4791  Flight4792  42136  ORD-ATL             10.6         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4790             0.833333               200       33000             4
4791             0.729167               200       33000             5

      Flight Year
4790         2014
4791         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4792  Flight4793  42003  ORD-JFK              1.7         182
4793  Flight4794  42318  ORD-IAH              2.1         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4792                0.625               250       41250            12
4793                0.750               200       37000            11

      Flight Year
4792         2014
4793         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4794  Flight4795  42318  ORD-JFK              2.6          27
4795  Flight4796  41704  ORD-IAH              2.5         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4794             0.791667               250       46250            11
4795             0.708333               200       33000             3

      Flight Year
4794         2015
4795         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4796  Flight4797  41948  ORD-MIA              2.2         205
4797  Flight4798  41770  ORD-PHL              0.6         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4796             0.583333               300       49500            11
4797             0.541667               275       50875             5

      Flight Year
4796         2014
4797         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4798  Flight4799  41707  ORD-LAX              2.2         145
4799  Flight4800  42154  ORD-LAX              2.2         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4798             0.791667               350       64750             3
4799             0.437500               350       64750             5

      Flight Year
4798         2014
4799         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4800  Flight4801  42023  ORD-LAX              3.1         158
4801  Flight4802  41816  ORD-JFK              1.9          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4800             0.666667               350       57750             1
4801             0.750000               275       50875             6

      Flight Year
4800         2015
4801         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4802  Flight4803  41882  ORD-LAS              1.9         144
4803  Flight4804  41955  ORD-ATL             10.4          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4802             0.875000             302.5     55962.5             8
4803             0.791667             200.0     37000.0            11

      Flight Year
4802         2014
4803         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4804  Flight4805  41927  ORD-LAX              4.1          13
4805  Flight4806  42268  ORD-LGA              1.3         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4804             0.437500               350       64750            10
4805             0.291667               275       45375             9

      Flight Year
4804         2014
4805         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4806  Flight4807  41815  ORD-DFW              1.8         148
4807  Flight4808  41791  ORD-CLT              1.2          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4806             0.770833             220.0     40700.0             6
4807             0.875000             137.5     22687.5             6

      Flight Year
4806         2014
4807         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4808  Flight4809  41699  ORD-DFW              0.9         185
4809  Flight4810  42308  ORD-CLT              2.2          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4808             0.333333               200       33000             3
4809             0.666667               125       23125            10

      Flight Year
4808         2014
4809         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4810  Flight4811  42310  ORD-LAX                4          93
4811  Flight4812  42361  ORD-PHX                5          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4810             0.812500               350       64750            11
4811             0.291667               350       64750            12

      Flight Year
4810         2015
4811         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4812  Flight4813  42332  ORD-PHL              4.4          29
4813  Flight4814  41652  ORD-IAH              1.9          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4812             0.333333             412.5     76312.5            11
4813             0.333333             200.0     37000.0             1

      Flight Year
4812         2015
4813         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4814  Flight4815  41830  ORD-DFW              1.9         174
4815  Flight4816  42080  ORD-SFO              1.0         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4814             0.729167               220       36300             7
4815             0.541667               375       61875             3

      Flight Year
4814         2014
4815         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4816  Flight4817  41952  ORD-EWR              2.2          22
4817  Flight4818  41966  ORD-SEA              2.1          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4816             0.729167               225       41625            11
4817             0.708333               350       57750            11

      Flight Year
4816         2014
4817         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4818  Flight4819  41942  ORD-DEN              2.1         108
4819  Flight4820  41829  ORD-FLL              1.6          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4818             0.354167               300       55500            10
4819             0.750000               330       61050             7

      Flight Year
4818         2014
4819         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4820  Flight4821  42227  ORD-DFW              2.0          37
4821  Flight4822  42001  ORD-JFK              5.3         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4820             0.291667               220       36300             8
4821             0.291667               350       57750            12

      Flight Year
4820         2015
4821         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4822  Flight4823  42264  ORD-EWR              2.2         189
4823  Flight4824  41776  ORD-LAS              1.4         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4822             0.791667               225       37125             9
4823             0.729167               275       50875             5

      Flight Year
4822         2015
4823         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4824  Flight4825  41668  ORD-JFK              1.5         116
4825  Flight4826  42341  ORD-DEN              2.0         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4824             0.875000               250       46250             1
4825             0.833333               300       49500            12

      Flight Year
4824         2014
4825         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4826  Flight4827  41819  ORD-MSP              2.5         131
4827  Flight4828  42011  ORD-MIA              1.9          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4826             0.291667             126.5     23402.5             6
4827             0.291667             300.0     49500.0             1

      Flight Year
4826         2014
4827         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4828  Flight4829  42074  ORD-ATL             12.2         210
4829  Flight4830  41992  ORD-ATL              7.0         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4828             0.875000               200       33000             3
4829             0.479167               200       37000            12

      Flight Year
4828         2015
4829         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4830  Flight4831  42104  ORD-JFK              2.2         200
4831  Flight4832  41847  ORD-DFW              2.0          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4830             0.791667               250       41250             4
4831             0.770833               220       40700             7

      Flight Year
4830         2015
4831         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4832  Flight4833  42166  ORD-DEN              1.5         120
4833  Flight4834  42327  ORD-DTW              1.3         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4832             0.708333               330       61050             6
4833             0.500000               115       21275            11

      Flight Year
4832         2015
4833         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4834  Flight4835  41990  ORD-DEN              1.2          88
4835  Flight4836  42197  ORD-DFW              3.1           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4834             0.458333               300       54300            12
4835             0.729167               220       40700             7

      Flight Year
4834         2014
4835         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4836  Flight4837  42195  ORD-DEN              2.3          74
4837  Flight4838  42338  ORD-ATL              8.1         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4836             0.291667               330       59730             7
4837             0.333333               200       33000            11

      Flight Year
4836         2015
4837         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4838  Flight4839  41801  ORD-PHL              3.4          87
4839  Flight4840  41819  ORD-SFO              2.9         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4838             0.541667             302.5     54752.5             6
4839             0.291667             412.5     76312.5             6

      Flight Year
4838         2014
4839         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4840  Flight4841  41860  ORD-LAX              5.5         192
4841  Flight4842  42330  ORD-IAH              1.9          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4840             0.791667               385       63525             8
4841             0.791667               200       37000            11

      Flight Year
4840         2014
4841         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4842  Flight4843  42269  ORD-DTW              1.8          27
4843  Flight4844  41945  ORD-SFO              1.6          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4842             0.562500               115       21275             9
4843             0.791667               375       67875            11

      Flight Year
4842         2015
4843         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4844  Flight4845  41882  ORD-SEA              2.1         119
4845  Flight4846  41914  ORD-IAH              1.4         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4844             0.791667               385       71225             8
4845             0.458333               200       37000            10

      Flight Year
4844         2014
4845         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4846  Flight4847  41654  ORD-DEN              0.9          90
4847  Flight4848  41681  ORD-CLT              2.7         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4846             0.750000               300       54300             1
4847             0.291667               125       20625             2

      Flight Year
4846         2014
4847         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4848  Flight4849  41876  ORD-BOS              1.9          32
4849  Flight4850  42229  ORD-LGA              1.3          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4848             0.729167             330.0     61050.0             8
4849             0.375000             302.5     54752.5             8

      Flight Year
4848         2014
4849         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4850  Flight4851  41971  ORD-SEA              5.0         131
4851  Flight4852  42005  ORD-DEN              2.6          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4850             0.562500               525       97125            11
4851             0.333333               300       55500             1

      Flight Year
4850         2014
4851         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4852  Flight4853  41941  ORD-LAS              1.5         199
4853  Flight4854  42183  ORD-IAH              1.4          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4852             0.770833               275       45375            10
4853             0.750000               220       40700             6

      Flight Year
4852         2014
4853         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4854  Flight4855  42230  ORD-IAD              3.4         203
4855  Flight4856  42171  ORD-JFK              2.5           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4854             0.770833               330       54450             8
4855             0.562500               275       50875             6

      Flight Year
4854         2015
4855         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4856  Flight4857  41859  ORD-JFK              2.1         108
4857  Flight4858  41888  ORD-LAX              4.6          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4856             0.791667               275       50875             8
4857             0.583333               350       57750             9

      Flight Year
4856         2014
4857         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4858  Flight4859  42308  ORD-DTW              0.3          72
4859  Flight4860  41994  ORD-DTW              2.1          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4858             0.791667               115       20815            10
4859             0.625000               115       18975            12

      Flight Year
4858         2015
4859         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4860  Flight4861  41761  ORD-DEN              1.7          35
4861  Flight4862  41818  ORD-DEN              2.9         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4860             0.541667               300       55500             5
4861             0.708333               330       54450             6

      Flight Year
4860         2014
4861         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4862  Flight4863  42206  ORD-DEN              2.1         197
4863  Flight4864  42047  ORD-MIA              3.0          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4862             0.354167               330       54450             7
4863             0.312500               300       54300             2

      Flight Year
4862         2015
4863         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4864  Flight4865  42313  ORD-SEA              0.8         124
4865  Flight4866  42048  ORD-PHX              1.3         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4864             0.458333               350       64750            11
4865             0.312500               250       46250             2

      Flight Year
4864         2015
4865         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4866  Flight4867  42354  ORD-LAS              2.2         134
4867  Flight4868  42293  ORD-BOS              2.0         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4866             0.291667               275       50875            12
4867             0.312500               300       49500            10

      Flight Year
4866         2015
4867         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4868  Flight4869  42194  ORD-LAX              5.3          18
4869  Flight4870  41694  ORD-ATL              7.9          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4868             0.833333               385       71225             7
4869             0.291667               200       36200             2

      Flight Year
4868         2015
4869         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4870  Flight4871  42184  ORD-CLT              2.9          44
4871  Flight4872  42128  ORD-LAX              5.2          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4870             0.791667             137.5     22687.5             6
4871             0.520833             350.0     64750.0             5

      Flight Year
4870         2015
4871         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4872  Flight4873  41906  ORD-MIA              3.1          12
4873  Flight4874  42187  ORD-DEN              1.2          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4872             0.291667               300       55500             9
4873             0.791667               330       59730             7

      Flight Year
4872         2014
4873         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4874  Flight4875  42078  ORD-JFK              1.4          54
4875  Flight4876  41752  ORD-PHX              0.3         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4874             0.666667               250       41250             3
4875             0.333333               250       46250             4

      Flight Year
4874         2015
4875         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4876  Flight4877  41641  ORD-PHL              2.5         146
4877  Flight4878  41728  ORD-JFK              2.2         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4876             0.729167               275       50875             1
4877             0.291667               250       46250             3

      Flight Year
4876         2014
4877         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4878  Flight4879  41755  ORD-MIA              1.9         143
4879  Flight4880  41967  ORD-IAH              5.6         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4878             0.708333               300       55500             4
4879             0.708333               300       55500            11

      Flight Year
4878         2014
4879         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4880  Flight4881  41668  ORD-DEN              3.2         194
4881  Flight4882  41959  ORD-DFW              3.4           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4880             0.354167               300       49500             1
4881             0.354167               200       37000            11

      Flight Year
4880         2014
4881         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4882  Flight4883  42031  ORD-PHX              2.5         167
4883  Flight4884  42057  ORD-SFO              1.2         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4882             0.395833               250       41250             1
4883             0.750000               375       61875             2

      Flight Year
4882         2015
4883         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4884  Flight4885  42265  ORD-SEA              2.7           9
4885  Flight4886  42071  ORD-ATL             10.9          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4884             0.354167               350       64750             9
4885             0.708333               200       33000             3

      Flight Year
4884         2015
4885         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4886  Flight4887  41874  ORD-IAD              0.9          76
4887  Flight4888  41991  ORD-MCO              2.0           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4886             0.458333               330       59730             8
4887             0.875000               250       46250            12

      Flight Year
4886         2014
4887         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4888  Flight4889  41889  ORD-LAS              2.1          58
4889  Flight4890  41823  ORD-SEA              1.4         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4888             0.416667               275       45375             9
4889             0.750000               385       71225             7

      Flight Year
4888         2014
4889         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4890  Flight4891  41819  ORD-JFK              2.4         181
4891  Flight4892  41646  ORD-BOS              2.4         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4890             0.729167               275       45375             6
4891             0.708333               300       49500             1

      Flight Year
4890         2014
4891         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4892  Flight4893  42333  ORD-DEN              3.1         141
4893  Flight4894  41933  ORD-SFO              1.7          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4892             0.895833               450       83250            11
4893             0.312500               375       61875            10

      Flight Year
4892         2015
4893         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4894  Flight4895  42129  ORD-SEA              2.2          56
4895  Flight4896  42192  ORD-SFO              2.9         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4894             0.791667             350.0     57750.0             5
4895             0.291667             412.5     68062.5             7

      Flight Year
4894         2015
4895         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4896  Flight4897  41719  ORD-LAX              4.4          59
4897  Flight4898  41866  ORD-DFW              2.1          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4896             0.708333               350       57750             3
4897             0.708333               220       40700             8

      Flight Year
4896         2014
4897         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4898  Flight4899  41813  ORD-DFW              2.3          40
4899  Flight4900  41749  ORD-LAS              3.7          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4898             0.708333               220       36300             6
4899             0.729167               275       50875             4

      Flight Year
4898         2014
4899         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4900  Flight4901  42055  ORD-JFK              2.1         109
4901  Flight4902  42264  ORD-CLT              2.2         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4900             0.750000               250       46250             2
4901             0.291667               125       20625             9

      Flight Year
4900         2015
4901         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4902  Flight4903  41915  ORD-MCO              2.1          80
4903  Flight4904  41674  ORD-EWR              2.8          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4902             0.833333               250       45250            10
4903             0.645833               225       41625             2

      Flight Year
4902         2014
4903         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4904  Flight4905  41725  ORD-ATL              8.7         122
4905  Flight4906  41706  ORD-LAS              1.6          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4904             0.854167               200       37000             3
4905             0.458333               275       45375             3

      Flight Year
4904         2014
4905         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4906  Flight4907  41941  ORD-SFO              1.8         182
4907  Flight4908  41780  ORD-MCO              2.6          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4906             0.333333               375       61875            10
4907             0.687500               250       46250             5

      Flight Year
4906         2014
4907         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4908  Flight4909  42138  ORD-JFK              2.5          58
4909  Flight4910  41775  ORD-SFO              1.8          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4908             0.708333               250       41250             5
4909             0.708333               375       69375             5

      Flight Year
4908         2015
4909         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4910  Flight4911  42013  ORD-LAX              3.5          68
4911  Flight4912  41721  ORD-LAX              5.1          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4910             0.416667               350       63350             1
4911             0.875000               350       57750             3

      Flight Year
4910         2015
4911         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4912  Flight4913  42338  ORD-DTW              1.4         128
4913  Flight4914  41725  ORD-DFW              2.2          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4912               0.4375               115       21275            11
4913               0.6875               200       33000             3

      Flight Year
4912         2015
4913         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4914  Flight4915  41653  ORD-SEA             -0.3         192
4915  Flight4916  42019  ORD-SEA              2.7          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4914             0.812500               350       57750             1
4915             0.645833               350       64750             1

      Flight Year
4914         2014
4915         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4916  Flight4917  41882  ORD-PHX              1.9          82
4917  Flight4918  41908  ORD-LAX              2.9         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4916             0.458333               275       49775             8
4917             0.312500               350       57750             9

      Flight Year
4916         2014
4917         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4918  Flight4919  42005  ORD-PHL              1.9         155
4919  Flight4920  42228  ORD-JFK              1.4           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4918             0.854167               275       45375             1
4919             0.812500               275       50875             8

      Flight Year
4918         2015
4919         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4920  Flight4921  42220  ORD-FLL              1.9          33
4921  Flight4922  41751  ORD-ATL              9.1          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4920               0.7500               330       61050             8
4921               0.3125               200       33000             4

      Flight Year
4920         2015
4921         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4922  Flight4923  42102  ORD-PHX              1.2         160
4923  Flight4924  42274  ORD-ATL              9.1         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4922             0.708333               250       41250             4
4923             0.354167               200       37000             9

      Flight Year
4922         2015
4923         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4924  Flight4925  42006  ORD-PHX              0.9          73
4925  Flight4926  42134  ORD-MSP              2.8          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4924             0.750000               250       45250             1
4925             0.708333               115       18975             5

      Flight Year
4924         2015
4925         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4926  Flight4927  42100  ORD-SFO              1.7          46
4927  Flight4928  41956  ORD-MSP              1.9          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4926             0.666667               375       61875             4
4927             0.312500               115       18975            11

      Flight Year
4926         2015
4927         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4928  Flight4929  42156  ORD-EWR              2.9         144
4929  Flight4930  41786  ORD-LGA              1.6         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4928             0.666667             247.5     45787.5             6
4929             0.750000             275.0     50875.0             5

      Flight Year
4928         2015
4929         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4930  Flight4931  41897  ORD-SEA              1.7           8
4931  Flight4932  42326  ORD-DEN              1.3         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4930             0.791667               350       64750             9
4931             0.333333               300       49500            11

      Flight Year
4930         2014
4931         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4932  Flight4933  41965  ORD-SFO              1.5         165
4933  Flight4934  41732  ORD-JFK              3.0         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4932             0.687500               375       61875            11
4933             0.729167               250       46250             4

      Flight Year
4932         2014
4933         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4934  Flight4935  42188  ORD-DEN              2.6         181
4935  Flight4936  41915  ORD-ATL              7.6         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4934             0.791667               330       54450             7
4935             0.791667               200       33000            10

      Flight Year
4934         2015
4935         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4936  Flight4937  42068  ORD-MIA              2.3         126
4937  Flight4938  42056  ORD-MIA              0.8         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4936             0.750000               300       55500             3
4937             0.833333               300       49500             2

      Flight Year
4936         2015
4937         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4938  Flight4939  41706  ORD-MIA              3.0         166
4939  Flight4940  41972  ORD-ATL             17.7          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4938             0.354167               300       49500             3
4939             0.708333               300       49500            11

      Flight Year
4938         2014
4939         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4940  Flight4941  41937  ORD-DFW              1.1          34
4941  Flight4942  41948  ORD-BOS              2.5          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4940             0.645833               200       37000            10
4941             0.750000               300       55500            11

      Flight Year
4940         2014
4941         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4942  Flight4943  42024  ORD-LAX              4.2          82
4943  Flight4944  42363  ORD-MIA              2.7          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4942             0.833333               350       63350             1
4943             0.729167               420       77700            12

      Flight Year
4942         2015
4943         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4944  Flight4945  42284  ORD-ATL              8.7         125
4945  Flight4946  42063  ORD-LAX              5.2          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4944             0.291667               200       37000            10
4945             0.812500               350       63350             2

      Flight Year
4944         2015
4945         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4946  Flight4947  42338  ORD-MIA              1.3         210
4947  Flight4948  41864  ORD-JFK              1.8         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4946               0.7500               300       49500            11
4947               0.8125               275       45375             8

      Flight Year
4946         2015
4947         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4948  Flight4949  42204  ORD-DTW              2.6         154
4949  Flight4950  42307  ORD-EWR              2.0         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4948             0.291667             126.5     20872.5             7
4949             0.541667             225.0     37125.0            10

      Flight Year
4948         2015
4949         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4950  Flight4951  42210  ORD-PHL              1.3          77
4951  Flight4952  42159  ORD-DEN              3.5         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4950             0.708333             302.5     54752.5             7
4951             0.770833             330.0     61050.0             6

      Flight Year
4950         2015
4951         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4952  Flight4953  41755  ORD-DFW              2.9           3
4953  Flight4954  42360  ORD-IAD              5.4         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4952             0.541667               200       37000             4
4953             0.750000               420       77700            12

      Flight Year
4952         2014
4953         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4954  Flight4955  41668  ORD-MIA              2.1          19
4955  Flight4956  42119  ORD-ATL              9.8          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4954             0.291667               300       55500             1
4955             0.708333               200       37000             4

      Flight Year
4954         2014
4955         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4956  Flight4957  42192  ORD-DFW              2.3         102
4957  Flight4958  42169  ORD-PHX              1.7         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4956             0.708333               220       40700             7
4957             0.333333               275       50875             6

      Flight Year
4956         2015
4957         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4958  Flight4959  42171  ORD-DEN              2.4          72
4959  Flight4960  41948  ORD-JFK              1.9          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4958             0.437500               330       59730             6
4959             0.333333               250       45250            11

      Flight Year
4958         2015
4959         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4960  Flight4961  41798  ORD-PHX              2.9          96
4961  Flight4962  42224  ORD-ATL             11.5         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4960             0.833333               275       50875             6
4961             0.708333               220       36300             8

      Flight Year
4960         2014
4961         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4962  Flight4963  41969  ORD-IAH                4         119
4963  Flight4964  41973  ORD-MIA                5         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4962             0.708333               300       55500            11
4963             0.479167               450       74250            11

      Flight Year
4962         2014
4963         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4964  Flight4965  42070  ORD-SEA              2.5         113
4965  Flight4966  41967  ORD-SEA              6.3         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4964             0.812500               350       64750             3
4965             0.791667               525       86625            11

      Flight Year
4964         2015
4965         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4966  Flight4967  42331  ORD-BOS              5.3         139
4967  Flight4968  42242  ORD-BOS              2.0         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4966             0.541667               450       83250            11
4967             0.583333               330       54450             8

      Flight Year
4966         2015
4967         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4968  Flight4969  41885  ORD-LAS              1.8         184
4969  Flight4970  42293  ORD-BWI              1.8          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4968             0.770833               275       45375             9
4969             0.291667               240       44400            10

      Flight Year
4968         2014
4969         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4970  Flight4971  42161  ORD-BOS              1.8         175
4971  Flight4972  42182  ORD-MSP              2.8          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4970             0.666667             330.0     54450.0             6
4971             0.833333             126.5     20872.5             6

      Flight Year
4970         2015
4971         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4972  Flight4973  42012  ORD-PHL              1.6         197
4973  Flight4974  41659  ORD-LAS              2.8          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4972             0.791667               275       45375             1
4973             0.333333               275       45375             1

      Flight Year
4972         2015
4973         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4974  Flight4975  42211  ORD-SFO              1.9          24
4975  Flight4976  42031  ORD-DEN              2.2         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4974             0.833333             412.5     76312.5             7
4975             0.354167             300.0     55500.0             1

      Flight Year
4974         2015
4975         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4976  Flight4977  41815  ORD-LAX              4.8         150
4977  Flight4978  41968  ORD-DEN              4.7          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4976             0.562500               385       71225             6
4977             0.541667               450       81450            11

      Flight Year
4976         2014
4977         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4978  Flight4979  41829  ORD-SEA              2.3          10
4979  Flight4980  41854  ORD-EWR              1.9         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4978             0.520833             385.0     71225.0             7
4979             0.333333             247.5     45787.5             8

      Flight Year
4978         2014
4979         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4980  Flight4981  42103  ORD-SLC              2.0         122
4981  Flight4982  41714  ORD-DFW              3.4         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4980             0.708333               290       53650             4
4981             0.666667               200       37000             3

      Flight Year
4980         2015
4981         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4982  Flight4983  42367  ORD-JFK              2.3          72
4983  Flight4984  42260  ORD-IAD              2.3          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4982             0.729167               250       45250            12
4983             0.354167               300       55500             9

      Flight Year
4982         2015
4983         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4984  Flight4985  42165  ORD-ATL             10.5         146
4985  Flight4986  41685  ORD-LGA              1.1         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4984             0.520833               220       40700             6
4985             0.416667               275       45375             2

      Flight Year
4984         2015
4985         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4986  Flight4987  42237  ORD-EWR              2.3         188
4987  Flight4988  41972  ORD-SFO              4.6          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4986             0.500000             247.5     40837.5             8
4987             0.791667             562.5    101812.5            11

      Flight Year
4986         2015
4987         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4988  Flight4989  42314  ORD-PHL              2.4         207
4989  Flight4990  42240  ORD-BOS              1.6           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4988             0.750000               275       45375            11
4989             0.354167               330       61050             8

      Flight Year
4988         2015
4989         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4990  Flight4991  41943  ORD-MCO              1.0          15
4991  Flight4992  42147  ORD-IAH              2.2          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4990             0.354167               250       46250            10
4991             0.812500               200       33000             5

      Flight Year
4990         2014
4991         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4992  Flight4993  41720  ORD-JFK              1.2         107
4993  Flight4994  42212  ORD-CLT              1.3          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4992               0.3125             250.0     46250.0             3
4993               0.5000             137.5     24887.5             7

      Flight Year
4992         2014
4993         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4994  Flight4995  41988  ORD-ATL              9.3         208
4995  Flight4996  41878  ORD-EWR              2.6          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4994             0.812500             200.0     33000.0            12
4995             0.291667             247.5     45787.5             8

      Flight Year
4994         2014
4995         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4996  Flight4997  41789  ORD-FLL              2.0          98
4997  Flight4998  41805  ORD-ATL             11.6         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4996             0.791667               300       55500             5
4997             0.812500               220       40700             6

      Flight Year
4996         2014
4997         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
4998  Flight4999  42092  ORD-PHL              3.5          12
4999  Flight5000  42348  ORD-EWR              1.3         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
4998             0.416667               275       50875             3
4999             0.750000               225       41625            12

      Flight Year
4998         2015
4999         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5000  Flight5001  42210  ORD-PHX              2.3          99
5001  Flight5002  41877  ORD-JFK              1.9          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5000             0.791667               275       50875             7
5001             0.562500               275       50875             8

      Flight Year
5000         2015
5001         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5002  Flight5003  41860  ORD-MSP              2.6         140
5003  Flight5004  42268  ORD-SFO              1.9         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5002             0.833333             126.5     23402.5             8
5003             0.291667             375.0     69375.0             9

      Flight Year
5002         2014
5003         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5004  Flight5005  41768  ORD-EWR              2.3         180
5005  Flight5006  42060  ORD-BOS              1.5          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5004               0.8125               225       37125             5
5005               0.3750               300       49500             2

      Flight Year
5004         2014
5005         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5006  Flight5007  41836  ORD-ATL              8.8         148
5007  Flight5008  41840  ORD-IAH              2.3          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5006             0.666667               220       40700             7
5007             0.312500               220       40700             7

      Flight Year
5006         2014
5007         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5008  Flight5009  42146  ORD-MSP              0.1          16
5009  Flight5010  41690  ORD-EWR              2.5          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5008             0.354167               115       21275             5
5009             0.333333               225       37125             2

      Flight Year
5008         2015
5009         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5010  Flight5011  42050  ORD-EWR              2.3          47
5011  Flight5012  41707  ORD-ATL              7.2         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5010             0.750000               225       37125             2
5011             0.291667               200       37000             3

      Flight Year
5010         2015
5011         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5012  Flight5013  42156  ORD-SFO              0.7          41
5013  Flight5014  42164  ORD-JFK              2.7         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5012             0.291667             412.5     68062.5             6
5013             0.750000             275.0     45375.0             6

      Flight Year
5012         2015
5013         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5014  Flight5015  42240  ORD-EWR              2.2          42
5015  Flight5016  41873  ORD-JFK              2.3         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5014             0.708333             247.5     40837.5             8
5015             0.604167             275.0     45375.0             8

      Flight Year
5014         2015
5015         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5016  Flight5017  42346  ORD-LAX              3.6         194
5017  Flight5018  42135  ORD-PHX              1.2          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5016             0.354167               350       57750            12
5017             0.416667               250       45250             5

      Flight Year
5016         2015
5017         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5018  Flight5019  42005  ORD-DEN              2.5          75
5019  Flight5020  41789  ORD-PHX              0.9         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5018             0.541667               300       54300             1
5019             0.791667               250       46250             5

      Flight Year
5018         2015
5019         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5020  Flight5021  41728  ORD-LAX                5         147
5021  Flight5022  42332  ORD-DFW                3          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5020               0.7500               350       64750             3
5021               0.5625               300       55500            11

      Flight Year
5020         2014
5021         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5022  Flight5023  41801  ORD-FLL              2.8          46
5023  Flight5024  42301  ORD-LAS              3.1          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5022             0.416667               330       54450             6
5023             0.291667               275       45375            10

      Flight Year
5022         2014
5023         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5024  Flight5025  42202  ORD-CLT              1.8         189
5025  Flight5026  42273  ORD-EWR              2.8          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5024             0.333333             137.5     22687.5             7
5025             0.395833             225.0     41625.0             9

      Flight Year
5024         2015
5025         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5026  Flight5027  41992  ORD-PHL              1.3          23
5027  Flight5028  41745  ORD-ATL              9.6         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5026             0.812500               275       50875            12
5027             0.291667               200       37000             4

      Flight Year
5026         2014
5027         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5028  Flight5029  41673  ORD-MCO              1.3         167
5029  Flight5030  41937  ORD-SFO              1.4          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5028             0.333333               250       41250             2
5029             0.750000               375       69375            10

      Flight Year
5028         2014
5029         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5030  Flight5031  41738  ORD-LGA              2.7          65
5031  Flight5032  41794  ORD-PHX              1.4         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5030             0.291667               275       49775             4
5031             0.416667               275       50875             6

      Flight Year
5030         2014
5031         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5032  Flight5033  41643  ORD-JFK              2.4          55
5033  Flight5034  42331  ORD-ATL             16.3         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5032             0.708333               250       41250             1
5033             0.541667               300       55500            11

      Flight Year
5032         2014
5033         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5034  Flight5035  41894  ORD-CLT              1.8          38
5035  Flight5036  42241  ORD-MIA              2.9         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5034             0.395833               125       20625             9
5035             0.583333               330       54450             8

      Flight Year
5034         2014
5035         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5036  Flight5037  42093  ORD-LAX              5.3         136
5037  Flight5038  42091  ORD-BWI              2.0         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5036             0.750000               350       64750             3
5037             0.791667               240       44400             3

      Flight Year
5036         2015
5037         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5038  Flight5039  41879  ORD-LGA              0.4          86
5039  Flight5040  42250  ORD-MSP              0.7         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5038             0.333333             302.5     54752.5             8
5039             0.291667             115.0     21275.0             9

      Flight Year
5038         2014
5039         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5040  Flight5041  42095  ORD-DEN              2.5          98
5041  Flight5042  42128  ORD-SEA              2.2         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5040             0.833333               300       55500             4
5041             0.333333               350       57750             5

      Flight Year
5040         2015
5041         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5042  Flight5043  41770  ORD-PHX              0.5         209
5043  Flight5044  42047  ORD-PHX              2.2          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5042             0.791667               250       41250             5
5043             0.291667               250       46250             2

      Flight Year
5042         2014
5043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5044  Flight5045  41816  ORD-DTW              1.3         183
5045  Flight5046  41831  ORD-BOS              1.2         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5044             0.312500             126.5     20872.5             6
5045             0.708333             330.0     54450.0             7

      Flight Year
5044         2014
5045         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5046  Flight5047  42210  ORD-DFW              3.1         115
5047  Flight5048  41657  ORD-ATL             10.9         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5046             0.708333               220       40700             7
5047             0.833333               200       33000             1

      Flight Year
5046         2015
5047         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5048  Flight5049  42166  ORD-MIA              2.0          44
5049  Flight5050  42159  ORD-LAS              2.6         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5048               0.8750             330.0     54450.0             6
5049               0.8125             302.5     55962.5             6

      Flight Year
5048         2015
5049         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5050  Flight5051  41799  ORD-SFO              1.6         116
5051  Flight5052  42246  ORD-MCO              2.1         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5050             0.750000             412.5     76312.5             6
5051             0.583333             275.0     50875.0             8

      Flight Year
5050         2014
5051         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5052  Flight5053  42189  ORD-DEN              1.9          91
5053  Flight5054  42124  ORD-EWR              4.5          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5052                0.500               330       61050             7
5053                0.375               225       37125             4

      Flight Year
5052         2015
5053         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5054  Flight5055  42091  ORD-IAD              0.3         206
5055  Flight5056  41742  ORD-LAX              4.5          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5054                 0.75               300       49500             3
5055                 0.75               350       57750             4

      Flight Year
5054         2015
5055         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5056  Flight5057  42227  ORD-MCO              2.5         107
5057  Flight5058  41786  ORD-SFO              1.5          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5056             0.666667               275       50875             8
5057             0.791667               375       69375             5

      Flight Year
5056         2015
5057         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5058  Flight5059  42288  ORD-ATL              8.7          70
5059  Flight5060  42222  ORD-DFW              2.6           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5058             0.541667               200       36200            10
5059             0.375000               220       40700             8

      Flight Year
5058         2015
5059         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5060  Flight5061  42147  ORD-BWI              3.2          16
5061  Flight5062  42207  ORD-DEN              2.9         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5060             0.375000               240       44400             5
5061             0.645833               330       54450             7

      Flight Year
5060         2015
5061         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5062  Flight5063  42019  ORD-SEA              1.8         132
5063  Flight5064  42121  ORD-MSP              2.6           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5062             0.583333               350       64750             1
5063             0.333333               115       21275             4

      Flight Year
5062         2015
5063         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5064  Flight5065  42365  ORD-SFO              3.8          83
5065  Flight5066  41804  ORD-MIA              1.2         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5064             0.666667               525       95025            12
5065             0.750000               330       54450             6

      Flight Year
5064         2015
5065         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5066  Flight5067  42273  ORD-DEN              1.4         199
5067  Flight5068  42233  ORD-MCO              1.4         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5066             0.791667               300       49500             9
5067             0.291667               275       50875             8

      Flight Year
5066         2015
5067         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5068  Flight5069  42359  ORD-PHX              3.5          49
5069  Flight5070  41938  ORD-MIA              2.4         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5068             0.333333               350       57750            12
5069             0.708333               300       49500            10

      Flight Year
5068         2015
5069         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5070  Flight5071  41862  ORD-DEN              1.5         123
5071  Flight5072  41893  ORD-DFW              1.8          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5070               0.7500               330       61050             8
5071               0.8125               200       33000             9

      Flight Year
5070         2014
5071         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5072  Flight5073  41701  ORD-ATL              6.9           5
5073  Flight5074  41739  ORD-PHL              2.2          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5072             0.708333               200       37000             3
5073             0.750000               275       50875             4

      Flight Year
5072         2014
5073         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5074  Flight5075  41971  ORD-PHL                4          20
5075  Flight5076  42280  ORD-IAH                2          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5074             0.791667             412.5     76312.5            11
5075             0.729167             200.0     33000.0            10

      Flight Year
5074         2014
5075         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5076  Flight5077  41774  ORD-LAS              1.5         121
5077  Flight5078  42125  ORD-DFW              2.4          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5076             0.583333               275       50875             5
5077             0.395833               200       33000             5

      Flight Year
5076         2014
5077         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5078  Flight5079  41875  ORD-MIA              2.5         197
5079  Flight5080  41879  ORD-MSP              1.5          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5078             0.625000             330.0     54450.0             8
5079             0.291667             126.5     23402.5             8

      Flight Year
5078         2014
5079         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5080  Flight5081  42277  ORD-LAS              2.5         176
5081  Flight5082  42246  ORD-LAX              5.4          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5080             0.333333               275       45375             9
5081             0.750000               385       63525             8

      Flight Year
5080         2015
5081         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5082  Flight5083  41810  ORD-ATL              9.5          49
5083  Flight5084  42023  ORD-CLT              1.1          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5082               0.3125               220       36300             6
5083               0.3750               125       20625             1

      Flight Year
5082         2014
5083         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5084  Flight5085  41963  ORD-BOS              3.0           9
5085  Flight5086  41779  ORD-IAH              1.1         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5084             0.833333               300       55500            11
5085             0.708333               200       33000             5

      Flight Year
5084         2014
5085         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5086  Flight5087  41712  ORD-ATL              9.6         107
5087  Flight5088  42167  ORD-LAX              5.4         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5086             0.645833               200       37000             3
5087             0.291667               385       71225             6

      Flight Year
5086         2014
5087         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5088  Flight5089  41964  ORD-PHX             -0.1         210
5089  Flight5090  42327  ORD-ATL              9.7         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5088             0.791667               250       41250            11
5089             0.770833               200       37000            11

      Flight Year
5088         2014
5089         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5090  Flight5091  41994  ORD-EWR              2.4         179
5091  Flight5092  41788  ORD-BWI              2.5         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5090             0.791667               225       37125            12
5091             0.895833               240       44400             5

      Flight Year
5090         2014
5091         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5092  Flight5093  41861  ORD-SFO              1.3          53
5093  Flight5094  42268  ORD-ATL              8.1          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5092             0.354167             412.5     68062.5             8
5093             0.750000             200.0     36200.0             9

      Flight Year
5092         2014
5093         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5094  Flight5095  42012  ORD-DFW              2.8         207
5095  Flight5096  41684  ORD-PHX              2.6         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5094             0.291667               200       33000             1
5095             0.708333               250       41250             2

      Flight Year
5094         2015
5095         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5096  Flight5097  42332  ORD-LAS              2.9          97
5097  Flight5098  41999  ORD-DEN              3.6          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5096               0.3750             412.5     76312.5            11
5097               0.3125             420.0     77700.0            12

      Flight Year
5096         2015
5097         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5098  Flight5099  42127  ORD-ATL              8.9         156
5099  Flight5100  41900  ORD-IAH              2.6          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5098             0.312500               200       33000             5
5099             0.666667               200       36200             9

      Flight Year
5098         2015
5099         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5100  Flight5101  41908  ORD-BWI              1.7          58
5101  Flight5102  42153  ORD-LGA              2.7         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5100             0.666667               240       39600             9
5101             0.729167               275       45375             5

      Flight Year
5100         2014
5101         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5102  Flight5103  41857  ORD-LAX              5.4         178
5103  Flight5104  42208  ORD-MIA              2.5         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5102             0.500000               385       63525             8
5103             0.458333               330       54450             7

      Flight Year
5102         2014
5103         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5104  Flight5105  42303  ORD-DTW              2.2         171
5105  Flight5106  41796  ORD-LAX              4.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5104             0.750000               115       18975            10
5105             0.770833               385       69685             6

      Flight Year
5104         2015
5105         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5106  Flight5107  41751  ORD-MIA              1.1          78
5107  Flight5108  42241  ORD-DFW              2.4         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5106             0.895833               300       54300             4
5107             0.416667               220       40700             8

      Flight Year
5106         2014
5107         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5108  Flight5109  41659  ORD-MCO              1.4           6
5109  Flight5110  41787  ORD-DFW              2.0          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5108             0.791667               250       46250             1
5109             0.770833               200       33000             5

      Flight Year
5108         2014
5109         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5110  Flight5111  41683  ORD-JFK              1.4         155
5111  Flight5112  42200  ORD-DFW              1.2          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5110             0.791667               250       41250             2
5111             0.354167               220       40700             7

      Flight Year
5110         2014
5111         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5112  Flight5113  41956  ORD-PHL              2.4         204
5113  Flight5114  42249  ORD-BWI              3.0         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5112               0.5625               275       45375            11
5113               0.8125               240       44400             9

      Flight Year
5112         2014
5113         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5114  Flight5115  42333  ORD-ATL             19.0         179
5115  Flight5116  42215  ORD-LAS              0.6         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5114               0.6875             300.0     49500.0            11
5115               0.8125             302.5     49912.5             7

      Flight Year
5114         2015
5115         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5116  Flight5117  42047  ORD-MSP              2.7          84
5117  Flight5118  42148  ORD-SFO              1.2         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5116             0.375000               115       20815             2
5117             0.708333               375       61875             5

      Flight Year
5116         2015
5117         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5118  Flight5119  42104  ORD-BOS              2.7         146
5119  Flight5120  41953  ORD-LAS              1.9          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5118             0.875000               300       55500             4
5119             0.791667               275       50875            11

      Flight Year
5118         2015
5119         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5120  Flight5121  42000  ORD-LAX              9.6         201
5121  Flight5122  41649  ORD-MCO              1.8          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5120                0.375               490       80850            12
5121                0.750               250       41250             1

      Flight Year
5120         2014
5121         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5122  Flight5123  41723  ORD-MIA              2.0         110
5123  Flight5124  42361  ORD-LGA              3.1           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5122             0.833333               300       55500             3
5123             0.750000               385       71225            12

      Flight Year
5122         2014
5123         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5124  Flight5125  41773  ORD-JFK              3.0         141
5125  Flight5126  41730  ORD-SEA              1.4         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5124             0.833333               250       46250             5
5125             0.791667               350       64750             4

      Flight Year
5124         2014
5125         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5126  Flight5127  41830  ORD-SEA              1.1         136
5127  Flight5128  42033  ORD-PHX              2.1          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5126             0.812500               385       71225             7
5127             0.416667               250       46250             1

      Flight Year
5126         2014
5127         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5128  Flight5129  41966  ORD-SEA              2.7          51
5129  Flight5130  41724  ORD-IAD              2.1         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5128             0.333333               350       57750            11
5129             0.729167               300       49500             3

      Flight Year
5128         2014
5129         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5130  Flight5131  41996  ORD-CLT              2.0          41
5131  Flight5132  41973  ORD-ATL             17.8           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5130             0.541667               175       28875            12
5131             0.583333               300       55500            11

      Flight Year
5130         2014
5131         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5132  Flight5133  41821  ORD-ATL              9.4         168
5133  Flight5134  42047  ORD-LAS              1.7          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5132             0.791667               220       36300             7
5133             0.791667               275       50875             2

      Flight Year
5132         2014
5133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5134  Flight5135  42031  ORD-IAH              1.5          84
5135  Flight5136  41953  ORD-MSP              2.7         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5134                 0.75               200       36200             1
5135                 0.75               115       18975            11

      Flight Year
5134         2015
5135         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5136  Flight5137  41849  ORD-LAX              2.8           9
5137  Flight5138  41640  ORD-LAX              3.4          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5136             0.708333               385       71225             7
5137             0.708333               350       63350             1

      Flight Year
5136         2014
5137         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5138  Flight5139  42054  ORD-DFW              2.2         206
5139  Flight5140  42213  ORD-CLT              3.1          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5138             0.666667             200.0     33000.0             2
5139             0.708333             137.5     24887.5             7

      Flight Year
5138         2015
5139         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5140  Flight5141  41859  ORD-SFO              1.8           4
5141  Flight5142  41817  ORD-LGA              2.0          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5140             0.729167             412.5     76312.5             8
5141             0.708333             302.5     54752.5             6

      Flight Year
5140         2014
5141         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5142  Flight5143  41701  ORD-ATL              5.6         110
5143  Flight5144  42155  ORD-LAX              3.9         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5142             0.291667               200       37000             3
5143             0.770833               350       64750             5

      Flight Year
5142         2014
5143         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5144  Flight5145  42095  ORD-LAX              3.2          50
5145  Flight5146  41888  ORD-LGA              1.9          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5144                 0.75               350       57750             4
5145                 0.75               275       45375             9

      Flight Year
5144         2015
5145         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5146  Flight5147  41957  ORD-DEN              2.0         109
5147  Flight5148  42184  ORD-LAX              6.4         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5146               0.8750               300       55500            11
5147               0.3125               385       63525             6

      Flight Year
5146         2014
5147         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5148  Flight5149  42116  ORD-DFW              2.2          65
5149  Flight5150  41994  ORD-ATL              9.5          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5148             0.770833               200       36200             4
5149             0.312500               200       36200            12

      Flight Year
5148         2015
5149         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5150  Flight5151  42298  ORD-PHL              1.3         104
5151  Flight5152  42139  ORD-BWI              2.7         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5150             0.354167               275       50875            10
5151             0.354167               240       39600             5

      Flight Year
5150         2015
5151         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5152  Flight5153  42099  ORD-SEA              1.4          94
5153  Flight5154  42205  ORD-DFW              2.4          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5152             0.708333               350       64750             4
5153             0.708333               220       39820             7

      Flight Year
5152         2015
5153         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5154  Flight5155  42337  ORD-SFO              5.1          23
5155  Flight5156  41718  ORD-DFW              2.9          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5154             0.541667             562.5    104062.5            11
5155             0.625000             200.0     36200.0             3

      Flight Year
5154         2015
5155         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5156  Flight5157  41850  ORD-PHL              2.0         141
5157  Flight5158  41774  ORD-DFW              2.1          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5156             0.770833             302.5     55962.5             7
5157             0.583333             200.0     36200.0             5

      Flight Year
5156         2014
5157         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5158  Flight5159  42171  ORD-BOS              2.4         183
5159  Flight5160  41794  ORD-JFK              1.9         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5158             0.458333               330       54450             6
5159             0.708333               275       50875             6

      Flight Year
5158         2015
5159         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5160  Flight5161  42346  ORD-SEA              3.6         203
5161  Flight5162  41896  ORD-PHX              2.6          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5160                0.625               350       57750            12
5161                0.500               250       46250             9

      Flight Year
5160         2015
5161         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5162  Flight5163  42198  ORD-JFK              1.6         127
5163  Flight5164  42188  ORD-JFK              1.4          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5162             0.750000               275       50875             7
5163             0.791667               275       45375             7

      Flight Year
5162         2015
5163         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5164  Flight5165  42047  ORD-DFW              1.6          76
5165  Flight5166  41839  ORD-ATL             10.1         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5164             0.416667               200       36200             2
5165             0.708333               220       40700             7

      Flight Year
5164         2015
5165         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5166  Flight5167  42113  ORD-JFK              1.9          12
5167  Flight5168  42188  ORD-PHX              2.3          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5166             0.333333               250       46250             4
5167             0.291667               275       49775             7

      Flight Year
5166         2015
5167         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5168  Flight5169  41830  ORD-IAH              2.4         181
5169  Flight5170  41653  ORD-SEA              3.5         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5168             0.750000               220       36300             7
5169             0.333333               350       57750             1

      Flight Year
5168         2014
5169         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5170  Flight5171  41969  ORD-LGA              4.2          43
5171  Flight5172  41819  ORD-LAX              2.3          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5170                 0.75             412.5     68062.5            11
5171                 0.75             385.0     63525.0             6

      Flight Year
5170         2014
5171         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5172  Flight5173  41798  ORD-DTW              2.8         107
5173  Flight5174  42126  ORD-LAX              3.6          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5172             0.895833             126.5     23402.5             6
5173             0.812500             350.0     64750.0             5

      Flight Year
5172         2014
5173         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5174  Flight5175  42211  ORD-DEN              1.9          62
5175  Flight5176  41789  ORD-LGA              0.8          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5174             0.333333               330       54450             7
5175             0.750000               275       50875             5

      Flight Year
5174         2015
5175         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5176  Flight5177  41924  ORD-PHL              2.3          19
5177  Flight5178  42248  ORD-MIA              2.0         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5176             0.833333               275       50875            10
5177             0.791667               300       49500             9

      Flight Year
5176         2014
5177         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5178  Flight5179  41996  ORD-SEA              4.2         133
5179  Flight5180  41846  ORD-SEA              1.2         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5178             0.729167               490       90650            12
5179             0.395833               385       71225             7

      Flight Year
5178         2014
5179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5180  Flight5181  41970  ORD-CLT              3.8          37
5181  Flight5182  41868  ORD-CLT              1.4          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5180             0.458333             187.5     30937.5            11
5181             0.541667             137.5     22687.5             8

      Flight Year
5180         2014
5181         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5182  Flight5183  42254  ORD-JFK              0.8         113
5183  Flight5184  41687  ORD-PHX              2.4         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5182               0.8125               250       46250             9
5183               0.7500               250       46250             2

      Flight Year
5182         2015
5183         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5184  Flight5185  41885  ORD-CLT              2.8         205
5185  Flight5186  41796  ORD-MIA              2.6          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5184             0.791667               125       20625             9
5185             0.500000               330       61050             6

      Flight Year
5184         2014
5185         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5186  Flight5187  41968  ORD-ATL             16.8           3
5187  Flight5188  42099  ORD-CLT              2.3         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5186             0.354167               300       55500            11
5187             0.479167               125       23125             4

      Flight Year
5186         2014
5187         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5188  Flight5189  41802  ORD-ATL              9.3          88
5189  Flight5190  42033  ORD-CLT              2.2          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5188               0.3125               220       39820             6
5189               0.7500               125       22625             1

      Flight Year
5188         2014
5189         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5190  Flight5191  42119  ORD-FLL              3.3         194
5191  Flight5192  42197  ORD-JFK              0.8          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5190             0.583333               300       49500             4
5191             0.791667               275       50875             7

      Flight Year
5190         2015
5191         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5192  Flight5193  41748  ORD-MCO              1.4          30
5193  Flight5194  42066  ORD-SEA              1.9          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5192             0.291667               250       46250             4
5193             0.833333               350       63350             3

      Flight Year
5192         2014
5193         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5194  Flight5195  42245  ORD-MSP              1.4          81
5195  Flight5196  42293  ORD-ATL              7.6          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5194                0.750             126.5     22896.5             8
5195                0.625             200.0     36200.0            10

      Flight Year
5194         2015
5195         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5196  Flight5197  42308  ORD-PHL              2.3         165
5197  Flight5198  42001  ORD-CLT              2.7          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5196               0.7500               275       45375            10
5197               0.3125               175       28875            12

      Flight Year
5196         2015
5197         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5198  Flight5199  41725  ORD-MIA              0.8          71
5199  Flight5200  42168  ORD-DFW              1.4          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5198             0.395833               300       54300             3
5199             0.770833               220       39820             6

      Flight Year
5198         2014
5199         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5200  Flight5201  42084  ORD-DTW              1.5          76
5201  Flight5202  42362  ORD-LAX              8.4         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5200             0.708333               115       20815             3
5201             0.708333               490       90650            12

      Flight Year
5200         2015
5201         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5202  Flight5203  42120  ORD-CLT              1.8         186
5203  Flight5204  41804  ORD-DTW              0.6          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5202             0.750000             125.0     20625.0             4
5203             0.791667             126.5     23402.5             6

      Flight Year
5202         2015
5203         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5204  Flight5205  42042  ORD-FLL              1.2          95
5205  Flight5206  41903  ORD-LGA              2.2         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5204             0.333333               300       55500             2
5205             0.375000               275       50875             9

      Flight Year
5204         2015
5205         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5206  Flight5207  41848  ORD-DFW              3.1          88
5207  Flight5208  41742  ORD-CLT              2.9         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5206             0.875000               220       39820             7
5207             0.833333               125       20625             4

      Flight Year
5206         2014
5207         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5208  Flight5209  41740  ORD-DFW              2.1         115
5209  Flight5210  42183  ORD-EWR              1.8         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5208             0.729167             200.0     37000.0             4
5209             0.291667             247.5     45787.5             6

      Flight Year
5208         2014
5209         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5210  Flight5211  42076  ORD-CLT              2.2          16
5211  Flight5212  42023  ORD-LAS              2.4          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5210             0.333333               125       23125             3
5211             0.541667               275       49775             1

      Flight Year
5210         2015
5211         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5212  Flight5213  42185  ORD-ATL             10.0         142
5213  Flight5214  42274  ORD-SLC              3.4         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5212             0.854167               220       40700             6
5213             0.708333               290       47850             9

      Flight Year
5212         2015
5213         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5214  Flight5215  41820  ORD-CLT              2.5         193
5215  Flight5216  42324  ORD-LGA              1.3          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5214             0.708333             137.5     22687.5             6
5215             0.729167             275.0     45375.0            11

      Flight Year
5214         2014
5215         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5216  Flight5217  42272  ORD-DEN              1.9         171
5217  Flight5218  42118  ORD-SFO              1.6         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5216             0.708333               300       49500             9
5217             0.708333               375       69375             4

      Flight Year
5216         2015
5217         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5218  Flight5219  41805  ORD-LAS              1.1         191
5219  Flight5220  42177  ORD-MSP              3.0          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5218             0.416667             302.5     49912.5             6
5219             0.458333             126.5     20872.5             6

      Flight Year
5218         2014
5219         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5220  Flight5221  41691  ORD-PHL              0.9         103
5221  Flight5222  41913  ORD-ATL              8.5           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5220             0.875000               275       50875             2
5221             0.458333               200       37000            10

      Flight Year
5220         2014
5221         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5222  Flight5223  41747  ORD-SFO              2.6         110
5223  Flight5224  42288  ORD-CLT              1.3          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5222             0.791667               375       69375             4
5223             0.854167               125       23125            10

      Flight Year
5222         2014
5223         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5224  Flight5225  42322  ORD-MIA              0.7          33
5225  Flight5226  42179  ORD-BWI              0.9           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5224             0.750000               300       55500            11
5225             0.895833               264       48840             6

      Flight Year
5224         2015
5225         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5226  Flight5227  42041  ORD-DEN              1.3          50
5227  Flight5228  42172  ORD-CLT              2.2         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5226             0.291667             300.0     49500.0             2
5227             0.291667             137.5     25437.5             6

      Flight Year
5226         2015
5227         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5228  Flight5229  41850  ORD-MIA              0.4          14
5229  Flight5230  41995  ORD-CLT              2.2         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5228             0.708333               330       61050             7
5229             0.354167               175       32375            12

      Flight Year
5228         2014
5229         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5230  Flight5231  42086  ORD-LAS              2.5          72
5231  Flight5232  42322  ORD-DEN              0.5         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5230             0.333333               275       49775             3
5231             0.354167               300       49500            11

      Flight Year
5230         2015
5231         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5232  Flight5233  41854  ORD-DTW              0.8         139
5233  Flight5234  41830  ORD-SEA              1.2         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5232             0.645833             126.5     23402.5             8
5233             0.833333             385.0     63525.0             7

      Flight Year
5232         2014
5233         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5234  Flight5235  42088  ORD-MIA              3.1         185
5235  Flight5236  42222  ORD-EWR              2.1          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5234             0.541667             300.0     49500.0             3
5235             0.291667             247.5     45787.5             8

      Flight Year
5234         2015
5235         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5236  Flight5237  41774  ORD-LAS              1.1          97
5237  Flight5238  41890  ORD-SFO              2.0         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5236             0.708333               275       50875             5
5237             0.458333               375       69375             9

      Flight Year
5236         2014
5237         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5238  Flight5239  41841  ORD-LAX              7.0          98
5239  Flight5240  41718  ORD-LAX              5.2         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5238             0.291667               385       71225             7
5239             0.750000               350       57750             3

      Flight Year
5238         2014
5239         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5240  Flight5241  42166  ORD-MIA                2          30
5241  Flight5242  41913  ORD-JFK                1          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5240             0.437500               330       61050             6
5241             0.333333               250       45250            10

      Flight Year
5240         2015
5241         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5242  Flight5243  41757  ORD-MIA              2.3          51
5243  Flight5244  41878  ORD-PHX              2.8          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5242               0.6875               300       49500             4
5243               0.5000               275       50875             8

      Flight Year
5242         2014
5243         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5244  Flight5245  41995  ORD-LAX              7.6          92
5245  Flight5246  42058  ORD-DEN              1.9          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5244             0.875000               490       90650            12
5245             0.291667               300       55500             2

      Flight Year
5244         2014
5245         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5246  Flight5247  42219  ORD-DEN              0.9           3
5247  Flight5248  42114  ORD-LAX              3.8         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5246             0.333333               330       61050             8
5247             0.812500               350       57750             4

      Flight Year
5246         2015
5247         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5248  Flight5249  41960  ORD-IAH              2.8          72
5249  Flight5250  41721  ORD-MIA              2.6           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5248             0.500000               200       36200            11
5249             0.729167               300       55500             3

      Flight Year
5248         2014
5249         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5250  Flight5251  41733  ORD-DEN              1.7          30
5251  Flight5252  41900  ORD-PHX              2.6          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5250             0.666667               300       55500             4
5251             0.333333               250       46250             9

      Flight Year
5250         2014
5251         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5252  Flight5253  42021  ORD-JFK              2.3         114
5253  Flight5254  41812  ORD-DFW              2.0         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5252             0.729167               250       46250             1
5253             0.708333               220       36300             6

      Flight Year
5252         2015
5253         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5254  Flight5255  42101  ORD-JFK              2.1         139
5255  Flight5256  41751  ORD-LAX              6.6         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5254             0.333333               250       46250             4
5255             0.750000               350       64750             4

      Flight Year
5254         2015
5255         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5256  Flight5257  42307  ORD-BOS              2.4         155
5257  Flight5258  42288  ORD-PHL              1.9          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5256             0.791667               300       49500            10
5257             0.708333               275       50875            10

      Flight Year
5256         2015
5257         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5258  Flight5259  42126  ORD-LAX              5.0          41
5259  Flight5260  41654  ORD-ATL              8.3          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5258             0.312500               350       57750             5
5259             0.833333               200       33000             1

      Flight Year
5258         2015
5259         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5260  Flight5261  42173  ORD-ATL             10.7           4
5261  Flight5262  42208  ORD-LAS              1.5         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5260             0.875000             220.0     40700.0             6
5261             0.458333             302.5     49912.5             7

      Flight Year
5260         2015
5261         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5262  Flight5263  42226  ORD-JFK              2.7         121
5263  Flight5264  42245  ORD-MIA              1.7         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5262             0.833333               275       50875             8
5263             0.750000               330       54450             8

      Flight Year
5262         2015
5263         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5264  Flight5265  41972  ORD-SFO              5.2         135
5265  Flight5266  42256  ORD-MIA              2.6          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5264             0.708333             562.5    104062.5            11
5265             0.770833             300.0     49500.0             9

      Flight Year
5264         2014
5265         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5266  Flight5267  41840  ORD-CLT              2.7         104
5267  Flight5268  41933  ORD-JFK              2.1          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5266             0.375000             137.5     25437.5             7
5267             0.583333             250.0     46250.0            10

      Flight Year
5266         2014
5267         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5268  Flight5269  41987  ORD-SFO              1.9         101
5269  Flight5270  41996  ORD-BOS              2.1         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5268             0.750000               375       69375            12
5269             0.708333               420       77700            12

      Flight Year
5268         2014
5269         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5270  Flight5271  42198  ORD-MIA              1.8          71
5271  Flight5272  42234  ORD-ATL              6.9         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5270             0.291667               330       59730             7
5271             0.666667               220       36300             8

      Flight Year
5270         2015
5271         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5272  Flight5273  42020  ORD-PHL              0.9         143
5273  Flight5274  42121  ORD-CLT              1.0         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5272             0.708333               275       50875             1
5273             0.729167               125       23125             4

      Flight Year
5272         2015
5273         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5274  Flight5275  42331  ORD-CLT              5.9          30
5275  Flight5276  42010  ORD-FLL              2.4          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5274             0.750000             187.5     34687.5            11
5275             0.791667             300.0     55500.0             1

      Flight Year
5274         2015
5275         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5276  Flight5277  42356  ORD-SFO              0.8         188
5277  Flight5278  42149  ORD-ATL              8.4         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5276             0.770833               375       61875            12
5277             0.583333               200       33000             5

      Flight Year
5276         2015
5277         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5278  Flight5279  41985  ORD-DFW              2.6         206
5279  Flight5280  42186  ORD-DFW              2.0         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5278             0.729167               200       33000            12
5279             0.520833               220       36300             7

      Flight Year
5278         2014
5279         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5280  Flight5281  41708  ORD-JFK              1.8          75
5281  Flight5282  41660  ORD-PHX              2.5         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5280             0.291667               250       45250             3
5281             0.750000               250       41250             1

      Flight Year
5280         2014
5281         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5282  Flight5283  42333  ORD-JFK              4.5         110
5283  Flight5284  42220  ORD-LAS              1.3          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5282             0.562500             375.0     69375.0            11
5283             0.458333             302.5     54752.5             8

      Flight Year
5282         2015
5283         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5284  Flight5285  41868  ORD-LAX              3.7          77
5285  Flight5286  42144  ORD-MSP              2.3         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5284               0.7500               385       69685             8
5285               0.3125               115       18975             5

      Flight Year
5284         2014
5285         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5286  Flight5287  42130  ORD-CLT              2.0         132
5287  Flight5288  41941  ORD-LGA              2.3         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5286             0.291667               125       23125             5
5287             0.645833               275       45375            10

      Flight Year
5286         2015
5287         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5288  Flight5289  41835  ORD-ATL              7.8         174
5289  Flight5290  42360  ORD-DEN              3.8         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5288               0.4375               220       36300             7
5289               0.8750               420       77700            12

      Flight Year
5288         2014
5289         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5290  Flight5291  42341  ORD-JFK              1.8          86
5291  Flight5292  41865  ORD-EWR              2.7          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5290             0.729167             250.0     45250.0            12
5291             0.291667             247.5     44797.5             8

      Flight Year
5290         2015
5291         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5292  Flight5293  41673  ORD-CLT              2.7          72
5293  Flight5294  42222  ORD-ATL              6.2         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5292             0.291667               125       22625             2
5293             0.291667               220       40700             8

      Flight Year
5292         2014
5293         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5294  Flight5295  41851  ORD-SFO              2.5         117
5295  Flight5296  41852  ORD-ATL              7.4          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5294             0.875000             412.5     76312.5             7
5295             0.666667             220.0     39820.0             8

      Flight Year
5294         2014
5295         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5296  Flight5297  41979  ORD-CLT              2.1          18
5297  Flight5298  42050  ORD-LGA              2.2         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5296             0.895833               125       23125            12
5297             0.833333               275       45375             2

      Flight Year
5296         2014
5297         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5298  Flight5299  41978  ORD-SFO              2.2           8
5299  Flight5300  42045  ORD-PHX              1.7         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5298             0.291667               375       69375            12
5299             0.291667               250       41250             2

      Flight Year
5298         2014
5299         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5300  Flight5301  41710  ORD-MCO              1.1         132
5301  Flight5302  42082  ORD-DEN              2.6          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5300             0.833333               250       46250             3
5301             0.791667               300       54300             3

      Flight Year
5300         2014
5301         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5302  Flight5303  42331  ORD-EWR              5.6         112
5303  Flight5304  41845  ORD-ATL              9.3          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5302             0.750000             337.5     62437.5            11
5303             0.354167             220.0     39820.0             7

      Flight Year
5302         2015
5303         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5304  Flight5305  41771  ORD-EWR              1.2         190
5305  Flight5306  41957  ORD-MCO              1.3          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5304             0.333333               225       37125             5
5305             0.812500               250       46250            11

      Flight Year
5304         2014
5305         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5306  Flight5307  42004  ORD-DEN              1.4          60
5307  Flight5308  42173  ORD-LAX              7.1         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5306             0.312500               300       49500            12
5307             0.416667               385       63525             6

      Flight Year
5306         2014
5307         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5308  Flight5309  41703  ORD-PHX              1.3          80
5309  Flight5310  41903  ORD-CLT             -0.3          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5308             0.333333               250       45250             3
5309             0.708333               125       22625             9

      Flight Year
5308         2014
5309         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5310  Flight5311  42135  ORD-PHL              2.1         172
5311  Flight5312  42109  ORD-PHX              0.9          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5310             0.750000               275       45375             5
5311             0.729167               250       45250             4

      Flight Year
5310         2015
5311         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5312  Flight5313  42066  ORD-LAX              4.4         209
5313  Flight5314  41699  ORD-LAX              2.5           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5312             0.750000               350       57750             3
5313             0.895833               350       64750             3

      Flight Year
5312         2015
5313         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5314  Flight5315  41804  ORD-PHX              1.3         185
5315  Flight5316  41683  ORD-DFW              1.8          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5314             0.833333               275       45375             6
5315             0.833333               200       37000             2

      Flight Year
5314         2014
5315         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5316  Flight5317  42285  ORD-JFK              1.5          90
5317  Flight5318  42066  ORD-LAX              3.2         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5316             0.541667               250       45250            10
5317             0.812500               350       64750             3

      Flight Year
5316         2015
5317         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5318  Flight5319  42369  ORD-ATL              7.2         134
5319  Flight5320  41934  ORD-SEA              1.9           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5318             0.500000               200       37000            12
5319             0.791667               350       64750            10

      Flight Year
5318         2015
5319         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5320  Flight5321  41836  ORD-SEA              3.0          12
5321  Flight5322  41928  ORD-ATL             10.9          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5320               0.5000               385       71225             7
5321               0.3125               200       37000            10

      Flight Year
5320         2014
5321         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5322  Flight5323  42028  ORD-IAH              1.8         143
5323  Flight5324  42191  ORD-ATL             10.9          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5322             0.458333               200       37000             1
5323             0.500000               220       36300             7

      Flight Year
5322         2015
5323         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5324  Flight5325  41948  ORD-LAX              3.0          47
5325  Flight5326  42000  ORD-MSP              3.6          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5324             0.479167               350       57750            11
5325             0.291667               161       29785            12

      Flight Year
5324         2014
5325         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5326  Flight5327  41859  ORD-PHX              2.1         179
5327  Flight5328  42335  ORD-CLT              5.7         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5326               0.6875             275.0     45375.0             8
5327               0.5000             187.5     30937.5            11

      Flight Year
5326         2014
5327         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5328  Flight5329  41917  ORD-DEN              2.7          54
5329  Flight5330  42311  ORD-DFW              2.4         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5328             0.541667               300       49500            10
5329             0.645833               200       33000            11

      Flight Year
5328         2014
5329         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5330  Flight5331  41998  ORD-LAX              8.0         101
5331  Flight5332  42041  ORD-CLT              1.6         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5330             0.708333               490       90650            12
5331             0.791667               125       23125             2

      Flight Year
5330         2014
5331         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5332  Flight5333  41834  ORD-MCO              1.1         113
5333  Flight5334  42226  ORD-LGA              3.0         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5332             0.875000             275.0     50875.0             7
5333             0.708333             302.5     55962.5             8

      Flight Year
5332         2014
5333         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5334  Flight5335  41862  ORD-BOS              2.3         173
5335  Flight5336  42248  ORD-MIA              1.4         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5334             0.291667               330       54450             8
5335             0.333333               300       49500             9

      Flight Year
5334         2014
5335         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5336  Flight5337  42368  ORD-BOS              3.3         115
5337  Flight5338  41953  ORD-LAS              2.0          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5336             0.520833               300       55500            12
5337             0.625000               275       45375            11

      Flight Year
5336         2015
5337         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5338  Flight5339  41798  ORD-IAH              1.2         119
5339  Flight5340  41891  ORD-IAH              1.9          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5338             0.833333               220       40700             6
5339             0.333333               200       36200             9

      Flight Year
5338         2014
5339         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5340  Flight5341  41741  ORD-ATL              6.5         158
5341  Flight5342  41828  ORD-IAH              2.4          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5340             0.291667               200       33000             4
5341             0.750000               220       39820             7

      Flight Year
5340         2014
5341         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5342  Flight5343  41822  ORD-ATL              9.0          36
5343  Flight5344  42141  ORD-BOS              0.8          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5342             0.520833               220       36300             7
5343             0.770833               300       49500             5

      Flight Year
5342         2014
5343         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5344  Flight5345  41868  ORD-JFK              1.5         180
5345  Flight5346  41969  ORD-PHX              5.8         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5344               0.8125               275       45375             8
5345               0.3125               375       69375            11

      Flight Year
5344         2014
5345         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5346  Flight5347  41734  ORD-ATL              9.6         168
5347  Flight5348  41973  ORD-MIA              4.4          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5346             0.625000               200       33000             4
5347             0.895833               450       74250            11

      Flight Year
5346         2014
5347         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5348  Flight5349  42235  ORD-ATL              8.0         162
5349  Flight5350  42126  ORD-BOS              2.8          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5348             0.291667               220       36300             8
5349             0.458333               300       49500             5

      Flight Year
5348         2015
5349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5350  Flight5351  41703  ORD-LAS              1.8           5
5351  Flight5352  41985  ORD-PHX              1.6         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5350             0.708333               275       50875             3
5351             0.395833               250       46250            12

      Flight Year
5350         2014
5351         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5352  Flight5353  42190  ORD-DEN              2.8         168
5353  Flight5354  41818  ORD-FLL              2.4          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5352             0.500000               330       54450             7
5353             0.583333               330       59730             6

      Flight Year
5352         2015
5353         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5354  Flight5355  41829  ORD-ATL             10.7         143
5355  Flight5356  42288  ORD-DFW              2.5         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5354             0.312500               220       40700             7
5355             0.708333               200       37000            10

      Flight Year
5354         2014
5355         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5356  Flight5357  42343  ORD-LAS              1.7          82
5357  Flight5358  42089  ORD-LAX              5.1         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5356             0.604167               275       49775            12
5357             0.625000               350       57750             3

      Flight Year
5356         2015
5357         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5358  Flight5359  41889  ORD-SEA              1.6           2
5359  Flight5360  42356  ORD-IAH              1.4          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5358             0.833333               350       64750             9
5359             0.875000               200       33000            12

      Flight Year
5358         2014
5359         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5360  Flight5361  41884  ORD-PHL              1.3         139
5361  Flight5362  41681  ORD-PHX              2.6         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5360             0.812500               275       50875             9
5361             0.291667               250       46250             2

      Flight Year
5360         2014
5361         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5362  Flight5363  42234  ORD-DFW              3.2         208
5363  Flight5364  42144  ORD-BOS              2.2          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5362             0.645833               220       36300             8
5363             0.291667               300       49500             5

      Flight Year
5362         2015
5363         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5364  Flight5365  42126  ORD-PHX              1.7          47
5365  Flight5366  42159  ORD-FLL              1.4         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5364             0.729167               250       41250             5
5365             0.604167               330       61050             6

      Flight Year
5364         2015
5365         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5366  Flight5367  42033  ORD-JFK              2.1          43
5367  Flight5368  42018  ORD-PHX              2.7         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5366             0.500000               250       41250             1
5367             0.583333               250       46250             1

      Flight Year
5366         2015
5367         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5368  Flight5369  41886  ORD-PHX              1.3          45
5369  Flight5370  42355  ORD-IAH              2.3         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5368             0.291667               250       41250             9
5369             0.312500               200       33000            12

      Flight Year
5368         2014
5369         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5370  Flight5371  41992  ORD-SFO              3.0          43
5371  Flight5372  41956  ORD-BWI              2.3         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5370             0.833333               375       61875            12
5371             0.708333               240       44400            11

      Flight Year
5370         2014
5371         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5372  Flight5373  42064  ORD-LAS              1.5           3
5373  Flight5374  41852  ORD-DFW              2.1          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5372             0.354167               275       50875             3
5373             0.291667               220       40700             8

      Flight Year
5372         2015
5373         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5374  Flight5375  42146  ORD-DFW              2.2           8
5375  Flight5376  41865  ORD-SFO              2.8          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5374             0.604167             200.0     37000.0             5
5375             0.750000             412.5     76312.5             8

      Flight Year
5374         2015
5375         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5376  Flight5377  42106  ORD-LAX              4.6         116
5377  Flight5378  41774  ORD-SFO              1.6          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5376             0.791667               350       64750             4
5377             0.708333               375       67875             5

      Flight Year
5376         2015
5377         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5378  Flight5379  41921  ORD-ATL              6.7         140
5379  Flight5380  41798  ORD-DEN              2.1         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5378             0.750000               200       37000            10
5379             0.333333               330       54450             6

      Flight Year
5378         2014
5379         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5380  Flight5381  41813  ORD-DFW              1.3         145
5381  Flight5382  41927  ORD-JFK              1.7          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5380             0.729167               220       40700             6
5381             0.750000               250       46250            10

      Flight Year
5380         2014
5381         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5382  Flight5383  41975  ORD-PHL              0.5         135
5383  Flight5384  41643  ORD-JFK              2.1         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5382             0.708333               275       50875            12
5383             0.395833               250       46250             1

      Flight Year
5382         2014
5383         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5384  Flight5385  42126  ORD-FLL              2.7          24
5385  Flight5386  41718  ORD-DEN              2.5         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5384             0.666667               300       55500             5
5385             0.291667               300       55500             3

      Flight Year
5384         2015
5385         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5386  Flight5387  41767  ORD-LAX              3.6         102
5387  Flight5388  41847  ORD-DEN              2.1          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5386             0.791667               350       64750             5
5387             0.875000               330       61050             7

      Flight Year
5386         2014
5387         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5388  Flight5389  42345  ORD-MSP              1.3         131
5389  Flight5390  41802  ORD-MCO              2.4         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5388             0.291667               115       21275            12
5389             0.791667               275       45375             6

      Flight Year
5388         2015
5389         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5390  Flight5391  41948  ORD-DFW              1.4          32
5391  Flight5392  42286  ORD-LAS              1.5          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5390                 0.75               200       37000            11
5391                 0.50               275       50875            10

      Flight Year
5390         2014
5391         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5392  Flight5393  42345  ORD-CLT              1.9           7
5393  Flight5394  41777  ORD-DFW              1.9         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5392             0.791667               125       23125            12
5393             0.791667               200       37000             5

      Flight Year
5392         2015
5393         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5394  Flight5395  41844  ORD-MCO              1.9         121
5395  Flight5396  41812  ORD-IAD              1.8          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5394             0.541667               275       50875             7
5395             0.375000               330       59730             6

      Flight Year
5394         2014
5395         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5396  Flight5397  42207  ORD-LGA              2.4          29
5397  Flight5398  42032  ORD-DTW              1.4         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5396             0.833333             302.5     55962.5             7
5397             0.708333             115.0     18975.0             1

      Flight Year
5396         2015
5397         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5398  Flight5399  41929  ORD-LGA              1.3         158
5399  Flight5400  42221  ORD-LAX              4.7          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5398             0.750000               275       45375            10
5399             0.458333               385       69685             8

      Flight Year
5398         2014
5399         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5400  Flight5401  42190  ORD-PHL              1.3          49
5401  Flight5402  42247  ORD-LGA              1.9         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5400             0.791667             302.5     49912.5             7
5401             0.791667             302.5     49912.5             8

      Flight Year
5400         2015
5401         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5402  Flight5403  42035  ORD-CLT              3.7           7
5403  Flight5404  41968  ORD-LAX             10.6         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5402             0.500000               125       23125             1
5403             0.333333               525       97125            11

      Flight Year
5402         2015
5403         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5404  Flight5405  42029  ORD-DFW              2.6         145
5405  Flight5406  41642  ORD-DFW              1.6         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5404             0.583333               200       37000             1
5405             0.708333               200       33000             1

      Flight Year
5404         2015
5405         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5406  Flight5407  41658  ORD-SFO              1.8          13
5407  Flight5408  41662  ORD-PHX              2.7          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5406             0.833333               375       69375             1
5407             0.729167               250       45250             1

      Flight Year
5406         2014
5407         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5408  Flight5409  42092  ORD-DFW              2.1         196
5409  Flight5410  41831  ORD-CLT              2.6          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5408                0.875             200.0     33000.0             3
5409                0.750             137.5     22687.5             7

      Flight Year
5408         2015
5409         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5410  Flight5411  41643  ORD-MSP              2.4         186
5411  Flight5412  42054  ORD-IAH              3.6          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5410             0.812500               115       18975             1
5411             0.708333               200       33000             2

      Flight Year
5410         2014
5411         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5412  Flight5413  42044  ORD-JFK              2.6         210
5413  Flight5414  42149  ORD-PHX              2.1         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5412             0.666667               250       41250             2
5413             0.812500               250       41250             5

      Flight Year
5412         2015
5413         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5414  Flight5415  41850  ORD-MCO              3.3         100
5415  Flight5416  41651  ORD-ATL             10.2          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5414             0.541667               275       50875             7
5415             0.333333               200       37000             1

      Flight Year
5414         2014
5415         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5416  Flight5417  42227  ORD-PHX              1.8          28
5417  Flight5418  41958  ORD-JFK              2.8         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5416             0.458333               275       50875             8
5417             0.291667               250       41250            11

      Flight Year
5416         2015
5417         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5418  Flight5419  41848  ORD-DTW              1.6          87
5419  Flight5420  41709  ORD-IAH              3.3         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5418             0.708333             126.5     22896.5             7
5419             0.291667             200.0     37000.0             3

      Flight Year
5418         2014
5419         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5420  Flight5421  41729  ORD-DEN              1.2         103
5421  Flight5422  42017  ORD-ATL              8.3          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5420             0.833333               300       55500             3
5421             0.812500               200       33000             1

      Flight Year
5420         2014
5421         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5422  Flight5423  41674  ORD-PHX              2.2           3
5423  Flight5424  41840  ORD-CLT              3.0         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5422             0.791667             250.0     46250.0             2
5423             0.812500             137.5     22687.5             7

      Flight Year
5422         2014
5423         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5424  Flight5425  42080  ORD-JFK              2.8         169
5425  Flight5426  42358  ORD-SEA              2.8         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5424             0.583333               250       41250             3
5425             0.458333               350       57750            12

      Flight Year
5424         2015
5425         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5426  Flight5427  41784  ORD-SFO              4.0         205
5427  Flight5428  42196  ORD-LGA              1.1         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5426             0.708333             375.0     61875.0             5
5427             0.291667             302.5     55962.5             7

      Flight Year
5426         2014
5427         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5428  Flight5429  42245  ORD-LAS              2.5          94
5429  Flight5430  41996  ORD-MIA              3.9         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5428             0.291667             302.5     55962.5             8
5429             0.708333             420.0     69300.0            12

      Flight Year
5428         2015
5429         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5430  Flight5431  42367  ORD-DFW              2.2          70
5431  Flight5432  41828  ORD-LAS              2.0         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5430             0.833333             200.0     36200.0            12
5431             0.708333             302.5     49912.5             7

      Flight Year
5430         2015
5431         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5432  Flight5433  42319  ORD-SFO              3.1          22
5433  Flight5434  42183  ORD-IAH              1.7          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5432             0.375000               375       69375            11
5433             0.416667               220       36300             6

      Flight Year
5432         2015
5433         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5434  Flight5435  41971  ORD-IAH              6.0         133
5435  Flight5436  42132  ORD-DEN              1.8         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5434             0.416667               300       55500            11
5435             0.750000               300       55500             5

      Flight Year
5434         2014
5435         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5436  Flight5437  42183  ORD-JFK              1.8          51
5437  Flight5438  42088  ORD-SEA              2.3         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5436             0.312500               275       45375             6
5437             0.791667               350       64750             3

      Flight Year
5436         2015
5437         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5438  Flight5439  42024  ORD-DFW              0.5         199
5439  Flight5440  41848  ORD-DEN              1.7         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5438             0.895833               200       33000             1
5439             0.541667               330       54450             7

      Flight Year
5438         2015
5439         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5440  Flight5441  41941  ORD-SFO              2.6         139
5441  Flight5442  42346  ORD-ATL              9.6         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5440             0.479167               375       69375            10
5441             0.666667               200       37000            12

      Flight Year
5440         2014
5441         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5442  Flight5443  41801  ORD-PHL              3.5          61
5443  Flight5444  42257  ORD-MCO              2.8         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5442             0.625000             302.5     49912.5             6
5443             0.708333             250.0     41250.0             9

      Flight Year
5442         2014
5443         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5444  Flight5445  41913  ORD-DFW              2.7          78
5445  Flight5446  41695  ORD-ATL              8.1          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5444             0.395833               200       36200            10
5445             0.875000               200       37000             2

      Flight Year
5444         2014
5445         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5446  Flight5447  42198  ORD-MCO              2.5         181
5447  Flight5448  42336  ORD-SFO              6.6         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5446             0.291667             275.0     45375.0             7
5447             0.354167             562.5    104062.5            11

      Flight Year
5446         2015
5447         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5448  Flight5449  42267  ORD-DEN              1.7          95
5449  Flight5450  42146  ORD-MIA              2.1         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5448             0.333333               300       55500             9
5449             0.791667               300       49500             5

      Flight Year
5448         2015
5449         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5450  Flight5451  42080  ORD-SEA              2.1         137
5451  Flight5452  42312  ORD-SFO              2.8         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5450             0.666667               350       64750             3
5451             0.291667               375       69375            11

      Flight Year
5450         2015
5451         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5452  Flight5453  41894  ORD-PHX              1.7          10
5453  Flight5454  42252  ORD-PHX              2.8          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5452             0.666667               250       46250             9
5453             0.416667               250       41250             9

      Flight Year
5452         2014
5453         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5454  Flight5455  41655  ORD-EWR              1.7          40
5455  Flight5456  42331  ORD-LAX             11.9          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5454             0.791667               225       37125             1
5455             0.875000               525       97125            11

      Flight Year
5454         2014
5455         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5456  Flight5457  41878  ORD-FLL              1.6         149
5457  Flight5458  41898  ORD-DEN              1.6         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5456             0.520833               330       61050             8
5457             0.750000               300       55500             9

      Flight Year
5456         2014
5457         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5458  Flight5459  42048  ORD-MCO              1.5         141
5459  Flight5460  42359  ORD-IAH              2.9         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5458             0.750000               250       46250             2
5459             0.520833               280       51800            12

      Flight Year
5458         2015
5459         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5460  Flight5461  42064  ORD-DFW              1.8          70
5461  Flight5462  41746  ORD-DTW              2.6          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5460                 0.75               200       36200             3
5461                 0.50               115       18975             4

      Flight Year
5460         2015
5461         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5462  Flight5463  42182  ORD-SFO              2.3         186
5463  Flight5464  42202  ORD-SFO              2.5          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5462             0.333333             412.5     68062.5             6
5463             0.541667             412.5     68062.5             7

      Flight Year
5462         2015
5463         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5464  Flight5465  41878  ORD-DFW              1.6          29
5465  Flight5466  41949  ORD-LAX              1.9         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5464             0.750000               220       40700             8
5465             0.458333               350       57750            11

      Flight Year
5464         2014
5465         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5466  Flight5467  41974  ORD-SEA              1.2          27
5467  Flight5468  42362  ORD-DEN              4.4          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5466             0.770833               350       64750            12
5467             0.687500               420       77700            12

      Flight Year
5466         2014
5467         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5468  Flight5469  42273  ORD-MIA              1.9         153
5469  Flight5470  41723  ORD-SEA              0.5           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5468             0.708333               300       49500             9
5469             0.791667               350       64750             3

      Flight Year
5468         2015
5469         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5470  Flight5471  41861  ORD-DEN              1.1         117
5471  Flight5472  42163  ORD-ATL             11.6         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5470             0.291667               330       61050             8
5471             0.770833               220       36300             6

      Flight Year
5470         2014
5471         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5472  Flight5473  42069  ORD-MSP              1.8         136
5473  Flight5474  42041  ORD-LGA              1.9          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5472             0.875000               115       21275             3
5473             0.833333               275       50875             2

      Flight Year
5472         2015
5473         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5474  Flight5475  42302  ORD-BOS              2.1         148
5475  Flight5476  42352  ORD-DFW              2.9          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5474                 0.75               300       55500            10
5475                 0.75               200       37000            12

      Flight Year
5474         2015
5475         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5476  Flight5477  42037  ORD-LGA              2.2           6
5477  Flight5478  41657  ORD-SFO              1.5          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5476             0.854167               275       50875             2
5477             0.729167               375       69375             1

      Flight Year
5476         2015
5477         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5478  Flight5479  42306  ORD-EWR              1.2         183
5479  Flight5480  42187  ORD-SEA              0.7          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5478                 0.50               225       37125            10
5479                 0.75               385       71225             7

      Flight Year
5478         2015
5479         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5480  Flight5481  42346  ORD-SEA              1.8           3
5481  Flight5482  41932  ORD-DTW              1.2         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5480             0.291667               350       64750            12
5481             0.729167               115       18975            10

      Flight Year
5480         2015
5481         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5482  Flight5483  42239  ORD-PHX              1.7          66
5483  Flight5484  42316  ORD-IAH              2.1         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5482             0.708333               275       49775             8
5483             0.333333               200       33000            11

      Flight Year
5482         2015
5483         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5484  Flight5485  41870  ORD-DEN              1.5          79
5485  Flight5486  41781  ORD-PHX              2.3          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5484             0.770833               330       59730             8
5485             0.791667               250       46250             5

      Flight Year
5484         2014
5485         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5486  Flight5487  41695  ORD-MCO              2.3          46
5487  Flight5488  42112  ORD-SEA              2.2          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5486             0.812500               250       41250             2
5487             0.833333               350       64750             4

      Flight Year
5486         2014
5487         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5488  Flight5489  42197  ORD-DFW              1.4         137
5489  Flight5490  42253  ORD-MSP              1.7         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5488               0.3125               220       40700             7
5489               0.7500               115       18975             9

      Flight Year
5488         2015
5489         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5490  Flight5491  41835  ORD-LAX              4.4         183
5491  Flight5492  42057  ORD-MCO              1.7         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5490             0.541667               385       63525             7
5491             0.479167               250       46250             2

      Flight Year
5490         2014
5491         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5492  Flight5493  42212  ORD-SEA              1.4         119
5493  Flight5494  42209  ORD-CLT              1.2         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5492             0.708333             385.0     71225.0             7
5493             0.562500             137.5     22687.5             7

      Flight Year
5492         2015
5493         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5494  Flight5495  42098  ORD-EWR              1.0         197
5495  Flight5496  42193  ORD-MCO              1.5         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5494             0.833333               225       37125             4
5495             0.687500               275       50875             7

      Flight Year
5494         2015
5495         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5496  Flight5497  42269  ORD-MSP              2.1          83
5497  Flight5498  41688  ORD-SEA              1.0         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5496               0.8125               115       20815             9
5497               0.5000               350       64750             2

      Flight Year
5496         2015
5497         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5498  Flight5499  42325  ORD-MIA              2.9         209
5499  Flight5500  42091  ORD-JFK              1.5         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5498             0.791667               300       49500            11
5499             0.375000               250       46250             3

      Flight Year
5498         2015
5499         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5500  Flight5501  42163  ORD-LAS              1.0         195
5501  Flight5502  41845  ORD-ATL             11.4         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5500             0.291667             302.5     49912.5             6
5501             0.395833             220.0     36300.0             7

      Flight Year
5500         2015
5501         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5502  Flight5503  42010  ORD-DEN              1.8          45
5503  Flight5504  41919  ORD-ATL             10.6         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5502             0.875000               300       49500             1
5503             0.833333               200       37000            10

      Flight Year
5502         2015
5503         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5504  Flight5505  42324  ORD-DFW              1.5         154
5505  Flight5506  41999  ORD-JFK              1.0         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5504             0.541667               200       33000            11
5505             0.604167               350       57750            12

      Flight Year
5504         2015
5505         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5506  Flight5507  41799  ORD-LGA              1.7          35
5507  Flight5508  41796  ORD-IAH              1.9         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5506             0.604167             302.5     55962.5             6
5507             0.291667             220.0     36300.0             6

      Flight Year
5506         2014
5507         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5508  Flight5509  42256  ORD-PHX              2.0         201
5509  Flight5510  41669  ORD-MIA              3.7         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5508             0.583333               250       41250             9
5509             0.291667               300       55500             1

      Flight Year
5508         2015
5509         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5510  Flight5511  41768  ORD-DTW              2.2         152
5511  Flight5512  41933  ORD-DFW              2.4          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5510             0.333333               115       18975             5
5511             0.833333               200       37000            10

      Flight Year
5510         2014
5511         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5512  Flight5513  42351  ORD-IAH              1.4          14
5513  Flight5514  42313  ORD-DFW              1.5         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5512             0.541667               200       37000            12
5513             0.791667               200       33000            11

      Flight Year
5512         2015
5513         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5514  Flight5515  41929  ORD-LGA              0.7          64
5515  Flight5516  41815  ORD-DFW              2.1          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5514             0.708333               275       49775            10
5515             0.708333               220       40700             6

      Flight Year
5514         2014
5515         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5516  Flight5517  41970  ORD-IAH              3.8          89
5517  Flight5518  41869  ORD-ATL              7.9         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5516               0.7500               300       54300            11
5517               0.8125               220       36300             8

      Flight Year
5516         2014
5517         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5518  Flight5519  41697  ORD-CLT              1.8          90
5519  Flight5520  42355  ORD-DTW              1.3         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5518             0.791667               125       22625             2
5519             0.812500               115       21275            12

      Flight Year
5518         2014
5519         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5520  Flight5521  41985  ORD-DEN              2.5           7
5521  Flight5522  42211  ORD-LAX              3.1         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5520             0.687500               300       55500            12
5521             0.458333               385       71225             7

      Flight Year
5520         2014
5521         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5522  Flight5523  42020  ORD-BOS              1.4         190
5523  Flight5524  42118  ORD-LAX              3.4          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5522             0.708333               300       49500             1
5523             0.312500               350       63350             4

      Flight Year
5522         2015
5523         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5524  Flight5525  42086  ORD-MSP              1.9         152
5525  Flight5526  42111  ORD-LAX              5.7         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5524               0.8125               115       18975             3
5525               0.7500               350       64750             4

      Flight Year
5524         2015
5525         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5526  Flight5527  41973  ORD-LAX              9.7         131
5527  Flight5528  42342  ORD-SFO              1.0         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5526             0.833333               525       97125            11
5527             0.708333               375       61875            12

      Flight Year
5526         2014
5527         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5528  Flight5529  41862  ORD-MCO              2.5          63
5529  Flight5530  41843  ORD-DFW              2.4         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5528             0.833333               275       49775             8
5529             0.791667               220       40700             7

      Flight Year
5528         2014
5529         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5530  Flight5531  42103  ORD-LGA              1.1          78
5531  Flight5532  41726  ORD-DFW              1.8          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5530             0.541667               275       49775             4
5531             0.854167               200       36200             3

      Flight Year
5530         2015
5531         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5532  Flight5533  41658  ORD-ATL              9.0          36
5533  Flight5534  42264  ORD-ATL              7.4         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5532             0.312500               200       33000             1
5533             0.541667               200       33000             9

      Flight Year
5532         2014
5533         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5534  Flight5535  41914  ORD-CLT              1.3         180
5535  Flight5536  41832  ORD-JFK              1.3          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5534             0.333333               125       20625            10
5535             0.791667               275       45375             7

      Flight Year
5534         2014
5535         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5536  Flight5537  42294  ORD-LAX              4.1         163
5537  Flight5538  41855  ORD-LAS              2.6         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5536             0.770833             350.0     57750.0            10
5537             0.541667             302.5     49912.5             8

      Flight Year
5536         2015
5537         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5538  Flight5539  41971  ORD-LAS              2.6         108
5539  Flight5540  42158  ORD-DEN              1.5         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5538             0.291667             412.5     76312.5            11
5539             0.708333             330.0     54450.0             6

      Flight Year
5538         2014
5539         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5540  Flight5541  41910  ORD-LAS              1.5         154
5541  Flight5542  42266  ORD-LAX              3.8          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5540             0.708333               275       45375             9
5541             0.604167               350       64750             9

      Flight Year
5540         2014
5541         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5542  Flight5543  42030  ORD-PHX              1.6          13
5543  Flight5544  42196  ORD-JFK              2.6           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5542             0.833333               250       46250             1
5543             0.312500               275       50875             7

      Flight Year
5542         2015
5543         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5544  Flight5545  41970  ORD-DEN              3.4          82
5545  Flight5546  41841  ORD-ATL              9.1          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5544             0.833333               450       81450            11
5545             0.750000               220       39820             7

      Flight Year
5544         2014
5545         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5546  Flight5547  42292  ORD-PHL              2.6          57
5547  Flight5548  42341  ORD-LAX              3.6         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5546             0.708333               275       45375            10
5547             0.354167               350       64750            12

      Flight Year
5546         2015
5547         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5548  Flight5549  42288  ORD-LGA              2.9         202
5549  Flight5550  42198  ORD-DFW              3.0         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5548             0.708333               275       45375            10
5549             0.500000               220       36300             7

      Flight Year
5548         2015
5549         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5550  Flight5551  41820  ORD-LAS              1.9          10
5551  Flight5552  42266  ORD-LGA              2.0         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5550             0.791667             302.5     55962.5             6
5551             0.291667             275.0     50875.0             9

      Flight Year
5550         2014
5551         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5552  Flight5553  41814  ORD-LGA              1.3          17
5553  Flight5554  42214  ORD-SEA              3.3          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5552             0.333333             302.5     55962.5             6
5553             0.750000             385.0     71225.0             7

      Flight Year
5552         2014
5553         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5554  Flight5555  41740  ORD-MCO              1.0         185
5555  Flight5556  42178  ORD-CLT              2.5          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5554             0.312500             250.0     41250.0             4
5555             0.333333             137.5     22687.5             6

      Flight Year
5554         2014
5555         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5556  Flight5557  41973  ORD-MCO              5.3         136
5557  Flight5558  42130  ORD-SFO              2.7          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5556             0.729167               375       69375            11
5557             0.666667               375       69375             5

      Flight Year
5556         2014
5557         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5558  Flight5559  42165  ORD-SFO              2.0          28
5559  Flight5560  41804  ORD-PHX              3.4         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5558             0.854167             412.5     76312.5             6
5559             0.833333             275.0     50875.0             6

      Flight Year
5558         2015
5559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5560  Flight5561  42092  ORD-LGA              2.6          92
5561  Flight5562  41793  ORD-PHX              1.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5560             0.625000               275       50875             3
5561             0.666667               275       49775             6

      Flight Year
5560         2015
5561         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5562  Flight5563  42056  ORD-DEN              2.5          53
5563  Flight5564  42023  ORD-MCO              3.0          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5562             0.750000               300       49500             2
5563             0.833333               250       46250             1

      Flight Year
5562         2015
5563         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5564  Flight5565  42296  ORD-LAS              2.4          66
5565  Flight5566  41806  ORD-ATL              9.3          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5564             0.291667               275       49775            10
5565             0.333333               220       39820             6

      Flight Year
5564         2015
5565         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5566  Flight5567  42312  ORD-JFK              3.0           2
5567  Flight5568  42098  ORD-DEN              1.8          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5566             0.291667               250       46250            11
5567             0.312500               300       55500             4

      Flight Year
5566         2015
5567         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5568  Flight5569  42117  ORD-EWR              1.1         191
5569  Flight5570  41793  ORD-SFO              2.1          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5568             0.750000             225.0     37125.0             4
5569             0.333333             412.5     68062.5             6

      Flight Year
5568         2015
5569         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5570  Flight5571  41968  ORD-ATL             18.3         200
5571  Flight5572  41752  ORD-DEN              2.2         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5570             0.375000               300       49500            11
5571             0.729167               300       49500             4

      Flight Year
5570         2014
5571         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5572  Flight5573  41969  ORD-MCO              4.9         125
5573  Flight5574  42022  ORD-DTW              3.2          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5572               0.5000               375       69375            11
5573               0.8125               115       21275             1

      Flight Year
5572         2014
5573         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5574  Flight5575  42104  ORD-ATL              9.8           5
5575  Flight5576  41725  ORD-IAH              1.4         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5574             0.708333               200       37000             4
5575             0.708333               200       33000             3

      Flight Year
5574         2015
5575         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5576  Flight5577  41910  ORD-EWR              0.6         202
5577  Flight5578  41967  ORD-PHX              4.6         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5576             0.708333               225       37125             9
5577             0.625000               375       61875            11

      Flight Year
5576         2014
5577         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5578  Flight5579  41841  ORD-CLT              1.6          39
5579  Flight5580  42173  ORD-JFK              1.6          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5578             0.479167             137.5     22687.5             7
5579             0.666667             275.0     49775.0             6

      Flight Year
5578         2014
5579         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5580  Flight5581  41818  ORD-MSP              2.5          19
5581  Flight5582  41959  ORD-DFW              1.6          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5580             0.791667             126.5     23402.5             6
5581             0.666667             200.0     37000.0            11

      Flight Year
5580         2014
5581         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5582  Flight5583  42132  ORD-SFO              0.4         189
5583  Flight5584  42308  ORD-EWR              1.3         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5582             0.791667               375       61875             5
5583             0.729167               225       41625            10

      Flight Year
5582         2015
5583         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5584  Flight5585  41915  ORD-SFO              3.5         179
5585  Flight5586  41712  ORD-PHX              1.8          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5584             0.583333               375       61875            10
5585             0.750000               250       46250             3

      Flight Year
5584         2014
5585         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5586  Flight5587  41880  ORD-MCO              3.0          92
5587  Flight5588  41936  ORD-JFK              3.8          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5586             0.583333               275       50875             8
5587             0.291667               250       45250            10

      Flight Year
5586         2014
5587         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5588  Flight5589  42114  ORD-DTW              2.0         163
5589  Flight5590  42178  ORD-MSP              0.9          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5588             0.833333             115.0     18975.0             4
5589             0.708333             126.5     22896.5             6

      Flight Year
5588         2015
5589         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5590  Flight5591  42213  ORD-LAS              0.9         143
5591  Flight5592  42364  ORD-DEN              3.6         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5590             0.729167             302.5     55962.5             7
5591             0.812500             420.0     69300.0            12

      Flight Year
5590         2015
5591         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5592  Flight5593  42107  ORD-LAS              1.8         206
5593  Flight5594  41855  ORD-LAS              1.9          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5592                 0.75             275.0     45375.0             4
5593                 0.50             302.5     55962.5             8

      Flight Year
5592         2015
5593         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5594  Flight5595  41683  ORD-DEN              1.0          11
5595  Flight5596  42261  ORD-DEN              1.9          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5594               0.7500               300       55500             2
5595               0.3125               300       55500             9

      Flight Year
5594         2014
5595         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5596  Flight5597  41815  ORD-PHL              2.6         135
5597  Flight5598  41767  ORD-DFW              2.4          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5596             0.625000             302.5     55962.5             6
5597             0.833333             200.0     37000.0             5

      Flight Year
5596         2014
5597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5598  Flight5599  42102  ORD-DEN              2.9         173
5599  Flight5600  42208  ORD-BOS              2.9         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5598             0.791667               300       49500             4
5599             0.541667               330       54450             7

      Flight Year
5598         2015
5599         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5600  Flight5601  41831  ORD-EWR              0.8         162
5601  Flight5602  41929  ORD-DFW              2.5         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5600             0.833333             247.5     40837.5             7
5601             0.312500             200.0     37000.0            10

      Flight Year
5600         2014
5601         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5602  Flight5603  41811  ORD-DFW              2.1           1
5603  Flight5604  41771  ORD-IAH              1.2         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5602                 0.50               220       40700             6
5603                 0.75               200       37000             5

      Flight Year
5602         2014
5603         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5604  Flight5605  42279  ORD-EWR              2.3          57
5605  Flight5606  42166  ORD-LAX              4.5          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5604             0.333333               225       37125            10
5605             0.833333               385       69685             6

      Flight Year
5604         2015
5605         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5606  Flight5607  41917  ORD-BWI              1.6         114
5607  Flight5608  42314  ORD-DFW              1.5          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5606             0.291667               240       44400            10
5607             0.875000               200       37000            11

      Flight Year
5606         2014
5607         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5608  Flight5609  42290  ORD-CLT              3.8         169
5609  Flight5610  42277  ORD-SFO              1.6         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5608                0.625               125       20625            10
5609                0.750               375       69375             9

      Flight Year
5608         2015
5609         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5610  Flight5611  42337  ORD-PHL              5.4         200
5611  Flight5612  42360  ORD-LAS              3.7          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5610             0.833333             412.5     68062.5            11
5611             0.875000             385.0     63525.0            12

      Flight Year
5610         2015
5611         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5612  Flight5613  41968  ORD-MCO              5.1         112
5613  Flight5614  42199  ORD-SFO              0.8          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5612             0.791667             375.0     69375.0            11
5613             0.458333             412.5     68062.5             7

      Flight Year
5612         2014
5613         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5614  Flight5615  42109  ORD-FLL              1.9          10
5615  Flight5616  41861  ORD-MSP              2.7         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5614             0.750000             300.0     55500.0             4
5615             0.395833             126.5     23402.5             8

      Flight Year
5614         2015
5615         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5616  Flight5617  41923  ORD-SFO              0.6         159
5617  Flight5618  41855  ORD-IAH              2.9         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5616             0.708333               375       61875            10
5617             0.541667               220       40700             8

      Flight Year
5616         2014
5617         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5618  Flight5619  42060  ORD-BOS              1.3          32
5619  Flight5620  42365  ORD-CLT              2.3         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5618             0.708333               300       55500             2
5619             0.354167               175       32375            12

      Flight Year
5618         2015
5619         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5620  Flight5621  41883  ORD-EWR              2.8         143
5621  Flight5622  42347  ORD-DEN              2.8          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5620             0.770833               225       41625             9
5621             0.791667               300       54300            12

      Flight Year
5620         2014
5621         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5622  Flight5623  41660  ORD-SEA              1.7         130
5623  Flight5624  42249  ORD-PHL              2.2         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5622             0.812500               350       64750             1
5623             0.395833               275       45375             9

      Flight Year
5622         2014
5623         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5624  Flight5625  42299  ORD-CLT              2.3          72
5625  Flight5626  41975  ORD-EWR              3.8         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5624             0.833333               125       22625            10
5625             0.750000               225       37125            12

      Flight Year
5624         2015
5625         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5626  Flight5627  42324  ORD-JFK              0.4          83
5627  Flight5628  42314  ORD-JFK              1.8         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5626             0.750000               250       45250            11
5627             0.458333               250       46250            11

      Flight Year
5626         2015
5627         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5628  Flight5629  41740  ORD-IAH              2.1         118
5629  Flight5630  41778  ORD-DFW              1.8         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5628             0.833333               200       37000             4
5629             0.291667               200       37000             5

      Flight Year
5628         2014
5629         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5630  Flight5631  41922  ORD-DTW              2.0         129
5631  Flight5632  41823  ORD-PHX              1.8          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5630             0.645833               115       21275            10
5631             0.708333               275       50875             7

      Flight Year
5630         2014
5631         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5632  Flight5633  41855  ORD-EWR              1.6          93
5633  Flight5634  42227  ORD-SFO              1.0         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5632             0.750000             247.5     45787.5             8
5633             0.708333             412.5     68062.5             8

      Flight Year
5632         2014
5633         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5634  Flight5635  41727  ORD-MCO              1.1         146
5635  Flight5636  42244  ORD-PHL              1.3         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5634             0.791667             250.0     46250.0             3
5635             0.458333             302.5     55962.5             8

      Flight Year
5634         2014
5635         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5636  Flight5637  42260  ORD-JFK              1.1         111
5637  Flight5638  42208  ORD-EWR              2.3         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5636             0.791667             250.0     46250.0             9
5637             0.333333             247.5     45787.5             7

      Flight Year
5636         2015
5637         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5638  Flight5639  42167  ORD-IAH              1.3          22
5639  Flight5640  42303  ORD-IAH              2.2         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5638             0.833333               220       40700             6
5639             0.770833               200       37000            10

      Flight Year
5638         2015
5639         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5640  Flight5641  42127  ORD-DTW              0.5          42
5641  Flight5642  42344  ORD-EWR              2.0          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5640             0.291667               115       18975             5
5641             0.687500               225       40725            12

      Flight Year
5640         2015
5641         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5642  Flight5643  41822  ORD-IAH              1.6           3
5643  Flight5644  42104  ORD-DEN              1.9           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5642               0.5000               220       40700             7
5643               0.3125               300       55500             4

      Flight Year
5642         2014
5643         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5644  Flight5645  42066  ORD-EWR              2.0         184
5645  Flight5646  41649  ORD-DEN              2.6          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5644               0.8125               225       37125             3
5645               0.7500               300       55500             1

      Flight Year
5644         2015
5645         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5646  Flight5647  41837  ORD-MIA              1.4          50
5647  Flight5648  42362  ORD-EWR              4.3          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5646             0.583333               330       54450             7
5647             0.333333               315       58275            12

      Flight Year
5646         2014
5647         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5648  Flight5649  41749  ORD-DEN              1.3         163
5649  Flight5650  42302  ORD-SFO              2.3          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5648             0.708333               300       49500             4
5649             0.708333               375       61875            10

      Flight Year
5648         2014
5649         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5650  Flight5651  42273  ORD-ATL             11.6           3
5651  Flight5652  42142  ORD-IAH              1.0          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5650             0.687500               200       37000             9
5651             0.729167               200       37000             5

      Flight Year
5650         2015
5651         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5652  Flight5653  41828  ORD-LAS              0.2          18
5653  Flight5654  42079  ORD-JFK              1.5          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5652             0.625000             302.5     55962.5             7
5653             0.583333             250.0     46250.0             3

      Flight Year
5652         2014
5653         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5654  Flight5655  41657  ORD-JFK              2.3         164
5655  Flight5656  42059  ORD-LAX              3.4           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5654               0.7500               250       41250             1
5655               0.8125               350       64750             2

      Flight Year
5654         2014
5655         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5656  Flight5657  42367  ORD-IAD              1.2          44
5657  Flight5658  42201  ORD-PHX              2.5          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5656             0.291667               300       49500            12
5657             0.708333               275       45375             7

      Flight Year
5656         2015
5657         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5658  Flight5659  42333  ORD-MIA              6.2          84
5659  Flight5660  42001  ORD-LAX              8.4         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5658             0.791667               450       81450            11
5659             0.750000               490       80850            12

      Flight Year
5658         2015
5659         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5660  Flight5661  42127  ORD-IAH              1.1          35
5661  Flight5662  41924  ORD-PHX              2.4         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5660                0.750               200       37000             5
5661                0.375               250       41250            10

      Flight Year
5660         2015
5661         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5662  Flight5663  41893  ORD-CLT              1.3          70
5663  Flight5664  41728  ORD-LGA              1.4          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5662               0.8125               125       22625             9
5663               0.7500               275       49775             3

      Flight Year
5662         2014
5663         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5664  Flight5665  41962  ORD-MSP              1.1         105
5665  Flight5666  42312  ORD-CLT              2.6          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5664             0.666667               115       21275            11
5665             0.833333               125       23125            11

      Flight Year
5664         2014
5665         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5666  Flight5667  41873  ORD-SEA              2.0         171
5667  Flight5668  42304  ORD-MIA              1.9          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5666             0.562500               385       63525             8
5667             0.416667               300       55500            10

      Flight Year
5666         2014
5667         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5668  Flight5669  41744  ORD-EWR              0.4         206
5669  Flight5670  42092  ORD-DFW              2.3         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5668             0.750000               225       37125             4
5669             0.291667               200       33000             3

      Flight Year
5668         2014
5669         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5670  Flight5671  41671  ORD-SFO              1.5         146
5671  Flight5672  42029  ORD-MSP              1.7         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5670             0.770833               375       69375             2
5671             0.291667               115       21275             1

      Flight Year
5670         2014
5671         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5672  Flight5673  41899  ORD-DEN              2.8          52
5673  Flight5674  41714  ORD-PHX              2.6         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5672             0.750000               300       49500             9
5673             0.541667               250       41250             3

      Flight Year
5672         2014
5673         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5674  Flight5675  41718  ORD-BWI              2.8         140
5675  Flight5676  42302  ORD-JFK              2.7          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5674             0.291667               240       44400             3
5675             0.875000               250       46250            10

      Flight Year
5674         2014
5675         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5676  Flight5677  42349  ORD-LGA              2.3         203
5677  Flight5678  42363  ORD-BOS              3.0         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5676             0.791667               275       45375            12
5677             0.333333               420       69300            12

      Flight Year
5676         2015
5677         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5678  Flight5679  41945  ORD-ATL              8.3          92
5679  Flight5680  42259  ORD-CLT              1.6          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5678             0.375000               200       37000            11
5679             0.791667               125       22625             9

      Flight Year
5678         2014
5679         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5680  Flight5681  41687  ORD-JFK              2.1         100
5681  Flight5682  41880  ORD-JFK              2.1         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5680               0.6875               250       46250             2
5681               0.3750               275       50875             8

      Flight Year
5680         2014
5681         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5682  Flight5683  42314  ORD-LAS              1.9           2
5683  Flight5684  41895  ORD-DFW              1.2         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5682             0.479167               275       50875            11
5683             0.791667               200       33000             9

      Flight Year
5682         2015
5683         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5684  Flight5685  41880  ORD-ATL             11.2         206
5685  Flight5686  41755  ORD-DFW              1.7          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5684             0.666667               220       36300             8
5685             0.625000               200       33000             4

      Flight Year
5684         2014
5685         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5686  Flight5687  42236  ORD-JFK              2.3         111
5687  Flight5688  41794  ORD-JFK              3.4         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5686             0.770833               275       50875             8
5687             0.750000               275       50875             6

      Flight Year
5686         2015
5687         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5688  Flight5689  42320  ORD-LAX              2.8         116
5689  Flight5690  41958  ORD-SEA              2.4          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5688             0.375000               350       64750            11
5689             0.333333               350       64750            11

      Flight Year
5688         2015
5689         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5690  Flight5691  42354  ORD-CLT              2.0         208
5691  Flight5692  42018  ORD-BOS              2.5         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5690             0.583333               125       20625            12
5691             0.750000               300       49500             1

      Flight Year
5690         2015
5691         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5692  Flight5693  42239  ORD-ATL             10.1          94
5693  Flight5694  42236  ORD-DEN              2.3         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5692             0.708333               220       40700             8
5693             0.750000               330       54450             8

      Flight Year
5692         2015
5693         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5694  Flight5695  41863  ORD-MSP              2.0         108
5695  Flight5696  42211  ORD-MIA              2.4          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5694             0.375000             126.5     23402.5             8
5695             0.791667             330.0     61050.0             7

      Flight Year
5694         2014
5695         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5696  Flight5697  42163  ORD-LAS              2.2         192
5697  Flight5698  42114  ORD-IAH              3.3          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5696             0.708333             302.5     49912.5             6
5697             0.520833             200.0     37000.0             4

      Flight Year
5696         2015
5697         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5698  Flight5699  41802  ORD-MIA              1.6         171
5699  Flight5700  42159  ORD-ATL              9.4          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5698             0.750000               330       54450             6
5699             0.708333               220       39820             6

      Flight Year
5698         2014
5699         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5700  Flight5701  41896  ORD-IAH              2.5          69
5701  Flight5702  42182  ORD-ATL             11.8         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5700             0.291667               200       36200             9
5701             0.708333               220       36300             6

      Flight Year
5700         2014
5701         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5702  Flight5703  42320  ORD-DTW              2.0          98
5703  Flight5704  42109  ORD-LAX              4.5         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5702             0.791667               115       21275            11
5703             0.854167               350       64750             4

      Flight Year
5702         2015
5703         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5704  Flight5705  42041  ORD-SFO              2.2          57
5705  Flight5706  41721  ORD-ATL              9.2         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5704             0.750000               375       61875             2
5705             0.895833               200       37000             3

      Flight Year
5704         2015
5705         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5706  Flight5707  41724  ORD-ATL              9.1          14
5707  Flight5708  41889  ORD-DFW              3.4          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5706             0.291667               200       37000             3
5707             0.833333               200       37000             9

      Flight Year
5706         2014
5707         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5708  Flight5709  42288  ORD-EWR              1.7         196
5709  Flight5710  41984  ORD-CLT              2.0         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5708             0.791667               225       37125            10
5709             0.812500               125       23125            12

      Flight Year
5708         2015
5709         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5710  Flight5711  42076  ORD-MCO              1.7         184
5711  Flight5712  42047  ORD-DFW              2.1          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5710             0.750000               250       41250             3
5711             0.708333               200       36200             2

      Flight Year
5710         2015
5711         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5712  Flight5713  42114  ORD-DFW              2.8          59
5713  Flight5714  41837  ORD-BOS              1.3         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5712             0.791667               200       33000             4
5713             0.333333               330       54450             7

      Flight Year
5712         2015
5713         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5714  Flight5715  42171  ORD-ATL              8.7         132
5715  Flight5716  41896  ORD-DFW              2.3          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5714             0.791667               220       40700             6
5715             0.708333               200       33000             9

      Flight Year
5714         2015
5715         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5716  Flight5717  42342  ORD-SEA              1.2         191
5717  Flight5718  42272  ORD-IAD              2.7         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5716             0.333333               350       57750            12
5717             0.833333               300       49500             9

      Flight Year
5716         2015
5717         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5718  Flight5719  41806  ORD-DEN              2.4          64
5719  Flight5720  42197  ORD-EWR              2.4         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5718             0.708333             330.0     59730.0             6
5719             0.729167             247.5     40837.5             7

      Flight Year
5718         2014
5719         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5720  Flight5721  42006  ORD-CLT              1.7          58
5721  Flight5722  42292  ORD-MCO              2.9         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5720             0.895833               125       20625             1
5721             0.750000               250       41250            10

      Flight Year
5720         2015
5721         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5722  Flight5723  42000  ORD-JFK              4.3         151
5723  Flight5724  42345  ORD-LAS              3.1         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5722             0.812500               350       64750            12
5723             0.770833               275       45375            12

      Flight Year
5722         2014
5723         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5724  Flight5725  41678  ORD-DFW              2.1         184
5725  Flight5726  42063  ORD-IAH              2.8          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5724             0.729167               200       33000             2
5725             0.583333               200       36200             2

      Flight Year
5724         2014
5725         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5726  Flight5727  41643  ORD-LGA              2.1         113
5727  Flight5728  41973  ORD-JFK              5.3          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5726             0.750000               275       50875             1
5727             0.354167               375       67875            11

      Flight Year
5726         2014
5727         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5728  Flight5729  42337  ORD-DEN              4.1          17
5729  Flight5730  41836  ORD-DFW              1.8         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5728             0.708333               450       83250            11
5729             0.708333               220       36300             7

      Flight Year
5728         2015
5729         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5730  Flight5731  41999  ORD-DFW              4.3         164
5731  Flight5732  42325  ORD-SEA              2.2         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5730             0.416667               280       46200            12
5731             0.791667               350       64750            11

      Flight Year
5730         2014
5731         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5732  Flight5733  41847  ORD-DEN              2.9         119
5733  Flight5734  42320  ORD-SFO              2.9         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5732             0.708333               330       61050             7
5733             0.666667               375       69375            11

      Flight Year
5732         2014
5733         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5734  Flight5735  42048  ORD-DFW              2.7         105
5735  Flight5736  41773  ORD-LAX              3.1          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5734               0.5625               200       37000             2
5735               0.7500               350       57750             5

      Flight Year
5734         2015
5735         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5736  Flight5737  42223  ORD-MIA              1.9          83
5737  Flight5738  42208  ORD-JFK              0.9          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5736               0.8125               330       59730             8
5737               0.8125               275       49775             7

      Flight Year
5736         2015
5737         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5738  Flight5739  42291  ORD-ATL             10.4         207
5739  Flight5740  41967  ORD-MCO              5.4         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5738             0.625000               200       33000            10
5739             0.333333               375       61875            11

      Flight Year
5738         2015
5739         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5740  Flight5741  41815  ORD-LAX              3.7         175
5741  Flight5742  42187  ORD-DFW              1.5          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5740             0.666667               385       63525             6
5741             0.625000               220       36300             7

      Flight Year
5740         2014
5741         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5742  Flight5743  41783  ORD-PHL              1.5          87
5743  Flight5744  41873  ORD-BOS              1.8         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5742             0.750000               275       49775             5
5743             0.541667               330       61050             8

      Flight Year
5742         2014
5743         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5744  Flight5745  41666  ORD-SFO              3.0         123
5745  Flight5746  42032  ORD-LGA              1.1          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5744               0.5000               375       69375             1
5745               0.4375               275       45375             1

      Flight Year
5744         2014
5745         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5746  Flight5747  41699  ORD-LAX              4.1         128
5747  Flight5748  41850  ORD-SFO              1.9         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5746             0.791667             350.0     64750.0             3
5747             0.291667             412.5     68062.5             7

      Flight Year
5746         2014
5747         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5748  Flight5749  41683  ORD-MIA              2.7          97
5749  Flight5750  41668  ORD-DEN              2.2          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5748             0.583333               300       55500             2
5749             0.791667               300       55500             1

      Flight Year
5748         2014
5749         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5750  Flight5751  42246  ORD-ATL             10.6          86
5751  Flight5752  42185  ORD-ATL             12.3          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5750             0.333333               220       39820             8
5751             0.833333               220       40700             6

      Flight Year
5750         2015
5751         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5752  Flight5753  42259  ORD-LGA              2.5          92
5753  Flight5754  42053  ORD-PHX              1.8         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5752             0.854167               275       50875             9
5753             0.375000               250       46250             2

      Flight Year
5752         2015
5753         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5754  Flight5755  42172  ORD-DTW              1.6         138
5755  Flight5756  41756  ORD-SEA              1.0          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5754             0.833333             126.5     23402.5             6
5755             0.375000             350.0     64750.0             4

      Flight Year
5754         2015
5755         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5756  Flight5757  42161  ORD-MIA              2.0          54
5757  Flight5758  42359  ORD-CLT              4.2          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5756             0.291667               330       54450             6
5757             0.708333               175       28875            12

      Flight Year
5756         2015
5757         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5758  Flight5759  42333  ORD-SFO              6.7           5
5759  Flight5760  42210  ORD-LAS              1.0          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5758             0.708333             562.5    104062.5            11
5759             0.541667             302.5     54752.5             7

      Flight Year
5758         2015
5759         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5760  Flight5761  42194  ORD-DEN              1.7         126
5761  Flight5762  41920  ORD-LAX              4.6          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5760                 0.75               330       61050             7
5761                 0.75               350       57750            10

      Flight Year
5760         2015
5761         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5762  Flight5763  42127  ORD-PHX              2.4         190
5763  Flight5764  42341  ORD-PHX              2.6         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5762             0.354167               250       41250             5
5763             0.791667               250       46250            12

      Flight Year
5762         2015
5763         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5764  Flight5765  42129  ORD-ATL             10.5         189
5765  Flight5766  41962  ORD-ATL              8.3          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5764             0.770833               200       33000             5
5765             0.791667               200       37000            11

      Flight Year
5764         2015
5765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5766  Flight5767  42000  ORD-ATL             15.3         146
5767  Flight5768  41878  ORD-LAS              1.5          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5766             0.333333             280.0     51800.0            12
5767             0.291667             302.5     49912.5             8

      Flight Year
5766         2014
5767         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5768  Flight5769  42336  ORD-MSP              4.1         145
5769  Flight5770  42251  ORD-MIA              1.3         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5768             0.416667             172.5     31912.5            11
5769             0.354167             300.0     55500.0             9

      Flight Year
5768         2015
5769         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5770  Flight5771  41862  ORD-DTW              1.8          41
5771  Flight5772  41659  ORD-JFK              2.9          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5770             0.479167             126.5     20872.5             8
5771             0.291667             250.0     46250.0             1

      Flight Year
5770         2014
5771         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5772  Flight5773  42161  ORD-JFK              2.8          71
5773  Flight5774  41833  ORD-MIA              1.8         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5772                 0.50               275       49775             6
5773                 0.75               330       54450             7

      Flight Year
5772         2015
5773         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5774  Flight5775  42231  ORD-DEN              3.1         149
5775  Flight5776  42238  ORD-DFW              1.9         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5774             0.583333               330       61050             8
5775             0.645833               220       36300             8

      Flight Year
5774         2015
5775         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5776  Flight5777  41734  ORD-CLT              1.1         140
5777  Flight5778  42253  ORD-DFW              2.3          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5776                 0.75               125       23125             4
5777                 0.75               200       33000             9

      Flight Year
5776         2014
5777         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5778  Flight5779  41722  ORD-SEA              1.6          31
5779  Flight5780  41881  ORD-FLL              2.8         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5778             0.312500               350       64750             3
5779             0.708333               330       61050             8

      Flight Year
5778         2014
5779         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5780  Flight5781  42334  ORD-EWR              5.1          52
5781  Flight5782  42237  ORD-MIA              3.1         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5780             0.791667             337.5     55687.5            11
5781             0.812500             330.0     54450.0             8

      Flight Year
5780         2015
5781         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5782  Flight5783  42021  ORD-PHL              1.6          53
5783  Flight5784  42214  ORD-JFK              1.6         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5782                0.625               275       45375             1
5783                0.750               275       45375             7

      Flight Year
5782         2015
5783         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5784  Flight5785  41968  ORD-JFK              5.0           6
5785  Flight5786  42264  ORD-LGA              2.5          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5784             0.708333               375       69375            11
5785             0.583333               275       49775             9

      Flight Year
5784         2014
5785         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5786  Flight5787  42247  ORD-BOS              2.3          85
5787  Flight5788  41761  ORD-CLT              0.7          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5786             0.291667               330       59730             8
5787             0.416667               125       23125             5

      Flight Year
5786         2015
5787         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5788  Flight5789  41662  ORD-JFK              2.8         167
5789  Flight5790  41713  ORD-BOS              3.0         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5788             0.729167               250       41250             1
5789             0.458333               300       55500             3

      Flight Year
5788         2014
5789         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5790  Flight5791  41856  ORD-LAX              7.2          77
5791  Flight5792  42274  ORD-IAH              1.7         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5790             0.583333               385       69685             8
5791             0.770833               200       37000             9

      Flight Year
5790         2014
5791         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5792  Flight5793  42214  ORD-LGA              2.1          41
5793  Flight5794  41732  ORD-DFW              2.2         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5792             0.750000             302.5     49912.5             7
5793             0.583333             200.0     33000.0             4

      Flight Year
5792         2015
5793         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5794  Flight5795  41993  ORD-LAS              1.9          46
5795  Flight5796  41867  ORD-MCO              1.9          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5794             0.520833               275       45375            12
5795             0.708333               275       45375             8

      Flight Year
5794         2014
5795         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5796  Flight5797  42332  ORD-LAX              9.4         149
5797  Flight5798  41804  ORD-LAS              2.8          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5796             0.666667             525.0     97125.0            11
5797             0.791667             302.5     55962.5             6

      Flight Year
5796         2015
5797         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5798  Flight5799  42171  ORD-ATL             11.8          18
5799  Flight5800  41949  ORD-BOS              1.6         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5798               0.6875               220       40700             6
5799               0.5625               300       49500            11

      Flight Year
5798         2015
5799         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5800  Flight5801  42240  ORD-SFO              1.6          92
5801  Flight5802  41801  ORD-DFW              2.0         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5800             0.333333             412.5     76312.5             8
5801             0.333333             220.0     40700.0             6

      Flight Year
5800         2015
5801         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5802  Flight5803  42061  ORD-MSP              2.6         140
5803  Flight5804  41656  ORD-CLT              3.0         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5802             0.354167               115       21275             2
5803             0.437500               125       23125             1

      Flight Year
5802         2015
5803         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5804  Flight5805  41664  ORD-SFO              2.7         181
5805  Flight5806  41666  ORD-DTW              1.0         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5804             0.604167               375       61875             1
5805             0.750000               115       21275             1

      Flight Year
5804         2014
5805         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5806  Flight5807  42091  ORD-JFK              1.8         155
5807  Flight5808  41878  ORD-JFK              0.9         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5806             0.583333               250       41250             3
5807             0.375000               275       45375             8

      Flight Year
5806         2015
5807         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5808  Flight5809  41973  ORD-LGA              2.7         154
5809  Flight5810  41648  ORD-JFK              2.6          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5808             0.708333             412.5     68062.5            11
5809             0.770833             250.0     45250.0             1

      Flight Year
5808         2014
5809         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5810  Flight5811  42216  ORD-CLT              2.6         185
5811  Flight5812  42104  ORD-SFO              2.5         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5810             0.708333             137.5     22687.5             7
5811             0.833333             375.0     69375.0             4

      Flight Year
5810         2015
5811         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5812  Flight5813  42349  ORD-DFW              2.5          42
5813  Flight5814  42167  ORD-FLL              1.9         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5812             0.291667               200       33000            12
5813             0.354167               330       54450             6

      Flight Year
5812         2015
5813         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5814  Flight5815  42032  ORD-CLT              1.9          31
5815  Flight5816  41907  ORD-CLT              0.9          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5814             0.333333               125       23125             1
5815             0.291667               125       23125             9

      Flight Year
5814         2015
5815         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5816  Flight5817  42338  ORD-IAH              2.0         160
5817  Flight5818  41907  ORD-LAX              4.9          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5816             0.750000               200       33000            11
5817             0.354167               350       63350             9

      Flight Year
5816         2015
5817         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5818  Flight5819  42239  ORD-IAH              1.8         178
5819  Flight5820  41969  ORD-MCO              3.4          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5818             0.708333               220       36300             8
5819             0.312500               375       69375            11

      Flight Year
5818         2015
5819         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5820  Flight5821  41863  ORD-EWR              1.6         129
5821  Flight5822  41879  ORD-IAH              3.0         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5820             0.812500             247.5     45787.5             8
5821             0.791667             220.0     36300.0             8

      Flight Year
5820         2014
5821         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5822  Flight5823  41911  ORD-MIA              1.7         206
5823  Flight5824  42241  ORD-CLT              1.4         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5822             0.791667             300.0     49500.0             9
5823             0.666667             137.5     25437.5             8

      Flight Year
5822         2014
5823         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5824  Flight5825  41891  ORD-DEN              0.7         149
5825  Flight5826  42007  ORD-DEN              3.1         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5824             0.291667               300       55500             9
5825             0.791667               300       55500             1

      Flight Year
5824         2014
5825         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5826  Flight5827  41801  ORD-PHX              2.8         162
5827  Flight5828  42150  ORD-LAX              4.3          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5826             0.333333               275       45375             6
5827             0.666667               350       63350             5

      Flight Year
5826         2014
5827         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5828  Flight5829  42159  ORD-MCO              1.8          79
5829  Flight5830  41989  ORD-PHL              2.0         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5828             0.333333               275       49775             6
5829             0.833333               275       45375            12

      Flight Year
5828         2015
5829         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5830  Flight5831  42066  ORD-LGA              1.6         147
5831  Flight5832  41946  ORD-PHX              3.1         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5830             0.791667               275       50875             3
5831             0.833333               250       46250            11

      Flight Year
5830         2015
5831         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5832  Flight5833  42211  ORD-MCO              2.0          20
5833  Flight5834  42188  ORD-MIA              1.7          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5832             0.708333               275       50875             7
5833             0.500000               330       61050             7

      Flight Year
5832         2015
5833         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5834  Flight5835  42211  ORD-BOS              2.3         107
5835  Flight5836  41839  ORD-LAX              4.1         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5834             0.520833               330       61050             7
5835             0.791667               385       63525             7

      Flight Year
5834         2015
5835         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5836  Flight5837  42155  ORD-LAS              2.6         188
5837  Flight5838  41929  ORD-BWI              2.1          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5836             0.812500               275       45375             5
5837             0.291667               240       43440            10

      Flight Year
5836         2015
5837         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5838  Flight5839  42112  ORD-CLT              2.0         148
5839  Flight5840  41997  ORD-PHL              4.6         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5838             0.312500               125       23125             4
5839             0.791667               385       71225            12

      Flight Year
5838         2015
5839         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5840  Flight5841  41671  ORD-ATL              7.7         111
5841  Flight5842  42033  ORD-BWI              3.5         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5840             0.812500               200       37000             2
5841             0.791667               240       39600             1

      Flight Year
5840         2014
5841         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5842  Flight5843  42213  ORD-ATL              8.3         105
5843  Flight5844  42354  ORD-MCO              2.6         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5842             0.875000               220       40700             7
5843             0.458333               250       41250            12

      Flight Year
5842         2015
5843         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5844  Flight5845  41665  ORD-LAS              3.1          63
5845  Flight5846  42309  ORD-BOS              0.8         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5844             0.520833               275       49775             1
5845             0.708333               300       55500            11

      Flight Year
5844         2014
5845         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5846  Flight5847  41751  ORD-LAS              1.7         164
5847  Flight5848  41963  ORD-LAX              5.1         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5846             0.500000               275       45375             4
5847             0.854167               350       57750            11

      Flight Year
5846         2014
5847         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5848  Flight5849  42203  ORD-DEN              0.3           2
5849  Flight5850  42115  ORD-EWR              2.7          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5848             0.333333               330       61050             7
5849             0.812500               225       37125             4

      Flight Year
5848         2015
5849         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5850  Flight5851  41647  ORD-DEN              2.2          10
5851  Flight5852  41950  ORD-BOS              1.7         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5850             0.708333               300       55500             1
5851             0.791667               300       49500            11

      Flight Year
5850         2014
5851         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5852  Flight5853  41921  ORD-MCO              2.7          32
5853  Flight5854  42337  ORD-LAX             10.2         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5852             0.708333               250       46250            10
5853             0.666667               525       86625            11

      Flight Year
5852         2014
5853         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5854  Flight5855  41988  ORD-JFK              2.5         172
5855  Flight5856  41930  ORD-DEN              1.2         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5854             0.770833               250       41250            12
5855             0.291667               300       55500            10

      Flight Year
5854         2014
5855         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5856  Flight5857  41911  ORD-LAX              3.4         152
5857  Flight5858  41685  ORD-ATL              9.8         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5856             0.729167               350       57750             9
5857             0.812500               200       33000             2

      Flight Year
5856         2014
5857         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5858  Flight5859  42369  ORD-LAS              2.2         178
5859  Flight5860  41779  ORD-MIA              1.8         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5858             0.708333               275       45375            12
5859             0.500000               300       55500             5

      Flight Year
5858         2015
5859         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5860  Flight5861  42145  ORD-ATL             10.9         166
5861  Flight5862  42115  ORD-SFO              1.7          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5860             0.291667               200       33000             5
5861             0.750000               375       61875             4

      Flight Year
5860         2015
5861         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5862  Flight5863  41661  ORD-IAD              1.1          84
5863  Flight5864  42332  ORD-ATL             16.7         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5862             0.750000               300       54300             1
5863             0.458333               300       49500            11

      Flight Year
5862         2014
5863         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5864  Flight5865  41703  ORD-SFO                3         183
5865  Flight5866  41925  ORD-DFW                2         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5864             0.333333               375       61875             3
5865             0.666667               200       37000            10

      Flight Year
5864         2014
5865         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5866  Flight5867  41815  ORD-DFW              1.5         116
5867  Flight5868  41676  ORD-LAX              5.0         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5866             0.854167               220       40700             6
5867             0.333333               350       57750             2

      Flight Year
5866         2014
5867         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5868  Flight5869  41807  ORD-BOS              2.3          66
5869  Flight5870  42280  ORD-LGA              2.8          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5868             0.291667               330       59730             6
5869             0.333333               275       45375            10

      Flight Year
5868         2014
5869         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5870  Flight5871  41690  ORD-DFW              1.2          75
5871  Flight5872  41709  ORD-EWR              2.3         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5870             0.291667               200       36200             2
5871             0.875000               225       41625             3

      Flight Year
5870         2014
5871         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5872  Flight5873  42276  ORD-DTW              0.9         156
5873  Flight5874  41716  ORD-SFO              2.4          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5872             0.583333               115       18975             9
5873             0.312500               375       69375             3

      Flight Year
5872         2015
5873         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5874  Flight5875  42169  ORD-JFK              1.5          11
5875  Flight5876  42311  ORD-CLT              1.1          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5874               0.8125               275       50875             6
5875               0.8750               125       22625            11

      Flight Year
5874         2015
5875         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5876  Flight5877  42290  ORD-MIA              4.0          53
5877  Flight5878  42093  ORD-LAX              4.2         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5876             0.708333               300       49500            10
5877             0.291667               350       64750             3

      Flight Year
5876         2015
5877         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5878  Flight5879  41763  ORD-JFK              1.5          74
5879  Flight5880  41908  ORD-BWI              2.1          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5878               0.8125               250       45250             5
5879               0.6250               240       44400             9

      Flight Year
5878         2014
5879         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5880  Flight5881  42331  ORD-IAH              3.3         198
5881  Flight5882  41754  ORD-LGA              3.0          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5880             0.791667               300       49500            11
5881             0.354167               275       49775             4

      Flight Year
5880         2015
5881         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5882  Flight5883  41899  ORD-LAX              3.5          58
5883  Flight5884  41720  ORD-PHX              2.7         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5882             0.500000               350       57750             9
5883             0.479167               250       46250             3

      Flight Year
5882         2014
5883         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5884  Flight5885  41817  ORD-LAX              5.8         104
5885  Flight5886  41764  ORD-EWR              2.5         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5884               0.8750               385       71225             6
5885               0.8125               225       37125             5

      Flight Year
5884         2014
5885         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5886  Flight5887  41798  ORD-LAS              1.6          29
5887  Flight5888  42084  ORD-DEN              2.2           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5886             0.750000             302.5     55962.5             6
5887             0.666667             300.0     55500.0             3

      Flight Year
5886         2014
5887         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5888  Flight5889  41967  ORD-JFK              4.8          27
5889  Flight5890  41933  ORD-PHL              2.0         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5888             0.750000               375       69375            11
5889             0.708333               275       50875            10

      Flight Year
5888         2014
5889         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5890  Flight5891  42239  ORD-MCO              0.6          75
5891  Flight5892  41672  ORD-CLT              2.0         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5890             0.791667               275       49775             8
5891             0.708333               125       20625             2

      Flight Year
5890         2015
5891         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5892  Flight5893  42079  ORD-IAH              2.7         118
5893  Flight5894  42369  ORD-MIA              3.0          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5892             0.812500               200       37000             3
5893             0.333333               300       54300            12

      Flight Year
5892         2015
5893         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5894  Flight5895  42196  ORD-MSP              1.9         193
5895  Flight5896  42045  ORD-JFK              1.9         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5894             0.333333             126.5     20872.5             7
5895             0.791667             250.0     41250.0             2

      Flight Year
5894         2015
5895         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5896  Flight5897  42325  ORD-ATL              9.2          66
5897  Flight5898  42252  ORD-LAS              2.3         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5896             0.333333               200       36200            11
5897             0.500000               275       45375             9

      Flight Year
5896         2015
5897         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5898  Flight5899  42348  ORD-SFO              1.9         121
5899  Flight5900  42296  ORD-SLC              2.1         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5898             0.291667               375       69375            12
5899             0.625000               290       53650            10

      Flight Year
5898         2015
5899         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5900  Flight5901  42148  ORD-CLT              2.1          67
5901  Flight5902  42174  ORD-PHL              2.6         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5900             0.291667             125.0     22625.0             5
5901             0.500000             302.5     49912.5             6

      Flight Year
5900         2015
5901         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5902  Flight5903  41810  ORD-EWR                2         150
5903  Flight5904  42020  ORD-LGA                1         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5902               0.3125             247.5     45787.5             6
5903               0.5000             275.0     45375.0             1

      Flight Year
5902         2014
5903         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5904  Flight5905  42078  ORD-LAX              2.2         143
5905  Flight5906  42187  ORD-SEA              1.8          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5904             0.833333               350       64750             3
5905             0.833333               385       71225             7

      Flight Year
5904         2015
5905         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5906  Flight5907  41769  ORD-MIA                3          74
5907  Flight5908  41814  ORD-IAH                2         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5906             0.354167               300       54300             5
5907             0.291667               220       36300             6

      Flight Year
5906         2014
5907         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5908  Flight5909  42141  ORD-BOS              1.4          45
5909  Flight5910  42146  ORD-CLT              2.4         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5908             0.750000               300       49500             5
5909             0.770833               125       23125             5

      Flight Year
5908         2015
5909         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5910  Flight5911  42186  ORD-PHX              2.3         137
5911  Flight5912  42046  ORD-PHL              2.0         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5910             0.791667               275       50875             7
5911             0.791667               275       45375             2

      Flight Year
5910         2015
5911         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5912  Flight5913  42071  ORD-LAX              6.3         140
5913  Flight5914  42024  ORD-CLT              2.5         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5912             0.708333               350       64750             3
5913             0.750000               125       23125             1

      Flight Year
5912         2015
5913         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5914  Flight5915  42215  ORD-EWR              2.5         167
5915  Flight5916  42038  ORD-JFK              1.7         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5914             0.416667             247.5     40837.5             7
5915             0.291667             250.0     46250.0             2

      Flight Year
5914         2015
5915         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5916  Flight5917  42327  ORD-EWR              2.4          37
5917  Flight5918  42293  ORD-JFK              2.1          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5916             0.437500               225       37125            11
5917             0.333333               250       45250            10

      Flight Year
5916         2015
5917         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5918  Flight5919  42225  ORD-IAH              1.2         198
5919  Flight5920  41977  ORD-LGA              2.6         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5918             0.333333               220       36300             8
5919             0.812500               275       45375            12

      Flight Year
5918         2015
5919         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5920  Flight5921  41892  ORD-MIA              2.8          52
5921  Flight5922  41792  ORD-MSP              2.1          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5920             0.333333             300.0     49500.0             9
5921             0.291667             126.5     20872.5             6

      Flight Year
5920         2014
5921         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5922  Flight5923  42051  ORD-PHX              1.0          88
5923  Flight5924  41774  ORD-ATL              6.9          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5922             0.833333               250       45250             2
5923             0.291667               200       37000             5

      Flight Year
5922         2015
5923         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5924  Flight5925  41793  ORD-LAX              6.5           8
5925  Flight5926  41750  ORD-DFW              2.3         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5924             0.854167               385       71225             6
5925             0.750000               200       37000             4

      Flight Year
5924         2014
5925         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5926  Flight5927  41804  ORD-DEN              1.5          69
5927  Flight5928  42149  ORD-EWR              1.5          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5926             0.479167               330       59730             6
5927             0.770833               225       40725             5

      Flight Year
5926         2014
5927         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5928  Flight5929  42295  ORD-PHX              1.6         134
5929  Flight5930  41968  ORD-CLT              3.8         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5928             0.895833             250.0     46250.0            10
5929             0.291667             187.5     30937.5            11

      Flight Year
5928         2015
5929         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5930  Flight5931  42211  ORD-JFK              1.0         209
5931  Flight5932  41943  ORD-LAS              2.3         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5930             0.708333               275       45375             7
5931             0.666667               275       50875            10

      Flight Year
5930         2015
5931         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5932  Flight5933  41959  ORD-MIA              1.3          98
5933  Flight5934  42092  ORD-JFK              2.2         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5932             0.416667               300       55500            11
5933             0.291667               250       41250             3

      Flight Year
5932         2014
5933         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5934  Flight5935  41687  ORD-LGA              1.5          37
5935  Flight5936  42092  ORD-SEA              1.1         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5934             0.291667               275       45375             2
5935             0.791667               350       57750             3

      Flight Year
5934         2014
5935         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5936  Flight5937  42060  ORD-BWI              1.4          65
5937  Flight5938  41989  ORD-ATL             10.9         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5936             0.291667               240       43440             2
5937             0.895833               200       33000            12

      Flight Year
5936         2015
5937         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5938  Flight5939  41978  ORD-EWR              1.7          72
5939  Flight5940  42225  ORD-MCO              2.0          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5938             0.833333               225       40725            12
5939             0.291667               275       45375             8

      Flight Year
5938         2014
5939         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5940  Flight5941  42162  ORD-BOS              0.4         162
5941  Flight5942  41961  ORD-SEA              2.3          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5940             0.708333               330       54450             6
5941             0.520833               350       63350            11

      Flight Year
5940         2015
5941         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5942  Flight5943  42088  ORD-IAH              1.8          91
5943  Flight5944  41703  ORD-MIA              1.6         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5942             0.291667               200       37000             3
5943             0.416667               300       49500             3

      Flight Year
5942         2015
5943         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5944  Flight5945  42333  ORD-SEA              6.5         191
5945  Flight5946  41724  ORD-BOS              1.3         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5944             0.333333               525       86625            11
5945             0.333333               300       49500             3

      Flight Year
5944         2015
5945         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5946  Flight5947  42244  ORD-DFW              1.2         202
5947  Flight5948  42228  ORD-LGA              3.0         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5946             0.541667             220.0     36300.0             8
5947             0.333333             302.5     55962.5             8

      Flight Year
5946         2015
5947         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5948  Flight5949  41795  ORD-LAX              3.6         110
5949  Flight5950  41896  ORD-JFK              0.3         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5948             0.833333               385       71225             6
5949             0.750000               250       41250             9

      Flight Year
5948         2014
5949         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5950  Flight5951  42115  ORD-EWR              2.6           5
5951  Flight5952  42068  ORD-EWR              2.4          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5950             0.708333               225       41625             4
5951             0.333333               225       40725             3

      Flight Year
5950         2015
5951         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5952  Flight5953  41721  ORD-SFO              1.5           6
5953  Flight5954  41997  ORD-JFK              3.1           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5952                 0.75               375       69375             3
5953                 0.75               350       64750            12

      Flight Year
5952         2014
5953         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5954  Flight5955  41813  ORD-CLT              1.9          89
5955  Flight5956  42358  ORD-PHX              2.3         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5954             0.291667             137.5     24887.5             6
5955             0.354167             250.0     46250.0            12

      Flight Year
5954         2014
5955         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5956  Flight5957  42214  ORD-MIA              0.8         202
5957  Flight5958  41738  ORD-SFO              3.0         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5956             0.708333               330       54450             7
5957             0.291667               375       61875             4

      Flight Year
5956         2015
5957         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5958  Flight5959  42180  ORD-DEN              3.0         117
5959  Flight5960  42126  ORD-EWR              2.1          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5958             0.291667               330       61050             6
5959             0.833333               225       37125             5

      Flight Year
5958         2015
5959         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5960  Flight5961  42297  ORD-DEN              0.9          43
5961  Flight5962  41819  ORD-CLT              2.9         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5960             0.583333             300.0     49500.0            10
5961             0.750000             137.5     22687.5             6

      Flight Year
5960         2015
5961         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5962  Flight5963  42102  ORD-DTW              0.8         112
5963  Flight5964  42334  ORD-JFK              4.4         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5962             0.791667               115       21275             4
5963             0.708333               375       69375            11

      Flight Year
5962         2015
5963         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5964  Flight5965  41857  ORD-DFW              2.1           4
5965  Flight5966  42014  ORD-JFK              1.2         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5964             0.854167               220       40700             8
5965             0.375000               250       46250             1

      Flight Year
5964         2014
5965         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5966  Flight5967  41819  ORD-LAS              2.0          73
5967  Flight5968  42290  ORD-DFW              1.8         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5966             0.291667             302.5     54752.5             6
5967             0.791667             200.0     33000.0            10

      Flight Year
5966         2014
5967         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5968  Flight5969  41996  ORD-LAX              9.8         148
5969  Flight5970  42282  ORD-SEA              0.5          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5968             0.729167               490       90650            12
5969             0.708333               350       57750            10

      Flight Year
5968         2014
5969         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5970  Flight5971  41857  ORD-LAX              4.4           5
5971  Flight5972  42107  ORD-JFK              2.7         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5970             0.791667               385       71225             8
5971             0.541667               250       46250             4

      Flight Year
5970         2014
5971         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5972  Flight5973  41766  ORD-CLT              2.6          78
5973  Flight5974  41979  ORD-CLT              2.4          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5972             0.791667               125       22625             5
5973             0.770833               125       22625            12

      Flight Year
5972         2014
5973         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5974  Flight5975  42112  ORD-JFK              1.7         169
5975  Flight5976  42195  ORD-CLT              2.7          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5974             0.375000             250.0     41250.0             4
5975             0.291667             137.5     22687.5             7

      Flight Year
5974         2015
5975         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5976  Flight5977  42143  ORD-SEA              2.5         131
5977  Flight5978  42291  ORD-LAX              4.5           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5976             0.729167               350       64750             5
5977             0.333333               350       64750            10

      Flight Year
5976         2015
5977         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5978  Flight5979  42263  ORD-FLL              2.9          39
5979  Flight5980  42199  ORD-SFO              2.7          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5978             0.312500             300.0     49500.0             9
5979             0.791667             412.5     76312.5             7

      Flight Year
5978         2015
5979         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5980  Flight5981  42169  ORD-BOS              3.7         157
5981  Flight5982  41839  ORD-ATL              7.9         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5980             0.791667               330       54450             6
5981             0.729167               220       40700             7

      Flight Year
5980         2015
5981         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5982  Flight5983  41995  ORD-ATL             13.4         198
5983  Flight5984  41995  ORD-MIA              3.1          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5982             0.291667               280       46200            12
5983             0.583333               420       69300            12

      Flight Year
5982         2014
5983         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5984  Flight5985  41969  ORD-ATL             17.9         170
5985  Flight5986  41916  ORD-PHX              1.0         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5984             0.291667               300       49500            11
5985             0.708333               250       46250            10

      Flight Year
5984         2014
5985         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5986  Flight5987  41764  ORD-DFW              1.3          37
5987  Flight5988  42311  ORD-SFO              1.7          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5986             0.708333               200       33000             5
5987             0.708333               375       69375            11

      Flight Year
5986         2014
5987         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5988  Flight5989  41834  ORD-ATL              9.9         190
5989  Flight5990  42126  ORD-CLT              0.6          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5988             0.729167               220       36300             7
5989             0.500000               125       22625             5

      Flight Year
5988         2014
5989         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5990  Flight5991  41960  ORD-DEN              2.2          19
5991  Flight5992  41698  ORD-FLL              2.4         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5990             0.770833               300       55500            11
5991             0.791667               300       55500             2

      Flight Year
5990         2014
5991         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5992  Flight5993  42236  ORD-DTW              1.5          27
5993  Flight5994  42088  ORD-IAD              3.0         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5992             0.395833             126.5     23402.5             8
5993             0.291667             300.0     49500.0             3

      Flight Year
5992         2015
5993         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5994  Flight5995  42162  ORD-BWI              3.3          23
5995  Flight5996  42021  ORD-DEN              2.2          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5994             0.708333               264       48840             6
5995             0.520833               300       54300             1

      Flight Year
5994         2015
5995         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5996  Flight5997  42270  ORD-DFW              2.1         151
5997  Flight5998  42053  ORD-ATL             10.5          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5996             0.291667               200       37000             9
5997             0.333333               200       33000             2

      Flight Year
5996         2015
5997         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
5998  Flight5999  42061  ORD-LAX              5.4          47
5999  Flight6000  42125  ORD-LAS              2.6         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
5998             0.666667               350       57750             2
5999             0.291667               275       50875             5

      Flight Year
5998         2015
5999         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6000  Flight6001  41843  ORD-DFW              2.7          24
6001  Flight6002  42084  ORD-SFO              1.5          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6000             0.416667               220       40700             7
6001             0.291667               375       67875             3

      Flight Year
6000         2014
6001         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6002  Flight6003  41990  ORD-DFW              2.8         206
6003  Flight6004  41972  ORD-PHX              5.4         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6002             0.291667               200       33000            12
6003             0.791667               375       69375            11

      Flight Year
6002         2014
6003         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6004  Flight6005  42326  ORD-LGA              2.0           4
6005  Flight6006  41997  ORD-PHL              5.2         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6004             0.708333               275       50875            11
6005             0.458333               385       63525            12

      Flight Year
6004         2015
6005         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6006  Flight6007  41698  ORD-MCO              1.1          40
6007  Flight6008  42329  ORD-ATL              7.1          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6006             0.500000               250       41250             2
6007             0.833333               200       36200            11

      Flight Year
6006         2014
6007         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6008  Flight6009  42182  ORD-MCO              2.8         103
6009  Flight6010  41949  ORD-EWR              1.7         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6008             0.875000               275       50875             6
6009             0.895833               225       41625            11

      Flight Year
6008         2015
6009         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6010  Flight6011  41800  ORD-DEN              2.9         134
6011  Flight6012  42193  ORD-IAH              2.6         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6010             0.708333               330       61050             6
6011             0.729167               220       36300             7

      Flight Year
6010         2014
6011         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6012  Flight6013  42043  ORD-IAH              2.0         210
6013  Flight6014  41996  ORD-PHX              3.4         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6012                0.750               200       33000             2
6013                0.375               350       57750            12

      Flight Year
6012         2015
6013         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6014  Flight6015  42353  ORD-LAX              6.0           3
6015  Flight6016  41880  ORD-MIA              2.4          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6014             0.666667               350       64750            12
6015             0.729167               330       61050             8

      Flight Year
6014         2015
6015         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6016  Flight6017  41793  ORD-ATL              9.1          41
6017  Flight6018  41744  ORD-LAS              0.8          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6016             0.708333               220       36300             6
6017             0.791667               275       49775             4

      Flight Year
6016         2014
6017         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6018  Flight6019  41756  ORD-DTW              2.2          57
6019  Flight6020  42283  ORD-DEN              3.0         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6018             0.708333               115       18975             4
6019             0.854167               300       55500            10

      Flight Year
6018         2014
6019         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6020  Flight6021  42176  ORD-CLT              1.6          57
6021  Flight6022  41940  ORD-CLT              2.6         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6020             0.791667             137.5     22687.5             6
6021             0.625000             125.0     20625.0            10

      Flight Year
6020         2015
6021         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6022  Flight6023  42104  ORD-DFW              2.8         187
6023  Flight6024  42301  ORD-DFW              2.4         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6022             0.333333               200       33000             4
6023             0.416667               200       33000            10

      Flight Year
6022         2015
6023         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6024  Flight6025  42296  ORD-JFK              2.0         195
6025  Flight6026  42130  ORD-CLT              2.7          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6024             0.354167               250       41250            10
6025             0.312500               125       23125             5

      Flight Year
6024         2015
6025         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6026  Flight6027  41668  ORD-LAS              2.1         200
6027  Flight6028  42155  ORD-DFW              1.2         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6026             0.750000               275       45375             1
6027             0.458333               200       33000             5

      Flight Year
6026         2014
6027         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6028  Flight6029  42119  ORD-CLT              3.1         117
6029  Flight6030  42034  ORD-PHX              2.1         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6028             0.416667               125       23125             4
6029             0.291667               250       46250             1

      Flight Year
6028         2015
6029         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6030  Flight6031  42363  ORD-CLT              4.1         139
6031  Flight6032  42073  ORD-LGA              3.8         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6030               0.3125               175       32375            12
6031               0.6875               275       50875             3

      Flight Year
6030         2015
6031         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6032  Flight6033  42362  ORD-CLT              4.5         161
6033  Flight6034  42342  ORD-EWR              1.6         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6032             0.625000               175       28875            12
6033             0.895833               225       41625            12

      Flight Year
6032         2015
6033         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6034  Flight6035  42364  ORD-MIA              4.3         157
6035  Flight6036  42075  ORD-CLT              2.0          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6034             0.500000               420       69300            12
6035             0.291667               125       23125             3

      Flight Year
6034         2015
6035         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6036  Flight6037  42169  ORD-MIA              1.2          62
6037  Flight6038  41641  ORD-EWR              2.7         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6036                 0.75               330       54450             6
6037                 0.75               225       41625             1

      Flight Year
6036         2015
6037         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6038  Flight6039  42010  ORD-LAS              2.8          46
6039  Flight6040  41693  ORD-LAX              3.2         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6038             0.458333               275       45375             1
6039             0.708333               350       57750             2

      Flight Year
6038         2015
6039         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6040  Flight6041  41689  ORD-PHX              1.1          42
6041  Flight6042  41892  ORD-JFK              1.0          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6040             0.291667               250       41250             2
6041             0.541667               250       45250             9

      Flight Year
6040         2014
6041         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6042  Flight6043  42366  ORD-BOS              0.7         108
6043  Flight6044  42026  ORD-DFW              2.3          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6042             0.416667               300       55500            12
6043             0.791667               200       33000             1

      Flight Year
6042         2015
6043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6044  Flight6045  41913  ORD-JFK              1.0          38
6045  Flight6046  41968  ORD-JFK              3.8          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6044             0.333333               250       41250            10
6045             0.791667               375       61875            11

      Flight Year
6044         2014
6045         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6046  Flight6047  42254  ORD-EWR              2.2          86
6047  Flight6048  42248  ORD-SFO              2.1         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6046             0.333333               225       40725             9
6047             0.666667               375       61875             9

      Flight Year
6046         2015
6047         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6048  Flight6049  42347  ORD-BOS              3.1         174
6049  Flight6050  42151  ORD-LAX              3.4          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6048             0.708333               300       49500            12
6049             0.750000               350       63350             5

      Flight Year
6048         2015
6049         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6050  Flight6051  42216  ORD-DEN              3.2         159
6051  Flight6052  41825  ORD-SFO              1.0         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6050             0.812500             330.0     54450.0             7
6051             0.770833             412.5     76312.5             7

      Flight Year
6050         2015
6051         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6052  Flight6053  42129  ORD-LAX              3.9          66
6053  Flight6054  41974  ORD-CLT              1.9          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6052             0.708333               350       63350             5
6053             0.750000               125       23125            12

      Flight Year
6052         2015
6053         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6054  Flight6055  42193  ORD-MCO              2.2         119
6055  Flight6056  42325  ORD-BOS              2.1         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6054             0.791667               275       50875             7
6055             0.291667               300       55500            11

      Flight Year
6054         2015
6055         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6056  Flight6057  42254  ORD-MSP              2.4         185
6057  Flight6058  41908  ORD-DTW              3.1         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6056             0.541667               115       18975             9
6057             0.708333               115       21275             9

      Flight Year
6056         2015
6057         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6058  Flight6059  41854  ORD-CLT              1.3         123
6059  Flight6060  41656  ORD-LAX              2.3          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6058             0.833333             137.5     25437.5             8
6059             0.708333             350.0     64750.0             1

      Flight Year
6058         2014
6059         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6060  Flight6061  41803  ORD-DFW              1.8         192
6061  Flight6062  42068  ORD-SFO              0.8         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6060             0.291667               220       36300             6
6061             0.666667               375       69375             3

      Flight Year
6060         2014
6061         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6062  Flight6063  41914  ORD-SEA              2.3          17
6063  Flight6064  41745  ORD-BWI              2.3         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6062             0.750000               350       64750            10
6063             0.333333               240       44400             4

      Flight Year
6062         2014
6063         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6064  Flight6065  41832  ORD-ATL              8.5         110
6065  Flight6066  42034  ORD-SEA              2.9          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6064             0.791667               220       40700             7
6065             0.791667               350       57750             1

      Flight Year
6064         2014
6065         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6066  Flight6067  42118  ORD-IAH              1.4         136
6067  Flight6068  42236  ORD-LAS              0.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6066             0.791667             200.0     37000.0             4
6067             0.583333             302.5     49912.5             8

      Flight Year
6066         2015
6067         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6068  Flight6069  41896  ORD-MSP              0.6         135
6069  Flight6070  41664  ORD-CLT              1.7         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6068             0.291667               115       21275             9
6069             0.833333               125       23125             1

      Flight Year
6068         2014
6069         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6070  Flight6071  41768  ORD-MSP              2.4          13
6071  Flight6072  41847  ORD-DEN              2.0         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6070                0.750               115       21275             5
6071                0.875               330       54450             7

      Flight Year
6070         2014
6071         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6072  Flight6073  42213  ORD-CLT              1.2         159
6073  Flight6074  42281  ORD-LAS              2.8         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6072             0.750000             137.5     22687.5             7
6073             0.583333             275.0     45375.0            10

      Flight Year
6072         2015
6073         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6074  Flight6075  42104  ORD-EWR              1.7         183
6075  Flight6076  41901  ORD-PHX              1.1          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6074             0.375000               225       37125             4
6075             0.333333               250       41250             9

      Flight Year
6074         2015
6075         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6076  Flight6077  41964  ORD-LGA              3.2         187
6077  Flight6078  42038  ORD-BWI              2.1         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6076             0.312500               275       45375            11
6077             0.708333               240       39600             2

      Flight Year
6076         2014
6077         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6078  Flight6079  41922  ORD-ATL              6.8         111
6079  Flight6080  41757  ORD-CLT              0.0           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6078             0.770833               200       37000            10
6079             0.291667               125       23125             4

      Flight Year
6078         2014
6079         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6080  Flight6081  42332  ORD-IAH              4.0           1
6081  Flight6082  42280  ORD-BOS              0.8         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6080             0.791667               300       55500            11
6081             0.750000               300       55500            10

      Flight Year
6080         2015
6081         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6082  Flight6083  41748  ORD-DTW              1.5          14
6083  Flight6084  42297  ORD-ATL              7.8         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6082             0.729167               115       21275             4
6083             0.750000               200       33000            10

      Flight Year
6082         2014
6083         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6084  Flight6085  41976  ORD-MCO              2.3          48
6085  Flight6086  42051  ORD-LAX              4.7          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6084             0.791667               250       41250            12
6085             0.541667               350       64750             2

      Flight Year
6084         2014
6085         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6086  Flight6087  42224  ORD-MCO              1.9          73
6087  Flight6088  41953  ORD-ATL              8.5          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6086             0.645833               275       49775             8
6087             0.729167               200       33000            11

      Flight Year
6086         2015
6087         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6088  Flight6089  42337  ORD-DFW              4.2          94
6089  Flight6090  41782  ORD-PHX              2.3          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6088             0.687500               300       55500            11
6089             0.791667               250       46250             5

      Flight Year
6088         2015
6089         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6090  Flight6091  42020  ORD-JFK              0.4         171
6091  Flight6092  41648  ORD-DFW              2.1          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6090             0.375000               250       41250             1
6091             0.333333               200       36200             1

      Flight Year
6090         2015
6091         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6092  Flight6093  41843  ORD-PHL              1.2          57
6093  Flight6094  42156  ORD-IAH              3.2          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6092             0.458333             302.5     49912.5             7
6093             0.770833             220.0     36300.0             6

      Flight Year
6092         2014
6093         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6094  Flight6095  42354  ORD-SEA              2.6         157
6095  Flight6096  42020  ORD-FLL              2.8         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6094             0.833333               350       57750            12
6095             0.833333               300       55500             1

      Flight Year
6094         2015
6095         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6096  Flight6097  41677  ORD-LGA              0.7          63
6097  Flight6098  42138  ORD-SFO              1.9         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6096             0.291667               275       49775             2
6097             0.458333               375       69375             5

      Flight Year
6096         2014
6097         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6098  Flight6099  41810  ORD-LGA              2.6          38
6099  Flight6100  41878  ORD-ATL              7.5          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6098               0.8750             302.5     49912.5             6
6099               0.8125             220.0     39820.0             8

      Flight Year
6098         2014
6099         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6100  Flight6101  41790  ORD-EWR              2.5         150
6101  Flight6102  41748  ORD-SFO              1.5          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6100             0.770833               225       41625             5
6101             0.687500               375       61875             4

      Flight Year
6100         2014
6101         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6102  Flight6103  42334  ORD-CLT              3.3         171
6103  Flight6104  42159  ORD-ATL              9.5          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6102             0.291667             187.5     30937.5            11
6103             0.729167             220.0     40700.0             6

      Flight Year
6102         2015
6103         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6104  Flight6105  41642  ORD-DEN              1.7         172
6105  Flight6106  41716  ORD-EWR              1.6         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6104               0.6250               300       49500             1
6105               0.8125               225       41625             3

      Flight Year
6104         2014
6105         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6106  Flight6107  41923  ORD-BOS              1.9          56
6107  Flight6108  41822  ORD-DFW              0.3          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6106             0.812500               300       49500            10
6107             0.458333               220       39820             7

      Flight Year
6106         2014
6107         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6108  Flight6109  42104  ORD-IAH              2.4         190
6109  Flight6110  41818  ORD-CLT              1.6          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6108             0.833333             200.0     33000.0             4
6109             0.312500             137.5     25437.5             6

      Flight Year
6108         2015
6109         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6110  Flight6111  42213  ORD-DTW              1.2          18
6111  Flight6112  41794  ORD-PHX              2.4         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6110             0.291667             126.5     23402.5             7
6111             0.604167             275.0     45375.0             6

      Flight Year
6110         2015
6111         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6112  Flight6113  41798  ORD-DEN                2          59
6113  Flight6114  42185  ORD-LAX                5         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6112             0.708333               330       54450             6
6113             0.333333               385       63525             6

      Flight Year
6112         2014
6113         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6114  Flight6115  42089  ORD-MIA              1.8          51
6115  Flight6116  41727  ORD-PHX              2.6         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6114               0.8125               300       49500             3
6115               0.4375               250       41250             3

      Flight Year
6114         2015
6115         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6116  Flight6117  42190  ORD-SFO              3.1         167
6117  Flight6118  42223  ORD-LAS              1.5         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6116                 0.50             412.5     68062.5             7
6117                 0.75             302.5     55962.5             8

      Flight Year
6116         2015
6117         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6118  Flight6119  42254  ORD-SEA              1.2          11
6119  Flight6120  42232  ORD-MIA              2.4         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6118             0.750000               350       64750             9
6119             0.666667               330       54450             8

      Flight Year
6118         2015
6119         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6120  Flight6121  41851  ORD-SFO              1.3         161
6121  Flight6122  41783  ORD-EWR              1.6         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6120             0.708333             412.5     68062.5             7
6121             0.875000             225.0     37125.0             5

      Flight Year
6120         2014
6121         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6122  Flight6123  42214  ORD-SFO              2.5          18
6123  Flight6124  42055  ORD-LGA              1.0         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6122             0.666667             412.5     76312.5             7
6123             0.791667             275.0     50875.0             2

      Flight Year
6122         2015
6123         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6124  Flight6125  42261  ORD-SFO              2.8          57
6125  Flight6126  41841  ORD-IAH              2.2         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6124             0.500000               375       61875             9
6125             0.833333               220       36300             7

      Flight Year
6124         2015
6125         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6126  Flight6127  42184  ORD-ATL              8.5           2
6127  Flight6128  42277  ORD-MCO              2.3           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6126             0.291667               220       40700             6
6127             0.291667               250       46250             9

      Flight Year
6126         2015
6127         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6128  Flight6129  42247  ORD-DFW              2.3          47
6129  Flight6130  42365  ORD-SEA              4.0          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6128             0.687500               220       36300             8
6129             0.708333               490       88690            12

      Flight Year
6128         2015
6129         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6130  Flight6131  42182  ORD-LAS              2.9         128
6131  Flight6132  42245  ORD-PHX              2.3         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6130             0.666667             302.5     55962.5             6
6131             0.854167             275.0     50875.0             8

      Flight Year
6130         2015
6131         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6132  Flight6133  42228  ORD-SFO              1.1         206
6133  Flight6134  41980  ORD-PHX              2.1          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6132             0.291667             412.5     68062.5             8
6133             0.750000             250.0     41250.0            12

      Flight Year
6132         2015
6133         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6134  Flight6135  41938  ORD-ATL             10.5          19
6135  Flight6136  41789  ORD-EWR              0.3         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6134             0.833333               200       37000            10
6135             0.645833               225       37125             5

      Flight Year
6134         2014
6135         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6136  Flight6137  42322  ORD-PHX              1.6          96
6137  Flight6138  42292  ORD-DFW              2.3         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6136             0.625000               250       46250            11
6137             0.291667               200       37000            10

      Flight Year
6136         2015
6137         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6138  Flight6139  41933  ORD-MSP              2.5         131
6139  Flight6140  42223  ORD-ATL              7.3         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6138                0.875               115       21275            10
6139                0.375               220       40700             8

      Flight Year
6138         2014
6139         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6140  Flight6141  42299  ORD-MIA              2.3         206
6141  Flight6142  42057  ORD-EWR              2.3          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6140             0.791667               300       49500            10
6141             0.750000               225       41625             2

      Flight Year
6140         2015
6141         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6142  Flight6143  41823  ORD-BOS              1.9          48
6143  Flight6144  41745  ORD-DEN              1.7         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6142             0.416667               330       54450             7
6143             0.812500               300       49500             4

      Flight Year
6142         2014
6143         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6144  Flight6145  42170  ORD-DEN              1.7          92
6145  Flight6146  42192  ORD-PHL              1.6          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6144             0.750000             330.0     61050.0             6
6145             0.583333             302.5     54752.5             7

      Flight Year
6144         2015
6145         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6146  Flight6147  42001  ORD-LAX              8.2          75
6147  Flight6148  42059  ORD-DEN              1.6         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6146             0.791667               490       88690            12
6147             0.750000               300       49500             2

      Flight Year
6146         2014
6147         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6148  Flight6149  42153  ORD-SEA              1.8         100
6149  Flight6150  41947  ORD-DFW              1.6          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6148             0.354167               350       64750             5
6149             0.291667               200       37000            11

      Flight Year
6148         2015
6149         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6150  Flight6151  41835  ORD-DEN              2.0          49
6151  Flight6152  41977  ORD-DEN              1.2          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6150             0.750000               330       54450             7
6151             0.708333               300       55500            12

      Flight Year
6150         2014
6151         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6152  Flight6153  42062  ORD-SFO              2.2         155
6153  Flight6154  41798  ORD-EWR              1.3         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6152                0.625             375.0     61875.0             2
6153                0.750             247.5     40837.5             6

      Flight Year
6152         2015
6153         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6154  Flight6155  41909  ORD-LAX              4.0          65
6155  Flight6156  42341  ORD-SLC              3.8         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6154             0.791667               350       63350             9
6155             0.625000               290       47850            12

      Flight Year
6154         2014
6155         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6156  Flight6157  42051  ORD-LAS              2.4         100
6157  Flight6158  41803  ORD-PHL              3.1         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6156             0.791667             275.0     50875.0             2
6157             0.562500             302.5     55962.5             6

      Flight Year
6156         2015
6157         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6158  Flight6159  41927  ORD-SFO                2         186
6159  Flight6160  41916  ORD-PHX                1         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6158             0.375000               375       61875            10
6159             0.666667               250       41250            10

      Flight Year
6158         2014
6159         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6160  Flight6161  42030  ORD-MSP              2.4          97
6161  Flight6162  42346  ORD-LAX              3.9         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6160             0.791667               115       21275             1
6161             0.750000               350       57750            12

      Flight Year
6160         2015
6161         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6162  Flight6163  41830  ORD-SFO              2.9         184
6163  Flight6164  42169  ORD-JFK              1.8         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6162             0.708333             412.5     68062.5             7
6163             0.395833             275.0     45375.0             6

      Flight Year
6162         2014
6163         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6164  Flight6165  41653  ORD-SEA              1.9         108
6165  Flight6166  41858  ORD-IAH              2.1         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6164             0.833333               350       64750             1
6165             0.541667               220       40700             8

      Flight Year
6164         2014
6165         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6166  Flight6167  42203  ORD-LAS              1.6         131
6167  Flight6168  41654  ORD-FLL              0.8          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6166             0.541667             302.5     55962.5             7
6167             0.770833             300.0     54300.0             1

      Flight Year
6166         2015
6167         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6168  Flight6169  42239  ORD-SFO              1.8          46
6169  Flight6170  41856  ORD-PHL              0.6          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6168             0.666667             412.5     68062.5             8
6169             0.729167             302.5     55962.5             8

      Flight Year
6168         2015
6169         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6170  Flight6171  41845  ORD-PHL              0.9         166
6171  Flight6172  41999  ORD-DEN              4.7         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6170             0.750000             302.5     49912.5             7
6171             0.708333             420.0     69300.0            12

      Flight Year
6170         2014
6171         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6172  Flight6173  42093  ORD-MSP              1.3          88
6173  Flight6174  41672  ORD-LAS              0.2          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6172             0.333333               115       20815             3
6173             0.791667               275       50875             2

      Flight Year
6172         2015
6173         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6174  Flight6175  42278  ORD-CLT              1.9          62
6175  Flight6176  41932  ORD-LAX              4.9          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6174             0.708333               125       20625            10
6175             0.770833               350       57750            10

      Flight Year
6174         2015
6175         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6176  Flight6177  41874  ORD-MCO              2.0         182
6177  Flight6178  42094  ORD-ATL             10.8         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6176             0.833333               275       45375             8
6177             0.333333               200       33000             3

      Flight Year
6176         2014
6177         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6178  Flight6179  42141  ORD-IAD              2.4         173
6179  Flight6180  41995  ORD-ATL             11.0         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6178             0.708333               300       49500             5
6179             0.770833               280       46200            12

      Flight Year
6178         2015
6179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6180  Flight6181  41832  ORD-JFK              1.2         178
6181  Flight6182  42128  ORD-BOS              1.9         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6180             0.375000               275       45375             7
6181             0.458333               300       49500             5

      Flight Year
6180         2014
6181         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6182  Flight6183  41976  ORD-JFK              2.2          29
6183  Flight6184  41960  ORD-DFW              1.6          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6182             0.291667               250       46250            12
6183             0.291667               200       36200            11

      Flight Year
6182         2014
6183         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6184  Flight6185  42350  ORD-JFK              1.8         169
6185  Flight6186  42302  ORD-LAS              2.2         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6184             0.458333               250       41250            12
6185             0.812500               275       50875            10

      Flight Year
6184         2015
6185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6186  Flight6187  42359  ORD-ATL             14.7          90
6187  Flight6188  42275  ORD-PHX              2.7         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6186             0.291667               280       50680            12
6187             0.666667               250       41250             9

      Flight Year
6186         2015
6187         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6188  Flight6189  41814  ORD-CLT              1.0           7
6189  Flight6190  42153  ORD-PHL              1.2         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6188             0.854167             137.5     25437.5             6
6189             0.770833             275.0     45375.0             5

      Flight Year
6188         2014
6189         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6190  Flight6191  42336  ORD-LGA              6.6         119
6191  Flight6192  42087  ORD-DFW              1.2          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6190             0.291667             412.5     76312.5            11
6191             0.854167             200.0     37000.0             3

      Flight Year
6190         2015
6191         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6192  Flight6193  41644  ORD-CLT              2.3         126
6193  Flight6194  42025  ORD-DEN              2.9          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6192             0.333333               125       23125             1
6193             0.520833               300       54300             1

      Flight Year
6192         2014
6193         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6194  Flight6195  41753  ORD-ATL             10.2         189
6195  Flight6196  41942  ORD-JFK              2.7          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6194             0.416667               200       33000             4
6195             0.791667               250       46250            10

      Flight Year
6194         2014
6195         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6196  Flight6197  41736  ORD-DEN              1.9         171
6197  Flight6198  41713  ORD-PHL              2.1         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6196             0.416667               300       49500             4
6197             0.791667               275       45375             3

      Flight Year
6196         2014
6197         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6198  Flight6199  41666  ORD-LGA              1.9         131
6199  Flight6200  41873  ORD-DEN              1.2          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6198             0.645833               275       50875             1
6199             0.833333               330       61050             8

      Flight Year
6198         2014
6199         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6200  Flight6201  41828  ORD-IAH              0.8          80
6201  Flight6202  42119  ORD-SFO              2.0         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6200             0.791667               220       39820             7
6201             0.770833               375       61875             4

      Flight Year
6200         2014
6201         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6202  Flight6203  41894  ORD-MCO              2.9          13
6203  Flight6204  42244  ORD-LAS              2.1         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6202             0.520833             250.0     46250.0             9
6203             0.291667             302.5     49912.5             8

      Flight Year
6202         2014
6203         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6204  Flight6205  42104  ORD-IAH              1.7          71
6205  Flight6206  42358  ORD-JFK              0.7          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6204             0.416667               200       36200             4
6205             0.729167               250       46250            12

      Flight Year
6204         2015
6205         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6206  Flight6207  42329  ORD-CLT              2.3         188
6207  Flight6208  41967  ORD-PHX              5.7         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6206             0.291667               125       20625            11
6207             0.791667               375       61875            11

      Flight Year
6206         2015
6207         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6208  Flight6209  42241  ORD-FLL              1.5         145
6209  Flight6210  42177  ORD-LAX              3.2          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6208             0.541667               330       61050             8
6209             0.291667               385       63525             6

      Flight Year
6208         2015
6209         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6210  Flight6211  42040  ORD-ATL             12.4          18
6211  Flight6212  41702  ORD-MSP              0.9          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6210             0.583333               200       37000             2
6211             0.291667               115       20815             3

      Flight Year
6210         2015
6211         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6212  Flight6213  41982  ORD-MIA                2         135
6213  Flight6214  42199  ORD-IAH                2         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6212             0.750000               300       55500            12
6213             0.833333               220       36300             7

      Flight Year
6212         2014
6213         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6214  Flight6215  41767  ORD-DFW              2.5           3
6215  Flight6216  41728  ORD-MIA              1.4          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6214             0.895833               200       37000             5
6215             0.687500               300       54300             3

      Flight Year
6214         2014
6215         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6216  Flight6217  41653  ORD-MIA              1.2          51
6217  Flight6218  41971  ORD-SFO              5.7         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6216             0.708333             300.0     49500.0             1
6217             0.895833             562.5    104062.5            11

      Flight Year
6216         2014
6217         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6218  Flight6219  41711  ORD-DEN              1.6          88
6219  Flight6220  41940  ORD-IAD              1.2          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6218             0.354167               300       54300             3
6219             0.375000               300       54300            10

      Flight Year
6218         2014
6219         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6220  Flight6221  41860  ORD-BWI              2.5         196
6221  Flight6222  42336  ORD-MIA              4.4          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6220             0.333333               264       43560             8
6221             0.833333               450       81450            11

      Flight Year
6220         2014
6221         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6222  Flight6223  42175  ORD-PHL              2.3          47
6223  Flight6224  42183  ORD-LAX              4.6          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6222             0.479167             302.5     49912.5             6
6223             0.729167             385.0     71225.0             6

      Flight Year
6222         2015
6223         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6224  Flight6225  42239  ORD-LAS              2.4         208
6225  Flight6226  41835  ORD-LGA              0.7         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6224             0.729167             302.5     49912.5             8
6225             0.291667             302.5     49912.5             7

      Flight Year
6224         2015
6225         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6226  Flight6227  42109  ORD-PHX              2.7         140
6227  Flight6228  42189  ORD-MIA              2.0         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6226             0.666667               250       46250             4
6227             0.291667               330       61050             7

      Flight Year
6226         2015
6227         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6228  Flight6229  42209  ORD-DEN              1.6         108
6229  Flight6230  42113  ORD-MCO              1.6          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6228             0.708333               330       61050             7
6229             0.541667               250       41250             4

      Flight Year
6228         2015
6229         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6230  Flight6231  42366  ORD-DEN              2.6         102
6231  Flight6232  42183  ORD-JFK              1.7         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6230             0.333333               300       55500            12
6231             0.729167               275       50875             6

      Flight Year
6230         2015
6231         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6232  Flight6233  41838  ORD-MIA              1.3          92
6233  Flight6234  42365  ORD-ATL             13.8         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6232             0.895833               330       61050             7
6233             0.812500               280       46200            12

      Flight Year
6232         2014
6233         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6234  Flight6235  42105  ORD-PHL              0.8          72
6235  Flight6236  42308  ORD-CLT              2.6          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6234             0.833333               275       49775             4
6235             0.750000               125       22625            10

      Flight Year
6234         2015
6235         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6236  Flight6237  42334  ORD-SFO              7.5          65
6237  Flight6238  42359  ORD-DEN              5.1         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6236             0.812500             562.5    101812.5            11
6237             0.854167             420.0     77700.0            12

      Flight Year
6236         2015
6237         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6238  Flight6239  42084  ORD-ATL             11.7         129
6239  Flight6240  42305  ORD-MCO              2.1         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6238             0.708333               200       37000             3
6239             0.708333               250       46250            10

      Flight Year
6238         2015
6239         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6240  Flight6241  42365  ORD-EWR              4.5          53
6241  Flight6242  42184  ORD-DFW              1.9         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6240             0.500000               315       51975            12
6241             0.791667               220       36300             6

      Flight Year
6240         2015
6241         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6242  Flight6243  42217  ORD-DCA              2.7         139
6243  Flight6244  41663  ORD-DEN              1.7          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6242             0.416667              5500     1017500             8
6243             0.729167               300       54300             1

      Flight Year
6242         2015
6243         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6244  Flight6245  42189  ORD-DEN              1.9         107
6245  Flight6246  41942  ORD-IAH              1.1         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6244             0.645833               330       61050             7
6245             0.291667               200       33000            10

      Flight Year
6244         2015
6245         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6246  Flight6247  42162  ORD-DTW              2.6          60
6247  Flight6248  41649  ORD-DEN              2.5         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6246             0.625000             126.5     20872.5             6
6247             0.333333             300.0     55500.0             1

      Flight Year
6246         2015
6247         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6248  Flight6249  41868  ORD-MIA              1.9          44
6249  Flight6250  41838  ORD-DFW              2.1          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6248             0.750000               330       54450             8
6249             0.791667               220       40700             7

      Flight Year
6248         2014
6249         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6250  Flight6251  42226  ORD-MCO              2.2         182
6251  Flight6252  41887  ORD-JFK              1.7         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6250             0.604167               275       45375             8
6251             0.729167               250       41250             9

      Flight Year
6250         2015
6251         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6252  Flight6253  42180  ORD-DEN              2.0          74
6253  Flight6254  41686  ORD-ATL             10.6          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6252             0.708333               330       59730             6
6253             0.333333               200       33000             2

      Flight Year
6252         2015
6253         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6254  Flight6255  41940  ORD-EWR              2.5         148
6255  Flight6256  41967  ORD-DTW              5.7          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6254             0.375000             225.0     41625.0            10
6255             0.354167             172.5     31222.5            11

      Flight Year
6254         2014
6255         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6256  Flight6257  42022  ORD-MSP              2.4          57
6257  Flight6258  41978  ORD-SEA              2.5         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6256             0.750000               115       18975             1
6257             0.708333               350       64750            12

      Flight Year
6256         2015
6257         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6258  Flight6259  42309  ORD-PHX              2.8           1
6259  Flight6260  42124  ORD-SEA              1.4         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6258             0.416667               250       46250            11
6259             0.833333               350       57750             4

      Flight Year
6258         2015
6259         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6260  Flight6261  42176  ORD-DEN              2.8         104
6261  Flight6262  41845  ORD-LAS              1.6         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6260             0.666667             330.0     61050.0             6
6261             0.291667             302.5     55962.5             7

      Flight Year
6260         2015
6261         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6262  Flight6263  41685  ORD-PHX              0.7          63
6263  Flight6264  42350  ORD-DEN              1.4          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6262             0.791667               250       45250             2
6263             0.291667               300       55500            12

      Flight Year
6262         2014
6263         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6264  Flight6265  41663  ORD-DEN              1.6         142
6265  Flight6266  41860  ORD-DFW              2.2          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6264             0.375000               300       55500             1
6265             0.791667               220       39820             8

      Flight Year
6264         2014
6265         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6266  Flight6267  42167  ORD-LAX              4.7          88
6267  Flight6268  41873  ORD-MSP              1.7         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6266                0.625             385.0     69685.0             6
6267                0.875             126.5     23402.5             8

      Flight Year
6266         2015
6267         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6268  Flight6269  42232  ORD-DTW              1.6         160
6269  Flight6270  42364  ORD-PHL              4.0         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6268             0.770833             126.5     20872.5             8
6269             0.291667             385.0     63525.0            12

      Flight Year
6268         2015
6269         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6270  Flight6271  41719  ORD-JFK              2.9          86
6271  Flight6272  42348  ORD-BWI              3.4         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6270             0.333333               250       45250             3
6271             0.875000               240       44400            12

      Flight Year
6270         2014
6271         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6272  Flight6273  41886  ORD-PHL              2.8         170
6273  Flight6274  41923  ORD-JFK              1.6          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6272             0.520833               275       45375             9
6273             0.375000               250       45250            10

      Flight Year
6272         2014
6273         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6274  Flight6275  42242  ORD-MCO              2.0         179
6275  Flight6276  41978  ORD-LAX              3.1          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6274             0.354167               275       45375             8
6275             0.791667               350       64750            12

      Flight Year
6274         2015
6275         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6276  Flight6277  41702  ORD-JFK              1.6         108
6277  Flight6278  42020  ORD-PHL              1.6          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6276             0.729167               250       46250             3
6277             0.312500               275       45375             1

      Flight Year
6276         2014
6277         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6278  Flight6279  42178  ORD-JFK              1.8         162
6279  Flight6280  42191  ORD-DFW              2.1         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6278             0.458333               275       45375             6
6279             0.583333               220       36300             7

      Flight Year
6278         2015
6279         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6280  Flight6281  41999  ORD-SFO              3.9         112
6281  Flight6282  41646  ORD-CLT              1.3           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6280             0.708333               525       97125            12
6281             0.541667               125       23125             1

      Flight Year
6280         2014
6281         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6282  Flight6283  41722  ORD-LAX              2.8          82
6283  Flight6284  41888  ORD-DEN              1.8         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6282             0.833333               350       63350             3
6283             0.687500               300       49500             9

      Flight Year
6282         2014
6283         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6284  Flight6285  42063  ORD-LAS              1.7          59
6285  Flight6286  42231  ORD-BOS              2.7          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6284             0.625000               275       45375             2
6285             0.291667               330       54450             8

      Flight Year
6284         2015
6285         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6286  Flight6287  41911  ORD-CLT              2.2         204
6287  Flight6288  42337  ORD-EWR              5.7          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6286             0.895833             125.0     20625.0             9
6287             0.479167             337.5     62437.5            11

      Flight Year
6286         2014
6287         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6288  Flight6289  41945  ORD-PHL              1.7          83
6289  Flight6290  41877  ORD-ATL              9.5         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6288             0.333333               275       49775            11
6289             0.625000               220       36300             8

      Flight Year
6288         2014
6289         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6290  Flight6291  42217  ORD-DFW              2.9         172
6291  Flight6292  42183  ORD-MCO              1.3         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6290             0.750000               220       36300             8
6291             0.666667               275       45375             6

      Flight Year
6290         2015
6291         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6292  Flight6293  42224  ORD-DFW              2.4          88
6293  Flight6294  41900  ORD-SLC              2.8          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6292             0.333333               220       39820             8
6293             0.770833               290       47850             9

      Flight Year
6292         2015
6293         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6294  Flight6295  42176  ORD-JFK              1.7          40
6295  Flight6296  42346  ORD-LAS              0.6          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6294             0.750000               275       45375             6
6295             0.333333               275       50875            12

      Flight Year
6294         2015
6295         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6296  Flight6297  42047  ORD-SEA              2.8          39
6297  Flight6298  42179  ORD-SFO              1.4         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6296             0.833333             350.0     57750.0             2
6297             0.770833             412.5     76312.5             6

      Flight Year
6296         2015
6297         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6298  Flight6299  42086  ORD-DFW              1.0          13
6299  Flight6300  41999  ORD-DTW              1.8         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6298             0.708333               200       37000             3
6299             0.750000               161       26565            12

      Flight Year
6298         2015
6299         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6300  Flight6301  42305  ORD-MIA              1.2          29
6301  Flight6302  41778  ORD-DFW              3.2          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6300             0.833333               300       55500            10
6301             0.604167               200       36200             5

      Flight Year
6300         2015
6301         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6302  Flight6303  41948  ORD-LAS              3.0         146
6303  Flight6304  41896  ORD-CLT              3.1          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6302                0.500               275       50875            11
6303                0.375               125       22625             9

      Flight Year
6302         2014
6303         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6304  Flight6305  41705  ORD-PHX              1.4           7
6305  Flight6306  42338  ORD-DFW              1.4         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6304             0.333333               250       46250             3
6305             0.708333               200       37000            11

      Flight Year
6304         2014
6305         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6306  Flight6307  42142  ORD-DFW              1.2         156
6307  Flight6308  42158  ORD-LAS              2.7         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6306               0.3125             200.0     33000.0             5
6307               0.6875             302.5     55962.5             6

      Flight Year
6306         2015
6307         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6308  Flight6309  42346  ORD-CLT              2.6         204
6309  Flight6310  42211  ORD-LAS              2.1         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6308             0.354167             125.0     20625.0            12
6309             0.625000             302.5     49912.5             7

      Flight Year
6308         2015
6309         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6310  Flight6311  41699  ORD-SFO              3.1          21
6311  Flight6312  42335  ORD-MCO              5.3         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6310             0.458333               375       69375             3
6311             0.333333               375       69375            11

      Flight Year
6310         2014
6311         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6312  Flight6313  42180  ORD-MCO              3.0         140
6313  Flight6314  41680  ORD-DEN              0.9         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6312             0.291667               275       50875             6
6313             0.312500               300       49500             2

      Flight Year
6312         2015
6313         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6314  Flight6315  41697  ORD-IAH              2.9          68
6315  Flight6316  42100  ORD-FLL              1.5          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6314             0.291667               200       36200             2
6315             0.750000               300       55500             4

      Flight Year
6314         2014
6315         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6316  Flight6317  42005  ORD-EWR              3.1         161
6317  Flight6318  41653  ORD-IAD              2.5          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6316             0.854167               225       37125             1
6317             0.604167               300       55500             1

      Flight Year
6316         2015
6317         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6318  Flight6319  41953  ORD-JFK              1.5           3
6319  Flight6320  42246  ORD-LAX              5.8         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6318             0.375000               250       46250            11
6319             0.458333               385       63525             8

      Flight Year
6318         2014
6319         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6320  Flight6321  42205  ORD-JFK              2.2         100
6321  Flight6322  41917  ORD-LAS              1.5         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6320             0.333333               275       50875             7
6321             0.375000               275       50875            10

      Flight Year
6320         2015
6321         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6322  Flight6323  41738  ORD-EWR              2.0         159
6323  Flight6324  42214  ORD-PHX              2.1          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6322             0.354167               225       37125             4
6323             0.750000               275       45375             7

      Flight Year
6322         2014
6323         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6324  Flight6325  42346  ORD-ATL             10.2         115
6325  Flight6326  41824  ORD-DEN              1.7         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6324             0.333333               200       37000            12
6325             0.291667               330       54450             7

      Flight Year
6324         2015
6325         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6326  Flight6327  42067  ORD-EWR              2.7          74
6327  Flight6328  42198  ORD-MCO              1.7          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6326             0.750000               225       40725             3
6327             0.604167               275       45375             7

      Flight Year
6326         2015
6327         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6328  Flight6329  41901  ORD-LAS              1.9         155
6329  Flight6330  42359  ORD-JFK              3.0         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6328             0.666667               275       45375             9
6329             0.291667               350       57750            12

      Flight Year
6328         2014
6329         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6330  Flight6331  42242  ORD-DEN              1.3          55
6331  Flight6332  41972  ORD-LAX              8.9         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6330             0.729167               330       54450             8
6331             0.333333               525       97125            11

      Flight Year
6330         2015
6331         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6332  Flight6333  41787  ORD-PHX              1.6         203
6333  Flight6334  42290  ORD-SFO              2.0          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6332             0.416667               250       41250             5
6333             0.354167               375       69375            10

      Flight Year
6332         2014
6333         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6334  Flight6335  42061  ORD-LAX              4.7         204
6335  Flight6336  41833  ORD-MIA              2.1          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6334             0.791667               350       57750             2
6335             0.708333               330       54450             7

      Flight Year
6334         2015
6335         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6336  Flight6337  41848  ORD-DEN              2.2         135
6337  Flight6338  42172  ORD-DEN              1.3         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6336                0.750               330       61050             7
6337                0.625               330       61050             6

      Flight Year
6336         2014
6337         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6338  Flight6339  42191  ORD-ATL             12.3          96
6339  Flight6340  42134  ORD-ATL             10.6         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6338             0.333333               220       40700             7
6339             0.833333               200       37000             5

      Flight Year
6338         2015
6339         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6340  Flight6341  42106  ORD-LAX              4.1          36
6341  Flight6342  41822  ORD-ATL             10.1         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6340             0.541667               350       57750             4
6341             0.708333               220       40700             7

      Flight Year
6340         2015
6341         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6342  Flight6343  42104  ORD-DFW                1          39
6343  Flight6344  41976  ORD-DTW                1         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6342             0.333333               200       33000             4
6343             0.375000               115       18975            12

      Flight Year
6342         2015
6343         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6344  Flight6345  41945  ORD-LAS              0.9         197
6345  Flight6346  41884  ORD-SEA              1.7          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6344             0.708333               275       45375            11
6345             0.291667               350       64750             9

      Flight Year
6344         2014
6345         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6346  Flight6347  41833  ORD-ATL             13.4         204
6347  Flight6348  42351  ORD-DFW              3.2         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6346             0.541667               220       36300             7
6347             0.291667               200       33000            12

      Flight Year
6346         2014
6347         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6348  Flight6349  41961  ORD-LAS              1.7          14
6349  Flight6350  42045  ORD-LAS              1.9          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6348             0.354167               275       50875            11
6349             0.854167               275       49775             2

      Flight Year
6348         2014
6349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6350  Flight6351  42024  ORD-LGA              3.4         167
6351  Flight6352  41908  ORD-MIA              2.7         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6350             0.750000               275       45375             1
6351             0.708333               300       55500             9

      Flight Year
6350         2015
6351         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6352  Flight6353  42213  ORD-SFO              1.5         127
6353  Flight6354  41856  ORD-IAH              3.2          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6352             0.291667             412.5     76312.5             7
6353             0.458333             220.0     36300.0             8

      Flight Year
6352         2015
6353         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6354  Flight6355  42020  ORD-DEN              2.5         197
6355  Flight6356  42358  ORD-CLT              1.9         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6354             0.333333               300       49500             1
6355             0.750000               125       20625            12

      Flight Year
6354         2015
6355         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6356  Flight6357  42125  ORD-LAS              0.3          39
6357  Flight6358  42203  ORD-PHX              0.6         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6356             0.770833               275       45375             5
6357             0.333333               275       50875             7

      Flight Year
6356         2015
6357         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6358  Flight6359  42089  ORD-LAS              2.5         152
6359  Flight6360  41995  ORD-CLT              5.8         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6358             0.729167               275       45375             3
6359             0.791667               175       28875            12

      Flight Year
6358         2015
6359         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6360  Flight6361  42229  ORD-CLT              3.0           6
6361  Flight6362  41761  ORD-IAD              2.2         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6360             0.791667             137.5     25437.5             8
6361             0.708333             300.0     49500.0             5

      Flight Year
6360         2015
6361         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6362  Flight6363  42362  ORD-EWR              5.1         202
6363  Flight6364  41796  ORD-MCO              1.8           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6362             0.291667               315       51975            12
6363             0.291667               275       50875             6

      Flight Year
6362         2015
6363         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6364  Flight6365  42231  ORD-MCO              2.5         123
6365  Flight6366  42115  ORD-IAH              2.6         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6364             0.812500               275       50875             8
6365             0.729167               200       33000             4

      Flight Year
6364         2015
6365         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6366  Flight6367  41858  ORD-DTW              1.6         172
6367  Flight6368  41828  ORD-LAX              4.5         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6366             0.812500             126.5     20872.5             8
6367             0.770833             385.0     63525.0             7

      Flight Year
6366         2014
6367         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6368  Flight6369  41650  ORD-LAS              1.1          67
6369  Flight6370  42248  ORD-MCO              2.3          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6368             0.833333               275       49775             1
6369             0.770833               250       41250             9

      Flight Year
6368         2014
6369         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6370  Flight6371  42362  ORD-MSP              4.2         111
6371  Flight6372  41969  ORD-MIA              5.2          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6370             0.291667               161       29785            12
6371             0.833333               450       74250            11

      Flight Year
6370         2015
6371         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6372  Flight6373  41727  ORD-DEN              2.2         206
6373  Flight6374  41856  ORD-SFO              2.9         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6372             0.791667             300.0     49500.0             3
6373             0.416667             412.5     68062.5             8

      Flight Year
6372         2014
6373         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6374  Flight6375  41793  ORD-LAX              5.3         128
6375  Flight6376  42359  ORD-EWR              2.4         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6374             0.291667               385       71225             6
6375             0.708333               315       51975            12

      Flight Year
6374         2014
6375         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6376  Flight6377  41732  ORD-DEN              1.2         167
6377  Flight6378  41746  ORD-MIA              2.1          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6376             0.500000               300       49500             4
6377             0.770833               300       54300             4

      Flight Year
6376         2014
6377         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6378  Flight6379  42365  ORD-LAS              4.8          51
6379  Flight6380  42105  ORD-MIA              3.0         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6378             0.791667               385       63525            12
6379             0.791667               300       49500             4

      Flight Year
6378         2015
6379         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6380  Flight6381  42325  ORD-DTW              3.9           9
6381  Flight6382  42009  ORD-LAX              2.5         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6380             0.750000               115       21275            11
6381             0.291667               350       57750             1

      Flight Year
6380         2015
6381         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6382  Flight6383  42170  ORD-JFK              2.2          78
6383  Flight6384  42262  ORD-DFW              0.7          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6382             0.708333               275       49775             6
6383             0.500000               200       37000             9

      Flight Year
6382         2015
6383         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6384  Flight6385  41792  ORD-DFW              0.9          10
6385  Flight6386  42080  ORD-DFW              2.5         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6384             0.708333               220       40700             6
6385             0.791667               200       37000             3

      Flight Year
6384         2014
6385         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6386  Flight6387  42155  ORD-DFW              1.7          15
6387  Flight6388  41929  ORD-MIA              2.3         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6386             0.750000               200       37000             5
6387             0.333333               300       49500            10

      Flight Year
6386         2015
6387         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6388  Flight6389  41677  ORD-CLT              1.5         188
6389  Flight6390  41801  ORD-MSP              2.0         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6388             0.812500             125.0     20625.0             2
6389             0.666667             126.5     23402.5             6

      Flight Year
6388         2014
6389         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6390  Flight6391  41833  ORD-LGA              1.6          26
6391  Flight6392  42334  ORD-LGA              6.5         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6390               0.3125             302.5     55962.5             7
6391               0.8125             412.5     76312.5            11

      Flight Year
6390         2014
6391         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6392  Flight6393  42241  ORD-SFO              1.5          70
6393  Flight6394  41774  ORD-LGA              2.5          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6392             0.791667             412.5     74662.5             8
6393             0.791667             275.0     49775.0             5

      Flight Year
6392         2015
6393         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6394  Flight6395  41758  ORD-DFW              2.6         123
6395  Flight6396  42226  ORD-ATL             10.2         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6394             0.791667               200       37000             4
6395             0.708333               220       40700             8

      Flight Year
6394         2014
6395         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6396  Flight6397  42187  ORD-ATL             10.8          49
6397  Flight6398  41695  ORD-DFW              1.8         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6396             0.750000               220       36300             7
6397             0.291667               200       37000             2

      Flight Year
6396         2015
6397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6398  Flight6399  42331  ORD-LAS              4.1          11
6399  Flight6400  42239  ORD-JFK              1.7          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6398             0.708333             412.5     76312.5            11
6399             0.833333             275.0     50875.0             8

      Flight Year
6398         2015
6399         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6400  Flight6401  41763  ORD-LAS              0.9          61
6401  Flight6402  41656  ORD-LAX              4.7          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6400             0.354167               275       45375             5
6401             0.625000               350       64750             1

      Flight Year
6400         2014
6401         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6402  Flight6403  42191  ORD-IAH              2.1          10
6403  Flight6404  42268  ORD-DTW              2.0           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6402             0.583333               220       40700             7
6403             0.708333               115       21275             9

      Flight Year
6402         2015
6403         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6404  Flight6405  42292  ORD-ATL             10.2          25
6405  Flight6406  41895  ORD-FLL              1.3         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6404             0.291667               200       37000            10
6405             0.895833               300       49500             9

      Flight Year
6404         2015
6405         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6406  Flight6407  42205  ORD-LGA              2.2         140
6407  Flight6408  41855  ORD-ATL              9.3         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6406             0.833333             302.5     55962.5             7
6407             0.500000             220.0     40700.0             8

      Flight Year
6406         2015
6407         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6408  Flight6409  41778  ORD-BWI              2.7         203
6409  Flight6410  41917  ORD-LGA              1.2          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6408             0.812500               240       39600             5
6409             0.354167               275       49775            10

      Flight Year
6408         2014
6409         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6410  Flight6411  41811  ORD-IAH              2.6         186
6411  Flight6412  41781  ORD-MIA              2.4          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6410             0.770833               220       36300             6
6411             0.416667               300       49500             5

      Flight Year
6410         2014
6411         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6412  Flight6413  42191  ORD-PHX              1.5         115
6413  Flight6414  41917  ORD-CLT              1.5         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6412             0.583333               275       50875             7
6413             0.291667               125       20625            10

      Flight Year
6412         2015
6413         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6414  Flight6415  42115  ORD-DEN              1.0          40
6415  Flight6416  42049  ORD-SFO              2.2         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6414             0.333333               300       49500             4
6415             0.333333               375       69375             2

      Flight Year
6414         2015
6415         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6416  Flight6417  41886  ORD-ATL              8.3          20
6417  Flight6418  42251  ORD-DCA              2.2          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6416             0.895833               200       37000             9
6417             0.750000              5000      825000             9

      Flight Year
6416         2014
6417         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6418  Flight6419  42283  ORD-EWR              1.6         172
6419  Flight6420  42015  ORD-ATL              9.0         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6418             0.791667               225       37125            10
6419             0.625000               200       33000             1

      Flight Year
6418         2015
6419         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6420  Flight6421  41988  ORD-ATL              8.1         196
6421  Flight6422  42234  ORD-LAX              5.6         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6420             0.666667               200       33000            12
6421             0.291667               385       63525             8

      Flight Year
6420         2014
6421         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6422  Flight6423  41779  ORD-DTW              3.5         139
6423  Flight6424  42048  ORD-DFW              1.6         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6422             0.791667               115       21275             5
6423             0.666667               200       33000             2

      Flight Year
6422         2014
6423         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6424  Flight6425  42182  ORD-PHX              1.5          49
6425  Flight6426  41969  ORD-SFO              3.6         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6424             0.812500             275.0     45375.0             6
6425             0.729167             562.5     92812.5            11

      Flight Year
6424         2015
6425         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6426  Flight6427  41837  ORD-DFW              1.8          35
6427  Flight6428  42025  ORD-PHL              1.4          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6426             0.791667               220       40700             7
6427             0.354167               275       50875             1

      Flight Year
6426         2014
6427         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6428  Flight6429  41995  ORD-DFW              2.7          17
6429  Flight6430  41999  ORD-SEA              4.8         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6428             0.416667               280       51800            12
6429             0.770833               490       90650            12

      Flight Year
6428         2014
6429         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6430  Flight6431  41996  ORD-ATL             13.5          11
6431  Flight6432  41930  ORD-MCO              2.0          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6430             0.750000               280       51800            12
6431             0.854167               250       45250            10

      Flight Year
6430         2014
6431         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6432  Flight6433  42141  ORD-SEA              1.1          20
6433  Flight6434  41988  ORD-IAH              1.8          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6432             0.854167               350       64750             5
6433             0.416667               200       33000            12

      Flight Year
6432         2015
6433         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6434  Flight6435  42293  ORD-EWR                2           5
6435  Flight6436  41978  ORD-SEA                1         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6434                0.375               225       41625            10
6435                0.750               350       64750            12

      Flight Year
6434         2015
6435         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6436  Flight6437  42058  ORD-DFW              1.9           7
6437  Flight6438  42051  ORD-SFO              3.0          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6436             0.708333               200       37000             2
6437             0.375000               375       67875             2

      Flight Year
6436         2015
6437         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6438  Flight6439  41878  ORD-PHX              1.8         200
6439  Flight6440  41985  ORD-DTW              1.5         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6438             0.604167               275       45375             8
6439             0.645833               115       18975            12

      Flight Year
6438         2014
6439         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6440  Flight6441  41995  ORD-DTW              4.1         191
6441  Flight6442  42128  ORD-LAS              2.4         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6440             0.812500               161       26565            12
6441             0.708333               275       50875             5

      Flight Year
6440         2014
6441         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6442  Flight6443  41721  ORD-MIA              2.2          57
6443  Flight6444  41698  ORD-SEA              0.8         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6442             0.291667               300       49500             3
6443             0.791667               350       64750             2

      Flight Year
6442         2014
6443         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6444  Flight6445  42160  ORD-PHX              0.9          71
6445  Flight6446  42131  ORD-ATL              7.2         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6444             0.291667               275       49775             6
6445             0.291667               200       37000             5

      Flight Year
6444         2015
6445         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6446  Flight6447  41715  ORD-SFO              2.7          19
6447  Flight6448  42047  ORD-SEA              1.1         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6446             0.333333               375       69375             3
6447             0.333333               350       57750             2

      Flight Year
6446         2014
6447         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6448  Flight6449  42050  ORD-ATL             10.8         164
6449  Flight6450  42308  ORD-DEN              2.7         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6448                  0.5               200       33000             2
6449                  0.5               300       55500            10

      Flight Year
6448         2015
6449         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6450  Flight6451  42210  ORD-SEA              2.7         187
6451  Flight6452  42127  ORD-PHL              2.5         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6450             0.583333               385       63525             7
6451             0.750000               275       50875             5

      Flight Year
6450         2015
6451         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6452  Flight6453  42130  ORD-DTW              1.4          97
6453  Flight6454  41918  ORD-DFW              2.5          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6452             0.854167               115       21275             5
6453             0.708333               200       37000            10

      Flight Year
6452         2015
6453         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6454  Flight6455  41856  ORD-MCO              1.5         152
6455  Flight6456  42169  ORD-PHL              0.8         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6454             0.541667             275.0     45375.0             8
6455             0.791667             302.5     49912.5             6

      Flight Year
6454         2014
6455         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6456  Flight6457  41693  ORD-DEN              1.4          22
6457  Flight6458  42249  ORD-DTW              1.8           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6456             0.750000               300       55500             2
6457             0.708333               115       21275             9

      Flight Year
6456         2014
6457         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6458  Flight6459  41847  ORD-MSP              2.1         133
6459  Flight6460  42122  ORD-DFW              2.3         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6458             0.791667             126.5     23402.5             7
6459             0.666667             200.0     33000.0             4

      Flight Year
6458         2014
6459         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6460  Flight6461  41865  ORD-DEN              1.9          61
6461  Flight6462  41972  ORD-LAX             10.3         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6460             0.812500               330       54450             8
6461             0.604167               525       86625            11

      Flight Year
6460         2014
6461         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6462  Flight6463  41969  ORD-ATL             17.5          35
6463  Flight6464  41904  ORD-LGA              2.5         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6462             0.812500               300       55500            11
6463             0.458333               275       45375             9

      Flight Year
6462         2014
6463         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6464  Flight6465  42019  ORD-JFK              2.8          90
6465  Flight6466  41735  ORD-EWR              2.3          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6464             0.708333               250       45250             1
6465             0.583333               225       41625             4

      Flight Year
6464         2015
6465         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6466  Flight6467  42308  ORD-ATL              9.5          67
6467  Flight6468  42003  ORD-BOS              1.8          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6466             0.291667               200       36200            10
6467             0.291667               300       55500            12

      Flight Year
6466         2015
6467         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6468  Flight6469  41994  ORD-IAH              3.1          65
6469  Flight6470  42215  ORD-JFK              1.9          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6468             0.708333               200       36200            12
6469             0.333333               275       45375             7

      Flight Year
6468         2014
6469         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6470  Flight6471  42025  ORD-SEA              1.3         165
6471  Flight6472  41770  ORD-DFW              1.4         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6470             0.458333               350       57750             1
6471             0.875000               200       37000             5

      Flight Year
6470         2015
6471         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6472  Flight6473  41784  ORD-DEN              2.6         154
6473  Flight6474  42341  ORD-LAS              1.5         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6472             0.812500               300       49500             5
6473             0.791667               275       45375            12

      Flight Year
6472         2014
6473         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6474  Flight6475  41874  ORD-DTW              3.0          22
6475  Flight6476  42204  ORD-FLL              1.9         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6474             0.500000             126.5     23402.5             8
6475             0.708333             330.0     54450.0             7

      Flight Year
6474         2014
6475         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6476  Flight6477  42150  ORD-BOS              2.1         158
6477  Flight6478  42077  ORD-ATL             12.6          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6476             0.333333               300       49500             5
6477             0.333333               200       33000             3

      Flight Year
6476         2015
6477         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6478  Flight6479  41991  ORD-CLT              2.7          49
6479  Flight6480  41645  ORD-MCO              2.4         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6478             0.770833               125       20625            12
6479             0.333333               250       41250             1

      Flight Year
6478         2014
6479         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6480  Flight6481  42346  ORD-CLT              2.1         149
6481  Flight6482  41967  ORD-JFK              4.4          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6480             0.500000               125       23125            12
6481             0.291667               375       61875            11

      Flight Year
6480         2015
6481         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6482  Flight6483  42116  ORD-MIA              1.3          27
6483  Flight6484  42159  ORD-MIA              3.0         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6482             0.791667               300       55500             4
6483             0.666667               330       61050             6

      Flight Year
6482         2015
6483         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6484  Flight6485  41765  ORD-SEA              1.2         176
6485  Flight6486  42135  ORD-ATL              9.7          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6484             0.875000               350       57750             5
6485             0.833333               200       33000             5

      Flight Year
6484         2014
6485         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6486  Flight6487  42310  ORD-LAX              2.3         115
6487  Flight6488  42196  ORD-CLT              1.4         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6486             0.750000             350.0     64750.0            11
6487             0.791667             137.5     25437.5             7

      Flight Year
6486         2015
6487         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6488  Flight6489  42243  ORD-MSP              1.7          34
6489  Flight6490  41709  ORD-CLT              2.4          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6488             0.291667             126.5     23402.5             8
6489             0.583333             125.0     20625.0             3

      Flight Year
6488         2015
6489         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6490  Flight6491  41652  ORD-IAH              1.5          23
6491  Flight6492  41764  ORD-DFW              0.5         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6490             0.479167               200       37000             1
6491             0.770833               200       37000             5

      Flight Year
6490         2014
6491         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6492  Flight6493  42166  ORD-IAH              2.8          56
6493  Flight6494  42197  ORD-MCO              2.7         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6492             0.375000               220       36300             6
6493             0.291667               275       50875             7

      Flight Year
6492         2015
6493         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6494  Flight6495  41717  ORD-SFO              2.9         128
6495  Flight6496  42308  ORD-DFW              1.9         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6494             0.729167               375       69375             3
6495             0.708333               200       33000            10

      Flight Year
6494         2014
6495         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6496  Flight6497  41960  ORD-ATL              7.7          47
6497  Flight6498  41751  ORD-BOS              1.7         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6496             0.354167               200       33000            11
6497             0.708333               300       49500             4

      Flight Year
6496         2014
6497         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6498  Flight6499  42094  ORD-MIA              1.0          90
6499  Flight6500  42183  ORD-ATL              9.9         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6498             0.750000               300       54300             3
6499             0.708333               220       40700             6

      Flight Year
6498         2015
6499         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6500  Flight6501  42182  ORD-LAX              3.8          18
6501  Flight6502  41999  ORD-IAH              5.3          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6500             0.729167               385       71225             6
6501             0.791667               280       51800            12

      Flight Year
6500         2015
6501         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6502  Flight6503  41795  ORD-SEA              1.1          34
6503  Flight6504  42334  ORD-PHX              4.5         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6502             0.541667               385       71225             6
6503             0.875000               375       61875            11

      Flight Year
6502         2014
6503         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6504  Flight6505  42173  ORD-DFW              1.6           9
6505  Flight6506  41892  ORD-SLC              2.6         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6504             0.458333               220       40700             6
6505             0.541667               290       47850             9

      Flight Year
6504         2015
6505         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6506  Flight6507  42193  ORD-LAX              4.6         164
6507  Flight6508  42149  ORD-JFK              1.9         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6506             0.333333               385       63525             7
6507             0.416667               250       46250             5

      Flight Year
6506         2015
6507         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6508  Flight6509  41666  ORD-MSP              1.7          43
6509  Flight6510  41960  ORD-FLL              2.4          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6508             0.770833               115       18975             1
6509             0.291667               300       55500            11

      Flight Year
6508         2014
6509         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6510  Flight6511  42331  ORD-MSP              4.5          87
6511  Flight6512  42308  ORD-CLT              2.0         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6510             0.750000             172.5     31222.5            11
6511             0.833333             125.0     23125.0            10

      Flight Year
6510         2015
6511         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6512  Flight6513  42264  ORD-LGA              2.2           8
6513  Flight6514  42302  ORD-LAS              1.5         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6512             0.333333               275       50875             9
6513             0.416667               275       50875            10

      Flight Year
6512         2015
6513         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6514  Flight6515  41998  ORD-PHX              2.6          79
6515  Flight6516  41740  ORD-CLT              3.8         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6514             0.291667               350       63350            12
6515             0.791667               125       23125             4

      Flight Year
6514         2014
6515         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6516  Flight6517  41834  ORD-MSP              2.0         106
6517  Flight6518  41703  ORD-ATL              8.3          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6516                0.625             126.5     23402.5             7
6517                0.750             200.0     37000.0             3

      Flight Year
6516         2014
6517         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6518  Flight6519  41796  ORD-DFW              2.1         109
6519  Flight6520  41974  ORD-JFK              2.9          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6518             0.520833               220       40700             6
6519             0.791667               250       45250            12

      Flight Year
6518         2014
6519         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6520  Flight6521  41938  ORD-MCO              1.1          77
6521  Flight6522  41829  ORD-JFK              3.2          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6520             0.395833               250       45250            10
6521             0.708333               275       50875             7

      Flight Year
6520         2014
6521         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6522  Flight6523  41785  ORD-ATL              8.8         131
6523  Flight6524  41769  ORD-LAS              2.1         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6522             0.729167               200       37000             5
6523             0.291667               275       50875             5

      Flight Year
6522         2014
6523         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6524  Flight6525  42231  ORD-IAH              1.5          66
6525  Flight6526  42344  ORD-CLT              2.2          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6524             0.541667               220       39820             8
6525             0.333333               125       23125            12

      Flight Year
6524         2015
6525         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6526  Flight6527  41693  ORD-CLT              3.0          40
6527  Flight6528  41745  ORD-PHX              3.1         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6526             0.875000               125       20625             2
6527             0.770833               250       41250             4

      Flight Year
6526         2014
6527         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6528  Flight6529  42221  ORD-IAH              1.3          61
6529  Flight6530  41834  ORD-DFW              2.2          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6528             0.833333               220       36300             8
6529             0.750000               220       36300             7

      Flight Year
6528         2015
6529         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6530  Flight6531  42331  ORD-CLT              6.4          72
6531  Flight6532  42309  ORD-IAH              2.9         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6530             0.395833             187.5     33937.5            11
6531             0.375000             200.0     33000.0            11

      Flight Year
6530         2015
6531         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6532  Flight6533  42220  ORD-LAX              2.9          43
6533  Flight6534  42243  ORD-LAS              2.5          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6532             0.541667             385.0     63525.0             8
6533             0.833333             302.5     49912.5             8

      Flight Year
6532         2015
6533         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6534  Flight6535  42053  ORD-MSP              2.8          36
6535  Flight6536  41728  ORD-MIA              2.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6534             0.770833               115       18975             2
6535             0.791667               300       49500             3

      Flight Year
6534         2015
6535         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6536  Flight6537  41910  ORD-DTW              2.4         109
6537  Flight6538  41809  ORD-LAS              2.0          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6536             0.770833             115.0     21275.0             9
6537             0.833333             302.5     54752.5             6

      Flight Year
6536         2014
6537         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6538  Flight6539  41820  ORD-DEN              1.6          49
6539  Flight6540  41767  ORD-BOS              1.6           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6538             0.666667               330       54450             6
6539             0.729167               300       55500             5

      Flight Year
6538         2014
6539         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6540  Flight6541  42366  ORD-DEN              2.6          73
6541  Flight6542  41697  ORD-SFO              2.9         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6540             0.583333               300       54300            12
6541             0.833333               375       61875             2

      Flight Year
6540         2015
6541         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6542  Flight6543  41879  ORD-JFK              2.5         182
6543  Flight6544  41872  ORD-IAH              2.0         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6542             0.791667               275       45375             8
6543             0.375000               220       36300             8

      Flight Year
6542         2014
6543         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6544  Flight6545  41648  ORD-MCO              1.9         117
6545  Flight6546  41842  ORD-MCO              2.2         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6544                0.625               250       46250             1
6545                0.375               275       45375             7

      Flight Year
6544         2014
6545         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6546  Flight6547  42233  ORD-ATL              9.3         128
6547  Flight6548  42035  ORD-LAS              3.2         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6546             0.708333               220       40700             8
6547             0.708333               275       50875             1

      Flight Year
6546         2015
6547         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6548  Flight6549  42040  ORD-DFW              3.4         193
6549  Flight6550  41918  ORD-PHX              2.5         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6548             0.750000               200       33000             2
6549             0.583333               250       41250            10

      Flight Year
6548         2015
6549         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6550  Flight6551  41898  ORD-SFO              1.9          17
6551  Flight6552  42102  ORD-SLC              1.8          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6550             0.791667               375       69375             9
6551             0.583333               290       52490             4

      Flight Year
6550         2014
6551         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6552  Flight6553  41698  ORD-SFO              2.0         175
6553  Flight6554  42080  ORD-DCA              1.8         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6552             0.625000               375       61875             2
6553             0.458333              5000      825000             3

      Flight Year
6552         2014
6553         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6554  Flight6555  41883  ORD-DEN              2.5          53
6555  Flight6556  41653  ORD-JFK              2.0         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6554             0.312500               300       49500             9
6555             0.416667               250       46250             1

      Flight Year
6554         2014
6555         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6556  Flight6557  42198  ORD-SFO              2.0         185
6557  Flight6558  42112  ORD-CLT              1.9         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6556             0.791667             412.5     68062.5             7
6557             0.729167             125.0     20625.0             4

      Flight Year
6556         2015
6557         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6558  Flight6559  42035  ORD-ATL              9.2          79
6559  Flight6560  41936  ORD-CLT              1.4          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6558             0.708333               200       36200             1
6559             0.791667               125       20625            10

      Flight Year
6558         2015
6559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6560  Flight6561  41827  ORD-DEN              3.3         129
6561  Flight6562  42109  ORD-DFW              2.1         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6560             0.708333               330       61050             7
6561             0.770833               200       33000             4

      Flight Year
6560         2014
6561         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6562  Flight6563  41940  ORD-SFO              2.5          77
6563  Flight6564  41865  ORD-LAS              1.9          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6562             0.375000             375.0     67875.0            10
6563             0.333333             302.5     54752.5             8

      Flight Year
6562         2014
6563         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6564  Flight6565  42001  ORD-MCO              4.7           6
6565  Flight6566  42228  ORD-MCO              2.2          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6564             0.291667               350       64750            12
6565             0.812500               275       50875             8

      Flight Year
6564         2014
6565         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6566  Flight6567  42156  ORD-LAX              6.5         201
6567  Flight6568  41727  ORD-EWR              2.4         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6566             0.604167               385       63525             6
6567             0.312500               225       37125             3

      Flight Year
6566         2015
6567         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6568  Flight6569  42061  ORD-SFO              1.0           4
6569  Flight6570  42077  ORD-LAS              2.9          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6568             0.729167               375       69375             2
6569             0.583333               275       49775             3

      Flight Year
6568         2015
6569         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6570  Flight6571  42191  ORD-LAS              0.5         188
6571  Flight6572  41935  ORD-JFK              2.2         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6570             0.375000             302.5     49912.5             7
6571             0.770833             250.0     41250.0            10

      Flight Year
6570         2015
6571         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6572  Flight6573  41838  ORD-LAX              4.8          41
6573  Flight6574  42172  ORD-PHX              1.4          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6572             0.708333               385       63525             7
6573             0.770833               275       50875             6

      Flight Year
6572         2014
6573         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6574  Flight6575  42113  ORD-EWR              1.9         101
6575  Flight6576  41743  ORD-CLT              2.6         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6574             0.791667               225       41625             4
6575             0.750000               125       23125             4

      Flight Year
6574         2015
6575         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6576  Flight6577  42012  ORD-EWR              0.6         151
6577  Flight6578  41669  ORD-ATL             11.0         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6576             0.770833               225       41625             1
6577             0.729167               200       37000             1

      Flight Year
6576         2015
6577         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6578  Flight6579  41970  ORD-SEA              5.9          63
6579  Flight6580  41753  ORD-CLT              1.7          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6578             0.791667               525       95025            11
6579             0.625000               125       23125             4

      Flight Year
6578         2014
6579         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6580  Flight6581  41984  ORD-LAX              2.8          95
6581  Flight6582  41926  ORD-LAX              3.3         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6580             0.729167               350       64750            12
6581             0.750000               350       57750            10

      Flight Year
6580         2014
6581         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6582  Flight6583  42363  ORD-DFW              3.8         172
6583  Flight6584  42262  ORD-LAS              2.8          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6582               0.8125               280       46200            12
6583               0.3125               275       45375             9

      Flight Year
6582         2015
6583         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6584  Flight6585  42014  ORD-DEN              1.5         194
6585  Flight6586  42227  ORD-FLL             -0.4         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6584             0.770833               300       49500             1
6585             0.791667               330       54450             8

      Flight Year
6584         2015
6585         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6586  Flight6587  41999  ORD-MSP              6.8           5
6587  Flight6588  42123  ORD-MIA              1.7         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6586             0.333333               161       29785            12
6587             0.791667               300       55500             4

      Flight Year
6586         2014
6587         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6588  Flight6589  42168  ORD-LGA              0.9         100
6589  Flight6590  42251  ORD-JFK              1.2          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6588             0.291667             302.5     55962.5             6
6589             0.291667             250.0     41250.0             9

      Flight Year
6588         2015
6589         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6590  Flight6591  41866  ORD-DEN              2.3         180
6591  Flight6592  42163  ORD-DEN              1.5         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6590             0.750000               330       54450             8
6591             0.333333               330       54450             6

      Flight Year
6590         2014
6591         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6592  Flight6593  42364  ORD-SEA              5.3         201
6593  Flight6594  42243  ORD-LAS              1.7         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6592             0.416667             490.0     80850.0            12
6593             0.291667             302.5     49912.5             8

      Flight Year
6592         2015
6593         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6594  Flight6595  41843  ORD-DFW              1.6         194
6595  Flight6596  42017  ORD-ATL              6.5         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6594             0.291667               220       36300             7
6595             0.875000               200       33000             1

      Flight Year
6594         2014
6595         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6596  Flight6597  42256  ORD-IAH              2.5         200
6597  Flight6598  41649  ORD-MSP              1.5         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6596                0.750               200       33000             9
6597                0.625               115       21275             1

      Flight Year
6596         2015
6597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6598  Flight6599  41783  ORD-EWR              1.6          78
6599  Flight6600  41929  ORD-DEN              2.0          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6598             0.375000               225       40725             5
6599             0.458333               300       54300            10

      Flight Year
6598         2014
6599         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6600  Flight6601  42030  ORD-MIA              1.3          40
6601  Flight6602  41706  ORD-SEA              1.6         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6600             0.416667               300       49500             1
6601             0.416667               350       64750             3

      Flight Year
6600         2015
6601         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6602  Flight6603  42161  ORD-IAD              1.4          58
6603  Flight6604  42186  ORD-DFW              1.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6602             0.291667               330       54450             6
6603             0.791667               220       39820             7

      Flight Year
6602         2015
6603         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6604  Flight6605  41787  ORD-SFO              2.1         119
6605  Flight6606  41888  ORD-DTW              3.0         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6604             0.416667               375       69375             5
6605             0.333333               115       18975             9

      Flight Year
6604         2014
6605         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6606  Flight6607  41655  ORD-LAX              4.1          18
6607  Flight6608  42165  ORD-SEA              1.5          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6606             0.333333               350       64750             1
6607             0.750000               385       63525             6

      Flight Year
6606         2014
6607         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6608  Flight6609  41757  ORD-MSP              2.8         138
6609  Flight6610  42195  ORD-MCO              3.2         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6608             0.416667               115       21275             4
6609             0.708333               275       50875             7

      Flight Year
6608         2014
6609         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6610  Flight6611  42100  ORD-EWR              1.7         184
6611  Flight6612  41971  ORD-SEA              3.6          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6610             0.354167               225       37125             4
6611             0.291667               525       95025            11

      Flight Year
6610         2015
6611         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6612  Flight6613  41910  ORD-MSP              2.7           7
6613  Flight6614  42246  ORD-LGA              2.3          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6612             0.354167             115.0     21275.0             9
6613             0.708333             302.5     54752.5             8

      Flight Year
6612         2014
6613         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6614  Flight6615  42363  ORD-SEA              5.5          41
6615  Flight6616  42013  ORD-MIA              1.9          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6614             0.333333               490       80850            12
6615             0.291667               300       49500             1

      Flight Year
6614         2015
6615         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6616  Flight6617  42086  ORD-LAX              4.0          85
6617  Flight6618  42150  ORD-MCO              1.3         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6616               0.5000               350       63350             3
6617               0.6875               250       41250             5

      Flight Year
6616         2015
6617         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6618  Flight6619  42149  ORD-FLL              1.4         131
6619  Flight6620  41944  ORD-PHL              2.0         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6618             0.333333               300       55500             5
6619             0.583333               275       50875            11

      Flight Year
6618         2015
6619         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6620  Flight6621  42082  ORD-CLT              1.3         200
6621  Flight6622  42136  ORD-DFW              3.0         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6620             0.708333               125       20625             3
6621             0.750000               200       37000             5

      Flight Year
6620         2015
6621         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6622  Flight6623  41967  ORD-MIA              4.7          49
6623  Flight6624  42362  ORD-PHX              3.8         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6622             0.333333               450       74250            11
6623             0.750000               350       57750            12

      Flight Year
6622         2014
6623         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6624  Flight6625  41707  ORD-FLL              1.6          23
6625  Flight6626  42196  ORD-JFK              2.9          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6624             0.791667               300       55500             3
6625             0.854167               275       49775             7

      Flight Year
6624         2014
6625         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6626  Flight6627  42147  ORD-PHX              1.9         184
6627  Flight6628  41824  ORD-MIA              3.4         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6626               0.8750               250       41250             5
6627               0.8125               330       54450             7

      Flight Year
6626         2015
6627         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6628  Flight6629  42005  ORD-SFO              2.4         142
6629  Flight6630  42309  ORD-SFO              0.3          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6628             0.791667               375       69375             1
6629             0.687500               375       69375            11

      Flight Year
6628         2015
6629         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6630  Flight6631  42166  ORD-JFK              2.0         189
6631  Flight6632  41649  ORD-ATL              7.9          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6630                 0.75               275       45375             6
6631                 0.50               200       36200             1

      Flight Year
6630         2015
6631         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6632  Flight6633  41680  ORD-DEN              1.8           3
6633  Flight6634  41864  ORD-LAX              3.6          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6632             0.791667               300       55500             2
6633             0.812500               385       71225             8

      Flight Year
6632         2014
6633         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6634  Flight6635  41693  ORD-ATL              9.4          49
6635  Flight6636  41938  ORD-SEA              2.0          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6634             0.625000               200       33000             2
6635             0.833333               350       64750            10

      Flight Year
6634         2014
6635         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6636  Flight6637  42073  ORD-MIA              1.9         157
6637  Flight6638  41860  ORD-DFW              1.2         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6636             0.291667               300       49500             3
6637             0.458333               220       36300             8

      Flight Year
6636         2015
6637         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6638  Flight6639  42246  ORD-CLT              2.6         198
6639  Flight6640  41875  ORD-FLL              1.4         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6638             0.875000             137.5     22687.5             8
6639             0.770833             330.0     54450.0             8

      Flight Year
6638         2015
6639         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6640  Flight6641  41711  ORD-ATL             12.7          86
6641  Flight6642  41753  ORD-JFK              2.0          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6640             0.354167               200       36200             3
6641             0.291667               250       46250             4

      Flight Year
6640         2014
6641         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6642  Flight6643  42361  ORD-JFK              4.7         119
6643  Flight6644  41717  ORD-DFW              1.9         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6642             0.750000               350       64750            12
6643             0.333333               200       37000             3

      Flight Year
6642         2015
6643         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6644  Flight6645  42343  ORD-PHX              3.1         159
6645  Flight6646  41897  ORD-SEA              1.3          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6644             0.562500               250       41250            12
6645             0.729167               350       63350             9

      Flight Year
6644         2015
6645         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6646  Flight6647  41647  ORD-PHX              1.2          11
6647  Flight6648  41805  ORD-SFO              2.5         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6646             0.708333             250.0     46250.0             1
6647             0.729167             412.5     76312.5             6

      Flight Year
6646         2014
6647         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6648  Flight6649  42051  ORD-DEN              1.4          45
6649  Flight6650  41963  ORD-IAD              3.3          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6648             0.750000               300       49500             2
6649             0.666667               300       49500            11

      Flight Year
6648         2015
6649         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6650  Flight6651  42253  ORD-SFO              1.3         142
6651  Flight6652  42332  ORD-LAS              3.3         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6650             0.750000             375.0     69375.0             9
6651             0.354167             412.5     68062.5            11

      Flight Year
6650         2015
6651         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6652  Flight6653  42343  ORD-JFK              2.0         205
6653  Flight6654  42062  ORD-DFW              1.3           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6652             0.708333               250       41250            12
6653             0.770833               200       37000             2

      Flight Year
6652         2015
6653         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6654  Flight6655  42329  ORD-IAH              2.4          42
6655  Flight6656  42333  ORD-DEN              4.2          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6654             0.854167               200       33000            11
6655             0.625000               450       81450            11

      Flight Year
6654         2015
6655         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6656  Flight6657  42008  ORD-PHL              1.9          55
6657  Flight6658  42042  ORD-PHX              1.9         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6656             0.354167               275       45375             1
6657             0.416667               250       46250             2

      Flight Year
6656         2015
6657         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6658  Flight6659  41969  ORD-DEN              6.3           4
6659  Flight6660  42099  ORD-PHX              0.7          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6658             0.333333               450       83250            11
6659             0.541667               250       45250             4

      Flight Year
6658         2014
6659         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6660  Flight6661  42010  ORD-IAH              1.3         204
6661  Flight6662  42179  ORD-LAX              6.9         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6660             0.833333               200       33000             1
6661             0.770833               385       63525             6

      Flight Year
6660         2015
6661         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6662  Flight6663  41866  ORD-ATL             10.5          19
6663  Flight6664  41704  ORD-PHX              1.8          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6662             0.291667               220       40700             8
6663             0.729167               250       41250             3

      Flight Year
6662         2014
6663         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6664  Flight6665  42138  ORD-DEN              2.4          56
6665  Flight6666  42075  ORD-JFK              0.8         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6664             0.333333               300       49500             5
6665             0.770833               250       46250             3

      Flight Year
6664         2015
6665         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6666  Flight6667  41830  ORD-BWI              1.6          80
6667  Flight6668  41874  ORD-LAX              4.9         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6666             0.812500               264       47784             7
6667             0.291667               385       71225             8

      Flight Year
6666         2014
6667         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6668  Flight6669  42092  ORD-PHX              3.1           8
6669  Flight6670  41881  ORD-IAH              2.5          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6668             0.750000               250       46250             3
6669             0.729167               220       36300             8

      Flight Year
6668         2015
6669         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6670  Flight6671  41726  ORD-LAX              2.8          20
6671  Flight6672  42349  ORD-LAS              2.3         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6670             0.333333               350       64750             3
6671             0.833333               275       45375            12

      Flight Year
6670         2014
6671         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6672  Flight6673  42293  ORD-DFW              1.9          29
6673  Flight6674  41971  ORD-MSP              4.4         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6672             0.791667             200.0     37000.0            10
6673             0.625000             172.5     31912.5            11

      Flight Year
6672         2015
6673         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6674  Flight6675  41888  ORD-DFW              1.2          90
6675  Flight6676  41742  ORD-CLT              2.7          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6674             0.791667               200       36200             9
6675             0.791667               125       20625             4

      Flight Year
6674         2014
6675         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6676  Flight6677  42300  ORD-PHL              0.8          27
6677  Flight6678  42158  ORD-PHL              2.2          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6676             0.833333             275.0     50875.0            10
6677             0.791667             302.5     49912.5             6

      Flight Year
6676         2015
6677         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6678  Flight6679  42222  ORD-DTW              1.8           7
6679  Flight6680  42152  ORD-IAD              1.0         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6678             0.708333             126.5     23402.5             8
6679             0.395833             300.0     49500.0             5

      Flight Year
6678         2015
6679         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6680  Flight6681  42255  ORD-IAD              0.8          98
6681  Flight6682  41717  ORD-EWR              3.1         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6680             0.416667               300       55500             9
6681             0.833333               225       37125             3

      Flight Year
6680         2015
6681         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6682  Flight6683  42328  ORD-IAD              2.5         210
6683  Flight6684  41758  ORD-MIA              1.2         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6682             0.708333               300       49500            11
6683             0.791667               300       55500             4

      Flight Year
6682         2015
6683         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6684  Flight6685  41969  ORD-IAH              5.8         151
6685  Flight6686  42192  ORD-IAH              2.7         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6684             0.437500               300       55500            11
6685             0.333333               220       40700             7

      Flight Year
6684         2014
6685         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6686  Flight6687  42368  ORD-LAX              4.8         164
6687  Flight6688  42173  ORD-SFO              0.4          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6686             0.791667             350.0     57750.0            12
6687             0.541667             412.5     74662.5             6

      Flight Year
6686         2015
6687         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6688  Flight6689  42247  ORD-PHX              1.9         154
6689  Flight6690  42182  ORD-FLL              2.0         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6688             0.354167               275       45375             8
6689             0.312500               330       61050             6

      Flight Year
6688         2015
6689         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6690  Flight6691  42138  ORD-DFW              2.4          23
6691  Flight6692  42286  ORD-JFK              1.7           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6690               0.6875               200       37000             5
6691               0.4375               250       46250            10

      Flight Year
6690         2015
6691         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6692  Flight6693  42315  ORD-LGA              0.9          90
6693  Flight6694  42183  ORD-MIA              1.7          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6692             0.354167               275       49775            11
6693             0.750000               330       59730             6

      Flight Year
6692         2015
6693         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6694  Flight6695  41880  ORD-DFW              1.6         168
6695  Flight6696  42299  ORD-LAX              3.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6694             0.458333               220       36300             8
6695             0.312500               350       63350            10

      Flight Year
6694         2014
6695         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6696  Flight6697  41681  ORD-DFW              2.8         165
6697  Flight6698  42257  ORD-PHL              1.9          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6696             0.708333               200       33000             2
6697             0.770833               275       49775             9

      Flight Year
6696         2014
6697         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6698  Flight6699  42087  ORD-SFO              1.6         155
6699  Flight6700  42163  ORD-EWR              2.2          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6698             0.770833             375.0     61875.0             3
6699             0.458333             247.5     44797.5             6

      Flight Year
6698         2015
6699         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6700  Flight6701  41698  ORD-PHL              2.1          43
6701  Flight6702  42009  ORD-DFW              1.6          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6700             0.312500               275       45375             2
6701             0.291667               200       33000             1

      Flight Year
6700         2014
6701         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6702  Flight6703  42010  ORD-BOS              3.7          66
6703  Flight6704  41693  ORD-LAS              1.7         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6702             0.812500               300       54300             1
6703             0.666667               275       45375             2

      Flight Year
6702         2015
6703         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6704  Flight6705  41942  ORD-LGA              2.4         126
6705  Flight6706  41753  ORD-ATL              8.7          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6704             0.333333               275       50875            10
6705             0.562500               200       37000             4

      Flight Year
6704         2014
6705         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6706  Flight6707  41922  ORD-CLT              1.8         210
6707  Flight6708  42084  ORD-IAH              1.8         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6706             0.708333               125       20625            10
6707             0.395833               200       33000             3

      Flight Year
6706         2014
6707         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6708  Flight6709  41840  ORD-JFK              2.0         169
6709  Flight6710  41951  ORD-JFK              1.6          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6708             0.666667               275       45375             7
6709             0.750000               250       46250            11

      Flight Year
6708         2014
6709         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6710  Flight6711  42332  ORD-ATL             16.4          42
6711  Flight6712  42237  ORD-LAX              5.6         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6710             0.791667               300       49500            11
6711             0.791667               385       63525             8

      Flight Year
6710         2015
6711         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6712  Flight6713  41839  ORD-FLL              1.5         171
6713  Flight6714  41737  ORD-EWR              1.7         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6712               0.8125               330       54450             7
6713               0.6250               225       37125             4

      Flight Year
6712         2014
6713         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6714  Flight6715  41825  ORD-LGA              2.3          36
6715  Flight6716  42361  ORD-IAH              2.6          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6714             0.791667             302.5     49912.5             7
6715             0.291667             280.0     50680.0            12

      Flight Year
6714         2014
6715         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6716  Flight6717  42313  ORD-MSP              2.8         134
6717  Flight6718  42175  ORD-SEA              1.4          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6716             0.708333               115       21275            11
6717             0.562500               385       63525             6

      Flight Year
6716         2015
6717         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6718  Flight6719  42300  ORD-MSP              0.4         158
6719  Flight6720  41931  ORD-CLT              2.4           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6718             0.333333               115       18975            10
6719             0.854167               125       23125            10

      Flight Year
6718         2015
6719         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6720  Flight6721  41805  ORD-BOS              1.6          98
6721  Flight6722  41941  ORD-DEN              1.0           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6720             0.291667               330       61050             6
6721             0.312500               300       55500            10

      Flight Year
6720         2014
6721         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6722  Flight6723  42050  ORD-MSP              1.3         143
6723  Flight6724  42244  ORD-FLL              2.0          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6722             0.666667               115       21275             2
6723             0.750000               330       59730             8

      Flight Year
6722         2015
6723         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6724  Flight6725  42361  ORD-ATL             15.8          62
6725  Flight6726  41998  ORD-IAH              3.9         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6724             0.750000               280       46200            12
6725             0.708333               280       51800            12

      Flight Year
6724         2015
6725         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6726  Flight6727  42198  ORD-LAX              4.6          84
6727  Flight6728  41949  ORD-JFK              1.9          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6726             0.770833               385       69685             7
6727             0.791667               250       46250            11

      Flight Year
6726         2015
6727         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6728  Flight6729  41972  ORD-DTW              3.4          91
6729  Flight6730  42255  ORD-MCO              3.0          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6728             0.458333             172.5     31912.5            11
6729             0.812500             250.0     46250.0             9

      Flight Year
6728         2014
6729         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6730  Flight6731  41789  ORD-BOS              2.2         139
6731  Flight6732  41968  ORD-ATL             16.8          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6730             0.791667               300       55500             5
6731             0.812500               300       49500            11

      Flight Year
6730         2014
6731         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6732  Flight6733  42165  ORD-EWR              2.0         161
6733  Flight6734  42187  ORD-DFW              3.2         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6732             0.708333             247.5     40837.5             6
6733             0.520833             220.0     36300.0             7

      Flight Year
6732         2015
6733         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6734  Flight6735  41920  ORD-MIA              0.5         157
6735  Flight6736  42161  ORD-DFW              2.3         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6734             0.562500               300       49500            10
6735             0.291667               220       36300             6

      Flight Year
6734         2014
6735         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6736  Flight6737  42043  ORD-LAX              3.3         141
6737  Flight6738  42161  ORD-EWR              2.6         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6736             0.416667             350.0     64750.0             2
6737             0.333333             247.5     45787.5             6

      Flight Year
6736         2015
6737         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6738  Flight6739  42240  ORD-SFO              2.9         158
6739  Flight6740  42318  ORD-DTW              1.6          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6738             0.708333             412.5     68062.5             8
6739             0.895833             115.0     21275.0            11

      Flight Year
6738         2015
6739         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6740  Flight6741  42331  ORD-DTW              4.8         142
6741  Flight6742  42149  ORD-LAX              3.4           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6740             0.770833             172.5     31912.5            11
6741             0.791667             350.0     64750.0             5

      Flight Year
6740         2015
6741         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6742  Flight6743  41703  ORD-EWR              0.6          29
6743  Flight6744  42365  ORD-SFO              2.3         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6742                 0.75               225       41625             3
6743                 0.50               525       86625            12

      Flight Year
6742         2014
6743         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6744  Flight6745  41909  ORD-ATL             10.7          76
6745  Flight6746  42053  ORD-MSP              3.5         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6744             0.750000               200       36200             9
6745             0.666667               115       18975             2

      Flight Year
6744         2014
6745         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6746  Flight6747  41971  ORD-JFK              3.5         189
6747  Flight6748  42252  ORD-SFO              2.2         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6746             0.708333               375       61875            11
6747             0.812500               375       61875             9

      Flight Year
6746         2014
6747         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6748  Flight6749  42015  ORD-MIA              1.9           1
6749  Flight6750  42157  ORD-DTW              2.0         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6748               0.7500             300.0     55500.0             1
6749               0.8125             126.5     20872.5             6

      Flight Year
6748         2015
6749         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6750  Flight6751  41817  ORD-SEA              2.4          16
6751  Flight6752  41971  ORD-BOS              4.5          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6750             0.750000               385       71225             6
6751             0.416667               450       81450            11

      Flight Year
6750         2014
6751         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6752  Flight6753  41686  ORD-CLT              2.4         173
6753  Flight6754  42124  ORD-EWR              1.8         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6752             0.708333               125       20625             2
6753             0.562500               225       37125             4

      Flight Year
6752         2014
6753         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6754  Flight6755  41754  ORD-CLT              2.8          91
6755  Flight6756  42090  ORD-DFW              1.9          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6754             0.625000               125       23125             4
6755             0.604167               200       36200             3

      Flight Year
6754         2014
6755         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6756  Flight6757  41700  ORD-ATL              7.1         150
6757  Flight6758  41818  ORD-SFO              1.1         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6756             0.708333             200.0     37000.0             3
6757             0.791667             412.5     76312.5             6

      Flight Year
6756         2014
6757         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6758  Flight6759  42211  ORD-CLT              2.0         196
6759  Flight6760  42099  ORD-IAH              2.1         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6758             0.312500             137.5     22687.5             7
6759             0.791667             200.0     37000.0             4

      Flight Year
6758         2015
6759         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6760  Flight6761  41856  ORD-PHL              1.5         106
6761  Flight6762  42007  ORD-PHL              2.3         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6760             0.708333             302.5     55962.5             8
6761             0.291667             275.0     45375.0             1

      Flight Year
6760         2014
6761         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6762  Flight6763  41967  ORD-DFW              3.6         193
6763  Flight6764  42193  ORD-CLT              1.2          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6762             0.791667             300.0     49500.0            11
6763             0.750000             137.5     25437.5             7

      Flight Year
6762         2014
6763         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6764  Flight6765  42314  ORD-DTW              1.3          15
6765  Flight6766  41853  ORD-EWR              3.2         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6764             0.750000             115.0     21275.0            11
6765             0.770833             247.5     45787.5             8

      Flight Year
6764         2015
6765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6766  Flight6767  42193  ORD-SFO              3.5         204
6767  Flight6768  41791  ORD-LAX              4.8          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6766             0.395833             412.5     68062.5             7
6767             0.770833             385.0     69685.0             6

      Flight Year
6766         2015
6767         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6768  Flight6769  42056  ORD-MSP              2.7          36
6769  Flight6770  41723  ORD-LGA              0.9          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6768             0.708333               115       18975             2
6769             0.791667               275       50875             3

      Flight Year
6768         2015
6769         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6770  Flight6771  42363  ORD-LAS              2.6         202
6771  Flight6772  41809  ORD-IAH              0.3         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6770             0.333333               385       63525            12
6771             0.750000               220       40700             6

      Flight Year
6770         2015
6771         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6772  Flight6773  42101  ORD-DFW              2.4         135
6773  Flight6774  42123  ORD-SEA              2.2          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6772             0.312500               200       37000             4
6773             0.833333               350       64750             4

      Flight Year
6772         2015
6773         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6774  Flight6775  41792  ORD-DTW              0.4          13
6775  Flight6776  41961  ORD-JFK              2.0         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6774             0.291667             126.5     23402.5             6
6775             0.833333             250.0     46250.0            11

      Flight Year
6774         2014
6775         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6776  Flight6777  42149  ORD-SFO              1.3         149
6777  Flight6778  41664  ORD-MIA              3.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6776             0.708333               375       69375             5
6777             0.625000               300       54300             1

      Flight Year
6776         2015
6777         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6778  Flight6779  41661  ORD-PHL              1.6          92
6779  Flight6780  42214  ORD-PHX              1.1         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6778             0.750000               275       50875             1
6779             0.708333               275       45375             7

      Flight Year
6778         2014
6779         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6780  Flight6781  42218  ORD-EWR              2.2         158
6781  Flight6782  42208  ORD-JFK              2.1         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6780             0.375000             247.5     40837.5             8
6781             0.791667             275.0     45375.0             7

      Flight Year
6780         2015
6781         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6782  Flight6783  41987  ORD-JFK              0.6         114
6783  Flight6784  41700  ORD-LAS              1.4          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6782             0.291667               250       46250            12
6783             0.833333               275       50875             3

      Flight Year
6782         2014
6783         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6784  Flight6785  41973  ORD-CLT              5.3          72
6785  Flight6786  42338  ORD-JFK              2.1         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6784             0.708333             187.5     33937.5            11
6785             0.729167             250.0     41250.0            11

      Flight Year
6784         2014
6785         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6786  Flight6787  41878  ORD-CLT              2.8         171
6787  Flight6788  42086  ORD-SFO              1.5          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6786             0.708333             137.5     22687.5             8
6787             0.583333             375.0     67875.0             3

      Flight Year
6786         2014
6787         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6788  Flight6789  41797  ORD-SEA              2.4         152
6789  Flight6790  41852  ORD-LAX              4.6          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6788             0.312500               385       63525             6
6789             0.854167               385       69685             8

      Flight Year
6788         2014
6789         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6790  Flight6791  41811  ORD-PHL              1.9          18
6791  Flight6792  42305  ORD-PHL              3.6         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6790             0.833333             302.5     55962.5             6
6791             0.708333             275.0     50875.0            10

      Flight Year
6790         2014
6791         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6792  Flight6793  41985  ORD-DFW              1.9         165
6793  Flight6794  41850  ORD-PHX              1.7          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6792             0.791667               200       33000            12
6793             0.708333               275       50875             7

      Flight Year
6792         2014
6793         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6794  Flight6795  41871  ORD-LAS              2.2          19
6795  Flight6796  41652  ORD-DTW              1.1         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6794             0.708333             302.5     55962.5             8
6795             0.291667             115.0     21275.0             1

      Flight Year
6794         2014
6795         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6796  Flight6797  42168  ORD-ATL             12.2         114
6797  Flight6798  42154  ORD-LAX              4.8           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6796             0.500000               220       40700             6
6797             0.791667               350       64750             5

      Flight Year
6796         2015
6797         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6798  Flight6799  42152  ORD-CLT              2.2         202
6799  Flight6800  42206  ORD-MIA              1.5         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6798             0.750000               125       20625             5
6799             0.833333               330       54450             7

      Flight Year
6798         2015
6799         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6800  Flight6801  42115  ORD-DFW              1.2          30
6801  Flight6802  41875  ORD-LAX              7.4          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6800             0.333333               200       37000             4
6801             0.791667               385       69685             8

      Flight Year
6800         2015
6801         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6802  Flight6803  41881  ORD-DFW              2.2         118
6803  Flight6804  42016  ORD-DTW              3.0          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6802             0.291667               220       40700             8
6803             0.708333               115       20815             1

      Flight Year
6802         2014
6803         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6804  Flight6805  42298  ORD-MSP              2.2         117
6805  Flight6806  42149  ORD-DFW              2.0         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6804             0.770833               115       21275            10
6805             0.708333               200       37000             5

      Flight Year
6804         2015
6805         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6806  Flight6807  41890  ORD-JFK              3.2          52
6807  Flight6808  42025  ORD-MSP              2.3          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6806             0.791667               250       41250             9
6807             0.791667               115       18975             1

      Flight Year
6806         2014
6807         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6808  Flight6809  41771  ORD-ATL              9.2          21
6809  Flight6810  41756  ORD-CLT              1.9         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6808             0.833333               200       37000             5
6809             0.791667               125       23125             4

      Flight Year
6808         2014
6809         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6810  Flight6811  42108  ORD-JFK              1.2           7
6811  Flight6812  41806  ORD-MIA              1.8          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6810             0.687500               250       46250             4
6811             0.791667               330       54450             6

      Flight Year
6810         2015
6811         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6812  Flight6813  42175  ORD-IAH              2.3         100
6813  Flight6814  41678  ORD-LAS              2.8          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6812             0.791667               220       40700             6
6813             0.854167               275       50875             2

      Flight Year
6812         2015
6813         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6814  Flight6815  41732  ORD-IAH              1.9           1
6815  Flight6816  41842  ORD-LAS              1.9          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6814             0.708333             200.0     37000.0             4
6815             0.770833             302.5     49912.5             7

      Flight Year
6814         2014
6815         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6816  Flight6817  41895  ORD-JFK              2.1           9
6817  Flight6818  42229  ORD-ATL              9.9         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6816             0.291667               250       46250             9
6817             0.291667               220       40700             8

      Flight Year
6816         2014
6817         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6818  Flight6819  42365  ORD-LAS              3.5         144
6819  Flight6820  42000  ORD-LAS              3.0         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6818             0.750000               385       71225            12
6819             0.458333               385       71225            12

      Flight Year
6818         2015
6819         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6820  Flight6821  41687  ORD-SFO              2.3         122
6821  Flight6822  42280  ORD-EWR              2.7          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6820             0.625000               375       69375             2
6821             0.291667               225       41625            10

      Flight Year
6820         2014
6821         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6822  Flight6823  42028  ORD-DFW              1.1          56
6823  Flight6824  42078  ORD-FLL              2.2         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6822             0.791667               200       33000             1
6823             0.750000               300       49500             3

      Flight Year
6822         2015
6823         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6824  Flight6825  42095  ORD-LAX              1.9          12
6825  Flight6826  41970  ORD-LAX              8.5         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6824             0.708333               350       64750             4
6825             0.708333               525       97125            11

      Flight Year
6824         2015
6825         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6826  Flight6827  41710  ORD-EWR              2.4         184
6827  Flight6828  41975  ORD-EWR              1.5          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6826                0.625               225       37125             3
6827                0.750               225       41625            12

      Flight Year
6826         2014
6827         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6828  Flight6829  42086  ORD-ATL             11.4         114
6829  Flight6830  41743  ORD-LGA              1.2         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6828             0.708333               200       37000             3
6829             0.541667               275       45375             4

      Flight Year
6828         2015
6829         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6830  Flight6831  41756  ORD-LAX              3.3         174
6831  Flight6832  41807  ORD-PHL              1.8          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6830             0.375000             350.0     57750.0             4
6831             0.333333             302.5     49912.5             6

      Flight Year
6830         2014
6831         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6832  Flight6833  42342  ORD-PHX              2.6         162
6833  Flight6834  41649  ORD-BOS              2.0          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6832             0.708333               250       41250            12
6833             0.291667               300       49500             1

      Flight Year
6832         2015
6833         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6834  Flight6835  42361  ORD-MSP              2.2         130
6835  Flight6836  42168  ORD-FLL              2.3         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6834             0.354167               161       29785            12
6835             0.583333               330       54450             6

      Flight Year
6834         2015
6835         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6836  Flight6837  42364  ORD-JFK              2.7          65
6837  Flight6838  42285  ORD-DFW              1.3          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6836             0.312500               350       63350            12
6837             0.333333               200       33000            10

      Flight Year
6836         2015
6837         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6838  Flight6839  41839  ORD-MIA              2.7          15
6839  Flight6840  42152  ORD-CLT              1.9         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6838               0.4375               330       61050             7
6839               0.3125               125       20625             5

      Flight Year
6838         2014
6839         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6840  Flight6841  41866  ORD-ATL             10.0         134
6841  Flight6842  41847  ORD-PHL              1.1          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6840             0.375000             220.0     40700.0             8
6841             0.791667             302.5     49912.5             7

      Flight Year
6840         2014
6841         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6842  Flight6843  42359  ORD-EWR              4.7         204
6843  Flight6844  42016  ORD-SFO              1.1          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6842             0.750000               315       51975            12
6843             0.791667               375       67875             1

      Flight Year
6842         2015
6843         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6844  Flight6845  42118  ORD-BOS              2.8          94
6845  Flight6846  41808  ORD-MCO              2.0         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6844             0.479167               300       55500             4
6845             0.583333               275       45375             6

      Flight Year
6844         2015
6845         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6846  Flight6847  41806  ORD-DFW              2.9         167
6847  Flight6848  41708  ORD-SEA              1.8         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6846               0.7500               220       36300             6
6847               0.4375               350       64750             3

      Flight Year
6846         2014
6847         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6848  Flight6849  42201  ORD-SEA              2.7         171
6849  Flight6850  41684  ORD-BOS              1.8         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6848             0.729167               385       63525             7
6849             0.750000               300       55500             2

      Flight Year
6848         2015
6849         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6850  Flight6851  41652  ORD-DFW              1.8         116
6851  Flight6852  41835  ORD-CLT              3.3          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6850             0.562500             200.0     37000.0             1
6851             0.291667             137.5     24887.5             7

      Flight Year
6850         2014
6851         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6852  Flight6853  42064  ORD-JFK              2.4         103
6853  Flight6854  41972  ORD-CLT              5.4          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6852             0.791667             250.0     46250.0             3
6853             0.500000             187.5     34687.5            11

      Flight Year
6852         2015
6853         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6854  Flight6855  42133  ORD-LAS              1.3          85
6855  Flight6856  41664  ORD-JFK              2.8         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6854             0.791667               275       49775             5
6855             0.312500               250       41250             1

      Flight Year
6854         2015
6855         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6856  Flight6857  41963  ORD-SFO              1.9          53
6857  Flight6858  41791  ORD-SFO              0.8         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6856             0.583333             375.0     61875.0            11
6857             0.416667             412.5     68062.5             6

      Flight Year
6856         2014
6857         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6858  Flight6859  42221  ORD-PHX              2.9         151
6859  Flight6860  41828  ORD-ATL             11.5         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6858             0.291667               275       50875             8
6859             0.708333               220       36300             7

      Flight Year
6858         2015
6859         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6860  Flight6861  41887  ORD-ATL              9.1         117
6861  Flight6862  41926  ORD-SFO              1.4          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6860             0.833333               200       37000             9
6861             0.645833               375       67875            10

      Flight Year
6860         2014
6861         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6862  Flight6863  41973  ORD-CLT              5.4         108
6863  Flight6864  42158  ORD-LAS              1.6         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6862             0.770833             187.5     34687.5            11
6863             0.708333             302.5     49912.5             6

      Flight Year
6862         2014
6863         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6864  Flight6865  42305  ORD-DEN              1.1         116
6865  Flight6866  42119  ORD-PHX              1.1          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6864             0.500000               300       55500            10
6865             0.354167               250       46250             4

      Flight Year
6864         2015
6865         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6866  Flight6867  41959  ORD-DEN              1.8          76
6867  Flight6868  41809  ORD-DTW              2.9         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6866             0.708333             300.0     54300.0            11
6867             0.541667             126.5     20872.5             6

      Flight Year
6866         2014
6867         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6868  Flight6869  42006  ORD-MCO              3.1          34
6869  Flight6870  42164  ORD-LAX              4.0          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6868             0.708333               250       46250             1
6869             0.291667               385       69685             6

      Flight Year
6868         2015
6869         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6870  Flight6871  41967  ORD-DFW              5.8          33
6871  Flight6872  41789  ORD-MCO              2.4           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6870             0.437500               300       55500            11
6871             0.291667               250       46250             5

      Flight Year
6870         2014
6871         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6872  Flight6873  41872  ORD-SEA              1.5         139
6873  Flight6874  41947  ORD-LAX              3.6         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6872             0.770833               385       71225             8
6873             0.625000               350       57750            11

      Flight Year
6872         2014
6873         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6874  Flight6875  41968  ORD-LGA              4.3         178
6875  Flight6876  42168  ORD-BOS              0.7         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6874             0.770833             412.5     68062.5            11
6875             0.291667             330.0     54450.0             6

      Flight Year
6874         2014
6875         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6876  Flight6877  42334  ORD-DFW              5.2          25
6877  Flight6878  42284  ORD-ATL             10.9          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6876             0.291667               300       55500            11
6877             0.354167               200       33000            10

      Flight Year
6876         2015
6877         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6878  Flight6879  41731  ORD-SEA              1.7          35
6879  Flight6880  41854  ORD-CLT              2.0         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6878             0.791667             350.0     64750.0             4
6879             0.791667             137.5     22687.5             8

      Flight Year
6878         2014
6879         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6880  Flight6881  41827  ORD-LAX              5.1          78
6881  Flight6882  41922  ORD-LAS              2.0           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6880             0.875000               385       69685             7
6881             0.458333               275       50875            10

      Flight Year
6880         2014
6881         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6882  Flight6883  41796  ORD-MIA              2.5         141
6883  Flight6884  42257  ORD-EWR              2.1         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6882             0.875000               330       61050             6
6883             0.291667               225       41625             9

      Flight Year
6882         2014
6883         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6884  Flight6885  42049  ORD-LAX              4.5         105
6885  Flight6886  41642  ORD-SFO              1.8          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6884             0.500000               350       64750             2
6885             0.541667               375       67875             1

      Flight Year
6884         2015
6885         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6886  Flight6887  42319  ORD-MIA              2.9         165
6887  Flight6888  42141  ORD-PHX              1.6          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6886             0.833333               300       49500            11
6887             0.791667               250       41250             5

      Flight Year
6886         2015
6887         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6888  Flight6889  41879  ORD-LAX              4.0          72
6889  Flight6890  42364  ORD-SFO              4.5          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6888             0.291667               385       69685             8
6889             0.708333               525       97125            12

      Flight Year
6888         2014
6889         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6890  Flight6891  41845  ORD-DTW              1.7         163
6891  Flight6892  42104  ORD-PHL              2.6         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6890             0.625000             126.5     20872.5             7
6891             0.708333             275.0     50875.0             4

      Flight Year
6890         2014
6891         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6892  Flight6893  42028  ORD-SFO              2.7          37
6893  Flight6894  42065  ORD-LGA              1.3          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6892             0.708333               375       61875             1
6893             0.708333               275       45375             3

      Flight Year
6892         2015
6893         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6894  Flight6895  42234  ORD-LGA              3.4          25
6895  Flight6896  41950  ORD-MIA              1.8         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6894             0.333333             302.5     55962.5             8
6895             0.770833             300.0     55500.0            11

      Flight Year
6894         2015
6895         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6896  Flight6897  42058  ORD-JFK              1.9          15
6897  Flight6898  41827  ORD-LAS              2.5           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6896             0.416667             250.0     46250.0             2
6897             0.375000             302.5     55962.5             7

      Flight Year
6896         2015
6897         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6898  Flight6899  41701  ORD-ATL              7.8          78
6899  Flight6900  41738  ORD-DEN              1.8          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6898             0.750000               200       36200             3
6899             0.333333               300       49500             4

      Flight Year
6898         2014
6899         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6900  Flight6901  42300  ORD-JFK              2.5         134
6901  Flight6902  41740  ORD-MIA              2.0          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6900             0.645833               250       46250            10
6901             0.708333               300       49500             4

      Flight Year
6900         2015
6901         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6902  Flight6903  42111  ORD-SFO              2.5         166
6903  Flight6904  41902  ORD-DEN              4.3          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6902             0.333333               375       61875             4
6903             0.291667               300       54300             9

      Flight Year
6902         2015
6903         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6904  Flight6905  42347  ORD-PHL              2.5          10
6905  Flight6906  41726  ORD-LAS              2.8         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6904             0.625000               275       50875            12
6905             0.291667               275       50875             3

      Flight Year
6904         2015
6905         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6906  Flight6907  42170  ORD-LAX              4.6         160
6907  Flight6908  41969  ORD-LAX             10.2          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6906             0.291667               385       63525             6
6907             0.333333               525       95025            11

      Flight Year
6906         2015
6907         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6908  Flight6909  41677  ORD-DEN              2.9         107
6909  Flight6910  41761  ORD-CLT              2.2          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6908             0.291667               300       55500             2
6909             0.312500               125       20625             5

      Flight Year
6908         2014
6909         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6910  Flight6911  41927  ORD-DEN              1.2         188
6911  Flight6912  41842  ORD-JFK              2.7           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6910             0.833333               300       49500            10
6911             0.750000               275       50875             7

      Flight Year
6910         2014
6911         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6912  Flight6913  41739  ORD-LGA              0.9         174
6913  Flight6914  42182  ORD-LAS              1.3         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6912             0.666667             275.0     45375.0             4
6913             0.812500             302.5     55962.5             6

      Flight Year
6912         2014
6913         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6914  Flight6915  41810  ORD-PHX              1.8         185
6915  Flight6916  41671  ORD-CLT              2.5         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6914             0.791667               275       45375             6
6915             0.708333               125       20625             2

      Flight Year
6914         2014
6915         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6916  Flight6917  42160  ORD-MIA              1.4          77
6917  Flight6918  42359  ORD-ATL             14.8         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6916             0.416667               330       59730             6
6917             0.854167               280       51800            12

      Flight Year
6916         2015
6917         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6918  Flight6919  42139  ORD-JFK              1.1          81
6919  Flight6920  41662  ORD-MIA              1.5         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6918             0.312500               250       45250             5
6919             0.291667               300       49500             1

      Flight Year
6918         2015
6919         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6920  Flight6921  42060  ORD-PHX              1.7         172
6921  Flight6922  42305  ORD-DEN              3.3          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6920             0.791667               250       41250             2
6921             0.770833               300       49500            10

      Flight Year
6920         2015
6921         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6922  Flight6923  42219  ORD-SFO              1.9          53
6923  Flight6924  42217  ORD-CLT              2.2         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6922             0.895833             412.5     68062.5             8
6923             0.854167             137.5     25437.5             8

      Flight Year
6922         2015
6923         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6924  Flight6925  41995  ORD-LGA              2.9         166
6925  Flight6926  42267  ORD-EWR              1.6         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6924             0.729167               385       63525            12
6925             0.333333               225       37125             9

      Flight Year
6924         2014
6925         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6926  Flight6927  41999  ORD-LGA              3.2         102
6927  Flight6928  42186  ORD-MSP              1.8          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6926             0.750000             385.0     71225.0            12
6927             0.770833             126.5     20872.5             7

      Flight Year
6926         2014
6927         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6928  Flight6929  41943  ORD-IAH              2.1         103
6929  Flight6930  42001  ORD-DTW              3.3         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6928             0.416667               200       37000            10
6929             0.833333               161       26565            12

      Flight Year
6928         2014
6929         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6930  Flight6931  41833  ORD-PHX              1.9         142
6931  Flight6932  42177  ORD-DFW              2.0         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6930               0.5625               275       50875             7
6931               0.7500               220       40700             6

      Flight Year
6930         2014
6931         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6932  Flight6933  42009  ORD-BOS              2.4          68
6933  Flight6934  42041  ORD-DFW              2.6          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6932             0.333333               300       54300             1
6933             0.458333               200       37000             2

      Flight Year
6932         2015
6933         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6934  Flight6935  42109  ORD-PHX              1.2          11
6935  Flight6936  41970  ORD-LGA              5.8         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6934             0.500000             250.0     46250.0             4
6935             0.708333             412.5     68062.5            11

      Flight Year
6934         2015
6935         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6936  Flight6937  42277  ORD-MCO              1.7          43
6937  Flight6938  41853  ORD-ATL              9.2         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6936             0.812500               250       41250             9
6937             0.333333               220       36300             8

      Flight Year
6936         2015
6937         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6938  Flight6939  42192  ORD-DFW              2.1         129
6939  Flight6940  41971  ORD-LAS              4.2          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6938             0.375000             220.0     40700.0             7
6939             0.291667             412.5     68062.5            11

      Flight Year
6938         2015
6939         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6940  Flight6941  41644  ORD-MIA              3.2         190
6941  Flight6942  42099  ORD-LAX              3.7          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6940             0.291667               300       49500             1
6941             0.416667               350       64750             4

      Flight Year
6940         2014
6941         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6942  Flight6943  42031  ORD-MIA              2.1         103
6943  Flight6944  42264  ORD-CLT              2.0          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6942             0.708333               300       55500             1
6943             0.791667               125       23125             9

      Flight Year
6942         2015
6943         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6944  Flight6945  41971  ORD-DTW              6.1         150
6945  Flight6946  41746  ORD-IAH              0.6         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6944             0.750000             172.5     31912.5            11
6945             0.416667             200.0     33000.0             4

      Flight Year
6944         2014
6945         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6946  Flight6947  41888  ORD-DTW              3.2          33
6947  Flight6948  42162  ORD-MSP              1.4          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6946             0.541667             115.0     21275.0             9
6947             0.562500             126.5     23402.5             6

      Flight Year
6946         2014
6947         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6948  Flight6949  41691  ORD-PHL              2.6          52
6949  Flight6950  41889  ORD-LAX              4.9         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6948             0.791667               275       45375             2
6949             0.625000               350       57750             9

      Flight Year
6948         2014
6949         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6950  Flight6951  42335  ORD-DFW              6.2          78
6951  Flight6952  42157  ORD-DFW              1.5         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6950             0.375000               300       54300            11
6951             0.291667               220       36300             6

      Flight Year
6950         2015
6951         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6952  Flight6953  41829  ORD-MCO              0.9         101
6953  Flight6954  42103  ORD-MIA              2.6         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6952             0.541667               275       50875             7
6953             0.354167               300       49500             4

      Flight Year
6952         2014
6953         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6954  Flight6955  42148  ORD-ATL              7.9         145
6955  Flight6956  41879  ORD-EWR              1.2         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6954             0.291667             200.0     37000.0             5
6955             0.333333             247.5     40837.5             8

      Flight Year
6954         2015
6955         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6956  Flight6957  42014  ORD-SFO              2.9          73
6957  Flight6958  41732  ORD-LAX              4.6         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6956             0.854167               375       67875             1
6957             0.770833               350       57750             4

      Flight Year
6956         2015
6957         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6958  Flight6959  41796  ORD-JFK              2.4         173
6959  Flight6960  42033  ORD-SEA              2.1         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6958             0.500000               275       45375             6
6959             0.291667               350       57750             1

      Flight Year
6958         2014
6959         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6960  Flight6961  42347  ORD-ATL              9.6         150
6961  Flight6962  41935  ORD-LAS              1.8          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6960             0.666667               200       37000            12
6961             0.333333               275       50875            10

      Flight Year
6960         2015
6961         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6962  Flight6963  42342  ORD-DFW              0.7         103
6963  Flight6964  42144  ORD-MSP              1.6         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6962             0.395833               200       37000            12
6963             0.729167               115       18975             5

      Flight Year
6962         2015
6963         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6964  Flight6965  41734  ORD-IAH              3.4           3
6965  Flight6966  41877  ORD-DEN              2.4          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6964             0.666667               200       37000             4
6965             0.833333               330       59730             8

      Flight Year
6964         2014
6965         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6966  Flight6967  42001  ORD-BOS              2.4         109
6967  Flight6968  42101  ORD-SFO              3.2         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6966             0.500000               420       77700            12
6967             0.416667               375       61875             4

      Flight Year
6966         2014
6967         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6968  Flight6969  42076  ORD-LAX              3.9         187
6969  Flight6970  41868  ORD-JFK              2.9         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6968             0.458333               350       57750             3
6969             0.708333               275       45375             8

      Flight Year
6968         2015
6969         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6970  Flight6971  42187  ORD-LAX              5.0         139
6971  Flight6972  41902  ORD-LAX              5.2         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6970             0.291667               385       71225             7
6971             0.833333               350       64750             9

      Flight Year
6970         2015
6971         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6972  Flight6973  41837  ORD-JFK              2.8          65
6973  Flight6974  42024  ORD-MCO              1.8         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6972             0.791667               275       49775             7
6973             0.791667               250       46250             1

      Flight Year
6972         2014
6973         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6974  Flight6975  42334  ORD-EWR              4.8          46
6975  Flight6976  42050  ORD-CLT              3.9         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6974             0.854167             337.5     55687.5            11
6975             0.708333             125.0     23125.0             2

      Flight Year
6974         2015
6975         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6976  Flight6977  42093  ORD-MIA              2.2         123
6977  Flight6978  42001  ORD-DEN              3.9          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6976             0.791667               300       55500             3
6977             0.291667               420       77700            12

      Flight Year
6976         2015
6977         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6978  Flight6979  42253  ORD-MCO              2.6         199
6979  Flight6980  42022  ORD-ATL             10.3          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6978             0.541667               250       41250             9
6979             0.312500               200       37000             1

      Flight Year
6978         2015
6979         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6980  Flight6981  42016  ORD-JFK              1.5          10
6981  Flight6982  41799  ORD-BOS              3.6         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6980             0.791667               250       46250             1
6981             0.500000               330       54450             6

      Flight Year
6980         2015
6981         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6982  Flight6983  41963  ORD-ATL              8.4          64
6983  Flight6984  42349  ORD-IAH              2.5          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6982             0.812500               200       36200            11
6983             0.708333               200       36200            12

      Flight Year
6982         2014
6983         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6984  Flight6985  42319  ORD-CLT              2.4         167
6985  Flight6986  42131  ORD-IAH              2.3          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6984             0.812500               125       20625            11
6985             0.666667               200       37000             5

      Flight Year
6984         2015
6985         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6986  Flight6987  41716  ORD-LAS              2.1         177
6987  Flight6988  41816  ORD-DFW              1.5          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6986             0.333333               275       45375             3
6987             0.395833               220       39820             6

      Flight Year
6986         2014
6987         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6988  Flight6989  41822  ORD-MSP              3.6         192
6989  Flight6990  42314  ORD-EWR              2.0         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6988             0.333333             126.5     20872.5             7
6989             0.312500             225.0     37125.0            11

      Flight Year
6988         2014
6989         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6990  Flight6991  41941  ORD-SFO              2.4          43
6991  Flight6992  42199  ORD-SEA              1.0         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6990             0.375000               375       61875            10
6991             0.791667               385       63525             7

      Flight Year
6990         2014
6991         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6992  Flight6993  42076  ORD-LAX              4.2         130
6993  Flight6994  42245  ORD-ATL              5.6         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6992             0.479167               350       64750             3
6993             0.875000               220       40700             8

      Flight Year
6992         2015
6993         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6994  Flight6995  41843  ORD-DFW              1.5         105
6995  Flight6996  42230  ORD-JFK              1.7          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6994             0.666667               220       40700             7
6995             0.312500               275       45375             8

      Flight Year
6994         2014
6995         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6996  Flight6997  42210  ORD-ATL             10.8          59
6997  Flight6998  42035  ORD-LAS              1.2          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6996             0.666667               220       36300             7
6997             0.750000               275       50875             1

      Flight Year
6996         2015
6997         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
6998  Flight6999  42286  ORD-EWR              1.1          50
6999  Flight7000  41661  ORD-PHL              3.0         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
6998             0.354167               225       37125            10
6999             0.520833               275       50875             1

      Flight Year
6998         2015
6999         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7000  Flight7001  41822  ORD-PHX              2.2         189
7001  Flight7002  41952  ORD-CLT              2.0          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7000             0.750000               275       45375             7
7001             0.708333               125       22625            11

      Flight Year
7000         2014
7001         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7002  Flight7003  41726  ORD-BWI              2.0          69
7003  Flight7004  42311  ORD-LGA              1.6         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7002             0.791667               240       43440             3
7003             0.708333               275       45375            11

      Flight Year
7002         2014
7003         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7004  Flight7005  42307  ORD-SFO              2.7          40
7005  Flight7006  42192  ORD-DEN              2.1          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7004             0.416667               375       61875            10
7005             0.708333               330       61050             7

      Flight Year
7004         2015
7005         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7006  Flight7007  42003  ORD-JFK              1.8           8
7007  Flight7008  41882  ORD-LAX              3.5         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7006             0.333333               250       46250            12
7007             0.291667               385       63525             8

      Flight Year
7006         2014
7007         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7008  Flight7009  41884  ORD-CLT              2.5          34
7009  Flight7010  41982  ORD-BOS              1.7         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7008             0.291667               125       23125             9
7009             0.562500               300       49500            12

      Flight Year
7008         2014
7009         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7010  Flight7011  41848  ORD-CLT              2.5         155
7011  Flight7012  41820  ORD-EWR              2.1         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7010             0.708333             137.5     22687.5             7
7011             0.708333             247.5     40837.5             6

      Flight Year
7010         2014
7011         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7012  Flight7013  42142  ORD-SEA              2.9          96
7013  Flight7014  41979  ORD-LAS              3.0           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7012             0.333333               350       64750             5
7013             0.458333               275       50875            12

      Flight Year
7012         2015
7013         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7014  Flight7015  42336  ORD-PHX              4.9          98
7015  Flight7016  42240  ORD-DFW              1.4         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7014             0.750000               375       69375            11
7015             0.833333               220       40700             8

      Flight Year
7014         2015
7015         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7016  Flight7017  42318  ORD-ATL              7.4         107
7017  Flight7018  42337  ORD-SEA              5.0         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7016             0.854167               200       37000            11
7017             0.729167               525       97125            11

      Flight Year
7016         2015
7017         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7018  Flight7019  41885  ORD-ATL              7.9          78
7019  Flight7020  42262  ORD-ATL              9.6         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7018             0.625000               200       36200             9
7019             0.791667               200       33000             9

      Flight Year
7018         2014
7019         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7020  Flight7021  41649  ORD-LAS              1.2          54
7021  Flight7022  41831  ORD-LAX              5.3          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7020             0.291667               275       45375             1
7021             0.708333               385       69685             7

      Flight Year
7020         2014
7021         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7022  Flight7023  42118  ORD-PHX              2.7          34
7023  Flight7024  41661  ORD-JFK              2.0          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7022             0.833333               250       46250             4
7023             0.770833               250       41250             1

      Flight Year
7022         2015
7023         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7024  Flight7025  42100  ORD-EWR              2.8         113
7025  Flight7026  41966  ORD-FLL              1.9         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7024             0.541667               225       41625             4
7025             0.791667               300       55500            11

      Flight Year
7024         2015
7025         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7026  Flight7027  42148  ORD-PHX              2.1          65
7027  Flight7028  41648  ORD-SEA              1.6          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7026             0.708333               250       45250             5
7027             0.500000               350       63350             1

      Flight Year
7026         2015
7027         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7028  Flight7029  42313  ORD-LAS              1.4          76
7029  Flight7030  41844  ORD-DEN              1.0          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7028             0.291667               275       49775            11
7029             0.333333               330       54450             7

      Flight Year
7028         2015
7029         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7030  Flight7031  41682  ORD-IAD              1.6          88
7031  Flight7032  41971  ORD-FLL              5.4         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7030             0.333333               300       54300             2
7031             0.708333               450       83250            11

      Flight Year
7030         2014
7031         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7032  Flight7033  42085  ORD-SEA              2.0          25
7033  Flight7034  41941  ORD-JFK              2.2         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7032             0.291667               350       64750             3
7033             0.750000               250       46250            10

      Flight Year
7032         2015
7033         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7034  Flight7035  41926  ORD-PHX              1.2          16
7035  Flight7036  41766  ORD-MSP              2.3          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7034             0.791667               250       46250            10
7035             0.833333               115       21275             5

      Flight Year
7034         2014
7035         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7036  Flight7037  41706  ORD-BWI              1.3          59
7037  Flight7038  41826  ORD-DFW              1.8         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7036             0.625000               240       39600             3
7037             0.791667               220       36300             7

      Flight Year
7036         2014
7037         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7038  Flight7039  41647  ORD-EWR              1.5           1
7039  Flight7040  41854  ORD-CLT              2.4         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7038             0.291667             225.0     41625.0             1
7039             0.291667             137.5     22687.5             8

      Flight Year
7038         2014
7039         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7040  Flight7041  42244  ORD-LAX              5.1         132
7041  Flight7042  42171  ORD-JFK              1.9         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7040             0.791667               385       71225             8
7041             0.375000               275       45375             6

      Flight Year
7040         2015
7041         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7042  Flight7043  42292  ORD-LGA              2.0         194
7043  Flight7044  42340  ORD-CLT              2.1         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7042             0.791667               275       45375            10
7043             0.500000               125       23125            12

      Flight Year
7042         2015
7043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7044  Flight7045  42145  ORD-MIA              2.2         192
7045  Flight7046  42078  ORD-DEN              1.3         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7044             0.375000               300       49500             5
7045             0.708333               300       55500             3

      Flight Year
7044         2015
7045         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7046  Flight7047  42197  ORD-LAS              2.8         124
7047  Flight7048  41918  ORD-BOS              1.2         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7046               0.3125             302.5     55962.5             7
7047               0.8125             300.0     55500.0            10

      Flight Year
7046         2015
7047         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7048  Flight7049  42022  ORD-LAX              2.4          89
7049  Flight7050  42032  ORD-DFW              1.7          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7048             0.791667               350       63350             1
7049             0.562500               200       37000             1

      Flight Year
7048         2015
7049         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7050  Flight7051  42067  ORD-PHL              2.7          27
7051  Flight7052  42242  ORD-SEA              3.1         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7050             0.708333               275       50875             3
7051             0.833333               385       63525             8

      Flight Year
7050         2015
7051         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7052  Flight7053  42107  ORD-SFO              0.4         158
7053  Flight7054  41820  ORD-MCO              1.9          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7052             0.604167               375       61875             4
7053             0.750000               275       50875             6

      Flight Year
7052         2015
7053         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7054  Flight7055  42365  ORD-MIA              6.6          78
7055  Flight7056  41913  ORD-SFO              1.9          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7054             0.354167               420       76020            12
7055             0.291667               375       67875            10

      Flight Year
7054         2015
7055         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7056  Flight7057  42183  ORD-MSP              1.7          79
7057  Flight7058  42066  ORD-LAX              3.1          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7056             0.729167             126.5     22896.5             6
7057             0.541667             350.0     64750.0             3

      Flight Year
7056         2015
7057         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7058  Flight7059  42165  ORD-JFK              2.7         204
7059  Flight7060  41688  ORD-PHL              2.0           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7058             0.833333               275       45375             6
7059             0.791667               275       50875             2

      Flight Year
7058         2015
7059         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7060  Flight7061  42155  ORD-JFK              2.0         199
7061  Flight7062  42356  ORD-IAH              1.9         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7060             0.562500               250       41250             5
7061             0.333333               200       37000            12

      Flight Year
7060         2015
7061         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7062  Flight7063  41874  ORD-SFO              1.1          29
7063  Flight7064  41787  ORD-MIA              2.0         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7062             0.750000             412.5     76312.5             8
7063             0.333333             300.0     55500.0             5

      Flight Year
7062         2014
7063         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7064  Flight7065  42156  ORD-DEN              2.4          43
7065  Flight7066  42319  ORD-ATL              9.1         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7064             0.312500               330       54450             6
7065             0.708333               200       33000            11

      Flight Year
7064         2015
7065         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7066  Flight7067  41802  ORD-SFO              2.1         124
7067  Flight7068  42272  ORD-JFK              2.0         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7066             0.895833             412.5     76312.5             6
7067             0.833333             250.0     41250.0             9

      Flight Year
7066         2014
7067         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7068  Flight7069  41849  ORD-CLT                3         204
7069  Flight7070  41759  ORD-ATL                7          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7068             0.791667             137.5     22687.5             7
7069             0.458333             200.0     36200.0             4

      Flight Year
7068         2014
7069         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7070  Flight7071  42014  ORD-IAH              1.7          51
7071  Flight7072  41709  ORD-MSP              0.7          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7070             0.666667               200       33000             1
7071             0.708333               115       20815             3

      Flight Year
7070         2015
7071         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7072  Flight7073  42262  ORD-MSP              3.0          24
7073  Flight7074  41688  ORD-SEA              1.7         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7072             0.770833               115       21275             9
7073             0.791667               350       57750             2

      Flight Year
7072         2015
7073         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7074  Flight7075  41996  ORD-ATL             13.0         179
7075  Flight7076  41973  ORD-ATL             17.5         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7074             0.479167               280       46200            12
7075             0.541667               300       49500            11

      Flight Year
7074         2014
7075         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7076  Flight7077  42005  ORD-LAX              2.9          36
7077  Flight7078  41875  ORD-LAS              2.4         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7076             0.854167             350.0     57750.0             1
7077             0.583333             302.5     55962.5             8

      Flight Year
7076         2015
7077         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7078  Flight7079  42060  ORD-MCO              2.4         149
7079  Flight7080  41903  ORD-IAH              1.9         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7078             0.854167               250       46250             2
7079             0.416667               200       37000             9

      Flight Year
7078         2015
7079         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7080  Flight7081  41678  ORD-CLT              0.9          74
7081  Flight7082  41796  ORD-LAX              4.8          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7080             0.291667               125       22625             2
7081             0.291667               385       63525             6

      Flight Year
7080         2014
7081         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7082  Flight7083  42029  ORD-DTW              2.6         117
7083  Flight7084  41911  ORD-LAX              5.4         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7082             0.354167               115       21275             1
7083             0.416667               350       57750             9

      Flight Year
7082         2015
7083         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7084  Flight7085  41952  ORD-DTW              1.5         172
7085  Flight7086  42158  ORD-LAX              4.8          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7084             0.354167               115       18975            11
7085             0.750000               385       71225             6

      Flight Year
7084         2014
7085         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7086  Flight7087  42017  ORD-IAH              1.3          63
7087  Flight7088  41970  ORD-PHX              6.2         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7086             0.750000               200       36200             1
7087             0.729167               375       69375            11

      Flight Year
7086         2015
7087         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7088  Flight7089  42346  ORD-PHX              0.8          54
7089  Flight7090  42006  ORD-PHL              1.5           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7088             0.791667               250       41250            12
7089             0.833333               275       50875             1

      Flight Year
7088         2015
7089         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7090  Flight7091  42268  ORD-ATL             10.8         197
7091  Flight7092  42041  ORD-PHX              1.6          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7090             0.291667               200       33000             9
7091             0.333333               250       46250             2

      Flight Year
7090         2015
7091         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7092  Flight7093  42304  ORD-DFW              2.0          33
7093  Flight7094  41964  ORD-SFO              0.7         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7092             0.791667               200       37000            10
7093             0.500000               375       69375            11

      Flight Year
7092         2015
7093         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7094  Flight7095  42242  ORD-CLT              1.9         145
7095  Flight7096  41701  ORD-ATL             10.4          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7094             0.750000             137.5     25437.5             8
7095             0.333333             200.0     37000.0             3

      Flight Year
7094         2015
7095         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7096  Flight7097  42342  ORD-DEN              1.8           3
7097  Flight7098  41905  ORD-PHX              2.2         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7096             0.687500               300       55500            12
7097             0.354167               250       46250             9

      Flight Year
7096         2015
7097         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7098  Flight7099  42350  ORD-JFK              2.5           5
7099  Flight7100  41812  ORD-MIA              1.9          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7098                 0.75               250       46250            12
7099                 0.75               330       54450             6

      Flight Year
7098         2015
7099         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7100  Flight7101  41961  ORD-PHX              1.2          45
7101  Flight7102  41926  ORD-ATL              9.6          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7100             0.291667               250       41250            11
7101             0.583333               200       33000            10

      Flight Year
7100         2014
7101         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7102  Flight7103  41864  ORD-DTW              2.9           8
7103  Flight7104  42105  ORD-MCO              1.9         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7102             0.458333             126.5     23402.5             8
7103             0.708333             250.0     46250.0             4

      Flight Year
7102         2014
7103         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7104  Flight7105  41937  ORD-ATL              8.1          12
7105  Flight7106  41967  ORD-PHX              2.8          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7104             0.291667               200       37000            10
7105             0.333333               375       61875            11

      Flight Year
7104         2014
7105         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7106  Flight7107  41953  ORD-DTW              2.3          83
7107  Flight7108  42146  ORD-PHX              3.8          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7106             0.812500               115       20815            11
7107             0.291667               250       46250             5

      Flight Year
7106         2014
7107         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7108  Flight7109  42353  ORD-SEA              2.0          74
7109  Flight7110  42028  ORD-MSP              1.4         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7108             0.750000               350       63350            12
7109             0.708333               115       18975             1

      Flight Year
7108         2015
7109         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7110  Flight7111  41931  ORD-BWI              1.1          44
7111  Flight7112  41820  ORD-MIA              1.6         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7110             0.291667               240       39600            10
7111             0.708333               330       54450             6

      Flight Year
7110         2014
7111         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7112  Flight7113  42188  ORD-LAS              2.4         146
7113  Flight7114  42069  ORD-DEN              2.1         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7112             0.875000             302.5     55962.5             7
7113             0.333333             300.0     49500.0             3

      Flight Year
7112         2015
7113         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7114  Flight7115  42126  ORD-SFO              2.8          88
7115  Flight7116  41854  ORD-LAS              2.3          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7114             0.791667             375.0     67875.0             5
7115             0.333333             302.5     49912.5             8

      Flight Year
7114         2015
7115         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7116  Flight7117  41903  ORD-SFO              4.0          12
7117  Flight7118  42211  ORD-LGA              1.1         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7116             0.729167             375.0     69375.0             9
7117             0.312500             302.5     49912.5             7

      Flight Year
7116         2014
7117         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7118  Flight7119  42246  ORD-DEN              1.2         193
7119  Flight7120  41685  ORD-SEA              2.9         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7118             0.729167               330       54450             8
7119             0.833333               350       57750             2

      Flight Year
7118         2015
7119         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7120  Flight7121  42334  ORD-CLT              5.9          34
7121  Flight7122  42071  ORD-DEN              2.8         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7120                0.750             187.5     34687.5            11
7121                0.375             300.0     55500.0             3

      Flight Year
7120         2015
7121         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7122  Flight7123  42081  ORD-LAS              0.8           1
7123  Flight7124  41995  ORD-LAX              8.8          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7122             0.708333               275       50875             3
7123             0.791667               490       80850            12

      Flight Year
7122         2015
7123         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7124  Flight7125  41973  ORD-EWR              5.0         171
7125  Flight7126  41931  ORD-ATL              8.2          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7124             0.833333             337.5     55687.5            11
7125             0.312500             200.0     36200.0            10

      Flight Year
7124         2014
7125         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7126  Flight7127  42322  ORD-MIA              2.8         205
7127  Flight7128  41971  ORD-DEN              5.3          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7126               0.8125               300       49500            11
7127               0.4375               450       83250            11

      Flight Year
7126         2015
7127         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7128  Flight7129  42178  ORD-LAS              2.5         134
7129  Flight7130  41920  ORD-ATL              9.1         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7128             0.291667             302.5     55962.5             6
7129             0.750000             200.0     33000.0            10

      Flight Year
7128         2015
7129         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7130  Flight7131  41681  ORD-SFO              2.2         164
7131  Flight7132  42352  ORD-EWR              0.4         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7130             0.729167               375       61875             2
7131             0.333333               225       41625            12

      Flight Year
7130         2014
7131         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7132  Flight7133  41863  ORD-DFW              3.4         207
7133  Flight7134  42337  ORD-IAD              3.7         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7132             0.770833               220       36300             8
7133             0.750000               450       83250            11

      Flight Year
7132         2014
7133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7134  Flight7135  42333  ORD-JFK              4.6         181
7135  Flight7136  42194  ORD-LAX              5.8          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7134             0.291667               375       61875            11
7135             0.291667               385       63525             7

      Flight Year
7134         2015
7135         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7136  Flight7137  41921  ORD-LAX              4.2          94
7137  Flight7138  42127  ORD-SFO              1.8          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7136             0.791667               350       64750            10
7137             0.312500               375       67875             5

      Flight Year
7136         2014
7137         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7138  Flight7139  42225  ORD-MCO              2.1         107
7139  Flight7140  42245  ORD-CLT              3.0          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7138             0.312500             275.0     50875.0             8
7139             0.291667             137.5     22687.5             8

      Flight Year
7138         2015
7139         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7140  Flight7141  42283  ORD-PHX              1.8         113
7141  Flight7142  42341  ORD-ATL              7.0         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7140             0.625000               250       46250            10
7141             0.791667               200       33000            12

      Flight Year
7140         2015
7141         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7142  Flight7143  42321  ORD-IAH              2.7          27
7143  Flight7144  42155  ORD-DFW              1.0          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7142             0.541667               200       37000            11
7143             0.291667               200       36200             5

      Flight Year
7142         2015
7143         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7144  Flight7145  42229  ORD-LAX              4.2         106
7145  Flight7146  41719  ORD-EWR              1.4         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7144             0.729167               385       71225             8
7145             0.750000               225       37125             3

      Flight Year
7144         2015
7145         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7146  Flight7147  42333  ORD-CLT              5.4         135
7147  Flight7148  41745  ORD-LAX              4.8           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7146             0.687500             187.5     34687.5            11
7147             0.791667             350.0     64750.0             4

      Flight Year
7146         2015
7147         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7148  Flight7149  41717  ORD-SEA              1.6          38
7149  Flight7150  42087  ORD-MIA              2.4         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7148             0.750000               350       57750             3
7149             0.354167               300       55500             3

      Flight Year
7148         2014
7149         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7150  Flight7151  41818  ORD-DFW              1.7         118
7151  Flight7152  41870  ORD-LAX              5.4          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7150                0.625               220       40700             6
7151                0.375               385       69685             8

      Flight Year
7150         2014
7151         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7152  Flight7153  41772  ORD-MCO              1.5          87
7153  Flight7154  42121  ORD-DFW              1.4         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7152             0.354167               250       45250             5
7153             0.729167               200       37000             4

      Flight Year
7152         2014
7153         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7154  Flight7155  42351  ORD-ATL              9.4          51
7155  Flight7156  41845  ORD-MIA              2.2          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7154             0.708333               200       33000            12
7155             0.791667               330       54450             7

      Flight Year
7154         2015
7155         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7156  Flight7157  41981  ORD-DEN              1.7         148
7157  Flight7158  42276  ORD-CLT              2.3         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7156             0.645833               300       55500            12
7157             0.708333               125       20625             9

      Flight Year
7156         2014
7157         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7158  Flight7159  41669  ORD-SEA              3.0          83
7159  Flight7160  41748  ORD-JFK              1.7          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7158             0.729167               350       63350             1
7159             0.812500               250       41250             4

      Flight Year
7158         2014
7159         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7160  Flight7161  41670  ORD-DTW              1.9         157
7161  Flight7162  41899  ORD-SEA              2.7         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7160             0.291667               115       18975             1
7161             0.375000               350       64750             9

      Flight Year
7160         2014
7161         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7162  Flight7163  42025  ORD-SEA              1.2         123
7163  Flight7164  42359  ORD-JFK              3.6         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7162             0.833333               350       64750             1
7163             0.750000               350       57750            12

      Flight Year
7162         2015
7163         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7164  Flight7165  42108  ORD-ATL              8.3         203
7165  Flight7166  41689  ORD-ATL              9.4          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7164             0.833333               200       33000             4
7165             0.791667               200       33000             2

      Flight Year
7164         2015
7165         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7166  Flight7167  42236  ORD-MIA              1.9         205
7167  Flight7168  41747  ORD-DFW              1.5         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7166             0.479167               330       54450             8
7167             0.854167               200       37000             4

      Flight Year
7166         2015
7167         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7168  Flight7169  41668  ORD-DTW              2.3         139
7169  Flight7170  41914  ORD-LAS              1.7          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7168             0.333333               115       21275             1
7169             0.770833               275       50875            10

      Flight Year
7168         2014
7169         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7170  Flight7171  42018  ORD-SFO              2.1         104
7171  Flight7172  41823  ORD-JFK              2.3         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7170             0.770833               375       69375             1
7171             0.312500               275       45375             7

      Flight Year
7170         2015
7171         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7172  Flight7173  42081  ORD-ATL              8.6          55
7173  Flight7174  42318  ORD-MCO              1.9          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7172             0.750000               200       33000             3
7173             0.791667               250       45250            11

      Flight Year
7172         2015
7173         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7174  Flight7175  41878  ORD-BOS              1.7         107
7175  Flight7176  41660  ORD-EWR              2.8         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7174             0.291667               330       61050             8
7175             0.854167               225       41625             1

      Flight Year
7174         2014
7175         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7176  Flight7177  42235  ORD-SFO              3.1          41
7177  Flight7178  41643  ORD-MCO              2.2         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7176             0.854167             412.5     68062.5             8
7177             0.833333             250.0     46250.0             1

      Flight Year
7176         2015
7177         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7178  Flight7179  42010  ORD-LAX              5.7          58
7179  Flight7180  41835  ORD-CLT              4.5          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7178                0.375             350.0     57750.0             1
7179                0.500             137.5     25437.5             7

      Flight Year
7178         2015
7179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7180  Flight7181  42210  ORD-CLT              1.2         109
7181  Flight7182  42085  ORD-IAH              1.0         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7180             0.333333             137.5     25437.5             7
7181             0.812500             200.0     33000.0             3

      Flight Year
7180         2015
7181         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7182  Flight7183  42168  ORD-LAX              7.2          57
7183  Flight7184  42167  ORD-PHX              2.2         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7182             0.791667               385       63525             6
7183             0.791667               275       45375             6

      Flight Year
7182         2015
7183         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7184  Flight7185  42282  ORD-JFK              1.2         114
7185  Flight7186  42276  ORD-PHL              2.9         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7184             0.583333               250       46250            10
7185             0.500000               275       50875             9

      Flight Year
7184         2015
7185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7186  Flight7187  42361  ORD-LAX              7.1         113
7187  Flight7188  41960  ORD-PHL              1.7         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7186                0.750               490       90650            12
7187                0.875               275       50875            11

      Flight Year
7186         2015
7187         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7188  Flight7189  41709  ORD-BWI              3.1         200
7189  Flight7190  42349  ORD-LGA              2.3         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7188             0.791667               240       39600             3
7189             0.541667               275       50875            12

      Flight Year
7188         2014
7189         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7190  Flight7191  42238  ORD-PHX              2.4          48
7191  Flight7192  41998  ORD-DTW              1.0         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7190             0.791667               275       45375             8
7191             0.583333               161       26565            12

      Flight Year
7190         2015
7191         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7192  Flight7193  42149  ORD-MCO              1.4         193
7193  Flight7194  41916  ORD-DFW              1.4          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7192             0.333333               250       41250             5
7193             0.395833               200       33000            10

      Flight Year
7192         2015
7193         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7194  Flight7195  41825  ORD-IAH              2.1         156
7195  Flight7196  42302  ORD-LAX              5.5         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7194             0.708333               220       36300             7
7195             0.583333               350       64750            10

      Flight Year
7194         2014
7195         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7196  Flight7197  41672  ORD-CLT              1.3          50
7197  Flight7198  42074  ORD-MIA              2.6         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7196             0.750000               125       20625             2
7197             0.291667               300       49500             3

      Flight Year
7196         2014
7197         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7198  Flight7199  41791  ORD-PHL              1.7         197
7199  Flight7200  41697  ORD-JFK              1.2          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7198             0.812500             302.5     49912.5             6
7199             0.520833             250.0     45250.0             2

      Flight Year
7198         2014
7199         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7200  Flight7201  42059  ORD-LGA              3.7         118
7201  Flight7202  41744  ORD-BOS              1.3         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7200             0.520833               275       50875             2
7201             0.791667               300       49500             4

      Flight Year
7200         2015
7201         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7202  Flight7203  42171  ORD-LAS              2.7          91
7203  Flight7204  42310  ORD-CLT              3.3          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7202             0.354167             302.5     55962.5             6
7203             0.479167             125.0     23125.0            11

      Flight Year
7202         2015
7203         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7204  Flight7205  42346  ORD-PHX              2.8          81
7205  Flight7206  41870  ORD-MIA              0.1         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7204             0.333333               250       45250            12
7205             0.770833               330       61050             8

      Flight Year
7204         2015
7205         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7206  Flight7207  41891  ORD-MSP              1.9         161
7207  Flight7208  41908  ORD-SFO              2.3         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7206             0.750000               115       18975             9
7207             0.291667               375       69375             9

      Flight Year
7206         2014
7207         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7208  Flight7209  41832  ORD-SFO              2.0          97
7209  Flight7210  41862  ORD-PHX              2.4         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7208             0.729167             412.5     76312.5             7
7209             0.708333             275.0     50875.0             8

      Flight Year
7208         2014
7209         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7210  Flight7211  42314  ORD-LAS              2.2          31
7211  Flight7212  41745  ORD-MSP              1.9         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7210             0.750000               275       50875            11
7211             0.291667               115       21275             4

      Flight Year
7210         2015
7211         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7212  Flight7213  41748  ORD-SEA              2.6           6
7213  Flight7214  41691  ORD-DFW              1.9         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7212             0.583333               350       64750             4
7213             0.812500               200       37000             2

      Flight Year
7212         2014
7213         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7214  Flight7215  41949  ORD-ATL             10.8         138
7215  Flight7216  41969  ORD-SFO              4.5          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7214                0.750             200.0     37000.0            11
7215                0.375             562.5    104062.5            11

      Flight Year
7214         2014
7215         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7216  Flight7217  41756  ORD-SFO              1.1         140
7217  Flight7218  41753  ORD-ATL              9.3         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7216             0.458333               375       69375             4
7217             0.770833               200       37000             4

      Flight Year
7216         2014
7217         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7218  Flight7219  42262  ORD-SFO              3.7          97
7219  Flight7220  42181  ORD-PHX              2.7         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7218             0.729167               375       69375             9
7219             0.750000               275       45375             6

      Flight Year
7218         2015
7219         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7220  Flight7221  41807  ORD-DFW              1.8         154
7221  Flight7222  42241  ORD-EWR              1.2         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7220             0.791667             220.0     36300.0             6
7221             0.833333             247.5     40837.5             8

      Flight Year
7220         2014
7221         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7222  Flight7223  41852  ORD-DFW              1.6         113
7223  Flight7224  42120  ORD-LAX              4.8          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7222             0.729167               220       40700             8
7223             0.833333               350       64750             4

      Flight Year
7222         2014
7223         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7224  Flight7225  42274  ORD-MCO              3.0         116
7225  Flight7226  41940  ORD-LAX              5.1         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7224             0.291667               250       46250             9
7225             0.312500               350       57750            10

      Flight Year
7224         2015
7225         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7226  Flight7227  41733  ORD-SEA              1.8          91
7227  Flight7228  41968  ORD-DEN              5.0          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7226             0.354167               350       64750             4
7227             0.875000               450       81450            11

      Flight Year
7226         2014
7227         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7228  Flight7229  41872  ORD-PHX              2.4         137
7229  Flight7230  41795  ORD-SFO              1.7          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7228             0.708333             275.0     50875.0             8
7229             0.875000             412.5     76312.5             6

      Flight Year
7228         2014
7229         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7230  Flight7231  41840  ORD-DEN              2.0         125
7231  Flight7232  42124  ORD-DTW              1.6          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7230             0.708333               330       61050             7
7231             0.729167               115       20815             4

      Flight Year
7230         2014
7231         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7232  Flight7233  42182  ORD-EWR              1.9          24
7233  Flight7234  42206  ORD-PHX              2.5          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7232             0.291667             247.5     45787.5             6
7233             0.333333             275.0     45375.0             7

      Flight Year
7232         2015
7233         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7234  Flight7235  41992  ORD-DFW                3          92
7235  Flight7236  42089  ORD-LAX                4         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7234             0.895833               200       37000            12
7235             0.708333               350       64750             3

      Flight Year
7234         2014
7235         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7236  Flight7237  42000  ORD-ATL             15.6          88
7237  Flight7238  41875  ORD-DEN              2.3          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7236                0.500               280       50680            12
7237                0.375               330       61050             8

      Flight Year
7236         2014
7237         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7238  Flight7239  42365  ORD-DEN              4.8         161
7239  Flight7240  41879  ORD-SFO              2.1         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7238             0.708333             420.0     69300.0            12
7239             0.500000             412.5     76312.5             8

      Flight Year
7238         2015
7239         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7240  Flight7241  41918  ORD-SFO              1.6         106
7241  Flight7242  42228  ORD-LGA              2.6         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7240             0.750000             375.0     69375.0            10
7241             0.458333             302.5     55962.5             8

      Flight Year
7240         2014
7241         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7242  Flight7243  42116  ORD-MIA              1.0         129
7243  Flight7244  41800  ORD-DFW              2.7          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7242             0.291667               300       55500             4
7243             0.708333               220       40700             6

      Flight Year
7242         2015
7243         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7244  Flight7245  42109  ORD-JFK              2.4         131
7245  Flight7246  42256  ORD-IAH              2.7          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7244             0.291667               250       46250             4
7245             0.291667               200       37000             9

      Flight Year
7244         2015
7245         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7246  Flight7247  41918  ORD-PHL              1.8           3
7247  Flight7248  42076  ORD-IAH              3.7          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7246             0.708333               275       50875            10
7247             0.750000               200       37000             3

      Flight Year
7246         2014
7247         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7248  Flight7249  41905  ORD-JFK              2.6         150
7249  Flight7250  42366  ORD-IAH              1.6          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7248             0.395833               250       46250             9
7249             0.791667               200       33000            12

      Flight Year
7248         2014
7249         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7250  Flight7251  41889  ORD-SEA              0.2         137
7251  Flight7252  41860  ORD-LGA              2.1         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7250             0.875000             350.0     64750.0             9
7251             0.645833             302.5     49912.5             8

      Flight Year
7250         2014
7251         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7252  Flight7253  42184  ORD-JFK              2.1         169
7253  Flight7254  41938  ORD-JFK              2.5          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7252             0.291667               275       45375             6
7253             0.291667               250       41250            10

      Flight Year
7252         2015
7253         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7254  Flight7255  41682  ORD-DFW              2.2         107
7255  Flight7256  41782  ORD-DFW              2.2          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7254             0.333333               200       37000             2
7255             0.791667               200       33000             5

      Flight Year
7254         2014
7255         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7256  Flight7257  42122  ORD-DEN              1.8         201
7257  Flight7258  42161  ORD-SEA              3.2         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7256               0.7500               300       49500             4
7257               0.3125               385       63525             6

      Flight Year
7256         2015
7257         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7258  Flight7259  41822  ORD-SFO              1.1         149
7259  Flight7260  42217  ORD-LAS              1.4          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7258             0.791667             412.5     76312.5             7
7259             0.750000             302.5     54752.5             8

      Flight Year
7258         2014
7259         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7260  Flight7261  42237  ORD-EWR              2.7         187
7261  Flight7262  42062  ORD-BWI              1.4         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7260             0.625000             247.5     40837.5             8
7261             0.791667             240.0     39600.0             2

      Flight Year
7260         2015
7261         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7262  Flight7263  41708  ORD-PHX              2.0          17
7263  Flight7264  41829  ORD-LAS              1.3          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7262             0.750000             250.0     46250.0             3
7263             0.708333             302.5     54752.5             7

      Flight Year
7262         2014
7263         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7264  Flight7265  41714  ORD-LAX              3.1           3
7265  Flight7266  42368  ORD-PHX              2.1          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7264             0.416667               350       64750             3
7265             0.291667               250       41250            12

      Flight Year
7264         2014
7265         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7266  Flight7267  41994  ORD-LAS              3.9          13
7267  Flight7268  41835  ORD-DFW              1.6          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7266             0.625000               275       50875            12
7267             0.708333               220       36300             7

      Flight Year
7266         2014
7267         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7268  Flight7269  42335  ORD-SEA              7.7         116
7269  Flight7270  41788  ORD-DEN              1.8          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7268             0.729167               525       97125            11
7269             0.750000               300       49500             5

      Flight Year
7268         2015
7269         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7270  Flight7271  41853  ORD-ATL             10.1         190
7271  Flight7272  42357  ORD-ATL              8.8          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7270                0.875               220       36300             8
7271                0.750               200       36200            12

      Flight Year
7270         2014
7271         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7272  Flight7273  41847  ORD-LAX              3.4         144
7273  Flight7274  41665  ORD-EWR              2.4          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7272             0.333333               385       71225             7
7273             0.500000               225       40725             1

      Flight Year
7272         2014
7273         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7274  Flight7275  41913  ORD-MIA              2.9         104
7275  Flight7276  41732  ORD-MSP              0.2         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7274             0.458333               300       55500            10
7275             0.833333               115       18975             4

      Flight Year
7274         2014
7275         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7276  Flight7277  42224  ORD-IAH              2.5         179
7277  Flight7278  42362  ORD-DTW              4.3          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7276             0.770833               220       36300             8
7277             0.729167               161       29785            12

      Flight Year
7276         2015
7277         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7278  Flight7279  41834  ORD-DFW              3.9          76
7279  Flight7280  42244  ORD-BWI              2.6         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7278             0.291667               220       39820             7
7279             0.291667               264       48840             8

      Flight Year
7278         2014
7279         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7280  Flight7281  42211  ORD-LAX              5.0          49
7281  Flight7282  41855  ORD-DEN              2.3         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7280             0.791667               385       63525             7
7281             0.729167               330       61050             8

      Flight Year
7280         2015
7281         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7282  Flight7283  42281  ORD-DEN              1.6         125
7283  Flight7284  42179  ORD-MIA              2.4          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7282             0.750000               300       55500            10
7283             0.770833               330       54450             6

      Flight Year
7282         2015
7283         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7284  Flight7285  42223  ORD-SFO              1.9          91
7285  Flight7286  42160  ORD-PHX              2.5          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7284             0.770833             412.5     76312.5             8
7285             0.833333             275.0     49775.0             6

      Flight Year
7284         2015
7285         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7286  Flight7287  42014  ORD-LAX              3.9         136
7287  Flight7288  42199  ORD-IAH              1.0         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7286             0.791667               350       64750             1
7287             0.812500               220       40700             7

      Flight Year
7286         2015
7287         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7288  Flight7289  41868  ORD-PHL              2.4         168
7289  Flight7290  41872  ORD-DFW              1.5          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7288             0.437500             302.5     49912.5             8
7289             0.458333             220.0     40700.0             8

      Flight Year
7288         2014
7289         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7290  Flight7291  42258  ORD-MCO              0.5          15
7291  Flight7292  41950  ORD-JFK              3.2         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7290             0.791667               250       46250             9
7291             0.416667               250       46250            11

      Flight Year
7290         2015
7291         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7292  Flight7293  41766  ORD-ATL              9.9         123
7293  Flight7294  42346  ORD-DEN              1.1          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7292             0.750000               200       37000             5
7293             0.604167               300       55500            12

      Flight Year
7292         2014
7293         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7294  Flight7295  42362  ORD-SEA                2         106
7295  Flight7296  42327  ORD-SFO                3         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7294               0.5000               490       90650            12
7295               0.5625               375       61875            11

      Flight Year
7294         2015
7295         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7296  Flight7297  42107  ORD-MIA              2.0         210
7297  Flight7298  41737  ORD-SFO              1.9         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7296             0.750000               300       49500             4
7297             0.729167               375       69375             4

      Flight Year
7296         2015
7297         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7298  Flight7299  42263  ORD-EWR              1.4         191
7299  Flight7300  41801  ORD-MCO              1.5         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7298             0.291667               225       37125             9
7299             0.375000               275       45375             6

      Flight Year
7298         2015
7299         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7300  Flight7301  41704  ORD-MCO              0.8          98
7301  Flight7302  42032  ORD-EWR              2.1         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7300                0.625               250       46250             3
7301                0.750               225       37125             1

      Flight Year
7300         2014
7301         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7302  Flight7303  42204  ORD-EWR              2.5         111
7303  Flight7304  42064  ORD-ATL              9.5         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7302             0.333333             247.5     45787.5             7
7303             0.791667             200.0     33000.0             3

      Flight Year
7302         2015
7303         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7304  Flight7305  41658  ORD-SEA              2.8         187
7305  Flight7306  42066  ORD-LAS              2.2          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7304             0.500000               350       57750             1
7305             0.729167               275       49775             3

      Flight Year
7304         2014
7305         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7306  Flight7307  42360  ORD-MIA              4.5         188
7307  Flight7308  42234  ORD-PHX              2.6         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7306             0.333333               420       69300            12
7307             0.312500               275       50875             8

      Flight Year
7306         2015
7307         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7308  Flight7309  41728  ORD-DEN              1.1         141
7309  Flight7310  41824  ORD-JFK              2.5         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7308             0.791667               300       55500             3
7309             0.791667               275       45375             7

      Flight Year
7308         2014
7309         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7310  Flight7311  42348  ORD-BOS              3.3         131
7311  Flight7312  41972  ORD-IAD              3.9          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7310             0.291667               300       55500            12
7311             0.729167               450       81450            11

      Flight Year
7310         2015
7311         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7312  Flight7313  42093  ORD-PHX              2.5         192
7313  Flight7314  42277  ORD-CLT              1.8         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7312             0.333333               250       41250             3
7313             0.750000               125       23125             9

      Flight Year
7312         2015
7313         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7314  Flight7315  42001  ORD-MIA              5.0          92
7315  Flight7316  42235  ORD-DCA              1.8          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7314                 0.50               420       77700            12
7315                 0.75              5500      995500             8

      Flight Year
7314         2014
7315         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7316  Flight7317  41879  ORD-JFK              3.1          71
7317  Flight7318  42019  ORD-BWI              2.3         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7316             0.708333               275       49775             8
7317             0.291667               240       44400             1

      Flight Year
7316         2014
7317         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7318  Flight7319  42133  ORD-CLT              1.8          54
7319  Flight7320  42342  ORD-PHL              2.3          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7318             0.666667               125       20625             5
7319             0.833333               275       50875            12

      Flight Year
7318         2015
7319         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7320  Flight7321  41828  ORD-CLT              2.9         178
7321  Flight7322  42292  ORD-DEN              1.3         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7320             0.333333             137.5     22687.5             7
7321             0.833333             300.0     49500.0            10

      Flight Year
7320         2014
7321         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7322  Flight7323  42191  ORD-ATL             10.6          32
7323  Flight7324  41968  ORD-IAH              6.2         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7322             0.750000               220       40700             7
7323             0.291667               300       49500            11

      Flight Year
7322         2015
7323         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7324  Flight7325  42128  ORD-SFO              2.8         117
7325  Flight7326  41653  ORD-PHX              1.0         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7324             0.770833               375       69375             5
7325             0.604167               250       41250             1

      Flight Year
7324         2015
7325         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7326  Flight7327  42249  ORD-SFO              1.9          47
7327  Flight7328  42224  ORD-BOS              2.6         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7326             0.333333               375       61875             9
7327             0.333333               330       54450             8

      Flight Year
7326         2015
7327         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7328  Flight7329  42171  ORD-JFK              2.1          21
7329  Flight7330  42228  ORD-IAD              2.2          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7328             0.833333               275       50875             6
7329             0.541667               330       54450             8

      Flight Year
7328         2015
7329         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7330  Flight7331  41928  ORD-ATL             10.6         120
7331  Flight7332  42054  ORD-PHL              2.9           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7330                 0.75               200       37000            10
7331                 0.75               275       50875             2

      Flight Year
7330         2014
7331         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7332  Flight7333  42360  ORD-MCO              3.4          28
7333  Flight7334  41785  ORD-PHX              3.6          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7332             0.708333               350       64750            12
7333             0.416667               250       41250             5

      Flight Year
7332         2015
7333         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7334  Flight7335  41946  ORD-DFW              1.5         130
7335  Flight7336  41642  ORD-PHX              0.9         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7334             0.791667               200       37000            11
7335             0.708333               250       46250             1

      Flight Year
7334         2014
7335         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7336  Flight7337  41782  ORD-MIA              1.9          96
7337  Flight7338  41653  ORD-LAX              3.9          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7336             0.291667               300       55500             5
7337             0.291667               350       57750             1

      Flight Year
7336         2014
7337         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7338  Flight7339  41886  ORD-DFW              1.8          92
7339  Flight7340  42163  ORD-MCO              2.1          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7338             0.791667               200       37000             9
7339             0.708333               275       49775             6

      Flight Year
7338         2014
7339         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7340  Flight7341  41817  ORD-PHL              3.1         157
7341  Flight7342  42256  ORD-CLT              2.5         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7340             0.541667             302.5     49912.5             6
7341             0.333333             125.0     20625.0             9

      Flight Year
7340         2014
7341         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7342  Flight7343  41814  ORD-CLT              1.6         210
7343  Flight7344  42138  ORD-CLT              3.5           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7342             0.708333             137.5     22687.5             6
7343             0.708333             125.0     23125.0             5

      Flight Year
7342         2014
7343         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7344  Flight7345  42140  ORD-LAX              4.9          50
7345  Flight7346  41696  ORD-SFO              0.8         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7344             0.854167               350       57750             5
7345             0.791667               375       69375             2

      Flight Year
7344         2015
7345         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7346  Flight7347  41970  ORD-SFO              4.4         169
7347  Flight7348  42208  ORD-SEA              2.2          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7346             0.500000             562.5     92812.5            11
7347             0.416667             385.0     63525.0             7

      Flight Year
7346         2014
7347         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7348  Flight7349  41785  ORD-JFK              1.6         126
7349  Flight7350  42238  ORD-MSP              2.5          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7348             0.687500             250.0     46250.0             5
7349             0.333333             126.5     20872.5             8

      Flight Year
7348         2014
7349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7350  Flight7351  41852  ORD-SEA              1.2          46
7351  Flight7352  42360  ORD-ATL              9.3          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7350             0.333333               385       63525             8
7351             0.750000               280       46200            12

      Flight Year
7350         2014
7351         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7352  Flight7353  42080  ORD-DEN              2.8         163
7353  Flight7354  41815  ORD-ATL             10.3         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7352             0.333333               300       49500             3
7353             0.791667               220       40700             6

      Flight Year
7352         2015
7353         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7354  Flight7355  42089  ORD-PHL              1.3         205
7355  Flight7356  41756  ORD-ATL              6.9         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7354             0.354167               275       45375             3
7355             0.895833               200       33000             4

      Flight Year
7354         2015
7355         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7356  Flight7357  42210  ORD-IAH              1.9         107
7357  Flight7358  41751  ORD-LAX              5.6          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7356             0.729167               220       40700             7
7357             0.791667               350       63350             4

      Flight Year
7356         2015
7357         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7358  Flight7359  42365  ORD-DEN              2.1         160
7359  Flight7360  41764  ORD-DFW              2.3         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7358             0.833333               420       69300            12
7359             0.770833               200       33000             5

      Flight Year
7358         2015
7359         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7360  Flight7361  42053  ORD-LAX              3.2          44
7361  Flight7362  42002  ORD-PHX              0.5         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7360             0.604167               350       57750             2
7361             0.583333               250       41250            12

      Flight Year
7360         2015
7361         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7362  Flight7363  41675  ORD-CLT              1.2          36
7363  Flight7364  42170  ORD-PHX              2.3         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7362             0.708333               125       20625             2
7363             0.333333               275       50875             6

      Flight Year
7362         2014
7363         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7364  Flight7365  42186  ORD-ATL              9.9          27
7365  Flight7366  42097  ORD-EWR              3.8          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7364             0.708333               220       40700             7
7365             0.770833               225       41625             4

      Flight Year
7364         2015
7365         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7366  Flight7367  42193  ORD-MIA              1.9         146
7367  Flight7368  42221  ORD-DFW              2.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7366             0.791667               330       61050             7
7367             0.354167               220       36300             8

      Flight Year
7366         2015
7367         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7368  Flight7369  42336  ORD-LAS              6.4          58
7369  Flight7370  42357  ORD-JFK              2.1          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7368               0.8125             412.5     68062.5            11
7369               0.3125             250.0     46250.0            12

      Flight Year
7368         2015
7369         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7370  Flight7371  41870  ORD-LAS              1.0          31
7371  Flight7372  42152  ORD-ATL              8.4          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7370             0.791667             302.5     55962.5             8
7371             0.854167             200.0     37000.0             5

      Flight Year
7370         2014
7371         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7372  Flight7373  41714  ORD-LGA              2.3         141
7373  Flight7374  41767  ORD-ATL             10.0         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7372             0.291667               275       50875             3
7373             0.750000               200       33000             5

      Flight Year
7372         2014
7373         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7374  Flight7375  42229  ORD-LAS              0.7         206
7375  Flight7376  41745  ORD-LAS              1.9         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7374             0.416667             302.5     49912.5             8
7375             0.625000             275.0     45375.0             4

      Flight Year
7374         2015
7375         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7376  Flight7377  42003  ORD-CLT              1.4         178
7377  Flight7378  41695  ORD-JFK              1.5         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7376             0.812500               125       20625            12
7377             0.333333               250       46250             2

      Flight Year
7376         2014
7377         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7378  Flight7379  42355  ORD-CLT              1.5         155
7379  Flight7380  42047  ORD-BOS              1.9         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7378             0.708333               125       20625            12
7379             0.812500               300       49500             2

      Flight Year
7378         2015
7379         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7380  Flight7381  42294  ORD-JFK              1.3         184
7381  Flight7382  42061  ORD-DEN              0.7          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7380             0.750000               250       41250            10
7381             0.541667               300       54300             2

      Flight Year
7380         2015
7381         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7382  Flight7383  41657  ORD-LAX              4.7         152
7383  Flight7384  42213  ORD-JFK              2.6         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7382               0.8125               350       57750             1
7383               0.3750               275       50875             7

      Flight Year
7382         2014
7383         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7384  Flight7385  42176  ORD-LAS              2.1          21
7385  Flight7386  42340  ORD-JFK              2.1          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7384               0.8125             302.5     55962.5             6
7385               0.4375             250.0     46250.0            12

      Flight Year
7384         2015
7385         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7386  Flight7387  41864  ORD-CLT              1.6         162
7387  Flight7388  41880  ORD-CLT              2.3          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7386             0.833333             137.5     22687.5             8
7387             0.500000             137.5     22687.5             8

      Flight Year
7386         2014
7387         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7388  Flight7389  41698  ORD-CLT              2.4         134
7389  Flight7390  42312  ORD-SFO              1.9         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7388             0.520833               125       23125             2
7389             0.666667               375       69375            11

      Flight Year
7388         2014
7389         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7390  Flight7391  42208  ORD-IAD              1.1         150
7391  Flight7392  42157  ORD-DEN              2.6          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7390             0.479167               330       61050             7
7391             0.625000               330       59730             6

      Flight Year
7390         2015
7391         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7392  Flight7393  41807  ORD-IAH              1.9          67
7393  Flight7394  41847  ORD-LAS              2.6          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7392               0.3125             220.0     39820.0             6
7393               0.8125             302.5     54752.5             7

      Flight Year
7392         2014
7393         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7394  Flight7395  41685  ORD-JFK              2.5         130
7395  Flight7396  42194  ORD-ATL             10.0           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7394                 0.50               250       46250             2
7395                 0.75               220       40700             7

      Flight Year
7394         2014
7395         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7396  Flight7397  41882  ORD-EWR              1.1          92
7397  Flight7398  41817  ORD-SEA              2.1          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7396             0.729167             247.5     45787.5             8
7397             0.750000             385.0     71225.0             6

      Flight Year
7396         2014
7397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7398  Flight7399  42345  ORD-SEA              2.8         162
7399  Flight7400  42317  ORD-SEA              2.0         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7398             0.541667               350       57750            12
7399             0.354167               350       64750            11

      Flight Year
7398         2015
7399         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7400  Flight7401  42265  ORD-JFK              1.7         143
7401  Flight7402  41949  ORD-PHX              2.9          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7400             0.708333               250       46250             9
7401             0.604167               250       45250            11

      Flight Year
7400         2015
7401         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7402  Flight7403  41752  ORD-LGA              0.5         186
7403  Flight7404  42156  ORD-EWR              2.4           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7402             0.833333             275.0     45375.0             4
7403             0.291667             247.5     45787.5             6

      Flight Year
7402         2014
7403         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7404  Flight7405  41969  ORD-JFK              1.8         210
7405  Flight7406  42069  ORD-DFW              1.9          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7404             0.750000               375       61875            11
7405             0.770833               200       36200             3

      Flight Year
7404         2014
7405         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7406  Flight7407  41863  ORD-IAH              2.7          43
7407  Flight7408  41958  ORD-MIA              2.1         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7406             0.791667               220       36300             8
7407             0.791667               300       55500            11

      Flight Year
7406         2014
7407         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7408  Flight7409  41720  ORD-MSP              2.5          37
7409  Flight7410  41852  ORD-MCO              1.9          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7408             0.708333               115       18975             3
7409             0.854167               275       50875             8

      Flight Year
7408         2014
7409         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7410  Flight7411  41774  ORD-MCO              2.2         109
7411  Flight7412  42252  ORD-IAH              1.7          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7410             0.791667               250       46250             5
7411             0.750000               200       36200             9

      Flight Year
7410         2014
7411         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7412  Flight7413  41729  ORD-JFK              2.0         165
7413  Flight7414  41806  ORD-EWR              1.6          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7412             0.458333             250.0     41250.0             3
7413             0.729167             247.5     45787.5             6

      Flight Year
7412         2014
7413         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7414  Flight7415  41966  ORD-BOS              2.8          74
7415  Flight7416  41983  ORD-LAX              3.1          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7414             0.333333               300       54300            11
7415             0.583333               350       64750            12

      Flight Year
7414         2014
7415         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7416  Flight7417  42228  ORD-LGA              2.5         149
7417  Flight7418  41868  ORD-BOS              3.2         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7416                0.750             302.5     55962.5             8
7417                0.625             330.0     54450.0             8

      Flight Year
7416         2015
7417         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7418  Flight7419  42207  ORD-ATL             10.6         125
7419  Flight7420  42326  ORD-PHL              1.9          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7418                0.875               220       40700             7
7419                0.625               275       49775            11

      Flight Year
7418         2015
7419         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7420  Flight7421  41902  ORD-DFW              0.5         137
7421  Flight7422  42008  ORD-LAX              3.2          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7420             0.541667               200       37000             9
7421             0.312500               350       63350             1

      Flight Year
7420         2014
7421         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7422  Flight7423  41955  ORD-JFK              3.4         125
7423  Flight7424  41833  ORD-DFW              2.3          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7422             0.687500               250       46250            11
7423             0.833333               220       39820             7

      Flight Year
7422         2014
7423         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7424  Flight7425  41888  ORD-IAH              2.0         187
7425  Flight7426  41935  ORD-DFW              0.5          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7424             0.708333               200       33000             9
7425             0.500000               200       36200            10

      Flight Year
7424         2014
7425         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7426  Flight7427  42173  ORD-PHX              2.1         185
7427  Flight7428  42217  ORD-DTW              1.8          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7426             0.729167             275.0     45375.0             6
7427             0.333333             126.5     23402.5             8

      Flight Year
7426         2015
7427         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7428  Flight7429  41860  ORD-CLT              3.1          15
7429  Flight7430  41871  ORD-LAS              2.3          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7428             0.833333             137.5     25437.5             8
7429             0.625000             302.5     55962.5             8

      Flight Year
7428         2014
7429         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7430  Flight7431  42315  ORD-DEN              2.7         129
7431  Flight7432  42019  ORD-SFO              1.4         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7430             0.708333               300       55500            11
7431             0.312500               375       69375             1

      Flight Year
7430         2015
7431         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7432  Flight7433  42268  ORD-CLT              2.4          98
7433  Flight7434  41729  ORD-PHX              1.4         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7432             0.625000               125       23125             9
7433             0.791667               250       41250             3

      Flight Year
7432         2015
7433         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7434  Flight7435  41720  ORD-IAH              1.3         133
7435  Flight7436  41653  ORD-SFO              1.9         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7434               0.6250               200       37000             3
7435               0.3125               375       61875             1

      Flight Year
7434         2014
7435         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7436  Flight7437  41705  ORD-SFO              2.7          97
7437  Flight7438  42127  ORD-DFW              1.3          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7436             0.354167               375       69375             3
7437             0.833333               200       33000             5

      Flight Year
7436         2014
7437         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7438  Flight7439  42125  ORD-MIA              2.1         119
7439  Flight7440  42261  ORD-PHX              2.9         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7438             0.833333               300       55500             5
7439             0.291667               250       41250             9

      Flight Year
7438         2015
7439         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7440  Flight7441  42015  ORD-LAX              3.9         157
7441  Flight7442  42348  ORD-SFO              2.7         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7440             0.833333               350       57750             1
7441             0.833333               375       61875            12

      Flight Year
7440         2015
7441         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7442  Flight7443  41879  ORD-CLT              2.3         132
7443  Flight7444  41691  ORD-DFW              3.3          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7442             0.416667             137.5     25437.5             8
7443             0.291667             200.0     33000.0             2

      Flight Year
7442         2014
7443         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7444  Flight7445  42229  ORD-PHL              0.8         147
7445  Flight7446  41907  ORD-DEN              2.3          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7444             0.812500             302.5     55962.5             8
7445             0.541667             300.0     54300.0             9

      Flight Year
7444         2015
7445         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7446  Flight7447  41752  ORD-PHL              1.8          89
7447  Flight7448  42145  ORD-DFW              1.3         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7446             0.416667               275       49775             4
7447             0.500000               200       37000             5

      Flight Year
7446         2014
7447         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7448  Flight7449  42332  ORD-LAX             10.2         113
7449  Flight7450  41843  ORD-ATL              9.8          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7448             0.333333               525       97125            11
7449             0.708333               220       36300             7

      Flight Year
7448         2015
7449         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7450  Flight7451  41650  ORD-SEA              1.9         182
7451  Flight7452  42355  ORD-MIA              1.8         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7450             0.770833               350       57750             1
7451             0.812500               300       55500            12

      Flight Year
7450         2014
7451         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7452  Flight7453  41802  ORD-CLT              2.8         133
7453  Flight7454  42082  ORD-JFK              2.1         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7452             0.562500             137.5     25437.5             6
7453             0.708333             250.0     46250.0             3

      Flight Year
7452         2014
7453         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7454  Flight7455  41864  ORD-PHX              2.6         199
7455  Flight7456  41710  ORD-DFW              2.5          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7454             0.291667               275       45375             8
7455             0.458333               200       33000             3

      Flight Year
7454         2014
7455         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7456  Flight7457  41715  ORD-LAX              3.7         189
7457  Flight7458  42087  ORD-BOS              1.8         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7456             0.812500               350       57750             3
7457             0.770833               300       49500             3

      Flight Year
7456         2014
7457         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7458  Flight7459  41995  ORD-JFK              2.9           9
7459  Flight7460  42235  ORD-PHX              2.8         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7458             0.291667               350       64750            12
7459             0.750000               275       45375             8

      Flight Year
7458         2014
7459         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7460  Flight7461  42178  ORD-LAX              4.7         181
7461  Flight7462  41897  ORD-CLT              2.0         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7460             0.791667               385       63525             6
7461             0.625000               125       20625             9

      Flight Year
7460         2015
7461         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7462  Flight7463  41904  ORD-LAS              2.8         139
7463  Flight7464  41787  ORD-SEA              1.8         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7462             0.541667               275       50875             9
7463             0.854167               350       57750             5

      Flight Year
7462         2014
7463         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7464  Flight7465  41858  ORD-MCO              1.9         126
7465  Flight7466  41765  ORD-EWR              2.0         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7464             0.770833               275       50875             8
7465             0.291667               225       37125             5

      Flight Year
7464         2014
7465         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7466  Flight7467  41857  ORD-CLT              0.6         179
7467  Flight7468  42257  ORD-LAX              3.2          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7466             0.416667             137.5     22687.5             8
7467             0.708333             350.0     64750.0             9

      Flight Year
7466         2014
7467         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7468  Flight7469  41892  ORD-JFK              1.4         185
7469  Flight7470  42220  ORD-IAH              2.4          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7468             0.645833               250       41250             9
7469             0.854167               220       40700             8

      Flight Year
7468         2014
7469         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7470  Flight7471  42166  ORD-MCO              2.8          51
7471  Flight7472  42360  ORD-BOS              4.9         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7470             0.833333               275       45375             6
7471             0.541667               420       69300            12

      Flight Year
7470         2015
7471         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7472  Flight7473  42241  ORD-LGA              3.0          60
7473  Flight7474  41974  ORD-PHX              2.8         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7472             0.375000             302.5     49912.5             8
7473             0.729167             250.0     46250.0            12

      Flight Year
7472         2015
7473         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7474  Flight7475  41980  ORD-ATL             10.7         160
7475  Flight7476  41832  ORD-DTW              1.6         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7474             0.770833             200.0     33000.0            12
7475             0.520833             126.5     23402.5             7

      Flight Year
7474         2014
7475         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7476  Flight7477  42234  ORD-FLL              2.5          64
7477  Flight7478  41736  ORD-JFK              1.7         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7476             0.791667               330       59730             8
7477             0.708333               250       46250             4

      Flight Year
7476         2015
7477         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7478  Flight7479  41793  ORD-LAX              5.4          63
7479  Flight7480  42272  ORD-MSP              1.1         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7478             0.708333               385       69685             6
7479             0.708333               115       18975             9

      Flight Year
7478         2014
7479         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7480  Flight7481  41811  ORD-ATL              8.7         106
7481  Flight7482  42311  ORD-CLT              2.2          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7480             0.479167               220       40700             6
7481             0.833333               125       23125            11

      Flight Year
7480         2014
7481         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7482  Flight7483  41860  ORD-ATL              8.6          12
7483  Flight7484  41961  ORD-MSP              2.4         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7482             0.854167               220       40700             8
7483             0.729167               115       21275            11

      Flight Year
7482         2014
7483         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7484  Flight7485  41727  ORD-EWR              0.5         140
7485  Flight7486  42123  ORD-MIA              2.2         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7484             0.354167               225       41625             3
7485             0.500000               300       55500             4

      Flight Year
7484         2014
7485         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7486  Flight7487  42169  ORD-PHX              1.7          20
7487  Flight7488  42108  ORD-CLT              1.5           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7486             0.333333               275       50875             6
7487             0.729167               125       23125             4

      Flight Year
7486         2015
7487         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7488  Flight7489  41798  ORD-PHX              1.8          68
7489  Flight7490  41833  ORD-BOS              2.3          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7488             0.541667               275       49775             6
7489             0.750000               330       54450             7

      Flight Year
7488         2014
7489         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7490  Flight7491  41983  ORD-DTW              1.0         172
7491  Flight7492  41823  ORD-SFO              2.5         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7490             0.729167             115.0     18975.0            12
7491             0.708333             412.5     76312.5             7

      Flight Year
7490         2014
7491         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7492  Flight7493  42027  ORD-LAX              4.4         146
7493  Flight7494  41926  ORD-PHL              1.8          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7492             0.333333               350       64750             1
7493             0.666667               275       45375            10

      Flight Year
7492         2015
7493         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7494  Flight7495  42141  ORD-MIA              1.8          46
7495  Flight7496  41681  ORD-CLT              2.3         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7494             0.750000               300       49500             5
7495             0.458333               125       20625             2

      Flight Year
7494         2015
7495         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7496  Flight7497  42087  ORD-LAX              2.9         189
7497  Flight7498  42221  ORD-LGA              2.7          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7496             0.333333             350.0     57750.0             3
7497             0.729167             302.5     55962.5             8

      Flight Year
7496         2015
7497         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7498  Flight7499  41686  ORD-SEA              1.6           3
7499  Flight7500  42057  ORD-FLL              2.8          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7498             0.729167               350       64750             2
7499             0.583333               300       49500             2

      Flight Year
7498         2014
7499         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7500  Flight7501  42332  ORD-ATL             17.7          83
7501  Flight7502  41868  ORD-LAS              2.7         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7500             0.770833             300.0     54300.0            11
7501             0.750000             302.5     55962.5             8

      Flight Year
7500         2015
7501         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7502  Flight7503  42188  ORD-ATL             11.5         198
7503  Flight7504  42271  ORD-CLT              2.3           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7502             0.708333               220       36300             7
7503             0.750000               125       23125             9

      Flight Year
7502         2015
7503         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7504  Flight7505  42174  ORD-LAS              1.8         169
7505  Flight7506  42325  ORD-LGA              1.9         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7504             0.333333             302.5     49912.5             6
7505             0.750000             275.0     50875.0            11

      Flight Year
7504         2015
7505         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7506  Flight7507  41713  ORD-DCA              1.8          54
7507  Flight7508  41676  ORD-SFO              3.0         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7506                0.625              5000      825000             3
7507                0.625               375       61875             2

      Flight Year
7506         2014
7507         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7508  Flight7509  42347  ORD-DEN              2.2          19
7509  Flight7510  41829  ORD-PHX              1.9         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7508             0.770833               300       55500            12
7509             0.291667               275       50875             7

      Flight Year
7508         2015
7509         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7510  Flight7511  41861  ORD-PHL              3.1          47
7511  Flight7512  41884  ORD-LAS              0.4         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7510             0.729167             302.5     49912.5             8
7511             0.708333             275.0     50875.0             9

      Flight Year
7510         2014
7511         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7512  Flight7513  41673  ORD-DTW              3.5          70
7513  Flight7514  41692  ORD-DEN              1.6          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7512             0.875000               115       20815             2
7513             0.833333               300       54300             2

      Flight Year
7512         2014
7513         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7514  Flight7515  42335  ORD-SLC              3.4          57
7515  Flight7516  42261  ORD-SFO              1.6          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7514             0.770833               435       71775            11
7515             0.854167               375       67875             9

      Flight Year
7514         2015
7515         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7516  Flight7517  42367  ORD-ATL             11.1         185
7517  Flight7518  42317  ORD-DEN              1.4          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7516             0.791667               200       33000            12
7517             0.312500               300       55500            11

      Flight Year
7516         2015
7517         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7518  Flight7519  41977  ORD-ATL              7.5          44
7519  Flight7520  41896  ORD-DEN              2.0         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7518             0.708333               200       33000            12
7519             0.291667               300       49500             9

      Flight Year
7518         2014
7519         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7520  Flight7521  42049  ORD-CLT              3.3          21
7521  Flight7522  42188  ORD-ATL              7.0          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7520             0.354167               125       23125             2
7521             0.291667               220       40700             7

      Flight Year
7520         2015
7521         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7522  Flight7523  41970  ORD-CLT              6.8           6
7523  Flight7524  41996  ORD-PHL              3.5          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7522             0.729167             187.5     34687.5            11
7523             0.770833             385.0     69685.0            12

      Flight Year
7522         2014
7523         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7524  Flight7525  42133  ORD-MCO              3.0          72
7525  Flight7526  41891  ORD-LGA              1.2          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7524             0.604167               250       45250             5
7525             0.354167               275       45375             9

      Flight Year
7524         2015
7525         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7526  Flight7527  42334  ORD-MIA              4.9          13
7527  Flight7528  42256  ORD-PHL              2.5          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7526             0.312500               450       83250            11
7527             0.291667               275       50875             9

      Flight Year
7526         2015
7527         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7528  Flight7529  42128  ORD-LGA              1.8          83
7529  Flight7530  41888  ORD-DEN              2.1          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7528             0.791667               275       49775             5
7529             0.375000               300       55500             9

      Flight Year
7528         2015
7529         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7530  Flight7531  42226  ORD-PHL              1.8         201
7531  Flight7532  41817  ORD-BOS              1.0         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7530             0.333333             302.5     49912.5             8
7531             0.333333             330.0     54450.0             6

      Flight Year
7530         2015
7531         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7532  Flight7533  42157  ORD-SEA              4.1         147
7533  Flight7534  42251  ORD-SFO              1.7         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7532                0.750               385       71225             6
7533                0.875               375       69375             9

      Flight Year
7532         2015
7533         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7534  Flight7535  42140  ORD-PHL              2.1         187
7535  Flight7536  41849  ORD-ATL             10.5         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7534             0.812500               275       45375             5
7535             0.291667               220       40700             7

      Flight Year
7534         2015
7535         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7536  Flight7537  41886  ORD-SFO              3.4          76
7537  Flight7538  41771  ORD-MCO              3.2         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7536               0.7500               375       67875             9
7537               0.6875               250       41250             5

      Flight Year
7536         2014
7537         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7538  Flight7539  42026  ORD-DFW              2.6          89
7539  Flight7540  41942  ORD-SFO              2.3          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7538                 0.75               200       36200             1
7539                 0.75               375       69375            10

      Flight Year
7538         2015
7539         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7540  Flight7541  42342  ORD-BOS              3.6         141
7541  Flight7542  42207  ORD-DEN              2.5         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7540               0.7500               300       55500            12
7541               0.3125               330       54450             7

      Flight Year
7540         2015
7541         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7542  Flight7543  41759  ORD-JFK              3.5         188
7543  Flight7544  42115  ORD-JFK              1.8           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7542             0.833333               250       41250             4
7543             0.708333               250       46250             4

      Flight Year
7542         2014
7543         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7544  Flight7545  41908  ORD-SEA              3.0          81
7545  Flight7546  42339  ORD-LAS              2.4          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7544             0.791667               350       63350             9
7545             0.791667               275       50875            12

      Flight Year
7544         2014
7545         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7546  Flight7547  42290  ORD-ATL              9.1          96
7547  Flight7548  42308  ORD-MIA              1.5         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7546             0.729167               200       37000            10
7547             0.666667               300       49500            10

      Flight Year
7546         2015
7547         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7548  Flight7549  41976  ORD-PHX              2.4          34
7549  Flight7550  42157  ORD-LAX              6.4          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7548             0.791667               250       46250            12
7549             0.666667               385       71225             6

      Flight Year
7548         2014
7549         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7550  Flight7551  42001  ORD-ATL             14.9          77
7551  Flight7552  42139  ORD-JFK              1.6          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7550             0.583333               280       50680            12
7551             0.875000               250       41250             5

      Flight Year
7550         2014
7551         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7552  Flight7553  42124  ORD-LGA              2.4          55
7553  Flight7554  42314  ORD-DEN              1.8           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7552             0.708333               275       45375             4
7553             0.333333               300       55500            11

      Flight Year
7552         2015
7553         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7554  Flight7555  41684  ORD-ATL             10.7         181
7555  Flight7556  41974  ORD-LGA              1.5          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7554             0.708333               200       33000             2
7555             0.833333               275       50875            12

      Flight Year
7554         2014
7555         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7556  Flight7557  41997  ORD-MIA              2.8         198
7557  Flight7558  42028  ORD-SEA              2.1         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7556             0.833333               420       69300            12
7557             0.729167               350       64750             1

      Flight Year
7556         2014
7557         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7558  Flight7559  41856  ORD-SFO              2.3          60
7559  Flight7560  41781  ORD-DFW              2.7          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7558             0.291667             412.5     68062.5             8
7559             0.833333             200.0     36200.0             5

      Flight Year
7558         2014
7559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7560  Flight7561  42237  ORD-ATL             10.5           7
7561  Flight7562  41897  ORD-IAH              1.6          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7560             0.770833               220       40700             8
7561             0.875000               200       33000             9

      Flight Year
7560         2015
7561         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7562  Flight7563  42163  ORD-PHX              1.6         122
7563  Flight7564  42265  ORD-ATL              7.8          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7562             0.729167               275       50875             6
7563             0.708333               200       36200             9

      Flight Year
7562         2015
7563         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7564  Flight7565  42157  ORD-MIA              0.7          22
7565  Flight7566  41984  ORD-FLL              2.0         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7564             0.875000               330       61050             6
7565             0.729167               300       55500            12

      Flight Year
7564         2015
7565         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7566  Flight7567  42025  ORD-SEA              3.2         184
7567  Flight7568  42327  ORD-PHL              1.7          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7566               0.6875               350       57750             1
7567               0.7500               275       45375            11

      Flight Year
7566         2015
7567         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7568  Flight7569  41738  ORD-IAH              2.6         194
7569  Flight7570  41819  ORD-JFK              1.3         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7568             0.500000               200       33000             4
7569             0.479167               275       45375             6

      Flight Year
7568         2014
7569         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7570  Flight7571  42021  ORD-BOS              3.3         128
7571  Flight7572  42040  ORD-LAS              2.3          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7570             0.708333               300       55500             1
7571             0.291667               275       49775             2

      Flight Year
7570         2015
7571         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7572  Flight7573  42276  ORD-PHX              2.8         115
7573  Flight7574  42312  ORD-DEN              1.9         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7572             0.291667               250       46250             9
7573             0.416667               300       49500            11

      Flight Year
7572         2015
7573         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7574  Flight7575  41891  ORD-CLT              1.9         118
7575  Flight7576  41870  ORD-IAH              2.7         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7574             0.791667               125       23125             9
7575             0.333333               220       36300             8

      Flight Year
7574         2014
7575         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7576  Flight7577  41936  ORD-PHX              2.7         165
7577  Flight7578  41862  ORD-PHX              3.3         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7576             0.291667               250       41250            10
7577             0.708333               275       45375             8

      Flight Year
7576         2014
7577         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7578  Flight7579  42231  ORD-MIA                2           5
7579  Flight7580  41943  ORD-CLT                2         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7578             0.333333               330       61050             8
7579             0.354167               125       20625            10

      Flight Year
7578         2015
7579         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7580  Flight7581  42243  ORD-DEN              2.8         210
7581  Flight7582  42360  ORD-CLT              2.9          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7580             0.791667               330       54450             8
7581             0.500000               175       31675            12

      Flight Year
7580         2015
7581         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7582  Flight7583  42204  ORD-BWI              1.9          94
7583  Flight7584  42166  ORD-JFK              2.5         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7582             0.770833               264       48840             7
7583             0.708333               275       50875             6

      Flight Year
7582         2015
7583         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7584  Flight7585  42259  ORD-LAX              3.0          42
7585  Flight7586  41966  ORD-BOS              1.9          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7584             0.625000               350       57750             9
7585             0.708333               300       54300            11

      Flight Year
7584         2015
7585         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7586  Flight7587  42233  ORD-SEA              2.9          92
7587  Flight7588  41682  ORD-DTW              3.0         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7586             0.333333               385       71225             8
7587             0.291667               115       21275             2

      Flight Year
7586         2015
7587         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7588  Flight7589  42331  ORD-MCO              7.0          99
7589  Flight7590  42205  ORD-PHX              1.2          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7588             0.708333               375       69375            11
7589             0.791667               275       49775             7

      Flight Year
7588         2015
7589         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7590  Flight7591  41791  ORD-PHX              1.7          68
7591  Flight7592  42315  ORD-FLL              2.1          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7590             0.291667               275       49775             6
7591             0.750000               300       55500            11

      Flight Year
7590         2014
7591         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7592  Flight7593  42301  ORD-DTW              1.5         160
7593  Flight7594  41850  ORD-LAX              5.6         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7592             0.312500               115       18975            10
7593             0.791667               385       63525             7

      Flight Year
7592         2015
7593         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7594  Flight7595  42359  ORD-PHX              4.2          80
7595  Flight7596  41818  ORD-DEN              2.0          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7594             0.312500               350       63350            12
7595             0.666667               330       61050             6

      Flight Year
7594         2015
7595         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7596  Flight7597  41662  ORD-FLL              1.6         147
7597  Flight7598  41972  ORD-SFO              4.7         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7596             0.395833             300.0     55500.0             1
7597             0.666667             562.5    104062.5            11

      Flight Year
7596         2014
7597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7598  Flight7599  41705  ORD-SFO              0.8         132
7599  Flight7600  41835  ORD-ATL             10.7         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7598             0.708333               375       69375             3
7599             0.541667               220       40700             7

      Flight Year
7598         2014
7599         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7600  Flight7601  42337  ORD-MSP              3.9          41
7601  Flight7602  41864  ORD-LGA              1.1         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7600             0.291667             172.5     28462.5            11
7601             0.625000             302.5     49912.5             8

      Flight Year
7600         2015
7601         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7602  Flight7603  41725  ORD-CLT              1.7          85
7603  Flight7604  42021  ORD-ATL             12.6         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7602             0.791667               125       22625             3
7603             0.708333               200       37000             1

      Flight Year
7602         2014
7603         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7604  Flight7605  42331  ORD-EWR              3.7         120
7605  Flight7606  41664  ORD-DTW              2.0          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7604             0.312500             337.5     62437.5            11
7605             0.354167             115.0     20815.0             1

      Flight Year
7604         2015
7605         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7606  Flight7607  42157  ORD-LGA              1.8          99
7607  Flight7608  41886  ORD-DEN              1.9         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7606             0.791667             302.5     55962.5             6
7607             0.625000             300.0     49500.0             9

      Flight Year
7606         2015
7607         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7608  Flight7609  41989  ORD-DTW              3.1         193
7609  Flight7610  41927  ORD-MSP              0.2         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7608             0.354167               115       18975            12
7609             0.520833               115       21275            10

      Flight Year
7608         2014
7609         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7610  Flight7611  41709  ORD-MCO              2.9         123
7611  Flight7612  42252  ORD-DEN              2.7         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7610             0.416667               250       46250             3
7611             0.791667               300       49500             9

      Flight Year
7610         2014
7611         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7612  Flight7613  42010  ORD-MSP              1.8         133
7613  Flight7614  42249  ORD-MIA              2.7         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7612             0.791667               115       21275             1
7613             0.708333               300       55500             9

      Flight Year
7612         2015
7613         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7614  Flight7615  41729  ORD-MIA              1.7          62
7615  Flight7616  41683  ORD-DFW              2.2         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7614             0.333333               300       49500             3
7615             0.708333               200       37000             2

      Flight Year
7614         2014
7615         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7616  Flight7617  41905  ORD-PHX              1.6         178
7617  Flight7618  41707  ORD-IAH              2.6          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7616             0.729167               250       41250             9
7617             0.708333               200       33000             3

      Flight Year
7616         2014
7617         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7618  Flight7619  41742  ORD-LAX              3.1           9
7619  Flight7620  42193  ORD-SEA              0.8         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7618             0.729167               350       64750             4
7619             0.645833               385       71225             7

      Flight Year
7618         2014
7619         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7620  Flight7621  42016  ORD-JFK              2.4         188
7621  Flight7622  42168  ORD-MCO              1.3         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7620             0.416667               250       41250             1
7621             0.812500               275       50875             6

      Flight Year
7620         2015
7621         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7622  Flight7623  41661  ORD-LGA              0.8          89
7623  Flight7624  41761  ORD-DTW              1.3         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7622             0.645833               275       49775             1
7623             0.291667               115       18975             5

      Flight Year
7622         2014
7623         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7624  Flight7625  41974  ORD-BOS              1.5         130
7625  Flight7626  41990  ORD-DEN              0.9          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7624             0.541667               300       55500            12
7625             0.625000               300       55500            12

      Flight Year
7624         2014
7625         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7626  Flight7627  42337  ORD-LAX             10.4          21
7627  Flight7628  42151  ORD-SFO              1.1          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7626             0.708333               525       97125            11
7627             0.625000               375       67875             5

      Flight Year
7626         2015
7627         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7628  Flight7629  41821  ORD-IAD              1.0         209
7629  Flight7630  42159  ORD-PHL              1.6          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7628             0.458333             330.0     54450.0             7
7629             0.291667             302.5     55962.5             6

      Flight Year
7628         2014
7629         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7630  Flight7631  41761  ORD-ATL              7.3          85
7631  Flight7632  42166  ORD-SFO              1.4         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7630             0.333333             200.0     36200.0             5
7631             0.375000             412.5     68062.5             6

      Flight Year
7630         2014
7631         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7632  Flight7633  41871  ORD-LAS              1.9          60
7633  Flight7634  41970  ORD-MSP              2.6          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7632             0.729167             302.5     49912.5             8
7633             0.416667             172.5     31912.5            11

      Flight Year
7632         2014
7633         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7634  Flight7635  41819  ORD-LAX              5.5          50
7635  Flight7636  42185  ORD-LAS              2.6          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7634             0.416667             385.0     63525.0             6
7635             0.291667             302.5     49912.5             6

      Flight Year
7634         2014
7635         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7636  Flight7637  42301  ORD-MIA              2.0          18
7637  Flight7638  42016  ORD-PHX              1.3          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7636             0.791667               300       55500            10
7637             0.645833               250       46250             1

      Flight Year
7636         2015
7637         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7638  Flight7639  41768  ORD-SFO              2.2          46
7639  Flight7640  41662  ORD-EWR              2.6         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7638             0.791667               375       61875             5
7639             0.625000               225       37125             1

      Flight Year
7638         2014
7639         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7640  Flight7641  41843  ORD-JFK              1.5         192
7641  Flight7642  41730  ORD-CLT              1.6          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7640             0.750000               275       45375             7
7641             0.708333               125       22625             4

      Flight Year
7640         2014
7641         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7642  Flight7643  41967  ORD-LAX             10.0          83
7643  Flight7644  42148  ORD-ATL             10.8         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7642             0.750000               525       95025            11
7643             0.291667               200       33000             5

      Flight Year
7642         2014
7643         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7644  Flight7645  41865  ORD-BOS              1.5         193
7645  Flight7646  41680  ORD-DFW              2.3         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7644             0.854167               330       54450             8
7645             0.854167               200       33000             2

      Flight Year
7644         2014
7645         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7646  Flight7647  41925  ORD-LGA              1.8          57
7647  Flight7648  41848  ORD-DTW              2.7          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7646             0.291667             275.0     45375.0            10
7647             0.395833             126.5     23402.5             7

      Flight Year
7646         2014
7647         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7648  Flight7649  41833  ORD-SFO              1.6          92
7649  Flight7650  42351  ORD-LAS              1.5         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7648             0.604167             412.5     76312.5             7
7649             0.666667             275.0     45375.0            12

      Flight Year
7648         2014
7649         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7650  Flight7651  42264  ORD-MIA              2.6         167
7651  Flight7652  42244  ORD-EWR              1.3          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7650             0.750000             300.0     49500.0             9
7651             0.791667             247.5     44797.5             8

      Flight Year
7650         2015
7651         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7652  Flight7653  42329  ORD-SFO              1.7          11
7653  Flight7654  42159  ORD-IAH              1.5          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7652             0.833333               375       69375            11
7653             0.750000               220       40700             6

      Flight Year
7652         2015
7653         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7654  Flight7655  42213  ORD-SEA              2.2          99
7655  Flight7656  41677  ORD-MCO              2.8         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7654             0.833333               385       71225             7
7655             0.708333               250       46250             2

      Flight Year
7654         2015
7655         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7656  Flight7657  41896  ORD-LAX              5.2         195
7657  Flight7658  41709  ORD-SEA              1.9          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7656             0.895833               350       57750             9
7657             0.291667               350       63350             3

      Flight Year
7656         2014
7657         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7658  Flight7659  41862  ORD-LAX              6.1           5
7659  Flight7660  41998  ORD-LAX             10.1         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7658             0.812500               385       71225             8
7659             0.333333               490       90650            12

      Flight Year
7658         2014
7659         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7660  Flight7661  41667  ORD-JFK              1.2          76
7661  Flight7662  42232  ORD-SFO              2.3         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7660             0.708333             250.0     45250.0             1
7661             0.583333             412.5     68062.5             8

      Flight Year
7660         2014
7661         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7662  Flight7663  42157  ORD-SEA              3.3         189
7663  Flight7664  41658  ORD-CLT              1.0          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7662               0.7500               385       63525             6
7663               0.8125               125       22625             1

      Flight Year
7662         2015
7663         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7664  Flight7665  42187  ORD-SFO              1.8          13
7665  Flight7666  42158  ORD-DEN              2.2          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7664               0.7500             412.5     76312.5             7
7665               0.3125             330.0     54450.0             6

      Flight Year
7664         2015
7665         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7666  Flight7667  41893  ORD-PHX              2.5         100
7667  Flight7668  41872  ORD-CLT              3.3           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7666             0.875000             250.0     46250.0             9
7667             0.791667             137.5     25437.5             8

      Flight Year
7666         2014
7667         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7668  Flight7669  41875  ORD-LAX              4.0         141
7669  Flight7670  42298  ORD-LAS              2.1         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7668             0.333333               385       71225             8
7669             0.833333               275       45375            10

      Flight Year
7668         2014
7669         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7670  Flight7671  41808  ORD-CLT              3.4         125
7671  Flight7672  42234  ORD-BOS              1.6          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7670             0.333333             137.5     25437.5             6
7671             0.729167             330.0     54450.0             8

      Flight Year
7670         2014
7671         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7672  Flight7673  41818  ORD-DTW              1.1          89
7673  Flight7674  42014  ORD-CLT              1.9          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7672             0.854167             126.5     22896.5             6
7673             0.791667             125.0     20625.0             1

      Flight Year
7672         2014
7673         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7674  Flight7675  41731  ORD-BOS              2.5          34
7675  Flight7676  42145  ORD-MIA              1.8         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7674               0.7500               300       55500             4
7675               0.6875               300       49500             5

      Flight Year
7674         2014
7675         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7676  Flight7677  42365  ORD-LAS              2.7          97
7677  Flight7678  42178  ORD-SEA              1.2         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7676             0.791667               385       71225            12
7677             0.354167               385       71225             6

      Flight Year
7676         2015
7677         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7678  Flight7679  42009  ORD-LAS              2.4         111
7679  Flight7680  41975  ORD-PHL              2.7          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7678                 0.75               275       50875             1
7679                 0.50               275       49775            12

      Flight Year
7678         2015
7679         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7680  Flight7681  41906  ORD-BOS              2.6         143
7681  Flight7682  41737  ORD-CLT              2.4         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7680               0.8125               300       55500             9
7681               0.3125               125       20625             4

      Flight Year
7680         2014
7681         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7682  Flight7683  41901  ORD-CLT              1.6         201
7683  Flight7684  42315  ORD-BOS              1.0         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7682             0.541667               125       20625             9
7683             0.333333               300       49500            11

      Flight Year
7682         2014
7683         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7684  Flight7685  41717  ORD-MCO              2.0          12
7685  Flight7686  41909  ORD-JFK              3.5         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7684             0.708333               250       46250             3
7685             0.708333               250       41250             9

      Flight Year
7684         2014
7685         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7686  Flight7687  42316  ORD-SFO              2.1         112
7687  Flight7688  42274  ORD-ATL             11.3          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7686             0.729167               375       69375            11
7687             0.458333               200       37000             9

      Flight Year
7686         2015
7687         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7688  Flight7689  41959  ORD-PHL              3.9         188
7689  Flight7690  42153  ORD-DEN              2.4         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7688             0.708333               275       45375            11
7689             0.333333               300       49500             5

      Flight Year
7688         2014
7689         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7690  Flight7691  41699  ORD-LAX              4.5         187
7691  Flight7692  41852  ORD-DFW              2.9          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7690             0.666667               350       57750             3
7691             0.708333               220       36300             8

      Flight Year
7690         2014
7691         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7692  Flight7693  42075  ORD-ATL              9.3         105
7693  Flight7694  41822  ORD-SEA              1.6          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7692             0.750000               200       37000             3
7693             0.291667               385       63525             7

      Flight Year
7692         2015
7693         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7694  Flight7695  41954  ORD-SFO              2.9         197
7695  Flight7696  41698  ORD-JFK              1.6          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7694             0.291667               375       61875            11
7695             0.708333               250       41250             2

      Flight Year
7694         2014
7695         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7696  Flight7697  42317  ORD-PHX              1.9         121
7697  Flight7698  41693  ORD-ATL              9.1          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7696             0.833333               250       46250            11
7697             0.291667               200       37000             2

      Flight Year
7696         2015
7697         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7698  Flight7699  41710  ORD-SFO              0.5          85
7699  Flight7700  41717  ORD-FLL              1.8         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7698             0.583333               375       67875             3
7699             0.750000               300       49500             3

      Flight Year
7698         2014
7699         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7700  Flight7701  41895  ORD-BOS              2.7          66
7701  Flight7702  41796  ORD-JFK              2.3         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7700             0.770833               300       54300             9
7701             0.770833               275       45375             6

      Flight Year
7700         2014
7701         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7702  Flight7703  42287  ORD-LAX              3.7         210
7703  Flight7704  41965  ORD-JFK              1.1          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7702             0.437500               350       57750            10
7703             0.583333               250       46250            11

      Flight Year
7702         2015
7703         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7704  Flight7705  41729  ORD-SEA              1.8          98
7705  Flight7706  42038  ORD-BWI              1.7         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7704             0.479167               350       64750             3
7705             0.708333               240       44400             2

      Flight Year
7704         2014
7705         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7706  Flight7707  41834  ORD-PHX              0.6          65
7707  Flight7708  42020  ORD-LAS              2.7         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7706             0.750000               275       49775             7
7707             0.791667               275       50875             1

      Flight Year
7706         2014
7707         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7708  Flight7709  42324  ORD-DFW              0.3         187
7709  Flight7710  42336  ORD-EWR              4.6          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7708             0.812500             200.0     33000.0            11
7709             0.583333             337.5     55687.5            11

      Flight Year
7708         2015
7709         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7710  Flight7711  42312  ORD-LAX              2.3         108
7711  Flight7712  42237  ORD-DEN              3.4         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7710             0.854167               350       64750            11
7711             0.291667               330       61050             8

      Flight Year
7710         2015
7711         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7712  Flight7713  42174  ORD-EWR              3.7         119
7713  Flight7714  41755  ORD-PHX              2.5          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7712             0.291667             247.5     45787.5             6
7713             0.833333             250.0     45250.0             4

      Flight Year
7712         2015
7713         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7714  Flight7715  41713  ORD-MIA              1.0         172
7715  Flight7716  41894  ORD-DTW              2.1          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7714             0.625000               300       49500             3
7715             0.666667               115       20815             9

      Flight Year
7714         2014
7715         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7716  Flight7717  42102  ORD-EWR              1.5          10
7717  Flight7718  41944  ORD-SFO              2.1         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7716             0.750000               225       41625             4
7717             0.791667               375       69375            11

      Flight Year
7716         2015
7717         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7718  Flight7719  41731  ORD-SFO              2.4         122
7719  Flight7720  41761  ORD-LAX              3.3          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7718             0.291667               375       69375             4
7719             0.416667               350       64750             5

      Flight Year
7718         2014
7719         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7720  Flight7721  42189  ORD-MIA              2.2         198
7721  Flight7722  42190  ORD-SEA              1.7         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7720             0.708333               330       54450             7
7721             0.729167               385       71225             7

      Flight Year
7720         2015
7721         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7722  Flight7723  41958  ORD-LAS              1.5          40
7723  Flight7724  42186  ORD-IAH              1.4         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7722             0.416667               275       45375            11
7723             0.791667               220       40700             7

      Flight Year
7722         2014
7723         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7724  Flight7725  41795  ORD-SFO              2.6          72
7725  Flight7726  41821  ORD-DEN              1.4          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7724             0.458333             412.5     74662.5             6
7725             0.708333             330.0     59730.0             7

      Flight Year
7724         2014
7725         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7726  Flight7727  41918  ORD-IAH              2.6          35
7727  Flight7728  41849  ORD-DTW              2.5         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7726                0.625             200.0     37000.0            10
7727                0.750             126.5     20872.5             7

      Flight Year
7726         2014
7727         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7728  Flight7729  42055  ORD-SEA              1.6          63
7729  Flight7730  42031  ORD-IAD              2.1          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7728             0.729167               350       63350             2
7729             0.812500               300       55500             1

      Flight Year
7728         2015
7729         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7730  Flight7731  42196  ORD-JFK              1.2         113
7731  Flight7732  42346  ORD-LAX              5.4         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7730             0.500000               275       50875             7
7731             0.291667               350       57750            12

      Flight Year
7730         2015
7731         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7732  Flight7733  41773  ORD-DEN              1.9         142
7733  Flight7734  42203  ORD-DTW              2.1         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7732             0.875000             300.0     55500.0             5
7733             0.291667             126.5     23402.5             7

      Flight Year
7732         2014
7733         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7734  Flight7735  41779  ORD-DFW              2.6          45
7735  Flight7736  41748  ORD-DEN              3.0         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7734                0.625               200       33000             5
7735                0.750               300       49500             4

      Flight Year
7734         2014
7735         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7736  Flight7737  42027  ORD-LGA              2.1          47
7737  Flight7738  41742  ORD-BOS              3.9          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7736             0.770833               275       45375             1
7737             0.708333               300       49500             4

      Flight Year
7736         2015
7737         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7738  Flight7739  42103  ORD-MIA              1.4         103
7739  Flight7740  42296  ORD-CLT              2.8          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7738             0.291667               300       55500             4
7739             0.333333               125       23125            10

      Flight Year
7738         2015
7739         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7740  Flight7741  41973  ORD-DEN              3.3         149
7741  Flight7742  41970  ORD-SFO              7.2         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7740             0.333333             450.0     83250.0            11
7741             0.291667             562.5    104062.5            11

      Flight Year
7740         2014
7741         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7742  Flight7743  41850  ORD-DEN              1.7         140
7743  Flight7744  42098  ORD-LAX              4.7         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7742             0.625000               330       61050             7
7743             0.791667               350       57750             4

      Flight Year
7742         2014
7743         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7744  Flight7745  41951  ORD-LAS              1.3         110
7745  Flight7746  41806  ORD-IAH              1.4         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7744             0.500000               275       50875            11
7745             0.541667               220       40700             6

      Flight Year
7744         2014
7745         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7746  Flight7747  42183  ORD-DEN              2.4          21
7747  Flight7748  42239  ORD-DEN              0.8         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7746             0.333333               330       61050             6
7747             0.375000               330       54450             8

      Flight Year
7746         2015
7747         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7748  Flight7749  41844  ORD-DFW              1.6         122
7749  Flight7750  42169  ORD-SEA              1.1          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7748             0.291667               220       40700             7
7749             0.312500               385       69685             6

      Flight Year
7748         2014
7749         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7750  Flight7751  42063  ORD-PHL              2.1           5
7751  Flight7752  42193  ORD-JFK              0.7         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7750             0.770833               275       50875             2
7751             0.354167               275       45375             7

      Flight Year
7750         2015
7751         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7752  Flight7753  41853  ORD-DTW              2.5          42
7753  Flight7754  41945  ORD-CLT              2.2         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7752             0.812500             126.5     20872.5             8
7753             0.895833             125.0     20625.0            11

      Flight Year
7752         2014
7753         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7754  Flight7755  41876  ORD-EWR              1.5          77
7755  Flight7756  42161  ORD-ATL             11.1           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7754             0.291667             247.5     44797.5             8
7755             0.333333             220.0     40700.0             6

      Flight Year
7754         2014
7755         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7756  Flight7757  41845  ORD-MSP              2.1          19
7757  Flight7758  41851  ORD-DEN              1.6         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7756             0.437500             126.5     23402.5             7
7757             0.666667             330.0     54450.0             7

      Flight Year
7756         2014
7757         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7758  Flight7759  41765  ORD-PHL              1.4         120
7759  Flight7760  42321  ORD-CLT              1.2          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7758             0.583333               275       50875             5
7759             0.541667               125       20625            11

      Flight Year
7758         2014
7759         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7760  Flight7761  42196  ORD-BOS              1.1          75
7761  Flight7762  42206  ORD-BOS              2.2         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7760             0.750000               330       59730             7
7761             0.791667               330       61050             7

      Flight Year
7760         2015
7761         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7762  Flight7763  41967  ORD-SEA              2.4          13
7763  Flight7764  41808  ORD-BOS              2.8          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7762             0.666667               525       97125            11
7763             0.333333               330       61050             6

      Flight Year
7762         2014
7763         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7764  Flight7765  42294  ORD-PHL              1.7         148
7765  Flight7766  41754  ORD-IAD              3.4          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7764             0.875000               275       50875            10
7765             0.666667               300       54300             4

      Flight Year
7764         2015
7765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7766  Flight7767  41873  ORD-EWR              1.9          43
7767  Flight7768  41660  ORD-ATL              6.6         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7766             0.791667             247.5     40837.5             8
7767             0.625000             200.0     33000.0             1

      Flight Year
7766         2014
7767         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7768  Flight7769  42324  ORD-ATL              7.9          24
7769  Flight7770  41795  ORD-ATL             11.1         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7768             0.291667               200       37000            11
7769             0.750000               220       40700             6

      Flight Year
7768         2015
7769         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7770  Flight7771  41648  ORD-IAH              1.8          23
7771  Flight7772  42137  ORD-EWR              1.6         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7770             0.791667               200       37000             1
7771             0.791667               225       41625             5

      Flight Year
7770         2014
7771         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7772  Flight7773  41828  ORD-JFK              3.0          93
7773  Flight7774  42207  ORD-SFO              2.8         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7772             0.729167             275.0     50875.0             7
7773             0.437500             412.5     68062.5             7

      Flight Year
7772         2014
7773         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7774  Flight7775  42088  ORD-IAH              3.2         129
7775  Flight7776  42206  ORD-LAS              2.3         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7774             0.395833             200.0     37000.0             3
7775             0.375000             302.5     49912.5             7

      Flight Year
7774         2015
7775         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7776  Flight7777  42151  ORD-BOS              2.8           8
7777  Flight7778  41661  ORD-JFK              2.2          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7776             0.291667               300       55500             5
7777             0.333333               250       45250             1

      Flight Year
7776         2015
7777         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7778  Flight7779  41812  ORD-DTW              0.5          57
7779  Flight7780  41838  ORD-BOS              0.9          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7778             0.312500             126.5     20872.5             6
7779             0.333333             330.0     59730.0             7

      Flight Year
7778         2014
7779         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7780  Flight7781  41705  ORD-CLT             -0.6          68
7781  Flight7782  42286  ORD-PHL              3.4         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7780             0.687500               125       22625             3
7781             0.708333               275       50875            10

      Flight Year
7780         2014
7781         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7782  Flight7783  41650  ORD-DFW              3.8          20
7783  Flight7784  42329  ORD-EWR              2.9          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7782             0.333333               200       37000             1
7783             0.458333               225       40725            11

      Flight Year
7782         2014
7783         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7784  Flight7785  41745  ORD-DFW              3.8          78
7785  Flight7786  41833  ORD-CLT              3.7         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7784             0.541667             200.0     36200.0             4
7785             0.833333             137.5     22687.5             7

      Flight Year
7784         2014
7785         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7786  Flight7787  42351  ORD-PHL              0.6         206
7787  Flight7788  41990  ORD-MIA              2.3         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7786             0.437500               275       45375            12
7787             0.770833               300       55500            12

      Flight Year
7786         2015
7787         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7788  Flight7789  42164  ORD-JFK              0.2         107
7789  Flight7790  42193  ORD-PHX              2.7          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7788             0.291667               275       50875             6
7789             0.291667               275       49775             7

      Flight Year
7788         2015
7789         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7790  Flight7791  42196  ORD-SEA              1.4          41
7791  Flight7792  41790  ORD-BOS              0.9         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7790             0.833333               385       63525             7
7791             0.500000               300       55500             5

      Flight Year
7790         2015
7791         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7792  Flight7793  41777  ORD-SEA              1.7          50
7793  Flight7794  41662  ORD-JFK              2.3         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7792             0.541667               350       57750             5
7793             0.500000               250       46250             1

      Flight Year
7792         2014
7793         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7794  Flight7795  41953  ORD-JFK              2.5         118
7795  Flight7796  42193  ORD-MSP              2.1         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7794             0.750000             250.0     46250.0            11
7795             0.791667             126.5     20872.5             7

      Flight Year
7794         2014
7795         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7796  Flight7797  42325  ORD-LAS              2.5           4
7797  Flight7798  42335  ORD-LGA              5.5         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7796             0.333333             275.0     50875.0            11
7797             0.666667             412.5     68062.5            11

      Flight Year
7796         2015
7797         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7798  Flight7799  42045  ORD-MSP              2.9          54
7799  Flight7800  42223  ORD-CLT              3.5         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7798             0.833333             115.0     18975.0             2
7799             0.750000             137.5     25437.5             8

      Flight Year
7798         2015
7799         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7800  Flight7801  42050  ORD-LAX              4.6          18
7801  Flight7802  42119  ORD-DFW              2.7         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7800             0.354167               350       64750             2
7801             0.833333               200       33000             4

      Flight Year
7800         2015
7801         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7802  Flight7803  41878  ORD-IAH              2.7         152
7803  Flight7804  41929  ORD-IAH              3.3          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7802             0.291667               220       36300             8
7803             0.875000               200       36200            10

      Flight Year
7802         2014
7803         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7804  Flight7805  42328  ORD-SFO              3.0           1
7805  Flight7806  41819  ORD-SFO              2.6         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7804             0.729167             375.0     69375.0            11
7805             0.812500             412.5     76312.5             6

      Flight Year
7804         2015
7805         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7806  Flight7807  41991  ORD-SFO              1.9          58
7807  Flight7808  42059  ORD-MIA              2.1         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7806             0.750000               375       61875            12
7807             0.708333               300       49500             2

      Flight Year
7806         2014
7807         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7808  Flight7809  41668  ORD-SFO              2.1          98
7809  Flight7810  41858  ORD-DFW              1.9          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7808             0.333333               375       69375             1
7809             0.291667               220       36300             8

      Flight Year
7808         2014
7809         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7810  Flight7811  41918  ORD-SEA              3.6         137
7811  Flight7812  41658  ORD-DTW              1.7         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7810             0.708333               350       64750            10
7811             0.687500               115       18975             1

      Flight Year
7810         2014
7811         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7812  Flight7813  41826  ORD-FLL              2.7          96
7813  Flight7814  41881  ORD-JFK              1.3          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7812             0.625000               330       61050             7
7813             0.291667               275       49775             8

      Flight Year
7812         2014
7813         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7814  Flight7815  42325  ORD-DEN              3.3          97
7815  Flight7816  42255  ORD-DFW              3.0         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7814             0.541667               300       55500            11
7815             0.875000               200       37000             9

      Flight Year
7814         2015
7815         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7816  Flight7817  41812  ORD-PHL              1.5          11
7817  Flight7818  41808  ORD-PHX              2.8         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7816               0.4375             302.5     55962.5             6
7817               0.6250             275.0     50875.0             6

      Flight Year
7816         2014
7817         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7818  Flight7819  41705  ORD-EWR              0.5         121
7819  Flight7820  42114  ORD-CLT              1.7         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7818             0.416667               225       41625             3
7819             0.729167               125       20625             4

      Flight Year
7818         2014
7819         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7820  Flight7821  41956  ORD-SFO              2.7         118
7821  Flight7822  41859  ORD-EWR              2.0          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7820             0.541667             375.0     69375.0            11
7821             0.645833             247.5     45787.5             8

      Flight Year
7820         2014
7821         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7822  Flight7823  42179  ORD-DEN              1.9         181
7823  Flight7824  41955  ORD-ATL              9.7         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7822             0.729167               330       54450             6
7823             0.791667               200       33000            11

      Flight Year
7822         2015
7823         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7824  Flight7825  41770  ORD-MSP              2.1         126
7825  Flight7826  41699  ORD-PHX              1.2          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7824             0.812500               115       21275             5
7825             0.791667               250       41250             3

      Flight Year
7824         2014
7825         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7826  Flight7827  42149  ORD-MSP              2.3          28
7827  Flight7828  42222  ORD-PHL              1.4         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7826             0.770833             115.0     21275.0             5
7827             0.750000             302.5     55962.5             8

      Flight Year
7826         2015
7827         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7828  Flight7829  42027  ORD-PHX              2.7          22
7829  Flight7830  41952  ORD-PHL              1.0          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7828             0.291667               250       46250             1
7829             0.291667               275       45375            11

      Flight Year
7828         2015
7829         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7830  Flight7831  42183  ORD-SFO              1.6         167
7831  Flight7832  42034  ORD-LAS              2.3          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7830             0.416667             412.5     68062.5             6
7831             0.291667             275.0     50875.0             1

      Flight Year
7830         2015
7831         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7832  Flight7833  41769  ORD-DEN              1.5         122
7833  Flight7834  42217  ORD-MCO              1.9         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7832             0.604167               300       55500             5
7833             0.791667               275       45375             8

      Flight Year
7832         2014
7833         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7834  Flight7835  42032  ORD-MIA              1.3         132
7835  Flight7836  41765  ORD-SFO              1.5          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7834               0.8750               300       55500             1
7835               0.3125               375       61875             5

      Flight Year
7834         2015
7835         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7836  Flight7837  41842  ORD-MSP              0.3         183
7837  Flight7838  41654  ORD-IAH              0.9         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7836             0.791667             126.5     20872.5             7
7837             0.791667             200.0     33000.0             1

      Flight Year
7836         2014
7837         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7838  Flight7839  42030  ORD-DEN              2.7          35
7839  Flight7840  42087  ORD-DTW              1.7         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7838             0.833333               300       55500             1
7839             0.791667               115       18975             3

      Flight Year
7838         2015
7839         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7840  Flight7841  41970  ORD-SFO              7.4         147
7841  Flight7842  41770  ORD-PHX             -0.1         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7840             0.666667             562.5    104062.5            11
7841             0.645833             250.0     46250.0             5

      Flight Year
7840         2014
7841         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7842  Flight7843  42073  ORD-CLT                2         142
7843  Flight7844  41878  ORD-SEA                2         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7842             0.708333               125       23125             3
7843             0.812500               385       71225             8

      Flight Year
7842         2015
7843         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7844  Flight7845  42287  ORD-IAH              2.4         146
7845  Flight7846  41804  ORD-MSP              2.9         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7844             0.791667             200.0     37000.0            10
7845             0.708333             126.5     23402.5             6

      Flight Year
7844         2015
7845         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7846  Flight7847  41695  ORD-DTW              2.4          80
7847  Flight7848  41641  ORD-DTW              1.8         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7846             0.645833               115       20815             2
7847             0.729167               115       18975             1

      Flight Year
7846         2014
7847         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7848  Flight7849  41666  ORD-IAH              2.1          14
7849  Flight7850  42044  ORD-CLT              1.6         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7848             0.500000               200       37000             1
7849             0.541667               125       20625             2

      Flight Year
7848         2014
7849         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7850  Flight7851  41934  ORD-DTW              2.4          81
7851  Flight7852  42231  ORD-DFW              0.6         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7850             0.395833               115       20815            10
7851             0.562500               220       36300             8

      Flight Year
7850         2014
7851         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7852  Flight7853  42293  ORD-JFK              2.0          20
7853  Flight7854  41732  ORD-LAX              5.1         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7852                 0.75               250       46250            10
7853                 0.75               350       64750             4

      Flight Year
7852         2015
7853         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7854  Flight7855  42256  ORD-PHL              1.6          74
7855  Flight7856  41998  ORD-DFW              3.4         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7854             0.583333               275       49775             9
7855             0.895833               280       46200            12

      Flight Year
7854         2015
7855         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7856  Flight7857  42298  ORD-LAS              0.7         172
7857  Flight7858  42234  ORD-MSP              2.3         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7856             0.708333             275.0     45375.0            10
7857             0.708333             126.5     23402.5             8

      Flight Year
7856         2015
7857         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7858  Flight7859  42335  ORD-DEN              5.8          49
7859  Flight7860  41939  ORD-JFK              3.7          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7858             0.791667               450       74250            11
7859             0.458333               250       46250            10

      Flight Year
7858         2015
7859         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7860  Flight7861  42175  ORD-JFK              2.8          59
7861  Flight7862  41741  ORD-MIA              1.2         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7860                0.625               275       45375             6
7861                0.375               300       55500             4

      Flight Year
7860         2015
7861         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7862  Flight7863  42287  ORD-JFK              2.5         161
7863  Flight7864  41845  ORD-SFO              2.4          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7862             0.333333             250.0     41250.0            10
7863             0.833333             412.5     74662.5             7

      Flight Year
7862         2015
7863         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7864  Flight7865  41746  ORD-DTW              1.3         115
7865  Flight7866  42163  ORD-FLL              3.4           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7864               0.3125               115       21275             4
7865               0.7500               330       61050             6

      Flight Year
7864         2014
7865         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7866  Flight7867  41713  ORD-SFO              2.1          97
7867  Flight7868  41913  ORD-ATL             10.8           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7866             0.708333               375       69375             3
7867             0.708333               200       37000            10

      Flight Year
7866         2014
7867         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7868  Flight7869  41769  ORD-EWR              1.9          44
7869  Flight7870  41969  ORD-PHX              5.2          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7868             0.791667               225       37125             5
7869             0.375000               375       69375            11

      Flight Year
7868         2014
7869         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7870  Flight7871  42359  ORD-PHL              3.0         126
7871  Flight7872  41740  ORD-DEN              1.6         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7870             0.291667               385       71225            12
7871             0.708333               300       49500             4

      Flight Year
7870         2015
7871         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7872  Flight7873  41647  ORD-MSP              0.9          43
7873  Flight7874  41654  ORD-LAX              3.6          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7872             0.333333               115       18975             1
7873             0.333333               350       63350             1

      Flight Year
7872         2014
7873         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7874  Flight7875  41758  ORD-JFK              2.8         113
7875  Flight7876  42001  ORD-DTW              4.2         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7874             0.791667               250       46250             4
7875             0.541667               161       29785            12

      Flight Year
7874         2014
7875         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7876  Flight7877  41676  ORD-LGA              1.3         132
7877  Flight7878  42150  ORD-DEN              1.5          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7876               0.3750               275       50875             2
7877               0.8125               300       55500             5

      Flight Year
7876         2014
7877         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7878  Flight7879  41774  ORD-PHX              1.7         152
7879  Flight7880  42313  ORD-BOS              1.3          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7878             0.437500               250       41250             5
7879             0.416667               300       55500            11

      Flight Year
7878         2014
7879         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7880  Flight7881  41862  ORD-IAH              2.3         208
7881  Flight7882  41869  ORD-ATL              9.3          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7880               0.8125               220       36300             8
7881               0.5000               220       39820             8

      Flight Year
7880         2014
7881         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7882  Flight7883  42268  ORD-BOS              1.6         184
7883  Flight7884  41938  ORD-IAH              3.5         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7882             0.812500               300       49500             9
7883             0.395833               200       37000            10

      Flight Year
7882         2015
7883         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7884  Flight7885  42038  ORD-LAX              5.7          78
7885  Flight7886  41888  ORD-CLT              1.4         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7884             0.791667               350       63350             2
7885             0.312500               125       23125             9

      Flight Year
7884         2015
7885         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7886  Flight7887  41665  ORD-DFW              3.3          48
7887  Flight7888  41934  ORD-DEN              1.8          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7886             0.791667               200       33000             1
7887             0.291667               300       49500            10

      Flight Year
7886         2014
7887         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7888  Flight7889  41893  ORD-MIA              1.6         136
7889  Flight7890  41731  ORD-PHX              2.5          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7888               0.5000               300       55500             9
7889               0.6875               250       45250             4

      Flight Year
7888         2014
7889         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7890  Flight7891  42207  ORD-LAS              2.0         182
7891  Flight7892  41835  ORD-DFW              1.6         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7890             0.333333             302.5     49912.5             7
7891             0.604167             220.0     40700.0             7

      Flight Year
7890         2015
7891         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7892  Flight7893  42260  ORD-JFK              2.1           6
7893  Flight7894  41858  ORD-DFW              2.3           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7892             0.708333               250       46250             9
7893             0.333333               220       40700             8

      Flight Year
7892         2015
7893         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7894  Flight7895  41993  ORD-MIA              0.9          12
7895  Flight7896  41725  ORD-CLT              2.1           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7894             0.416667               300       55500            12
7895             0.812500               125       23125             3

      Flight Year
7894         2014
7895         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7896  Flight7897  41716  ORD-IAH              2.2         206
7897  Flight7898  42360  ORD-LAS              1.5          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7896             0.750000               200       33000             3
7897             0.833333               385       69685            12

      Flight Year
7896         2014
7897         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7898  Flight7899  41993  ORD-LAX              5.2          42
7899  Flight7900  41885  ORD-IAD              1.9          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7898             0.750000               350       57750            12
7899             0.770833               300       54300             9

      Flight Year
7898         2014
7899         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7900  Flight7901  42245  ORD-SEA              1.9          23
7901  Flight7902  42089  ORD-ATL             10.0          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7900             0.812500               385       71225             8
7901             0.291667               200       37000             3

      Flight Year
7900         2015
7901         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7902  Flight7903  41906  ORD-LGA              1.6          93
7903  Flight7904  42173  ORD-MCO              2.0         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7902             0.625000               275       50875             9
7903             0.291667               275       50875             6

      Flight Year
7902         2014
7903         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7904  Flight7905  42337  ORD-LAS              4.7          40
7905  Flight7906  42226  ORD-MIA              1.3         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7904             0.291667             412.5     68062.5            11
7905             0.541667             330.0     61050.0             8

      Flight Year
7904         2015
7905         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7906  Flight7907  41722  ORD-SEA              2.0         112
7907  Flight7908  41797  ORD-BOS              1.1          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7906             0.291667               350       64750             3
7907             0.708333               330       61050             6

      Flight Year
7906         2014
7907         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7908  Flight7909  41793  ORD-JFK              2.1         103
7909  Flight7910  41791  ORD-JFK              2.1         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7908             0.416667               275       50875             6
7909             0.500000               275       45375             6

      Flight Year
7908         2014
7909         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7910  Flight7911  41713  ORD-IAD              2.6         189
7911  Flight7912  41772  ORD-MIA              1.5         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7910             0.354167               300       49500             3
7911             0.812500               300       55500             5

      Flight Year
7910         2014
7911         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7912  Flight7913  41935  ORD-IAH              1.7         139
7913  Flight7914  41830  ORD-PHL              1.3         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7912             0.291667             200.0     37000.0            10
7913             0.708333             302.5     49912.5             7

      Flight Year
7912         2014
7913         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7914  Flight7915  42219  ORD-SFO              2.1          43
7915  Flight7916  42052  ORD-IAH              2.3          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7914             0.708333             412.5     68062.5             8
7915             0.708333             200.0     37000.0             2

      Flight Year
7914         2015
7915         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7916  Flight7917  41858  ORD-FLL              2.5          31
7917  Flight7918  41910  ORD-SEA              3.1         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7916               0.6250               330       61050             8
7917               0.3125               350       64750             9

      Flight Year
7916         2014
7917         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7918  Flight7919  41989  ORD-CLT              2.5         132
7919  Flight7920  42225  ORD-DEN              1.4         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7918             0.562500               125       23125            12
7919             0.791667               330       54450             8

      Flight Year
7918         2014
7919         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7920  Flight7921  41828  ORD-MCO              3.1          23
7921  Flight7922  41832  ORD-DFW              2.7          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7920             0.812500               275       50875             7
7921             0.333333               220       36300             7

      Flight Year
7920         2014
7921         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7922  Flight7923  41819  ORD-LAS              1.6           1
7923  Flight7924  42279  ORD-SEA              2.7          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7922             0.666667             302.5     55962.5             6
7923             0.666667             350.0     63350.0            10

      Flight Year
7922         2014
7923         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7924  Flight7925  42034  ORD-ATL             10.7         116
7925  Flight7926  41803  ORD-DFW              2.8          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7924             0.291667               200       37000             1
7925             0.291667               220       36300             6

      Flight Year
7924         2015
7925         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7926  Flight7927  42160  ORD-JFK              3.3         175
7927  Flight7928  42243  ORD-LAS              0.8         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7926             0.708333             275.0     45375.0             6
7927             0.541667             302.5     49912.5             8

      Flight Year
7926         2015
7927         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7928  Flight7929  42116  ORD-MSP              2.1         112
7929  Flight7930  41708  ORD-SFO              2.3          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7928             0.291667               115       21275             4
7929             0.333333               375       61875             3

      Flight Year
7928         2015
7929         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7930  Flight7931  41737  ORD-PHL              3.8         101
7931  Flight7932  41932  ORD-DEN              0.9           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7930             0.750000               275       50875             4
7931             0.666667               300       55500            10

      Flight Year
7930         2014
7931         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7932  Flight7933  41968  ORD-MIA              7.0          52
7933  Flight7934  41844  ORD-DFW              2.2         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7932             0.291667               450       74250            11
7933             0.875000               220       36300             7

      Flight Year
7932         2014
7933         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7934  Flight7935  41867  ORD-ATL             12.6          48
7935  Flight7936  42000  ORD-PHL              2.9         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7934             0.833333               220       36300             8
7935             0.500000               385       63525            12

      Flight Year
7934         2014
7935         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7936  Flight7937  41792  ORD-JFK              0.8          71
7937  Flight7938  42345  ORD-LGA              0.9         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7936             0.708333               275       49775             6
7937             0.833333               275       45375            12

      Flight Year
7936         2014
7937         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7938  Flight7939  41840  ORD-DFW              2.0         147
7939  Flight7940  41761  ORD-ATL             10.5         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7938             0.833333               220       40700             7
7939             0.416667               200       33000             5

      Flight Year
7938         2014
7939         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7940  Flight7941  42090  ORD-LAX              5.3         141
7941  Flight7942  42220  ORD-MCO              1.4         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7940             0.750000               350       64750             3
7941             0.458333               275       50875             8

      Flight Year
7940         2015
7941         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7942  Flight7943  41809  ORD-LAS              2.3         144
7943  Flight7944  41926  ORD-BWI              2.7         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7942             0.708333             302.5     55962.5             6
7943             0.291667             240.0     44400.0            10

      Flight Year
7942         2014
7943         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7944  Flight7945  42220  ORD-SFO              2.7          84
7945  Flight7946  42231  ORD-LAX              4.7           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7944             0.854167             412.5     74662.5             8
7945             0.791667             385.0     71225.0             8

      Flight Year
7944         2015
7945         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7946  Flight7947  42307  ORD-LGA              3.5         200
7947  Flight7948  41732  ORD-BOS              3.5         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7946             0.541667               275       45375            10
7947             0.354167               300       49500             4

      Flight Year
7946         2015
7947         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7948  Flight7949  42139  ORD-PHX              2.1          40
7949  Flight7950  42201  ORD-LAS              1.4          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7948             0.791667             250.0     41250.0             5
7949             0.791667             302.5     54752.5             7

      Flight Year
7948         2015
7949         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7950  Flight7951  41935  ORD-ATL             11.4          89
7951  Flight7952  41804  ORD-EWR              2.5         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7950             0.750000             200.0     36200.0            10
7951             0.416667             247.5     45787.5             6

      Flight Year
7950         2014
7951         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7952  Flight7953  42093  ORD-MIA              1.0          46
7953  Flight7954  42147  ORD-LGA              1.3         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7952                 0.75               300       49500             3
7953                 0.75               275       50875             5

      Flight Year
7952         2015
7953         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7954  Flight7955  42218  ORD-PHL              2.6         142
7955  Flight7956  42209  ORD-DEN              1.4         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7954             0.895833             302.5     55962.5             8
7955             0.562500             330.0     61050.0             7

      Flight Year
7954         2015
7955         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7956  Flight7957  42331  ORD-PHX              7.3         183
7957  Flight7958  41645  ORD-MCO              2.5          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7956             0.354167               375       61875            11
7957             0.583333               250       45250             1

      Flight Year
7956         2015
7957         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7958  Flight7959  41845  ORD-DFW              2.5          21
7959  Flight7960  42303  ORD-MCO              1.5         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7958             0.666667               220       40700             7
7959             0.541667               250       46250            10

      Flight Year
7958         2014
7959         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7960  Flight7961  42256  ORD-PHL              2.4         155
7961  Flight7962  41658  ORD-FLL              2.2          58

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7960             0.333333               275       45375             9
7961             0.333333               300       49500             1

      Flight Year
7960         2015
7961         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7962  Flight7963  42340  ORD-LAS              0.9          38
7963  Flight7964  42036  ORD-PHX              2.5          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7962             0.770833               275       45375            12
7963             0.750000               250       46250             2

      Flight Year
7962         2015
7963         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7964  Flight7965  42153  ORD-ATL             12.4          16
7965  Flight7966  42342  ORD-SFO              4.0           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7964             0.333333               200       37000             5
7965             0.500000               375       69375            12

      Flight Year
7964         2015
7965         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7966  Flight7967  42290  ORD-PHX              1.8          52
7967  Flight7968  41946  ORD-PHX              0.1          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7966             0.562500               250       41250            10
7967             0.291667               250       41250            11

      Flight Year
7966         2015
7967         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7968  Flight7969  42141  ORD-IAH              1.5         111
7969  Flight7970  42320  ORD-DFW              2.2         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7968             0.333333               200       37000             5
7969             0.750000               200       37000            11

      Flight Year
7968         2015
7969         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7970  Flight7971  41803  ORD-LAX              4.0         128
7971  Flight7972  42308  ORD-LAX              5.2         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7970             0.333333               385       71225             6
7971             0.291667               350       57750            10

      Flight Year
7970         2014
7971         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7972  Flight7973  41905  ORD-ATL              7.8          86
7973  Flight7974  41941  ORD-EWR              2.0          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7972                0.375               200       36200             9
7973                0.875               225       37125            10

      Flight Year
7972         2014
7973         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7974  Flight7975  41729  ORD-MCO              1.9          70
7975  Flight7976  42186  ORD-CLT              2.3         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7974             0.333333             250.0     45250.0             3
7975             0.750000             137.5     22687.5             7

      Flight Year
7974         2014
7975         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7976  Flight7977  41679  ORD-MIA              0.6          31
7977  Flight7978  41729  ORD-LAS              2.9         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7976             0.666667               300       55500             2
7977             0.291667               275       45375             3

      Flight Year
7976         2014
7977         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7978  Flight7979  41733  ORD-DFW              1.7          61
7979  Flight7980  41907  ORD-ATL              4.8         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7978             0.500000               200       33000             4
7979             0.291667               200       37000             9

      Flight Year
7978         2014
7979         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7980  Flight7981  42184  ORD-CLT              2.3          79
7981  Flight7982  41644  ORD-SFO              1.6          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7980             0.333333             137.5     24887.5             6
7981             0.458333             375.0     69375.0             1

      Flight Year
7980         2015
7981         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7982  Flight7983  42229  ORD-PHX              2.2         169
7983  Flight7984  41753  ORD-ATL              8.2          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7982             0.541667               275       45375             8
7983             0.791667               200       36200             4

      Flight Year
7982         2015
7983         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7984  Flight7985  41957  ORD-BOS              2.5          96
7985  Flight7986  41895  ORD-MIA              2.2         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7984                0.625               300       55500            11
7985                0.750               300       49500             9

      Flight Year
7984         2014
7985         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7986  Flight7987  41775  ORD-JFK              2.8          29
7987  Flight7988  41968  ORD-MCO              5.2          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7986             0.854167               250       46250             5
7987             0.291667               375       61875            11

      Flight Year
7986         2014
7987         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7988  Flight7989  41721  ORD-DFW              0.7          92
7989  Flight7990  41901  ORD-SEA              1.2         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7988             0.333333               200       37000             3
7989             0.791667               350       64750             9

      Flight Year
7988         2014
7989         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7990  Flight7991  41863  ORD-SFO              2.3          17
7991  Flight7992  41690  ORD-ATL             10.1         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7990             0.729167             412.5     76312.5             8
7991             0.645833             200.0     33000.0             2

      Flight Year
7990         2014
7991         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7992  Flight7993  41869  ORD-SEA              0.4         188
7993  Flight7994  42283  ORD-MCO              2.4         155

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7992               0.8125               385       63525             8
7993               0.3125               250       41250            10

      Flight Year
7992         2014
7993         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7994  Flight7995  42286  ORD-JFK              1.1           3
7995  Flight7996  41661  ORD-MSP              1.3          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7994             0.333333               250       46250            10
7995             0.354167               115       18975             1

      Flight Year
7994         2015
7995         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7996  Flight7997  42157  ORD-IAH              2.5          13
7997  Flight7998  42160  ORD-SEA              2.0         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7996             0.291667               220       40700             6
7997             0.750000               385       63525             6

      Flight Year
7996         2015
7997         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
7998  Flight7999  42218  ORD-IAH              1.7         121
7999  Flight8000  41866  ORD-DTW              2.1          93

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
7998             0.625000             220.0     40700.0             8
7999             0.291667             126.5     23402.5             8

      Flight Year
7998         2015
7999         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8000  Flight8001  42326  ORD-DTW              2.4          87
8001  Flight8002  42159  ORD-MCO              3.2         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8000             0.791667               115       20815            11
8001             0.854167               275       45375             6

      Flight Year
8000         2015
8001         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8002  Flight8003  41886  ORD-MCO              1.4         122
8003  Flight8004  42053  ORD-LAS              1.2          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8002             0.812500               250       46250             9
8003             0.291667               275       50875             2

      Flight Year
8002         2014
8003         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8004  Flight8005  41713  ORD-DCA              1.5         166
8005  Flight8006  41900  ORD-SFO              1.3         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8004                0.375              5000      825000             3
8005                0.750               375       69375             9

      Flight Year
8004         2014
8005         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8006  Flight8007  42039  ORD-PHX              2.8         143
8007  Flight8008  42199  ORD-ATL              9.4         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8006                0.750               250       46250             2
8007                0.375               220       40700             7

      Flight Year
8006         2015
8007         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8008  Flight8009  42174  ORD-JFK              0.5         107
8009  Flight8010  42313  ORD-CLT              1.7         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8008             0.291667               275       50875             6
8009             0.750000               125       20625            11

      Flight Year
8008         2015
8009         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8010  Flight8011  41736  ORD-DEN              3.4          70
8011  Flight8012  41807  ORD-DTW              2.3          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8010             0.708333             300.0     54300.0             4
8011             0.791667             126.5     23402.5             6

      Flight Year
8010         2014
8011         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8012  Flight8013  42193  ORD-ATL             12.5         192
8013  Flight8014  41759  ORD-EWR              1.5          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8012             0.354167               220       36300             7
8013             0.458333               225       40725             4

      Flight Year
8012         2015
8013         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8014  Flight8015  41966  ORD-SEA              2.4         123
8015  Flight8016  42338  ORD-MIA              3.3          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8014               0.3125               350       64750            11
8015               0.7500               300       55500            11

      Flight Year
8014         2014
8015         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8016  Flight8017  42221  ORD-DFW              2.5         139
8017  Flight8018  42197  ORD-LAX              4.1         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8016                 0.75               220       40700             8
8017                 0.75               385       63525             7

      Flight Year
8016         2015
8017         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8018  Flight8019  42132  ORD-IAH              1.1         174
8019  Flight8020  42267  ORD-LAX              5.7         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8018             0.854167               200       33000             5
8019             0.708333               350       64750             9

      Flight Year
8018         2015
8019         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8020  Flight8021  41983  ORD-MSP              1.9         125
8021  Flight8022  41721  ORD-BOS              2.2         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8020             0.291667               115       21275            12
8021             0.750000               300       55500             3

      Flight Year
8020         2014
8021         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8022  Flight8023  42303  ORD-JFK              0.8          93
8023  Flight8024  41986  ORD-SEA              2.0         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8022             0.833333               250       46250            10
8023             0.812500               350       57750            12

      Flight Year
8022         2015
8023         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8024  Flight8025  42149  ORD-DTW              2.1          82
8025  Flight8026  41702  ORD-ATL              9.1          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8024             0.541667               115       20815             5
8025             0.333333               200       36200             3

      Flight Year
8024         2015
8025         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8026  Flight8027  42174  ORD-BWI              1.9         140
8027  Flight8028  41998  ORD-LAS              3.3          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8026             0.416667               264       48840             6
8027             0.791667               385       63525            12

      Flight Year
8026         2015
8027         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8028  Flight8029  42146  ORD-MIA              3.5         147
8029  Flight8030  41699  ORD-DFW              1.6         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8028                0.750               300       55500             5
8029                0.375               200       33000             3

      Flight Year
8028         2015
8029         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8030  Flight8031  41758  ORD-PHL              2.4         101
8031  Flight8032  41802  ORD-LAX              4.2          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8030             0.750000               275       50875             4
8031             0.791667               385       69685             6

      Flight Year
8030         2014
8031         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8032  Flight8033  42233  ORD-PHX              2.9          77
8033  Flight8034  41945  ORD-SFO              2.7          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8032                0.375               275       49775             8
8033                0.375               375       69375            11

      Flight Year
8032         2015
8033         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8034  Flight8035  41885  ORD-DTW              2.2          26
8035  Flight8036  41677  ORD-JFK              3.4          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8034             0.791667               115       21275             9
8035             0.333333               250       41250             2

      Flight Year
8034         2014
8035         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8036  Flight8037  41829  ORD-JFK              1.0          70
8037  Flight8038  42035  ORD-LAS              2.7         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8036             0.645833               275       49775             7
8037             0.291667               275       50875             1

      Flight Year
8036         2014
8037         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8038  Flight8039  41852  ORD-EWR              0.6         210
8039  Flight8040  42331  ORD-MSP              5.2         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8038                0.500             247.5     40837.5             8
8039                0.625             172.5     31912.5            11

      Flight Year
8038         2014
8039         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8040  Flight8041  42358  ORD-EWR              1.3         159
8041  Flight8042  41992  ORD-LAS              1.4           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8040               0.5625               225       37125            12
8041               0.7500               275       50875            12

      Flight Year
8040         2015
8041         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8042  Flight8043  41824  ORD-JFK              1.7          98
8043  Flight8044  42099  ORD-SEA              2.3         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8042             0.416667               275       50875             7
8043             0.708333               350       57750             4

      Flight Year
8042         2014
8043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8044  Flight8045  42192  ORD-DFW              1.7         173
8045  Flight8046  42315  ORD-SEA              1.7          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8044               0.6250               220       36300             7
8045               0.3125               350       63350            11

      Flight Year
8044         2015
8045         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8046  Flight8047  41812  ORD-LGA              1.3         180
8047  Flight8048  41931  ORD-SEA              2.1         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8046                0.875             302.5     49912.5             6
8047                0.750             350.0     64750.0            10

      Flight Year
8046         2014
8047         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8048  Flight8049  41814  ORD-LAS              2.6          15
8049  Flight8050  41764  ORD-ATL             10.5         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8048             0.333333             302.5     55962.5             6
8049             0.291667             200.0     33000.0             5

      Flight Year
8048         2014
8049         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8050  Flight8051  41659  ORD-BWI              3.8           8
8051  Flight8052  41893  ORD-JFK              2.1          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8050             0.729167               240       44400             1
8051             0.500000               250       46250             9

      Flight Year
8050         2014
8051         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8052  Flight8053  42213  ORD-IAH              2.6         155
8053  Flight8054  42168  ORD-LAS              3.5         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8052             0.291667             220.0     36300.0             7
8053             0.708333             302.5     49912.5             6

      Flight Year
8052         2015
8053         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8054  Flight8055  42368  ORD-PHL              0.6          74
8055  Flight8056  41949  ORD-LGA              0.8          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8054             0.812500               275       49775            12
8055             0.333333               275       50875            11

      Flight Year
8054         2015
8055         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8056  Flight8057  41753  ORD-DEN              4.2          97
8057  Flight8058  41880  ORD-SFO              2.4           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8056             0.583333             300.0     55500.0             4
8057             0.333333             412.5     76312.5             8

      Flight Year
8056         2014
8057         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8058  Flight8059  42245  ORD-PHX              2.8         102
8059  Flight8060  42287  ORD-DTW              2.0          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8058             0.750000               275       50875             8
8059             0.708333               115       18975            10

      Flight Year
8058         2015
8059         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8060  Flight8061  42344  ORD-DTW              2.4          11
8061  Flight8062  41839  ORD-SFO              2.1         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8060             0.895833             115.0     21275.0            12
8061             0.791667             412.5     68062.5             7

      Flight Year
8060         2015
8061         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8062  Flight8063  42262  ORD-PHX              0.7         174
8063  Flight8064  42046  ORD-MIA              0.3           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8062             0.333333               250       41250             9
8063             0.750000               300       55500             2

      Flight Year
8062         2015
8063         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8064  Flight8065  42098  ORD-DTW              1.0          63
8065  Flight8066  41969  ORD-SLC              4.6         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8064             0.729167               115       20815             4
8065             0.812500               435       80475            11

      Flight Year
8064         2015
8065         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8066  Flight8067  41680  ORD-EWR              2.4         101
8067  Flight8068  41875  ORD-EWR              3.2          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8066             0.812500             225.0     41625.0             2
8067             0.770833             247.5     44797.5             8

      Flight Year
8066         2014
8067         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8068  Flight8069  42221  ORD-ATL             11.8           8
8069  Flight8070  41810  ORD-DTW              2.6         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8068             0.791667             220.0     40700.0             8
8069             0.708333             126.5     23402.5             6

      Flight Year
8068         2015
8069         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8070  Flight8071  41988  ORD-FLL              1.9          21
8071  Flight8072  41759  ORD-PHX              1.2         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8070             0.750000               300       55500            12
8071             0.854167               250       46250             4

      Flight Year
8070         2014
8071         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8072  Flight8073  42166  ORD-LAX              4.5         111
8073  Flight8074  42240  ORD-IAH              2.8         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8072             0.458333               385       71225             6
8073             0.333333               220       40700             8

      Flight Year
8072         2015
8073         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8074  Flight8075  42142  ORD-PHX              2.1         188
8075  Flight8076  42167  ORD-DEN              2.5          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8074             0.791667               250       41250             5
8075             0.291667               330       54450             6

      Flight Year
8074         2015
8075         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8076  Flight8077  42242  ORD-SFO              1.7         184
8077  Flight8078  42152  ORD-JFK              2.0          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8076             0.708333             412.5     68062.5             8
8077             0.750000             250.0     45250.0             5

      Flight Year
8076         2015
8077         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8078  Flight8079  42005  ORD-DTW              2.0         156
8079  Flight8080  41858  ORD-LGA              1.2         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8078             0.708333             115.0     18975.0             1
8079             0.395833             302.5     49912.5             8

      Flight Year
8078         2015
8079         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8080  Flight8081  42184  ORD-MCO              1.8         208
8081  Flight8082  41908  ORD-JFK              1.6          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8080             0.708333               275       45375             6
8081             0.625000               250       45250             9

      Flight Year
8080         2015
8081         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8082  Flight8083  41839  ORD-SEA              1.1          18
8083  Flight8084  42255  ORD-LAX              3.5           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8082             0.291667               385       71225             7
8083             0.416667               350       64750             9

      Flight Year
8082         2014
8083         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8084  Flight8085  41992  ORD-JFK              1.7         170
8085  Flight8086  42021  ORD-IAH              2.2          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8084             0.291667               250       41250            12
8085             0.729167               200       37000             1

      Flight Year
8084         2014
8085         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8086  Flight8087  42000  ORD-BOS              4.4         142
8087  Flight8088  41665  ORD-DEN              1.6         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8086             0.791667               420       77700            12
8087             0.666667               300       55500             1

      Flight Year
8086         2014
8087         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8088  Flight8089  42019  ORD-SFO              3.2         165
8089  Flight8090  41875  ORD-SFO              1.2          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8088             0.750000             375.0     61875.0             1
8089             0.333333             412.5     76312.5             8

      Flight Year
8088         2015
8089         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8090  Flight8091  41968  ORD-JFK              2.8          38
8091  Flight8092  42140  ORD-DFW              2.6         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8090             0.500000               375       61875            11
8091             0.833333               200       37000             5

      Flight Year
8090         2014
8091         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8092  Flight8093  42124  ORD-DFW              0.6          22
8093  Flight8094  41817  ORD-MCO             -0.4          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8092             0.354167               200       37000             4
8093             0.812500               275       49775             6

      Flight Year
8092         2015
8093         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8094  Flight8095  41719  ORD-LAS              2.0          69
8095  Flight8096  41958  ORD-LGA              2.4         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8094             0.291667               275       49775             3
8095             0.729167               275       45375            11

      Flight Year
8094         2014
8095         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8096  Flight8097  42203  ORD-EWR              1.6          57
8097  Flight8098  42174  ORD-LGA              2.3          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8096             0.541667             247.5     40837.5             7
8097             0.291667             302.5     55962.5             6

      Flight Year
8096         2015
8097         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8098  Flight8099  42298  ORD-DFW              0.6          83
8099  Flight8100  42023  ORD-DEN              1.8         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8098             0.875000               200       36200            10
8099             0.791667               300       55500             1

      Flight Year
8098         2015
8099         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8100  Flight8101  41939  ORD-JFK              3.4          93
8101  Flight8102  41821  ORD-PHL              1.9          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8100             0.708333             250.0     46250.0            10
8101             0.416667             302.5     55962.5             7

      Flight Year
8100         2014
8101         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8102  Flight8103  41667  ORD-SFO              2.6         167
8103  Flight8104  42069  ORD-BWI              1.7         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8102             0.833333               375       61875             1
8103             0.812500               240       44400             3

      Flight Year
8102         2014
8103         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8104  Flight8105  41892  ORD-DTW              0.6          40
8105  Flight8106  42154  ORD-PHX              2.1          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8104             0.291667               115       18975             9
8105             0.625000               250       46250             5

      Flight Year
8104         2014
8105         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8106  Flight8107  42104  ORD-SEA              1.7          80
8107  Flight8108  41798  ORD-MIA              1.7         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8106             0.750000               350       63350             4
8107             0.333333               330       61050             6

      Flight Year
8106         2015
8107         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8108  Flight8109  42091  ORD-SEA              3.0          74
8109  Flight8110  41969  ORD-CLT              3.3         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8108             0.333333             350.0     63350.0             3
8109             0.854167             187.5     30937.5            11

      Flight Year
8108         2015
8109         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8110  Flight8111  42290  ORD-FLL              1.6          63
8111  Flight8112  41692  ORD-EWR              1.3          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8110             0.625000               300       54300            10
8111             0.395833               225       37125             2

      Flight Year
8110         2015
8111         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8112  Flight8113  41887  ORD-DTW              0.8         162
8113  Flight8114  42287  ORD-DEN              2.4          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8112               0.3125               115       18975             9
8113               0.8125               300       54300            10

      Flight Year
8112         2014
8113         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8114  Flight8115  42369  ORD-LAS              1.6         196
8115  Flight8116  41804  ORD-SFO              2.2         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8114             0.291667             275.0     45375.0            12
8115             0.541667             412.5     76312.5             6

      Flight Year
8114         2015
8115         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8116  Flight8117  41678  ORD-DEN              3.1          49
8117  Flight8118  41845  ORD-MSP              1.2          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8116             0.291667             300.0     49500.0             2
8117             0.666667             126.5     22896.5             7

      Flight Year
8116         2014
8117         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8118  Flight8119  41957  ORD-FLL              1.2          52
8119  Flight8120  41976  ORD-LAX              3.4          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8118             0.791667               300       49500            11
8119             0.708333               350       57750            12

      Flight Year
8118         2014
8119         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8120  Flight8121  42336  ORD-DEN              2.8         100
8121  Flight8122  42120  ORD-PHL              1.5         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8120                 0.50               450       83250            11
8121                 0.75               275       50875             4

      Flight Year
8120         2015
8121         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8122  Flight8123  42125  ORD-EWR              3.9         110
8123  Flight8124  42137  ORD-LAX              4.2         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8122             0.833333               225       41625             5
8123             0.291667               350       64750             5

      Flight Year
8122         2015
8123         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8124  Flight8125  41683  ORD-ATL             16.0          72
8125  Flight8126  41870  ORD-LGA              2.6          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8124             0.354167             200.0     36200.0             2
8125             0.333333             302.5     49912.5             8

      Flight Year
8124         2014
8125         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8126  Flight8127  41653  ORD-IAH              1.9          45
8127  Flight8128  42361  ORD-IAH              5.1          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8126             0.291667               200       33000             1
8127             0.812500               280       51800            12

      Flight Year
8126         2014
8127         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8128  Flight8129  41659  ORD-MIA              1.0         168
8129  Flight8130  42166  ORD-LAS              2.3         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8128             0.708333             300.0     49500.0             1
8129             0.791667             302.5     49912.5             6

      Flight Year
8128         2014
8129         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8130  Flight8131  42032  ORD-JFK              1.5         163
8131  Flight8132  42295  ORD-CLT              2.4          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8130             0.375000               250       41250             1
8131             0.833333               125       23125            10

      Flight Year
8130         2015
8131         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8132  Flight8133  41657  ORD-SFO              3.0         203
8133  Flight8134  42009  ORD-SFO              1.8          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8132             0.708333               375       61875             1
8133             0.333333               375       61875             1

      Flight Year
8132         2014
8133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8134  Flight8135  41793  ORD-DEN              0.8          26
8135  Flight8136  42332  ORD-FLL              5.0          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8134             0.645833               330       61050             6
8135             0.708333               450       81450            11

      Flight Year
8134         2014
8135         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8136  Flight8137  41731  ORD-LAX              5.3         189
8137  Flight8138  42279  ORD-EWR              2.4          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8136                0.375               350       57750             4
8137                0.375               225       40725            10

      Flight Year
8136         2014
8137         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8138  Flight8139  42091  ORD-LAX              4.1         134
8139  Flight8140  42137  ORD-IAH              1.6         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8138             0.354167               350       64750             3
8139             0.479167               200       33000             5

      Flight Year
8138         2015
8139         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8140  Flight8141  42166  ORD-JFK              2.6          99
8141  Flight8142  41830  ORD-DFW              0.4         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8140             0.812500               275       50875             6
8141             0.458333               220       36300             7

      Flight Year
8140         2015
8141         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8142  Flight8143  42112  ORD-MCO              2.6          88
8143  Flight8144  42234  ORD-PHX              3.7         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8142               0.7500               250       45250             4
8143               0.8125               275       50875             8

      Flight Year
8142         2015
8143         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8144  Flight8145  41838  ORD-DTW              2.0          29
8145  Flight8146  42333  ORD-DEN              6.2          99

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8144             0.875000             126.5     23402.5             7
8145             0.541667             450.0     83250.0            11

      Flight Year
8144         2014
8145         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8146  Flight8147  41913  ORD-SLC              1.1          85
8147  Flight8148  42365  ORD-MCO              2.8           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8146             0.708333               290       52490            10
8147             0.729167               350       64750            12

      Flight Year
8146         2014
8147         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8148  Flight8149  41843  ORD-EWR              3.1           8
8149  Flight8150  42096  ORD-ATL              8.2          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8148             0.791667             247.5     45787.5             7
8149             0.395833             200.0     36200.0             4

      Flight Year
8148         2014
8149         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8150  Flight8151  41896  ORD-ATL             10.1           1
8151  Flight8152  41733  ORD-SFO              2.9         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8150             0.833333               200       37000             9
8151             0.479167               375       69375             4

      Flight Year
8150         2014
8151         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8152  Flight8153  42010  ORD-DTW              1.4          37
8153  Flight8154  42011  ORD-JFK              2.6         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8152             0.895833               115       18975             1
8153             0.500000               250       46250             1

      Flight Year
8152         2015
8153         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8154  Flight8155  41996  ORD-MSP              3.1          49
8155  Flight8156  41735  ORD-LAX              5.2         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8154             0.375000               161       26565            12
8155             0.666667               350       57750             4

      Flight Year
8154         2014
8155         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8156  Flight8157  41643  ORD-SEA              2.0          71
8157  Flight8158  42207  ORD-PHX              1.5         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8156             0.708333               350       63350             1
8157             0.354167               275       50875             7

      Flight Year
8156         2014
8157         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8158  Flight8159  41958  ORD-LAX              4.3          67
8159  Flight8160  42366  ORD-MIA              2.0         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8158             0.541667               350       63350            11
8159             0.895833               300       55500            12

      Flight Year
8158         2014
8159         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8160  Flight8161  41817  ORD-IAH              3.2          84
8161  Flight8162  42362  ORD-DTW              3.9          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8160             0.708333               220       39820             6
8161             0.541667               161       29785            12

      Flight Year
8160         2014
8161         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8162  Flight8163  41945  ORD-MIA              1.6          18
8163  Flight8164  41960  ORD-DTW              1.1         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8162             0.708333               300       55500            11
8163             0.791667               115       18975            11

      Flight Year
8162         2014
8163         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8164  Flight8165  42095  ORD-PHX              3.1          44
8165  Flight8166  42081  ORD-MCO              2.6          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8164             0.562500               250       41250             4
8165             0.291667               250       41250             3

      Flight Year
8164         2015
8165         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8166  Flight8167  41999  ORD-JFK              4.6         123
8167  Flight8168  42031  ORD-JFK              1.1         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8166             0.291667               350       64750            12
8167             0.791667               250       46250             1

      Flight Year
8166         2014
8167         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8168  Flight8169  41896  ORD-CLT              1.6         177
8169  Flight8170  41972  ORD-DEN              6.3         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8168             0.291667               125       20625             9
8169             0.416667               450       83250            11

      Flight Year
8168         2014
8169         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8170  Flight8171  41694  ORD-JFK              1.2          41
8171  Flight8172  42091  ORD-ATL             11.4         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8170             0.541667               250       41250             2
8171             0.312500               200       33000             3

      Flight Year
8170         2014
8171         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8172  Flight8173  41859  ORD-BWI              2.7         142
8173  Flight8174  41841  ORD-LAX              4.5          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8172             0.729167               264       48840             8
8173             0.645833               385       69685             7

      Flight Year
8172         2014
8173         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8174  Flight8175  42162  ORD-JFK              2.2         192
8175  Flight8176  41776  ORD-CLT              1.8          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8174             0.812500               275       45375             6
8175             0.833333               125       20625             5

      Flight Year
8174         2015
8175         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8176  Flight8177  41860  ORD-SFO              1.2         153
8177  Flight8178  41763  ORD-DEN              2.4         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8176             0.708333             412.5     68062.5             8
8177             0.666667             300.0     49500.0             5

      Flight Year
8176         2014
8177         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8178  Flight8179  41712  ORD-MCO              2.5          59
8179  Flight8180  41930  ORD-BOS              2.4          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8178             0.708333               250       41250             3
8179             0.729167               300       54300            10

      Flight Year
8178         2014
8179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8180  Flight8181  41886  ORD-FLL              2.3           7
8181  Flight8182  42015  ORD-PHX              3.7         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8180             0.291667               300       55500             9
8181             0.291667               250       41250             1

      Flight Year
8180         2014
8181         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8182  Flight8183  41693  ORD-CLT              1.7          19
8183  Flight8184  41714  ORD-BOS              3.5          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8182                 0.75               125       23125             2
8183                 0.75               300       55500             3

      Flight Year
8182         2014
8183         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8184  Flight8185  41792  ORD-SFO              1.7          32
8185  Flight8186  42030  ORD-DTW              3.3          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8184             0.291667             412.5     76312.5             6
8185             0.708333             115.0     21275.0             1

      Flight Year
8184         2014
8185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8186  Flight8187  42130  ORD-MCO              3.0           8
8187  Flight8188  41996  ORD-LGA              3.8          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8186             0.333333               250       46250             5
8187             0.500000               385       69685            12

      Flight Year
8186         2015
8187         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8188  Flight8189  41717  ORD-CLT              0.5         209
8189  Flight8190  41698  ORD-SFO              1.8          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8188             0.416667               125       20625             3
8189             0.750000               375       67875             2

      Flight Year
8188         2014
8189         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8190  Flight8191  42187  ORD-LAX              4.5         179
8191  Flight8192  41760  ORD-SEA              2.2         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8190             0.791667               385       63525             7
8191             0.791667               350       64750             5

      Flight Year
8190         2015
8191         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8192  Flight8193  42134  ORD-DFW              2.9          66
8193  Flight8194  41656  ORD-DEN              1.8         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8192             0.291667               200       36200             5
8193             0.708333               300       49500             1

      Flight Year
8192         2015
8193         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8194  Flight8195  42345  ORD-LAS              2.2         153
8195  Flight8196  42188  ORD-MSP              2.2         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8194             0.875000             275.0     45375.0            12
8195             0.291667             126.5     20872.5             7

      Flight Year
8194         2015
8195         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8196  Flight8197  41654  ORD-ATL             11.5          97
8197  Flight8198  42362  ORD-ATL             14.8          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8196             0.333333               200       37000             1
8197             0.812500               280       50680            12

      Flight Year
8196         2014
8197         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8198  Flight8199  41659  ORD-DFW              2.4         129
8199  Flight8200  41835  ORD-LAS              0.6          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8198             0.770833             200.0     37000.0             1
8199             0.625000             302.5     54752.5             7

      Flight Year
8198         2014
8199         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8200  Flight8201  42273  ORD-LAS              1.9          20
8201  Flight8202  41845  ORD-DCA              1.2         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8200             0.750000               275       50875             9
8201             0.854167              5500     1017500             7

      Flight Year
8200         2015
8201         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8202  Flight8203  41835  ORD-PHX              1.8         180
8203  Flight8204  41799  ORD-JFK              2.4         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8202             0.791667               275       45375             7
8203             0.833333               275       50875             6

      Flight Year
8202         2014
8203         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8204  Flight8205  41765  ORD-SFO              2.6         131
8205  Flight8206  41924  ORD-PHL              2.1         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8204             0.291667               375       69375             5
8205             0.416667               275       45375            10

      Flight Year
8204         2014
8205         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8206  Flight8207  41995  ORD-CLT              6.0         206
8207  Flight8208  42146  ORD-JFK              1.7         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8206             0.291667               175       28875            12
8207             0.750000               250       41250             5

      Flight Year
8206         2014
8207         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8208  Flight8209  41942  ORD-DEN              3.1          85
8209  Flight8210  41972  ORD-JFK              4.5         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8208             0.333333               300       54300            10
8209             0.833333               375       61875            11

      Flight Year
8208         2014
8209         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8210  Flight8211  42113  ORD-DEN              0.8          18
8211  Flight8212  41823  ORD-IAH              1.3         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8210             0.583333               300       55500             4
8211             0.708333               220       40700             7

      Flight Year
8210         2015
8211         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8212  Flight8213  42011  ORD-LGA              2.2          37
8213  Flight8214  42197  ORD-IAH              1.4         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8212             0.583333               275       45375             1
8213             0.708333               220       36300             7

      Flight Year
8212         2015
8213         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8214  Flight8215  41933  ORD-LAX              6.7         209
8215  Flight8216  42211  ORD-EWR              1.9           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8214             0.458333             350.0     57750.0            10
8215             0.791667             247.5     45787.5             7

      Flight Year
8214         2014
8215         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8216  Flight8217  41894  ORD-LAS              2.6         191
8217  Flight8218  42030  ORD-CLT              3.0          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8216             0.750000               275       45375             9
8217             0.791667               125       20625             1

      Flight Year
8216         2014
8217         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8218  Flight8219  41730  ORD-DFW              2.5          30
8219  Flight8220  42004  ORD-FLL              1.4         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8218             0.895833               200       37000             4
8219             0.729167               300       49500            12

      Flight Year
8218         2014
8219         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8220  Flight8221  42179  ORD-EWR              1.8          24
8221  Flight8222  42134  ORD-SLC              2.2         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8220             0.833333             247.5     45787.5             6
8221             0.708333             290.0     53650.0             5

      Flight Year
8220         2015
8221         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8222  Flight8223  41919  ORD-DFW              2.1          69
8223  Flight8224  42023  ORD-JFK              2.1          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8222               0.5625               200       36200            10
8223               0.6250               250       41250             1

      Flight Year
8222         2014
8223         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8224  Flight8225  42047  ORD-DEN              0.9          61
8225  Flight8226  42236  ORD-DFW              2.0         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8224             0.583333               300       49500             2
8225             0.625000               220       40700             8

      Flight Year
8224         2015
8225         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8226  Flight8227  42035  ORD-MCO              2.5          22
8227  Flight8228  41804  ORD-JFK              2.4         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8226             0.458333               250       46250             1
8227             0.833333               275       45375             6

      Flight Year
8226         2015
8227         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8228  Flight8229  42338  ORD-LGA              2.2         115
8229  Flight8230  41827  ORD-BOS              2.6         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8228             0.333333               275       50875            11
8229             0.729167               330       61050             7

      Flight Year
8228         2015
8229         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8230  Flight8231  42173  ORD-DFW              1.8         159
8231  Flight8232  41795  ORD-SFO              2.5         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8230             0.291667             220.0     36300.0             6
8231             0.750000             412.5     68062.5             6

      Flight Year
8230         2015
8231         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8232  Flight8233  42266  ORD-CLT              2.3         139
8233  Flight8234  41895  ORD-LGA              2.5          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8232             0.333333               125       23125             9
8233             0.291667               275       49775             9

      Flight Year
8232         2015
8233         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8234  Flight8235  41972  ORD-LAS              6.1          70
8235  Flight8236  41764  ORD-PHL              1.3          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8234             0.833333             412.5     74662.5            11
8235             0.750000             275.0     45375.0             5

      Flight Year
8234         2014
8235         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8236  Flight8237  41945  ORD-BOS              1.6          43
8237  Flight8238  41886  ORD-CLT              2.0         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8236             0.625000               300       49500            11
8237             0.604167               125       20625             9

      Flight Year
8236         2014
8237         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8238  Flight8239  41818  ORD-BOS              2.1         134
8239  Flight8240  41655  ORD-CLT              1.4         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8238             0.729167               330       61050             6
8239             0.604167               125       23125             1

      Flight Year
8238         2014
8239         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8240  Flight8241  42151  ORD-MCO              1.3          78
8241  Flight8242  41741  ORD-SFO              1.7         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8240             0.833333               250       45250             5
8241             0.750000               375       69375             4

      Flight Year
8240         2015
8241         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8242  Flight8243  41713  ORD-DEN              2.2          69
8243  Flight8244  42038  ORD-CLT              2.6         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8242             0.708333               300       54300             3
8243             0.708333               125       20625             2

      Flight Year
8242         2014
8243         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8244  Flight8245  41716  ORD-PHL              3.5         126
8245  Flight8246  41827  ORD-LAS              1.9         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8244             0.333333             275.0     50875.0             3
8245             0.729167             302.5     55962.5             7

      Flight Year
8244         2014
8245         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8246  Flight8247  42238  ORD-SEA              2.0         145
8247  Flight8248  42120  ORD-IAH              1.3          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8246             0.291667               385       71225             8
8247             0.833333               200       37000             4

      Flight Year
8246         2015
8247         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8248  Flight8249  41951  ORD-FLL              0.9         142
8249  Flight8250  41646  ORD-ATL             10.5          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8248             0.750000               300       55500            11
8249             0.791667               200       37000             1

      Flight Year
8248         2014
8249         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8250  Flight8251  42006  ORD-JFK              2.3          78
8251  Flight8252  42344  ORD-MSP              2.8          89

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8250             0.291667               250       45250             1
8251             0.833333               115       20815            12

      Flight Year
8250         2015
8251         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8252  Flight8253  42078  ORD-SEA              1.7           7
8253  Flight8254  41708  ORD-SFO              1.1         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8252             0.291667               350       64750             3
8253             0.750000               375       69375             3

      Flight Year
8252         2015
8253         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8254  Flight8255  42202  ORD-DEN              2.3         179
8255  Flight8256  42277  ORD-MSP              2.6         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8254             0.750000               330       54450             7
8255             0.291667               115       21275             9

      Flight Year
8254         2015
8255         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8256  Flight8257  42193  ORD-SEA              0.7          31
8257  Flight8258  41850  ORD-DFW              2.2          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8256             0.833333               385       71225             7
8257             0.333333               220       36300             7

      Flight Year
8256         2015
8257         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8258  Flight8259  42214  ORD-MIA              2.1           5
8259  Flight8260  42216  ORD-ATL             11.4          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8258             0.666667               330       61050             7
8259             0.791667               220       40700             7

      Flight Year
8258         2015
8259         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8260  Flight8261  41837  ORD-ATL             12.5         135
8261  Flight8262  42314  ORD-MIA              2.7         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8260             0.333333               220       40700             7
8261             0.312500               300       49500            11

      Flight Year
8260         2014
8261         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8262  Flight8263  42357  ORD-CLT              1.5         124
8263  Flight8264  41762  ORD-DFW              1.9         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8262             0.729167               125       23125            12
8263             0.708333               200       37000             5

      Flight Year
8262         2015
8263         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8264  Flight8265  41897  ORD-MCO              2.7          41
8265  Flight8266  42332  ORD-CLT              5.4          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8264             0.333333             250.0     41250.0             9
8265             0.833333             187.5     30937.5            11

      Flight Year
8264         2014
8265         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8266  Flight8267  41737  ORD-MCO              1.3          35
8267  Flight8268  42024  ORD-LAX              3.5         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8266               0.7500               250       46250             4
8267               0.8125               350       64750             1

      Flight Year
8266         2014
8267         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8268  Flight8269  42159  ORD-LAX              4.8          85
8269  Flight8270  42223  ORD-DEN              1.0          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8268             0.583333               385       69685             6
8269             0.333333               330       61050             8

      Flight Year
8268         2015
8269         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8270  Flight8271  42161  ORD-MIA              1.5          88
8271  Flight8272  41822  ORD-FLL              2.4          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8270             0.708333               330       59730             6
8271             0.875000               330       54450             7

      Flight Year
8270         2015
8271         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8272  Flight8273  42005  ORD-LGA              1.3         204
8273  Flight8274  42016  ORD-ATL              8.9         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8272             0.333333               275       45375             1
8273             0.625000               200       33000             1

      Flight Year
8272         2015
8273         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8274  Flight8275  42259  ORD-MIA              3.2          38
8275  Flight8276  42140  ORD-MIA              0.4           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8274             0.750000               300       49500             9
8275             0.416667               300       55500             5

      Flight Year
8274         2015
8275         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8276  Flight8277  42245  ORD-DFW              0.7         127
8277  Flight8278  42331  ORD-DFW              4.6         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8276             0.291667               220       40700             8
8277             0.458333               300       49500            11

      Flight Year
8276         2015
8277         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8278  Flight8279  42175  ORD-DCA              1.5          21
8279  Flight8280  41696  ORD-LAX              3.1          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8278             0.750000              5500     1017500             6
8279             0.895833               350       63350             2

      Flight Year
8278         2015
8279         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8280  Flight8281  42156  ORD-PHL              2.7         152
8281  Flight8282  42185  ORD-DEN              1.6          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8280               0.8125             302.5     49912.5             6
8281               0.8750             330.0     61050.0             6

      Flight Year
8280         2015
8281         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8282  Flight8283  42295  ORD-SFO              2.7         183
8283  Flight8284  42316  ORD-LGA              1.8         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8282             0.833333               375       61875            10
8283             0.541667               275       45375            11

      Flight Year
8282         2015
8283         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8284  Flight8285  42332  ORD-BWI              5.2          48
8285  Flight8286  41664  ORD-SEA              1.2          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8284             0.291667               360       59400            11
8285             0.770833               350       63350             1

      Flight Year
8284         2015
8285         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8286  Flight8287  41714  ORD-DFW              0.7          54
8287  Flight8288  42191  ORD-LGA              2.1           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8286             0.500000             200.0     33000.0             3
8287             0.291667             302.5     55962.5             7

      Flight Year
8286         2014
8287         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8288  Flight8289  41874  ORD-IAH              0.6         209
8289  Flight8290  42329  ORD-MSP              2.5         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8288             0.687500               220       36300             8
8289             0.791667               115       21275            11

      Flight Year
8288         2014
8289         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8290  Flight8291  41884  ORD-LAX              4.7          64
8291  Flight8292  42295  ORD-SEA              2.7          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8290             0.291667               350       63350             9
8291             0.583333               350       63350            10

      Flight Year
8290         2014
8291         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8292  Flight8293  41796  ORD-CLT              3.4         193
8293  Flight8294  41811  ORD-IAH              0.9         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8292             0.770833             137.5     22687.5             6
8293             0.562500             220.0     40700.0             6

      Flight Year
8292         2014
8293         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8294  Flight8295  42307  ORD-MIA              2.3         177
8295  Flight8296  41727  ORD-CLT              1.6         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8294             0.520833               300       49500            10
8295             0.354167               125       23125             3

      Flight Year
8294         2015
8295         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8296  Flight8297  41826  ORD-ATL              9.8          88
8297  Flight8298  41674  ORD-LAX              1.8          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8296             0.791667               220       39820             7
8297             0.416667               350       64750             2

      Flight Year
8296         2014
8297         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8298  Flight8299  41779  ORD-SFO              2.9         207
8299  Flight8300  42292  ORD-LAS              1.9          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8298             0.458333               375       61875             5
8299             0.770833               275       50875            10

      Flight Year
8298         2014
8299         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8300  Flight8301  42163  ORD-LAS              1.5         135
8301  Flight8302  42138  ORD-ATL              6.5          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8300             0.750000             302.5     55962.5             6
8301             0.479167             200.0     33000.0             5

      Flight Year
8300         2015
8301         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8302  Flight8303  41670  ORD-PHX              1.1         109
8303  Flight8304  42299  ORD-EWR              2.2         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8302             0.770833               250       46250             1
8303             0.500000               225       37125            10

      Flight Year
8302         2014
8303         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8304  Flight8305  41840  ORD-IAH              2.2         100
8305  Flight8306  42307  ORD-ATL              7.5         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8304             0.812500               220       40700             7
8305             0.666667               200       33000            10

      Flight Year
8304         2014
8305         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8306  Flight8307  42032  ORD-MSP              3.3          61
8307  Flight8308  41722  ORD-DFW              2.3          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8306             0.791667               115       18975             1
8307             0.750000               200       36200             3

      Flight Year
8306         2015
8307         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8308  Flight8309  42231  ORD-PHX              2.4         164
8309  Flight8310  42240  ORD-DEN              3.1          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8308             0.708333               275       45375             8
8309             0.333333               330       54450             8

      Flight Year
8308         2015
8309         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8310  Flight8311  41683  ORD-LGA              1.4         180
8311  Flight8312  42360  ORD-EWR              3.3          78

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8310             0.708333               275       45375             2
8311             0.750000               315       57015            12

      Flight Year
8310         2014
8311         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8312  Flight8313  42294  ORD-IAH              1.4          91
8313  Flight8314  42266  ORD-SEA              1.7          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8312             0.291667               200       37000            10
8313             0.791667               350       57750             9

      Flight Year
8312         2015
8313         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8314  Flight8315  42247  ORD-MSP              2.4         141
8315  Flight8316  42100  ORD-DEN              2.0          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8314             0.291667             126.5     23402.5             8
8315             0.395833             300.0     54300.0             4

      Flight Year
8314         2015
8315         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8316  Flight8317  41834  ORD-ATL             10.1         107
8317  Flight8318  42232  ORD-BOS              2.5         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8316             0.791667               220       40700             7
8317             0.458333               330       61050             8

      Flight Year
8316         2014
8317         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8318  Flight8319  41932  ORD-PHL              3.3          97
8319  Flight8320  42325  ORD-DCA              1.3         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8318             0.708333               275       50875            10
8319             0.729167              5000      925000            11

      Flight Year
8318         2014
8319         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8320  Flight8321  42165  ORD-FLL              1.9          16
8321  Flight8322  42363  ORD-DEN              5.2         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8320             0.729167               330       61050             6
8321             0.708333               420       77700            12

      Flight Year
8320         2015
8321         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8322  Flight8323  41934  ORD-DTW              1.6         138
8323  Flight8324  41973  ORD-LAX              8.4          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8322             0.604167               115       21275            10
8323             0.333333               525       97125            11

      Flight Year
8322         2014
8323         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8324  Flight8325  41785  ORD-ATL              9.4         104
8325  Flight8326  42245  ORD-EWR              2.2         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8324             0.500000             200.0     37000.0             5
8325             0.833333             247.5     40837.5             8

      Flight Year
8324         2014
8325         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8326  Flight8327  42068  ORD-FLL              1.1         163
8327  Flight8328  42226  ORD-DEN              2.2         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8326             0.791667               300       49500             3
8327             0.666667               330       61050             8

      Flight Year
8326         2015
8327         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8328  Flight8329  42031  ORD-LAX              4.1           6
8329  Flight8330  41976  ORD-LGA              3.0         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8328             0.541667               350       64750             1
8329             0.750000               275       50875            12

      Flight Year
8328         2015
8329         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8330  Flight8331  41925  ORD-MCO              1.8          29
8331  Flight8332  42293  ORD-PHL              1.9         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8330             0.750000               250       46250            10
8331             0.708333               275       45375            10

      Flight Year
8330         2014
8331         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8332  Flight8333  42211  ORD-JFK              3.4          58
8333  Flight8334  42344  ORD-ATL              9.6          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8332             0.708333               275       45375             7
8333             0.354167               200       37000            12

      Flight Year
8332         2015
8333         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8334  Flight8335  41915  ORD-MIA                2         137
8335  Flight8336  41675  ORD-LAS                2          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8334             0.458333               300       55500            10
8335             0.708333               275       49775             2

      Flight Year
8334         2014
8335         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8336  Flight8337  42144  ORD-DEN              2.7          83
8337  Flight8338  42143  ORD-SFO              2.5         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8336             0.625000               300       54300             5
8337             0.791667               375       69375             5

      Flight Year
8336         2015
8337         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8338  Flight8339  42188  ORD-SFO              1.6          34
8339  Flight8340  41997  ORD-EWR              3.2         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8338             0.458333             412.5     76312.5             7
8339             0.333333             315.0     58275.0            12

      Flight Year
8338         2015
8339         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8340  Flight8341  42063  ORD-JFK              1.3         127
8341  Flight8342  42109  ORD-LAX              2.3         205

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8340             0.416667               250       46250             2
8341             0.354167               350       57750             4

      Flight Year
8340         2015
8341         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8342  Flight8343  42168  ORD-JFK              1.6         173
8343  Flight8344  42060  ORD-EWR              0.9         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8342               0.5625               275       45375             6
8343               0.6250               225       41625             2

      Flight Year
8342         2015
8343         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8344  Flight8345  41697  ORD-JFK              1.7         132
8345  Flight8346  41953  ORD-DFW              2.0         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8344             0.708333               250       46250             2
8345             0.541667               200       37000            11

      Flight Year
8344         2014
8345         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8346  Flight8347  42283  ORD-SFO              2.5         161
8347  Flight8348  41841  ORD-CLT              1.1         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8346             0.750000             375.0     61875.0            10
8347             0.291667             137.5     22687.5             7

      Flight Year
8346         2015
8347         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8348  Flight8349  41967  ORD-IAH              6.1         180
8349  Flight8350  41654  ORD-MIA              2.0         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8348             0.812500               300       49500            11
8349             0.291667               300       55500             1

      Flight Year
8348         2014
8349         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8350  Flight8351  41643  ORD-MIA              1.3          24
8351  Flight8352  42175  ORD-IAH              1.2         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8350             0.791667               300       55500             1
8351             0.458333               220       36300             6

      Flight Year
8350         2014
8351         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8352  Flight8353  41644  ORD-PHL              1.5          96
8353  Flight8354  42329  ORD-PHL              1.8          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8352             0.791667               275       50875             1
8353             0.291667               275       45375            11

      Flight Year
8352         2014
8353         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8354  Flight8355  41880  ORD-LAS              1.3          81
8355  Flight8356  41869  ORD-DFW              1.6          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8354             0.791667             302.5     54752.5             8
8355             0.541667             220.0     40700.0             8

      Flight Year
8354         2014
8355         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8356  Flight8357  41912  ORD-BOS              1.3         149
8357  Flight8358  42092  ORD-CLT              1.6         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8356             0.750000               300       55500             9
8357             0.291667               125       20625             3

      Flight Year
8356         2014
8357         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8358  Flight8359  41982  ORD-LGA              1.8          61
8359  Flight8360  42092  ORD-JFK              2.6          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8358             0.708333               275       45375            12
8359             0.708333               250       41250             3

      Flight Year
8358         2014
8359         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8360  Flight8361  42059  ORD-DFW              2.0         114
8361  Flight8362  41752  ORD-ATL              8.1         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8360             0.416667               200       37000             2
8361             0.333333               200       37000             4

      Flight Year
8360         2015
8361         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8362  Flight8363  41843  ORD-LAX              5.4         166
8363  Flight8364  42346  ORD-PHX              3.3          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8362             0.291667               385       63525             7
8363             0.750000               250       46250            12

      Flight Year
8362         2014
8363         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8364  Flight8365  41963  ORD-SFO              3.4         191
8365  Flight8366  42332  ORD-IAH              2.8         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8364             0.875000               375       61875            11
8365             0.458333               300       49500            11

      Flight Year
8364         2014
8365         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8366  Flight8367  42142  ORD-DEN              2.6         131
8367  Flight8368  42094  ORD-PHX              3.4          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8366             0.791667               300       55500             5
8367             0.708333               250       45250             3

      Flight Year
8366         2015
8367         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8368  Flight8369  42221  ORD-ATL              9.9         125
8369  Flight8370  42115  ORD-PHX              1.5          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8368             0.708333               220       40700             8
8369             0.333333               250       45250             4

      Flight Year
8368         2015
8369         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8370  Flight8371  41751  ORD-SEA              2.1          37
8371  Flight8372  42072  ORD-JFK              2.1          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8370             0.604167               350       57750             4
8371             0.750000               250       41250             3

      Flight Year
8370         2014
8371         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8372  Flight8373  42008  ORD-ATL              6.9           2
8373  Flight8374  41831  ORD-DEN              2.3         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8372             0.875000               200       37000             1
8373             0.291667               330       61050             7

      Flight Year
8372         2015
8373         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8374  Flight8375  41895  ORD-BWI              0.3         126
8375  Flight8376  41673  ORD-CLT              2.5         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8374             0.854167               240       44400             9
8375             0.750000               125       23125             2

      Flight Year
8374         2014
8375         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8376  Flight8377  41982  ORD-CLT              1.3         140
8377  Flight8378  41746  ORD-SFO              2.4         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8376             0.458333               125       23125            12
8377             0.583333               375       61875             4

      Flight Year
8376         2014
8377         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8378  Flight8379  42195  ORD-DFW              2.5         161
8379  Flight8380  41910  ORD-LAX              4.8         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8378             0.812500               220       36300             7
8379             0.729167               350       64750             9

      Flight Year
8378         2015
8379         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8380  Flight8381  41806  ORD-PHX              1.9          72
8381  Flight8382  42031  ORD-PHL              2.7         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8380             0.708333               275       49775             6
8381             0.625000               275       45375             1

      Flight Year
8380         2014
8381         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8382  Flight8383  41679  ORD-DEN              2.3         153
8383  Flight8384  41959  ORD-LGA              3.0         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8382             0.750000               300       49500             2
8383             0.729167               275       45375            11

      Flight Year
8382         2014
8383         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8384  Flight8385  42368  ORD-ATL             11.6         155
8385  Flight8386  42332  ORD-DEN              5.2          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8384             0.354167               200       33000            12
8385             0.375000               450       81450            11

      Flight Year
8384         2015
8385         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8386  Flight8387  42124  ORD-CLT              2.1         177
8387  Flight8388  42365  ORD-DEN              2.7         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8386             0.708333               125       20625             4
8387             0.812500               420       69300            12

      Flight Year
8386         2015
8387         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8388  Flight8389  41919  ORD-BWI              3.6         209
8389  Flight8390  42355  ORD-MIA              2.1          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8388             0.791667               240       39600            10
8389             0.791667               300       55500            12

      Flight Year
8388         2014
8389         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8390  Flight8391  42333  ORD-LAX              8.9          14
8391  Flight8392  42302  ORD-ATL              9.9          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8390             0.416667               525       97125            11
8391             0.291667               200       37000            10

      Flight Year
8390         2015
8391         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8392  Flight8393  41713  ORD-JFK              1.9          44
8393  Flight8394  42174  ORD-MSP              1.3          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8392             0.333333             250.0     41250.0             3
8393             0.583333             126.5     23402.5             6

      Flight Year
8392         2014
8393         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8394  Flight8395  42275  ORD-PHL              0.2         167
8395  Flight8396  42217  ORD-CLT              2.1         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8394             0.291667             275.0     45375.0             9
8395             0.791667             137.5     25437.5             8

      Flight Year
8394         2015
8395         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8396  Flight8397  42130  ORD-EWR              1.3         127
8397  Flight8398  42001  ORD-MIA              4.4         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8396             0.604167               225       41625             5
8397             0.833333               420       69300            12

      Flight Year
8396         2015
8397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8398  Flight8399  42243  ORD-LGA              1.0         101
8399  Flight8400  42207  ORD-DFW              2.9          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8398             0.750000             302.5     55962.5             8
8399             0.354167             220.0     40700.0             7

      Flight Year
8398         2015
8399         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8400  Flight8401  41821  ORD-LAX              3.6         184
8401  Flight8402  41878  ORD-PHL              1.7         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8400             0.625000             385.0     63525.0             7
8401             0.708333             302.5     55962.5             8

      Flight Year
8400         2014
8401         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8402  Flight8403  41641  ORD-PHX              2.1          28
8403  Flight8404  42046  ORD-MSP              1.7           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8402             0.333333               250       46250             1
8403             0.541667               115       21275             2

      Flight Year
8402         2014
8403         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8404  Flight8405  41708  ORD-DFW              1.1         146
8405  Flight8406  41930  ORD-MIA              1.0         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8404             0.500000               200       37000             3
8405             0.791667               300       49500            10

      Flight Year
8404         2014
8405         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8406  Flight8407  42158  ORD-EWR              2.4         144
8407  Flight8408  41741  ORD-DTW              1.7         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8406             0.708333             247.5     45787.5             6
8407             0.791667             115.0     18975.0             4

      Flight Year
8406         2015
8407         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8408  Flight8409  41720  ORD-LAX              2.0          90
8409  Flight8410  42172  ORD-MIA              2.2          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8408             0.500000               350       63350             3
8409             0.791667               330       61050             6

      Flight Year
8408         2014
8409         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8410  Flight8411  42250  ORD-PHL              1.5         108
8411  Flight8412  41754  ORD-LAX              3.8          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8410             0.333333               275       50875             9
8411             0.291667               350       63350             4

      Flight Year
8410         2015
8411         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8412  Flight8413  42332  ORD-LAS              5.2          57
8413  Flight8414  42359  ORD-MIA              2.7          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8412             0.500000             412.5     68062.5            11
8413             0.291667             420.0     69300.0            12

      Flight Year
8412         2015
8413         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8414  Flight8415  41861  ORD-CLT              2.1         116
8415  Flight8416  42233  ORD-MCO              1.7         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8414             0.833333             137.5     25437.5             8
8415             0.458333             275.0     50875.0             8

      Flight Year
8414         2014
8415         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8416  Flight8417  41767  ORD-MIA              2.1         117
8417  Flight8418  42289  ORD-SEA              2.0          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8416             0.458333               300       55500             5
8417             0.812500               350       63350            10

      Flight Year
8416         2014
8417         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8418  Flight8419  42082  ORD-LAX              4.7          57
8419  Flight8420  42331  ORD-PHX              3.3           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8418             0.708333               350       57750             3
8419             0.312500               375       69375            11

      Flight Year
8418         2015
8419         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8420  Flight8421  42329  ORD-SEA              1.7         175
8421  Flight8422  42346  ORD-ATL              7.4         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8420             0.854167               350       57750            11
8421             0.583333               200       37000            12

      Flight Year
8420         2015
8421         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8422  Flight8423  42221  ORD-IAH              2.8         108
8423  Flight8424  41796  ORD-MSP              1.8         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8422             0.625000             220.0     40700.0             8
8423             0.291667             126.5     20872.5             6

      Flight Year
8422         2015
8423         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8424  Flight8425  41819  ORD-DFW              2.2         100
8425  Flight8426  41697  ORD-MSP              1.5           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8424             0.666667               220       40700             6
8425             0.291667               115       21275             2

      Flight Year
8424         2014
8425         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8426  Flight8427  42167  ORD-LAS              1.6         164
8427  Flight8428  42229  ORD-PHX              0.6         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8426             0.791667             302.5     49912.5             6
8427             0.500000             275.0     50875.0             8

      Flight Year
8426         2015
8427         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8428  Flight8429  42351  ORD-DEN              1.3         195
8429  Flight8430  41755  ORD-CLT              2.0          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8428             0.708333               300       49500            12
8429             0.500000               125       22625             4

      Flight Year
8428         2015
8429         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8430  Flight8431  42343  ORD-SFO              1.9         156
8431  Flight8432  42094  ORD-SFO              1.8          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8430             0.812500               375       61875            12
8431             0.666667               375       61875             3

      Flight Year
8430         2015
8431         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8432  Flight8433  41735  ORD-MSP              2.6         129
8433  Flight8434  42187  ORD-MSP              2.8           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8432                0.625             115.0     21275.0             4
8433                0.750             126.5     23402.5             7

      Flight Year
8432         2014
8433         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8434  Flight8435  41955  ORD-CLT              2.2          14
8435  Flight8436  41981  ORD-ATL              8.1          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8434             0.708333               125       23125            11
8435             0.541667               200       36200            12

      Flight Year
8434         2014
8435         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8436  Flight8437  42253  ORD-BOS              2.7         173
8437  Flight8438  42065  ORD-DFW              1.1         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8436             0.416667               300       49500             9
8437             0.791667               200       33000             3

      Flight Year
8436         2015
8437         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8438  Flight8439  41715  ORD-DFW              1.6          89
8439  Flight8440  41675  ORD-MCO              2.4           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8438             0.333333               200       36200             3
8439             0.312500               250       46250             2

      Flight Year
8438         2014
8439         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8440  Flight8441  41824  ORD-EWR              2.4          85
8441  Flight8442  41939  ORD-LAS              1.2         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8440             0.416667             247.5     44797.5             7
8441             0.750000             275.0     50875.0            10

      Flight Year
8440         2014
8441         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8442  Flight8443  41913  ORD-EWR              2.1          56
8443  Flight8444  41650  ORD-DFW              2.1         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8442             0.833333               225       37125            10
8443             0.791667               200       37000             1

      Flight Year
8442         2014
8443         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8444  Flight8445  41755  ORD-DEN              2.1          24
8445  Flight8446  42297  ORD-PHX              0.8          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8444             0.291667               300       55500             4
8445             0.895833               250       46250            10

      Flight Year
8444         2014
8445         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8446  Flight8447  42070  ORD-PHL              1.9          93
8447  Flight8448  42250  ORD-LGA              2.3          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8446             0.791667               275       50875             3
8447             0.666667               275       50875             9

      Flight Year
8446         2015
8447         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8448  Flight8449  42229  ORD-SEA              2.5          24
8449  Flight8450  41991  ORD-LAX              2.9         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8448             0.708333               385       71225             8
8449             0.729167               350       64750            12

      Flight Year
8448         2015
8449         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8450  Flight8451  41728  ORD-DFW              1.1         109
8451  Flight8452  41857  ORD-LAS              2.5         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8450                 0.50             200.0     37000.0             3
8451                 0.75             302.5     55962.5             8

      Flight Year
8450         2014
8451         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8452  Flight8453  42193  ORD-MIA              1.4         115
8453  Flight8454  41886  ORD-ATL              9.4          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8452             0.291667               330       61050             7
8453             0.895833               200       33000             9

      Flight Year
8452         2015
8453         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8454  Flight8455  42053  ORD-LGA              1.9         128
8455  Flight8456  41851  ORD-LAS              2.8         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8454             0.791667             275.0     50875.0             2
8455             0.791667             302.5     49912.5             7

      Flight Year
8454         2015
8455         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8456  Flight8457  42336  ORD-CLT              5.7           1
8457  Flight8458  42203  ORD-CLT              2.7          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8456             0.458333             187.5     34687.5            11
8457             0.604167             137.5     24887.5             7

      Flight Year
8456         2015
8457         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8458  Flight8459  42270  ORD-SFO              1.6         107
8459  Flight8460  41691  ORD-LAS              0.6         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8458               0.5625               375       69375             9
8459               0.8750               275       45375             2

      Flight Year
8458         2015
8459         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8460  Flight8461  41923  ORD-ATL             10.7          23
8461  Flight8462  42285  ORD-SFO              1.8          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8460             0.333333               200       37000            10
8461             0.333333               375       67875            10

      Flight Year
8460         2014
8461         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8462  Flight8463  42201  ORD-JFK              1.5          49
8463  Flight8464  41676  ORD-PHL              1.6         201

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8462             0.833333               275       45375             7
8463             0.770833               275       45375             2

      Flight Year
8462         2015
8463         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8464  Flight8465  41702  ORD-LAX              3.6          83
8465  Flight8466  42143  ORD-MIA              2.6         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8464                0.500               350       63350             3
8465                0.875               300       49500             5

      Flight Year
8464         2014
8465         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8466  Flight8467  41935  ORD-DFW              2.0         193
8467  Flight8468  42177  ORD-LGA              1.7         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8466             0.354167             200.0     33000.0            10
8467             0.791667             302.5     55962.5             6

      Flight Year
8466         2014
8467         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8468  Flight8469  42211  ORD-DFW              2.9         124
8469  Flight8470  42154  ORD-MSP              2.1         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8468             0.312500               220       40700             7
8469             0.708333               115       21275             5

      Flight Year
8468         2015
8469         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8470  Flight8471  41759  ORD-CLT              1.6          63
8471  Flight8472  42042  ORD-PHX              2.5          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8470             0.708333               125       22625             4
8471             0.708333               250       46250             2

      Flight Year
8470         2014
8471         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8472  Flight8473  41966  ORD-MCO              1.2         117
8473  Flight8474  42222  ORD-PHX              2.1         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8472             0.416667               250       46250            11
8473             0.791667               275       45375             8

      Flight Year
8472         2014
8473         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8474  Flight8475  42005  ORD-MSP              1.1          24
8475  Flight8476  42224  ORD-JFK              2.4         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8474             0.770833               115       21275             1
8475             0.291667               275       50875             8

      Flight Year
8474         2015
8475         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8476  Flight8477  41797  ORD-CLT              1.4          91
8477  Flight8478  42124  ORD-CLT              1.5         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8476             0.791667             137.5     25437.5             6
8477             0.437500             125.0     20625.0             4

      Flight Year
8476         2014
8477         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8478  Flight8479  42307  ORD-LGA              2.7          45
8479  Flight8480  42362  ORD-DEN              4.5         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8478             0.729167               275       45375            10
8479             0.791667               420       69300            12

      Flight Year
8478         2015
8479         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8480  Flight8481  41879  ORD-LAX              4.6           3
8481  Flight8482  41956  ORD-MSP              1.5         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8480             0.541667               385       71225             8
8481             0.645833               115       21275            11

      Flight Year
8480         2014
8481         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8482  Flight8483  41862  ORD-DEN              1.5          46
8483  Flight8484  42197  ORD-SEA              3.6         209

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8482             0.333333               330       54450             8
8483             0.291667               385       63525             7

      Flight Year
8482         2014
8483         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8484  Flight8485  42248  ORD-MCO              2.6         125
8485  Flight8486  41903  ORD-DFW              1.8         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8484                  0.5               250       46250             9
8485                  0.5               200       37000             9

      Flight Year
8484         2015
8485         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8486  Flight8487  41904  ORD-MCO              1.8         146
8487  Flight8488  41993  ORD-BWI              1.8         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8486             0.416667               250       46250             9
8487             0.750000               240       44400            12

      Flight Year
8486         2014
8487         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8488  Flight8489  41826  ORD-IAH              2.3         127
8489  Flight8490  42149  ORD-EWR              1.2          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8488             0.729167               220       40700             7
8489             0.458333               225       40725             5

      Flight Year
8488         2014
8489         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8490  Flight8491  42219  ORD-DEN              0.8          39
8491  Flight8492  42317  ORD-BOS              2.0         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8490                0.875               330       54450             8
8491                0.500               300       55500            11

      Flight Year
8490         2015
8491         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8492  Flight8493  41874  ORD-ATL             11.4         203
8493  Flight8494  42206  ORD-LAX              3.7         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8492             0.541667               220       36300             8
8493             0.291667               385       63525             7

      Flight Year
8492         2014
8493         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8494  Flight8495  42189  ORD-SEA              1.2         175
8495  Flight8496  41683  ORD-MCO              1.9         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8494             0.333333               385       63525             7
8495             0.750000               250       46250             2

      Flight Year
8494         2015
8495         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8496  Flight8497  42263  ORD-MCO              2.2         137
8497  Flight8498  41649  ORD-DTW              2.0         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8496             0.354167               250       46250             9
8497             0.312500               115       18975             1

      Flight Year
8496         2015
8497         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8498  Flight8499  41888  ORD-ATL              6.0          34
8499  Flight8500  41671  ORD-LAX              4.2          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8498             0.750000               200       37000             9
8499             0.291667               350       63350             2

      Flight Year
8498         2014
8499         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8500  Flight8501  42274  ORD-DTW              1.5         143
8501  Flight8502  41922  ORD-MCO              0.7          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8500             0.791667               115       21275             9
8501             0.770833               250       41250            10

      Flight Year
8500         2015
8501         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8502  Flight8503  42325  ORD-PHL              2.3         101
8503  Flight8504  42017  ORD-MCO              2.4          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8502             0.708333               275       50875            11
8503             0.333333               250       41250             1

      Flight Year
8502         2015
8503         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8504  Flight8505  42368  ORD-DFW              1.2         124
8505  Flight8506  41996  ORD-DEN              4.3           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8504             0.500000               200       37000            12
8505             0.833333               420       77700            12

      Flight Year
8504         2015
8505         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8506  Flight8507  41801  ORD-SFO              0.9           4
8507  Flight8508  41862  ORD-SFO              0.8          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8506             0.750000             412.5     76312.5             6
8507             0.895833             412.5     76312.5             8

      Flight Year
8506         2014
8507         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8508  Flight8509  41876  ORD-DEN              1.5          86
8509  Flight8510  42134  ORD-ATL             10.8          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8508             0.750000               330       59730             8
8509             0.291667               200       36200             5

      Flight Year
8508         2014
8509         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8510  Flight8511  41966  ORD-DFW              1.5         160
8511  Flight8512  41837  ORD-LAS              2.0          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8510             0.750000             200.0     33000.0            11
8511             0.708333             302.5     55962.5             7

      Flight Year
8510         2014
8511         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8512  Flight8513  41966  ORD-SFO              1.9         180
8513  Flight8514  42302  ORD-IAH              2.5          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8512             0.291667               375       61875            11
8513             0.791667               200       36200            10

      Flight Year
8512         2014
8513         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8514  Flight8515  41962  ORD-LAX              4.6          73
8515  Flight8516  42261  ORD-MIA              1.0         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8514             0.645833               350       63350            11
8515             0.791667               300       55500             9

      Flight Year
8514         2014
8515         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8516  Flight8517  41693  ORD-SEA              1.2          18
8517  Flight8518  41980  ORD-IAH              1.2          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8516             0.479167               350       64750             2
8517             0.312500               200       37000            12

      Flight Year
8516         2014
8517         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8518  Flight8519  42154  ORD-JFK              2.0           7
8519  Flight8520  42303  ORD-IAH              3.2           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8518             0.833333               250       46250             5
8519             0.833333               200       37000            10

      Flight Year
8518         2015
8519         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8520  Flight8521  42156  ORD-PHX              2.3         133
8521  Flight8522  41995  ORD-DTW              5.9         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8520             0.645833               275       50875             6
8521             0.541667               161       26565            12

      Flight Year
8520         2015
8521         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8522  Flight8523  41953  ORD-LAX              5.5         115
8523  Flight8524  41888  ORD-JFK              2.4         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8522             0.333333               350       64750            11
8523             0.708333               250       41250             9

      Flight Year
8522         2014
8523         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8524  Flight8525  42165  ORD-DEN              2.5         116
8525  Flight8526  42313  ORD-JFK              0.7          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8524             0.791667               330       61050             6
8525             0.333333               250       41250            11

      Flight Year
8524         2015
8525         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8526  Flight8527  41962  ORD-EWR              3.0           4
8527  Flight8528  42355  ORD-LGA              2.2          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8526             0.625000               225       41625            11
8527             0.395833               275       45375            12

      Flight Year
8526         2014
8527         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8528  Flight8529  41742  ORD-LAX              3.3          25
8529  Flight8530  41948  ORD-PHL              2.4          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8528             0.729167               350       64750             4
8529             0.625000               275       50875            11

      Flight Year
8528         2014
8529         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8530  Flight8531  42327  ORD-SEA              1.8         130
8531  Flight8532  42340  ORD-MCO              1.2         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8530             0.729167               350       64750            11
8531             0.333333               250       46250            12

      Flight Year
8530         2015
8531         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8532  Flight8533  41777  ORD-JFK              1.9          14
8533  Flight8534  42340  ORD-SEA              1.7          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8532             0.291667               250       46250             5
8533             0.500000               350       57750            12

      Flight Year
8532         2014
8533         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8534  Flight8535  42192  ORD-BOS              2.1          37
8535  Flight8536  41897  ORD-LGA              1.4          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8534             0.458333               330       54450             7
8535             0.687500               275       45375             9

      Flight Year
8534         2015
8535         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8536  Flight8537  42221  ORD-MIA              1.2         148
8537  Flight8538  41936  ORD-DFW              1.1          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8536             0.708333               330       61050             8
8537             0.875000               200       37000            10

      Flight Year
8536         2015
8537         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8538  Flight8539  41813  ORD-SFO              1.9         147
8539  Flight8540  42005  ORD-JFK              1.3          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8538             0.708333             412.5     76312.5             6
8539             0.375000             250.0     46250.0             1

      Flight Year
8538         2014
8539         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8540  Flight8541  41809  ORD-ATL              6.0         132
8541  Flight8542  42149  ORD-LAS              0.4          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8540             0.291667               220       40700             6
8541             0.791667               275       45375             5

      Flight Year
8540         2014
8541         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8542  Flight8543  42118  ORD-ATL             11.5          71
8543  Flight8544  42333  ORD-IAH              4.7          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8542             0.375000               200       36200             4
8543             0.541667               300       55500            11

      Flight Year
8542         2015
8543         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8544  Flight8545  42232  ORD-ATL              8.9         117
8545  Flight8546  42007  ORD-LAX              3.9         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8544             0.458333               220       40700             8
8545             0.458333               350       57750             1

      Flight Year
8544         2015
8545         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8546  Flight8547  42281  ORD-DFW              2.4         208
8547  Flight8548  41734  ORD-MIA              2.5          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8546             0.562500               200       33000            10
8547             0.833333               300       54300             4

      Flight Year
8546         2015
8547         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8548  Flight8549  41852  ORD-PHL              1.5          30
8549  Flight8550  42271  ORD-BOS              2.7         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8548                0.750             302.5     55962.5             8
8549                0.375             300.0     55500.0             9

      Flight Year
8548         2014
8549         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8550  Flight8551  41678  ORD-DFW              3.2           7
8551  Flight8552  41721  ORD-MCO              1.5         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8550             0.416667               200       37000             2
8551             0.833333               250       46250             3

      Flight Year
8550         2014
8551         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8552  Flight8553  42043  ORD-PHX              1.0         191
8553  Flight8554  41737  ORD-BWI              2.1          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8552             0.854167               250       41250             2
8553             0.333333               240       44400             4

      Flight Year
8552         2015
8553         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8554  Flight8555  42107  ORD-JFK              3.0           1
8555  Flight8556  41947  ORD-JFK              0.8         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8554             0.541667               250       46250             4
8555             0.500000               250       41250            11

      Flight Year
8554         2015
8555         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8556  Flight8557  41802  ORD-SEA              2.4         187
8557  Flight8558  41957  ORD-LAS              2.6          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8556             0.791667               385       63525             6
8557             0.791667               275       49775            11

      Flight Year
8556         2014
8557         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8558  Flight8559  41918  ORD-DFW              1.8         199
8559  Flight8560  41944  ORD-DFW              1.5         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8558             0.791667               200       33000            10
8559             0.354167               200       33000            11

      Flight Year
8558         2014
8559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8560  Flight8561  41879  ORD-BOS              1.8         181
8561  Flight8562  41699  ORD-SFO              2.0          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8560             0.291667               330       54450             8
8561             0.791667               375       69375             3

      Flight Year
8560         2014
8561         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8562  Flight8563  41901  ORD-DTW              1.9          78
8563  Flight8564  41707  ORD-LAX              3.3          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8562             0.812500               115       20815             9
8563             0.708333               350       63350             3

      Flight Year
8562         2014
8563         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8564  Flight8565  42164  ORD-PHL              2.5           1
8565  Flight8566  42360  ORD-LAX              8.9         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8564             0.875000             302.5     55962.5             6
8565             0.666667             490.0     80850.0            12

      Flight Year
8564         2015
8565         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8566  Flight8567  42195  ORD-LAX              3.2          63
8567  Flight8568  41786  ORD-DFW              2.3          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8566             0.479167               385       69685             7
8567             0.833333               200       37000             5

      Flight Year
8566         2015
8567         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8568  Flight8569  42219  ORD-MIA              1.0          56
8569  Flight8570  41871  ORD-JFK              1.7         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8568             0.291667               330       54450             8
8569             0.291667               275       45375             8

      Flight Year
8568         2015
8569         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8570  Flight8571  42360  ORD-BOS              4.9         178
8571  Flight8572  42133  ORD-LAX              3.2         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8570             0.291667               420       69300            12
8571             0.604167               350       64750             5

      Flight Year
8570         2015
8571         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8572  Flight8573  42261  ORD-LAS              0.7         209
8573  Flight8574  41999  ORD-PHL              4.6         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8572             0.479167               275       45375             9
8573             0.750000               385       71225            12

      Flight Year
8572         2015
8573         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8574  Flight8575  41685  ORD-JFK              2.4          69
8575  Flight8576  42244  ORD-JFK              2.5         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8574             0.770833               250       45250             2
8575             0.333333               275       45375             8

      Flight Year
8574         2014
8575         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8576  Flight8577  41826  ORD-LAS              1.5         165
8577  Flight8578  41835  ORD-DEN              1.6         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8576             0.854167             302.5     49912.5             7
8577             0.416667             330.0     61050.0             7

      Flight Year
8576         2014
8577         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8578  Flight8579  42317  ORD-IAH              1.5         188
8579  Flight8580  41716  ORD-CLT              2.4         143

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8578             0.791667               200       33000            11
8579             0.458333               125       23125             3

      Flight Year
8578         2015
8579         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8580  Flight8581  42245  ORD-LGA              2.7         149
8581  Flight8582  42237  ORD-LAS              0.5          33

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8580             0.791667             302.5     55962.5             8
8581             0.583333             302.5     55962.5             8

      Flight Year
8580         2015
8581         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8582  Flight8583  42189  ORD-MIA              2.4         130
8583  Flight8584  42335  ORD-MCO              5.9          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8582             0.583333               330       61050             7
8583             0.291667               375       67875            11

      Flight Year
8582         2015
8583         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8584  Flight8585  42297  ORD-DEN              2.1          57
8585  Flight8586  41709  ORD-ATL             10.9         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8584             0.708333               300       49500            10
8585             0.291667               200       37000             3

      Flight Year
8584         2015
8585         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8586  Flight8587  41908  ORD-DEN              2.2         117
8587  Flight8588  42289  ORD-LGA              1.9         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8586             0.770833               300       55500             9
8587             0.583333               275       45375            10

      Flight Year
8586         2014
8587         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8588  Flight8589  41842  ORD-LAS              2.3          34
8589  Flight8590  42165  ORD-LAS              2.4         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8588             0.854167             302.5     55962.5             7
8589             0.750000             302.5     55962.5             6

      Flight Year
8588         2014
8589         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8590  Flight8591  42276  ORD-MIA              1.7          72
8591  Flight8592  41843  ORD-PHX              3.1         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8590             0.333333               300       54300             9
8591             0.750000               275       45375             7

      Flight Year
8590         2015
8591         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8592  Flight8593  42116  ORD-DEN              1.3           9
8593  Flight8594  41942  ORD-MIA              3.8         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8592             0.541667               300       55500             4
8593             0.750000               300       49500            10

      Flight Year
8592         2015
8593         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8594  Flight8595  42181  ORD-FLL              1.9         140
8595  Flight8596  42024  ORD-PHX              2.8          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8594             0.375000               330       61050             6
8595             0.333333               250       46250             1

      Flight Year
8594         2015
8595         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8596  Flight8597  42333  ORD-SFO              3.9         153
8597  Flight8598  41866  ORD-SFO              2.8         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8596             0.479167             562.5     92812.5            11
8597             0.812500             412.5     76312.5             8

      Flight Year
8596         2015
8597         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8598  Flight8599  42325  ORD-CLT              2.6         143
8599  Flight8600  41733  ORD-IAH              1.8         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8598               0.6250               125       23125            11
8599               0.8125               200       33000             4

      Flight Year
8598         2015
8599         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8600  Flight8601  41889  ORD-DTW              1.6         152
8601  Flight8602  41877  ORD-IAD              1.8          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8600             0.291667               115       18975             9
8601             0.791667               330       61050             8

      Flight Year
8600         2014
8601         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8602  Flight8603  41953  ORD-SFO              2.4          91
8603  Flight8604  41849  ORD-MCO              1.8         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8602             0.708333               375       69375            11
8603             0.333333               275       45375             7

      Flight Year
8602         2014
8603         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8604  Flight8605  41760  ORD-LAX              3.7         166
8605  Flight8606  42089  ORD-MSP              2.0         191

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8604                 0.75               350       57750             5
8605                 0.75               115       18975             3

      Flight Year
8604         2014
8605         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8606  Flight8607  42336  ORD-PHX              5.3         136
8607  Flight8608  42250  ORD-EWR              2.6         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8606             0.708333               375       69375            11
8607             0.333333               225       37125             9

      Flight Year
8606         2015
8607         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8608  Flight8609  41783  ORD-ATL             10.0           1
8609  Flight8610  41816  ORD-MIA              2.5         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8608             0.708333               200       37000             5
8609             0.729167               330       54450             6

      Flight Year
8608         2014
8609         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8610  Flight8611  41824  ORD-LAX              4.8         113
8611  Flight8612  41814  ORD-DEN              2.8         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8610             0.770833               385       71225             7
8611             0.708333               330       54450             6

      Flight Year
8610         2014
8611         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8612  Flight8613  41740  ORD-IAH              1.0         191
8613  Flight8614  42196  ORD-DFW              1.2         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8612             0.291667               200       33000             4
8613             0.833333               220       36300             7

      Flight Year
8612         2014
8613         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8614  Flight8615  42035  ORD-IAH              0.9          10
8615  Flight8616  41729  ORD-CLT              2.8          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8614             0.750000               200       37000             1
8615             0.770833               125       20625             3

      Flight Year
8614         2015
8615         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8616  Flight8617  42270  ORD-PHX              1.1         105
8617  Flight8618  42156  ORD-MCO              2.4         188

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8616             0.875000               250       46250             9
8617             0.354167               275       45375             6

      Flight Year
8616         2015
8617         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8618  Flight8619  41730  ORD-LAX              4.9          82
8619  Flight8620  42008  ORD-SFO              1.5         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8618             0.708333               350       63350             4
8619             0.687500               375       61875             1

      Flight Year
8618         2014
8619         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8620  Flight8621  42037  ORD-DTW              2.2         116
8621  Flight8622  42023  ORD-LAX              4.5         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8620             0.708333               115       21275             2
8621             0.520833               350       57750             1

      Flight Year
8620         2015
8621         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8622  Flight8623  42240  ORD-LAS              2.8          63
8623  Flight8624  42362  ORD-PHX              4.8          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8622             0.541667             302.5     54752.5             8
8623             0.291667             350.0     64750.0            12

      Flight Year
8622         2015
8623         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8624  Flight8625  42190  ORD-BOS              2.0           3
8625  Flight8626  42209  ORD-BOS              2.4          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8624                 0.75               330       61050             7
8625                 0.75               330       59730             7

      Flight Year
8624         2015
8625         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8626  Flight8627  42143  ORD-SFO              0.5         153
8627  Flight8628  41913  ORD-CLT              2.4         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8626             0.333333               375       61875             5
8627             0.750000               125       20625            10

      Flight Year
8626         2015
8627         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8628  Flight8629  42295  ORD-CLT              1.0           7
8629  Flight8630  41657  ORD-SFO              1.7          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8628             0.291667               125       23125            10
8629             0.708333               375       61875             1

      Flight Year
8628         2015
8629         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8630  Flight8631  42326  ORD-LGA              2.0          36
8631  Flight8632  41663  ORD-MCO              1.6         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8630             0.333333               275       45375            11
8631             0.750000               250       41250             1

      Flight Year
8630         2015
8631         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8632  Flight8633  42319  ORD-DFW              2.6          72
8633  Flight8634  41956  ORD-DEN              2.7          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8632             0.708333               200       36200            11
8633             0.750000               300       55500            11

      Flight Year
8632         2015
8633         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8634  Flight8635  42157  ORD-BOS              1.8         200
8635  Flight8636  41907  ORD-MSP              1.5         179

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8634             0.854167               330       54450             6
8635             0.312500               115       18975             9

      Flight Year
8634         2015
8635         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8636  Flight8637  41716  ORD-ATL              8.1          25
8637  Flight8638  42258  ORD-IAH              1.8          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8636             0.354167               200       37000             3
8637             0.291667               200       33000             9

      Flight Year
8636         2014
8637         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8638  Flight8639  42330  ORD-DTW              2.6         163
8639  Flight8640  42228  ORD-LAX              4.7         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8638             0.520833               115       18975            11
8639             0.833333               385       63525             8

      Flight Year
8638         2015
8639         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8640  Flight8641  42214  ORD-MCO              1.2          79
8641  Flight8642  41860  ORD-MCO              1.8          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8640             0.875000               275       49775             7
8641             0.791667               275       50875             8

      Flight Year
8640         2015
8641         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8642  Flight8643  41774  ORD-JFK              1.8         150
8643  Flight8644  42298  ORD-PHL              1.4          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8642             0.333333               250       46250             5
8643             0.333333               275       49775            10

      Flight Year
8642         2014
8643         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8644  Flight8645  42042  ORD-MCO              2.7          27
8645  Flight8646  42222  ORD-MSP              0.7          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8644             0.708333             250.0     46250.0             2
8645             0.750000             126.5     22896.5             8

      Flight Year
8644         2015
8645         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8646  Flight8647  42252  ORD-BWI              2.2         165
8647  Flight8648  41976  ORD-DEN              2.2         144

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8646             0.750000               240       39600             9
8647             0.708333               300       55500            12

      Flight Year
8646         2015
8647         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8648  Flight8649  41794  ORD-PHX              3.1         176
8649  Flight8650  41825  ORD-ATL              9.8          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8648             0.708333               275       45375             6
8649             0.458333               220       36300             7

      Flight Year
8648         2014
8649         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8650  Flight8651  41737  ORD-ATL              6.0          71
8651  Flight8652  41728  ORD-LAS              3.5         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8650             0.375000               200       36200             4
8651             0.291667               275       45375             3

      Flight Year
8650         2014
8651         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8652  Flight8653  42245  ORD-LAS              2.6         163
8653  Flight8654  41795  ORD-ATL              9.3         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8652             0.708333             302.5     49912.5             8
8653             0.729167             220.0     36300.0             6

      Flight Year
8652         2015
8653         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8654  Flight8655  42134  ORD-LAS              2.9          79
8655  Flight8656  42034  ORD-DEN              1.3         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8654               0.8750               275       49775             5
8655               0.4375               300       55500             1

      Flight Year
8654         2015
8655         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8656  Flight8657  41705  ORD-LAX              3.4          99
8657  Flight8658  41874  ORD-EWR              1.5         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8656             0.708333             350.0     64750.0             3
8657             0.333333             247.5     45787.5             8

      Flight Year
8656         2014
8657         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8658  Flight8659  41960  ORD-LAS              1.4         153
8659  Flight8660  42342  ORD-JFK              1.0          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8658                 0.75               275       45375            11
8659                 0.75               250       46250            12

      Flight Year
8658         2014
8659         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8660  Flight8661  41735  ORD-LAX              1.7          18
8661  Flight8662  42003  ORD-EWR              2.6         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8660             0.312500               350       64750             4
8661             0.791667               225       41625            12

      Flight Year
8660         2014
8661         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8662  Flight8663  42173  ORD-EWR              2.0         186
8663  Flight8664  42098  ORD-BOS              3.2         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8662             0.354167             247.5     40837.5             6
8663             0.291667             300.0     55500.0             4

      Flight Year
8662         2015
8663         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8664  Flight8665  42269  ORD-LGA              2.2         129
8665  Flight8666  42314  ORD-LAX              4.7         174

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8664             0.750000               275       50875             9
8665             0.520833               350       57750            11

      Flight Year
8664         2015
8665         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8666  Flight8667  41942  ORD-LAX              5.3         100
8667  Flight8668  42078  ORD-IAH              3.2         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8666             0.750000               350       64750            10
8667             0.333333               200       37000             3

      Flight Year
8666         2014
8667         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8668  Flight8669  41961  ORD-LAS              3.0         123
8669  Flight8670  41888  ORD-IAH              0.9         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8668             0.791667               275       50875            11
8669             0.875000               200       33000             9

      Flight Year
8668         2014
8669         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8670  Flight8671  42298  ORD-PHX              2.7          46
8671  Flight8672  42292  ORD-MSP              1.6          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8670             0.791667               250       41250            10
8671             0.708333               115       18975            10

      Flight Year
8670         2015
8671         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8672  Flight8673  41685  ORD-DTW              1.5          60
8673  Flight8674  41813  ORD-LGA              2.1          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8672             0.708333             115.0     18975.0             2
8673             0.708333             302.5     55962.5             6

      Flight Year
8672         2014
8673         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8674  Flight8675  42055  ORD-DTW              1.3           3
8675  Flight8676  42116  ORD-EWR              3.2          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8674             0.375000               115       21275             2
8675             0.791667               225       37125             4

      Flight Year
8674         2015
8675         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8676  Flight8677  42337  ORD-SLC                7          48
8677  Flight8678  41648  ORD-EWR                1         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8676             0.520833               435       71775            11
8677             0.770833               225       41625             1

      Flight Year
8676         2015
8677         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8678  Flight8679  41813  ORD-CLT              2.5          88
8679  Flight8680  42334  ORD-DEN              6.1          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8678             0.708333             137.5     24887.5             6
8679             0.583333             450.0     81450.0            11

      Flight Year
8678         2014
8679         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8680  Flight8681  42140  ORD-ATL              8.0         135
8681  Flight8682  41773  ORD-IAH              0.9         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8680             0.333333               200       37000             5
8681             0.895833               200       37000             5

      Flight Year
8680         2015
8681         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8682  Flight8683  41793  ORD-IAH              0.8         209
8683  Flight8684  42042  ORD-MIA              2.0          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8682             0.625000               220       36300             6
8683             0.895833               300       49500             2

      Flight Year
8682         2014
8683         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8684  Flight8685  42091  ORD-PHL              2.2         101
8685  Flight8686  42360  ORD-PHX              4.9         140

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8684             0.541667               275       50875             3
8685             0.833333               350       64750            12

      Flight Year
8684         2015
8685         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8686  Flight8687  41853  ORD-CLT              0.7          62
8687  Flight8688  42060  ORD-FLL              1.7          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8686             0.291667             137.5     22687.5             8
8687             0.333333             300.0     49500.0             2

      Flight Year
8686         2014
8687         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8688  Flight8689  42097  ORD-LAX              5.0         117
8689  Flight8690  42180  ORD-MIA              1.9         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8688                0.500               350       64750             4
8689                0.375               330       54450             6

      Flight Year
8688         2015
8689         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8690  Flight8691  41658  ORD-EWR              1.8          68
8691  Flight8692  41842  ORD-JFK              1.7          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8690               0.3125               225       40725             1
8691               0.3125               275       49775             7

      Flight Year
8690         2014
8691         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8692  Flight8693  41813  ORD-JFK              1.4           3
8693  Flight8694  42187  ORD-FLL              1.2         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8692             0.333333               275       50875             6
8693             0.791667               330       61050             7

      Flight Year
8692         2014
8693         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8694  Flight8695  41908  ORD-SFO              1.2          82
8695  Flight8696  42276  ORD-ATL              9.4         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8694             0.687500               375       67875             9
8695             0.666667               200       37000             9

      Flight Year
8694         2014
8695         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8696  Flight8697  42223  ORD-PHX              2.8          40
8697  Flight8698  42212  ORD-BWI              2.0         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8696             0.333333               275       45375             8
8697             0.708333               264       43560             7

      Flight Year
8696         2015
8697         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8698  Flight8699  41832  ORD-MIA              2.0          51
8699  Flight8700  41754  ORD-JFK              1.9         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8698             0.583333               330       54450             7
8699             0.750000               250       41250             4

      Flight Year
8698         2014
8699         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8700  Flight8701  41653  ORD-MCO              2.9          24
8701  Flight8702  42262  ORD-LAS              3.7         134

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8700             0.395833               250       46250             1
8701             0.333333               275       50875             9

      Flight Year
8700         2014
8701         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8702  Flight8703  42107  ORD-LGA              1.2         120
8703  Flight8704  42134  ORD-MIA              1.4         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8702             0.708333               275       50875             4
8703             0.708333               300       55500             5

      Flight Year
8702         2015
8703         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8704  Flight8705  41703  ORD-EWR              2.2          60
8705  Flight8706  41780  ORD-DEN              2.5         113

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8704             0.833333               225       37125             3
8705             0.791667               300       55500             5

      Flight Year
8704         2014
8705         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8706  Flight8707  41850  ORD-BOS              3.0          75
8707  Flight8708  41791  ORD-DEN              1.7          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8706             0.791667               330       59730             7
8707             0.750000               330       61050             6

      Flight Year
8706         2014
8707         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8708  Flight8709  41814  ORD-ATL             12.3          40
8709  Flight8710  42064  ORD-DEN              3.2          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8708             0.437500               220       36300             6
8709             0.354167               300       49500             3

      Flight Year
8708         2014
8709         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8710  Flight8711  41985  ORD-BWI              2.3         129
8711  Flight8712  42090  ORD-MSP              2.8         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8710             0.708333               240       44400            12
8711             0.291667               115       18975             3

      Flight Year
8710         2014
8711         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8712  Flight8713  42349  ORD-SEA              2.7         177
8713  Flight8714  41710  ORD-LAX              4.5         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8712             0.541667               350       57750            12
8713             0.750000               350       64750             3

      Flight Year
8712         2015
8713         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8714  Flight8715  42054  ORD-PHL              3.2          16
8715  Flight8716  42153  ORD-LAS              2.1         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8714             0.375000               275       50875             2
8715             0.729167               275       45375             5

      Flight Year
8714         2015
8715         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8716  Flight8717  41736  ORD-DEN              2.8         102
8717  Flight8718  41800  ORD-EWR              2.4           6

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8716             0.708333             300.0     55500.0             4
8717             0.750000             247.5     45787.5             6

      Flight Year
8716         2014
8717         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8718  Flight8719  42165  ORD-DFW              1.8         150
8719  Flight8720  41641  ORD-PHL              2.2          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8718                0.750               220       40700             6
8719                0.625               275       45375             1

      Flight Year
8718         2015
8719         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8720  Flight8721  41851  ORD-DFW              0.5           4
8721  Flight8722  42261  ORD-PHX              2.2         163

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8720             0.708333               220       40700             7
8721             0.750000               250       41250             9

      Flight Year
8720         2014
8721         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8722  Flight8723  42234  ORD-JFK              1.4         166
8723  Flight8724  42020  ORD-SFO              1.1          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8722             0.458333               275       45375             8
8723             0.541667               375       69375             1

      Flight Year
8722         2015
8723         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8724  Flight8725  41983  ORD-CLT              1.3         173
8725  Flight8726  42150  ORD-SFO              2.4          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8724             0.500000               125       20625            12
8725             0.791667               375       69375             5

      Flight Year
8724         2014
8725         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8726  Flight8727  41702  ORD-LAX              4.6          10
8727  Flight8728  41754  ORD-SEA              1.9          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8726             0.791667               350       64750             3
8727             0.750000               350       64750             4

      Flight Year
8726         2014
8727         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8728  Flight8729  41851  ORD-SEA              0.8          72
8729  Flight8730  42205  ORD-JFK              0.7          83

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8728             0.770833               385       69685             7
8729             0.750000               275       49775             7

      Flight Year
8728         2014
8729         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8730  Flight8731  42123  ORD-EWR              2.1          39
8731  Flight8732  42025  ORD-LAX              4.0         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8730               0.8125               225       37125             4
8731               0.8750               350       64750             1

      Flight Year
8730         2015
8731         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8732  Flight8733  41891  ORD-LGA              2.4         142
8733  Flight8734  42034  ORD-ATL              8.5         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8732             0.458333               275       50875             9
8733             0.833333               200       33000             1

      Flight Year
8732         2014
8733         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8734  Flight8735  42094  ORD-DTW              1.7         154
8735  Flight8736  41791  ORD-LGA              2.2         118

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8734             0.458333             115.0     18975.0             3
8735             0.791667             302.5     55962.5             6

      Flight Year
8734         2015
8735         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8736  Flight8737  42300  ORD-SFO              1.6         201
8737  Flight8738  42283  ORD-DFW              1.6         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8736             0.750000               375       61875            10
8737             0.833333               200       37000            10

      Flight Year
8736         2015
8737         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8738  Flight8739  42312  ORD-JFK              1.6         183
8739  Flight8740  42081  ORD-DEN              3.1         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8738             0.708333               250       41250            11
8739             0.812500               300       55500             3

      Flight Year
8738         2015
8739         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8740  Flight8741  42239  ORD-DEN              1.5         150
8741  Flight8742  41683  ORD-SFO              1.9          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8740             0.333333               330       61050             8
8741             0.791667               375       67875             2

      Flight Year
8740         2015
8741         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8742  Flight8743  41651  ORD-CLT              1.0         143
8743  Flight8744  42041  ORD-BOS              2.2          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8742             0.354167               125       23125             1
8743             0.312500               300       55500             2

      Flight Year
8742         2014
8743         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8744  Flight8745  42250  ORD-ATL              8.2         152
8745  Flight8746  42323  ORD-SFO              2.3          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8744                 0.75               200       33000             9
8745                 0.75               375       61875            11

      Flight Year
8744         2015
8745         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8746  Flight8747  42216  ORD-CLT                2          73
8747  Flight8748  42227  ORD-DFW                2          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8746               0.8125             137.5     24887.5             7
8747               0.3125             220.0     40700.0             8

      Flight Year
8746         2015
8747         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8748  Flight8749  41991  ORD-JFK              0.3         119
8749  Flight8750  42343  ORD-SEA              2.7          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8748             0.812500               250       46250            12
8749             0.333333               350       64750            12

      Flight Year
8748         2014
8749         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8750  Flight8751  41821  ORD-JFK              2.6         166
8751  Flight8752  42163  ORD-DTW              2.2          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8750             0.416667             275.0     45375.0             7
8751             0.291667             126.5     22896.5             6

      Flight Year
8750         2014
8751         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8752  Flight8753  41931  ORD-DEN              1.7         184
8753  Flight8754  42009  ORD-PHL              1.9         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8752             0.291667               300       49500            10
8753             0.333333               275       50875             1

      Flight Year
8752         2014
8753         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8754  Flight8755  42335  ORD-SEA              4.1         178
8755  Flight8756  41692  ORD-LAX              5.9         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8754             0.729167               525       86625            11
8755             0.729167               350       64750             2

      Flight Year
8754         2015
8755         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8756  Flight8757  41792  ORD-SEA              2.2         195
8757  Flight8758  42145  ORD-LAS              1.6         135

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8756             0.541667               385       63525             6
8757             0.750000               275       50875             5

      Flight Year
8756         2014
8757         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8758  Flight8759  41882  ORD-LAX              4.1         185
8759  Flight8760  41867  ORD-BOS              2.0         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8758             0.375000               385       63525             8
8759             0.291667               330       61050             8

      Flight Year
8758         2014
8759         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8760  Flight8761  42125  ORD-CLT              1.3          81
8761  Flight8762  42075  ORD-LAX              4.2         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8760             0.833333               125       22625             5
8761             0.750000               350       64750             3

      Flight Year
8760         2015
8761         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8762  Flight8763  41783  ORD-BOS              2.5         113
8763  Flight8764  42184  ORD-PHX              1.8          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8762             0.333333               300       55500             5
8763             0.458333               275       45375             6

      Flight Year
8762         2014
8763         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8764  Flight8765  42327  ORD-PHX              1.3          73
8765  Flight8766  41873  ORD-EWR              2.6         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8764             0.708333             250.0     45250.0            11
8765             0.708333             247.5     45787.5             8

      Flight Year
8764         2015
8765         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8766  Flight8767  41656  ORD-MIA              0.9         158
8767  Flight8768  42205  ORD-MCO              1.3          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8766             0.375000               300       49500             1
8767             0.708333               275       49775             7

      Flight Year
8766         2014
8767         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8768  Flight8769  41896  ORD-MSP              0.7          44
8769  Flight8770  42187  ORD-MIA              1.6         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8768             0.312500               115       18975             9
8769             0.291667               330       54450             7

      Flight Year
8768         2014
8769         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8770  Flight8771  42007  ORD-IAH              2.6         146
8771  Flight8772  41821  ORD-DFW              3.0          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8770             0.833333               200       37000             1
8771             0.291667               220       40700             7

      Flight Year
8770         2015
8771         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8772  Flight8773  41794  ORD-DEN              1.1          25
8773  Flight8774  42322  ORD-DEN              3.1           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8772             0.291667               330       61050             6
8773             0.791667               300       55500            11

      Flight Year
8772         2014
8773         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8774  Flight8775  42074  ORD-CLT              1.1          11
8775  Flight8776  42066  ORD-MIA              1.8         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8774             0.583333               125       23125             3
8775             0.291667               300       55500             3

      Flight Year
8774         2015
8775         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8776  Flight8777  41998  ORD-SEA              4.9         102
8777  Flight8778  42333  ORD-DEN              3.2           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8776             0.437500               490       90650            12
8777             0.291667               450       83250            11

      Flight Year
8776         2014
8777         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8778  Flight8779  41658  ORD-LAX              4.7         131
8779  Flight8780  41668  ORD-DEN              2.5         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8778             0.562500               350       64750             1
8779             0.791667               300       55500             1

      Flight Year
8778         2014
8779         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8780  Flight8781  42362  ORD-CLT              4.4         208
8781  Flight8782  41724  ORD-JFK              2.2         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8780             0.708333               175       28875            12
8781             0.458333               250       46250             3

      Flight Year
8780         2015
8781         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8782  Flight8783  41743  ORD-DFW              1.6          79
8783  Flight8784  41959  ORD-JFK              2.3         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8782             0.645833               200       36200             4
8783             0.291667               250       41250            11

      Flight Year
8782         2014
8783         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8784  Flight8785  42108  ORD-LAS              1.8         103
8785  Flight8786  41673  ORD-LAS              1.8         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8784             0.312500               275       50875             4
8785             0.729167               275       50875             2

      Flight Year
8784         2015
8785         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8786  Flight8787  41778  ORD-DEN              2.0         112
8787  Flight8788  41911  ORD-MSP              2.1          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8786             0.750000               300       55500             5
8787             0.333333               115       20815             9

      Flight Year
8786         2014
8787         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8788  Flight8789  42200  ORD-MIA              2.4          60
8789  Flight8790  41793  ORD-FLL              0.8         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8788             0.333333               330       54450             7
8789             0.562500               330       61050             6

      Flight Year
8788         2015
8789         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8790  Flight8791  41803  ORD-LAS              1.2         101
8791  Flight8792  42328  ORD-PHL              2.6         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8790             0.770833             302.5     55962.5             6
8791             0.833333             275.0     45375.0            11

      Flight Year
8790         2014
8791         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8792  Flight8793  41891  ORD-MSP              1.9         164
8793  Flight8794  42317  ORD-JFK              1.0          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8792             0.895833               115       18975             9
8793             0.583333               250       46250            11

      Flight Year
8792         2014
8793         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8794  Flight8795  42192  ORD-JFK              3.0         154
8795  Flight8796  41903  ORD-EWR              2.6         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8794             0.833333               275       45375             7
8795             0.458333               225       37125             9

      Flight Year
8794         2015
8795         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8796  Flight8797  42185  ORD-CLT              2.7           7
8797  Flight8798  41673  ORD-DFW              1.6          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8796             0.895833             137.5     25437.5             6
8797             0.895833             200.0     33000.0             2

      Flight Year
8796         2015
8797         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8798  Flight8799  41856  ORD-PHX              0.8         202
8799  Flight8800  42255  ORD-BOS              2.7         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8798             0.729167               275       45375             8
8799             0.333333               300       49500             9

      Flight Year
8798         2014
8799         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8800  Flight8801  42015  ORD-LAS              0.9         134
8801  Flight8802  42061  ORD-LGA              1.6          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8800             0.500000               275       50875             1
8801             0.604167               275       50875             2

      Flight Year
8800         2015
8801         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8802  Flight8803  42177  ORD-ATL             10.3         116
8803  Flight8804  42295  ORD-PHL              2.6         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8802             0.708333               220       40700             6
8803             0.291667               275       50875            10

      Flight Year
8802         2015
8803         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8804  Flight8805  41983  ORD-PHL              2.0          17
8805  Flight8806  41670  ORD-DCA              1.9          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8804             0.791667               275       50875            12
8805             0.750000              5000      925000             1

      Flight Year
8804         2014
8805         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8806  Flight8807  42007  ORD-DFW              2.3         111
8807  Flight8808  42113  ORD-DFW              2.8         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8806             0.500000               200       37000             1
8807             0.583333               200       33000             4

      Flight Year
8806         2015
8807         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8808  Flight8809  41932  ORD-JFK              2.5          45
8809  Flight8810  42113  ORD-ATL              8.4         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8808             0.291667               250       41250            10
8809             0.708333               200       33000             4

      Flight Year
8808         2014
8809         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8810  Flight8811  42007  ORD-DFW                2         100
8811  Flight8812  42042  ORD-MIA                2          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8810             0.791667               200       37000             1
8811             0.770833               300       55500             2

      Flight Year
8810         2015
8811         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8812  Flight8813  41882  ORD-ATL             10.0          25
8813  Flight8814  42174  ORD-JFK              1.4         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8812             0.791667               220       40700             8
8813             0.708333               275       45375             6

      Flight Year
8812         2014
8813         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8814  Flight8815  41804  ORD-PHL              3.0         198
8815  Flight8816  41753  ORD-ATL              9.3          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8814             0.291667             302.5     49912.5             6
8815             0.291667             200.0     36200.0             4

      Flight Year
8814         2014
8815         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8816  Flight8817  41642  ORD-PHL              2.9         102
8817  Flight8818  42198  ORD-DCA              1.9         187

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8816             0.812500               275       50875             1
8817             0.333333              5500      907500             7

      Flight Year
8816         2014
8817         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8818  Flight8819  41803  ORD-LAX              3.4         104
8819  Flight8820  41705  ORD-CLT              1.4         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8818             0.625000               385       71225             6
8819             0.291667               125       20625             3

      Flight Year
8818         2014
8819         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8820  Flight8821  41824  ORD-SEA              0.7         185
8821  Flight8822  41770  ORD-CLT              2.3          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8820             0.791667               385       63525             7
8821             0.541667               125       20625             5

      Flight Year
8820         2014
8821         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8822  Flight8823  42097  ORD-BWI              1.6          55
8823  Flight8824  41917  ORD-LAS              2.2          62

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8822               0.6250               240       39600             4
8823               0.3125               275       45375            10

      Flight Year
8822         2015
8823         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8824  Flight8825  42152  ORD-LAX              3.1          75
8825  Flight8826  41963  ORD-SFO              1.7          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8824             0.791667               350       63350             5
8825             0.541667               375       67875            11

      Flight Year
8824         2015
8825         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8826  Flight8827  41663  ORD-DEN              1.7         121
8827  Flight8828  41991  ORD-DEN              1.6         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8826             0.708333               300       55500             1
8827             0.541667               300       49500            12

      Flight Year
8826         2014
8827         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8828  Flight8829  42046  ORD-DFW              1.2          51
8829  Flight8830  42198  ORD-ATL             10.4         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8828             0.458333               200       33000             2
8829             0.416667               220       40700             7

      Flight Year
8828         2015
8829         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8830  Flight8831  41785  ORD-LAX              5.3          37
8831  Flight8832  41733  ORD-SEA              2.5         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8830             0.291667               350       57750             5
8831             0.750000               350       64750             4

      Flight Year
8830         2014
8831         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8832  Flight8833  41733  ORD-LGA              3.3          55
8833  Flight8834  42365  ORD-IAH              2.7         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8832             0.500000               275       45375             4
8833             0.354167               280       46200            12

      Flight Year
8832         2014
8833         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8834  Flight8835  42360  ORD-ATL             12.9         101
8835  Flight8836  41817  ORD-SFO              1.8         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8834             0.375000             280.0     51800.0            12
8835             0.291667             412.5     76312.5             6

      Flight Year
8834         2015
8835         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8836  Flight8837  42189  ORD-SFO              2.7         205
8837  Flight8838  42110  ORD-PHX              1.7          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8836             0.333333             412.5     68062.5             7
8837             0.750000             250.0     45250.0             4

      Flight Year
8836         2015
8837         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8838  Flight8839  42069  ORD-DFW              2.2         113
8839  Flight8840  42354  ORD-DEN              2.5         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8838             0.291667               200       37000             3
8839             0.291667               300       49500            12

      Flight Year
8838         2015
8839         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8840  Flight8841  42028  ORD-MIA              2.4         167
8841  Flight8842  42276  ORD-JFK              3.2         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8840             0.708333               300       49500             1
8841             0.291667               250       41250             9

      Flight Year
8840         2015
8841         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8842  Flight8843  41771  ORD-BOS              1.7         140
8843  Flight8844  42024  ORD-IAH              2.3         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8842             0.750000               300       55500             5
8843             0.333333               200       33000             1

      Flight Year
8842         2014
8843         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8844  Flight8845  41995  ORD-ATL             15.5         147
8845  Flight8846  42138  ORD-LAX              3.8           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8844             0.479167               280       51800            12
8845             0.833333               350       64750             5

      Flight Year
8844         2014
8845         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8846  Flight8847  41669  ORD-JFK              2.4          23
8847  Flight8848  41728  ORD-FLL              1.6         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8846             0.291667               250       46250             1
8847             0.708333               300       49500             3

      Flight Year
8846         2014
8847         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8848  Flight8849  41817  ORD-MSP              2.0           3
8849  Flight8850  41824  ORD-PHX              3.8         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8848             0.750000             126.5     23402.5             6
8849             0.666667             275.0     45375.0             7

      Flight Year
8848         2014
8849         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8850  Flight8851  41664  ORD-ATL              8.1         203
8851  Flight8852  42031  ORD-IAH              1.3          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8850                0.500               200       33000             1
8851                0.625               200       37000             1

      Flight Year
8850         2014
8851         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8852  Flight8853  42346  ORD-IAH              0.7         132
8853  Flight8854  41995  ORD-JFK              3.4          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8852             0.291667               200       37000            12
8853             0.833333               350       63350            12

      Flight Year
8852         2015
8853         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8854  Flight8855  41693  ORD-PHL              1.6          25
8855  Flight8856  41683  ORD-IAH              2.6          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8854             0.791667               275       50875             2
8855             0.333333               200       37000             2

      Flight Year
8854         2014
8855         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8856  Flight8857  42102  ORD-JFK              2.3         119
8857  Flight8858  41756  ORD-DFW              1.5         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8856             0.708333               250       46250             4
8857             0.791667               200       37000             4

      Flight Year
8856         2015
8857         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8858  Flight8859  41853  ORD-DEN              0.9          14
8859  Flight8860  42244  ORD-IAH              2.1          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8858             0.500000               330       61050             8
8859             0.354167               220       39820             8

      Flight Year
8858         2014
8859         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8860  Flight8861  41727  ORD-SEA              1.5         158
8861  Flight8862  42070  ORD-CLT              2.2         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8860             0.666667               350       57750             3
8861             0.291667               125       23125             3

      Flight Year
8860         2014
8861         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8862  Flight8863  42287  ORD-BWI              2.5          34
8863  Flight8864  41735  ORD-IAH              1.8         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8862             0.750000               240       44400            10
8863             0.583333               200       33000             4

      Flight Year
8862         2015
8863         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8864  Flight8865  41722  ORD-LGA              1.3         139
8865  Flight8866  42001  ORD-IAH              3.9         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8864             0.416667               275       50875             3
8865             0.354167               280       46200            12

      Flight Year
8864         2014
8865         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8866  Flight8867  42049  ORD-CLT              1.9         149
8867  Flight8868  42251  ORD-JFK              2.9         147

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8866             0.583333               125       23125             2
8867             0.708333               250       46250             9

      Flight Year
8866         2015
8867         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8868  Flight8869  41915  ORD-PHX              2.6          81
8869  Flight8870  41915  ORD-BOS              2.5          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8868             0.583333               250       45250            10
8869             0.729167               300       55500            10

      Flight Year
8868         2014
8869         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8870  Flight8871  42154  ORD-IAH              2.7         191
8871  Flight8872  41789  ORD-PHL              2.4          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8870             0.333333               200       33000             5
8871             0.583333               275       49775             5

      Flight Year
8870         2015
8871         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8872  Flight8873  42108  ORD-MSP              2.3         190
8873  Flight8874  42329  ORD-IAH              2.4           9

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8872             0.416667               115       18975             4
8873             0.333333               200       37000            11

      Flight Year
8872         2015
8873         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8874  Flight8875  41952  ORD-EWR              0.5         110
8875  Flight8876  41824  ORD-SEA              1.8         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8874             0.708333               225       41625            11
8875             0.812500               385       63525             7

      Flight Year
8874         2014
8875         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8876  Flight8877  41860  ORD-PHL              1.4          29
8877  Flight8878  42136  ORD-DTW              2.7          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8876             0.458333             302.5     55962.5             8
8877             0.333333             115.0     18975.0             5

      Flight Year
8876         2014
8877         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8878  Flight8879  42260  ORD-JFK              1.7         196
8879  Flight8880  41694  ORD-LGA              1.9          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8878             0.354167               250       41250             9
8879             0.791667               275       45375             2

      Flight Year
8878         2015
8879         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8880  Flight8881  42267  ORD-DEN              2.0          89
8881  Flight8882  42208  ORD-PHX              2.5         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8880             0.687500               300       54300             9
8881             0.708333               275       50875             7

      Flight Year
8880         2015
8881         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8882  Flight8883  41745  ORD-PHX              2.7          97
8883  Flight8884  41949  ORD-PHX              1.9         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8882             0.500000               250       46250             4
8883             0.645833               250       41250            11

      Flight Year
8882         2014
8883         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8884  Flight8885  42296  ORD-IAH              1.5           9
8885  Flight8886  42040  ORD-IAH              3.0         121

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8884             0.875000               200       37000            10
8885             0.833333               200       37000             2

      Flight Year
8884         2015
8885         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8886  Flight8887  41805  ORD-ATL             10.4          64
8887  Flight8888  42326  ORD-LAS              4.0         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8886               0.8750               220       39820             6
8887               0.6875               275       45375            11

      Flight Year
8886         2014
8887         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8888  Flight8889  41736  ORD-DEN              2.1          84
8889  Flight8890  42235  ORD-MCO              3.0          59

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8888             0.770833               300       54300             4
8889             0.291667               275       45375             8

      Flight Year
8888         2014
8889         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8890  Flight8891  42023  ORD-SFO              3.1         189
8891  Flight8892  41880  ORD-MSP              2.0         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8890             0.333333             375.0     61875.0             1
8891             0.333333             126.5     23402.5             8

      Flight Year
8890         2015
8891         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8892  Flight8893  41882  ORD-MSP              2.3          60
8893  Flight8894  41797  ORD-SLC              1.6          40

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8892               0.8125             126.5     20872.5             8
8893               0.5000             319.0     52635.0             6

      Flight Year
8892         2014
8893         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8894  Flight8895  42164  ORD-ATL             11.9         180
8895  Flight8896  41678  ORD-MIA              2.7         112

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8894             0.291667               220       36300             6
8895             0.625000               300       55500             2

      Flight Year
8894         2015
8895         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8896  Flight8897  41688  ORD-MIA              2.0          30
8897  Flight8898  42067  ORD-MIA              1.2         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8896             0.791667               300       55500             2
8897             0.791667               300       49500             3

      Flight Year
8896         2014
8897         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8898  Flight8899  41844  ORD-SFO              1.0          26
8899  Flight8900  41705  ORD-LAS              2.1         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8898             0.291667             412.5     76312.5             7
8899             0.312500             275.0     50875.0             3

      Flight Year
8898         2014
8899         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8900  Flight8901  42293  ORD-PHX              2.0         190
8901  Flight8902  41717  ORD-ATL              7.6         175

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8900             0.770833               250       41250            10
8901             0.666667               200       33000             3

      Flight Year
8900         2015
8901         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8902  Flight8903  42173  ORD-JFK              2.8          84
8903  Flight8904  41922  ORD-SFO              1.9           1

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8902             0.750000               275       49775             6
8903             0.541667               375       69375            10

      Flight Year
8902         2015
8903         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8904  Flight8905  41900  ORD-CLT              1.9          94
8905  Flight8906  41913  ORD-ATL              7.3         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8904             0.791667               125       23125             9
8905             0.500000               200       37000            10

      Flight Year
8904         2014
8905         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8906  Flight8907  41963  ORD-ATL              6.6          86
8907  Flight8908  42178  ORD-SEA              1.1         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8906             0.562500               200       36200            11
8907             0.333333               385       63525             6

      Flight Year
8906         2014
8907         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8908  Flight8909  42239  ORD-JFK              1.7         158
8909  Flight8910  42288  ORD-IAD              2.0          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8908             0.333333               275       45375             8
8909             0.416667               300       54300            10

      Flight Year
8908         2015
8909         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8910  Flight8911  42091  ORD-LAX              2.6         196
8911  Flight8912  41811  ORD-SFO              1.9          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8910             0.333333             350.0     57750.0             3
8911             0.291667             412.5     74662.5             6

      Flight Year
8910         2015
8911         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8912  Flight8913  41898  ORD-SFO              1.1         203
8913  Flight8914  42029  ORD-DEN              1.5         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8912             0.708333               375       61875             9
8913             0.333333               300       55500             1

      Flight Year
8912         2014
8913         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8914  Flight8915  42257  ORD-DFW              0.7         136
8915  Flight8916  42161  ORD-DTW              1.5          77

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8914             0.604167             200.0     37000.0             9
8915             0.708333             126.5     22896.5             6

      Flight Year
8914         2015
8915         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8916  Flight8917  42362  ORD-CLT              4.5         183
8917  Flight8918  41794  ORD-JFK              1.7         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8916             0.291667               175       28875            12
8917             0.291667               275       50875             6

      Flight Year
8916         2015
8917         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8918  Flight8919  42100  ORD-LAX              4.8          27
8919  Flight8920  42210  ORD-LAX              6.2         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8918             0.770833               350       64750             4
8919             0.770833               385       71225             7

      Flight Year
8918         2015
8919         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8920  Flight8921  41743  ORD-BOS              3.1          94
8921  Flight8922  42043  ORD-DFW              2.4          37

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8920             0.333333               300       55500             4
8921             0.791667               200       33000             2

      Flight Year
8920         2014
8921         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8922  Flight8923  41875  ORD-ATL              9.8           7
8923  Flight8924  42297  ORD-LAS              2.0         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8922             0.437500               220       40700             8
8923             0.333333               275       45375            10

      Flight Year
8922         2014
8923         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8924  Flight8925  41803  ORD-EWR              2.7          22
8925  Flight8926  42151  ORD-BOS              1.8         149

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8924             0.770833             247.5     45787.5             6
8925             0.312500             300.0     55500.0             5

      Flight Year
8924         2014
8925         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8926  Flight8927  41875  ORD-SFO              2.5          41
8927  Flight8928  41948  ORD-LAS              1.3         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8926             0.291667             412.5     68062.5             8
8927             0.708333             275.0     45375.0            11

      Flight Year
8926         2014
8927         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8928  Flight8929  42198  ORD-LGA              0.8         201
8929  Flight8930  41960  ORD-DEN              1.5         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8928             0.395833             302.5     49912.5             7
8929             0.812500             300.0     55500.0            11

      Flight Year
8928         2015
8929         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8930  Flight8931  41977  ORD-IAH              1.0          12
8931  Flight8932  41848  ORD-IAH              2.6         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8930                0.750               200       37000            12
8931                0.875               220       40700             7

      Flight Year
8930         2014
8931         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8932  Flight8933  42063  ORD-DTW              1.2          26
8933  Flight8934  42288  ORD-LGA              2.1         206

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8932             0.791667               115       21275             2
8933             0.791667               275       45375            10

      Flight Year
8932         2015
8933         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8934  Flight8935  42152  ORD-PHX              1.4           8
8935  Flight8936  41734  ORD-SEA              1.2         106

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8934             0.791667               250       46250             5
8935             0.333333               350       64750             4

      Flight Year
8934         2015
8935         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8936  Flight8937  42347  ORD-ATL              9.3          43
8937  Flight8938  41686  ORD-ATL              8.8         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8936             0.750000               200       33000            12
8937             0.395833               200       33000             2

      Flight Year
8936         2015
8937         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8938  Flight8939  41947  ORD-DEN              1.4         162
8939  Flight8940  41855  ORD-SEA              2.7         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8938             0.395833               300       49500            11
8939             0.541667               385       71225             8

      Flight Year
8938         2014
8939         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8940  Flight8941  42148  ORD-LAS              2.1          20
8941  Flight8942  41749  ORD-FLL              1.9          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8940             0.708333               275       50875             5
8941             0.541667               300       55500             4

      Flight Year
8940         2015
8941         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8942  Flight8943  41730  ORD-CLT              2.6          34
8943  Flight8944  42004  ORD-JFK              2.4          94

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8942             0.708333               125       23125             4
8943             0.833333               250       46250            12

      Flight Year
8942         2014
8943         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8944  Flight8945  41724  ORD-IAH              1.5         174
8945  Flight8946  41723  ORD-ATL              9.7         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8944             0.770833               200       33000             3
8945             0.708333               200       37000             3

      Flight Year
8944         2014
8945         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8946  Flight8947  42102  ORD-PHX              2.4         106
8947  Flight8948  42134  ORD-LAS              1.9          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8946             0.750000               250       46250             4
8947             0.791667               275       50875             5

      Flight Year
8946         2015
8947         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8948  Flight8949  42164  ORD-DEN              2.4         122
8949  Flight8950  41747  ORD-JFK              2.3         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8948             0.750000               330       61050             6
8949             0.291667               250       46250             4

      Flight Year
8948         2015
8949         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8950  Flight8951  41972  ORD-JFK              4.5          20
8951  Flight8952  41904  ORD-PHX              1.8         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8950             0.333333               375       69375            11
8951             0.458333               250       41250             9

      Flight Year
8950         2014
8951         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8952  Flight8953  42200  ORD-BOS              1.5         209
8953  Flight8954  41945  ORD-SEA              2.2         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8952                 0.75               330       54450             7
8953                 0.75               350       57750            11

      Flight Year
8952         2015
8953         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8954  Flight8955  41818  ORD-EWR              2.5          76
8955  Flight8956  41839  ORD-SFO              2.1          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8954             0.708333             247.5     44797.5             6
8955             0.375000             412.5     76312.5             7

      Flight Year
8954         2014
8955         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8956  Flight8957  41979  ORD-ATL              9.0          29
8957  Flight8958  41803  ORD-SFO              1.2          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8956             0.708333             200.0     37000.0            12
8957             0.333333             412.5     68062.5             6

      Flight Year
8956         2014
8957         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8958  Flight8959  42167  ORD-LGA              2.8          90
8959  Flight8960  42283  ORD-DCA              2.3         100

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8958             0.541667             302.5     54752.5             6
8959             0.750000            5000.0    925000.0            10

      Flight Year
8958         2015
8959         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8960  Flight8961  42019  ORD-ATL              6.3          61
8961  Flight8962  42151  ORD-SFO              2.1         117

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8960             0.375000               200       33000             1
8961             0.416667               375       69375             5

      Flight Year
8960         2015
8961         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8962  Flight8963  41807  ORD-DFW              2.0         144
8963  Flight8964  42151  ORD-SFO              1.9         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8962             0.625000               220       40700             6
8963             0.791667               375       61875             5

      Flight Year
8962         2014
8963         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8964  Flight8965  42308  ORD-MSP              0.9          60
8965  Flight8966  42245  ORD-PHX              0.7          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8964             0.291667               115       18975            10
8965             0.416667               275       49775             8

      Flight Year
8964         2015
8965         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8966  Flight8967  42237  ORD-ATL             12.7          15
8967  Flight8968  42045  ORD-DEN              2.1          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8966             0.333333               220       40700             8
8967             0.541667               300       54300             2

      Flight Year
8966         2015
8967         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8968  Flight8969  41943  ORD-SLC              1.8         180
8969  Flight8970  41813  ORD-IAH              1.6          30

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8968             0.312500               290       47850            10
8969             0.770833               220       40700             6

      Flight Year
8968         2014
8969         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8970  Flight8971  41813  ORD-FLL              1.4           4
8971  Flight8972  41937  ORD-PHX              1.6         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8970             0.291667               330       61050             6
8971             0.687500               250       46250            10

      Flight Year
8970         2014
8971         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8972  Flight8973  41837  ORD-EWR              2.2         113
8973  Flight8974  42315  ORD-MCO              2.3          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8972             0.791667             247.5     45787.5             7
8973             0.416667             250.0     46250.0            11

      Flight Year
8972         2014
8973         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8974  Flight8975  42273  ORD-SFO              0.8          21
8975  Flight8976  42090  ORD-IAH              1.4           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8974             0.583333               375       69375             9
8975             0.812500               200       37000             3

      Flight Year
8974         2015
8975         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8976  Flight8977  41847  ORD-LAX              3.9          77
8977  Flight8978  41957  ORD-DTW              3.6         184

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8976             0.666667               385       69685             7
8977             0.375000               115       18975            11

      Flight Year
8976         2014
8977         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8978  Flight8979  42185  ORD-ATL              8.0         203
8979  Flight8980  41887  ORD-LAS              1.4         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8978             0.812500               220       36300             6
8979             0.354167               275       50875             9

      Flight Year
8978         2015
8979         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8980  Flight8981  41906  ORD-MIA              2.3          39
8981  Flight8982  41909  ORD-BOS              2.0         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8980             0.666667               300       49500             9
8981             0.854167               300       55500             9

      Flight Year
8980         2014
8981         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8982  Flight8983  42279  ORD-DTW              2.1         140
8983  Flight8984  42115  ORD-DEN              2.7         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8982             0.770833               115       21275            10
8983             0.833333               300       49500             4

      Flight Year
8982         2015
8983         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8984  Flight8985  41646  ORD-DEN              2.1         118
8985  Flight8986  42102  ORD-IAD              1.7         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8984             0.312500               300       55500             1
8985             0.770833               300       49500             4

      Flight Year
8984         2014
8985         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8986  Flight8987  41794  ORD-DFW              2.7         169
8987  Flight8988  41683  ORD-IAH              2.7          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8986               0.3125               220       36300             6
8987               0.7500               200       33000             2

      Flight Year
8986         2014
8987         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8988  Flight8989  42073  ORD-LAX              3.6         178
8989  Flight8990  42357  ORD-DFW              3.5          46

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8988             0.729167               350       57750             3
8989             0.833333               200       33000            12

      Flight Year
8988         2015
8989         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8990  Flight8991  41870  ORD-BOS              1.6         132
8991  Flight8992  41752  ORD-JFK              1.6         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8990             0.291667               330       61050             8
8991             0.750000               250       41250             4

      Flight Year
8990         2014
8991         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8992  Flight8993  42000  ORD-CLT              3.4          36
8993  Flight8994  42100  ORD-CLT              2.3          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8992               0.6875               175       28875            12
8993               0.7500               125       23125             4

      Flight Year
8992         2014
8993         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8994  Flight8995  41911  ORD-BOS              1.2         185
8995  Flight8996  41789  ORD-FLL              1.9          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8994             0.750000               300       49500             9
8995             0.395833               300       49500             5

      Flight Year
8994         2014
8995         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8996  Flight8997  41967  ORD-PHX              6.3         187
8997  Flight8998  41984  ORD-EWR              1.7         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8996             0.562500               375       61875            11
8997             0.833333               225       37125            12

      Flight Year
8996         2014
8997         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
8998  Flight8999  41843  ORD-EWR              2.5          74
8999  Flight9000  42262  ORD-BWI              3.5          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
8998             0.395833             247.5     44797.5             7
8999             0.750000             240.0     43440.0             9

      Flight Year
8998         2014
8999         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9000  Flight9001  42293  ORD-MSP              1.1         120
9001  Flight9002  42296  ORD-DFW              0.5          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9000             0.875000               115       21275            10
9001             0.708333               200       33000            10

      Flight Year
9000         2015
9001         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9002  Flight9003  41777  ORD-JFK              1.2          23
9003  Flight9004  42134  ORD-MIA              1.8         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9002             0.812500               250       46250             5
9003             0.791667               300       49500             5

      Flight Year
9002         2014
9003         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9004  Flight9005  41998  ORD-IAH              2.8         181
9005  Flight9006  41742  ORD-MIA              1.8          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9004             0.500000               280       46200            12
9005             0.333333               300       49500             4

      Flight Year
9004         2014
9005         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9006  Flight9007  42184  ORD-LAX              4.0         128
9007  Flight9008  41952  ORD-ATL              6.1          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9006               0.7500               385       71225             6
9007               0.3125               200       37000            11

      Flight Year
9006         2015
9007         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9008  Flight9009  41913  ORD-DEN              2.0          65
9009  Flight9010  42050  ORD-DFW              1.5          61

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9008             0.291667               300       54300            10
9009             0.750000               200       33000             2

      Flight Year
9008         2014
9009         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9010  Flight9011  42038  ORD-MCO              2.8         168
9011  Flight9012  42302  ORD-LAX              5.0          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9010             0.708333               250       41250             2
9011             0.708333               350       64750            10

      Flight Year
9010         2015
9011         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9012  Flight9013  42331  ORD-ATL             17.9         106
9013  Flight9014  41909  ORD-FLL              2.7         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9012             0.791667               300       55500            11
9013             0.645833               300       49500             9

      Flight Year
9012         2015
9013         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9014  Flight9015  42178  ORD-PHX              2.1         186
9015  Flight9016  41841  ORD-DEN              2.4          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9014             0.375000               275       45375             6
9015             0.791667               330       54450             7

      Flight Year
9014         2015
9015         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9016  Flight9017  42035  ORD-MSP              1.9         130
9017  Flight9018  42349  ORD-LGA              0.6         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9016               0.7500               115       21275             1
9017               0.6875               275       45375            12

      Flight Year
9016         2015
9017         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9018  Flight9019  41799  ORD-LAX              5.0          90
9019  Flight9020  42030  ORD-DFW              1.8         208

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9018             0.791667               385       69685             6
9019             0.750000               200       33000             1

      Flight Year
9018         2014
9019         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9020  Flight9021  42304  ORD-IAH              0.3         179
9021  Flight9022  42284  ORD-MIA              1.5         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9020                0.750               200       33000            10
9021                0.375               300       49500            10

      Flight Year
9020         2015
9021         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9022  Flight9023  42003  ORD-SFO              2.2         152
9023  Flight9024  41653  ORD-LAX              5.1         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9022             0.604167               375       61875            12
9023             0.791667               350       57750             1

      Flight Year
9022         2014
9023         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9024  Flight9025  42334  ORD-LGA              6.6         117
9025  Flight9026  42187  ORD-PHX              2.0          15

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9024             0.791667             412.5     76312.5            11
9025             0.458333             275.0     50875.0             7

      Flight Year
9024         2015
9025         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9026  Flight9027  42181  ORD-CLT              2.1          85
9027  Flight9028  42037  ORD-CLT              1.9          38

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9026             0.333333             137.5     24887.5             6
9027             0.333333             125.0     20625.0             2

      Flight Year
9026         2015
9027         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9028  Flight9029  41665  ORD-DFW              2.4         148
9029  Flight9030  42211  ORD-SFO              1.2          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9028             0.333333             200.0     37000.0             1
9029             0.791667             412.5     76312.5             7

      Flight Year
9028         2014
9029         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9030  Flight9031  42342  ORD-FLL              1.3         175
9031  Flight9032  41697  ORD-IAD              2.4         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9030             0.750000               300       49500            12
9031             0.291667               300       49500             2

      Flight Year
9030         2015
9031         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9032  Flight9033  42150  ORD-JFK              3.8          30
9033  Flight9034  41733  ORD-PHL              1.5         164

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9032             0.291667               250       46250             5
9033             0.833333               275       45375             4

      Flight Year
9032         2015
9033         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9034  Flight9035  42205  ORD-IAH              2.5         145
9035  Flight9036  42198  ORD-FLL              1.3         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9034               0.8125               220       40700             7
9035               0.5625               330       61050             7

      Flight Year
9034         2015
9035         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9036  Flight9037  41658  ORD-IAH              1.2         165
9037  Flight9038  41957  ORD-EWR              1.0         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9036             0.291667               200       33000             1
9037             0.791667               225       41625            11

      Flight Year
9036         2014
9037         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9038  Flight9039  41872  ORD-PHL              1.2          12
9039  Flight9040  41827  ORD-ATL              7.9         151

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9038             0.791667             302.5     55962.5             8
9039             0.520833             220.0     40700.0             7

      Flight Year
9038         2014
9039         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9040  Flight9041  42168  ORD-LAX              6.2          59
9041  Flight9042  41678  ORD-JFK              2.2          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9040                0.875               385       63525             6
9041                0.750               250       46250             2

      Flight Year
9040         2015
9041         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9042  Flight9043  41974  ORD-ATL              8.6         160
9043  Flight9044  42248  ORD-PHL              2.8         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9042             0.520833               200       33000            12
9043             0.791667               275       50875             9

      Flight Year
9042         2014
9043         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9044  Flight9045  41941  ORD-MCO              2.8         115
9045  Flight9046  41889  ORD-SFO              3.4         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9044             0.791667               250       46250            10
9045             0.583333               375       61875             9

      Flight Year
9044         2014
9045         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9046  Flight9047  41884  ORD-JFK              2.2          83
9047  Flight9048  42146  ORD-PHL              1.7          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9046             0.541667               250       45250             9
9047             0.854167               275       50875             5

      Flight Year
9046         2014
9047         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9048  Flight9049  41835  ORD-LAX              5.0          56
9049  Flight9050  41652  ORD-SEA              2.6          71

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9048             0.395833               385       63525             7
9049             0.770833               350       63350             1

      Flight Year
9048         2014
9049         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9050  Flight9051  41712  ORD-MSP              1.4         134
9051  Flight9052  41707  ORD-EWR              0.9           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9050             0.354167               115       21275             3
9051             0.541667               225       41625             3

      Flight Year
9050         2014
9051         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9052  Flight9053  41969  ORD-MSP              6.0         146
9053  Flight9054  42205  ORD-DEN              1.2          11

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9052             0.645833             172.5     31912.5            11
9053             0.791667             330.0     61050.0             7

      Flight Year
9052         2014
9053         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9054  Flight9055  41836  ORD-MCO              2.1         185
9055  Flight9056  42225  ORD-ATL             11.3         157

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9054             0.750000               275       45375             7
9055             0.791667               220       36300             8

      Flight Year
9054         2014
9055         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9056  Flight9057  41776  ORD-LAX              3.6         191
9057  Flight9058  42139  ORD-DFW              2.0         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9056             0.791667               350       57750             5
9057             0.708333               200       37000             5

      Flight Year
9056         2014
9057         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9058  Flight9059  41653  ORD-DFW              1.8          43
9059  Flight9060  42161  ORD-LAS              1.9         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9058             0.750000             200.0     33000.0             1
9059             0.458333             302.5     49912.5             6

      Flight Year
9058         2014
9059         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9060  Flight9061  42358  ORD-LAX              3.8         182
9061  Flight9062  42146  ORD-ATL              9.3          14

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9060               0.8125               350       57750            12
9061               0.5000               200       37000             5

      Flight Year
9060         2015
9061         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9062  Flight9063  42365  ORD-BWI              5.0         168
9063  Flight9064  41966  ORD-FLL              1.6         198

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9062             0.291667               336       55440            12
9063             0.291667               300       49500            11

      Flight Year
9062         2015
9063         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9064  Flight9065  42337  ORD-SFO              5.4          99
9065  Flight9066  42339  ORD-SEA              1.4          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9064             0.833333             562.5    104062.5            11
9065             0.791667             350.0     57750.0            12

      Flight Year
9064         2015
9065         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9066  Flight9067  42241  ORD-MCO              2.7          13
9067  Flight9068  42236  ORD-CLT              1.8         128

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9066             0.312500             275.0     50875.0             8
9067             0.666667             137.5     25437.5             8

      Flight Year
9066         2015
9067         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9068  Flight9069  42001  ORD-DFW              1.6          78
9069  Flight9070  41906  ORD-JFK              1.4          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9068                0.875               280       50680            12
9069                0.750               250       45250             9

      Flight Year
9068         2014
9069         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9070  Flight9071  42167  ORD-SFO              1.6         107
9071  Flight9072  41812  ORD-PHL              1.4          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9070             0.708333             412.5     76312.5             6
9071             0.791667             302.5     54752.5             6

      Flight Year
9070         2015
9071         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9072  Flight9073  41714  ORD-SFO              2.6         138
9073  Flight9074  41741  ORD-PHL              3.0         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9072             0.708333               375       69375             3
9073             0.541667               275       45375             4

      Flight Year
9072         2014
9073         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9074  Flight9075  41992  ORD-LAS              2.9           2
9075  Flight9076  42254  ORD-SFO              2.1          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9074             0.791667               275       50875            12
9075             0.854167               375       69375             9

      Flight Year
9074         2014
9075         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9076  Flight9077  42331  ORD-JFK              7.0         147
9077  Flight9078  41793  ORD-MIA              2.2          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9076             0.625000               375       69375            11
9077             0.708333               330       61050             6

      Flight Year
9076         2015
9077         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9078  Flight9079  41644  ORD-PHL              1.0         106
9079  Flight9080  42314  ORD-SFO              2.5         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9078             0.833333               275       50875             1
9079             0.645833               375       69375            11

      Flight Year
9078         2014
9079         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9080  Flight9081  41995  ORD-ATL             12.6         209
9081  Flight9082  42094  ORD-LAX              2.7          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9080             0.416667               280       46200            12
9081             0.291667               350       64750             3

      Flight Year
9080         2014
9081         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9082  Flight9083  42330  ORD-DFW              2.6          54
9083  Flight9084  42221  ORD-DEN              2.2          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9082             0.875000               200       33000            11
9083             0.604167               330       61050             8

      Flight Year
9082         2015
9083         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9084  Flight9085  42368  ORD-DFW              3.9         140
9085  Flight9086  41726  ORD-MIA              1.1         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9084             0.791667               200       37000            12
9085             0.291667               300       55500             3

      Flight Year
9084         2015
9085         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9086  Flight9087  41840  ORD-LGA              3.4          51
9087  Flight9088  41897  ORD-PHX              2.0         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9086             0.750000             302.5     49912.5             7
9087             0.333333             250.0     41250.0             9

      Flight Year
9086         2014
9087         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9088  Flight9089  41792  ORD-BWI              1.3          61
9089  Flight9090  41751  ORD-IAH              3.0          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9088             0.333333               264       43560             6
9089             0.333333               200       33000             4

      Flight Year
9088         2014
9089         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9090  Flight9091  42224  ORD-PHX              2.4         104
9091  Flight9092  42283  ORD-LAX              3.2          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9090             0.333333               275       50875             8
9091             0.708333               350       64750            10

      Flight Year
9090         2015
9091         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9092  Flight9093  42304  ORD-BOS              1.4          36
9093  Flight9094  42267  ORD-DEN              2.1          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9092             0.854167               300       49500            10
9093             0.770833               300       54300             9

      Flight Year
9092         2015
9093         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9094  Flight9095  41829  ORD-EWR              0.2          82
9095  Flight9096  42098  ORD-EWR              1.7          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9094             0.791667             247.5     44797.5             7
9095             0.541667             225.0     41625.0             4

      Flight Year
9094         2014
9095         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9096  Flight9097  41694  ORD-CLT              1.9          74
9097  Flight9098  41750  ORD-CLT              2.1         111

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9096             0.333333               125       22625             2
9097             0.291667               125       23125             4

      Flight Year
9096         2014
9097         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9098  Flight9099  41815  ORD-PHX              1.3         126
9099  Flight9100  42178  ORD-DEN              1.0         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9098             0.812500               275       50875             6
9099             0.833333               330       54450             6

      Flight Year
9098         2014
9099         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9100  Flight9101  41860  ORD-BOS              2.2         133
9101  Flight9102  41944  ORD-IAH              1.2          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9100             0.666667               330       61050             8
9101             0.791667               200       33000            11

      Flight Year
9100         2014
9101         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9102  Flight9103  41892  ORD-JFK              2.9         163
9103  Flight9104  42304  ORD-BOS              0.3          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9102             0.854167               250       41250             9
9103             0.500000               300       54300            10

      Flight Year
9102         2014
9103         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9104  Flight9105  41797  ORD-CLT              1.6          84
9105  Flight9106  41734  ORD-BOS              1.9         204

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9104             0.458333             137.5     24887.5             6
9105             0.833333             300.0     49500.0             4

      Flight Year
9104         2014
9105         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9106  Flight9107  41837  ORD-IAH              1.5         100
9107  Flight9108  42166  ORD-ATL              9.2         167

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9106             0.750000               220       40700             7
9107             0.708333               220       36300             6

      Flight Year
9106         2014
9107         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9108  Flight9109  42331  ORD-DFW              6.8          10
9109  Flight9110  42326  ORD-DFW              2.3         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9108             0.291667               300       55500            11
9109             0.791667               200       33000            11

      Flight Year
9108         2015
9109         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9110  Flight9111  42073  ORD-PHX              2.0          56
9111  Flight9112  41779  ORD-DFW              2.1          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9110             0.500000               250       41250             3
9111             0.333333               200       36200             5

      Flight Year
9110         2015
9111         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9112  Flight9113  41881  ORD-SEA              2.4         113
9113  Flight9114  41832  ORD-EWR              3.2          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9112             0.291667             385.0     71225.0             8
9113             0.770833             247.5     45787.5             7

      Flight Year
9112         2014
9113         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9114  Flight9115  42140  ORD-LGA              1.6         103
9115  Flight9116  41870  ORD-MIA              2.5          35

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9114             0.833333               275       50875             5
9115             0.791667               330       61050             8

      Flight Year
9114         2015
9115         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9116  Flight9117  41820  ORD-IAH              2.2         106
9117  Flight9118  41831  ORD-MIA              2.9          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9116             0.750000               220       40700             6
9117             0.791667               330       59730             7

      Flight Year
9116         2014
9117         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9118  Flight9119  42204  ORD-DFW              2.8         208
9119  Flight9120  42191  ORD-DFW              2.2         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9118             0.604167               220       36300             7
9119             0.812500               220       36300             7

      Flight Year
9118         2015
9119         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9120  Flight9121  41768  ORD-DFW              2.7         186
9121  Flight9122  41772  ORD-PHX              1.6          69

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9120             0.791667               200       33000             5
9121             0.812500               250       45250             5

      Flight Year
9120         2014
9121         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9122  Flight9123  41793  ORD-MSP              2.2         201
9123  Flight9124  41984  ORD-PHX              2.3          29

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9122             0.291667             126.5     20872.5             6
9123             0.583333             250.0     46250.0            12

      Flight Year
9122         2014
9123         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9124  Flight9125  41754  ORD-IAH              1.5          67
9125  Flight9126  42162  ORD-MIA              1.3          63

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9124             0.500000               200       36200             4
9125             0.291667               330       59730             6

      Flight Year
9124         2014
9125         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9126  Flight9127  41809  ORD-JFK              2.5          12
9127  Flight9128  41983  ORD-SFO              2.3          57

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9126             0.291667               275       50875             6
9127             0.687500               375       61875            12

      Flight Year
9126         2014
9127         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9128  Flight9129  42282  ORD-IAH              1.3          83
9129  Flight9130  42324  ORD-LAX              3.6         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9128             0.312500               200       36200            10
9129             0.791667               350       57750            11

      Flight Year
9128         2015
9129         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9130  Flight9131  42233  ORD-LGA              3.3         129
9131  Flight9132  41946  ORD-LAS              2.4          34

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9130             0.333333             302.5     55962.5             8
9131             0.666667             275.0     50875.0            11

      Flight Year
9130         2015
9131         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9132  Flight9133  41887  ORD-EWR              1.5         115
9133  Flight9134  42210  ORD-JFK              1.3          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9132             0.312500               225       41625             9
9133             0.791667               275       50875             7

      Flight Year
9132         2014
9133         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9134  Flight9135  42129  ORD-CLT                2         159
9135  Flight9136  41853  ORD-MCO                1         116

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9134                0.625               125       20625             5
9135                0.750               275       50875             8

      Flight Year
9134         2015
9135         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9136  Flight9137  41948  ORD-SFO              1.4         206
9137  Flight9138  42111  ORD-BOS              2.1          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9136             0.708333               375       61875            11
9137             0.791667               300       49500             4

      Flight Year
9136         2014
9137         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9138  Flight9139  42229  ORD-LAS              1.2          84
9139  Flight9140  41769  ORD-PHX              0.8          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9138                 0.75             302.5     54752.5             8
9139                 0.75             250.0     46250.0             5

      Flight Year
9138         2015
9139         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9140  Flight9141  41811  ORD-MCO              1.4         120
9141  Flight9142  41775  ORD-EWR              2.2         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9140             0.833333               275       50875             6
9141             0.333333               225       41625             5

      Flight Year
9140         2014
9141         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9142  Flight9143  42338  ORD-SFO              2.4          32
9143  Flight9144  42322  ORD-DTW              2.7           2

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9142             0.625000               375       69375            11
9143             0.708333               115       21275            11

      Flight Year
9142         2015
9143         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9144  Flight9145  42009  ORD-PHL              2.2          60
9145  Flight9146  42321  ORD-LAS              1.7          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9144             0.291667               275       45375             1
9145             0.666667               275       50875            11

      Flight Year
9144         2015
9145         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9146  Flight9147  41963  ORD-EWR              2.0          71
9147  Flight9148  41682  ORD-LAX              4.3          68

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9146             0.895833               225       40725            11
9147             0.812500               350       63350             2

      Flight Year
9146         2014
9147         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9148  Flight9149  41733  ORD-LAX              2.7         135
9149  Flight9150  42226  ORD-LAX              5.7          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9148               0.8125               350       64750             4
9149               0.7500               385       63525             8

      Flight Year
9148         2014
9149         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9150  Flight9151  42305  ORD-IAH              1.6          35
9151  Flight9152  41886  ORD-DFW              3.4         180

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9150             0.645833               200       37000            10
9151             0.312500               200       33000             9

      Flight Year
9150         2015
9151         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9152  Flight9153  41853  ORD-DFW              1.2          38
9153  Flight9154  41920  ORD-DFW              2.1          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9152             0.708333               220       36300             8
9153             0.312500               200       36200            10

      Flight Year
9152         2014
9153         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9154  Flight9155  42187  ORD-LAS              1.8         137
9155  Flight9156  42304  ORD-ATL              8.9         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9154             0.458333             302.5     55962.5             7
9155             0.354167             200.0     33000.0            10

      Flight Year
9154         2015
9155         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9156  Flight9157  42234  ORD-IAH              2.1         107
9157  Flight9158  42224  ORD-DFW              0.1         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9156             0.854167               220       40700             8
9157             0.312500               220       40700             8

      Flight Year
9156         2015
9157         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9158  Flight9159  41844  ORD-DFW              2.7          61
9159  Flight9160  41642  ORD-EWR              2.2         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9158             0.750000               220       36300             7
9159             0.833333               225       41625             1

      Flight Year
9158         2014
9159         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9160  Flight9161  42161  ORD-PHX              1.8           9
9161  Flight9162  41735  ORD-SLC              1.5          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9160             0.895833               275       50875             6
9161             0.791667               290       53650             4

      Flight Year
9160         2015
9161         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9162  Flight9163  41837  ORD-LAS              2.5          21
9163  Flight9164  42089  ORD-JFK              2.2         119

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9162             0.750000             302.5     55962.5             7
9163             0.833333             250.0     46250.0             3

      Flight Year
9162         2014
9163         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9164  Flight9165  41789  ORD-MSP              2.3          66
9165  Flight9166  41816  ORD-EWR              2.1          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9164             0.291667             115.0     20815.0             5
9165             0.791667             247.5     44797.5             6

      Flight Year
9164         2014
9165         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9166  Flight9167  41874  ORD-ATL              9.4         104
9167  Flight9168  42361  ORD-EWR              2.2          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9166             0.708333               220       40700             8
9167             0.750000               315       57015            12

      Flight Year
9166         2014
9167         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9168  Flight9169  41835  ORD-MCO              2.7         151
9169  Flight9170  42066  ORD-DFW              2.5         203

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9168             0.583333               275       50875             7
9169             0.791667               200       33000             3

      Flight Year
9168         2014
9169         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9170  Flight9171  41994  ORD-LAS              0.9         121
9171  Flight9172  42190  ORD-MCO              1.9          91

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9170             0.291667               275       50875            12
9171             0.812500               275       50875             7

      Flight Year
9170         2014
9171         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9172  Flight9173  42073  ORD-DFW              1.8           2
9173  Flight9174  41861  ORD-DFW              2.8         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9172             0.333333               200       37000             3
9173             0.895833               220       36300             8

      Flight Year
9172         2015
9173         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9174  Flight9175  42188  ORD-EWR              2.2         183
9175  Flight9176  41995  ORD-SFO              5.0         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9174             0.854167             247.5     40837.5             7
9175             0.291667             525.0     86625.0            12

      Flight Year
9174         2015
9175         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9176  Flight9177  41971  ORD-LAS              4.9          99
9177  Flight9178  42360  ORD-JFK              5.0         207

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9176               0.7500             412.5     76312.5            11
9177               0.8125             350.0     57750.0            12

      Flight Year
9176         2014
9177         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9178  Flight9179  42311  ORD-EWR              3.1          81
9179  Flight9180  41885  ORD-CLT              1.3          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9178             0.500000               225       40725            11
9179             0.541667               125       22625             9

      Flight Year
9178         2015
9179         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9180  Flight9181  42172  ORD-EWR              1.3          59
9181  Flight9182  42212  ORD-MCO              1.7         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9180             0.500000             247.5     40837.5             6
9181             0.791667             275.0     50875.0             7

      Flight Year
9180         2015
9181         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9182  Flight9183  41902  ORD-DTW              2.8           9
9183  Flight9184  41796  ORD-LGA              2.6          66

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9182             0.791667             115.0     21275.0             9
9183             0.750000             302.5     54752.5             6

      Flight Year
9182         2014
9183         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9184  Flight9185  41755  ORD-JFK              1.7          89
9185  Flight9186  42342  ORD-BOS              2.9          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9184             0.583333               250       45250             4
9185             0.812500               300       49500            12

      Flight Year
9184         2014
9185         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9186  Flight9187  41722  ORD-CLT              1.9         190
9187  Flight9188  41894  ORD-SEA              2.5         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9186             0.354167               125       20625             3
9187             0.541667               350       57750             9

      Flight Year
9186         2014
9187         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9188  Flight9189  41842  ORD-LGA              2.0         159
9189  Flight9190  41803  ORD-ATL             10.4         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9188             0.750000             302.5     49912.5             7
9189             0.333333             220.0     40700.0             6

      Flight Year
9188         2014
9189         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9190  Flight9191  42214  ORD-PHX              1.4         142
9191  Flight9192  42234  ORD-IAH              2.8         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9190             0.750000               275       50875             7
9191             0.791667               220       40700             8

      Flight Year
9190         2015
9191         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9192  Flight9193  41673  ORD-LAS              1.1         185
9193  Flight9194  42066  ORD-LAX              3.7         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9192             0.812500               275       45375             2
9193             0.520833               350       57750             3

      Flight Year
9192         2014
9193         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9194  Flight9195  42282  ORD-LAS              2.7          46
9195  Flight9196  41908  ORD-DEN              2.6           4

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9194             0.708333               275       45375            10
9195             0.291667               300       55500             9

      Flight Year
9194         2015
9195         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9196  Flight9197  42210  ORD-SEA              1.3           6
9197  Flight9198  41790  ORD-ATL              9.6         137

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9196             0.541667               385       71225             7
9197             0.750000               200       37000             5

      Flight Year
9196         2015
9197         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9198  Flight9199  41749  ORD-FLL              3.7          98
9199  Flight9200  42357  ORD-PHX              2.1          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9198             0.791667               300       55500             4
9199             0.500000               250       46250            12

      Flight Year
9198         2014
9199         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9200  Flight9201  41653  ORD-DFW              1.2          33
9201  Flight9202  41803  ORD-PHX              2.8         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9200                0.875               200       37000             1
9201                0.375               275       50875             6

      Flight Year
9200         2014
9201         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9202  Flight9203  42019  ORD-LAX              4.7          26
9203  Flight9204  41776  ORD-JFK              0.4         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9202             0.708333               350       64750             1
9203             0.791667               250       41250             5

      Flight Year
9202         2015
9203         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9204  Flight9205  41715  ORD-LGA              1.9         117
9205  Flight9206  42357  ORD-CLT              2.0         125

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9204             0.333333               275       50875             3
9205             0.708333               125       23125            12

      Flight Year
9204         2014
9205         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9206  Flight9207  42296  ORD-SEA              2.1          22
9207  Flight9208  41715  ORD-BOS              2.6         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9206             0.458333               350       64750            10
9207             0.333333               300       55500             3

      Flight Year
9206         2015
9207         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9208  Flight9209  41824  ORD-ATL              9.8          18
9209  Flight9210  42017  ORD-MSP              0.1          56

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9208             0.791667               220       40700             7
9209             0.375000               115       18975             1

      Flight Year
9208         2014
9209         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9210  Flight9211  41709  ORD-MSP              2.1          46
9211  Flight9212  41930  ORD-IAH              2.0         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9210             0.479167               115       18975             3
9211             0.625000               200       37000            10

      Flight Year
9210         2014
9211         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9212  Flight9213  41833  ORD-PHX              0.7         106
9213  Flight9214  42125  ORD-LGA              1.4          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9212             0.291667               275       50875             7
9213             0.583333               275       50875             5

      Flight Year
9212         2014
9213         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9214  Flight9215  42018  ORD-PHX              1.5         134
9215  Flight9216  42025  ORD-ATL             10.6         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9214             0.750000               250       46250             1
9215             0.333333               200       33000             1

      Flight Year
9214         2015
9215         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9216  Flight9217  42012  ORD-DEN              1.5          17
9217  Flight9218  42189  ORD-LAS              2.5         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9216             0.854167             300.0     55500.0             1
9217             0.375000             302.5     49912.5             7

      Flight Year
9216         2015
9217         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9218  Flight9219  41960  ORD-ATL              7.5         176
9219  Flight9220  42018  ORD-DFW              1.1          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9218             0.562500               200       33000            11
9219             0.291667               200       33000             1

      Flight Year
9218         2014
9219         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9220  Flight9221  41861  ORD-LAX              5.2          39
9221  Flight9222  41839  ORD-MCO              1.2         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9220             0.750000               385       63525             8
9221             0.333333               275       50875             7

      Flight Year
9220         2014
9221         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9222  Flight9223  42075  ORD-DEN              1.9         147
9223  Flight9224  42215  ORD-LAS              1.4         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9222             0.375000             300.0     55500.0             3
9223             0.833333             302.5     49912.5             7

      Flight Year
9222         2015
9223         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9224  Flight9225  41983  ORD-DEN              2.4         188
9225  Flight9226  42046  ORD-JFK              2.6         186

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9224               0.8125               300       49500            12
9225               0.7500               250       41250             2

      Flight Year
9224         2014
9225         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9226  Flight9227  42278  ORD-SFO              1.8         104
9227  Flight9228  41838  ORD-JFK              2.6         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9226             0.291667               375       69375            10
9227             0.333333               275       50875             7

      Flight Year
9226         2015
9227         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9228  Flight9229  42004  ORD-JFK              2.2         175
9229  Flight9230  41999  ORD-IAD              5.0          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9228             0.750000               250       41250            12
9229             0.354167               420       76020            12

      Flight Year
9228         2014
9229         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9230  Flight9231  41846  ORD-JFK              1.9         136
9231  Flight9232  41912  ORD-LAX              3.5         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9230             0.333333               275       50875             7
9231             0.833333               350       64750             9

      Flight Year
9230         2014
9231         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9232  Flight9233  41743  ORD-PHL              1.9         117
9233  Flight9234  42064  ORD-EWR              2.2         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9232             0.583333               275       50875             4
9233             0.541667               225       37125             3

      Flight Year
9232         2014
9233         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9234  Flight9235  41875  ORD-SEA              1.2          85
9235  Flight9236  42223  ORD-PHX              2.5          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9234             0.708333               385       69685             8
9235             0.333333               275       49775             8

      Flight Year
9234         2014
9235         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9236  Flight9237  41969  ORD-SFO              5.9          88
9237  Flight9238  41813  ORD-LGA              2.6         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9236             0.875000             562.5    101812.5            11
9237             0.708333             302.5     55962.5             6

      Flight Year
9236         2014
9237         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9238  Flight9239  42154  ORD-CLT              1.9         102
9239  Flight9240  42217  ORD-LAX              5.2         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9238             0.375000               125       23125             5
9239             0.833333               385       71225             8

      Flight Year
9238         2015
9239         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9240  Flight9241  42066  ORD-ATL              7.3         193
9241  Flight9242  42103  ORD-CLT              2.1          74

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9240             0.583333               200       33000             3
9241             0.416667               125       22625             4

      Flight Year
9240         2015
9241         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9242  Flight9243  41865  ORD-SFO              1.1         173
9243  Flight9244  41953  ORD-PHX              2.5          25

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9242             0.354167             412.5     68062.5             8
9243             0.395833             250.0     46250.0            11

      Flight Year
9242         2014
9243         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9244  Flight9245  41866  ORD-LGA              2.0         112
9245  Flight9246  41704  ORD-DEN              2.8          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9244             0.666667             302.5     55962.5             8
9245             0.708333             300.0     55500.0             3

      Flight Year
9244         2014
9245         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9246  Flight9247  42219  ORD-PHL              1.3         127
9247  Flight9248  41959  ORD-SFO              2.6         166

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9246             0.875000             302.5     55962.5             8
9247             0.333333             375.0     61875.0            11

      Flight Year
9246         2015
9247         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9248  Flight9249  41907  ORD-LAS              1.6          12
9249  Flight9250  42211  ORD-LAS              2.1          18

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9248             0.875000             275.0     50875.0             9
9249             0.541667             302.5     55962.5             7

      Flight Year
9248         2014
9249         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9250  Flight9251  42134  ORD-DEN              1.1         209
9251  Flight9252  42031  ORD-LGA              1.0         182

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9250             0.416667               300       49500             5
9251             0.687500               275       45375             1

      Flight Year
9250         2015
9251         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9252  Flight9253  42166  ORD-MCO              3.8          57
9253  Flight9254  42291  ORD-ATL              6.0         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9252             0.333333               275       45375             6
9253             0.770833               200       37000            10

      Flight Year
9252         2015
9253         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9254  Flight9255  41713  ORD-MCO              2.0          76
9255  Flight9256  41873  ORD-DFW              0.8         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9254             0.812500               250       45250             3
9255             0.708333               220       40700             8

      Flight Year
9254         2014
9255         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9256  Flight9257  42357  ORD-BOS              2.8          95
9257  Flight9258  42089  ORD-PHX              1.9         181

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9256             0.729167               300       55500            12
9257             0.791667               250       41250             3

      Flight Year
9256         2015
9257         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9258  Flight9259  41796  ORD-DFW              2.1          35
9259  Flight9260  41925  ORD-DTW              1.8          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9258             0.708333               220       40700             6
9259             0.625000               115       18975            10

      Flight Year
9258         2014
9259         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9260  Flight9261  42231  ORD-DEN              1.8          56
9261  Flight9262  41854  ORD-LAS              1.6          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9260             0.833333             330.0     54450.0             8
9261             0.479167             302.5     49912.5             8

      Flight Year
9260         2015
9261         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9262  Flight9263  42069  ORD-PHX              1.1          25
9263  Flight9264  41716  ORD-LAX              4.7         193

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9262             0.333333               250       46250             3
9263             0.708333               350       57750             3

      Flight Year
9262         2015
9263         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9264  Flight9265  42170  ORD-PHX              1.7         180
9265  Flight9266  42303  ORD-ATL              7.8         120

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9264             0.291667               275       45375             6
9265             0.333333               200       37000            10

      Flight Year
9264         2015
9265         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9266  Flight9267  42225  ORD-LAX              3.0         134
9267  Flight9268  42127  ORD-CLT              2.2         141

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9266             0.291667               385       71225             8
9267             0.354167               125       23125             5

      Flight Year
9266         2015
9267         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9268  Flight9269  41764  ORD-CLT              2.9         107
9269  Flight9270  42324  ORD-IAH              1.7          90

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9268             0.854167               125       23125             5
9269             0.708333               200       36200            11

      Flight Year
9268         2014
9269         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9270  Flight9271  42065  ORD-IAH              1.9         135
9271  Flight9272  41821  ORD-PHX              2.5          64

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9270             0.416667               200       37000             3
9271             0.833333               275       49775             7

      Flight Year
9270         2015
9271         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9272  Flight9273  41825  ORD-LAX                4          29
9273  Flight9274  41750  ORD-MCO                2         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9272             0.833333               385       71225             7
9273             0.312500               250       41250             4

      Flight Year
9272         2014
9273         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9274  Flight9275  42292  ORD-EWR              2.9          73
9275  Flight9276  41704  ORD-LAS              1.6         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9274             0.541667               225       40725            10
9275             0.750000               275       50875             3

      Flight Year
9274         2015
9275         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9276  Flight9277  41766  ORD-DEN              0.9         175
9277  Flight9278  41966  ORD-ATL              8.2          24

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9276             0.833333               300       49500             5
9277             0.354167               200       37000            11

      Flight Year
9276         2014
9277         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9278  Flight9279  41868  ORD-ATL             11.3          56
9279  Flight9280  41656  ORD-IAH              1.1         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9278             0.770833               220       36300             8
9279             0.354167               200       33000             1

      Flight Year
9278         2014
9279         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9280  Flight9281  41994  ORD-MCO              0.8         170
9281  Flight9282  41882  ORD-DTW              1.2          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9280             0.791667             250.0     41250.0            12
9281             0.770833             126.5     22896.5             8

      Flight Year
9280         2014
9281         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9282  Flight9283  41678  ORD-CLT              2.6          83
9283  Flight9284  41818  ORD-MIA              1.2          53

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9282             0.791667               125       22625             2
9283             0.541667               330       54450             6

      Flight Year
9282         2014
9283         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9284  Flight9285  41775  ORD-DEN              1.6          31
9285  Flight9286  42136  ORD-MCO              2.6         168

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9284             0.854167               300       55500             5
9285             0.791667               250       41250             5

      Flight Year
9284         2014
9285         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9286  Flight9287  42230  ORD-LAS              1.8         144
9287  Flight9288  42210  ORD-ATL              9.4          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9286             0.520833             302.5     55962.5             8
9287             0.312500             220.0     39820.0             7

      Flight Year
9286         2015
9287         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9288  Flight9289  42149  ORD-EWR              0.8         195
9289  Flight9290  41876  ORD-LAX              5.1          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9288             0.333333               225       37125             5
9289             0.583333               385       69685             8

      Flight Year
9288         2015
9289         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9290  Flight9291  41733  ORD-CLT              1.7         163
9291  Flight9292  41953  ORD-DTW              2.0         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9290             0.333333               125       20625             4
9291             0.416667               115       18975            11

      Flight Year
9290         2014
9291         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9292  Flight9293  41670  ORD-IAH              2.0         197
9293  Flight9294  42247  ORD-FLL              0.7         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9292             0.666667               200       33000             1
9293             0.791667               330       54450             8

      Flight Year
9292         2014
9293         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9294  Flight9295  41862  ORD-LAS              2.0         133
9295  Flight9296  42135  ORD-MSP              2.4         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9294             0.291667             302.5     55962.5             8
9295             0.750000             115.0     21275.0             5

      Flight Year
9294         2014
9295         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9296  Flight9297  42221  ORD-JFK              3.7          38
9297  Flight9298  42086  ORD-JFK              1.2          43

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9296             0.500000               275       45375             8
9297             0.791667               250       41250             3

      Flight Year
9296         2015
9297         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9298  Flight9299  42189  ORD-PHX              2.2         168
9299  Flight9300  41816  ORD-ATL              6.0         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9298             0.708333               275       45375             7
9299             0.708333               220       36300             6

      Flight Year
9298         2015
9299         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9300  Flight9301  42319  ORD-DEN              1.0         183
9301  Flight9302  41698  ORD-SEA              1.2         171

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9300             0.562500               300       49500            11
9301             0.708333               350       57750             2

      Flight Year
9300         2015
9301         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9302  Flight9303  42318  ORD-JFK              1.5         201
9303  Flight9304  42253  ORD-PHX              0.8         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9302             0.312500               250       41250            11
9303             0.416667               250       46250             9

      Flight Year
9302         2015
9303         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9304  Flight9305  42102  ORD-ATL              9.7          25
9305  Flight9306  41994  ORD-CLT              2.6          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9304             0.604167               200       37000             4
9305             0.770833               125       23125            12

      Flight Year
9304         2015
9305         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9306  Flight9307  41873  ORD-CLT              1.9         194
9307  Flight9308  42003  ORD-BOS              1.5         101

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9306             0.333333             137.5     22687.5             8
9307             0.500000             300.0     55500.0            12

      Flight Year
9306         2014
9307         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9308  Flight9309  42215  ORD-IAD              2.5          85
9309  Flight9310  41756  ORD-DCA              1.8         146

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9308             0.666667               330       59730             7
9309             0.291667              5000      925000             4

      Flight Year
9308         2015
9309         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9310  Flight9311  41995  ORD-SEA              5.2         142
9311  Flight9312  41662  ORD-JFK              2.4           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9310                 0.50               490       90650            12
9311                 0.75               250       46250             1

      Flight Year
9310         2014
9311         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9312  Flight9313  41680  ORD-PHX              1.7          43
9313  Flight9314  41805  ORD-LAS              2.0          48

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9312             0.791667             250.0     41250.0             2
9313             0.395833             302.5     49912.5             6

      Flight Year
9312         2014
9313         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9314  Flight9315  42186  ORD-PHL              2.0         169
9315  Flight9316  41999  ORD-LAS              5.1          13

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9314               0.3750             302.5     49912.5             7
9315               0.3125             385.0     71225.0            12

      Flight Year
9314         2015
9315         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9316  Flight9317  42365  ORD-LAS              3.2         132
9317  Flight9318  41968  ORD-JFK              5.3          21

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9316             0.854167               385       71225            12
9317             0.708333               375       69375            11

      Flight Year
9316         2015
9317         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9318  Flight9319  42202  ORD-ATL             12.3         173
9319  Flight9320  42171  ORD-CLT              2.9          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9318             0.375000             220.0     36300.0             7
9319             0.708333             137.5     25437.5             6

      Flight Year
9318         2015
9319         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9320  Flight9321  42172  ORD-MSP              2.2         171
9321  Flight9322  42081  ORD-SEA              1.7         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9320             0.291667             126.5     20872.5             6
9321             0.562500             350.0     57750.0             3

      Flight Year
9320         2015
9321         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9322  Flight9323  41976  ORD-ATL              7.1          75
9323  Flight9324  42271  ORD-IAD              1.4         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9322             0.833333               200       36200            12
9323             0.645833               300       55500             9

      Flight Year
9322         2014
9323         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9324  Flight9325  42200  ORD-CLT              3.4          89
9325  Flight9326  41846  ORD-DFW              2.4         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9324             0.395833             137.5     24887.5             7
9325             0.291667             220.0     40700.0             7

      Flight Year
9324         2015
9325         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9326  Flight9327  41830  ORD-SFO              2.9         144
9327  Flight9328  42318  ORD-BOS              3.1         114

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9326             0.791667             412.5     76312.5             7
9327             0.666667             300.0     55500.0            11

      Flight Year
9326         2014
9327         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9328  Flight9329  42351  ORD-LAS              0.6         157
9329  Flight9330  41870  ORD-ATL             10.1          81

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9328             0.416667               275       45375            12
9329             0.750000               220       39820             8

      Flight Year
9328         2015
9329         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9330  Flight9331  41730  ORD-DEN              3.0          53
9331  Flight9332  41873  ORD-MCO              1.6          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9330             0.770833               300       49500             4
9331             0.458333               275       45375             8

      Flight Year
9330         2014
9331         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9332  Flight9333  42182  ORD-CLT              1.2         148
9333  Flight9334  41761  ORD-MIA              1.7           8

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9332             0.791667             137.5     25437.5             6
9333             0.291667             300.0     55500.0             5

      Flight Year
9332         2015
9333         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9334  Flight9335  42090  ORD-LAS              2.3         106
9335  Flight9336  41865  ORD-DFW              2.4         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9334             0.375000               275       50875             3
9335             0.333333               220       36300             8

      Flight Year
9334         2015
9335         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9336  Flight9337  42367  ORD-LAX              3.5         119
9337  Flight9338  41689  ORD-PHX              1.9         152

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9336             0.708333               350       64750            12
9337             0.708333               250       41250             2

      Flight Year
9336         2015
9337         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9338  Flight9339  41810  ORD-JFK              2.1          30
9339  Flight9340  42016  ORD-DEN              1.4          49

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9338             0.708333               275       50875             6
9339             0.791667               300       49500             1

      Flight Year
9338         2014
9339         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9340  Flight9341  41962  ORD-JFK              1.2          33
9341  Flight9342  42266  ORD-ATL              7.5         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9340             0.375000               250       46250            11
9341             0.354167               200       33000             9

      Flight Year
9340         2014
9341         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9342  Flight9343  42324  ORD-BOS              1.2         111
9343  Flight9344  41716  ORD-LAX              2.6         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9342             0.500000               300       55500            11
9343             0.291667               350       57750             3

      Flight Year
9342         2015
9343         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9344  Flight9345  42038  ORD-CLT              1.4          23
9345  Flight9346  42221  ORD-PHL              2.2         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9344               0.8750             125.0     23125.0             2
9345               0.6875             302.5     55962.5             8

      Flight Year
9344         2015
9345         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9346  Flight9347  41918  ORD-LAX              4.9         206
9347  Flight9348  42175  ORD-LGA              2.5           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9346             0.416667             350.0     57750.0            10
9347             0.791667             302.5     55962.5             6

      Flight Year
9346         2014
9347         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9348  Flight9349  41783  ORD-PHX              0.5          17
9349  Flight9350  42232  ORD-JFK              2.7         200

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9348             0.708333               250       46250             5
9349             0.291667               275       45375             8

      Flight Year
9348         2014
9349         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9350  Flight9351  41804  ORD-LAX              4.4         101
9351  Flight9352  41878  ORD-PHL              3.3          72

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9350             0.708333             385.0     71225.0             6
9351             0.750000             302.5     54752.5             8

      Flight Year
9350         2014
9351         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9352  Flight9353  41775  ORD-DFW              2.1          56
9353  Flight9354  41930  ORD-IAH              0.0          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9352             0.708333               200       33000             5
9353             0.791667               200       37000            10

      Flight Year
9352         2014
9353         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9354  Flight9355  42222  ORD-JFK              2.6          51
9355  Flight9356  41809  ORD-DFW              1.4          95

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9354                0.375               275       45375             8
9355                0.500               220       40700             6

      Flight Year
9354         2015
9355         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9356  Flight9357  42365  ORD-IAH              6.0         130
9357  Flight9358  42069  ORD-LGA              0.9          45

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9356             0.458333               280       51800            12
9357             0.541667               275       45375             3

      Flight Year
9356         2015
9357         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9358  Flight9359  41752  ORD-FLL              1.0         176
9359  Flight9360  42253  ORD-LAS              2.3         102

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9358             0.562500               300       49500             4
9359             0.541667               275       50875             9

      Flight Year
9358         2014
9359         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9360  Flight9361  41790  ORD-EWR              1.8         187
9361  Flight9362  41790  ORD-LAX              2.1         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9360             0.291667               225       37125             5
9361             0.791667               350       57750             5

      Flight Year
9360         2014
9361         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9362  Flight9363  42334  ORD-PHX              4.5         205
9363  Flight9364  41718  ORD-DTW              1.3         170

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9362                 0.75               375       61875            11
9363                 0.75               115       18975             3

      Flight Year
9362         2015
9363         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9364  Flight9365  42238  ORD-PHX              1.3          51
9365  Flight9366  42019  ORD-MIA              2.4         145

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9364             0.375000               275       45375             8
9365             0.604167               300       55500             1

      Flight Year
9364         2015
9365         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9366  Flight9367  41849  ORD-CLT              1.5         143
9367  Flight9368  42177  ORD-EWR              0.4         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9366             0.708333             137.5     25437.5             7
9367             0.708333             247.5     45787.5             6

      Flight Year
9366         2014
9367         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9368  Flight9369  42075  ORD-DTW              1.8           2
9369  Flight9370  41879  ORD-DTW              2.5         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9368             0.750000             115.0     21275.0             3
9369             0.541667             126.5     23402.5             8

      Flight Year
9368         2015
9369         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9370  Flight9371  42306  ORD-BOS              2.2         156
9371  Flight9372  41918  ORD-CLT              1.2         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9370             0.750000               300       49500            10
9371             0.583333               125       20625            10

      Flight Year
9370         2015
9371         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9372  Flight9373  41978  ORD-DTW              2.5         116
9373  Flight9374  42135  ORD-MIA              2.4         202

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9372             0.291667               115       21275            12
9373             0.791667               300       49500             5

      Flight Year
9372         2014
9373         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9374  Flight9375  41999  ORD-EWR              5.3          90
9375  Flight9376  41965  ORD-LAS              3.2         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9374             0.708333               315       57015            12
9375             0.625000               275       45375            11

      Flight Year
9374         2014
9375         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9376  Flight9377  41759  ORD-MSP              3.0          81
9377  Flight9378  41647  ORD-MIA              2.2          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9376             0.291667               115       20815             4
9377             0.875000               300       55500             1

      Flight Year
9376         2014
9377         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9378  Flight9379  42025  ORD-MCO              2.6          27
9379  Flight9380  42140  ORD-MCO              1.5          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9378                0.625               250       46250             1
9379                0.750               250       45250             5

      Flight Year
9378         2015
9379         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9380  Flight9381  42113  ORD-MCO              2.0         179
9381  Flight9382  41813  ORD-LAS              1.7          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9380             0.812500             250.0     41250.0             4
9381             0.729167             302.5     49912.5             6

      Flight Year
9380         2015
9381         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9382  Flight9383  41868  ORD-MCO              1.7         177
9383  Flight9384  41851  ORD-MCO              1.4         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9382             0.291667               275       45375             8
9383             0.604167               275       45375             7

      Flight Year
9382         2014
9383         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9384  Flight9385  41908  ORD-LAS              1.5          66
9385  Flight9386  42273  ORD-LGA              2.4          88

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9384             0.312500               275       49775             9
9385             0.333333               275       49775             9

      Flight Year
9384         2014
9385         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9386  Flight9387  41709  ORD-LAS              3.4         208
9387  Flight9388  41648  ORD-DFW              2.1         129

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9386             0.833333               275       45375             3
9387             0.750000               200       37000             1

      Flight Year
9386         2014
9387         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9388  Flight9389  42186  ORD-SFO              2.1         206
9389  Flight9390  42297  ORD-PHX              2.9          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9388             0.500000             412.5     68062.5             7
9389             0.895833             250.0     45250.0            10

      Flight Year
9388         2015
9389         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9390  Flight9391  42084  ORD-DEN              1.5          77
9391  Flight9392  41868  ORD-EWR              2.5         199

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9390             0.833333             300.0     54300.0             3
9391             0.750000             247.5     40837.5             8

      Flight Year
9390         2015
9391         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9392  Flight9393  41693  ORD-SLC              2.7          24
9393  Flight9394  42180  ORD-MSP              2.1         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9392             0.708333             290.0     53650.0             2
9393             0.500000             126.5     20872.5             6

      Flight Year
9392         2014
9393         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9394  Flight9395  41968  ORD-ATL             17.0          60
9395  Flight9396  42246  ORD-PHX              1.7         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9394               0.7500               300       49500            11
9395               0.6875               275       50875             8

      Flight Year
9394         2014
9395         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9396  Flight9397  42362  ORD-LAX              8.3         174
9397  Flight9398  41824  ORD-DFW              1.9          86

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9396             0.291667               490       80850            12
9397             0.854167               220       39820             7

      Flight Year
9396         2015
9397         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9398  Flight9399  42288  ORD-IAH              2.5         128
9399  Flight9400  42112  ORD-SFO              1.1         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9398             0.708333               200       37000            10
9399             0.500000               375       61875             4

      Flight Year
9398         2015
9399         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9400  Flight9401  41867  ORD-BWI                2         196
9401  Flight9402  42330  ORD-SEA                1         142

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9400             0.312500               264       43560             8
9401             0.479167               350       64750            11

      Flight Year
9400         2014
9401         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9402  Flight9403  41858  ORD-DEN              2.7          53
9403  Flight9404  42332  ORD-MIA              5.9          65

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9402             0.583333               330       54450             8
9403             0.437500               450       81450            11

      Flight Year
9402         2014
9403         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9404  Flight9405  42012  ORD-PHX              2.6         208
9405  Flight9406  42111  ORD-SFO              2.3          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9404             0.583333               250       41250             1
9405             0.875000               375       69375             4

      Flight Year
9404         2015
9405         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9406  Flight9407  42270  ORD-DFW              2.0         149
9407  Flight9408  41973  ORD-LAS              5.1          28

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9406             0.750000             200.0     37000.0             9
9407             0.291667             412.5     76312.5            11

      Flight Year
9406         2015
9407         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9408  Flight9409  41851  ORD-EWR              1.6          34
9409  Flight9410  42111  ORD-MIA              3.1          10

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9408             0.666667             247.5     45787.5             7
9409             0.312500             300.0     55500.0             4

      Flight Year
9408         2014
9409         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9410  Flight9411  42002  ORD-SEA              2.0         103
9411  Flight9412  41773  ORD-LAX              4.1         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9410             0.833333               350       64750            12
9411             0.687500               350       57750             5

      Flight Year
9410         2014
9411         2014

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9412  Flight9413  41675  ORD-LAX              3.9         210
9413  Flight9414  41771  ORD-DFW              0.7          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9412             0.770833               350       57750             2
9413             0.458333               200       36200             5

      Flight Year
9412         2014
9413         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9414  Flight9415  42320  ORD-MCO              1.9         192
9415  Flight9416  42130  ORD-LGA              2.6         133

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9414             0.312500               250       41250            11
9415             0.291667               275       50875             5

      Flight Year
9414         2015
9415         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9416  Flight9417  41882  ORD-ATL              7.8         172
9417  Flight9418  42212  ORD-CLT              1.7         160

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9416             0.750000             220.0     36300.0             8
9417             0.833333             137.5     22687.5             7

      Flight Year
9416         2014
9417         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9418  Flight9419  42268  ORD-MSP              2.6         138
9419  Flight9420  42239  ORD-ATL              9.4          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9418             0.479167               115       21275             9
9419             0.833333               220       36300             8

      Flight Year
9418         2015
9419         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9420  Flight9421  42066  ORD-PHX              1.8          85
9421  Flight9422  42104  ORD-LAS              2.4         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9420             0.291667               250       45250             3
9421             0.479167               275       45375             4

      Flight Year
9420         2015
9421         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9422  Flight9423  42313  ORD-DEN              1.2          32
9423  Flight9424  42234  ORD-DFW              3.5         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9422             0.333333               300       55500            11
9423             0.770833               220       40700             8

      Flight Year
9422         2015
9423         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9424  Flight9425  41772  ORD-JFK              2.5         126
9425  Flight9426  41670  ORD-MSP              2.3         185

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9424             0.708333               250       46250             5
9425             0.604167               115       18975             1

      Flight Year
9424         2014
9425         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9426  Flight9427  41968  ORD-MIA              5.3         180
9427  Flight9428  42075  ORD-MIA              2.7          22

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9426             0.729167               450       74250            11
9427             0.833333               300       55500             3

      Flight Year
9426         2014
9427         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9428  Flight9429  41893  ORD-LAX              2.5         174
9429  Flight9430  42227  ORD-IAH              2.8          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9428             0.291667               350       57750             9
9429             0.333333               220       39820             8

      Flight Year
9428         2014
9429         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9430  Flight9431  42102  ORD-LAX              3.2          59
9431  Flight9432  42079  ORD-SFO              1.5          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9430             0.854167               350       57750             4
9431             0.729167               375       67875             3

      Flight Year
9430         2015
9431         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9432  Flight9433  42363  ORD-MSP              1.8         161
9433  Flight9434  42118  ORD-JFK              2.5         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9432             0.583333               161       26565            12
9433             0.500000               250       46250             4

      Flight Year
9432         2015
9433         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9434  Flight9435  42055  ORD-LAX              4.2          67
9435  Flight9436  42195  ORD-BOS              1.5         177

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9434             0.791667               350       63350             2
9435             0.416667               330       54450             7

      Flight Year
9434         2015
9435         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9436  Flight9437  41909  ORD-IAD              2.0           7
9437  Flight9438  41983  ORD-MIA              2.6          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9436             0.875000               300       55500             9
9437             0.708333               300       55500            12

      Flight Year
9436         2014
9437         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9438  Flight9439  41825  ORD-MSP              2.1         127
9439  Flight9440  42352  ORD-PHX              2.0         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9438             0.500000             126.5     23402.5             7
9439             0.833333             250.0     41250.0            12

      Flight Year
9438         2014
9439         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9440  Flight9441  42002  ORD-LGA              1.4         104
9441  Flight9442  41665  ORD-LAX              5.6         139

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9440             0.500000               275       50875            12
9441             0.583333               350       64750             1

      Flight Year
9440         2014
9441         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9442  Flight9443  42156  ORD-LAX                5          34
9443  Flight9444  41919  ORD-MCO                2          75

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9442             0.833333               385       71225             6
9443             0.833333               250       45250            10

      Flight Year
9442         2015
9443         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9444  Flight9445  42202  ORD-ATL              9.9         136
9445  Flight9446  42038  ORD-SEA              2.1          17

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9444             0.833333               220       40700             7
9445             0.750000               350       64750             2

      Flight Year
9444         2015
9445         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9446  Flight9447  41887  ORD-FLL              3.0         188
9447  Flight9448  41715  ORD-JFK              1.1         196

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9446             0.833333               300       49500             9
9447             0.291667               250       41250             3

      Flight Year
9446         2014
9447         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9448  Flight9449  41739  ORD-JFK              1.5          49
9449  Flight9450  41880  ORD-BOS              1.6         108

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9448             0.541667               250       41250             4
9449             0.791667               330       61050             8

      Flight Year
9448         2014
9449         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9450  Flight9451  42243  ORD-ATL             10.5         146
9451  Flight9452  42054  ORD-SEA              2.1          42

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9450             0.791667               220       40700             8
9451             0.750000               350       57750             2

      Flight Year
9450         2015
9451         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9452  Flight9453  41902  ORD-LAX              4.2         159
9453  Flight9454  42240  ORD-CLT              2.0          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9452             0.750000             350.0     57750.0             9
9453             0.583333             137.5     25437.5             8

      Flight Year
9452         2014
9453         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9454  Flight9455  42252  ORD-LAX              4.5         119
9455  Flight9456  42146  ORD-LAX              4.0         150

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9454             0.708333               350       64750             9
9455             0.895833               350       64750             5

      Flight Year
9454         2015
9455         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9456  Flight9457  41688  ORD-IAH              2.5         191
9457  Flight9458  41904  ORD-SFO              1.1         173

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9456             0.333333               200       33000             2
9457             0.458333               375       61875             9

      Flight Year
9456         2014
9457         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9458  Flight9459  42089  ORD-IAH              1.2          12
9459  Flight9460  41822  ORD-JFK              2.0         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9458             0.812500               200       37000             3
9459             0.354167               275       45375             7

      Flight Year
9458         2015
9459         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9460  Flight9461  42091  ORD-SFO              2.9         103
9461  Flight9462  41771  ORD-LAX              4.0         162

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9460             0.708333               375       69375             3
9461             0.854167               350       57750             5

      Flight Year
9460         2015
9461         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9462  Flight9463  42142  ORD-LAX              4.6         169
9463  Flight9464  42242  ORD-PHL              1.2          27

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9462             0.333333             350.0     57750.0             5
9463             0.333333             302.5     55962.5             8

      Flight Year
9462         2015
9463         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9464  Flight9465  42359  ORD-LGA              5.5         133
9465  Flight9466  41971  ORD-LAX              9.4         178

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9464             0.291667               385       71225            12
9465             0.312500               525       86625            11

      Flight Year
9464         2015
9465         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9466  Flight9467  42154  ORD-LGA              1.4          13
9467  Flight9468  41891  ORD-ATL              6.4         158

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9466             0.291667               275       50875             5
9467             0.875000               200       33000             9

      Flight Year
9466         2015
9467         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9468  Flight9469  41679  ORD-SFO              1.7          96
9469  Flight9470  41883  ORD-SEA              0.8          41

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9468             0.770833               375       69375             2
9469             0.708333               350       57750             9

      Flight Year
9468         2014
9469         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9470  Flight9471  42115  ORD-LAS              1.3           7
9471  Flight9472  42251  ORD-ATL              6.5         161

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9470             0.791667               275       50875             4
9471             0.291667               200       33000             9

      Flight Year
9470         2015
9471         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9472  Flight9473  41713  ORD-CLT              2.1         142
9473  Flight9474  41779  ORD-LAX              3.5         130

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9472             0.291667               125       23125             3
9473             0.333333               350       64750             5

      Flight Year
9472         2014
9473         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9474  Flight9475  41813  ORD-PHX              0.8         111
9475  Flight9476  42340  ORD-DEN              1.4         126

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9474             0.520833               275       50875             6
9475             0.791667               300       55500            12

      Flight Year
9474         2014
9475         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9476  Flight9477  41877  ORD-DFW              2.0          68
9477  Flight9478  42348  ORD-DFW              1.7         190

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9476             0.708333               220       39820             8
9477             0.625000               200       33000            12

      Flight Year
9476         2014
9477         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9478  Flight9479  41967  ORD-ATL             20.0         105
9479  Flight9480  41723  ORD-ATL              9.8         189

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9478             0.541667               300       55500            11
9479             0.708333               200       33000             3

      Flight Year
9478         2014
9479         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9480  Flight9481  42343  ORD-DEN              1.8          18
9481  Flight9482  41953  ORD-DFW              2.1          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9480             0.708333               300       55500            12
9481             0.500000               200       33000            11

      Flight Year
9480         2015
9481         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9482  Flight9483  41705  ORD-LGA              2.0          80
9483  Flight9484  42141  ORD-LAX              3.7          84

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9482             0.479167               275       49775             3
9483             0.708333               350       63350             5

      Flight Year
9482         2014
9483         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9484  Flight9485  41857  ORD-JFK              1.8         110
9485  Flight9486  42188  ORD-LAX              6.4         194

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9484             0.708333               275       50875             8
9485             0.645833               385       63525             7

      Flight Year
9484         2014
9485         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9486  Flight9487  42068  ORD-EWR              2.0          11
9487  Flight9488  42196  ORD-LAX              4.3         107

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9486                 0.75               225       41625             3
9487                 0.75               385       71225             7

      Flight Year
9486         2015
9487         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9488  Flight9489  42333  ORD-IAH              7.1           9
9489  Flight9490  42254  ORD-LGA              1.8          51

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9488             0.583333               300       55500            11
9489             0.333333               275       45375             9

      Flight Year
9488         2015
9489         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9490  Flight9491  42103  ORD-ATL              9.8          91
9491  Flight9492  42236  ORD-DFW              2.7         104

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9490             0.708333               200       37000             4
9491             0.791667               220       40700             8

      Flight Year
9490         2015
9491         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9492  Flight9493  42020  ORD-DEN              0.7         201
9493  Flight9494  42177  ORD-ATL              8.4          55

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9492             0.833333               300       49500             1
9493             0.291667               220       36300             6

      Flight Year
9492         2015
9493         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9494  Flight9495  42311  ORD-ATL              9.2         200
9495  Flight9496  41717  ORD-DEN              2.1          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9494             0.416667               200       33000            11
9495             0.833333               300       54300             3

      Flight Year
9494         2015
9495         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9496  Flight9497  41939  ORD-SEA              2.7         188
9497  Flight9498  42277  ORD-LAX              3.5          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9496             0.791667               350       57750            10
9497             0.583333               350       64750             9

      Flight Year
9496         2014
9497         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9498  Flight9499  42128  ORD-MCO              2.0          98
9499  Flight9500  42233  ORD-IAH              2.3          79

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9498             0.791667               250       46250             5
9499             0.729167               220       39820             8

      Flight Year
9498         2015
9499         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9500  Flight9501  42190  ORD-DFW              3.5          99
9501  Flight9502  42254  ORD-DTW              2.4         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9500             0.333333               220       40700             7
9501             0.750000               115       21275             9

      Flight Year
9500         2015
9501         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9502  Flight9503  41967  ORD-MSP              4.4         107
9503  Flight9504  42057  ORD-ATL             10.2         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9502             0.458333             172.5     31912.5            11
9503             0.750000             200.0     33000.0             2

      Flight Year
9502         2014
9503         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9504  Flight9505  42008  ORD-SFO              2.3         189
9505  Flight9506  42147  ORD-SEA              2.3          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9504             0.708333               375       61875             1
9505             0.750000               350       63350             5

      Flight Year
9504         2015
9505         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9506  Flight9507  42364  ORD-LAX              8.1         187
9507  Flight9508  42096  ORD-LAX              4.6          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9506             0.291667               490       80850            12
9507             0.291667               350       57750             4

      Flight Year
9506         2015
9507         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9508  Flight9509  41839  ORD-DFW              1.8         191
9509  Flight9510  41926  ORD-LAS              1.9         156

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9508             0.291667               220       36300             7
9509             0.333333               275       45375            10

      Flight Year
9508         2014
9509         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9510  Flight9511  41946  ORD-JFK              3.0         184
9511  Flight9512  41809  ORD-LAX              4.5         131

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9510             0.291667               250       41250            11
9511             0.875000               385       71225             6

      Flight Year
9510         2014
9511         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9512  Flight9513  42205  ORD-MCO              2.2          45
9513  Flight9514  41984  ORD-PHX              0.1          52

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9512             0.854167               275       45375             7
9513             0.708333               250       41250            12

      Flight Year
9512         2015
9513         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9514  Flight9515  42098  ORD-SEA              1.7         175
9515  Flight9516  41953  ORD-ATL              6.9         192

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9514               0.8125               350       57750             4
9515               0.7500               200       33000            11

      Flight Year
9514         2015
9515         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9516  Flight9517  41794  ORD-JFK              2.7           7
9517  Flight9518  42211  ORD-LAS              1.5           3

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9516             0.291667             275.0     50875.0             6
9517             0.500000             302.5     55962.5             7

      Flight Year
9516         2014
9517         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9518  Flight9519  41910  ORD-DEN              2.7         117
9519  Flight9520  41863  ORD-SEA              2.5         110

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9518             0.333333               300       55500             9
9519             0.625000               385       71225             8

      Flight Year
9518         2014
9519         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9520  Flight9521  41787  ORD-ATL              8.6          11
9521  Flight9522  42163  ORD-DFW              1.1         132

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9520             0.729167               200       37000             5
9521             0.729167               220       40700             6

      Flight Year
9520         2014
9521         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9522  Flight9523  42331  ORD-EWR              4.8          12
9523  Flight9524  42261  ORD-PHX              2.0          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9522             0.750000             337.5     62437.5            11
9523             0.833333             250.0     45250.0             9

      Flight Year
9522         2015
9523         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9524  Flight9525  41804  ORD-LAS              2.2         160
9525  Flight9526  42273  ORD-SLC              2.2          70

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9524             0.812500             302.5     49912.5             6
9525             0.791667             290.0     52490.0             9

      Flight Year
9524         2014
9525         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9526  Flight9527  41799  ORD-ATL              8.1         117
9527  Flight9528  41746  ORD-CLT              2.6         136

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9526             0.791667               220       40700             6
9527             0.750000               125       23125             4

      Flight Year
9526         2014
9527         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9528  Flight9529  42340  ORD-SFO              1.5         125
9529  Flight9530  42334  ORD-DEN              6.8          87

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9528             0.833333               375       69375            12
9529             0.604167               450       81450            11

      Flight Year
9528         2015
9529         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9530  Flight9531  42354  ORD-PHL              2.5          77
9531  Flight9532  42242  ORD-MCO              2.6          16

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9530             0.770833               275       49775            12
9531             0.875000               275       50875             8

      Flight Year
9530         2015
9531         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9532  Flight9533  42199  ORD-JFK              1.7          10
9533  Flight9534  41724  ORD-DFW              2.3          23

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9532             0.833333               275       50875             7
9533             0.500000               200       37000             3

      Flight Year
9532         2015
9533         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9534  Flight9535  41816  ORD-IAH              2.3         118
9535  Flight9536  41932  ORD-EWR              2.3          76

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9534             0.333333               220       40700             6
9535             0.666667               225       40725            10

      Flight Year
9534         2014
9535         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9536  Flight9537  41756  ORD-LAS              2.8          50
9537  Flight9538  41766  ORD-CLT              1.7          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9536             0.312500               275       45375             4
9537             0.291667               125       23125             5

      Flight Year
9536         2014
9537         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9538  Flight9539  41847  ORD-EWR              0.8         176
9539  Flight9540  42204  ORD-SLC              2.5         123

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9538             0.791667             247.5     40837.5             7
9539             0.604167             319.0     59015.0             7

      Flight Year
9538         2014
9539         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9540  Flight9541  41854  ORD-ATL             11.3         202
9541  Flight9542  41723  ORD-CLT              2.3          98

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9540             0.833333               220       36300             8
9541             0.333333               125       23125             3

      Flight Year
9540         2014
9541         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9542  Flight9543  41927  ORD-PHL              2.9          88
9543  Flight9544  41856  ORD-DFW              1.5         127

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9542             0.666667               275       49775            10
9543             0.708333               220       40700             8

      Flight Year
9542         2014
9543         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9544  Flight9545  41667  ORD-DTW              2.6          18
9545  Flight9546  41877  ORD-IAH              3.2         105

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9544             0.750000               115       21275             1
9545             0.333333               220       40700             8

      Flight Year
9544         2014
9545         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9546  Flight9547  41988  ORD-MIA              1.8          85
9547  Flight9548  41996  ORD-JFK              1.7          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9546             0.812500               300       54300            12
9547             0.791667               350       57750            12

      Flight Year
9546         2014
9547         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9548  Flight9549  41806  ORD-MIA              1.7         175
9549  Flight9550  42142  ORD-CLT              2.3          82

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9548             0.729167               330       54450             6
9549             0.416667               125       22625             5

      Flight Year
9548         2014
9549         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9550  Flight9551  41847  ORD-PHL              2.3         115
9551  Flight9552  42080  ORD-BWI              0.2         197

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9550             0.833333             302.5     55962.5             7
9551             0.500000             240.0     39600.0             3

      Flight Year
9550         2014
9551         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9552  Flight9553  42038  ORD-JFK              2.6          90
9553  Flight9554  42060  ORD-IAH              1.7         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9552             0.791667               250       45250             2
9553             0.354167               200       33000             2

      Flight Year
9552         2015
9553         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9554  Flight9555  42228  ORD-MIA              1.8          66
9555  Flight9556  41774  ORD-LAS              1.2          96

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9554             0.729167               330       59730             8
9555             0.791667               275       50875             5

      Flight Year
9554         2015
9555         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9556  Flight9557  41772  ORD-CLT              0.5         161
9557  Flight9558  41974  ORD-MSP              1.8          47

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9556             0.770833               125       20625             5
9557             0.833333               115       18975            12

      Flight Year
9556         2014
9557         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9558  Flight9559  41794  ORD-SEA              2.5          69
9559  Flight9560  41995  ORD-CLT              4.7         109

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9558             0.541667               385       69685             6
9559             0.312500               175       32375            12

      Flight Year
9558         2014
9559         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9560  Flight9561  42354  ORD-DFW              1.8           9
9561  Flight9562  41802  ORD-SFO              2.1         195

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9560             0.708333             200.0     37000.0            12
9561             0.458333             412.5     68062.5             6

      Flight Year
9560         2015
9561         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9562  Flight9563  42331  ORD-DFW              5.6          55
9563  Flight9564  42311  ORD-IAD              2.8         183

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9562             0.291667               300       49500            11
9563             0.625000               300       49500            11

      Flight Year
9562         2015
9563         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9564  Flight9565  41767  ORD-EWR              2.7          68
9565  Flight9566  42099  ORD-MCO              1.6          67

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9564             0.708333               225       40725             5
9565             0.750000               250       45250             4

      Flight Year
9564         2014
9565         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9566  Flight9567  42045  ORD-EWR              2.8         184
9567  Flight9568  42139  ORD-DEN              0.9         103

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9566             0.750000               225       37125             2
9567             0.854167               300       55500             5

      Flight Year
9566         2015
9567         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9568  Flight9569  42347  ORD-LAS              0.8          88
9569  Flight9570  41800  ORD-LAX              5.2          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9568             0.333333               275       49775            12
9569             0.500000               385       71225             6

      Flight Year
9568         2015
9569         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9570  Flight9571  42161  ORD-ATL             10.2          79
9571  Flight9572  41686  ORD-DFW              2.0          19

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9570             0.333333               220       39820             6
9571             0.645833               200       37000             2

      Flight Year
9570         2015
9571         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9572  Flight9573  42195  ORD-CLT              2.9         182
9573  Flight9574  41768  ORD-LGA              2.5          73

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9572             0.791667             137.5     22687.5             7
9573             0.541667             275.0     49775.0             5

      Flight Year
9572         2015
9573         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9574  Flight9575  42198  ORD-LAS              2.2         152
9575  Flight9576  41710  ORD-JFK              1.8         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9574             0.750000             302.5     49912.5             7
9575             0.791667             250.0     46250.0             3

      Flight Year
9574         2015
9575         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9576  Flight9577  42209  ORD-PHX              2.5         102
9577  Flight9578  42170  ORD-BOS              3.6          44

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9576                0.875               275       50875             7
9577                0.750               330       54450             6

      Flight Year
9576         2015
9577         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9578  Flight9579  41863  ORD-LGA              2.5          94
9579  Flight9580  41654  ORD-MCO              1.9         159

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9578                0.875             302.5     55962.5             8
9579                0.875             250.0     41250.0             1

      Flight Year
9578         2014
9579         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9580  Flight9581  42184  ORD-DFW              1.4         120
9581  Flight9582  42002  ORD-MIA              3.1         148

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9580             0.708333               220       40700             6
9581             0.708333               300       55500            12

      Flight Year
9580         2015
9581         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9582  Flight9583  41699  ORD-EWR              2.3         210
9583  Flight9584  41800  ORD-ATL             11.0          60

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9582             0.875000               225       37125             3
9583             0.854167               220       36300             6

      Flight Year
9582         2014
9583         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9584  Flight9585  42264  ORD-ATL              8.9          43
9585  Flight9586  41843  ORD-LAS              2.5           5

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9584             0.458333             200.0     33000.0             9
9585             0.750000             302.5     55962.5             7

      Flight Year
9584         2015
9585         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9586  Flight9587  42336  ORD-DFW              6.2          91
9587  Flight9588  42368  ORD-ATL              8.8         153

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9586             0.791667               300       55500            11
9587             0.333333               200       33000            12

      Flight Year
9586         2015
9587         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9588  Flight9589  42350  ORD-MCO              2.0         114
9589  Flight9590  42001  ORD-PHX              4.9           7

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9588             0.770833               250       46250            12
9589             0.708333               350       64750            12

      Flight Year
9588         2015
9589         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9590  Flight9591  42154  ORD-PHL              2.7         198
9591  Flight9592  41678  ORD-EWR              1.1          54

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9590             0.729167               275       45375             5
9591             0.791667               225       37125             2

      Flight Year
9590         2015
9591         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9592  Flight9593  41993  ORD-LGA              2.2         185
9593  Flight9594  42078  ORD-LAX              4.9          36

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9592             0.729167               275       45375            12
9593             0.812500               350       57750             3

      Flight Year
9592         2014
9593         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9594  Flight9595  42013  ORD-ATL             10.5         111
9595  Flight9596  41856  ORD-MSP              0.9          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9594             0.312500             200.0     37000.0             1
9595             0.791667             126.5     23402.5             8

      Flight Year
9594         2015
9595         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9596  Flight9597  42180  ORD-PHX              2.5          10
9597  Flight9598  42045  ORD-BOS              0.9          39

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9596             0.625000               275       50875             6
9597             0.458333               300       49500             2

      Flight Year
9596         2015
9597         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9598  Flight9599  42280  ORD-DFW              1.6          42
9599  Flight9600  41690  ORD-LAX              4.6          92

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9598             0.729167               200       33000            10
9599             0.604167               350       64750             2

      Flight Year
9598         2015
9599         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9600  Flight9601  42197  ORD-SEA              1.8         105
9601  Flight9602  41922  ORD-JFK              1.0         169

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9600             0.583333               385       71225             7
9601             0.770833               250       41250            10

      Flight Year
9600         2015
9601         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9602  Flight9603  42153  ORD-DFW              1.6          95
9603  Flight9604  42168  ORD-DFW              2.5          31

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9602             0.541667               200       37000             5
9603             0.354167               220       40700             6

      Flight Year
9602         2015
9603         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9604  Flight9605  41832  ORD-MIA              3.0         188
9605  Flight9606  42103  ORD-MCO              1.4         124

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9604             0.291667               330       54450             7
9605             0.354167               250       46250             4

      Flight Year
9604         2014
9605         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9606  Flight9607  42369  ORD-CLT              2.1         201
9607  Flight9608  42224  ORD-BWI              2.4         172

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9606             0.750000               125       20625            12
9607             0.833333               264       43560             8

      Flight Year
9606         2015
9607         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9608  Flight9609  42044  ORD-EWR              3.6         152
9609  Flight9610  41916  ORD-LAX              4.1         138

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9608             0.354167               225       37125             2
9609             0.729167               350       64750            10

      Flight Year
9608         2015
9609         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9610  Flight9611  41872  ORD-ATL             10.7          16
9611  Flight9612  41756  ORD-LAX              5.8          80

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9610             0.750000               220       40700             8
9611             0.395833               350       63350             4

      Flight Year
9610         2014
9611         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9612  Flight9613  42022  ORD-EWR              2.5          24
9613  Flight9614  42139  ORD-DFW              3.0          20

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9612             0.708333               225       41625             1
9613             0.854167               200       37000             5

      Flight Year
9612         2015
9613         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9614  Flight9615  42241  ORD-LAX              5.1         128
9615  Flight9616  42218  ORD-LGA              2.2          12

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9614             0.875000             385.0     71225.0             8
9615             0.291667             302.5     55962.5             8

      Flight Year
9614         2015
9615         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9616  Flight9617  42103  ORD-LAX              3.9           8
9617  Flight9618  42021  ORD-PHX              2.0          50

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9616             0.333333               350       64750             4
9617             0.708333               250       41250             1

      Flight Year
9616         2015
9617         2015

        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9618  Flight9619  41935  ORD-ATL              7.3         143
9619  Flight9620  41734  ORD-SFO              2.4         115

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9618             0.645833               200       37000            10
9619             0.854167               375       69375             4

      Flight Year
9618         2014
9619         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9620  Flight9621  41835  ORD-CLT              1.5          32
9621  Flight9622  42170  ORD-MIA              3.0         122

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9620             0.354167             137.5     25437.5             7
9621             0.708333             330.0     61050.0             6

      Flight Year
9620         2014
9621         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9622  Flight9623  41822  ORD-IAH              1.3         131
9623  Flight9624  41910  ORD-IAH              1.8          97

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9622             0.812500               220       40700             7
9623             0.458333               200       37000             9

      Flight Year
9622         2014
9623         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9624  Flight9625  42060  ORD-MSP              1.4          88
9625  Flight9626  41819  ORD-SFO              1.3          26

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9624             0.833333             115.0     20815.0             2
9625             0.750000             412.5     76312.5             6

      Flight Year
9624         2015
9625         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9626  Flight9627  42193  ORD-PHX              3.0           1
9627  Flight9628  41870  ORD-JFK              2.4          32

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9626             0.833333               275       50875             7
9627             0.833333               275       50875             8

      Flight Year
9626         2015
9627         2014
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9628  Flight9629  41725  ORD-SEA              1.8         146
9629  Flight9630  42054  ORD-LGA              2.6         154

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9628             0.333333               350       64750             3
9629             0.333333               275       45375             2

      Flight Year
9628         2014
9629         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9630  Flight9631  42302  ORD-BOS              1.2         155
9631  Flight9632  42146  ORD-DEN              2.8          85

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9630             0.770833               300       49500            10
9631             0.312500               300       54300             5

      Flight Year
9630         2015
9631         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9632  Flight9633  41818  ORD-DEN              1.6         185
9633  Flight9634  42361  ORD-JFK              4.3         165

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9632             0.291667               330       54450             6
9633             0.708333               350       57750            12

      Flight Year
9632         2014
9633         2015
        FlightID   Date  RouteID  Departure Delay  AircraftID  \
9634  Flight9635  42188  ORD-MIA              2.8         201
9635  Flight9636  42126  ORD-PHX              1.7         176

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
9634             0.833333               330       54450             7
9635             0.520833               250       41250             5

      Flight Year
9634         2015
9635         2015

In [19]:
df =pd.read_csv('PandasExample.csv')

In [20]:
df=df[df['AircraftID']>209]

In [22]:
df

,FlightID,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Month,Flight Year
422,Flight423,42325,ORD-DTW,2.1,210,0.791667,115.0,18975.0,11,2015
906,Flight907,42315,ORD-MCO,0.9,210,0.895833,250.0,41250.0,11,2015
938,Flight939,41792,ORD-LAS,2.5,210,0.750000,302.5,49912.5,6,2014
1211,Flight1212,41827,ORD-DEN,2.4,210,0.333333,330.0,54450.0,7,2014
1384,Flight1385,42355,ORD-LGA,1.9,210,0.812500,275.0,45375.0,12,2015
1497,Flight1498,42341,ORD-IAD,2.1,210,0.458333,300.0,49500.0,12,2015
1625,Flight1626,42163,ORD-DFW,2.6,210,0.687500,220.0,36300.0,6,2015
1675,Flight1676,41673,ORD-SEA,2.3,210,0.291667,350.0,57750.0,2,2014
1689,Flight1690,41971,ORD-JFK,6.2,210,0.875000,375.0,61875.0,11,2014
1987,Flight1988,42075,ORD-DEN,2.0,210,0.895833,300.0,49500.0,3,2015
2439,Flight2440,42005,ORD-MIA,1.2,210,0.500000,300.0,49500.0,1,2015
2554,Flight2555,41680,ORD-MSP,2.6,210,0.875000,115.0,18975.0,2,2014
2797,Flight2798,41718,ORD-LAX,4.7,210,0.312500,350.0,57750.0,3,2014
2916,Flight2917,42127,ORD-EWR,1.6,210,0.291667,225.0,37125.0,5,2015
3178,Flight3179,42216,ORD-ATL,8.3,210,0.750000,220.0,36300.0,7,2015
3317,Flight3318,42040,ORD-DEN,1.6,210,0.500000,300.0,49500.0,2,2015
3737,Flight3738,41897,ORD-MCO,2.3,210,0.291667,250.0,41250.0,9,2014
3779,Flight3780,41983,ORD-CLT,2.8,210,0.479167,125.0,20625.0,12,2014
3930,Flight3931,41970,ORD-JFK,6.3,210,0.583333,375.0,61875.0,11,2014
4299,Flight4300,42306,ORD-PHL,1.6,210,0.833333,275.0,45375.0,10,2015
4338,Flight4339,42368,ORD-LAX,4.0,210,0.791667,350.0,57750.0,12,2015
4382,Flight4383,41928,ORD-SEA,0.6,210,0.833333,350.0,57750.0,10,2014
4431,Flight4432,41893,ORD-SEA,1.5,210,0.708333,350.0,57750.0,9,2014
4488,Flight4489,41851,ORD-LAS,2.6,210,0.708333,302.5,49912.5,7,2014
4730,Flight4731,41862,ORD-SFO,1.9,210,0.375000,412.5,68062.5,8,2014
4795,Flight4796,41704,ORD-IAH,2.5,210,0.708333,200.0,33000.0,3,2014
4828,Flight4829,42074,ORD-ATL,12.2,210,0.875000,200.0,33000.0,3,2015
4946,Flight4947,42338,ORD-MIA,1.3,210,0.750000,300.0,49500.0,11,2015
5088,Flight5089,41964,ORD-PHX,-0.1,210,0.791667,250.0,41250.0,11,2014
5412,Flight5413,42044,ORD-JFK,2.6,210,0.666667,250.0,41250.0,2,2015
5723,Flight5724,42345,ORD-LAS,3.1,210,0.770833,275.0,45375.0,12,2015
6012,Flight6013,42043,ORD-IAH,2.0,210,0.750000,200.0,33000.0,2,2015
6023,Flight6024,42301,ORD-DFW,2.4,210,0.416667,200.0,33000.0,10,2015
6505,Flight6506,41892,ORD-SLC,2.6,210,0.541667,290.0,47850.0,9,2014
6682,Flight6683,42328,ORD-IAD,2.5,210,0.708333,300.0,49500.0,11,2015
6706,Flight6707,41922,ORD-CLT,1.8,210,0.708333,125.0,20625.0,10,2014
6743,Flight6744,42365,ORD-SFO,2.3,210,0.500000,525.0,86625.0,12,2015
7296,Flight7297,42107,ORD-MIA,2.0,210,0.750000,300.0,49500.0,4,2015
7342,Flight7343,41814,ORD-CLT,1.6,210,0.708333,137.5,22687.5,6,2014
7404,Flight7405,41969,ORD-JFK,1.8,210,0.750000,375.0,61875.0,11,2014
7580,Flight7581,42243,ORD-DEN,2.8,210,0.791667,330.0,54450.0,8,2015
7702,Flight7703,42287,ORD-LAX,3.7,210,0.437500,350.0,57750.0,10,2015
7747,Flight7748,42239,ORD-DEN,0.8,210,0.375000,330.0,54450.0,8,2015
7811,Flight7812,41658,ORD-DTW,1.7,210,0.687500,115.0,18975.0,1,2014
8038,Flight8039,41852,ORD-EWR,0.6,210,0.500000,247.5,40837.5,8,2014
8863,Flight8864,41735,ORD-IAH,1.8,210,0.583333,200.0,33000.0,4,2014
8953,Flight8954,41945,ORD-SEA,2.2,210,0.750000,350.0,57750.0,11,2014
9375,Flight9376,41965,ORD-LAS,3.2,210,0.625000,275.0,45375.0,11,2014
9412,Flight9413,41675,ORD-LAX,3.9,210,0.770833,350.0,57750.0,2,2014
9459,Flight9460,41822,ORD-JFK,2.0,210,0.354167,275.0,45375.0,7,2014
9582,Flight9583,41699,ORD-EWR,2.3,210,0.875000,225.0,37125.0,3,2014

In [26]:
df.pivot

<bound method DataFrame.pivot of         FlightID   Date  RouteID  Departure Delay  AircraftID  \
422    Flight423  42325  ORD-DTW              2.1         210
906    Flight907  42315  ORD-MCO              0.9         210
938    Flight939  41792  ORD-LAS              2.5         210
1211  Flight1212  41827  ORD-DEN              2.4         210
1384  Flight1385  42355  ORD-LGA              1.9         210
1497  Flight1498  42341  ORD-IAD              2.1         210
1625  Flight1626  42163  ORD-DFW              2.6         210
1675  Flight1676  41673  ORD-SEA              2.3         210
1689  Flight1690  41971  ORD-JFK              6.2         210
1987  Flight1988  42075  ORD-DEN              2.0         210
2439  Flight2440  42005  ORD-MIA              1.2         210
2554  Flight2555  41680  ORD-MSP              2.6         210
2797  Flight2798  41718  ORD-LAX              4.7         210
2916  Flight2917  42127  ORD-EWR              1.6         210
3178  Flight3179  42216  ORD-ATL              8.3         210
3317  Flight3318  42040  ORD-DEN              1.6         210
3737  Flight3738  41897  ORD-MCO              2.3         210
3779  Flight3780  41983  ORD-CLT              2.8         210
3930  Flight3931  41970  ORD-JFK              6.3         210
4299  Flight4300  42306  ORD-PHL              1.6         210
4338  Flight4339  42368  ORD-LAX              4.0         210
4382  Flight4383  41928  ORD-SEA              0.6         210
4431  Flight4432  41893  ORD-SEA              1.5         210
4488  Flight4489  41851  ORD-LAS              2.6         210
4730  Flight4731  41862  ORD-SFO              1.9         210
4795  Flight4796  41704  ORD-IAH              2.5         210
4828  Flight4829  42074  ORD-ATL             12.2         210
4946  Flight4947  42338  ORD-MIA              1.3         210
5088  Flight5089  41964  ORD-PHX             -0.1         210
5412  Flight5413  42044  ORD-JFK              2.6         210
5723  Flight5724  42345  ORD-LAS              3.1         210
6012  Flight6013  42043  ORD-IAH              2.0         210
6023  Flight6024  42301  ORD-DFW              2.4         210
6505  Flight6506  41892  ORD-SLC              2.6         210
6682  Flight6683  42328  ORD-IAD              2.5         210
6706  Flight6707  41922  ORD-CLT              1.8         210
6743  Flight6744  42365  ORD-SFO              2.3         210
7296  Flight7297  42107  ORD-MIA              2.0         210
7342  Flight7343  41814  ORD-CLT              1.6         210
7404  Flight7405  41969  ORD-JFK              1.8         210
7580  Flight7581  42243  ORD-DEN              2.8         210
7702  Flight7703  42287  ORD-LAX              3.7         210
7747  Flight7748  42239  ORD-DEN              0.8         210
7811  Flight7812  41658  ORD-DTW              1.7         210
8038  Flight8039  41852  ORD-EWR              0.6         210
8863  Flight8864  41735  ORD-IAH              1.8         210
8953  Flight8954  41945  ORD-SEA              2.2         210
9375  Flight9376  41965  ORD-LAS              3.2         210
9412  Flight9413  41675  ORD-LAX              3.9         210
9459  Flight9460  41822  ORD-JFK              2.0         210
9582  Flight9583  41699  ORD-EWR              2.3         210

      Scheduled Departure  Avg Ticket Price  Total Fare  Flight Month  \
422              0.791667             115.0     18975.0            11
906              0.895833             250.0     41250.0            11
938              0.750000             302.5     49912.5             6
1211             0.333333             330.0     54450.0             7
1384             0.812500             275.0     45375.0            12
1497             0.458333             300.0     49500.0            12
1625             0.687500             220.0     36300.0             6
1675             0.291667             350.0     57750.0             2
1689             0.875000             375.0     61875.0            11
1987             0.895833             300.0     49500.0             3
2439             0.500000             300.0     49500.0             1
2554             0.875000             115.0     18975.0             2
2797             0.312500             350.0     57750.0             3
2916             0.291667             225.0     37125.0             5
3178             0.750000             220.0     36300.0             7
3317             0.500000             300.0     49500.0             2
3737             0.291667             250.0     41250.0             9
3779             0.479167             125.0     20625.0            12
3930             0.583333             375.0     61875.0            11
4299             0.833333             275.0     45375.0            10
4338             0.791667             350.0     57750.0            12
4382             0.833333             350.0     57750.0            10
4431             0.708333             350.0     57750.0             9
4488             0.708333             302.5     49912.5             7
4730             0.375000             412.5     68062.5             8
4795             0.708333             200.0     33000.0             3
4828             0.875000             200.0     33000.0             3
4946             0.750000             300.0     49500.0            11
5088             0.791667             250.0     41250.0            11
5412             0.666667             250.0     41250.0             2
5723             0.770833             275.0     45375.0            12
6012             0.750000             200.0     33000.0             2
6023             0.416667             200.0     33000.0            10
6505             0.541667             290.0     47850.0             9
6682             0.708333             300.0     49500.0            11
6706             0.708333             125.0     20625.0            10
6743             0.500000             525.0     86625.0            12
7296             0.750000             300.0     49500.0             4
7342             0.708333             137.5     22687.5             6
7404             0.750000             375.0     61875.0            11
7580             0.791667             330.0     54450.0             8
7702             0.437500             350.0     57750.0            10
7747             0.375000             330.0     54450.0             8
7811             0.687500             115.0     18975.0             1
8038             0.500000             247.5     40837.5             8
8863             0.583333             200.0     33000.0             4
8953             0.750000             350.0     57750.0            11
9375             0.625000             275.0     45375.0            11
9412             0.770833             350.0     57750.0             2
9459             0.354167             275.0     45375.0             7
9582             0.875000             225.0     37125.0             3

      Flight Year
422          2015
906          2015
938          2014
1211         2014
1384         2015
1497         2015
1625         2015
1675         2014
1689         2014
1987         2015
2439         2015
2554         2014
2797         2014
2916         2015
3178         2015
3317         2015
3737         2014
3779         2014
3930         2014
4299         2015
4338         2015
4382         2014
4431         2014
4488         2014
4730         2014
4795         2014
4828         2015
4946         2015
5088         2014
5412         2015
5723         2015
6012         2015
6023         2015
6505         2014
6682         2015
6706         2014
6743         2015
7296         2015
7342         2014
7404         2014
7580         2015
7702         2015
7747         2015
7811         2014
8038         2014
8863         2014
8953         2014
9375         2014
9412         2014
9459         2014
9582         2014  >