In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('SFAReport.csv')

In [3]:
df

,OrderID,BrandName,EmployeeCode,AgentName,MnagerName,Branch,Zone,Year,Month,OrderDate,...,CustomerLongitude,OriginalAddress,DistributorCode,DistributorName,SKUName,SKUcode,Variance_In_Mtr,BeatPlanName,BeatPlanScheduleDay,MeetingDuration_InSec
0,7651088,Blume Nigerian Limited PULL,BNLPL0018,JAYEOBA TOSIN BOLAJI,Emmanuel Tobore,NaN,NaN,2023,June,6/22/2023,...,3.509186,"C349, Ikorodu - Sabo, Ikorodu, Lagos, Nigeria",NEOBL5670637,FRANCISCA STORES(SOPHISTIMARK),Sonia - Tomato Mix - SUP 1.1kg x 12(Pack),STM-110012SUP,NaN,Sabo tosin,Monday,0
1,7651088,Blume Nigerian Limited PULL,BNLPL0018,JAYEOBA TOSIN BOLAJI,Emmanuel Tobore,NaN,NaN,2023,June,6/22/2023,...,3.509186,"C349, Ikorodu - Sabo, Ikorodu, Lagos, Nigeria",NEOBL5670637,FRANCISCA STORES(SOPHISTIMARK),Sonia Tomato Mix - 2.2. Kg x 6 (TIN),STM-22006TIN,NaN,Sabo tosin,Monday,0
2,7651088,Blume Nigerian Limited PULL,BNLPL0018,JAYEOBA TOSIN BOLAJI,Emmanuel Tobore,NaN,NaN,2023,June,6/22/2023,...,3.509186,"C349, Ikorodu - Sabo, Ikorodu, Lagos, Nigeria",NEOBL5670637,FRANCISCA STORES(SOPHISTIMARK),Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet),STP-6550SAC,NaN,Sabo tosin,Monday,0
3,7650989,Blume Nigerian Limited PULL,BNLPL0018,JAYEOBA TOSIN BOLAJI,Emmanuel Tobore,NaN,NaN,2023,June,6/22/2023,...,3.509144,"Shop H21, Sabo, Ikorodu - Sabo, Ikorodu, Lagos...",NEOBL5670637,FRANCISCA STORES(SOPHISTIMARK),Sonia - Tomato Mix-400gm X24 ( Tin),STM-40024TIN,NaN,Sabo tosin,Monday,0
4,7650568,Blume Nigerian Limited PULL,BNLPL0018,JAYEOBA TOSIN BOLAJI,Emmanuel Tobore,NaN,NaN,2023,June,6/22/2023,...,3.502222,"Allison, Ikorodu-garage, Ikorodu, Lagos, Nigeria",NEOBL5670637,FRANCISCA STORES(SOPHISTIMARK),Sonia Tomato Mix -210gm x 48(Tin),STM-21024TIN,NaN,Allison,Saturday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8009,7427642,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,NaN,NaN,2023,June,6/1/2023,...,3.244096,"D1/ 144, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia - Tomato Mix - SUP 400gm x 24 (Pack),STM-40024SUP,NaN,NaN,NaN,0
8010,7427642,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,NaN,NaN,2023,June,6/1/2023,...,3.244096,"D1/ 144, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet),STP-6550SAC,NaN,NaN,NaN,0
8011,7427642,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,NaN,NaN,2023,June,6/1/2023,...,3.244096,"D1/ 144, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia- Tomato Mix- 65gm x50( Sachet),STM-6550SAC,NaN,NaN,NaN,0
8012,7427637,Blume Nigerian Limited PULL,BNLPL0051,AKINDELE ELIZABETH RODIAT,"Emmanuel Tobore , Evans",NaN,NaN,2023,June,6/1/2023,...,3.519429,"Odogunyan, Ikorodu, Lagos, Nigeria",NEOBL5696331,Redcliff Int'l Ltd - Ikorodu,Kivo - Good Time NDC 12 Gm x 200 (Sachets),KGT-12200SAC,NaN,NaN,NaN,0
8013,7427619,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,NaN,NaN,2023,June,6/1/2023,...,3.253050,"Mg 022 Halogen Gate, Trade Fair, Ojo, Lagos, N...",NEOBL5753822,Cycon & Company Ltd(Mr Chid),Sonia- Tomato Mix- 65gm x50( Sachet),STM-6550SAC,NaN,NaN,NaN,0

In [5]:
df.shape

(8014, 42)

In [8]:
df.columns

Index(['OrderID', 'BrandName', 'EmployeeCode', 'AgentName', 'MnagerName',
       'Branch', 'Zone', 'Year', 'Month', 'OrderDate', 'OrderTime',
       'DeliveryDate', 'DeliveryTime', 'RecoDate', 'RecoTime', 'OrderSyncdate',
       'OrderSyncTime', 'Quantity', 'Unit', 'Value', 'OrderLatitude',
       'OrderLongitude', 'OrderAddress', 'CustomerCode', 'CustomerName',
       'ContactNumber', 'CustomerStatus', 'CustomerType', 'SalesType',
       'Statename', 'CityName', 'CustomerLatitude', 'CustomerLongitude',
       'OriginalAddress', 'DistributorCode', 'DistributorName', 'SKUName',
       'SKUcode', 'Variance_In_Mtr', 'BeatPlanName', 'BeatPlanScheduleDay',
       'MeetingDuration_InSec'],
      dtype='object')

In [9]:
x = df[['EmployeeCode','SKUName','Quantity','RecoDate']]

In [10]:
x

,EmployeeCode,SKUName,Quantity,RecoDate
0,BNLPL0018,Sonia - Tomato Mix - SUP 1.1kg x 12(Pack),1,NaN
1,BNLPL0018,Sonia Tomato Mix - 2.2. Kg x 6 (TIN),1,NaN
2,BNLPL0018,Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet),3,NaN
3,BNLPL0018,Sonia - Tomato Mix-400gm X24 ( Tin),1,NaN
4,BNLPL0018,Sonia Tomato Mix -210gm x 48(Tin),1,NaN
...,...,...,...,...
8009,BNLPL0032,Sonia - Tomato Mix - SUP 400gm x 24 (Pack),1,6/1/2023
8010,BNLPL0032,Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet),2,6/1/2023
8011,BNLPL0032,Sonia- Tomato Mix- 65gm x50( Sachet),4,6/1/2023
8012,BNLPL0051,Kivo - Good Time NDC 12 Gm x 200 (Sachets),60,NaN
8013,BNLPL0032,Sonia- Tomato Mix- 65gm x50( Sachet),20,6/1/2023

In [12]:
x = df[['EmployeeCode','SKUName','Quantity','RecoDate']].values

In [13]:
x

array([['BNLPL0018', 'Sonia - Tomato Mix - SUP 1.1kg x 12(Pack)', 1, nan],
       ['BNLPL0018', 'Sonia Tomato Mix - 2.2. Kg x 6 (TIN)', 1, nan],
       ['BNLPL0018', 'Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet)',
        3, nan],
       ...,
       ['BNLPL0032', 'Sonia- Tomato Mix- 65gm x50( Sachet)', 4,
        '6/1/2023'],
       ['BNLPL0051', 'Kivo - Good Time NDC 12 Gm x 200 (Sachets)', 60,
        nan],
       ['BNLPL0032', 'Sonia- Tomato Mix- 65gm x50( Sachet)', 20,
        '6/1/2023']], dtype=object)

In [16]:
y = df[['CustomerCode']].values

In [17]:
y

array([['NEOBL8217401'],
       ['NEOBL8217401'],
       ['NEOBL8217401'],
       ...,
       ['NEOBL8471138'],
       ['NEOBL8485077'],
       ['NEOBL8470277']], dtype=object)

In [18]:
from sklearn.impute import SimpleImputer

In [19]:
imputer= SimpleImputer(missing_values=np.nan, strategy='mean')

In [22]:
imputer=imputer.fit(x[:,2:3])

In [23]:
x[:,2:3]=imputer.transform(x[:,2:3])

In [24]:
x

array([['BNLPL0018', 'Sonia - Tomato Mix - SUP 1.1kg x 12(Pack)', 1.0,
        nan],
       ['BNLPL0018', 'Sonia Tomato Mix - 2.2. Kg x 6 (TIN)', 1.0, nan],
       ['BNLPL0018', 'Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet)',
        3.0, nan],
       ...,
       ['BNLPL0032', 'Sonia- Tomato Mix- 65gm x50( Sachet)', 4.0,
        '6/1/2023'],
       ['BNLPL0051', 'Kivo - Good Time NDC 12 Gm x 200 (Sachets)', 60.0,
        nan],
       ['BNLPL0032', 'Sonia- Tomato Mix- 65gm x50( Sachet)', 20.0,
        '6/1/2023']], dtype=object)